### ISSUE TITLE
error during fetch of repo 

### ISSUE THREAD

**Issue by yellowflash07** [homuler/MediapipeUnityPlugin#1]
Hello, I am new to bazel. 
When I enter:
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 //mediapipe_api:mediapipe_c

i get an error:

ERROR: An error occurred during the fetch of repository 'com_google_mediapipe':
   Traceback (most recent call last):
        File "C:/users/ershad/_bazel_ershad/owdbunvt/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121
                patch(ctx)
        File "C:/users/ershad/_bazel_ershad/owdbunvt/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, in patch
                ctx.patch(patchfile, strip)
Not a regular file: C:/users/ershad/downloads/mediapipeunityplugin/mediapipeunityplugin-master/c/third_party/mediapipe_debug.diff

How do I fix this?

the C folder doesn't contain a mediapipe_debug.diff file either

**Comment by homuler** [comment]
Thank you for your issue.

I'm sorry, I committed code that I only used during debugging.
Now, I removed the line that caused the problem.

**Comment by yellowflash07** [comment]
Hello, the issue is fixed but now i get another error. I am using ubuntu WSL for building. 
This is the error i get when trying to build with gpu. i have included only handtracking in the build file.
ERROR: /home/ershad/.cache/bazel/_bazel_ershad/902d71d4bdcbce16c7d5b57c76d4c4f7/external/com_google_mediapipe/mediapipe/gpu/BUILD:639:11: C++ compilation of rule '@com_google_mediapipe//mediapipe/gpu:gl_simple_shaders' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 24 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_mediapipe/mediapipe/gpu/gl_simple_shaders.h:18,
                 from external/com_google_mediapipe/mediapipe/gpu/gl_simple_shaders.cc:15:
external/com_google_mediapipe/mediapipe/gpu/gl_base.h:57:10: fatal error: EGL/egl.h: No such file or directory
   57 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
Target //mediapipe_api:mediapipe_c failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by homuler** [comment]
Did you setup OpenGL ES?
https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop

**Comment by yellowflash07** [comment]
The build was successful! thank you very much. Now i can't find the generated file. Where is it?

**Comment by yellowflash07** [comment]
ok nevermind found it!
