### ISSUE TITLE
Getting multiple collaborators on this

### ISSUE THREAD

**Issue by mgyong** [homuler/MediaPipeUnityPlugin#10]
@homuler Thanks for the great effort in starting this Unity plugin for MP. I am product manager for MediaPipe and would like to chat about this effort and see how we can get more people to collaborate and potentially how Google can support this effort as well. Please join the MediaPipe slack https://mediapipe.page.link/joinslack so that we can have follow up conversation or email me at mgyong@google.com

**Comment by homuler** [comment]
@mgyong Thank you. I joined the channel as `@homuler`.
