### ISSUE TITLE
Crash on Android motorola/moto g play Mediapipe.UnsafeNativeMethods..cctor ()

### ISSUE THREAD

**Issue by LoopIssuer** [homuler/MediaPipeUnityPlugin#1001]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.12f1

### Your Host OS

Windows 11

### Target Platform

Android

### Target Device

motorola/moto g play - 2023/maui

### [Android Only] Android Build Tools and NDK Version

Build tools. 30.0.2

### Build Command

from releases

### Bug Description

We have an application released to the store. 
We use Mediapipe Unity Plugin Selfie Segmentation sample as a base for background cropping.
Received several crash reports, attached one of them for device: "motorola/moto g play - 2023/maui".
Please look in the attached logs and help us find the cause of crash.
Unfortunately - we have no contact with the users and code is obfuscated, so log is partially available.
No chance for reproduce.

### Steps to Reproduce the Bug

Unfortunately - we have no contact with the users and code is obfuscated, so log is partially available.
No chance for reproduce. 
We have two scenes with Selfie Segmentation sample used.
It seems like there was first one running ok, second crashe on Bootstrap.

### Log

```
Mediapipe.UnsafeNativeMethods..cctor () (at <00000000000000000000000000000000>:0)
Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) (at <00000000000000000000000000000000>:0)
Assets.Scripts.Presentation.VideoCall.VideoCallScene.Bootstrap+┮┮┮┭┭┭┭┮┮┮┭┭┭┮┮┭┭┮┭┮┮┮┮┮┭┭┮┮┮┭┭┮┮┭┮┮┭┭┭┭┮┮┭┮┮┮┮.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'Mediapipe.UnsafeNativeMethods' threw an exception.
Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) (at <00000000000000000000000000000000>:0)
Assets.Scripts.Presentation.VideoCall.VideoCallScene.Bootstrap+┮┮┮┭┭┭┭┮┮┮┭┭┭┮┮┭┭┮┭┮┮┮┮┮┭┭┮┮┮┭┭┮┮┭┮┮┭┭┭┭┮┮┭┮┮┮┮.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
```

**Comment by homuler** [comment]
> ```txt
> Mediapipe.UnsafeNativeMethods..cctor ()
> ```

is the following.
https://github.com/homuler/MediaPipeUnityPlugin/blob/2f3786687a4852d3a2fdd9888eb968b895c55dca/Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/UnsafeNativeMethods.cs#L27-L30

And this is all what I can say.

**Comment by homuler** [comment]
If further investigation is necessary, please provide the complete logs.
It seems to me that the most important line is omitted.

**Comment by homuler** [comment]
> ```txt
> DllNotFoundException: Unable to load DLL 'mediapipe_jni'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_jni' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "mediapipe_jni" not found
```

This is the true cause. Maybe `mediapipe_android.aar` was incompatible with the device.

**Comment by homuler** [comment]
The NDK API level is 21 and both of arm64 and armv7 are supported (note that the actual target architecture may depend on how you configure the app).
https://github.com/homuler/MediaPipeUnityPlugin/blob/2f3786687a4852d3a2fdd9888eb968b895c55dca/.github/workflows/release-packages.yml#L26

**Comment by homuler** [comment]
I am answering the cause of the reported error. I am not addressing any other causes for crashes that may occur.

> maybe there is some check in your plugin for that?

No.

**Comment by homuler** [comment]
MediaPipe itself doesn't use the Vulkan API, so even if the app were crashing due to Vulkan, it would be difficult to attribute it to this plugin without clear evidence.
