### ISSUE TITLE
Crash on start on iOS

### ISSUE THREAD

**Issue by TimmyBest** [homuler/MediaPipeUnityPlugin#1002]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.3.6f1

### Your Host OS

MacOs 13.4.1 (c) 

### Target Platform

iOS

### [iOS Only] XCode Version

Version 15.0 beta 5 (15A5209g)

### Build Command

hit run on Xcode

### Bug Description

crash on start even in an empty scene

### Steps to Reproduce the Bug

build for xcode, run

### Log

-> applicationDidFinishLaunching()
[Subsystems] Discovering subsystems at path /private/var/containers/Bundle/Application/F5A8E483-D4A5-4401-9123-5A68CD53808F/MediaPipeUnityPlugin.app/Data/UnitySubsystems
[Subsystems] No descriptors matched for  examples in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  displays in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[Subsystems] 1 'meshings' descriptors matched in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json
Initializing Metal device caps: Apple A15 GPU
Initialize engine version: 2022.3.6f1 (b9e6e7e9fa2d)
The referenced script (Unknown) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
XRGeneral Settings awakening...
UnityEngine.XR.Management.XRGeneralSettings:Awake()

**Comment by homuler** [comment]
Have you made any modifications yourself?

> crash on start even in an empty scene

If it crashes in an empty scene, wouldn't that suggest it's unrelated to this plugin?

**Comment by TimmyBest** [comment]
It works with the Unity version that the plugin is built with, so it is just that
