### ISSUE TITLE
docker build error on linux

### ISSUE THREAD

**Issue by sttsai** [homuler/MediaPipeUnityPlugin#1003]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.3.5f1

### Your Host OS

Ubuntu20.04

### Target Platform

Android

### [Linux Only] GCC/G++ and GLIBC Version

libc : 2.35
Docker version 20.10.25

### Command Sequences

docker build --build-arg UID=$(id -u) -t mediapipe_unity:latest . -f docker/linux/x86_64/Dockerfile

### Log

Sending build context to Docker daemon  12.17MB

Step 1/45 : ARG UID=1000
Step 2/45 : ARG ANDROID_SDK_BUILD_TOOLS_VERSION=30.0.3
Step 3/45 : ARG ANDROID_SDK_VERSION=30
Step 4/45 : ARG ANDROID_NDK_VERSION=21.4.7075529
Step 5/45 : FROM ubuntu:20.04 AS base
 ---> 6df894023726
Step 6/45 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 3b2e6c84b0f4
Step 7/45 : RUN apt-get update &&     apt-get install -y --no-install-recommends         apt-transport-https         build-essential         ca-certificates         clang         curl         dirmngr         git         gnupg         libegl1-mesa-dev         libgles2-mesa-dev         mesa-common-dev         nasm         npm         openjdk-11-jdk         pkg-config         software-properties-common         sudo         unzip         zip
 ---> Using cache
 ---> 4ee51a5ef6ac
Step 8/45 : FROM base AS android
 ---> 4ee51a5ef6ac
Step 9/45 : WORKDIR /tmp
 ---> Using cache
 ---> ae6e2908131a
Step 10/45 : ARG ANDROID_SDK_BUILD_TOOLS_VERSION
 ---> Using cache
 ---> 39dbdcc3c94e
Step 11/45 : ARG ANDROID_SDK_VERSION
 ---> Using cache
 ---> 46680ae91adb
Step 12/45 : ARG ANDROID_NDK_VERSION
 ---> Using cache
 ---> 1ae6851e88cf
Step 13/45 : ENV COMMANDLINETOOLS_ZIP commandlinetools.zip
 ---> Using cache
 ---> fbb3ad81584c
Step 14/45 : ENV COMMANDLINETOOLS_SHA256 124f2d5115eee365df6cf3228ffbca6fc3911d16f8025bebd5b1c6e2fcfa7faf
 ---> Using cache
 ---> ace0126347a9
Step 15/45 : RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o ${COMMANDLINETOOLS_ZIP} &&     (test "$(sha256sum ${COMMANDLINETOOLS_ZIP})" = "${COMMANDLINETOOLS_SHA256}  ${COMMANDLINETOOLS_ZIP}" || { echo 'Checksum Failed'; exit 1; }) &&     unzip ${COMMANDLINETOOLS_ZIP} -d /opt/android
 ---> Using cache
 ---> 25029ae72702
Step 16/45 : RUN  yes | /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --licenses
 ---> Using cache
 ---> 75fdcce4da78
Step 17/45 : RUN /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --install         "platforms;android-${ANDROID_SDK_VERSION}"         "build-tools;${ANDROID_SDK_BUILD_TOOLS_VERSION}"         "ndk;${ANDROID_NDK_VERSION}" &&     rm ${COMMANDLINETOOLS_ZIP}
 ---> Using cache
 ---> 225a7a7513f3
Step 18/45 : FROM base AS builder
 ---> 4ee51a5ef6ac
Step 19/45 : ARG UID
 ---> Using cache
 ---> 2ffe4713b13a
Step 20/45 : WORKDIR /tmp
 ---> Using cache
 ---> 27160b20c330
Step 21/45 : COPY --from=android /opt/android /opt/android
 ---> Using cache
 ---> a2996d055bc1
Step 22/45 : RUN apt-get install -y --no-install-recommends python3.9 python3.9-dev python3.9-distutils &&     curl -L https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&     python3.9 get-pip.py &&     update-alternatives --install /usr/local/bin/python python /usr/bin/python3.9 10 &&     update-alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3.9 10
 ---> Using cache
 ---> f6814fc5d1e7
Step 23/45 : RUN gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&     echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list &&     apt update
 ---> Using cache
 ---> b80a10b56d13
Step 24/45 : RUN apt-get install -y --no-install-recommends mono-complete &&     curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe &&     bash -c 'echo -e "#!/bin/bash\nmono /usr/local/bin/nuget.exe \$@" | tee -a /usr/local/bin/nuget' &&     chmod +x /usr/local/bin/nuget
 ---> Using cache
 ---> f95726320d5b
Step 25/45 : RUN apt-get install -y --no-install-recommends npm &&     npm install -g @bazel/bazelisk
 ---> Using cache
 ---> 7b55b7a41c1c
Step 26/45 : RUN bash -c 'echo -e "%wheel ALL=(ALL) NOPASSWD: ALL\n" > /etc/sudoers.d/01_wheel'
 ---> Using cache
 ---> d4d3d476426e
Step 27/45 : RUN addgroup wheel && useradd -u ${UID} -m mediapipe && usermod -aG wheel mediapipe
 ---> Using cache
 ---> ffbd943a833d
Step 28/45 : USER mediapipe
 ---> Using cache
 ---> 9c60288a123c
Step 29/45 : WORKDIR /home/mediapipe
 ---> Using cache
 ---> dd6da7365af2
Step 30/45 : ENV NPM_PREFIX /home/mediapipe/.npm-packages
 ---> Using cache
 ---> 8eb95aa0487a
Step 31/45 : ENV PATH ${NPM_PREFIX}/bin:/home/mediapipe/.local/bin:${PATH}
 ---> Using cache
 ---> 5e82bcfb5c01
Step 32/45 : RUN pip install --no-cache-dir --user numpy
 ---> Running in c721836d5a21
Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/69/1f/c95b1108a9972a52d7b1b63ed8ca70466b59b8c1811bd121f1e667cc45d8/numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Downloading numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 11.5 MB/s eta 0:00:00
Installing collected packages: numpy
 [91mERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/mediapipe/.local'
Check the permissions.

 [0m

**Comment by homuler** [comment]
At the very least, [it is functioning](https://github.com/homuler/MediaPipeUnityPlugin/actions/runs/5878475211/job/15940636428) with GitHub Actions, so if necessary, please fork this repository and use the Package workflow to build.
