### ISSUE TITLE
fbx animate by Mediapipeunityplugin

### ISSUE THREAD

**Issue by semi8583** [homuler/MediaPipeUnityPlugin#1004]
### Description

My fbx model has 
[body bones.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/12364937/body.bones.txt) include mixamo rig

how may my character animate by follow mediapipe that your project

could you help me please?

**Comment by homuler** [comment]
For inquiries about using MediaPipe, please consult the MediaPipe community.
If you're unsure about how to use the plugin's API, feel free to provide a more specific question, and I'll be able to assist you.
