### ISSUE TITLE
Is it posiible to use multiple solutions in a scene?

### ISSUE THREAD

**Issue by chris312319** [homuler/MediaPipeUnityPlugin#1006]
### Description

I want to use FaceMesh, PoseTracking and HandTracking in the same scene.
But when I put them in a same scene and play, editor crash without any report.
Is there anyone can teach me how to do that?

**Comment by homuler** [comment]
While it is possible to run 3 CalculatorGraphs, it's usually better to operate with a single CalculatorGraph (you can write such a CalculatorGraphConfig). Was there an issue with using Holistic?

**Comment by chris312319** [comment]
Thank you! Holistic is what I am looking for!

**Comment by chris312319** [comment]
> While it is possible to run 3 CalculatorGraphs, it's usually better to operate with a single CalculatorGraph (you can write such a CalculatorGraphConfig). Was there an issue with using Holistic?

Thank you! Holistic is what I am looking for!
