### ISSUE TITLE
MediapipeException: mediapipe aborted

### ISSUE THREAD

**Issue by hazzab** [homuler/MediaPipeUnityPlugin#101]
Hi. This is a truly awesome project - thanks you so much :)

It is running fine in the Unity Editor on MacOS but I'm having trouble getting iOS to work with the 'DesktopDemo' scene on 0.5.1( renamed iosMpipe12 in the log below ).  I've built the asset bundles & they seem to load okay.

Sorry if I've a simple mistake - any help you could give would be really appreciated. 

****

2021-03-23 18:25:12.443825+0000 iosMpipe12[1497:367881] Built from '2019.4/release' branch, Version '2019.4.18f1 (3310a4d4f880)', Build type 'Development', Scripting Backend 'il2cpp'
-> applicationDidFinishLaunching()
PlayerConnection initialized from /private/var/containers/Bundle/Application/A0B1A755-5455-4163-8018-1E5F96B9FC77/iosMpipe12.app/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55000
Multi-casting "[IP] 10.54.70.200 [Port] 55000 [Flags] 2 [Guid] 960316513 [EditorId] 3276023597 [Version] 1048832 [Id] iPhonePlayer(Harrys-iPhone):56000 [Debug] 0 [PackageName] iPhonePlayer [ProjectName] iosMpipe12" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55000]
PlayerConnection already initialized - listening to [0.0.0.0:55000]
2021-03-23 18:25:12.520528+0000 iosMpipe12[1497:367881] Metal GPU Frame Capture Enabled
2021-03-23 18:25:12.520659+0000 iosMpipe12[1497:367881] Metal API Validation Enabled
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A12 GPU
Initialize engine version: 2019.4.18f1 (3310a4d4f880)
**2021-03-23 18:25:12.874181+0000 iosMpipe12[1497:368230] fopen failed for data file: errno = 2 (No such file or directory)
2021-03-23 18:25:12.874232+0000 iosMpipe12[1497:368230] Errors found! Invalidating cache...
2021-03-23 18:25:14.244045+0000 iosMpipe12[1497:368230] fopen failed for data file: errno = 2 (No such file or directory)
2021-03-23 18:25:14.244304+0000 iosMpipe12[1497:368230] Errors found! Invalidating cache...**
-> applicationWillResignActive()
2021-03-23 18:25:14.447167+0000 iosMpipe12[1497:367881] Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x159faff50>.
-> applicationDidBecomeActive()
UnloadTime: 2.399542 ms
[SRDebugger] No SRDebugger settings object found - using defaults. (Open SRDebugger Settings window in the Unity Editor to create settings file)
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
SRDebugger.Settings:GetOrCreateInstance()
SRDebugger.Settings:get_Instance()
SRDebugger.AutoInitialize:OnLoadBeforeScene()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Graph Changed: Face Detection
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
GraphSelectorController:OnValueChanged(Dropdown)
GraphSelectorController:InitializeOptions()
GraphSelectorController:Start()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-> applicationWillResignActive()
-> applicationDidBecomeActive()
WebCamDevice Changed: Back Camera
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
WebCamDeviceSelectorController:OnValueChanged(Dropdown)
WebCamDeviceSelectorController:ResetOptions(WebCamDevice[])
<Start>d__2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

WebCamTexture Graphics Format: B8G8R8A8_UNorm
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
<ResetScreen>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
SceneDirector:ResetCamera(Nullable`1)
SceneDirector:ChangeWebCamDevice(Nullable`1)
WebCamDeviceSelectorController:OnValueChanged(Dropdown)
WebCamDeviceSelectorController:ResetOptions(WebCamDevice[])
<Start>d__2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
AssetBundleLoader:PrepareAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, Boolean)
FaceDetectionGraph:PrepareDependentAssets()
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Mediapipe.AssetBundleManager:LoadAssetBundle()
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
AssetBundleLoader:PrepareAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, Boolean)
FaceDetectionGraph:PrepareDependentAssets()
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

face_detection_front is saved to /var/mobile/Containers/Data/Application/77B08263-353B-464F-9BCE-9D206B6E7488/Documents/Cache/face_detection_front.bytes (length=229032)
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Mediapipe.AssetBundleManager:WriteCacheFile(TextAsset, String, Boolean)
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
AssetBundleLoader:PrepareAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, Boolean)
FaceDetectionGraph:PrepareDependentAssets()
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

hwd4 in AssetBundleLoader PrepareAsset face_detection_front.bytes key:face_detection_front.bytes
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AssetBundleLoader:PrepareAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, String, Boolean)
DemoGraph:PrepareDependentAsset(String, Boolean)
FaceDetectionGraph:PrepareDependentAssets()
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Loaded dependent assets
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**WARNING: Logging before InitGoogleLogging() is written to STDERR
F20210323 18:25:58.418504 47462592 calculator_graph.cc:124] Non-OK-status: Initialize(config) status: NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: FaceDetectionFrontCpu; Unable to find Calculator "FaceDetectionFrontCpu"
*** Check failure stack trace: *****

**Comment by homuler** [comment]
Maybe this is the same issue as https://github.com/homuler/MediaPipeUnityPlugin/issues/87 .

**Comment by hazzab** [comment]
Yes that works ! Thanks you so much.
