### ISSUE TITLE
Build on android but nor work

### ISSUE THREAD

**Issue by chris312319** [homuler/MediaPipeUnityPlugin#1010]
### Description

In Holistic scene, camera isn't work automatically when I open the app, I have to open the setting panel and change the source to image or video, then change back to caemra source, and after that I can see the camera's content.
Another issue is that after the above, solution doesn't work, is there something need to be set ?

**Comment by homuler** [comment]
Please build with Development build enabled and read the log.
If it doesn't solve the issue, then reopen using [this form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abug&projects=&template=bug_report.yml).
