### ISSUE TITLE
Blendshape keys are not correct

### ISSUE THREAD

**Issue by DeltaMatan7** [homuler/MediaPipeUnityPlugin#1011]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.25

### Your Host OS

Windows 10

### Target Platform

UnityEditor, Android

### Description

Hello, I'm working on connecting MediaPipe with Ready Player.me avatars, and I've noticed that the blendshape values I receive don't match the actual blendshapes. They seem mixed up. For example, the "cheekPuff" blend shape only responds when I close my right eye.

Is there a way to change the output values for all blend shapes? Is there an easier way to detect incorrect blendshapes?

**Comment by homuler** [comment]
Can it be the same issue as https://github.com/google/mediapipe/issues/4436 ?

**Comment by DeltaMatan7** [comment]
yes, almost same, but there are much more issues.
I'm currently working on untangling the issue, however, it's very difficult to determine which parts of the face affect specific blend shapes. Can you tell me how to more easily connect the appropriate blend shapes with facial movements (For example, when I select a specific blend shape, I would like to see which points on the face mesh are included in the calculation of the blend shape value.)?
Then I'll send you the exact indexes for each blend shape (or any other data to help solve issue).
