### ISSUE TITLE
Reason: image not found Error In IOS #bug

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#102]
app crash with image not found. Is this known issue?

**Comment by emreboyraz0** [comment]
also give 'Library not loaded: @rpath/MediaPipeUnity.framework/MediaPipeUnity' Error.

I run python build.py build --ios arm64 -v
Android apk is okey. But Ios crash

**Comment by samtremblo** [comment]
Hello, I'm having the same issue.
Did you fix it?

**Comment by samtremblo** [comment]
Fixed it.

For those having the same problem: make sure you have already installed the the assetbundle browser from the package manager and then built the main assetbundle. Make sure it's copied to StreamingAssets. After that my build was all good. Cheers.

**Comment by ZichunYuan** [comment]
> Fixed it.
> 
> For those having the same problem: first make sure you got the .framework linked to your xcode and then make sure you have already installed the the assetbundle browser from the package manager and then built the main assetbundle. Make sure it's copied to StreamingAssets. After that my build was all good. Cheers.

I am having the same problem. I am not sure how to build the main asset bundle, like what should be included in it? Could you please elaborate a little more?
