### ISSUE TITLE
Unable to find Calculator 'LandmarksToTensorCalculator'

### ISSUE THREAD

**Issue by sttsai** [homuler/MediaPipeUnityPlugin#1023]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.3.5f1

### Your Host OS

macOS Ventura 13.4.1

### Target Platform

Mac Standalone

### [iOS Only] XCode Version

Version 14.3.1

### Command Sequences

Hi:
I added the following to the document in mediapipe_api/BUILD:
cc_library(
    name = "calculators",
    deps = [
        "@com_google_mediapipe//mediapipe/calculators/core:pass_through_calculator",
        "@com_google_mediapipe//mediapipe/calculators/core:packet_presence_calculator",
        "@com_google_mediapipe//mediapipe/calculators/core:flow_limiter_calculator",
        "@com_google_mediapipe//mediapipe/calculators/image:image_transformation_calculator",
        **"@com_google_mediapipe//mediapipe/calculators/tensor:landmarks_to_tensor_calculator",
        "@com_google_mediapipe//mediapipe/calculators/tensor:tensors_to_classification_calculator",**
    ] + select({
        ...
    })
)

And compiled the following versions:
Windows (mediapipe_c.dll)
Android (mediapipe_android.aar)
MacOS (libmediapipe_c.dylib)

Afterward, I added the following node to the Graph file:
node {
    **calculator: "LandmarksToTensorCalculator"**
    input_stream: "NORM_LANDMARKS:pose_landmarks"
    input_stream: "IMAGE_SIZE:image_size"
    output_stream: "TENSORS:tensors"    
}

However, the same code works correctly on Windows and Android but gives an error message on macOS: **"Unable to find Calculator 'LandmarksToTensorCalculator'."**

Additionally, I forked the project and used GitHub Action to build the package, and the macOS version also encountered the same issue.

May I ask what is the reason that macOS cannot incorporate the tensor:landmarks_to_tensor_calculator into the program?

### Log

MPHolisticTrackingSolution: Mediapipe.MediaPipeException: NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: LandmarksToTensorCalculator; **Unable to find Calculator "LandmarksToTensorCalculator"**
  at Mediapipe.Status.AssertOk () [0x00014] in /Users/sttsai/Proejct/MediaPipeTest1/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:149 
  at MyTracking.MyGraphRunner+<Initialize>d__42.MoveNext () [0x00078]

**Comment by homuler** [comment]
> Additionally, I forked the project and used GitHub Action to build the package, and the macOS version also encountered the same issue.

Has the build succeeded with these changes applied? (I couldn't find such a build in [your public fork](https://github.com/sttsai/MediaPipeUnityPlugin/actions))

**Comment by sttsai** [comment]
Hi
This fork and branch are over [here](https://github.com/sttsai/MediaPipeUnityPlugin/tree/LandmarksToTensorCalculator) and also you can see the [build package](https://github.com/sttsai/MediaPipeUnityPlugin/actions/runs/6059101040). In that build  actions the macOS-build was successful. otherwise, I built the Windows and Android versions on my computer(Docker) it was also successful.

**Comment by homuler** [comment]
> In that build actions the macOS-build was successful.

How did you get the artifact (= `libmediapipe_c.dylib`)?
Since the workflow is failing as a whole, it's not evident that you're testing with the correctly built library.

**Comment by sttsai** [comment]
Yes, I also noticed the issue with the lack of artifact generation. I suspect it's due to my limited GitHub space.

However, you can take a look at the [initial use case](https://github.com/sttsai/MediaPipeUnityPlugin/actions/runs/5951157342) when I first used GitHub Actions. It also had some failures, but some artifacts were generated(so I got the libmediapipe_c.dylib). However, the build above(2 weeks ago) does not include the tests I recently conducted.

I freed up some unused space, [re-initiated the build](https://github.com/sttsai/MediaPipeUnityPlugin/actions/runs/6061777693), and hope it will generate the artifacts successfully.  After it completes, I'll check for the generation of artifacts and then get back to you.

**Comment by sttsai** [comment]
By the way, previously, I used a Mac desktop (M2) to build the project to obtain libmediapipe_c.dylib. Similarly, for Windows (mediapipe_c.dll) and Android (mediapipe_android.aar), I used Docker Desktop on a Windows 11 desktop to complete the builds.

**Comment by homuler** [comment]
> By the way, previously, I used a Mac desktop (M2) to build the project to obtain libmediapipe_c.dylib

Actually, I suspect that you may not be building it correctly on macOS.

> Yes, I also noticed the issue with the lack of artifact generation. I suspect it's due to my limited GitHub space.

That's just because your branch is based on the older commit.
Please pull the latest commit and try it again. The workflow will be much more stable.

> It also had some failures, but some artifacts were generated(so I got the libmediapipe_c.dylib). 

If you're using this `libmediapipe_c.dylib`, note that this is built on the master branch.

**Comment by sttsai** [comment]
Mmm....this morning's build also failed and didn't produce any artifacts.

Give me a few days, I'll pull the latest commit and prepare a complete example to demo the issues. In this example, I'll use GitHub Actions to build all versions and test if the same issues occur.

Thank you for your explanations over the past few days.

**Comment by sttsai** [comment]
By the way, you can take a look at the [latest build from your repo](https://github.com/homuler/MediaPipeUnityPlugin/actions/runs/6024553821); it also failed, but some platforms did produce artifacts. 

So, I obtained libmediapipe_c.dylib from my previous failed builds because I believe the failures on other platforms wouldn't affect the libmediapipe_c.dylib for macOS

**Comment by homuler** [comment]
> it also failed, but some platforms did produce artifacts.

It was unstable because #1015 had not yet merged into the master branch (I hope the next scheduled build will be more stable).
The reason why it still produces artifacts is it contains [this commit](https://github.com/homuler/MediaPipeUnityPlugin/commit/40af18637a786e9a91f1c98eb1fc627d62072400#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52L298).
Note that your branch (it seems to be deleted) did not contain that commit, so it did not produce artifacts when it failed.

> So, I obtained libmediapipe_c.dylib from my previous failed builds because I believe the failures on other platforms wouldn't affect the libmediapipe_c.dylib for macOS

Yes, but note that the workflow was run against the **master** branch, which does not contain your change, so it does not contain `LandmarksToTensorCalculator`.

**Comment by sttsai-xrspace** [comment]
Hi homuler:
I created a new branch from commit #1022 to write a demo for this issue and use the build package from your repo. 

After testing, this issue no longer appears on the latest master branch. The calculators used in the example can all be called correctly in the current package.

Thanks for your reply.

**Comment by homuler** [comment]
@sttsai if it's resolved, please close this issue.
