### ISSUE TITLE
Access mask array without workaround 

### ISSUE THREAD

**Issue by Elepaia** [homuler/MediaPipeUnityPlugin#1024]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18.f1

### Your Host OS

MacOS Ventura 13.5

### Target Platform

Mac Standalone

### Description

Hello, 
I want to access some data of the mask without having to display the mask on the screen. I only need an array of numbers between 0 and 1, essentially what is in **_maskArray** in **MaskAnnotationController**. I want to see, what is the mask (1) and what is outside (0).

The **SegmentationMask** I get from the **OutputStream** is of type ImageFrame. Unfortunately, there is no _maskArray included.

My Workaround:
Right now I have a Canvas with a Screen and AnnotationLayer, plus MaskAnnotationController and MaskAnnotation in my Scene. Just like in the tutorial scene. All of this only to access _maskArray in MaskAnnotationController. Is there another way to access the mask data without having to include all these unnecessary elements in the scene? 

I added a Getter called CurrentMaskArray in MaskAnnotationController to access _maskArray. I suppose there is a better way to get the same information.
 ```
//Getter, added my me
public float[] CurrentMaskArray { get; private set; }
.....

protected override void SyncNow()
    {
      isStale = false;
      
      //added by me. 
      CurrentMaskArray = _maskArray;
        
      annotation.Draw(_currentTarget == null ? null : _maskArray, _maskWidth, _maskHeight);
    }
```

Thanks for help!

**Comment by homuler** [comment]
You can read the data by calling `TryReadChannelNormalized`.
`MaskAnnotationController` also calls it internally.
https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotationController.cs#L43

https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Extension/ImageFrameExtension.cs#L250-L273

**Comment by Elepaia** [comment]
Ok, that‘s a way to get 0 and 1 instead of numbers between 0 and 1.  Thank you!

But my main problem is: I want to know how to get this information **without** canvas, screen, controller and annotation in my scene. Is there perhaps a way to get these data straight from the outputStream?

**Comment by homuler** [comment]
> Ok, that‘s a way to get 0 and 1 instead of numbers between 0 and 1.

> I want to know how to get this information **without** canvas, screen, controller and annotation in my scene. Is there perhaps a way to get these data straight from the outputStream?

Can't you get the information you need with this code?
`TryReadChannelNormalized` is a method of `ImageFrame`, so you don't need canvas, screen, controller or annotation.

**Comment by Elepaia** [comment]
I'm sorry, that was a misunderstanding. You're right, it works just as you had written. Thank you very much!
