### ISSUE TITLE
Hand tracking to Avatar

### ISSUE THREAD

**Issue by jefflim69** [homuler/MediaPipeUnityPlugin#1025]
### Description

I'm trying to apply Hand and Finger tracking to an avatar.
Is it correct to get the value from HandLandmarkerResult?
Are there any samples related to this?

**Comment by homuler** [comment]
I'm so sorry, I overlooked this issue.

> Is it correct to get the value from HandLandmarkerResult?

Yes.

> Are there any samples related to this?

Here is the sample code.
https://github.com/homuler/MediaPipeUnityPlugin/blob/74c1c8500afeca379ea6ba6a5cb9e9d1b08f1aa4/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Hand%20Landmark%20Detection/HandLandmarkerRunner.cs
