### ISSUE TITLE
Building for Magic Leap 2 (x86_64)

### ISSUE THREAD

**Issue by matthewc84** [homuler/MediaPipeUnityPlugin#1026]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.2.19

### Your Host OS

Windows 11

### Target Platform

Android

### [Android Only] Android Build Tools and NDK Version

Build Tool: 30.0.3
NDK: 21.4.7075529

### Command Sequences

I am building the plugins with a Linux Docker, using the commands and outputs below. After building the plugin, I then open the root folder as a Unity project as instructed and export it, and import it into my project. Everything works fine in the editor, but the errors below are created when I deploy my program.

![0981a40fec9058898f09ba64c26f92456240903d](https://github.com/homuler/MediaPipeUnityPlugin/assets/83882325/e2a146e3-1988-41e2-9a78-bd43c60991c6)

### Log

mediapipe@38c1c9bf10fd:~$ python build.py build --android fat --opencv cmake --android_ndk_api_level 29 -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="29" --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Build options --action_env, --copt, --cpu, and 5 more have changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (99 packages loaded, 1050 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 1.917s, Critical Path: 0.41s
INFO: 147 processes: 1 internal, 146 linux-sandbox.
INFO: Build completed successfully, 147 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Runtime/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  /home/mediapipe/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /home/mediapipe/packages.config are already installed.
DEBUG (build.py): Copying '.nuget/System.Memory.4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Runtime/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Copying '.nuget/System.Buffers.4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Runtime/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget/Google.Protobuf.3.20.0/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Runtime/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/System.Runtime.CompilerServices.Unsafe.4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Runtime/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Copying '.nuget/packages/system.memory/4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Runtime/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Copying '.nuget/packages/google.protobuf/3.20.0/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Runtime/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/packages/system.runtime.compilerservices.unsafe/4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Runtime/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Copying '.nuget/packages/system.buffers/4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Runtime/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Protobuf/System.Buffers.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="29" --verbose_failures //mediapipe_api:mediapipe_assets`
INFO: Analyzed target //mediapipe_api:mediapipe_assets (28 packages loaded, 97 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 3.525s, Critical Path: 3.24s
INFO: 21 processes: 1 internal, 20 linux-sandbox.
INFO: Build completed successfully, 21 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'build/PackageResources/MediaPipe'...
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'Assets/StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Android...
DEBUG (build.py): Running `bazel build -c opt --action_env ANDROID_NDK_API_LEVEL="29" --verbose_failures --config=android_fat --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android`
INFO: Build options --copt, --cpu, --crosstool_top, and 4 more have changed, discarding analysis cache.
WARNING: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/com_google_mediapipe/mediapipe/framework/BUILD:56:24: in cc_library rule @com_google_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android (157 packages loaded, 20500 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule @org_tensorflow//tensorflow/lite/acceleration/configuration:configuration_schema:
When you use --proto, that you should check for conformity yourself, using the existing --conform
INFO: From Executing genrule @org_tensorflow//tensorflow/lite/acceleration/configuration:configuration_schema:
When you use --proto, that you should check for conformity yourself, using the existing --conform
INFO: From Executing genrule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android:
Archive:  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/linux-sandbox/15927/execroot/mediapipe_api/bazel-out/arm64-v8a-opt/bin/mediapipe_api/java/com/github/homuler/mediapipe/mediapipe_android_dummy_app_unsigned.apk
   creating: lib/arm64-v8a/
  inflating: lib/arm64-v8a/libopencv_java3.so
  inflating: lib/arm64-v8a/libmediapipe_jni.so
   creating: lib/armeabi-v7a/
  inflating: lib/armeabi-v7a/libopencv_java3.so
  inflating: lib/armeabi-v7a/libmediapipe_jni.so
  adding: jni/arm64-v8a/libmediapipe_jni.so (deflated 74%)
  adding: jni/arm64-v8a/libopencv_java3.so (deflated 59%)
  adding: jni/armeabi-v7a/libmediapipe_jni.so (deflated 73%)
  adding: jni/armeabi-v7a/libopencv_java3.so (deflated 50%)
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android up-to-date:
  bazel-bin/mediapipe_api/java/com/github/homuler/mediapipe/mediapipe_android.aar
INFO: Elapsed time: 1219.983s, Critical Path: 339.88s
INFO: 4944 processes: 11 internal, 4930 linux-sandbox, 3 worker.
INFO: Build completed successfully, 4944 total actions
DEBUG (build.py): Copying 'bazel-bin/mediapipe_api/java/com/github/homuler/mediapipe/mediapipe_android.aar' to 'build/Runtime/Plugins/Android/mediapipe_android.aar'...
DEBUG (build.py): Changing the mode of 'build/Runtime/Plugins/Android/mediapipe_android.aar'...
INFO (build.py): Built native libraries for Android
INFO (build.py): Installing built resources...
DEBUG (build.py): Copying 'build' to 'Packages/com.github.homuler.mediapipe' recursively...
DEBUG (build.py): Running `cp -r build/* Packages/com.github.homuler.mediapipe`
INFO (build.py): Installed
mediapipe@38c1c9bf10fd:~$

### Additional Context

I am building the plugin for the Magic Leap 2 (x86_64) using the "fat" option on the build command, as shown in the log. When it is built and imported, the device cannot find the plugin files "mediapipe_ini" specifically (see error screenshot). I posted on the [Magic Leap Developer Forum](https://forum.magicleap.cloud/t/mediapipe-on-ml2/2544) and was told a certain file structure is not being created. Can I build this plugin specifically for x86_64? Does the response from ML2's devs make any sense to you?

![0981a40fec9058898f09ba64c26f92456240903d](https://github.com/homuler/MediaPipeUnityPlugin/assets/83882325/849d6783-91c8-4d76-8e40-dc4560ba0744)

***Edit. One additional comment. After talking some more to the ML2 devs, I changed the .aar file build from the "python build.py build --android fat --opencv cmake --android_ndk_api_level 26 -vv" command to explore the file system. There are no x86 or x86_64 directories created (see the inset below).  Is this an error? It should be possible as in [here](https://bazel.build/docs/android-ndk#configuring-target-abi)

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/83882325/124d701b-510c-43fa-a1b5-6cbbe1ff4fde)

**Comment by homuler** [comment]
I think it's possible to build for x86_64, but it's currently not supported, so you can't build it as-is.
What if you change the settings in .bazelrc?
https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/.bazelrc#L63

**Comment by matthewc84** [comment]
I have done this, as well as edited line 62 to say "x86_64", and the output .aar now contains the x86_64 folder, but the program is still throwing a DLLNotFoundException on Mediapipe_ini as shown above.

**Comment by homuler** [comment]
Will you try loading `mediapipe_jni` by yourself?
cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception
> ```cs
> public void LoadLibrary()
> {
>     using (var system = new AndroidJavaClass("java.lang.System"))
>     {
>         system.CallStatic("loadLibrary", "mediapipe_jni");
>     }
> }
> ```

**Comment by matthewc84** [comment]
I was able to add the code, it compiles fine. Also, I checked the apk, the .so is being imported. However, I get the message below.

2023-09-14 14:03:17.192;10106;9536;9557;Info;Unity;;
2023-09-14 14:03:17.228;10106;9536;9557;Error;Unity;AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__isOSVersionAtLeast" referenced by "/data/app/com.UnityTechnologies.com.unity.template.urpblank-Jocvmcf7NYEcTdEm2E20hA==/lib/x86_64/libmediapipe_jni.so"...;
2023-09-14 14:03:17.228;10106;9536;9557;Error;Unity;java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__isOSVersionAtLeast" referenced by "/data/app/com.UnityTechnologies.com.unity.template.urpblank-Jocvmcf7NYEcTdEm2E20hA==/lib/x86_64/libmediapipe_jni.so"...;

**Comment by homuler** [comment]
Try specifying `--android_ndk_api_level` as 25 or lower.
```sh
python build.py build --android fat --android_ndk_api_level=21 -vv
```

**Comment by karmacod3r** [comment]
Hi guys! I made a fork to build for x86_64 a while back. Just added this to .bazelrc to buil 0.10.3:
`build:android_fat --fat_apk_cpu=armeabi-v7a,arm64-v8a,x86_64`

And that worked fine. Don't know if it still works, though. I'll try updating the fork.

**Comment by mattycorbett** [comment]
OK, using @karmacod3r 's fork, I have made progress. The libraries load!. However, now the errors below are being thrown whe I declare a new CalculatorGraph like so "_faceGraph = new CalculatorGraph(_faceDetectConfigAsset.text);"

I can tell the libraries are loading because the resource manager is working correctly immediately before this issue. Again, the code works perfectly on the Unity Editor.

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/87574595/3fb262c7-e2c5-4cd4-bcea-dbd426382661)

**Comment by homuler** [comment]
It's likely there's an issue in the config, so please check the logs (e.g. `adb logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`).
Note that using different code for building the library and building the app can sometimes lead to issues.
(Although you may haven't tested it, I think [specifying the `--android_ndk_api_level` as 25 or below](https://github.com/homuler/MediaPipeUnityPlugin/issues/1026#issuecomment-1720368406) should resolve the original problem without the need for the fork)

**Comment by mattycorbett** [comment]
@homuler you were correct. I am only getting the errors above when I use a CPU-based config file. If I switch to a GPU-based file, the errors cease. However, the graph isn't producing any detections, and throws no errors, with a GPU file. I checked the input image produces facial detection in the Unity Editor, so its not a lack of actual faces.

**Comment by homuler** [comment]
Does the sample app work on your device? If it does, I think this issue is due to your implementation.
In that case, please open another issue if you need help.

If there are no errors, the most likely scenario is that the input images are not being passed correctly (e.g. CPU and GPU are not synchronized).

**Comment by mattycorbett** [comment]
You are correct. It was an implementation issue. I reworked your samples to add a class to use the Magic Leap MLCamera (standard WebCamera method did not work) and that solved it.  Thank you!
