### ISSUE TITLE
MediaPipeException: FAILED_PRECONDITION: Graph has errors

### ISSUE THREAD

**Issue by ChienTC1** [homuler/MediaPipeUnityPlugin#1028]
### Plugin Version or Commit ID

0.12.0

### Unity Version

2022.3.4f1

### Your Host OS

Windows 10 Enterprise

### Target Platform

Android

### Description

MediaPipeException: FAILED_PRECONDITION: Graph has errors:
Calculator::Open() for node "poselandmarkgpu__poselandmarkbyroigpu__poselandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read /storage/emulated/0/Android/data/com.DefaultCompany.ESPORTS_MOLE/files/pose_landmark_full.bytes
when i build .apk file and i try to access files got this error.

I already add below code to custom AndroidManifest.xml file. 
    uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" 
    uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 
    uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" 
but i still got it. how to fix it?
anybody help me? thanks

**Comment by homuler** [comment]
> Failed to read /storage/emulated/0/Android/data/com.DefaultCompany.ESPORTS_MOLE/files/pose_landmark_full.bytes

Maybe you haven't included `pose_landmark_full.bytes` to your apk or forgot to save it to the file system (using `StreamingAssetResourceManager`).
Please read https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#load-model-files for more details.
