### ISSUE TITLE
Handtracking Support, Parent a 3D Cube to the index finger

### ISSUE THREAD

**Issue by fxsrt10** [homuler/MediaPipeUnityPlugin#1029]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.3

### Your Host OS

MacOS

### Target Platform

UnityEditor, iOS

### Description

I'm trying to parent a cube and have it track to the position of a finger and match the joint position and rotation, I'm a little confused on how to extract that position and make a simple 3D model be a child of it and be parented to it. 

I looked at the MultiHandLandmarkListAnnotation class, and tried placing it in the draw function:
<img width="951" alt="image" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/4075097/140cebbd-3205-4c01-bae6-23f008248603">

I see the cube start to follow my finger but it doesn't look like it's matching one to one:

<img width="689" alt="image" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/4075097/054edf18-9ccf-40b6-8518-df1e952c8b7e">

**Comment by homuler** [comment]
You don't need to modify `*Annotation` classes since you can access the value without them.

synchronously
https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/Assets/MediaPipeUnity/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs#L79

or asynchronously (callback)
https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/Assets/MediaPipeUnity/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs#L103-L106

**Comment by fxsrt10** [comment]
Sorry still a little confused, how would I be able to get the landmarks transform properties from them?

**Comment by homuler** [comment]
To get the local position, please read https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks.

If you want to get the rotation, which is not returned by MediaPipe, you need to calculate it by yourself.

**Comment by dclxviclangames** [comment]
> ### Plugin Version or Commit ID
> v0.12.0
> 
> ### Unity Version
> 2022.3
> 
> ### Your Host OS
> MacOS
> 
> ### Target Platform
> UnityEditor, iOS
> 
> ### Description
> I'm trying to parent a cube and have it track to the position of a finger and match the joint position and rotation, I'm a little confused on how to extract that position and make a simple 3D model be a child of it and be parented to it.
> 
> I looked at the MultiHandLandmarkListAnnotation class, and tried placing it in the draw function: <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/4075097/271170467-140cebbd-3205-4c01-bae6-23f008248603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODg3ODYsIm5iZiI6MTcxNTM4ODQ4NiwicGF0aCI6Ii80MDc1MDk3LzI3MTE3MDQ2Ny0xNDBjZWJiZC0zMjA1LTRjMDEtYmFlNi0yM2YwMDgyNDg2MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDA0ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJkYWU0MDBmOTAxN2NkNzk5ZGNkODY0NDkzOWIxZjUyYjE5MjI4YzI2ZGE2YTQwNTllODFkNGNjZjBhOTIxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sjV1Cpv55CyosQUy3aM9_xKsna26FKsFZkmQo65fkvY">
> 
> I see the cube start to follow my finger but it doesn't look like it's matching one to one:
> 
> <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/4075097/271170703-054edf18-9ccf-40b6-8518-df1e952c8b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODg3ODYsIm5iZiI6MTcxNTM4ODQ4NiwicGF0aCI6Ii80MDc1MDk3LzI3MTE3MDcwMy0wNTRlZGYxOC05Y2NmLTQwYjYtODUxOC1kZjFlOTUyYzhiN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDA0ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YwOWM3MGY5NDY2MjBmZDc2YTBkYzA3OTYxZTI5ZWRiNTZkMzAzMjc0NThkMzVhMTE2MThlY2VlZTE2YTI0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LB7hcaN6YTv29f1APQpKgpgmA8obU4oATfII53CrWDA">
> ### Code to Reproduce the issue
> _No response_
> 
> ### Additional Context
> _No response_

Thanks for you logic, i very long find in others resourse how i can move objects with detection and u help me bro, you cool

**Comment by dclxviclangames** [comment]
> To get the local position, please read https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks.
> 
> If you want to get the rotation, which is not returned by MediaPipe, you need to calculate it by yourself.

you are right, this does not work synchronously, in the case when you edit the annotation, but I do not understand how exactly you propose to do this, I must call these functions from another created class
or contact handtrakingsolution, in the handtraking scene example, how to achieve this?
