### ISSUE TITLE
investigate low FPS

### ISSUE THREAD

**Issue by mgarbade** [homuler/MediaPipeUnityPlugin#1031]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

Windows 10 Pro

### Target Platform

Android

### Description

I'm pretty sure the MediaPipeUnityPlugin has become slower. This issue thread is where I will keep on brainstorming my findings, publish my measurements, etc.

The short story: From extensively testing the "pose tracking solution" of the plugin on Android devices in several versions, I can say, that there was a substantial performance drop (lower Pose FPS, higher latency).

The current release v0.12.0 
- clean checkout
- no modifications
- model complexity: full

runs with 
- 17 GameFPS and 17 Pose FPS (running mode: sync) 
- 30 GameFPS and 15 Pose FPS (running mode: non-blocking sync)

on a Galaxy S7 Tablet (SM-T870)

1. Using the [adb tflite benchmark tool](https://www.tensorflow.org/lite/performance/measurement) I know that the tflite model only takes ~10-12 ms on to run. It should be therefore no problem to achieve 30 Pose FPS.
2. Trying out early versions of the plugin (v0.5.0 - before the big code transformation), was showing qualitatively higher Pose FPS and lower latency (numbers will follow)
3. The fact that in "non-blocking-sync" mode the Pose FPS is exactly at half of the Game FPS shows that there might be a problem of images being pumped into mediapipe graph only every second frame

To be continued...

**Comment by homuler** [comment]
> The fact that in "non-blocking-sync" mode the Pose FPS is exactly at half of the Game FPS shows that there might be a problem of images being pumped into mediapipe graph only every second frame

That's because there're 2 yield statements in a loop (when running synchronously).
https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/PoseTrackingSolution.cs#L102
https://github.com/homuler/MediaPipeUnityPlugin/blob/01cdd567ac5939b81114e27e8c13a92bde8275f4/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs#L104

**Comment by mgarbade** [comment]
# Performance Metrics
I'm finally beginning to professionalize the performance investigation. Currently have 2 metrics:

1. Person-Recognitions per second (Pr/sec)
2. Person-Recognition Latency (Pr Latency)
I will follow up on how exactly I measure these two things. 

# Latency
For conducting latency comparisons, we utilize a standardized procedure:
A screen ("Input-Device") displays an image of a person with arms hanging down. A detection device with the app under test is positioned to capture the pose. Following a sudden switch of the image to a pose with raised arms, we measure the app's reaction time to this change using a high-speed camera. The time difference between the image switch on the input device and the app's reaction is measured in milliseconds, to determine the latency.
![LatencyMeasurement (1)](https://github.com/homuler/MediaPipeUnityPlugin/assets/3956593/35f0076b-6d80-42b8-89f0-fc59bf2ee274)


## Impact of Unity Editor on Performance
But for starters, here some result, that seem to indicate that the Unity Editor version has some impact on performance. I compiled [v0.6.2](https://github.com/homuler/MediaPipeUnityPlugin/commit/92dd55579f2faeabf49338974ddb1d15ae54b683), copied the resulting folder twice and opened it with newer Unity Versions (2021.3.18f1 and 2023.3.0b10). Just opening the project with another version seems to slow down the plugin as can be seen from the following table. Values are given in Milliseconds [ms] (average +- standard deviation)

**PrFull** 
|     | Samsung Galaxy Tab A8 | Samsung Galaxy Tab S7 |
| ---------- | --------------------- | --------------------- |
| Unity 2021 | 219 +- 19             | 152 +- 21             |
| Unity 2023 | 241 +- 22             | 188 +- 24             |


**PrLite**
|      | Samsung Galaxy Tab A8 | Samsung Galaxy Tab S7 |
| ---------- | --------------------- | --------------------- |
| Unity 2021 | 215 +- 23             | 158 +- 18             |
| Unity 2023 | 233 +- 24             | 181 +- 20             |

I found similar effects for Unity 2022.x, numbers will follow.
