### ISSUE TITLE
Handtracking for wrist watch 

### ISSUE THREAD

**Issue by harishniwane** [homuler/MediaPipeUnityPlugin#1032]
### Description

I'm looking for a solution. I'm aware of 3d tracking with programmes like Vuforia because I want to build an app to demo watches on the wrist. However I don't want to use any trackers on the hand. Is there a way to use marker-less tracking on my wrist to achieve the same experience  
I want how to rotate the wrist watch with hand but at same time we are not getting the hand rotation.

I want to create App for demo purpose

**Comment by harishniwane** [comment]
I tried like I already put a watch object on Hand wrist point but At the same time I want to rotate the hand and watch same time but the main issue is at runtime I am not getting the rotation of hand. I am using mediapipe hand tracking for the this . Is there any solution please give me thank you.

**Comment by homuler** [comment]
Please see https://github.com/homuler/MediaPipeUnityPlugin/issues/299#issuecomment-931346329.

If you have more questions about MediaPipe, please ask them in the official community.
