### ISSUE TITLE
GPU version is slower than CPU version.

### ISSUE THREAD

**Issue by mins-verse** [homuler/MediaPipeUnityPlugin#1033]
### Description

Hi,

I followed the whole install guideline and found the log which means that I used the GPU inference model. But it is slower than CPU version.

What I need to do to fix it?

I look forward to your help!

**Comment by homuler** [comment]
Could you please provide more details about the situation?

For example:
- Which platform (i.e. Windows, macOS, Linux, Android, iOS) are you referring to?
- What are the specs of your device?
- Which solution did you execute?
- The program you wrote
- How did you measure it?
- What is the actual difference you observed?
