### ISSUE TITLE
Mediapipe Android Build issue

### ISSUE THREAD

**Issue by usamanoob** [homuler/MediaPipeUnityPlugin#1039]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.3.6f1

### Your Host OS

Windows 11

### Target Platform

Android

### Description

I am making an app using FaceLandMarker from Mediapipe in Unity. The goal is to create a talking avatar that mimics the user from the camera.

When I build the app for windows and IOS, its fine but when I build an android app, the joint angles and the blendshapes mess up. 

Kindly help I am new to Unity and I have tried everything

![WhatsApp Image 2023-10-28 at 16 32 07_773edeb9](https://github.com/homuler/MediaPipeUnityPlugin/assets/114694792/ef3b62ba-db6c-4c6e-911c-2fa6585993b7)

### Code to Reproduce the issue

private void OnFaceLandmarkDetectionOutput(FaceLandmarkerResult result, Image image, int timestamp)
        {

            _faceLandmarkerResultAnnotationController.DrawLater(result);
            // new aDDED CODE for 

            if (result.faceBlendshapes.Count > 0)
            {
                classifications = result.faceBlendshapes[0];
                _isClsAvailable = true;
            }
            else
            {
                _isClsAvailable = false;
            }
            if (result.faceLandmarks.Count > 0)
            {
                _rotation = CalculateRotation(result.faceLandmarks[0].landmarks);
                _isRotAvailable = true;
            }
            else
            {
                _isRotAvailable = false;
            }

            //foreach (var normalizedLandmarks in result.faceLandmarks)
            //{
            //    CalculateLandmarks(normalizedLandmarks.landmarks);
            //}
        }

**Comment by homuler** [comment]
I'm not sure, but maybe the input image is rotated or output value is rotated (or both).
