### ISSUE TITLE
Where is the "PoseLandmarkCPU" subgraph defined?

### ISSUE THREAD

**Issue by megawattfs** [homuler/MediaPipeUnityPlugin#1040]
Hello,

I am trying to use a modified version of the pose_landmark_cpu graph. I have been using the sample PoseTrackingGraph, which uses the graph config pose_tracking_cpu.txt, which refers to the calculator "PoseLandmarksCpu." It is not clear to me where this calculator is defined in the source for the Mediapipe Unity plugin or how I could modify it to suit my purpose (outputting some extra data from intermediate computations). I searched the text of all the files in the repo and could not find it. 

Overall, I'm not sure I understand the difference between the regular mediapipe build process and the one used here (.pb files become .txt, not all solution-specific calculators appear to be part of the source, models use .bytes instead of .tflite). Would you mind providing a brief overview?

I am using the source for version 0.10.0

**Comment by megawattfs** [comment]
Never mind, I was misunderstanding how the build worked. I understand now it downloads the mediapipe source.

**Comment by Candlend** [comment]
Hello, I am facing the same problem. Can you tell me how I can modify the subgraph? @megawattfs
