### ISSUE TITLE
How to build a DetectionPacket

### ISSUE THREAD

**Issue by pacuum** [homuler/MediaPipeUnityPlugin#1041]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

Mac Venture 13.5

### Target Platform

iOS

### Description

I want to pass data between two graphs in MediaPipeUnity. The first graph runs PoseDetectionCpu, and Unity receives a DetectionVectorPacket. I want to split this DetectionVectorPacket into individual Detections, and then call PoseDetectionToRoi -> PoseLandmarkByRoiCpu sequentially to perform pose estimation.

However, this requires constructing a DetectionPacket from a Detection object. Is this possible? It appears that the only way to initialize a DetectionPacket is to pass an IntPtr, but the DetectionVectorPacket only has a pointer to a Vector, so there appears to be no direct way to get a pointer to the elements.

One idea I had was to create a bridge function similar that returns an IntPtr of the vector element of specific array index. Are there any other good ways?

**Comment by pacuum** [comment]
I just created a native function as below but it looks like it can not find the c++ function. 
What am I missing? Is there any steps to compile cc code?

DetectionVectorPacket.cs
```
    public DetectionPacket GetElementPointer(int index){
      UnsafeNativeMethods.mp__MakeDetectionPacketFromVector(mpPtr, index, out var ptr).Assert();
      GC.KeepAlive(this);
      return new DetectionPacket(ptr);
    }
```

protobuf_unsafe.cs
```
    [DllImport(MediaPipeLibrary, ExactSpelling = true)]
    public static extern MpReturnCode mp__MakeDetectionPacketFromVector(IntPtr packet, int index, out IntPtr ptr);

```

detection.cc
```
MpReturnCode mp__MakeDetectionPacketFromVector(mediapipe::Packet* vecPacket, int index, mediapipe::Packet** packet_out) {
  TRY
    mediapipe::Detection* pElem = &((*vec)[index]);
    *packet_out = new mediapipe::Packet{mediapipe::MakePacket<mediapipe::Detection>(pElem)};
    RETURN_CODE(MpReturnCode::Success);
  CATCH_EXCEPTION
}
```

detection.h
```
MP_CAPI(MpReturnCode) mp__MakeDetectionPacketFromVector(mediapipe::Packet* vecPacket, int index, mediapipe::Packet** packet_out);
```

Then I call from the solution's OnPoseDetectionOutput() as follows
```
# cast
OutputStream<DetectionVectorPacket, List<Detection>> _stream = stream as OutputStream<DetectionVectorPacket, List<Detection>>;
DetectionPacket packet = _stream.referencePacket.GetElementPointer(index);
```

But the error message I received is 
```
MediaPipeException: INTERNAL: Graph has errors: 
System.EntryPointNotFoundException: mp__MakeDetectionPacketFromVector assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Mediapipe.UnsafeNativeMethods.mp__MakeDetectionPacketFromVector(intptr,int,intptr&)
  at Mediapipe.DetectionVectorPacket.GetElementPointer (System.Int32 index) [0x00000] in /Users/kazu/workspaces/harmonyunityexperiment/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/DetectionVectorPacket.cs:39 
  at Mediapipe.Unity.Holistic.HarmonySolution.OnPoseDetectionOutput (System.Object stream, Mediapipe.Unity.OutputEventArgs`1[TValue] eventArgs) [0x00036] in /Users/kazu/workspaces/harmonyunityexperiment/Assets/MediaPipeUnity/Samples/Scenes/Holistic/HarmonySolution.cs:151 
  at Mediapipe.Unity.OutputStream`2[TPacket,TValue].InvokeIfOutputStreamFound (System.IntPtr graphPtr, System.Int32 streamId, System.IntPtr packetPtr) [0x00076] in /Users/kazu/workspaces/harmonyunityexperiment/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs:402 
Mediapipe.Status.AssertOk () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:149)
Mediapipe.Unity.GraphRunner.AddPacketToInputStream[T] (System.String streamName, Mediapipe.Packet`1[TValue] packet) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:183)
Mediapipe.Unity.GraphRunner.AddTextureFrameToInputStream (System.String streamName, Mediapipe.Unity.TextureFrame textureFrame) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:200)
Mediapipe.Unity.Holistic.HarmonyObjectDetectionGraph.AddTextureFrameToInputStream (Mediapipe.Unity.TextureFrame textureFrame) (at Assets/MediaPipeUnity/Samples/Scenes/Holistic/HarmonyObjectDetectionGraph.cs:70)
Mediapipe.Unity.Holistic.HarmonySolution.AddTextureFrameToInputStream (Mediapipe.Unity.TextureFrame textureFrame) (at Assets/MediaPipeUnity/Samples/Scenes/Holistic/HarmonySolution.cs:100)
Mediapipe.Unity.HarmonyBaseSolution+<Run>d__12.MoveNext () (at Assets/MediaPipeUnity/Samples/Scenes/Holistic/HarmonyBaseSolution.cs:112)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)
```

**Comment by pacuum** [comment]
I figured out that I have to build the library with build.py
thank you.

**Comment by homuler** [comment]
> I want to pass data between two graphs in MediaPipeUnity. The first graph runs PoseDetectionCpu, and Unity receives a DetectionVectorPacket. I want to split this DetectionVectorPacket into individual Detections, and then call PoseDetectionToRoi -> PoseLandmarkByRoiCpu sequentially to perform pose estimation.

If it's possible, I think the best way is to build a single `CalculatorGraphConfig` which can do what you want.
However, if you need to receive the result from the first `CalculatorGraph`, I think your approach is better.

**Comment by imamura-mmj** [comment]
Thank you for your suggestion. 

First I tried to do with single graph but I could not find the way to iterate over elements of a vector with pbtxt file only. 
Also I need tracking multiple objects so I had to get object are rectangles to run tracker algorithm such as SortCS.

Anyway the above code just worked well so far. Thank you.

**Comment by pacuum** [comment]
Thank you for your suggestion.

First I tried to go with single Graph but I could not find the way to iterate over a vector returned by the PoseDetectionCpu in Unity. 
Also I want to run tracking algorithm such as SortCS to decide which rectangle we should run pose estimation.

Anyway the above fix worked. Thank you for your support.
