### ISSUE TITLE
Build iOS app with React Native, Library not loaded: @rpath/MediaPipeUnity.framework/MediaPipeUnity

### ISSUE THREAD

**Issue by khuepm** [homuler/MediaPipeUnityPlugin#1042]
### Plugin Version or Commit ID

0.12.0

### Unity Version

2023.1.18f1

### Your Host OS

M1 MacOS Sonoma 14

### Target Platform

Mac Standalone, iOS

### [iOS Only] XCode Version

Xcode 15.0.1

### Command Sequences

I'm building a very simple iOS app with React Native, and add UnityFramework in a xcode workspace.
So I got error 

`MediaPipeUnity.framework/MediaPipeUnity' (no such file, not in dyld cache)`

I have read issues #880 and check all the same issues
- Add To Embedded Binaries and OpenGLES are checked 
- Use newest version 0.12 
- I use the code from MediaPipeUnityPlugin-all.zip. It works fine if I build to run standalone
- The code ReactNative works fine with another Unity project (embed UnityFramework, set target membership...)
- The code build success and only crash when it starts. 

Thank @homuler for this plugin. Have a nice day!

### Log

dyld[38333]: Library not loaded: @rpath/MediaPipeUnity.framework/MediaPipeUnity
  Referenced from: <23955DA9-20B9-300C-A434-58A1D86AB061> /private/var/containers/Bundle/Application/11BB9938-556A-4173-88C7-C6204D94A719/RNUnity.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/private/var/containers/Bundle/Application/11BB9938-556A-4173-88C7-C6204D94A719/RNUnity.app/Frameworks/MediaPipeUnity.framework/MediaPipeUnity' (no such file), '/usr/lib/swift/MediaPipeUnity.framework/MediaPipeUnity' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/MediaPipeUnity.framework/MediaPipeUnity' (no such file), '/private/var/containers/Bundle/Application/11BB9938-556A-4173-88C7-C6204D94A719/RNUnity.app/Frameworks/MediaPipeUnity.framework/MediaPipeUnity' (no such file), '/private/var/containers/Bundle/Application/11BB9938-556A-4173-88C7-C6204D94A719/RNUnity.app/Frameworks/MediaPipeUnity.framework/MediaPipeUnity' (no such file), '/usr/lib/swift/MediaPipeUnity.framework/MediaPipeUnity' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/MediaPipeUnity.framework/MediaPipeUnity' (no such file), '/private/var/containers/Bundle/Application/11BB9938-556A-4173-88C7-C6204D94A719/RNUnity.app/Frameworks/MediaPipeUnity.framework/MediaPipeUnity' (no such file), '/private/var/containers/Bundle/Application/11BB9938-556A-4173-88C7-C6204D94A719/RNUnity.app/Frameworks/MediaPipeUnity.framework/MediaPipeUnity' (no such file)

**Comment by homuler** [comment]
Perhaps there is an issue with the way you build the app. After identifying the more specific problem, you may want to ask in a different place (e.g. StackOverflow).

By reading the log, you can see that which path `dyld` expects the library to be located at.
And probably you also know where the library actually exists.

I think it's a good idea to investigate why the paths dyld is searching and the actual paths where the library exists are different.
