### ISSUE TITLE
General workflow to build with this plugin

### ISSUE THREAD

**Issue by Heavenswind** [homuler/MediaPipeUnityPlugin#1046]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022.3.6f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor, Windows Standalone

### Description

We want to build a face filter app with this plugin, what would be the best way to use this plugin to achieve that without modifying the package?

We are currently looking at the Face Mesh example and want to know what the best way to overlay the canonical face mesh model that the original github  provides:  https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry/data

**Comment by homuler** [comment]
I'm sorry, but I can answer questions related to more specific code, but discussions at the design level are beyond the scope of free support, so I will close this issue.
