### ISSUE TITLE
Running MediaPipeUnityPlugin on XR headsets

### ISSUE THREAD

**Issue by dogadogan** [homuler/MediaPipeUnityPlugin#1049]
### Feature Description

Would it be possible to run it inside Unity projects for Meta (Oculus) Quest or Microsoft HoloLens headsets?

Quest runs an Android-based operating system, whereas HoloLens runs Windows Holographic OS.
Are you aware of any projects that used the library on such headsets?

Thanks!

**Comment by homuler** [comment]
I believe it should work on Quest, but if it doesn't, please let me know.
I don't have a HoloLens, so I cannot provide support regardless of whether it works or not.
