### ISSUE TITLE
Issue with facial detection using fisheye (140 degree) lens

### ISSUE THREAD

**Issue by matthewc84** [homuler/MediaPipeUnityPlugin#1053]
### Plugin Version or Commit ID

0.12.0

### Unity Version

2022.2.19

### Your Host OS

Windows 11

### Target Platform

Android

### Description

I am trying to locate face landmarks and iris landmarks using MediaPipe. This solution works perfectly with a standard ESP32-CAM OV2640 with about 55 degrees of FOV. This FOV has proven inadequate for what I want to do, so I am now using a fisheye lens. The capture works fine, except the range of the face detection is now extremely limited. The camera only detects faces at about 1 ft, and beyond that fails to detect any faces. I can see the faces fine in the debug output image, but obviously, they are smaller with the distortion. I THINK that this is because the detection is only calibrated for 2m and closer, and the distortion is making MediaPipe believe the face is father than it is. Do you have any ideas?

**Comment by homuler** [comment]
I can't say much without seeing the input image, etc., but if you are successfully passing the input image from Unity to MediaPipe, it might be a good idea to consult with the MediaPipe developers team.
