### ISSUE TITLE
How to set the maximum number of faces that can be detected?

### ISSUE THREAD

**Issue by smallfly** [homuler/MediaPipeUnityPlugin#1055]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

macOS Sonoma 14.0

### Target Platform

Mac Standalone

### Description

Hello,

I'm looking to set the maximum number of faces that can be detected by the Face Detection. I looked at the sources but did not find where to define this value.

Thank you!

**Comment by smallfly** [comment]
Hello @homuler, 

would you have some insights on this? 

Thank you.

**Comment by PLandaA** [comment]
Any solutions to this issue?

**Comment by homuler** [comment]
I'm sorry, I overlooked this issue.
I believe it can be resolved by using `ClipDetectionVectorSizeCalculator`.

https://github.com/google/mediapipe/blob/4237b765ce95af0813de4094ed1e21a67bad2a5f/mediapipe/modules/face_landmark/face_landmark_front_cpu.pbtxt#L101-L114

 Additionally, in the Task API, there are corresponding parameters available.
https://github.com/homuler/MediaPipeUnityPlugin/blob/84181bf0eebbb625c06112909878ac582dcc4484/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceDetector/FaceDetectorOptions.cs#L63-L66
