### ISSUE TITLE
Support for Audio example

### ISSUE THREAD

**Issue by rootux** [homuler/MediaPipeUnityPlugin#1057]
### Feature Description

I would love to see support for the `Audio Classifier`.
Or general direction on how to implement it 🙏🏼 

[The Demo](https://mediapipe-studio.webapps.google.com/studio/demo/audio_classifier)

[Existing Samples source code](https://github.com/googlesamples/mediapipe/tree/main/examples/audio_classifier)

[JS Example](https://codepen.io/mediapipe-preview/pen/wvxYYmy)

[Python Example (without streaming - only audio files)](https://github.com/googlesamples/mediapipe/blob/main/examples/audio_classifier/python/audio_classification.ipynb)

**Comment by rootux** [comment]
@homuler how physible is this?

**Comment by homuler** [comment]
I'm sorry but I don't have the time to provide detailed explanations.
If you plan to implement it yourself, please refer to the pull requests where other Task APIs were implemented (e.g. https://github.com/homuler/MediaPipeUnityPlugin/pull/997).

**Comment by homuler** [comment]
I can accept the request through https://ko-fi.com/homuler.

**Comment by rootux** [comment]
Sure thing. With pleasure. What would be a reasonable coffee size donation
for this? 🙂
