### ISSUE TITLE
Pose Landmark Detection - Smooth Landmarks

### ISSUE THREAD

**Issue by cturanhc** [homuler/MediaPipeUnityPlugin#1058]
### Feature Description

I'm using your side branch the name is **feature/tasks/pose-landmarker** for multi-pose tracking.
I used Pose Tracking too, It's amazingly smooth because of the smoothLandmark feature.

So maybe if you continue to develop the pose-landmarker, the smoothLandmark feature can be very useful on pose-landmarker.

### Current Behaviour/State

Flickering point and connection annotations.

**Comment by homuler** [comment]
`PoseLandmarker` has already been implemented and is available in the master branch.
https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/PoseLandmarker/PoseLandmarker.cs

It's just that the sample scene has not been implemented yet.

**Comment by cturanhc** [comment]
Thanks for the quick response homuler! Let me explain this situation;
- Your second comment is right. I'm not using the master branch.
- My goal is multi-pose tracking and you have a feature/tasks/pose-landmarker branch
-  There is two scene about "pose" on your plugin. First /samples/pose-tracking, the second one is /samples/tasks/pose-landmarker
- At pose tracking scene, landmarks are extremely smooth but I can track only one person
- At pose landmarker scene, I can track multi-person but landmarks are shaky

So I'll try to use Mediapipe 0.10.7
