### ISSUE TITLE
Using external camera (UVC) on Android

### ISSUE THREAD

**Issue by dogadogan** [homuler/MediaPipeUnityPlugin#1062]
### Plugin Version or Commit ID

#1022 - 01cdd56

### Unity Version

2022.3.11f1

### Your Host OS

macOS Ventura 13.6

### Target Platform

Android

### Description

Firstly, thank you for this great repo. The repo conveniently runs object detection on live webcam streams.
My question is specific to using _webcams (external cameras) on Android_.

There's this other nice repo, which allows using webcams (UVC devices) within Unity on Android, and it works well:
https://github.com/saki4510t/UVC4UnityAndroid

I was wondering how I can use this as input source in the [Object Detector](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Assets/MediaPipeUnity/Samples/Scenes/Object%20Detection) scene.
The UVC4UnityAndroid repo basically turns the webcam stream into a Texture2D, which for example gets rendered on a Raw Image ([sample scene](https://github.com/saki4510t/UVC4UnityAndroid/blob/master/UVC4UnityAndroid/Assets/UVC4UnityAndroidPlugin/Samples/Scenes/UVC2DScene.unity)). This is how its script component looks: 
![Screenshot 2023-12-11 at 10 51 26](https://github.com/homuler/MediaPipeUnityPlugin/assets/11411924/64b07550-b7c6-43c0-9038-190def6e846d)

In this case, when it comes to MediaPipeUnityPlugin's [sample scenes](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Assets/MediaPipeUnity/Samples/Scenes/Object%20Detection), we can't just simply select "Web Camera" as the source in bootstrap, so I was wondering what would be the best way to handle this?

![Screenshot 2023-12-11 at 10 58 00](https://github.com/homuler/MediaPipeUnityPlugin/assets/11411924/8e559ab8-79e3-4293-a133-bb65c434f710)

Might you have any solutions or solutions to this?

**Comment by homuler** [comment]
If you can get the `Texture`, you can easily create an `ImageFrame` from it.
https://github.com/homuler/MediaPipeUnityPlugin/blob/ec3e4d726b378dc3117dbdf40ddffc5df9193c24/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs#L216
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#send-imageframe.

(Although I had implemented a constructor for generating an `ImageFrame` from a `Texture`, I forgot to merge it, so I plan to add it later)

If you want to use `TextureFrame`, please see the following code.
https://github.com/homuler/MediaPipeUnityPlugin/blob/ec3e4d726b378dc3117dbdf40ddffc5df9193c24/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Face%20Detection/FaceDetectorRunner.cs#L79-L89
https://github.com/homuler/MediaPipeUnityPlugin/blob/ec3e4d726b378dc3117dbdf40ddffc5df9193c24/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs#L120-L172

**Comment by wangwenfeng0** [comment]
Do you have test it? I have same issue.
