### ISSUE TITLE
EntryPointNotFoundException

### ISSUE THREAD

**Issue by HNTWings** [homuler/MediaPipeUnityPlugin#1063]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.20f1c1

### Your Host OS

windows 11

### Target Platform

Android, iOS

### Description

I try to export a bundle for my apps, when I put the exported resources in my Android Project and run it, it has debug 1 Error which says "EntryPointNotFoundException: mp_api__SetFreeHGlobal assembly:<unknown assembly> type:<unknown type> member:(null)". But I can using "Build and Run" and it worked very well, after that I've read some issue and tried only export on ARM64 and it still not work.
Hope teach, thanks!

### Code to Reproduce the issue

```
I/AudioTrack: isLongTimeZeroData zoer date time 2 Seconds



E/Unity: EntryPointNotFoundException: mp_api__SetFreeHGlobal assembly:<unknown assembly> type:<unknown type> member:(null)
        at (wrapper managed-to-native) Mediapipe.UnsafeNativeMethods.mp_api__SetFreeHGlobal(Mediapipe.UnsafeNativeMethods/FreeHGlobalDelegate)
      at Mediapipe.UnsafeNativeMethods..cctor () [0x00000] in <09b053d65618434190248835d691bf84>:0 
    Rethrow as TypeInitializationException: The type initializer for 'Mediapipe.UnsafeNativeMethods' threw an exception.
      at Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) [0x00000] in <09b053d65618434190248835d691bf84>:0 
      at Mediapipe.Unity.Bootstrap+<Init>d__16.MoveNext () [0x00033] in <4e6da0ceeae44186b347ebbeef2d22fa>:0 
      at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00020] in /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17 
    UnityEngine.MonoBehaviour:StartCoroutineManaged2(MonoBehaviour, IEnumerator)
    UnityEngine.MonoBehaviour:S



I/CameraManagerGlobal: Connecting to camera service
```

### Additional Context

Target Platform:
Android (Error)
iOS (havent try yet, I hope to fix Android build first)

Current Android build setting:
il2cpp arm64 (only, no armv7)

Publishing Settings:
Custom Main Manifest (for using OpenCV)

I've tried this: https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception but only 1 and 2.

**Comment by homuler** [comment]
> when I put the exported resources in my Android Project and run it

What specific actions did you take?

> But I can using "Build and Run" and it worked very well

If so, I suspect that `mediapipe_android.aar` might not be included in the apk.

**Comment by HNTWings** [comment]
1.Use “export” to build a folder with some dll, then move the "asset" folder in the Android Project.

2.I already had a '''mediapipe_android.aar''' in my unity project, but how do I know if it is indeed included in the project? Please tell me, thanks! I'm a green hand for Android.

**Comment by homuler** [comment]
Well, could you please provide a screenshot or some other form of visual aid and explain so that I can accurately understand?
Is this what you mean by 'export'?
![Screenshot_20231216_005527](https://github.com/homuler/MediaPipeUnityPlugin/assets/4690128/bd8b87db-3ab3-4e8a-88d5-99eea9b22154)

> how do I know if it is indeed included in the project?

I'm not sure which project you're referring to, but in any case, you can find out by examining the contents of the apk.

**Comment by HNTWings** [comment]
1.Yes, after that I copied the whole "unityLibrary" folder in my Android Project.
2.I've unzip my apk file and find out I got a "mediapipe_android.aar" in it.

Sorry for replying so late. After my exploration, I have discovered that I have some residual settings from the past. Once I clean them up, I should be able to successfully build it on Android Studio. However, I have encountered another issue. When the mediapipe_android.aar contains the armv7 library, I encounter a strange error when building with il2cpp. I am unsure whether I should modify it to only build the arm64 library. Below are the relevant screenshots.

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/41991213/370201fe-2f16-4b5d-bb8d-ec55a81972e5)

When I only build for arm64, this error does not occur. However, the my friend who provide me the AAR only includes the armv7 library. Should I ask them to provide the relevant content for 64-bit as well?

**Comment by homuler** [comment]
> However, the my friend who provide me the AAR only includes the armv7 library. Should I ask them to provide the relevant content for 64-bit as well?

Sorry, I don't quite understand what you mean because it's too high-context for me.

> I am unsure whether I should modify it to only build the arm64 library. Below are the relevant screenshots.

I think it's unrelated to this project, but have you tried what is written below the 'Try'?

**Comment by HNTWings** [comment]
I'm sorry to make this trouble for you. On this question, the answer I got was to clean the old settings, and make sure no duplicate or older files. That can maintain a clean project.
The problem now is that due to the lack of 64 -bit library (I mean the ARM64), I may not be able to build APK in Android Studio.
If you think its necessary to initiate another issue, please tell me and close the present one, thank you very much!

**Comment by homuler** [comment]
If you can demonstrate that it's related to this project, feel free to create a new issue.
For example, if you can clarify that the issue can be resolved if _a certain thing_ can be achieved and that the means for it are not provided by this project, I can consider addressing it.

However, for now, it appears to be an issue with your environment rather than an issue with this project.

> When the mediapipe_android.aar contains the armv7 library,

> due to the lack of 64 -bit library

It appears as if these two sentences are saying opposite things, and I sense the possibility that you've not analyzed what is occurring.
