### ISSUE TITLE
Which version of MediaPipe does this plugin use?

### ISSUE THREAD

**Issue by Jatin-Pawar** [homuler/MediaPipeUnityPlugin#107]
Hey @homuler 

I just curious enough to ask which version of MedaiPipe release does this plugin use? Do we have to set the MediaPipe version to be used or does it automatically uses the latest release of MediaPipe?

Thanks in advance.
~jk!ng

**Comment by homuler** [comment]
Currently 0.8.3.1 is used.
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/WORKSPACE#L53

In general, you cannot change the version without changing other parts.
