### ISSUE TITLE
How can I distinguish the landmarks of the left and right hands in an async?

### ISSUE THREAD

**Issue by bbq82828** [homuler/MediaPipeUnityPlugin#1075]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.29f1

### Your Host OS

Windows11

### Target Platform

Android

### Description

When I am in the asynchronous state, if both my left and right hands appear on the screen, the landmarks obtained at this time will not be able to distinguish which group is for the left hand and which group is for the right hand.

### Code to Reproduce the issue

This is how I get the landmark 
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/56858145/d8d06339-9233-4c24-aaa0-3e0f24c4c1e6)
I know that using ClassificationList can tell whether it is the left hand or the right hand

**Comment by homuler** [comment]
I hope the HandLandmarker API (not released yet) will resolve this since the callback receives the whole result as an argument.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d495193dd7081142d1a19c9f171b0d0bcccaaa1e/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/HandLandmarker/HandLandmarkerOptions.cs#L14-L23

**Comment by bbq82828** [comment]
OK, I understand. Thank you for your response. I look forward to subsequent updates.

**Comment by bbq82828** [comment]
@homuler  Hello,thank you again I have a solution myself. 
I untied and combined the two lists so that I can distinguish the landmarks of the left and right hands.
The solution is as follows
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/56858145/ecbde67f-cc63-41bd-8d3e-6e229fd90e24)

**Comment by homuler** [comment]
How do you ensure that it is an inference result for the same input?
While it might be unlikely to be a significant issue in practice, I think it is necessary to either check the timestamp of the output or ensure it through some `Calculator`.

**Comment by bbq82828** [comment]
Sorry for replying so late
After a simple test (of course, it may be that my test is not good enough), I found that as long as the first data in the two lists is from the left or right hand, the second data must be from the other hand, and the order in which the data comes in is alternate.
