### ISSUE TITLE
How to build sample or new project with plugin on Adr

### ISSUE THREAD

**Issue by PhamTienDat42** [homuler/MediaPipeUnityPlugin#1078]
### Plugin Version or Commit ID

d495193

### Unity Version

2022.3.16f1

### Your Host OS

window 10 pro

### Target Platform

Android

### Description

When i build sample on adr device. Its seem be dont find any camera and dont show! What should i do for adr build with unity 2022.3.16f1

### Code to Reproduce the issue

just build successed!

### Additional Context

![406140478_1375394749731991_8594064344870625421_n](https://github.com/homuler/MediaPipeUnityPlugin/assets/117574501/25b2d79e-401c-460d-9d42-6569bd8c6ee1)

**Comment by homuler** [comment]
Please share the log.
```txt
adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"
```

Did you build `mediapipe_android.aar`?

**Comment by PhamTienDat42** [comment]
I build with unity Build android support, how can i get this log: "adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S""

**Comment by homuler** [comment]
If you still need help, please share the log (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/1078#issuecomment-1866216728).
