### ISSUE TITLE
Smt wrong with app

### ISSUE THREAD

**Issue by Almazikman** [homuler/MediaPipeUnityPlugin#109]
Hey there, have a problem again. I managed to build template scene to android and sometimes it even worked but when I switched modes or cameras - it usually just doesn't do anything and sometimes just crashed. And btw my build size is around 200 mb! I tried to erase mediapipe and install it again but it didn't help. Now my build size is around 230 mb. How to reduce it? And usually my build crashed on android, but not always. Sometimes it works, but all I need to do is switch camera and it'll crash or just stop working.

Here are my logs:

First try crashlog:
https://appp.me/roZCEA

Second try crashlog:
https://appp.me/zXu2YD

Third try crashlog:
https://appp.me/ISVbvc

And finally it worked and after this I switched camera:
https://appp.me/bTIxjk

Btw, when it's working it render camera with 90 degree rotation.

Could you help me?

**Comment by homuler** [comment]
Will you rewrite the description of issue with this template, and show how to reproduce it, please?
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by Almazikman** [comment]
**System information**
- OS Platform and Distribution: MacBook Air (11-inch, Mid 2012), macOS Catalina 10.15.7 (19H524)
- Target Platform: Android
- Mobile Device: Redmi 4X (Custom Android 9)
- MediaPipeUnityPlugin version or commit id: e65a730b4c76d28cf70e374b9d68536add4b16a2
- Bazel version: 3.7.2
- GCC/G++ version: 12.0.0
- Android NDK version: 19.0.5232133 (Default Unity's NDK)

**Describe the current behavior**
I managed to build template scene to android and sometimes it even worked but when I switched modes or cameras - it usually just doesn't do anything and sometimes just crashed. I tried to erase mediapipe and install it again but it didn't help. And usually my build crashed on android, but not always. Sometimes it works, but all I need to do is switch camera and it'll crash or just stop working.

**Describe the expected behavior**
It had to not to crash 3 from 4 tries and work fine especially after switching camera. 

**Steps to reproduce the issue**
I did all installation steps correctly, but somehow it works that way and I dunno how to reproduce it.

**Full logs**
I tried to launch application for 4 times. Here are my logs:

First try crashlog:
https://appp.me/roZCEA

Second try crashlog:
https://appp.me/zXu2YD

Third try crashlog:
https://appp.me/ISVbvc

And finally it worked and after this I switched camera:
https://appp.me/bTIxjk

**Additional context**
My build size is around 230 mb! How to reduce it?

**Comment by Almazikman** [comment]
> Will you rewrite the description of issue with this template, and show how to reproduce it, please?

Done

**Comment by Vladislav489** [comment]
guys, are you have any update?

**Comment by Vladislav489** [comment]
@homuler

**Comment by Vladislav489** [comment]
@homuler  please help
