### ISSUE TITLE
Blendshapes too slow

### ISSUE THREAD

**Issue by usamanoob** [homuler/MediaPipeUnityPlugin#1095]
### Description

Hi I have used the facelandmark with blendshapes v2 model in my Vtube app.
The issue is that it runs really slowly.
I have tested everything to see what is causing the slow processing, I have tested different models, even without models and all the scene I ran the app and still it was lagging.

Kindly tell me if I made any mistake, or how can I make it fast. (the facelandmark model runs super fast but the one with the blendshapes is slow)

P.S. I have input the facelandmarker with blendshapes v2 in the streaming assets.

**Comment by homuler** [comment]
> The issue is that it runs really slowly.

Could you troubleshoot whether it is due to the model itself or the implementation of the plugin?
If it's the former, please ask the MediaPipe team.

**Comment by usamanoob** [comment]
Hi, can you suggest how can I troubleshoot it effectively?
I have used the model without the blendshapes (just the facelandmark model) and it ran smoothly, but the model with the blendshapes (facelandmark with blendshapes v2) heavily slowed my app

**Comment by homuler** [comment]
It depends on how you're running the model, but in any case, please use a profiler or similar tools to investigate which method is taking up time.
For example, if you're calling `FaceLandmarker.Detect`, check if the following method is a bottleneck.
https://github.com/homuler/MediaPipeUnityPlugin/blob/74c1c8500afeca379ea6ba6a5cb9e9d1b08f1aa4/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/TaskRunner.cs#L35

If it is, it's an issue on the model side, and there may be nothing that can be addressed as a plugin.
