### ISSUE TITLE
Missing ´Mediapipe´ reference in Unity

### ISSUE THREAD

**Issue by jborlido** [homuler/MediaPipeUnityPlugin#11]
After opening the Unity project on Ubuntu, it shows me multiple compiler errors saying that it's missing Mediapipe reference. Am I missing something?

**Comment by homuler** [comment]
Maybe you have not run the build step yet.
If so, please see [here](https://github.com/homuler/MediaPipeUnityPlugin#build).

If this does not solve the problem, will you show me the errror log?

**Comment by jborlido** [comment]
I've done all the steps listed and it still throws those errors.
All the errors look something like this `Assets/Mediapipe/SDK/Scripts/Annotation/AnnotationController.cs(3,32): error CS0234: The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)`

**Comment by homuler** [comment]
Will you run below commands and attach the output log here?
```sh
make gpu
make install
```

**Comment by jborlido** [comment]
These are the logs, probably need to install something.

`jborlido@mini-warmachine:~/Documents/mediapipe-tests$ make gpu
make: *** No rule to make target 'gpu'.  Stop.
jborlido@mini-warmachine:~/Documents/mediapipe-tests$ make install
mkdir -p Assets/Mediapipe/SDK/Plugins/Protobuf
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/Mediapipe/SDK/Plugins/Protobuf
cp -f C/bazel-bin/mediapipe_api/libmediapipe_c.so Assets/Mediapipe/SDK/Plugins
cp: cannot stat 'C/bazel-bin/mediapipe_api/libmediapipe_c.so': No such file or directory
Makefile:58: recipe for target 'install-mediapipe_c' failed
make: *** [install-mediapipe_c] Error 1`

**Comment by homuler** [comment]
Please run `git pull` first.

**Comment by homuler** [comment]
I think you have not installed protocol buffer compiler (`protoc` command) yet.
If so, please install `protoc` and then retry the build step.

**Comment by jborlido** [comment]
I've installed protoc and it still didn't build
`cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/Mediapipe/SDK/Plugins/Protobuf
cp -f C/bazel-bin/mediapipe_api/libmediapipe_c.so Assets/Mediapipe/SDK/Plugins
cp: cannot stat 'C/bazel-bin/mediapipe_api/libmediapipe_c.so': No such file or directory
Makefile:58: recipe for target 'install-mediapipe_c' failed
make: *** [install-mediapipe_c] Error 1`

**Comment by homuler** [comment]
Will you attach the `make gpu` log, please?
I think the above log is output when running `make install`.
And if you have not pulled the latest commit yet, please run `git pull` (https://github.com/homuler/MediaPipeUnityPlugin/issues/11#issuecomment-707053470)

**Comment by jborlido** [comment]
Already pulled. These are the logs for make gpu
`jborlido@mini-warmachine:~/Documents/mediapipe-tests$ make gpu
# TODO build all the .proto files and output to the same directories
protoc --proto_path=Assets/MediaPipe/SDK/Scripts --csharp_out=Assets/MediaPipe/SDK/Scripts/Protobuf Assets/MediaPipe/SDK/Scripts/Protobuf/*.proto && \
protoc --proto_path=Assets/MediaPipe/SDK/Scripts --csharp_out=Assets/MediaPipe/SDK/Scripts/Protobuf/Annotation Assets/MediaPipe/SDK/Scripts/Protobuf/Annotation/*.proto
cd C && bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 //mediapipe_api:libmediapipe_c.so //mediapipe_api:mediapipe_models
/bin/sh: 1: bazel: not found
Makefile:32: recipe for target 'gpu' failed
make: *** [gpu] Error 127
`

**Comment by homuler** [comment]
It seems that `bazel` is not installed.
This repository is dependent on MediaPipe, and if you cannot run the official example, this plugin cannot be built.

Please check the official guide and make sure that you can run the examples on your machine.
https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu
