### ISSUE TITLE
full body pose tracking

### ISSUE THREAD

**Issue by kitmek1** [homuler/MediaPipeUnityPlugin#110]
I want to ask if there is a plan to full body pose tracking instead of half body pose tracking

**Comment by LGuilhermeRodrigues** [comment]
I'm also interested in this option.
Today we can already use the full body pose tracking on the holistic demo.  However, it's not the lighest solution due face mesh and hands tracking running together.

**Comment by homuler** [comment]
If I have time, I may implement that option (like `enable_iris_detection` option in Holistic demo).

By the way, speaking of if full body pose tracking is supported or not, I think it's already supported.
The aim of this project is not to translate all the official solutions into C# and run them on Unity, but to enable developers to define and run `mediapipe::CalculatorGraph` on Unity without writing C++ code.

With this plugin, you can copy and import the definition of full body pose tracking graph from the official repository, and initialize `Mediapipe.CalculatorGraph` with it.
If you rewrite [upper_body_pose_tracking_*.txt](https://github.com/homuler/MediaPipeUnityPlugin/blob/2ba2cbc8813735ddfbed3abd2124ce9500efddf7/Assets/Mediapipe/Samples/Graphs/PoseTracking/Resources/upper_body_pose_tracking_desktop_gpu.txt), I think you can get full body pose landmarks even now (annotations won't work, so if you recycle sample code, you need to change some).

**Comment by jsaon-L** [comment]
[upper_body_pose_tracking_android.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226232/upper_body_pose_tracking_android.txt)
[upper_body_pose_tracking_desktop_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226233/upper_body_pose_tracking_desktop_cpu.txt)
[upper_body_pose_tracking_desktop_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226235/upper_body_pose_tracking_desktop_gpu.txt)

this my fullbody graph file (file name is upper_body in fact it is fullbody)
Don't forget use FullBodyPoseLandmarkListAnnotationController.cs to draw pose

**Comment by Wayne-nulitics** [comment]
@homuler Thank you for explaining the purpose of this port and use of mediapipe::CalculatorGraph, that we are looking for 'n a sample code snippet in C# that subscribes to the detection/graph calculation, we've been able to "track it down" to:

public class HandTrackingGraph : DemoGraph {
private OutputStreamPoller<List<NormalizedLandmarkList>> handLandmarksStreamPoller;
...
**var handLandmarks = isHandLandmarksPresent ? FetchNextHandLandmarks() : new List<NormalizedLandmarkList>();**
...
  private void RenderAnnotation(WebCamScreenController screenController, HandTrackingValue value) {
    // NOTE: input image is flipped
    GetComponent<HandTrackingAnnotationController>().Draw(
      screenController.transform, value.HandLandmarkLists, value.Handednesses, value.PalmDetections, value.PalmRects, true);
  }

But how, from another scripts, can we subscribe the receive the value.HandLandmarkLists and value.Handednesses as they are being updated.

ie. we can't figure out how to subscribe to the  **var handLandmarks**
 
We are well versed in using it in Python, and the hand_landmark detection from here https://google.github.io/mediapipe/solutions/hands.html 

Any help would be appreciated.

**Comment by homuler** [comment]
@Wayne-nulitics It looks unrelated to the topic to me. Will you create another issue, please?

**Comment by jjjhhjjh** [comment]
> [upper_body_pose_tracking_android.txt ](https://github.com/homuler/MediaPipeUnityPlugin/files/6226232/upper_body_pose_tracking_android.txt)
> [upper_body_pose_tracking_desktop_cpu.txt ](https://github.com/homuler/MediaPipeUnityPlugin/files/6226233/upper_body_pose_tracking_desktop_cpu.txt)
> [upper_body_pose_tracking_desktop_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226235/upper_body_pose_tracking_desktop_gpu.txt)
> 
> 이 내 전신 그래프 파일 (파일 이름은 upper_body이며 실제로 fullbody 임)
> FullBodyPoseLandmarkListAnnotationController.cs를 사용하여 포즈를 그리는 것을 잊지 마십시오.



Can you tell me specifically how to do it?
I want to do light body tracking.

**Comment by jjjhhjjh** [comment]
I succeeded through the 3 file links above. Thank you

**Comment by alibros** [comment]
> [upper_body_pose_tracking_android.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226232/upper_body_pose_tracking_android.txt)
> [upper_body_pose_tracking_desktop_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226233/upper_body_pose_tracking_desktop_cpu.txt)
> [upper_body_pose_tracking_desktop_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226235/upper_body_pose_tracking_desktop_gpu.txt)
> 
> this my fullbody graph file (file name is upper_body in fact it is fullbody)
> Don't forget use FullBodyPoseLandmarkListAnnotationController.cs to draw pose

Hey @jsaon-L thanks for this - The desktop graph does work however I get errors trying to Android Graph. Did you need to make any other modifications to get the full body graph working on android?

**Comment by jsaon-L** [comment]
> > [upper_body_pose_tracking_android.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226232/upper_body_pose_tracking_android.txt)
> > [upper_body_pose_tracking_desktop_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226233/upper_body_pose_tracking_desktop_cpu.txt)
> > [upper_body_pose_tracking_desktop_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6226235/upper_body_pose_tracking_desktop_gpu.txt)
> > this my fullbody graph file (file name is upper_body in fact it is fullbody)
> > Don't forget use FullBodyPoseLandmarkListAnnotationController.cs to draw pose
> 
> Hey @jsaon-L thanks for this - The desktop graph does work however I get errors trying to Android Graph. Did you need to make any other modifications to get the full body graph working on android?

this txt file  work in mediapipeUnityPlugin0.5.3,I don’t know if it can run on the latest version

you can make youself graphs,refer to
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/pose_tracking_gpu.pbtxt
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/subgraphs/pose_renderer_gpu.pbtxt

**Comment by alibros** [comment]
@homuler before I open a new issue - is this correct that full body is now supported? According to this post https://github.com/google/mediapipe/issues/1995  Google have stopped supporting upper body only so would be great to upgrade this project to the full model if it's not already.

**Comment by homuler** [comment]
> is this correct that full body is now supported? 

If you are asking whether the sample [PoseTrackingGraph](https://github.com/homuler/MediaPipeUnityPlugin/blob/92dd55579f2faeabf49338974ddb1d15ae54b683/Assets/Mediapipe/Samples/Graphs/PoseTracking/Scripts/PoseTrackingGraph.cs) supports full body tracking, yes, it's supported (cf. https://github.com/homuler/MediaPipeUnityPlugin/commit/c61d1c82d786ba377cd5cea4714609a640c90cc4#diff-98bcf1a12cc60eccd0f7b3c5db02914000d8341a62816904cd2cdca381274b04).
