### ISSUE TITLE
shoes not visible on foot

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#111]
I am trying object detection 3d on Android and IOS. 
- On Android - Blue box shows
- On IOS - box looking only black.

Also,
There is a sneaker.obj and sneaker_texture, but i can not see any shoes in foot. 
Can I use shoes models on Foot?  If yes can you tell how can i make it? 
I tried many ways but can not figure it out, hope you can help.
Regards.

**Comment by homuler** [comment]
As is described [here](https://github.com/homuler/MediaPipeUnityPlugin#example-graphs), Objectron is not supported on Android and iOS currently.
At first it worked, but after upgrading mediapipe to 0.8.3.1, it broke and I've not fixed it yet.

**Comment by emreboyraz0** [comment]
When upgraded mediapipe to 0.8.3.1? My last builds like below android/ios. 
"At first it worked" mean last week update?

![Android_ss](https://user-images.githubusercontent.com/39331199/112853668-c3007700-90b5-11eb-829a-45246fc4a849.JPG)
![IOS_ss](https://user-images.githubusercontent.com/39331199/112853675-c5fb6780-90b5-11eb-8065-9f90328cb556.PNG)

**Comment by homuler** [comment]
At latest commit, Objectron does not work on my device (Pixel 3a), but it seems that it's working on your device.
Currently, the sample app only shows the result MediaPipe renders.
I don't know why it does not work properly on iOS, but iOS does not support OpenGL ES 3.2, so I guess that's the reason.

> There is a sneaker.obj and sneaker_texture, but i can not see any shoes in foot.

As I mentioned earlier, the sample app copies the official apk's behavior.
https://google.github.io/mediapipe/solutions/objectron.html

If you'd like to render shoes, I think you should do it on Unity side based on the positions MediaPipe outputs.
I'd like to make Unity render annotations in the future, but I'm afraid I cannot do that for some time.

**Comment by homuler** [comment]
Close this because now `Point3d` data are acessible.
