### ISSUE TITLE
Missing DLL error

### ISSUE THREAD

**Issue by Wayne-nulitics** [homuler/MediaPipeUnityPlugin#112]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Linux 20.04
- Target (e.g. desktop cpu, android arm64): desktop and android 
- Bazel version: 4.0.0
- Python version: 3.9
- GCC/G++ version: 
- Unity version: 2019.4.13f1
- Android NDK version (if building for Android): 21.x
- Xcode version (if building for iOS):

**Describe the problem**
I installed opencv and have two versions it seems, one from apt-get install, installed to /user/lib/x86_64-linux-gnu, version 4.2.0 and one it seems is downloaded via bazel build, installed to /user/local/lib when I edit WORKSPACE and linux build I still don't find the DLL

WORKSPACE, tried both paths, here is the current

new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr/local/lib",
)

And

cc_library(
    name = "opencv",
    srcs = glob(
        [
            "usr/local/lib/libopencv_core.so",
            "usr/local/lib/libopencv_calib3d.so",
            "usr/local/lib/libopencv_features2d.so",
            "usr/local/lib/libopencv_highgui.so",
            "usr/local/lib/libopencv_imgcodecs.so",
            "usr/local/lib/libopencv_imgproc.so",
            "usr/local/lib/libopencv_video.so",
            "usr/local/lib/libopencv_videoio.so",
        ],

When I find the opencv versions I get:

find / -name "libopencv_video.so" -print 2>/dev/null
/x/x/.cache/bazel/_bazel_wventer/ce2d6f27d9834f5b0751c3dd09fab20a/external/linux_opencv/libopencv_video.so
/usr/lib/x86_64-linux-gnu/libopencv_video.so
/usr/local/lib/libopencv_video.so

They are:
4.2 in /user/lib/x86_64-linux-gnu
3.4.14 in /usr/local/lib

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

All instructions as per the build guide, it builds without error, just missing DLL error when starting in Editor, same build works fine on a Windows PC, so related to opencv location on Ubuntu

**Full logs**

**Additional context**

I get this when setting load at start:
Plugins: Couldn't open /x/x/UnityProjects/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.so, error: /x/x/UnityProjects/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.so: undefined symbol: _ZTVN2cv9BFMatcherE

**Comment by homuler** [comment]
You need to specify the root path in `WORKSPACE` and relative paths in `opencv_linux.BUILD`.
In your case (OpenCV 3), I think `path` in WORKSPACE should be `/usr/local` and `opencv_linux.BUILD` should be kept untouched.

**Comment by Wayne-nulitics** [comment]
Thank you, that solved it, hat to set the path to /usr/local
