### ISSUE TITLE
How to develop local build environment using google/mediapipe

### ISSUE THREAD

**Issue by neon-izm** [homuler/MediaPipeUnityPlugin#1122]
### Feature Description

This repository provides build scripts.

Build script can download the necessary modules and apply PATCH to build them.

patches are like them.

https://github.com/homuler/MediaPipeUnityPlugin/blob/master/third_party/bazel_ios_workaround.diff

https://github.com/homuler/MediaPipeUnityPlugin/blob/master/third_party/emscripten_extract_archive_fixes.diff

This works fine. But how do you develop to make those patches?

It would be easier for other developers to modify MediaPipe if the steps you are taking to adapt this repository to the latest MediaPipe at hand are documented in the Document.

Do you have any URLs or documentation that would be helpful?

**Comment by homuler** [comment]
Theses patches are specific to this project, but how to generate and apply them is not specific, so I've not written the documentation about it.

It is relatively easy to create a new patch:

1. Checkout the target version of MediaPipe (e.g. `cd mediapipe && git checkout v0.10.9`).
2. Make the necessary modifications.
3. `git diff > xxx.diff`.

Maintaining a patch is a bit more challenging.
For example, if you want to upgrade MediaPipe from version v0.10.8 to v0.10.9, I follow the steps below (there may be better methods):

1. `cd mediapipe && git checkout v.0.10.8`.
2. Apply the existing patch (e.g. `git apply xxx.diff`). There shouldn't be any errors at this point.
3. `git stash`.
4. `git checkout v0.10.9`.
5. `git stash pop`.
6. If there're conflicts, resolve them.
7. Update the patch (e.g. `git diff > xxx.diff`).

**Comment by neon-izm** [comment]
Thank you!It's clear and I understand.
