### ISSUE TITLE
multiple people's Bone detection

### ISSUE THREAD

**Issue by LiWeisuper** [homuler/MediaPipeUnityPlugin#1123]
### Plugin Version or Commit ID

v0.14.0

### Unity Version

2022.2.15f1c

### Your Host OS

Windows10

### Target Platform

Windows Standalone

### Description

Can multiple people's bones be recognized simultaneously? How to set and modify?

**Comment by homuler** [comment]
How about setting `numPoses` when running the PoseLandmarker?
https://github.com/homuler/MediaPipeUnityPlugin/blob/f5ab41d387bc2a3547beaa1d6a330aaa14715dc6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/PoseLandmarker/PoseLandmarkerOptions.cs#L48-L51

**Comment by LiWeisuper** [comment]
After testing the changes, the image still only shows the bone information of one person, and cannot draw the bone information of multiple people at the same time

**Comment by LiWeisuper** [comment]
![无标题](https://github.com/homuler/MediaPipeUnityPlugin/assets/80231119/e829d1a2-dc4e-41e9-94d3-4d6abce6b11d)
Thank you for your reply! After testing the changes, the image still only shows the bone information of one person, and cannot draw the bone information of multiple people at the same time

**Comment by LiWeisuper** [comment]
![无标题1](https://github.com/homuler/MediaPipeUnityPlugin/assets/80231119/4a493e75-e0b9-4089-88ae-27afcaa4dc01)
When the camera captures two people, it recognizes them here, but there is an empty and null list
