### ISSUE TITLE
The name 'GraphicsDeviceType' does not exist in the current context

### ISSUE THREAD

**Issue by tianshenzai** [homuler/MediaPipeUnityPlugin#1126]
### Plugin Version or Commit ID

v0.14.0

### Unity Version

2021.3.33f1c1

### Your Host OS

Windows10

### Target Platform

Android

### Build Command

no

### Bug Description

it's all right on unity editor, but when i build on Android, it has an error (Assets\MediaPipeUnity\Samples\Common\Scripts\GraphRunner.cs(52,48): error CS0103: The name 'GraphicsDeviceType' does not exist in the current context).i use the Pose Tracking demo.

### Steps to Reproduce the Bug

File-->Build Settings-->Android-->Build

### Log

Assets\MediaPipeUnity\Samples\Common\Scripts\GraphRunner.cs(52,48): error CS0103: The name 'GraphicsDeviceType' does not exist in the current context

**Comment by homuler** [comment]
Thank you for reporting the issue!
