### ISSUE TITLE
Hololens2 support

### ISSUE THREAD

**Issue by Prakash19921206** [homuler/MediaPipeUnityPlugin#1128]
### Description

Hi all,
I'm trying to build app with mediapipe for Hololens2
While it works fine on unity editor, it throws dll not found error on hololens2 that it cannot find mediapipe_c
my guess is that mediapipe_c.dll is not UWP compatible ?

> DllNotFoundException: Unable to load DLL 'mediapipe_c'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_c' because of 'C:\build\output\unity\unity\External\il2cpp\builds\external\baselib\Source\WinApi\Baselib_DynamicLibrary_WinApi.inl.h(36):Baselib_DynamicLibrary_OpenUtf16: Failed to open the requested dynamic library (0x06000000) - The specified module could not be found.  (WinError:0000007e)
>   at Mediapipe.UnsafeNativeMethods..cctor () [0x0000d] in .\Packages\com.github.homuler.mediapipe\Runtime\Scripts\PInvoke\UnsafeNativeMethods.cs:29 
>   at Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) [0x00002] in .\Packages\com.github.homuler.mediapipe\Runtime\Scripts\External\Protobuf.cs:16 
>   at Mediapipe.Unity.Bootstrap+<Init>d__16.MoveNext () [0x0003c] in C:\Users\ase103\MyUnityProjects\Prototype2\Hololens2_Deceptive Probability\Assets\MediaPipeUnity\Samples\Common\Scripts\Bootstrap.cs:44 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in C:\build\output\unity\unity\Runtime\Export\Scripting\Coroutines.cs:17 
>   at UnityEngine.MonoBehaviour.StartCoroutine (System.Collections.IEnumerator routine) [0x0002e] in C:\build\output\unity\unity\Runtime\Export\Scripting\MonoBehaviour.bindings.cs:112 
>   at Mediapipe.Unity.Bootstrap.OnEnable () [0x00008] in C:\Users\ase103\MyUnityProjects\Prototype2\Hololens2_Deceptive Probability\Assets\MediaPipeUnity\Samples\Common\Scripts\Bootstrap.cs:36 
>   at Mediapipe.Unity.Solution.FindBootstrap () [0x0003b] in C:\Users\ase103\MyUnityProjects\Prototype2\Hololens2_Deceptive Probability\Assets\MediaPipeUnity\Samples\Common\Scripts\Solution.cs:104 
>   at Mediapipe.Unity.Solution+<Start>d__4.MoveNext () [0x0002c] in C:\Users\ase103\MyUnityProjects\Prototype2\Hololens2_Deceptive Probability\Assets\MediaPipeUnity\Samples\Common\Scripts\Solution.cs:24 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in C:\build\output\unity\unity\Runtime\Export\Scripting\Coroutines.cs:17 
> 

Thanks

**Comment by homuler** [comment]
I think it's because the DLL is not built for Windows ARM.

**Comment by Prakash19921206** [comment]
Thanks for you reply.
app built fine for HoloLens
May i know how to build dll for Windows ARM ?
i'm using files from release section

**Comment by homuler** [comment]
I'm not sure if we can in the first place because the Tensorflow does not support Windows ARM AFAIK.

**Comment by Prakash19921206** [comment]
i see
Thanks for letting me know
