### ISSUE TITLE
Blendshape data and functionality with AR

### ISSUE THREAD

**Issue by skango** [homuler/MediaPipeUnityPlugin#1129]
### Plugin Version or Commit ID

V0.14.0

### Unity Version

2022.3.11f1

### Your Host OS

Windows 11

### Target Platform

Android, iOS

### Description

I would like to know if there is any way to get blend shape information. I want to use blendshape data to apply that to my 3D model in AR. Also can I run this without webtexture? Because I want to use this in AR and webtexture is not suitable. Maybe I can pass my own texture 2D? Can I do something like that? Please let me know, thanks!

**Comment by skango** [comment]
@homuler  Please when you have time just tell me 1 little thing, I got blend shapes working, I just need to understand how can I pass mediapipe my own texture 2Ds instead of using webcamera? Please, this is the only thing I need to get everything working.
I am using facelandmarkrunner script to get blendshape data, I just don't know how do provide this plugin with my own textures and not webtextures. Thanks!

**Comment by skango** [comment]
If anybody needs to get blendshapes, access it from facelandmarkrunner script at this part:
 private void OnFaceLandmarkDetectionOutput(FaceLandmarkerResult result, Image image, long timestamp)
 {
         File.WriteAllText(Application.persistentDataPath + "/mpblend.json",
             result.faceBlendshapes[0].ToString());
   _faceLandmarkerResultAnnotationController.DrawLater(result);
 }

**Comment by skango** [comment]
> > I just need to understand how can I pass mediapipe my own texture 2Ds instead of using webcamera?
> 
> You can build an `Image` from `Texture2D`.
> 
> https://github.com/homuler/MediaPipeUnityPlugin/blob/6eb80265bddd743ce287f7939a5fcdaa50521aa1/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Formats/Image.cs#L47-L50
> 
> See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#imageframe and #343.

Thank you for your response, it is very clear there how to create an image frame, however, I don't understand where to pass that frame variable. facelandmarkrunner is the script I want to use only, since that one has blend shapes, so how do I input there this image frame? Or it is global? If it's global where does that go? Everything else is clear and I understand, thank you! In the sample code you pass it to some graph drawer or something, and I don't use that, I need this facelandmarkrunner.

**Comment by homuler** [comment]
I mean you can build an **`Image`** from `Texture2D` as well as `ImageFrame`.

**Comment by skango** [comment]
Okay thanks I got it working on android, however, I am not able to make IOS build, is there anything that I am missing? The Xcode project with full of errors, that was not the case before I imported this plugin. I made a build from windows machine, should I make it from MacOS? Could that be an issue?

**Comment by homuler** [comment]
If necessary, please create a new issue.
