### ISSUE TITLE
Wrong coordinates of head 3D landmarks from pose tracking 

### ISSUE THREAD

**Issue by Deankovitch** [homuler/MediaPipeUnityPlugin#1131]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

MacOS Sonoma 14.1.1

### Target Platform

UnityEditor, Windows Standalone, Mac Standalone, Android, iOS

### Target Device

iOS, Android

### [Android Only] Android Build Tools and NDK Version

Android build API 33 and NDK r21d

### [iOS Only] XCode Version

Xcode 15.0.1

### Build Command

I used compiled libraries from the repository

### Bug Description

Wrong coordinates of head 3D landmarks from pose tracking 
I’m developing a project using a holistic solver and I realized that all the point coordinates from the head coming from the 3D World Pose tracking are misplaced. 

I created a debug gizmo representation of what I’m getting from Mediapipe and it looks very different from what is expected according to Mediapipe documentation as you can see on the attached images.

![Screenshot 2024-01-24 at 14 40 08 (2)](https://github.com/homuler/MediaPipeUnityPlugin/assets/1033830/c2a0c128-c170-473a-abd1-688d94f357bd)
<img width="1800" alt="Screenshot 2024-01-24 at 14 40 08" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/1033830/9151896a-0c7a-4b56-a5ef-6251fa322a1c">

### Steps to Reproduce the Bug

Open the Holistic sample scene and draw gizmos at body 3D world landmark coordinates to see its positions on unity editor scene.

### Log

No logs or errors 

### Screenshot/Video

https://github.com/homuler/MediaPipeUnityPlugin/assets/1033830/ae51f7f1-2d92-4a13-9c24-42aefc16e147

**Comment by homuler** [comment]
Will you ignore the z value and check if it still seems incorrect?
This plugin usually just returns the result from MediaPipe as it is, so please make sure you cannot reproduce the problem using the original MediaPipe APIs (or using the official sample) first.
