### ISSUE TITLE
Sync Mode not working with segmentation enabled

### ISSUE THREAD

**Issue by LeMetamax** [homuler/MediaPipeUnityPlugin#1141]
### Plugin Version or Commit ID

v0.14.1

### Unity Version

2022.3.17f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor

### Build Command

none

### Bug Description

Playing the holistic scene out of the box while running on Sync mode throws a NotImplementedException error that points to line 472 of PacketGetterExtension class. This causes the application to freeze.
But does not happen when segmentation is disabled.

### Steps to Reproduce the Bug

1. Install v0.14.1 on a brand new and empty unity URP project
2. Open the Holistic scene in Assets/MediaPipeUnity/Samples/Scenes/Holistic/Holistic.unity
3. Select "Solution" gameobject
4. Change Running Mode to "Sync" on the "Holistic Tracking Solution" component
5. Press play

### Log

NotImplementedException: The method or operation is not implemented.
Mediapipe.Unity.Sample.GraphRunner+<>c__45`1[T].<TryGetValue>b__45_0 (Mediapipe.Packet`1[TValue] packet) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:211)
Mediapipe.Unity.Sample.GraphRunner.TryGetValue[T] (Mediapipe.Packet`1[TValue] packet, T& value, System.Func`2[T,TResult] getter) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:221)
Mediapipe.Unity.Sample.GraphRunner.TryGetValue[T] (Mediapipe.Packet`1[TValue] packet, T& value) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:211)
Mediapipe.Unity.Sample.Holistic.HolisticTrackingGraph.WaitNextAsync () (at Assets/MediaPipeUnity/Samples/Scenes/Holistic/HolisticTrackingGraph.cs:219)
Rethrow as AggregateException: One or more errors occurred. (The method or operation is not implemented.)
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Threading.Tasks.Task`1[TResult].get_Result () (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
Mediapipe.Unity.Sample.Holistic.HolisticTrackingSolution+<WaitForNextValue>d__30.MoveNext () (at Assets/MediaPipeUnity/Samples/Scenes/Holistic/HolisticTrackingSolution.cs:102)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <f7237cf7abef49bfbb552d7eb076e422>:0)

**Comment by homuler** [comment]
Thank you for reporting the issue.
It is fixed by #1142 .

**Comment by LeMetamax** [comment]
> Thank you for reporting the issue, and also appreciate the clear explanation you provided. It is fixed by #1142 .

I appreciate the response. However, I tried to add the changes to MediaPipeUnityPlugin-all-stripped.zip and I am getting this error:
`Packages\com.github.homuler.mediapipe\Runtime\Scripts\Tasks\Audio\AudioClassifier\AudioClassifierOptions.cs(99,14): error CS0246: The type or namespace name 'Proto' could not be found (are you missing a using directive or an assembly reference?)`
Can you please update the releases page with the changes or let me know how to fix the error?

**Comment by homuler** [comment]
> I tried to add the changes to MediaPipeUnityPlugin-all-stripped.zip

I don't think the `AudioClassifier` is included in v0.14.1, but are you talking about a completely different issue from the original one?

**Comment by LeMetamax** [comment]
No I wasn't. I simply wanted to take a look at the holistic sample scene and see how everything is setup with sync mode segmentation.
But I figured it out. I simply copied the scripts with the changes(seen from the repo's history) and then pasted to overwrite the ones on 0.14.1 and it worked.
