### ISSUE TITLE
Document or WIKI typo and other problems

### ISSUE THREAD

**Issue by Altaiar** [homuler/MediaPipeUnityPlugin#1148]
### Description

Hi i have been trying to learn so i could work with this plugin its really hard so i started reading docs and wiki after hello world codes provided in tutorials are not in a good shape there is some varriables that their name is incorrect so if someone try to copy paste them (codes u provide in examples from wiki) it will not work in getting land mark section task.Result is not available even if we add  using System.Threading.Tasks 
in  Face Mesh Solution tutorial 
u missed a return after yield 
Qeustion 
question how exactly i should use positions from Graph Runner i can get them with my script but they are normalized and are between 0 and 1 i dont know how to convert them to world cords or rects i basically just want to instantiate a 3D object on 1 of the landmarks i tried to achive it by using 
            var screenRect = Canvas.GetComponent<RectTransform>().rect;
            var position = screenRect.GetPoint(myLocs[0].Landmark[0]);
but my object flys around the scene (moves so much)
My Unity Version 
2023.2.8f1
Media Pipe Plugin Version 
v0.14.1

**Comment by homuler** [comment]
> u missed a return after yield

Thanks, I fixed it.

> i dont know how to convert them to world cords or rects

There isn't a single prescribed way to do it; the method varies depending on the application.
You'll need to calculate it yourself based on what you want to do.

**Comment by Altaiar** [comment]
> There isn't a single prescribed way to do it; the method varies depending on the application.

u are right about it but i still think there should be one simple example  i cant understand examples in plugins too it took me a a lot of time  until i found a way to get land marks :) now im trying to find a way to use it :)

**Comment by homuler** [comment]
The purpose of this plugin is to run MediaPipe in Unity and retrieve values.
While I believe documenting how to retrieve the position of landmarks in the image is important, how to use it is a separate matter from MediaPipe, and I don't think it necessarily needs to be documented, although it could be convenient for some users if it exists.
In fact, most of the similar questions I've received so far have been about how to use Unity, and there are more appropriate places to ask about them.

**Comment by Altaiar** [comment]
i fixed it in way that dont make any sense at all  but still it works fine for me now 
BTW thanks for ur help and being friendly
