### ISSUE TITLE
Using GPUBuffer on iOS with Metal

### ISSUE THREAD

**Issue by ABazL** [homuler/MediaPipeUnityPlugin#1149]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.9f1

### Your Host OS

Windows

### Target Platform

iOS

### Description

Hello,

I'm trying to use GPUBuffer on iOS on an app running with Metal graphic API.
I didn't find samples where a potential "Metal context" was used like it's the case for Android with OpenGLES.
Is there one I missed ?

Not sure that there is this equivalent for Metal from what I saw in the API.
Is it possible to use GPUBuffer for iOS ? If yes, how ?
I'm wondering what object is expected as IntPtr in GPUBuffer constructor for iOS ?

I already saw your answer from [this post](https://github.com/homuler/MediaPipeUnityPlugin/issues/768#issuecomment-1279952048) but as it was a post from 2022, I was wondering if your answer was still up to date.

If there is no equivalent of OpenGLES context for Metal, does that mean that for apps running with Metal, they need to use ImageFrame in any case to make MediaPipe works ?

Thanks!

**Comment by homuler** [comment]
> Is it possible to use GPUBuffer for iOS ? If yes, how ?

It is used internally. However, it is not supported as an input type, so you need to build an `ImageFrame` (or `Image` for the Task API) and pass it to the `CalculatorGraph`.

> I already saw your answer from https://github.com/homuler/MediaPipeUnityPlugin/issues/768#issuecomment-1279952048 but as it was a post from 2022, I was wondering if your answer was still up to date.

It remains same. If you can demonstrate the overhead is relatively high, please let me know.
