### ISSUE TITLE
camera doesn't turn on when i build the sample scenes in android

### ISSUE THREAD

**Issue by yassergamedev** [homuler/MediaPipeUnityPlugin#1150]
### Description

I tried building different sample scenes in my android device but once i open up the app the camera doesn't turn on, is there a way to fix this?

**Comment by homuler** [comment]
Please read the Player.log.
```sh
adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"
```
