### ISSUE TITLE
Please help update the latest mediapipe, the  task holistic has been updated now

### ISSUE THREAD

**Issue by 1101728133** [homuler/MediaPipeUnityPlugin#1151]
### Feature Description

Same title

### Current Behaviour/State

Same title

### Additional Context

Same title

**Comment by homuler** [comment]
The latest version has been updated, so I will close this. Holistic has not been officially released yet, so it is not implemented.
https://ai.google.dev/edge/mediapipe/solutions/vision/holistic_landmarker
