### ISSUE TITLE
Doesn't work the camera when I build

### ISSUE THREAD

**Issue by MARLOPD** [homuler/MediaPipeUnityPlugin#1152]
### Plugin Version or Commit ID

v0.14.1

### Unity Version

2022.3.12

### Your Host OS

Android 12, Android 13

### Target Platform

Android

### Command Sequences

I build the app for android with this configuration:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/38f987d1-bab1-45f8-8494-ad42947f7993)

### Log

I used Logcat to see what was happening, and this is what it showed:

adb logcat Unity -s

--------- beginning of main
02-25 19:07:21.334 11769 11795 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
02-25 19:07:21.417 11769 11795 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 3701mb
02-25 19:07:21.417 11769 11795 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
02-25 19:07:21.417 11769 11795 I Unity   : ApplicationInfo com.Aula_STEM.Signia version 0.1
02-25 19:07:21.417 11769 11795 I Unity   : Built from '2022.3/release' branch, Version '2022.3.12f1 (4fe6e059c7ef)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
02-25 19:07:21.682 11769 11795 I Unity   : Company Name: Aula_STEM
02-25 19:07:21.682 11769 11795 I Unity   : Product Name: Signia
02-25 19:07:24.342 11769 11795 W Unity   : Logging for the MediaPipeUnityPlugin will be suppressed. To enable logging, please check the 'Development Build' option and build.
02-25 19:07:24.342 11769 11795 W Unity   : Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
02-25 19:07:24.342 11769 11795 W Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
02-25 19:07:24.342 11769 11795 W Unity   : UnityEngine.Object:Instantiate(T)
02-25 19:07:24.342 11769 11795 W Unity   : Mediapipe.Unity.Sample.Solution:FindBootstrap()
02-25 19:07:24.342 11769 11795 W Unity   : Mediapipe.Unity.Sample.<Start>d__9:MoveNext()
02-25 19:07:24.342 11769 11795 W Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
02-25 19:07:24.342 11769 11795 W Unity   :
02-25 19:07:24.357 11769 11795 E Unity   : DllNotFoundException: Unable to load DLL 'mediapipe_jni'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_jni' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "mediapipe_jni" not found
02-25 19:07:24.357 11769 11795 E Unity   :   at Mediapipe.UnsafeNativeMethods.mp_api__SetFreeHGlobal (Mediapipe.UnsafeNativeMethods+FreeHGlobalDelegate freeHGlobal) [0x00000] in <00000000000000000000000000000000>:0
02-25 19:07:24.357 11769 11795 E Unity   :   at Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) [0x00000] in <00000000000000000000000000000000>:0
02-25 19:07:24.357 11769 11795 E Unity   :   at Mediapipe.Unity.Sample.Bootstrap+<Init>d__11.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
02-25 19:07:24.357 11769 11795 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
02-25 19:07:24.357 11769 11795 E Unity   :   at UnityEngine.Object.Instantiate[T] (T original) [0x00000] in <00000000000000000000000000000000>:0
02-25 19:07:24.357 11769 11795 E Unity   :   at Mediapipe.Unity.Sample.Solution.FindB

### Additional Context

I thought maybe it could be because of the camera permission, but no, that was in order, and I created a Raw image and tried in a normal script to manage that Raw Image, and it worked, but the Camera from the plugging still didn't work

**Comment by homuler** [comment]
> 02-25 19:07:24.357 11769 11795 E Unity : DllNotFoundException: Unable to load DLL 'mediapipe_jni'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_jni' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "mediapipe_jni" not found

Where did you get the plugin? Did you download it from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases)?
If not (e.g. `git clone`), you need to build the required libraries.
cf. #901

**Comment by MARLOPD** [comment]
I downloaded the package from the release page and in the gradleTemplate.properties add the next line: android.ndkVersion = "21". However I build and still not working

**Comment by homuler** [comment]
Does your apk contain `lib/arm64-v8a/libmediapipe_jni.so`?
If not, will you describe the steps to reproduce the issue?

**Comment by MARLOPD** [comment]
No. It does not contain that file. Give me a second and I'll tell you specifically what I did in the project.

**Comment by MARLOPD** [comment]
I had a project in Unity version 2022.3.12 on my laptop (Windows 11), then I downloaded version 14.1 of this package, imported it into the project and then used it to get and send data to an onnx model. It worked perfectly in the editor, so I created a UI and build the project, however when building the application it did not work. I thought maybe it was a problem with my project so I downloaded the version unit project, then built it and it didn't work on my phone either. I think maybe this feedback I'm getting at the time of the build is important:

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/d9fba63e-170a-40a0-9d59-4b169a993e45)

And when I build the poject I selected the option "Yes, for these and other files..."

Regarding the configuration of the player in the project settings, these are some of the elements that I modified when I built it: 

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/c14b5015-2153-4e85-ae69-9243af9dc751)


PD: I really appreciate the help you have given me as well as the quick response.

**Comment by homuler** [comment]
> I think maybe this feedback I'm getting at the time of the build is important:

It seems like there might be some issue with the plugin itself, but for now, I think it is not affecting this issue.

>  I downloaded version 14.1 of this package, imported it into the project

Is it that you imported from a tarball (= `com.github.homuler.mediapipe-0.14.1.tgz`) using Package Manager?
![Screenshot_20240226_234654](https://github.com/homuler/MediaPipeUnityPlugin/assets/4690128/0f34089d-eb1e-4d12-9ea4-db977b6be738)

Can you confirm that the imported package contain `mediapipe_android.aar`?
![Screenshot_20240226_235103](https://github.com/homuler/MediaPipeUnityPlugin/assets/4690128/7cb5a921-274d-428d-b5b1-916dce8dda0d)

**Comment by MARLOPD** [comment]
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/76b09b5f-4f0b-45c7-9496-9be80731a4a3)
Yes, the file exist. 

The way I added the plugging was with something like this:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/d2433086-2141-4748-9463-a084d4705491)

And for what it's worth, this is  how looks my package manger windows like:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/befd1bec-07cc-4e4b-83ca-fcb7f636180c)

**Comment by homuler** [comment]
> No. It does not contain that file.

How did you confirm this?
I don't know why `mediapipe_android.aar` is imported and yet it is not included in the APK.

> I thought maybe it was a problem with my project so I downloaded the unity project of this package (Version 14.1), then built it and it didn't work on my phone either.

Have you confirmed that the same error (`dlerror() = dlopen failed: library "mediapipe_jni" not found`) occurs in both cases?

**Comment by MARLOPD** [comment]
I searched for the name in the Windows explorer and didn't appear. And in both cases there is no samples in the package manager:

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/80049481/bdbfd35a-45f9-47ae-8ec3-53e2cbdf0c86)

**Comment by MARLOPD** [comment]
I am new to this topic, so I am really not sure how to check this error dlerror() = dlopen failed: library "mediapipe_jni" not found, should I put it in the cmd?

**Comment by MARLOPD** [comment]
I found a solution in another issue. It was just move the .bytes files to Streaming assets. 

Thank you very much for your time and knowledge, you were really helpful, I hope you have a very good day. Thanks again

**Comment by homuler** [comment]
So after all the error had changed.
If it was resolved, please close this issue.

**Comment by ChandduFlyers** [comment]
Hi MARLPOD, can u explain how u resolved this issue pls,I am facing the same issue,appreciate your response,Thank you.

**Comment by MARLOPD** [comment]
Hi! Did you check the AppSetting file? It should be in StreamingAssest. The problema that I had was that It was in other option

**Comment by ChandduFlyers** [comment]
Hi ,thanks for quick response,yes just now checked that,now build is working fine,thought of updating here, but you are too quick;), appreciate that dude, Thank you.

**Comment by MARLOPD** [comment]
It was a pleasure, I hope your project goes well!

**Comment by cancaglar** [comment]
Im having the same issue. I read all comments and I got the .bytes  files and appsettings in StreamingAssets, I downloaded the project from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases) and still camera not working on android. Is there anything I should check?

**Comment by MARLOPD** [comment]
The App setting file shouldn't be in the streaming assets folder, but it should be with the streaming assets option in the inspector. Have you already checked that?

**Comment by sads32** [comment]
> The App setting file shouldn't be in the streaming assets folder, but it should be with the streaming assets option in the inspector. Have you already checked that?

added the streamingassets folder also changed assetloader type . now the camera works on unity remote but still on building apk it does not work.
screenshot added for unity remote but didnot change for apk file.
![Uploading Screenshot_20240411-182743.png…]()
![Screenshot_20240409-234515](https://github.com/homuler/MediaPipeUnityPlugin/assets/126474085/d87b10ef-d169-4866-a35b-b5617e919833)

**Comment by nemajor1** [comment]
> The App setting file shouldn't be in the streaming assets folder, but it should be with the streaming assets option in the inspector. Have you already checked that?

Hi, I ran into a similar problem, can you please write the paths how it should look, I will be grateful
