### ISSUE TITLE
Build errors prevent builds within Visual Studio when attempting to Attach Visual Studio to Unity for debugging

### ISSUE THREAD

**Issue by blaqsmith** [homuler/MediaPipeUnityPlugin#1157]
### Plugin Version or Commit ID

v0.14.1

### Unity Version

2022.3.20f1

### Your Host OS

Windows, MacOS

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Microsoft Visual Studio Community 2022 (64-bit) Version 17.7.5
Microsoft .NET Framework Version 4.8.09032
Visual Studio Tools for Unity Version 17.7.0.0

### Command Sequences

Build errors occur within Visual Studio when either trying to Build Solution (Build -> Build Solution) on a Unity project that includes the Mediapipe plugin, or Attach the VS debugger to Unity via Attach to Unity.

Unity itself does not generate errors.

### Log

Error logs:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeMatrix.cs	29	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\External\SerializedProto.cs	28	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\External\SerializedProto.cs	37	Active
Error	CS0171	Field 'Matrix.data' must be fully assigned before control is returned to the caller. Consider updating to language version '11.0' to auto-default the field.	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Formats\Matrix.cs	37	Active
Error	CS0171	Field 'Matrix.rows' must be fully assigned before control is returned to the caller. Consider updating to language version '11.0' to auto-default the field.	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Formats\Matrix.cs	37	Active
Error	CS0171	Field 'Matrix.cols' must be fully assigned before control is returned to the caller. Consider updating to language version '11.0' to auto-default the field.	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Formats\Matrix.cs	37	Active
Error	CS0171	Field 'Matrix.layout' must be fully assigned before control is returned to the caller. Consider updating to language version '11.0' to auto-default the field.	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Formats\Matrix.cs	37	Active
Error	CS0433	The type 'Span<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet.cs	310	Active
Error	CS0433	The type 'Span<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet.cs	331	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\ImageArray.cs	23	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\ImageArray.cs	27	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeCategory.cs	30	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeCategory.cs	34	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeClassificationResult.cs	20	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeClassificationResult.cs	26	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeClassificationResult.cs	42	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeClassificationResult.cs	48	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeClassificationResult.cs	70	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeClassificationResult.cs	74	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeDetectionResult.cs	25	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeDetectionResult.cs	31	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeDetectionResult.cs	36	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeDetectionResult.cs	42	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeDetectionResult.cs	54	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeDetectionResult.cs	58	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	58	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	62	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	73	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	77	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	93	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	97	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	113	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeLandmark.cs	117	Active
Error	CS0433	The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Mediapipe.Runtime	C:\Repos\livestage\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Marshal\NativeMatrix.cs	25	Active

**Comment by homuler** [comment]
Will it be fixed if you delete [`System.Memory.dll`](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/Protobuf/System.Memory.dll.meta) and [`System.Buffer.dll`](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/Protobuf/System.Buffers.dll.meta)?

**Comment by blaqsmith** [comment]
> Will it be fixed if you delete [`System.Memory.dll`](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/Protobuf/System.Memory.dll.meta) and [`System.Buffers.dll`](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/Protobuf/System.Buffers.dll.meta)?

Yes, it does, thanks!
It appears in my case the conflict specifically comes from the com.unity.burst package.
