### ISSUE TITLE
Obtaining GLOG from Android device

### ISSUE THREAD

**Issue by MohxGames** [homuler/MediaPipeUnityPlugin#1158]
### Plugin Version or Commit ID

v0.14.1

### Unity Version

2023.2.7f1

### Your Host OS

Windows 11

### Target Platform

Android

### Description

Hello,

I have followed the tutorial and successfully gotten MediaPipe up and running on the Editor using a webcam. I have created a system to convert an XRCPUImage to a Texture2D and passed that instead of the WebCamTexture for inference. This should allow me to use the system on Android, but there is a bug somewhere in the code. 

Quite simply, the ADB is telling me that MediaPipe was aborted, and I should check the glog dump for more information. Unfortunately, I cannot find any documentation as to how to get this file on Android. I have checked 'Android > data >com.myapp' but no log exists there. I have enabled logging via 
`
Glog.Logtostderr = true;
Glog.Minloglevel = 0;
Glog.V = 3;
Glog.Initialize("MediaPipeUnityPlugin");
`
but still get no file dump on Android, nor any additional relevant information in the console.

How can I view the error I am getting with glog on an Android device?

**Comment by homuler** [comment]
Have you executed logcat?
```sh
adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"
```

**Comment by MohxGames** [comment]
Seems my issue stems from using face_mesh_desktop_live as my configuration file. FaceLandmarkFrontCPU and FaceRendererCPU are not found. Is there a specific config file built for mobile platforms provided?

**Comment by homuler** [comment]
> Here is a screenshot of the exact error telling me to reference the 'glog' files.

Please share the _complete_ log in _text_ format.

**Comment by MohxGames** [comment]
Great, I will look into these aspects, thank you.
