### ISSUE TITLE
Relative depth values of the finger joints do not meet expectations

### ISSUE THREAD

**Issue by charleshuang880730** [homuler/MediaPipeUnityPlugin#1159]
### Description

Mediapipe Unity Plugin Version: [v0.10.3](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.3)

Based on the official explanation:

- Landmarks
    
    There are 21 hand landmarks, each composed of `x`, `y` and `z` coordinates. The `x` and `y` coordinates are normalized to [0.0, 1.0] by the image width and height, respectively. The `z` coordinate represents the landmark depth, with the depth at the wrist being the origin. The smaller the value, the closer the landmark is to the camera. The magnitude of `z` uses roughly the same scale as `x`.
    
- World Landmarks
    
    The 21 hand landmarks are also presented in world coordinates. Each landmark is composed of `x`, `y`, and `z`, representing real-world 3D coordinates in meters with the origin at the hand’s geometric center.

In my observations, the values of the finger joints do not align with the official data provided. When my hand is in a clicking position(graph 1), the relative depth **`z`** value (landmarks, not world landmarks) of the fingertip of the index finger is around 0.25, which, given the angle of the index finger, I believe the ideal value should be around 0.5. I want to further understand the significance of this value. Is it representative of the actual depth difference from the wrist, with the unit being meters? Additionally, the values for the world landmarks also appear to be incorrect.

I also noticed in the Mediapipe hand paper that the range of **`z`** values for landmarks is between [-1, 1], which differs from the current official website's description. Is this due to updates in the model?

Thank you for your help.

![NTU Lab Screenshot Mar 9](https://github.com/homuler/MediaPipeUnityPlugin/assets/55727935/7d6d3477-cf80-43af-9d81-a21919669391)
![NTU Lab](https://github.com/homuler/MediaPipeUnityPlugin/assets/55727935/87b923ac-a6ae-4b91-8550-dd99fdc3d8c5)

**Comment by homuler** [comment]
First, please confirm that you can reproduce the issue using the latest version (= 0.14.1).

Then, I'm sorry but it's difficult for me to verify this kind of inquiries every time.

Could you please confirm the following:

- that the issue does not occur when using MediaPipe directly (for example, the Python version)
- that the issue occurs when using this plugin

If the issue can be reproduced using MediaPipe directly, please contact the MediaPipe development team.
If the issue only occurs with this plugin, there may be a bug, so I will investigate further.
