### ISSUE TITLE
Questions About the Tutorial on the Wiki

### ISSUE THREAD

**Issue by yog-shun** [homuler/MediaPipeUnityPlugin#1160]
### Plugin Version or Commit ID

v0.12

### Unity Version

2021.3.32.f1

### Your Host OS

Window 11

### Target Platform

UnityEditor

### Description

I've been following the tutorial on your wiki and encountered some difficulties. While working through the tutorial, I've run into some bugs that I can't seem to resolve. When trying to write var input = Packet.CreateString("Hello World!");, the compiler complains that Packet<TValue> requires 1 type argument. I also encountered related errors when attempting to copy and run the code from the tutorial. Could you please help me understand the source of these issues? How can I resolve them? Any help would be greatly appreciated.

**Comment by homuler** [comment]
Please use the latest version.

If you want to keep using v0.12.0, see https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.14.0.

**Comment by yog-shun** [comment]
Thank you very much for your reply. I forgot to consider the syntax changes caused by updates. I apologize for that oversight.

**Comment by yog-shun** [comment]
> Please use the latest version.
> 
> If you want to keep using v0.12.0, see https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.14.0.

Thank you very much for your reply. I forgot to consider the syntax changes caused by updates. I apologize for that oversight.

**Comment by yog-shun** [comment]
> Please use the latest version.
> 
> If you want to keep using v0.12.0, see https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.14.0.


I attempted to use version v.0.14, but my Unity version is 2021.3.32. After downgrading, many errors appeared, such as:

Library\PackageCache\com.unity.2d.common@8.0.2\Runtime\InternalBridge\IAnimationPreviewable.cs(5,39): error CS0246: The type or namespace name 'IAnimationPreviewable' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.ai.navigation@1.1.5\Editor\NavMeshAssetManager.cs(47,30): error CS1061: 'NavMeshSurface' does not contain a definition for 'IsPartOfPrefab' and no accessible extension method 'IsPartOfPrefab' accepting a first argument of type 'NavMeshSurface' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.memoryprofiler@1.1.0\Editor\MemorySnapshot\Cached\CachedSnapshot.cs(17,23): error CS0234: The type or namespace name 'Memory' does not exist in the namespace 'Unity.Profiling' (are you missing an assembly reference?)

Are these errors due to features that are unique to the Unity 2022 version?

**Comment by homuler** [comment]
Even if you clear the cache, will it still reproduce?
```sh
rm -rf Library
```
I believe the plugin itself will work even in Unity 2020.4.

**Comment by yog-shun** [comment]
> Even if you clear the cache, will it still reproduce?
> 
> ```shell
> rm -rf Library
> ```
> 
> I believe the plugin itself will work even in Unity 2020.4.

I tried clearing the cache, including deleting the Library folder and selecting Assets > Reimport All from the Unity menu bar to clear the cache, but the problem still persists.

**Comment by homuler** [comment]
I'm not certain about how you've imported the plugin, but I can confirm that it can be imported into an empty project, so I don't believe the issue is directly related to the plugin.
At least, the plugin itself doesn't depend on the packages mentioned in the error message.

I'm not sure, but I think it would be best to try to import it again from the initial state.

**Comment by yog-shun** [comment]
> I'm not certain about how you've imported the plugin, but I can confirm that it can be imported into an empty project, so I don't believe the issue is directly related to the plugin. At least, the plugin itself doesn't depend on the packages mentioned in the error message.
> 
> I'm not sure, but I think it would be best to try to import it again from the initial state.

When I tried to import version 0.12 of the plugin, I downloaded the package you provided, MediaPipeUnityPlugin-all.zip, and after extracting it, I directly opened it in Unity. This method may differ from the current tutorial installation method. I did not use Docker, but I successfully opened and ran the 0.12 version examples in Unity, so I considered it successful. Therefore, when I attempted to import versions 0.14.0 and 0.14.1, I also used this method. However, unlike before, I failed.

**Comment by homuler** [comment]
`MediaPipeUnityPlugin-all.zip` is a Unity project containing all the code in this repository, and the Unity version that can open it is predetermined (attempting to open it with a different version should prompt a warning).

If you simply want to open this project, please upgrade your Unity version. If you have an existing project and wish to introduce a plugin into it, please download the `com.github.homuler.mediapipe-0.14.1.tgz` or `MediaPipeUnity.0.14.1.unitypackage`.
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project.

**Comment by yog-shun** [comment]
> `MediaPipeUnityPlugin-all.zip` is a Unity project containing all the code in this repository, and the Unity version that can open it is predetermined (attempting to open it with a different version should prompt a warning).
> 
> If you simply want to open this project, please upgrade your Unity version. If you have an existing project and wish to introduce a plugin into it, please download the `com.github.homuler.mediapipe-0.14.1.tgz` or `MediaPipeUnity.0.14.1.unitypackage`. See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project.

I see, thank you for the clarification. I was planning to develop using the existing example projects and it’s difficult for me to change the Unity version I'm using. Does this mean that version 0.12 might be more suitable for my situation? Also, could you please tell me which version of the wiki I should refer to for learning if I decide to use version 0.12? Thanks for your reply!

**Comment by homuler** [comment]
>  Does this mean that version 0.12 might be more suitable for my situation?

I don't think so. Your case is the following:
> If you have an existing project and wish to introduce a plugin into it, please download the `com.github.homuler.mediapipe-0.14.1.tgz` or `MediaPipeUnity.0.14.1.unitypackage`. See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project.

**Comment by homuler** [comment]
If you don't have an existing project, then create an empty project and import the unitypackage.

**Comment by yog-shun** [comment]
> If you don't have an existing project, then create an empty project and import the unitypackage.

I am deeply grateful for your guidance. Following your instructions, I have successfully utilized the version 0.14 plugin and experimented with some of the example scenes. However, I find myself unclear on how to use AppSettings. Is it intended as a replacement for Scenes/Start Scene.unity mentioned in the wiki? If possible, could you enlighten me on how to employ it? Additionally, I have encountered the issue with synchronization errors that is listed in the problem list. I eagerly await the solution you will provide this week. I sincerely appreciate your guidance.

**Comment by yog-shun** [comment]
> > could you enlighten me on how to employ it?
> 
> Rather, I'd like you to ask about unclear parts (please create a new issue). I'll answer them. In some cases, when you need to edit the AppSettings, what you should do will be logged at runtime.
> 
> https://github.com/homuler/MediaPipeUnityPlugin/blob/019a65520881d21c5bb7f6c96e409585881c4a67/Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs#L80

ok
