### ISSUE TITLE
Can't run sync on Holistic Scene

### ISSUE THREAD

**Issue by LGuilhermeRodrigues** [homuler/MediaPipeUnityPlugin#1163]
### Plugin Version or Commit ID

v0.14.0

### Unity Version

2022.3.16f1

### Your Host OS

Windows 11 Pro

### Target Platform

UnityEditor

### Description

In the Solution Game Object or in the Settings GUI button we can choose two Running Modes, Sync or Async, in the Holistic and Pose Scenes. The problem is that if I choose Sync the code throws the error NotImplementedException: The method or operation is not implemented.
Is this the expected behavior?

### Code to Reproduce the issue

Import the unitypackage of the plugin to your project, run the Holistic Sample Scene, click on the settings button, change running mode to sync.

**Comment by homuler** [comment]
It has already been [fixed](https://github.com/homuler/MediaPipeUnityPlugin/pull/1142), but I forgot to release it, so I will release it this week.

**Comment by homuler** [comment]
It is fixed in v0.14.3.
