### ISSUE TITLE
Memory leak on PoseLandmark Segmentation in Tasks example "Pose Landmark Detection" scene

### ISSUE THREAD

**Issue by Tigran-Vardanyan** [homuler/MediaPipeUnityPlugin#1164]
### Plugin Version or Commit ID

v0.14.1

### Unity Version

2022.3.10f1

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### Target Device

Windows 10

### Build Command

Used Mediapipe example

### Bug Description

Memory leak in Unity Editor then segmentation is enabled in example Scene. Only Unity Editor restart free the memory 

### Steps to Reproduce the Bug

1. Download Mediapipe Unity Package
2. Run PoseLandmark Detection.unity Scene
3. Enable Segmentation

### Log

There are no logs

**Comment by homuler** [comment]
Thank you for reporting the issue.
It'll be fixed by #1166
