### ISSUE TITLE
build.py syntax error in line 42

### ISSUE THREAD

**Issue by DaphiFluffi** [homuler/MediaPipeUnityPlugin#117]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10, WSL 1, Ubuntu 16.04. LTS
- Target (e.g. desktop cpu, android arm64): desktop cpu, android arm64
- Bazel version: 4.0.0.
- Python version: 2.7.12
- GCC/G++ version: 5.4.0
- Unity version: 2019.4.8f1
- Android NDK version (if building for Android): 19.0
- Xcode version (if building for iOS): none

**Describe the problem**
When I run the build.py file as in the examples, I get a syntax error:

```
python build.py build --android arm64 -v
  File "build.py", line 42
    self.console.v(f"Running `{' '.join(command_list)}`")
                                                       ^
SyntaxError: invalid syntax
```
**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

- cd /mnt/c (to acces the C: drive from WSL)
- cd to MediaPipeUnityPlugin Folder
- setting the sdk and ndk paths 
- running python build.py build --desktop cpu --android arm64 -v

**Full logs**

**Additional context**

- I had to downgrade to WSL 1 because otherwise Ubuntu wouldn't run

**Comment by homuler** [comment]
Hi. Thank you for reporting the issue.
I updated [README](https://github.com/homuler/MediaPipeUnityPlugin#prerequisites).

To build this plugin, Python >= 3.9.0 and GCC/G++ >= 8.0.0 are required, so please update them first.
I'm afraid Ubuntu 16.04 is too old and it would be easier to use Ubuntu 20.04 to build it (though you may have already tried).

I understand you're trying to build native libraries for Windows 10 and Android.
On WSL, you can build native libraries for **Android**, but you cannot build native libraries for **Desktop**.
Please see [updated documents](https://github.com/homuler/MediaPipeUnityPlugin#windows) for more details.

By the way, I've updated this plugin to support Docker.
So if Docker can run on your machine, it would make the building process much easier.
