### ISSUE TITLE
Enable CPU and GPU calculators at same time.

### ISSUE THREAD

**Issue by leozzyzheng** [homuler/MediaPipeUnityPlugin#1170]
### Feature Description

I found project only inlcude gpu calculators by default, so if I need switch to cpu calculators, I need rebuild the plugin. Export both cpu and gpu calculators is harmless I think.

### Current Behaviour/State

I add the calculator by myself:

```

cc_library(
    name = "hands_calculators",
    deps = [
        "@com_google_mediapipe//mediapipe/tasks/cc/vision/hand_landmarker:hand_landmarker",
    ] + select({
        "@com_google_mediapipe//mediapipe/gpu:disable_gpu": [
            "@com_google_mediapipe//mediapipe/graphs/hand_tracking:desktop_tflite_calculators",
        ],
        "//conditions:default": [
            "@com_google_mediapipe//mediapipe/graphs/hand_tracking:mobile_calculators",
            "@com_google_mediapipe//mediapipe/graphs/hand_tracking:desktop_tflite_calculators",  <-- ADDED THIS LINE
        ],
    }),
)
 
cc_library(
    name = "pose_calculators",
    deps = [
        "@com_google_mediapipe//mediapipe/tasks/cc/vision/pose_landmarker:pose_landmarker",
    ] + select({
        "@com_google_mediapipe//mediapipe/gpu:disable_gpu": [
            "@com_google_mediapipe//mediapipe/graphs/pose_tracking:pose_tracking_cpu_deps",
        ],
        "//conditions:default": [
            "@com_google_mediapipe//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
            "@com_google_mediapipe//mediapipe/graphs/pose_tracking:pose_tracking_cpu_deps",  <-- ADDED THIS LINE
        ],
    }),
)
```

And aslo changed the `HandRendererSubgraph` usage to `HandRendererCpu` or `HandRendererGpu` to avoid registration confliction, it requires change source code of mediapipe.

Then I can use CPU calculator on my Android device, profiler shows the xnnpack delegate works a little faster than GPU delegate on lite model for pose landmark usage which surprise me a lot, I use snapdragon 8Gen 2.

**Comment by homuler** [comment]
Perhaps, in the future, only the calculator used in the Task API will be included.
The Task API allows you to select GPU or CPU at runtime.

**Comment by leozzyzheng** [comment]
> Perhaps, in the future, only the calculator used in the Task API will be included. The Task API allows you to select GPU or CPU at runtime.

So the later version will only use task API rather than the graph runner?
