### ISSUE TITLE
Using GetPixel32() in video motion capture cause gc alloc,finally lead to intermittent lag.

### ISSUE THREAD

**Issue by K4N114** [homuler/MediaPipeUnityPlugin#1171]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.10f1

### Your Host OS

Windows11

### Target Platform

UnityEditor

### Target Device

PC

### Build Command

~

### Bug Description

When running the sample 'Pose Tracking Scene' with a video input in Unity editor,I found the constantly lagging of ‘game’ window.
So I checked the profiler and found that it's 
**'TextureFrame.cs'->'ReadTextureFromOnCPU()'->'GetPixel32()'** 
cause continuous 0.8MB gc alloc each frame.
So I tried this.
```c#
public void ReadTextureFromOnCPU(Texture src)
{
  //Original
  //var textureBuffer = LoadToTextureBuffer(src);
  //SetPixels32(textureBuffer.GetPixels32());
  
  //Mine
  var textureBuffer = LoadToTextureBuffer(src);
  textureBuffer.GetRawTextureData<byte>().CopyTo(_texture.GetRawTextureData<byte>());
  _texture.Apply();
}
``` 
Which solved the problem.

### Steps to Reproduce the Bug

1.Select the 'AppSetting' prefab,switch the 'Default Image Source' to 'Video' then add a video clip below.
2.Open the 'Pose Tracking' template scene.
3.Run in editor.

### Log

~

**Comment by homuler** [comment]
fixed by #1233
