### ISSUE TITLE
'opencv2/core/version.hpp' file not found

### ISSUE THREAD

**Issue by gyumni1261** [homuler/MediaPipeUnityPlugin#1172]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.29f1

### Your Host OS

Mac0S Sonoma14.2.1

### Target Platform

Android, iOS

### [iOS Only] XCode Version

Xcode version 15.3

### Command Sequences

# Build for Desktop, Android, and iOS
python build.py build --desktop cpu --android arm64 --ios arm64 -vv

### Log

external/com_google_mediapipe/mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: 'opencv2/core/version.hpp' file not found
#include <opencv2/core/version.hpp>

### Additional Context

Hi, I've been trying to build this for AOS, IOS. 

However, when I enter command sequence like the above, it makes error "opencv2/core/version.hpp file not found."

I've already tried some of the solutions that others have inquired about opencv2 issue in links below, but it still doesn't work.

https://github.com/homuler/MediaPipeUnityPlugin/issues/147  
https://github.com/homuler/MediaPipeUnityPlugin/issues/626 

I'm using MacOS now, and through this, the installation of Opencv3 doesn't work.. We can only install Opencv4.
MacBuild does work well but IOS and AOS Build don't.

So I would like to ask you about solutions to this problem.
And if possible, could you share the Mac version of 'Docker'?

Thank you.

**Comment by homuler** [comment]
In general, please use the Package workflow to build the libraries.
https://github.com/homuler/MediaPipeUnityPlugin?tab=readme-ov-file#hammer_and_wrench-installation
> You can also make use of [the Package Workflow](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/workflows/package.yml) on Github Actions after forking this repository.
