### ISSUE TITLE
How to call other texture images for real-time rendering

### ISSUE THREAD

**Issue by ljy0808** [homuler/MediaPipeUnityPlugin#1173]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.17

### Your Host OS

windows11

### Target Platform

UnityEditor

### Description

I am a beginner in C # and I have already obtained image textures from Leapmotion's camera. I hope to improve webcamsource.cs to process the obtained image textures and use this texture for image recognition, but I don't know how to modify it. My code always displays webcam images after modification.Here is my LeapImageController code, which retrieves the Leapmotion image

### Code to Reproduce the issue

using UnityEngine;
using Leap.Unity;
using Leap;
using System;
using Mediapipe.Unity;

public class LeapImageController : MonoBehaviour
{
    private Controller _controller;
    private LeapServiceProvider _provider;
    Texture2D tex2D_left, tex2D_right;
    public RenderTexture renTex_left, renTex_right;
    public byte[] image_buffer;
    private LeapCamSource _webCamSource;

    private void Awake()
    {
        _provider = GetComponent<LeapServiceProvider>();
        if (_provider == null)
        {
            _provider = GetComponentInChildren<LeapServiceProvider>();
        }
        if (_provider != null) _controller = _provider.GetLeapController();
    
        
    }

    void Start()
    {
        if (_controller != null) _controller.ImageReady += onImageReady;
        else Debug.LogWarning("Warning - Leap controller is null");
    }

    public void onImageReady(object sender, Leap.ImageEventArgs args)
    {
        int image_size = (int)(args.image.Width * args.image.Height * args.image.BytesPerPixel);
        image_buffer = new byte[image_size*2];
        Buffer.BlockCopy(args.image.Data(Image.CameraType.LEFT), (int)args.image.ByteOffset(Image.CameraType.LEFT), image_buffer, 0, image_size);
        Buffer.BlockCopy(args.image.Data(Image.CameraType.RIGHT), (int)args.image.ByteOffset(Image.CameraType.RIGHT), image_buffer, image_size, image_size);
        

        if (tex2D_left== null)
        {
            tex2D_left = new Texture2D(args.image.Width, args.image.Height, TextureFormat.R8, false);
        }
        tex2D_left.LoadRawTextureData(args.image.Data(Leap.Image.CameraType.LEFT));
        tex2D_left.Apply();
        Graphics.Blit(tex2D_left, renTex_left);

        if (tex2D_right == null)
        {

            tex2D_right = new Texture2D(args.image.Width, args.image.Height, TextureFormat.R8, false);
        }
        tex2D_right.LoadRawTextureData(args.image.Data(Leap.Image.CameraType.RIGHT));
        tex2D_right.Apply();
        Graphics.Blit(tex2D_right, renTex_right);

        _webCamSource.SetLeapTexture(renTex_left);
    }

}

**Comment by homuler** [comment]
Please ask questions not relevant to this project elsewhere (e.g. Stackoverflow)

**Comment by ljy0808** [comment]
您发给我的信件已收到。
