### ISSUE TITLE
Problem with Hand Tracking and multiple Hands

### ISSUE THREAD

**Issue by michaelheiml** [homuler/MediaPipeUnityPlugin#1176]
### Description

Hello,

I am trying to track several hands (up to 10) in a live video feed.

It works well with 1 hand (most of the time with 2 as well), but as soon as 3 or more hands are visible, the hands "flip" rapidly when moving (e.g. hand 1 is suddenly hand 2, while hand 2 becomes hand 1 and so forth).

This breaks what I am trying to do (basically making a projected screen interactive by filming the hands above the screen, and then trigger some interaction based on where the hands are).

As I am new to MediaPipe (not to Unity though), I wonder if this is a limitation by MediaPipe itself or what I could do about this problem, or if there is any solution to this at all?

Thanks, Michael

**Comment by homuler** [comment]
How do you determine the identity of the hand? (which hand should be hand 1 or hand 2)
I'm not sure, but I guess the order of the results in the list is not guaranteed to be maintained.
