### ISSUE TITLE
Downloaded Unity Package . But when building apk for andriod the screen is greyed out . camera permission is given . 

### ISSUE THREAD

**Issue by sads32** [homuler/MediaPipeUnityPlugin#1177]
![Screenshot_20240409-234515](https://github.com/homuler/MediaPipeUnityPlugin/assets/126474085/b8e733f3-ebc0-47a8-9943-3843a6a2ef00)
### Plugin Version or Commit ID

0.14.3

### Unity Version

2022.3.19f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

Downloaded Unity Package  . But when building apk for andriod the screen is greyed out . although camera permission is given.

**Comment by homuler** [comment]
Please read the log first.
Probably you've not changed the Asset Loader Type or copied model files to StreamingAssets.
https://github.com/homuler/MediaPipeUnityPlugin/issues/1152

**Comment by sads32** [comment]
added the streamingassets folder . now it works on unity remote but still on building apk it does not change.

**Comment by homuler** [comment]
_Please read the log first._ (don't forget to enable the Development Build)
```sh
adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"
```

**Comment by sads32** [comment]
the lib is present here C:\Users\HP EliteBook A&I\My project (3)\Library\Bee\Android\Prj\Mono2x\Gradle\launcher\build\intermediates\stripped_native_libs\debug\out\lib\arm64-v8a
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/126474085/5fbfa217-5e40-480f-abf6-8f3d388e16d0)

**Comment by sads32** [comment]
the issue was that i did change arm7 to arm64 in my player settings. 
the issue is resolved now. thank you.
