### ISSUE TITLE
Installation build.py  error loading package 'mediapipe_api': Unable to find package for @rules_pkg//:pkg.bzl

### ISSUE THREAD

**Issue by aloHyomora** [homuler/MediaPipeUnityPlugin#1183]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.16f1

### Your Host OS

Windows 10

### Target Platform

Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

my local VC version 19.35.32216.1
my local WinSDK version 10.0.22000.0

### Command Sequences

build commpan python build.py build --desktop cpu --android arm64 --ios arm64 --v

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/98201682/be4d14c0-5c71-482f-8cab-52c49aae51b8)

### Log

log in command prompt'

C:\Users\aloho\Documents\GitHub\MediscLabARBasedDTx>python build.py build --desktop cpu --android arm64 --ios arm64 --v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//aloho//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
ERROR: Skipping '//mediapipe_api:mediapipe_proto_srcs': error loading package 'mediapipe_api': Unable to find package for @rules_pkg//:pkg.bzl: The repository '@rules_pkg' could not be resolved: Repository '@rules_pkg' is not defined.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'mediapipe_api': Unable to find package for @rules_pkg//:pkg.bzl: The repository '@rules_pkg' could not be resolved: Repository '@rules_pkg' is not defined.
INFO: Elapsed time: 0.680s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: mediapipe_api
Traceback (most recent call last):
  File "C:\Users\aloho\Documents\GitHub\MediscLabARBasedDTx\build.py", line 469, in <module>
    Argument().command().run()
  File "C:\Users\aloho\Documents\GitHub\MediscLabARBasedDTx\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\aloho\Documents\GitHub\MediscLabARBasedDTx\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\aloho\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//aloho//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

python 3.9.13
bazelisk version 1.19.0
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/98201682/e52d5210-0556-4d3e-9677-176c2e6659dc)

**Comment by homuler** [comment]
Please use GitHub Actions workflow.
