### ISSUE TITLE
In the current build, should there be no graphs folder in the examples folder?

### ISSUE THREAD

**Issue by dclxviclangames** [homuler/MediaPipeUnityPlugin#1186]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.16f1

### Your Host OS

Windows 11

### Target Platform

Android

### Description

I watched a lesson on how to create a bracelet on a hand and noticed differences in the API in that assembly there are no trial scenes and there is a graphs folder, I wanted to know if I somehow installed the plugin incorrectly or in the new version and there shouldn’t be a graphs folder with scripts in the examples folder
![scrnn](https://github.com/homuler/MediaPipeUnityPlugin/assets/135003207/5b0a6592-3f79-459b-ae13-085620d013dc)
![scrnn1](https://github.com/homuler/MediaPipeUnityPlugin/assets/135003207/95207834-5d5e-4a96-b7bb-6c47ca022c9d)
![scrnn2](https://github.com/homuler/MediaPipeUnityPlugin/assets/135003207/78b14f71-2d88-4c28-a0d3-136b9b8b1c17)

**Comment by homuler** [comment]
Please check the commit history or past versions.
cf. https://github.com/homuler/MediaPipeUnityPlugin/tree/v0.6.2/Assets/Mediapipe/Samples
