### ISSUE TITLE
Slow 

### ISSUE THREAD

**Issue by Densen90** [homuler/MediaPipeUnityPlugin#1188]
### Plugin Version or Commit ID

v0.14.1

### Unity Version

2022.3.20f1

### Your Host OS

MacOS

### Target Platform

Android

### Description

Hi there, I am using your plugin for BodyTracking to control a 3D avatar.

When running the code in the Editor, I roughly get a detection rate of 60 times p. second. But when deploying on android I get very different results.
On a Sony Xperia S5 II it works ok with around 30 det/sec. On a Google Pixel 3 (which is way older) it works ok with around 10-25 det/sec. But on a Huawai P20 pro it really lags and has a low detection rate, although the phone should be powerful enough. The render framerate is always much higher (>200 fps on editor and 60 fps on phone)

I am running Body tracking on "Async" with GPU inference, a preferred webcam width of 1280, a timout of 100000 microseconds, a lite model complexity annd smooth landmarks and segmentation disabled. Target is ARMv7

Do you have any idea on how it could run better? Can I have some setups or mechanisms to have the tracking reach the render framerate performance? Any help would be awesome!

**Comment by homuler** [comment]
Could you enable the profiler and investigate the cause?

**Comment by homuler** [comment]
See also https://github.com/homuler/MediaPipeUnityPlugin/issues/1169#issuecomment-2002285483

**Comment by Densen90** [comment]
Hi there, thanks for your answer. From the profiler it seems that the two most demanding operations are:

PostLateUpdate.FinishFrameRendering - Gfx.WaitForPresentOnGfxThread - Semaphore.WaitForSignal

and 

PostLateUpdate.PlayerSendFrameComplete - PlayerEndOfFrame - CoroutineDelayedCalls - Solution.Run() [Coroutine.MoveNext] [Invoke] - WeCamTexture.GetPixels32 - Webcam.ProcessImage - Semaphore.WaitForSignal

It also seems, that when setting up a testvideo instead of the webcam, it even performs worse, because the testvideo is stuttering (showing maybe 1 frame per second) and therefore the tracking is also very slow. Maybe this helps.

Thanks for your assistance, really appreciate it!

**Comment by homuler** [comment]
Will you share the screenshot like https://github.com/homuler/MediaPipeUnityPlugin/issues/768#issuecomment-1291690202 or https://github.com/homuler/MediaPipeUnityPlugin/issues/1140#issue-2107595321?

Please also let me know which scene you are running (can I assume that you're running the sample scene without change?).

> It also seems, that when setting up a testvideo instead of the webcam, it even performs worse, because the testvideo is stuttering 

Can it be the same issue as https://github.com/homuler/MediaPipeUnityPlugin/issues/1171?
