### ISSUE TITLE
AssetBundles arent loaded in Android build

### ISSUE THREAD

**Issue by Kostas-Banakakis-Rokoko** [homuler/MediaPipeUnityPlugin#119]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): WSL2 Ubuntu 20.04
- Target (e.g. desktop cpu, android arm64): arm64
- Bazel version: 4.0.0
- Python version: 3.9
- GCC/G++ version: 9.3.0
- Unity version: 2019.4.23f1
- Android NDK version (if building for Android): 18

**Describe the problem**
Camera isnt showing anything in the build in the android device (only a gray square). 
![image](https://user-images.githubusercontent.com/70262082/113989416-1793b700-9859-11eb-8836-a6255e1f0116.png)

**Steps to reproduce the issue**
Changing between cameras while the phone application is running gives the following errors

**Full logs**
2021/04/08 10:43:06.865 6851 6873 Error Unity Unable to open archive file: jar:file:///data/app/com.DefaultCompany.MediapipeUnityPlugin-xneG3GC9IvHq45tUC2SNdA==/base.apk!/assets/mediapipe
2021/04/08 10:43:06.865 6851 6873 Error Unity Mediapipe.AssetBundleManager:LoadAssetBundle()
2021/04/08 10:43:06.865 6851 6873 Error Unity Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
2021/04/08 10:43:06.865 6851 6873 Error Unity DemoGraph:Initialize()
2021/04/08 10:43:06.865 6851 6873 Error Unity DemoGraph:Initialize(GpuResources, GlCalculatorHelper)
2021/04/08 10:43:06.865 6851 6873 Error Unity <RunGraph>d__24:MoveNext()
2021/04/08 10:43:06.865 6851 6873 Error Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2021/04/08 10:43:06.865 6851 6873 Error Unity 
2021/04/08 10:43:06.865 6851 6873 Error Unity [ line 584] 
2021/04/08 10:43:06.865 6851 6873 Error Unity (Filename:  Line: 584)
2021/04/08 10:43:06.865 6851 6873 Error Unity 
2021/04/08 10:43:06.865 6851 6873 Error Unity Failed to read data for the AssetBundle 'mediapipe'.
2021/04/08 10:43:06.865 6851 6873 Error Unity Mediapipe.AssetBundleManager:LoadAssetBundle()
2021/04/08 10:43:06.865 6851 6873 Error Unity Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
2021/04/08 10:43:06.865 6851 6873 Error Unity DemoGraph:Initialize()
2021/04/08 10:43:06.865 6851 6873 Error Unity DemoGraph:Initialize(GpuResources, GlCalculatorHelper)
2021/04/08 10:43:06.865 6851 6873 Error Unity <RunGraph>d__24:MoveNext()
2021/04/08 10:43:06.865 6851 6873 Error Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2021/04/08 10:43:06.865 6851 6873 Error Unity 
2021/04/08 10:43:06.865 6851 6873 Error Unity [ line 450] 
2021/04/08 10:43:06.865 6851 6873 Error Unity (Filename:  Line: 450)
2021/04/08 10:43:06.865 6851 6873 Error Unity 
2021/04/08 10:43:06.867 6851 6873 Error Unity NullReferenceException: Object reference not set to an instance of an object.
2021/04/08 10:43:06.867 6851 6873 Error Unity   at Mediapipe.AssetBundleManager.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) [0x00000] in <00000000000000000000000000000000>:0 
2021/04/08 10:43:06.867 6851 6873 Error Unity   at DemoGraph.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
2021/04/08 10:43:06.867 6851 6873 Error Unity   at DemoGraph.Initialize (Mediapipe.GpuResources gpuResources, Mediapipe.GlCalculatorHelper gpuHelper) [0x00000] in <00000000000000000000000000000000>:0 
2021/04/08 10:43:06.867 6851 6873 Error Unity   at SceneDirector+<RunGraph>d__24.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2021/04/08 10:43:06.867 6851 6873 Error Unity   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
2021/04/08 10:43:06.867 6851 6873 Error Unity  
2021/04/08 10:43:06.867 6851 6873 Error Unity (Filename: currently not available on il2cpp Line: -1)
2021/04/08 10:43:06.867 6851 6873 Error Unity 

**Additional context**
Streaming Assets folder in Unity is empty.

**Comment by homuler** [comment]
Are there any diffs under `Packages/com.github.homuler.mediapipe/Runtime/Resources` ?

```sh
git diff Packages/com.github.homuler.mediapipe/Runtime/Resources
```

If there are any diffs, please check out those files.

If you have stared UnityEditor before build & installing native libraries and resource files, `*.meta` files are removed and AssetBundle file will not be built.

**Comment by Kostas-Banakakis-Rokoko** [comment]
Replacing the meta files seems that it has fixed this issue. 

Thank you for your quick reply.
