### ISSUE TITLE
Help me understand world position output

### ISSUE THREAD

**Issue by vo6i** [homuler/MediaPipeUnityPlugin#1190]
### Plugin Version or Commit ID

v0. 14.3

### Unity Version

2022.3.16f1

### Your Host OS

Windows 11

### Target Platform

Android

### Description

Hello, dear friend, you repo is fantastic, I run and build all repo and all work great in Android, after test samples I use wiki code, and after my scene not work, but samples work amazing, I want create simple transform object with hand transform, but not understand how I can do this, I look other issues in this repo and find one method when user change * Annotation and put transform position in Draw function, it's work but asynchronosly and sync not working, I read many u comments, read official documentation where u comments links official mediapipe api, but nothing happen, my brain explode, I'm not working early with custom plugins and api without YouTube tutorials, I'm new in ML world, 3 days ago I'm not sleep, read fragment codes in different places in issues and other repos who install you plugin and work on different projects use mediapipe. Or methods is oldest, or I not have logic uses in other scripts. How I can simple add some logic in hand tracking scene for complete my idea, I'm not understand? U can help me? Please, I'm not can sleep 🤯😧🤕😥😰

**Comment by homuler** [comment]
I don't care whether you can sleep or not, so please briefly describe the current problems you are facing and what you want to achieve.
