### ISSUE TITLE
Multi-class selfie segmenter  256 support

### ISSUE THREAD

**Issue by YutakaKubota** [homuler/MediaPipeUnityPlugin#1191]
### Feature Description

I would like to use "Multi-class selfie segmenter 256", which is one of ImageSegmentation's models. 
It wasn't in the sample, but is it supported?

**Comment by homuler** [comment]
Do you mean [this model](https://developers.google.com/mediapipe/solutions/vision/image_segmenter#multiclass-model)?
No, it's not supported yet.
The ImageSegmentation Task API is not ported (cf. https://github.com/homuler/MediaPipeUnityPlugin/tree/bd417bfd463d2da9cae0d9f9f7d29dd9ef4fabe6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision).

**Comment by YutakaKubota** [comment]
Exactly. Do you have any plans for ported?

**Comment by homuler** [comment]
I would like to do it when I have time, but I haven't set a specific schedule yet.

**Comment by YutakaKubota** [comment]
ok, thanks! I'll try it myself.

**Comment by homuler** [comment]
implemented by #1225

**Comment by YutakaKubota** [comment]
thanks great!
