### ISSUE TITLE
Memory Leakage causing lagging after some time in play mode

### ISSUE THREAD

**Issue by joshiKuldeep** [homuler/MediaPipeUnityPlugin#1192]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.27f1

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Build Command

I am not building native lib, I am just importing the mediaipipe.unity package

### Bug Description

On entering play mode, at first its starting the scene with fps more than 40. But after some time, 55-60 seconds in my case (based on system) its showing lag and drop in fps from 45 to 8 or less.

### Steps to Reproduce the Bug

1. Select any scene eg. Pose Tracking or Task
2. Enter into play mode
3. After in between 60 and 120 seconds, the fps is dropping and its starting lagging.

### Log

NA

### Screenshot/Video

![Screenshot 2024-05-22 183820](https://github.com/homuler/MediaPipeUnityPlugin/assets/36835182/acda7325-f975-4d27-bb0e-b8587110ff20)
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/36835182/56fe4765-7fa5-4941-ac35-d7797a381dcb)
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/36835182/14552466-f494-4d43-bbef-86e5f7151d00)

**Comment by homuler** [comment]
How did you determine that a memory leak is the cause?

**Comment by joshiKuldeep** [comment]
using memory profiler.

**Comment by homuler** [comment]
I mean, assuming there was a memory leak, why did you think that it was causing the delay?

**Comment by joshiKuldeep** [comment]
Oh got it. Because the spike in memory and lagging is happening simultaneously. 
Please check or let me know if I need to share something specific to expedit the solution.
