### ISSUE TITLE
cpu mode for android

### ISSUE THREAD

**Issue by ghasedak3411** [homuler/MediaPipeUnityPlugin#1195]
### Feature Description

Hello, considering that Raspberry 4 doesn't have gpu, do you develop a version for cpu mode on android operating system?

**Comment by homuler** [comment]
I believe the Task API can run on both CPU and GPU.
https://github.com/homuler/MediaPipeUnityPlugin/blob/bd417bfd463d2da9cae0d9f9f7d29dd9ef4fabe6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceDetector/FaceDetectorOptions.cs#L33-L36

In the sample app, see
https://github.com/homuler/MediaPipeUnityPlugin/blob/bd417bfd463d2da9cae0d9f9f7d29dd9ef4fabe6/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Face%20Detection/FaceDetectionConfig.cs#L19-L24

**Comment by ghasedak3411** [comment]
I need it to run on android OS on cpu, in the description also written for android on gpu.
 am i wrong and it works on android with cpu?
![cpu](https://github.com/homuler/MediaPipeUnityPlugin/assets/26714645/1c333eea-12ff-4b84-aeba-b473204b0449)

**Comment by homuler** [comment]
The sample app is written using [a legacy API](https://ai.google.dev/edge/mediapipe/solutions/guide#legacy), and to run it on Android, you need to enable the GPU (although it is probably possible to build it for the CPU, we do not currently support this).
On the other hand, I believe [the Task API](https://ai.google.dev/edge/mediapipe/solutions/guide#available_solutions) can run on both GPU and CPU. There are also [sample scenes](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Assets/MediaPipeUnity/Samples/Scenes/Tasks) using the Task API.
