### ISSUE TITLE
How to simultaneous pose recognition of multiple videos?

### ISSUE THREAD

**Issue by hhxiaohei** [homuler/MediaPipeUnityPlugin#1199]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3

### Your Host OS

mac os 14

### Target Platform

UnityEditor, Mac Standalone

### Description

The pose of a single video can be recognized normally using the effect of the example project. The current business requirement is that two videos need to be used for pose recognition at the same time, such as video file 1 on the left and video file 2 on the right, or video file 1 on the left and camera material on the right. What should you do in this case? How to improve the corresponding performance?
<img width="618" alt="image" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/8379629/fcfa5337-e0b2-49a7-aed2-b1080effba93">

**Comment by homuler** [comment]
> What should you do in this case? How to improve the corresponding performance?

I'm not exactly sure what is being asked, but I think it will involve initializing and running `CalculatorGraph` (or Task API) for each input (in this case, 2).

**Comment by hhxiaohei** [comment]
> > What should you do in this case? How to improve the corresponding performance?
> 
> I'm not exactly sure what is being asked, but I think it will involve initializing and running `CalculatorGraph` (or Task API) for each input (in this case, 2).

>> Regardless of the performance issues, how can you play 2 videos at the same time for limb detection

**Comment by homuler** [comment]
Since playing videos itself is a separate matter from this plugin, are you asking how to run inference on two input images? 
If so, as I mentioned at https://github.com/homuler/MediaPipeUnityPlugin/issues/1199#issuecomment-2185065319, you may want to initialize and run 2 `CalculatorGraph` or Task API.
Please feel free to ask if you have any specific questions.
