### ISSUE TITLE
How to detect coordinates on hand tracker for put a 3d model on android

### ISSUE THREAD

**Issue by DaliGabriel** [homuler/MediaPipeUnityPlugin#1205]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.34f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

Hey, first i want to share my congrats with your work, I consider is an amazing.
I had installed the plugin and ran correctly the solution on my android device I had followed the tutorial about detect the coordinates on the face Landmark, but I struggle with the handLandMark for detecting the coordinates on my android device, I'm not so confident with unity environment, I hope you can help me about what path I should take in terms of unity media pipe plugin, and if it's possible to develop this solution (virtual jewelry try on) or I need to develop the solution I would be happy to contribute. Thanks for read

**Comment by homuler** [comment]
> I struggle with the handLandMark for detecting the coordinates on my android device

Could you please let me know specifically what kind of problem you are facing (such as error messages)?
