### ISSUE TITLE
how to use objectTracking with MediaPipeUnityPlugin

### ISSUE THREAD

**Issue by tisaud** [homuler/MediaPipeUnityPlugin#1211]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.34f

### Your Host OS

Windows10 home

### Target Platform

UnityEditor, Android

### Description

i just want to use Object Tracking without Object Detection,but i cannot find this case in unity examples.Could you share the idea of implementation，thank you

**Comment by homuler** [comment]
In order to perform Object Tracking, Object Detection should be necessary first, so I don't understand what is being asked. Could you please explain in more detail?

**Comment by tisaud** [comment]
of course！Object Detection should be necessary first,but i Implement object Detection with Another technique（Large models in the cloud），now i can get Initial position with Object Detection results（Cloud） per second，but frequency will update very slowly，so i want to update position with local Object Tracking（with unity mediapipe）Until the next data arrives。

**Comment by homuler** [comment]
I'll close it because the Object Tracking solution is no longer supported officially.
