### ISSUE TITLE
Failed to parse config text when using box_tracking_cpu graph

### ISSUE THREAD

**Issue by tisaud** [homuler/MediaPipeUnityPlugin#1212]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.34f

### Your Host OS

Windows10 home

### Target Platform

Windows Standalone

### Description

i want to design one graph for only tracking,but i cannot load this graph(the same code can load other graph)
error : [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mediapipe.CalculatorGraphConfig: 23:70: Could not find type "type.googleapis.com/mediapipe.MotionAnalysisCalculatorOptions" stored in google.protobuf.Any.

### Code to Reproduce the issue

input_stream: "input_video"
output_stream: "camera_motion"
output_stream: "region_flow"  

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:input_video"
  output_stream: "IMAGE:downscaled_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 320
      output_height: 240
    }
  }
}

node: {
  calculator: "MotionAnalysisCalculator"
  input_stream: "VIDEO:downscaled_input_video"
  output_stream: "CAMERA:camera_motion"
  output_stream: "FLOW:region_flow"  
node_options: {
    [type.googleapis.com/mediapipe.MotionAnalysisCalculatorOptions]: {
      analysis_options {
        analysis_policy: ANALYSIS_POLICY_CAMERA_MOBILE
        flow_options {
          fast_estimation_min_block_size: 50
          top_inlier_sets: 1
          frac_inlier_error_threshold: 3e-3
          downsample_mode: DOWNSAMPLE_TO_INPUT_SIZE
          verification_distance: 5.0
          verify_long_feature_acceleration: true
          verify_long_feature_trigger_ratio: 0.1
          tracking_options {
            max_features: 500
            adaptive_extraction_levels: 2
            min_eig_val_settings {
              adaptive_lowest_quality_level: 2e-4
            }
            klt_tracker_implementation: KLT_OPENCV
          }
        }
      }
    }
  }
}

**Comment by homuler** [comment]
That's because the distributed library does not include the `MotionAnalysisCalculator`. To get it working, you need to rebuild it with that included.
```diff
diff --git a/mediapipe_api/BUILD b/mediapipe_api/BUILD
index 3901425..d36ba2c 100644
--- a/mediapipe_api/BUILD
+++ b/mediapipe_api/BUILD
@@ -281,6 +281,7 @@ cc_library(
         "@mediapipe//mediapipe/calculators/core:packet_presence_calculator",
         "@mediapipe//mediapipe/calculators/core:flow_limiter_calculator",
         "@mediapipe//mediapipe/calculators/image:image_transformation_calculator",
+        "@mediapipe//mediapipe/calculators/video:motion_analysis_calculator",
     ] + select({
         "@mediapipe//mediapipe/gpu:disable_gpu": [],
         "//conditions:default": [
```

You can build it using [the Package workflow](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml) (see also https://github.com/homuler/MediaPipeUnityPlugin?tab=readme-ov-file#hammer_and_wrench-installation).
