### ISSUE TITLE
Install docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile error

### ISSUE THREAD

**Issue by Daniel70-liu** [homuler/MediaPipeUnityPlugin#1214]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2021.6.6f1

### Your Host OS

window 10 Pro

### Target Platform

Windows Standalone

### Command Sequences

Follow the installation steps 3,
When I execute in Windows Powershell: 
docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile 
I don’t know how to solve the problems I encountered. Can anyone help me?

### Log

PS C:\Users\Daniel\MediaPipeUnityPlugin> docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile
Sending build context to Docker daemon  13.95MB
Step 1/59 : ARG NODE_VERSION=18.17.1
Step 2/59 : ARG PYTHON_VERSION=3.9.9
Step 3/59 : ARG ANDROID_SDK_VERSION=30
Step 4/59 : ARG ANDROID_NDK_VERSION=21.4.7075529
Step 5/59 : FROM mcr.microsoft.com/windows/servercore:ltsc2019 as base
 ---> b51a50ce03f1
Step 6/59 : SHELL ["cmd", "/C"]
 ---> Using cache
 ---> 28b6b1d5f358
Step 7/59 : RUN mkdir C:\TEMP
 ---> Using cache
 ---> aeac0eda7005
Step 8/59 : FROM base as msys2
 ---> aeac0eda7005
Step 9/59 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 37fed6161f7c
Step 10/59 : RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;   Invoke-WebRequest -UseBasicParsing -uri "https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe" -OutFile msys2.exe;   .\msys2.exe -y -oC:\;   Remove-Item msys2.exe ;   function msys() { C:\msys64\usr\bin\bash.exe @('-lc') + @Args; }   msys ' ';   msys 'pacman --noconfirm -Syuu';   msys 'pacman --noconfirm -Syuu';   msys 'pacman --needed --noconfirm -S git patch unzip zip p7zip';   msys 'pacman --noconfirm -Scc'
 ---> Using cache
 ---> 4380e2b8af58
Step 11/59 : FROM msys2 as builder
 ---> 4380e2b8af58
Step 12/59 : SHELL ["cmd", "/C"]
 ---> Using cache
 ---> 422452675ecd
Step 13/59 : ARG NODE_VERSION
 ---> Using cache
 ---> d773cdafdc7a
Step 14/59 : RUN setx path "C:\msys64\usr\bin;%PATH%"
 ---> Using cache
 ---> 1c9abcee9f66
Step 15/59 : ARG CHANNEL_URL=https://aka.ms/vs/16/release/channel
 ---> Using cache
 ---> 1908ae7ee0c4
Step 16/59 : RUN curl --retry 4 --connect-timeout 10 -L https://nodejs.org/dist/v%NODE_VERSION%/node-v%NODE_VERSION%-x64.msi -o C:\TEMP\node-install.msi &&     start /wait msiexec.exe /i C:\TEMP\node-install.msi /l*vx "%TEMP%\MSI-node-install.log" /qn ADDLOCAL=ALL &&     del C:\TEMP\node-install.msi &&     curl --retry 4 --connect-timeout 10 -L %CHANNEL_URL% -o C:\TEMP\VisualStudio.chman &&     curl --retry 4 --connect-timeout 10 -L https://aka.ms/vs/16/release/vs_buildtools.exe -o C:\TEMP\vs_buildtools.exe &&     C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache         --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"         --channelUri C:\TEMP\VisualStudio.chman         --installChannelUri C:\TEMP\VisualStudio.chman         --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended &&     curl --retry 4 --connect-timeout 10 -L https://aka.ms/vs/16/release/vc_redist.x64.exe -o C:\TEMP\vc_redist.x64.exe &&     start /wait C:\TEMP\vc_redist.x64.exe /install /quiet /norestart &&     del C:\TEMP\vc_redist.x64.exe
 ---> Running in 80ad9b1bd26e
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.3M  100 30.3M    0     0  7625k      0  0:00:04  0:00:04 --:--:-- 7629k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Failed to connect to download.visualstudio.microsoft.com port 443 after 10008 ms: Timeout was reached
Warning: Problem : timeout. Will retry in 1 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Failed to connect to download.visualstudio.microsoft.com port 443 after 10000 ms: Timeout was reached
Warning: Problem : timeout. Will retry in 2 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Failed to connect to download.visualstudio.microsoft.com port 443 after 10000 ms: Timeout was reached
Warning: Problem : timeout. Will retry in 4 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Failed to connect to download.visualstudio.microsoft.com port 443 after 10000 ms: Timeout was reached
Warning: Problem : timeout. Will retry in 8 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Failed to connect to download.visualstudio.microsoft.com port 443 after 10000 ms: Timeout was reached
The command 'cmd /C curl --retry 4 --connect-timeout 10 -L https://nodejs.org/dist/v%NODE_VERSION%/node-v%NODE_VERSION%-x64.msi -o C:\TEMP\node-install.msi &&     start /wait msiexec.exe /i C:\TEMP\node-install.msi /l*vx "%TEMP%\MSI-node-install.log" /qn ADDLOCAL=ALL &&     del C:\TEMP\node-install.msi &&     curl --retry 4 --connect-timeout 10 -L %CHANNEL_URL% -o C:\TEMP\VisualStudio.chman &&     curl --retry 4 --connect-timeout 10 -L https://aka.ms/vs/16/release/vs_buildtools.exe -o C:\TEMP\vs_buildtools.exe &&     C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache         --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"         --channelUri C:\TEMP\VisualStudio.chman         --installChannelUri C:\TEMP\VisualStudio.chman         --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended &&     curl --retry 4 --connect-timeout 10 -L https://aka.ms/vs/16/release/vc_redist.x64.exe -o C:\TEMP\vc_redist.x64.exe &&     start /wait C:\TEMP\vc_redist.x64.exe /install /quiet /norestart &&     del C:\TEMP\vc_redist.x64.exe' returned a non-zero code: 28

### Additional Context

![螢幕擷取畫面 2024-07-12 000303](https://github.com/homuler/MediaPipeUnityPlugin/assets/56061895/3ed0b060-8be6-4144-b786-c982032ee874)

**Comment by homuler** [comment]
Since it's a network issue, there's nothing we can do on our end.
If there are no problems with your network environment, I think it will work if you try again after some time.

Also, it's difficult for me to follow up on individual environment issues, so if you want to build the plugin yourself and can't do it on your local machine, please use the GitHub Actions workflow (see https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation).

**Comment by Daniel70-liu** [comment]
I want to apply gesture judgment. Do I have to build a plugin for this job?
Also, I executed :  docker build --no-cache -t mediapipe_unity:latest . -f docker/windows/x86_64/Dockerfile again. The program was stuck in the fifth step. The following is the execution screen, and C:\ProgramData\Docker\tmp genera
![螢幕擷取畫面 2024-07-13 233754](https://github.com/user-attachments/assets/147f325d-d1ea-4baf-a4a3-8d764b75058c)
ted files

**Comment by homuler** [comment]
Please use GitHub Actions workflow to build the plugin.
