### ISSUE TITLE
Image source settings

### ISSUE THREAD

**Issue by TulgaTDev** [homuler/MediaPipeUnityPlugin#1215]
### Description

Why is Horizontally Flipped option is not working? A year ago it was working fine but its not working as expected in latest release. Currently tested it on holistic sample scene.

**Comment by homuler** [comment]
Please use the bug report format and describe the issues and the environment that are occurring more specifically.
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
