### ISSUE TITLE
The tracking of hand and pose is not possible.

### ISSUE THREAD

**Issue by mjcjc** [homuler/MediaPipeUnityPlugin#1216]
### Description
Plugin or Commit ID
v0.14.3

Unity Version
2020.3.48f1

Host OS
Windows 10 Pro

Target Platform
UnityEditor, 안드로이드

Description
I'm making a script that uses hand to judge gestures.
I just used the scene in the example to run it, but hand and 
pose does not work.
I don't know why.
![hand](https://github.com/user-attachments/assets/b5f54f83-069f-428a-88e8-1f99da6ec45c)
![solution](https://github.com/user-attachments/assets/4ec43434-0ba5-4446-b66f-db269fe9962d)

**Comment by homuler** [comment]
> I just used the scene in the example to run it, but hand and pose does not work.

Can you please describe exactly what is happening? (what does "does not work" exactly mean?)
It would be helpful if you compare the expected behavior with what is actually occurring.
If there are any error logs, please share those as well.
