### ISSUE TITLE
The issue with launching simultaneously with OBS Studio

### ISSUE THREAD

**Issue by emoto-yasushi** [homuler/MediaPipeUnityPlugin#1222]
### Description

Hi,

MediapipeUnityPlugin works well in many situations. 
However, when I launched MediapipeUnityPlugin simultaneously with a software called OBS Studio, the screen did not display, and it didn't work. 
Since OBS Studio is a software used by many live streamers, I would like to know if there is a way to use them together.

I tested it with MediapipeUnityPlugin v0.14.4, Unity 2022.3.6f1, and Windows 11 Home.

Thank you for your work.

**Comment by homuler** [comment]
Do you mean that the sample app doesn't run simultaneously with OBS?
Could you attach a screenshot or something similar that shows the problem?

**Comment by emoto-yasushi** [comment]
I tested the sample scene for Face Landmark Detection.
Here are the error messages and images.

![image](https://github.com/user-attachments/assets/62c1d4b3-43b1-420b-9054-bbd4de9a01cd)

```
Could not start graph
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Mediapipe.Unity.WebCamSource/<Play>d__41:MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs:197)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Could not pause pControl
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Mediapipe.Unity.WebCamSource/<Play>d__41:MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs:197)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

TimeoutException: Failed to start WebCam
Mediapipe.Unity.WebCamSource+<WaitForWebCamTexture>d__48.MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs:261)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <b41119cc6741409ea29f63c7f98de938>:0)
```

**Comment by homuler** [comment]
Is the camera used by OBS not selected?
https://github.com/homuler/MediaPipeUnityPlugin/blob/e007dd75335ba8a9daba32ba71c4c641f257ec70/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs#L135

**Comment by emoto-yasushi** [comment]
Yes. It worked fine after removing the camera from OBS.

**Comment by homuler** [comment]
So may I close this issue?
