### ISSUE TITLE
FaceLandmarkListWithIrisAnnotation: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by yuwei-chen-lm** [homuler/MediapipeUnityPlugin#1223]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.16

### Your Host OS

win11, note book camera

### Target Platform

UnityEditor

### Build Command

-

### Bug Description

// bug: Collection was modified; enumeration operation may not execute.
// https://stackoverflow.com/questions/604831/collection-was-modified-enumeration-operation-may-not-execute

// change (add ToList() to copy a new list)

in class FaceLandmarkListWithIrisAnnotation.cs:

var enumerator = landmarks.ToList().GetEnumerator();
var faceLandmarks = new List<T>(_FaceLandmarkCount);
for (var i = 0; i < _FaceLandmarkCount; i++)
{
	if (enumerator.MoveNext())
	{
		faceLandmarks.Add(enumerator.Current);
	}
}

### Steps to Reproduce the Bug

run scene tasks/Face Landmark Detection, sometimes the error occurs

### Log

-

**Comment by homuler** [comment]
Could you attach the _complete_ error log?

**Comment by homuler** [comment]
Did you modify some code?

**Comment by homuler** [comment]
This might be because the lock is not acquired here.
https://github.com/homuler/MediaPipeUnityPlugin/blob/e007dd75335ba8a9daba32ba71c4c641f257ec70/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/FaceLandmarkerResultAnnotationController.cs#L31
