### ISSUE TITLE
IOS pose tracking, camera won't start

### ISSUE THREAD

**Issue by likwifi** [homuler/MediaPipeUnityPlugin#1226]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.10f1

### Your Host OS

mac OS M2

### Target Platform

iOS

### Description

Hello,
I'm trying to run Pose Tracking solution on IOS 17.5.1
However after building and running it IOS device Xcode throws an exception saying
and camera won't start.
here is the screenshot.

Although this works fine at an Editor. 
Also app doesn't even ask for permission to use camera, even though camera usage description is specified.

![IMG_5201](https://github.com/user-attachments/assets/d13f42cf-cfaa-4a1b-a5cc-2137f9ba5b02)

> StreamingAssetsResourceManager and copying the required resources under StreamingAssets, for example.
> Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> UnityEngine.Object:Instantiate(T)
> Mediapipe.Unity.Sample.Solution:FindBootstrap()
> Mediapipe.Unity.Sample.<Start>d__9:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
> 
> NullReferenceException: Object reference not set to an instance of an object.
>   at Mediapipe.Unity.Sample.ImageSourceSolution1[T].Pause () [0x00000] in <00000000000000000000000000000000>:0 
>   at Mediapipe.Unity.Sample.UI.Modal.OpenAndPause (UnityEngine.GameObject contents) [0x00000] in <00000000000000000000000000000000>:0 
>   at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 

### Code to Reproduce the issue

Download latest release run pose tracking on iPhone.

**Comment by homuler** [comment]
> StreamingAssetsResourceManager and copying the required resources under StreamingAssets, for example.

The full message is here.
https://github.com/homuler/MediaPipeUnityPlugin/blob/7cfa66677d8baa582a8f74a5a1b3e3c70499dc26/Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs#L60-L61

So change the `assetLoaderType`
https://github.com/homuler/MediaPipeUnityPlugin/blob/7cfa66677d8baa582a8f74a5a1b3e3c70499dc26/Assets/MediaPipeUnity/Samples/Scenes/AppSettings.asset#L17

and copy the dependent files (e.g. `*.tflite`) to `Assets/StreamingAssets` before building the app.
If you've downloaded `MediaPipeUnityPlugin-all.zip` and using it, then all the required files should be already placed under `Assets/StreamingAssets`.

See also https://github.com/homuler/MediaPipeUnityPlugin/issues/681#issuecomment-1200339913.

**Comment by likwifi** [comment]
Thanks
