### ISSUE TITLE
In case you were wondering why your build doesn't work on other devices

### ISSUE THREAD

**Issue by ericosborne97** [homuler/MediaPipeUnityPlugin#1229]
### Plugin Version or Commit ID

x

### Unity Version

x

### Your Host OS

x

### Target Platform

Windows Standalone

### Build Command

x

### Bug Description

When you try to build for windows you may notice that the build works on your machine. However when you try to transfer the build to another machine the handtracking/other features do not work. This is because the application is using a few files from your local appdata. You can work around this by doing the following.
1) Open the StreamingAssetsResourceManager.cs
2) Replace this part starting at line 22 with my code

    public StreamingAssetsResourceManager(string path) : base(PathToResourceAsFile, GetResourceContents)
    {
      // It's safe to update static members because at most one RsourceManager can be initialized.
      _RelativePath = path;
      _AssetPathRoot = Path.Combine(Application.streamingAssetsPath, _RelativePath);
      _CachePathRoot = Path.Combine(Application.dataPath+"/<YOUR PROJECT NAME HERE GUYS>", _RelativePath).Replace("\\","/");
    }

3) Now search "AppSettings" in unity to make sure you have streaming assets enabled under asset loader type. Also pro tip set the hand tracking mode on the "Solution" game object to Sync this will increase performance immeasurably.

4) Now build with linux, windows, and mac

5)Now search file explorer for 
C:\Users\YOURUSERNAME\AppData\LocalLow\DefaultCompany\Hand Tracking Test
of course it will be different for your system. But basically you should see a folder of files such as palm_detection_full.bytes and several others. Copy this folder and paste it into your build folder called<PROJECTNAME>_Data

6) If it still doesn't work check the debug log while running the build for FILENOTFOUND that should help you narrow down what got messed up

7) Now this is more of a bandaid solution for now but it worked for me. Keep in mind that you'll have to copy the folder each time you create a new build

### Steps to Reproduce the Bug

x

### Log

x

**Comment by homuler** [comment]
If you really think it's a bug, please enter `Plugin Version or Commit ID`, `Unity Version`, `Steps to Reproduce the Bug` and `Log` at least.

With the current information, I can't say for sure, but it seems like you simply haven't prepared the `StreamingAssets` folder.
