### ISSUE TITLE
Handling and understanding GpuBuffer outputs

### ISSUE THREAD

**Issue by stoutut** [homuler/MediaPipeUnityPlugin#1236]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.17f1

### Your Host OS

Windows 11 Home

### Target Platform

Android, iOS

### Description

Hello!

While trying to use this plugin, I've been trying to handle graphs with a `GpuBuffer` output.
My goal is simply to render them on the screen while also minimizing the amount of interaction beetween CPU and GPU; So, if my understanding is correct, the conversion of `GpuBuffers` to `ImageFrames` should preferably be avoided.
The closest I found to this objective in your sample scenes is the `MediaPipe Video` scene, while using its OpenGL ES configuration. 
While I was able to learn from your code and produce a similar result on my end, I still can't understand two parts of your code.

First, I was wondering why we can't retrieve a `GpuBuffer` from its packet. I saw that the usual method used is part of an extension class that handles every type case by case, and no implementation for `GpuBuffer`s is present as of yet. Would you mind explaining me why?

Second, in the corresponding graph (`official_hand_tracking_demo_opengles.txt`), you eventually add through scripting a new input side packet called `"DESTINATION:destination_buffer"`, to which you give the `GpuBuffer` of the destination texture.
If I understand correctly, this allows the calculator to directly write on this buffer the results of the graph. However, I couldn't find any reference to this side input packet neither in your project nor in MediaPipe's code.
I was wondering how you made it work? Are you using a slightly modified version of MediaPipe or did I simply miss the part where the `"DESTINATION"` tag is implemented?

Thank you for your time and effort.

**Comment by homuler** [comment]
> I was wondering why we can't retrieve a GpuBuffer from its packet. 

There are 2 reasons for this.
The primary reason is that there was no case where I needed to use `GpuBuffer` for output. If we want to display the output directly, we can pass a `Texture` to MediaPipe and have it write directly to it, so there is no need to extract the result from `GpuBuffer` again.
Even in other cases, I thought it would be usual to share the `Texture` with MediaPipe using methods like `CreateExternalTexture` (regardless of whether it is possible at present).

The other reason is that a new Task API was introduced during that time, which allows data to be exchanged using a class called `Image` (an abstraction of both `ImageFrame` and `GpuBuffer`).

> Are you using a slightly modified version of MediaPipe

Yes, here is the patch.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d043b906feae4bc8bad60910d3cb23eb6c120ec1/third_party/mediapipe_extension.diff#L90-L171
