### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Almazikman** [homuler/MediaPipeUnityPlugin#124]
**System information**
- OS Platform and Distribution: MacBook Air (11-inch, Mid 2012), macOS Catalina 10.15.7 (19H524)
- Target Platform: Android
- Mobile Device: Redmi 4X (Custom Android 9)
- MediaPipeUnityPlugin version or commit id: e65a730b4c76d28cf70e374b9d68536add4b16a2
- Bazel version: 3.7.2
- GCC/G++ version: 12.0.0
- Android NDK version: 19.0.5232133 (Default Unity's NDK)

**Describe the current behavior**
I managed to build template scene to android and sometimes it even worked but when I switched modes or cameras - it usually just doesn't do anything and sometimes just crashed. I tried to erase mediapipe and install it again but it didn't help. And usually my build crashed on android, but not always. Sometimes it works, but all I need to do is switch camera and it'll crash or just stop working.

**Describe the expected behavior**
It had to not to crash 3 from 4 tries and work fine especially after switching camera. 

**Steps to reproduce the issue**
I did all installation steps correctly, but somehow it works that way and I dunno how to reproduce it.

**Full logs**
I tried to launch application for 4 times. Here are my logs:

First try crashlog:
https://appp.me/roZCEA

Second try crashlog:
https://appp.me/zXu2YD

Third try crashlog:
https://appp.me/ISVbvc

And finally it worked and after this I switched camera:
https://appp.me/bTIxjk

**Additional context**
My build size is around 230 mb! How to reduce it?

**Comment by homuler** [comment]
Have you changed the scripting backend to Mono?

P.S. please never create the same issue repeatedly.

**Comment by Almazikman** [comment]
Yeah, it was Mono. You think I need to change it to Il2CPP?

**Comment by Almazikman** [comment]
Changed to IL2CPP, it's still crashing with these logs:
https://pastebin.com/PhTSwNyA

**Comment by Almazikman** [comment]
Selected ARM64 architecture and now it's trying to start for a minute and crashing after it. Logs:
https://pastebin.com/agBgjMad

**Comment by homuler** [comment]
> Yeah, it was Mono. You think I need to change it to Il2CPP?

I don't know it matters if the backend is IL2CPP or Mono, but if you've changed something, please write all the things what you have done to build apk here (including build command (e.g. `python build --android arm64 -v`)).

> Steps to reproduce the issue
I did all installation steps correctly, but somehow it works that way and I dunno how to reproduce it.

Again, I cannot help you if I don't know how to reproduce the issue, so please write down all the steps you did, if you don't know which step is essential.

By the way, does this problem still occur if you remove calculators other than those for face detection? (note that you need to build native libraries again)
```diff
diff --git a/mediapipe_api/BUILD b/mediapipe_api/BUILD
index ac434d9..6c5a4b2 100644
--- a/mediapipe_api/BUILD
+++ b/mediapipe_api/BUILD
@@ -103,16 +103,6 @@ cc_library(
             "@com_google_mediapipe//mediapipe/gpu:gl_scaler_calculator",
             "@com_google_mediapipe//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",
             "@com_google_mediapipe//mediapipe/graphs/face_detection:desktop_live_gpu_calculators",
-            "@com_google_mediapipe//mediapipe/graphs/face_mesh:desktop_live_gpu_calculators",
-            "@com_google_mediapipe//mediapipe/graphs/hair_segmentation:mobile_calculators",
-            "@com_google_mediapipe//mediapipe/graphs/hand_tracking:mobile_calculators",
-            "@com_google_mediapipe//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps",
-            "@com_google_mediapipe//mediapipe/graphs/instant_motion_tracking:instant_motion_tracking_deps",
-            "@com_google_mediapipe//mediapipe/graphs/iris_tracking:iris_tracking_gpu_deps",
-            "@com_google_mediapipe//mediapipe/graphs/object_detection:mobile_calculators",
-            "@com_google_mediapipe//mediapipe/graphs/object_detection_3d:mobile_calculators",
-            "@com_google_mediapipe//mediapipe/graphs/pose_tracking:upper_body_pose_tracking_gpu_deps",
-            "@com_google_mediapipe//mediapipe/graphs/tracking:mobile_calculators",
         ],
     }),
 )
```

**Comment by Almazikman** [comment]
I reinstall everything on my ubuntu and now it works good, but I have some questions. I'll better create a new issue
