### ISSUE TITLE
How to get body id when running Pose Landmark Detection

### ISSUE THREAD

**Issue by JoeManba** [homuler/MediaPipeUnityPlugin#1241]
### Feature Description

When I running Samples/Tasks/Pose Landmark Detection scene,Set numPoses >1,How can i get player id like Kinect?

**Comment by homuler** [comment]
It seems that this feature is not supported by [PoseLandmarker](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker), so it cannot be done.
Please contact the MediaPipe team for more details.
