### ISSUE TITLE
Plans to Use PoseWorldLandmark for Controlling Multiple Annotations in a Room via Task APIs?

### ISSUE THREAD

**Issue by isoroku56** [homuler/MediaPipeUnityPlugin#1249]
### Plugin Version or Commit ID
v0.14.4
### Unity Version
2022.3.25f1

### Description
I particularly enjoy using the scene at MediaPipeUnity/Samples/Scenes/Tasks/PoseLandmark/PoseLandmarkDetection, which allows simultaneous pose estimation for multiple people using NumPoses. While the scene at MediaPipeUnity/Samples/Scenes/PoseTracking/PoseTracking does not support multiple people, it does allow placing poses in a 3D space using WorldLandmark within a Room. I would like to know if there are any plans to implement a similar feature in the Tasks scene, where we could set up a Room and observe poses moving in 3D space.

Thank you very much for your consideration.

**Comment by homuler** [comment]
I thought it wasn't necessary, so I deleted it. The origin of the world coordinate system is the hip, so there's no point in displaying more than one person, and I don't think I'll implement this feature.
Of course, it's possible to move and display based on the hip position from the `Landmarks`, but I think it's too complex as a sample.

cf. https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/python
> The output contains the following world coordinates (`WorldLandmarks`):
>
> - `x`, `y`, and `z`: Real-world 3-dimensional coordinates in meters, with the midpoint of the hips as the origin.
