### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'mediapipe_jni'.

### ISSUE THREAD

**Issue by Myfxyer** [homuler/MediaPipeUnityPlugin#1254]
### Description

08-20 19:20:34.263  7175  7200 E Unity   : DllNotFoundException: Unable to load DLL 'mediapipe_jni'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_jni' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "mediapipe_jni" not found
08-20 19:20:34.263  7175  7200 E Unity   :   at Mediapipe.SafeNativeMethods.mp__SetCustomGlobalPathResolver__P (Mediapipe.ResourceManager+PathResolver resolver) [0x00000] in <00000000000000000000000000000000>:0
08-20 19:20:34.263  7175  7200 E Unity   :   at Mediapipe.ResourceManager..ctor () [0x00000] in <00000000000000000000000000000000>:0
08-20 19:20:34.263  7175  7200 E Unity   :   at AssetBundleLoader.Start () [0x00000] in <00000000000000000000000000000000>:0
08-20 19:20:34.263  7175  7200 E Unity   :
08-20 19:20:38.212  7175  7175 W Unity   : Timeout while trying to pause the Unity Engine.
08-20 19:20:38.213  7175  7175 I Unity   : windowFocusChanged: true
08-20 19:20:38.216  7175  7175 I Unity   : android.permission.CAMERA granted
08-20 19:20:38.217  7175  7175 D Unity   : onActivityResumed: com.unity3d.player.UnityPlayerActivity@60068df
08-20 19:20:38.217  7175  7175 I Unity   : onResume

I dont know i can't read the dll of the library

**Comment by homuler** [comment]
Please write down the steps to reproduction the issue (where did you download the plugin, and how did you build and run it?).
That aside, there’s a high chance that the same issue has already been reported in the past, so I recommend checking [previous issues.](https://github.com/homuler/MediaPipeUnityPlugin/issues?q=is%3Aissue+Unable+to+load+DLL+%27mediapipe_jni%27+is%3Aclosed).
