### ISSUE TITLE
iOS Metal support

### ISSUE THREAD

**Issue by chrisError** [homuler/MediaPipeUnityPlugin#126]
currently the only way to get this plug in to work on device on iOS is to uncheck Auto Graphics API and OpenGLES3 to the list. The latest LTS version of Unity has now removed that option, so there is no choice, it's just Metal support only.
Is there any plan, and is it even possible, to make this plug in work with just metal?

(and thanks again for making such an amazing plug in!)

**Comment by chrisError** [comment]
p.s. maybe it can alreayd run just using Metal and I am doing something wrong :)

**Comment by homuler** [comment]
It is listed in TODO list, but not implemented yet.
https://github.com/homuler/MediaPipeUnityPlugin#todo
> use CVPixelBuffer on iOS

And I think it's possible to work with Metal API.

**Comment by chrisError** [comment]
thanks for the reply @homuler 
whe I try doing a compile through XCode using Auto Graphics API / Metal only I always get the following compilation errors (which are then resolved by adding Open GL ES3 to the API list)
![image](https://user-images.githubusercontent.com/286684/115264644-66313300-a12e-11eb-8906-dfe6f6e4a691.png)
`Undefined symbols for architecture arm64:
  "_glFlush", referenced from:
      _UnsafeNativeMethods_glFlush_m31511D22964C1C47F83A18E543AD163B2EEE80CD in MediaPipeSDK2.o
     (maybe you meant: _UnsafeNativeMethods_glFlush_m31511D22964C1C47F83A18E543AD163B2EEE80CD)
  "_glBlitFramebuffer", referenced from:
      _PreparePresentGLES in GlesHelper.o
  "_glDeleteTextures", referenced from:
      _DestroyRenderingSurfaceGLES in GlesHelper.o
  "_glRenderbufferStorage", referenced from:
      _CreateSharedDepthbufferGLES in GlesHelper.o
  "_glRenderbufferStorageMultisample", referenced from:
      _CreateRenderingSurfaceGLES in GlesHelper.o
      _CreateSharedDepthbufferGLES in GlesHelper.o
  "_glResolveMultisampleFramebufferAPPLE", referenced from:
      _PreparePresentGLES in GlesHelper.o
  "_glRenderbufferStorageMultisampleAPPLE", referenced from:
      _CreateRenderingSurfaceGLES in GlesHelper.o
      _CreateSharedDepthbufferGLES in GlesHelper.o
  "_glDeleteFramebuffers", referenced from:
      _DestroySystemRenderingSurfaceGLES in GlesHelper.o
      _DestroyRenderingSurfaceGLES in GlesHelper.o
  "_glFramebufferTexture2D", referenced from:
      _CreateRenderingSurfaceGLES in GlesHelper.o
  "_glReadPixels", referenced from:
      _UnsafeNativeMethods_glReadPixels_mB6CD520FF4A77019A700CDEB6646E61DED73EC85 in MediaPipeSDK2.o
     (maybe you meant: _UnsafeNativeMethods_glReadPixels_mB6CD520FF4A77019A700CDEB6646E61DED73EC85)
  "_glDeleteRenderbuffers", referenced from:
      _DestroySystemRenderingSurfaceGLES in GlesHelper.o
      _DestroyRenderingSurfaceGLES in GlesHelper.o
      _DestroySharedDepthbufferGLES in GlesHelper.o`

**Comment by manisharan-ys** [comment]
@chrisError  Actually in unity 2019, with Metal Graphics API selected in build settings, its working fine on iPhone 12. But its failing to work in unity 2020 for some reason, with above gl errors. As @homuler suggested me, build native libraries before opening unity editor, and use unity 2019. It should work.
