### ISSUE TITLE
Add another scene like a ring virtual try on

### ISSUE THREAD

**Issue by DaliGabriel** [homuler/MediaPipeUnityPlugin#1260]
### Plugin Version or Commit ID

v0.14.4

### Unity Version

2022.3.34f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

Hey @homuler I hope you are all right. I want to ask you if do you think it would be a good idea to add a ring virtual try on the scenes example to help the developers about how to use the Handlanmarks (in this case)  and show how to put 3d objects on the landmarks and how to handle it. I have the solution. Let me know what do you think about it. Cheers, and thank you for help the unity community with your abilities.

**Comment by homuler** [comment]
Thank you for your suggestion.
I think it's great that applied examples are being provided. However, the maintenance cost would increase, so it would be appreciated if you publish them in your own repositories for now.
