### ISSUE TITLE
translation from normalized coordinates to coordinates of 3D space Unity

### ISSUE THREAD

**Issue by nemajor1** [homuler/MediaPipeUnityPlugin#1263]
### Description

Hello, i have a problem with translation from normalized coordinates to coordinates of 3D space Unity. Or rather, fingertips, I am developing my own solution based on this plugin, I will be glad to contribute, thanks for your help

**Comment by homuler** [comment]
> i have a problem with translation from normalized coordinates to coordinates of 3D space Unity

Please describe that problem.
