### ISSUE TITLE
Windows 10 build error

### ISSUE THREAD

**Issue by sharyu** [homuler/MediaPipeUnityPlugin#127]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: bazel 4.0.0
- Python version: Python 3.9.4
- CMake version: cmake version 3.20.1
- Unity version: 2019.4.11f1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
I follow the setup steps for Windows(Desktop/UnityEditor), and after run build command, get error:
`ERROR: C:/_bzl/ru6tpeoz/external/com_google_mediapipe/third_party/BUILD:97:15: @com_google_mediapipe//third_party:opencv_cmake: no such attribute 'shared_libraries' in 'cmake' rule`

**Steps to reproduce the issue**
`python build.py build --desktop cpu -v`

**Full logs**
```
F:\unityproj\MediaPipeUnityPlugin-master>python build.py build --desktop cpu -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=D://Python//Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/ru6tpeoz/external/rules_foreign_cc/workspace_definitions.bzl:6:6: `@rules_foreign_cc//:workspace_definitions.bzl` has been replaced by `@rules_foreign_cc//foreign_cc:repositories.bzl`. Please use the updated source location
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 654 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 0.631s, Critical Path: 0.08s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget`
Feeds used:
  C:\Users\DELL\.nuget\packages\
  https://api.nuget.org/v3/index.json

F:\unityproj\MediaPipeUnityPlugin-master\packages.config 中列出的所有程序包均已安装。
DEBUG (build.py): Copying '.nuget\Google.Protobuf.3.15.6\lib\netstandard2.0\Google.Protobuf.dll' to 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll' to 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll' to 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Copying '.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll' to 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=D://Python//Python39//python.exe //mediapipe_api:mediapipe_assets`
DEBUG: C:/_bzl/ru6tpeoz/external/rules_foreign_cc/workspace_definitions.bzl:6:6: `@rules_foreign_cc//:workspace_definitions.bzl` has been replaced by `@rules_foreign_cc//foreign_cc:repositories.bzl`. Please use the updated source location
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 46 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 0.414s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'build\Resources'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=D://Python//Python39//python.exe --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe_api:mediapipe_desktop`
DEBUG: C:/_bzl/ru6tpeoz/external/rules_foreign_cc/workspace_definitions.bzl:6:6: `@rules_foreign_cc//:workspace_definitions.bzl` has been replaced by `@rules_foreign_cc//foreign_cc:repositories.bzl`. Please use the updated source location
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: C:/_bzl/ru6tpeoz/external/rules_foreign_cc/tools/build_defs/deprecation.bzl:5:10: `@rules_foreign_cc//tools/build_defs/...` is deprecated, please find the relevant symbols in `@rules_foreign_cc//foreign_cc/...`. Note that the core rules can now be loaded from `@rules_foreign_cc//foreign_cc:defs.bzl`
ERROR: C:/_bzl/ru6tpeoz/external/com_google_mediapipe/third_party/BUILD:97:15: @com_google_mediapipe//third_party:opencv_cmake: no such attribute 'shared_libraries' in 'cmake' rule
ERROR: C:/_bzl/ru6tpeoz/external/com_google_mediapipe/mediapipe/framework/port/BUILD:92:11: Target '@com_google_mediapipe//third_party:glog' contains an error and its package is in error and referenced by '@com_google_mediapipe//mediapipe/framework/port:commandlineflags'
INFO: Repository com_google_absl instantiated at:
  F:/unityproj/mediapipeunityplugin-master/WORKSPACE:57:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/ru6tpeoz/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.088s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 707 targets configured)
Traceback (most recent call last):
  File "F:\unityproj\MediaPipeUnityPlugin-master\build.py", line 362, in <module>
    Argument().command().run()
  File "F:\unityproj\MediaPipeUnityPlugin-master\build.py", line 128, in run
    self._run_command(self._build_desktop_commands())
  File "F:\unityproj\MediaPipeUnityPlugin-master\build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "D:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=D://Python//Python39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.
```

**Comment by Leuconoe** [comment]
I am having the same problem. There is no problem with rebuilding in the workspace where the build was completed. A problem occurs in a clean up workspace.

**Comment by homuler** [comment]
Will you check if you can build with `build/mediapipe-0.8.3.2` branch?
https://github.com/homuler/MediaPipeUnityPlugin/tree/build/mediapipe-0.8.3.2

Probably `rules_foreign_cc` version must be fixed.

**Comment by Leuconoe** [comment]
I built with build/mediapipe-0.8.3.2 branch and build failed.
here is my logs

`D:/workspace/unity/mediapipeunityplugin_win/mediapipe_api/BUILD:61:10: Linking mediapipe_api/libmediapipe_c.dll failed: (Exit 1120): link.exe failed: error executing command
  cd C:/_bzl/chece23i/execroot/mediapipe_api
  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Python39//python.exe
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\user\AppData\Local\Temp
    SET TMP=C:\Users\user\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/HostX64/x64/link.exe @bazel-out/x64_windows-opt/bin/mediapipe_api/libmediapipe_c.dll-2.params
Execution platform: @local_execution_config_platform//:platform
   bazel-out/x64_windows-opt/bin/mediapipe_api/libmediapipe_c.dll.if.lib 라이브러리 및 bazel-out/x64_windows-opt/bin/mediapipe_api/libmediapipe_c.dll.if.exp 개체를 생성하고 있습니다.
resource_util.lib(resource_util.obj) : error LNK2019: "class absl::lts_2020_09_23::Status __cdecl mediapipe::internal::DefaultPathToResourceAsFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DefaultPathToResourceAsFile@internal@mediapipe@@YA?AVStatus@lts_2020_09_23@absl@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)"class absl::lts_2020_09_23::StatusOr<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > __cdecl mediapipe::PathToResourceAsFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?PathToResourceAsFile@mediapipe@@YA?AV?$StatusOr@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@lts_2020_09_23@absl@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 함수에서 참조되는 확인할 수 없는 외부 기호
bazel-out\x64_windows-opt\bin\mediapipe_api\libmediapipe_c.dll : fatal error LNK1120: 1개의 확인할 수 없는 외부 참조입니다.
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 2.645s, Critical Path: 1.47s`

**Comment by homuler** [comment]
Thanks.
Will you apply this patch (`git apply`) to `master` branch?
```diff
diff --git a/WORKSPACE b/WORKSPACE
index ffdaf2c..cf30d2b 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -78,8 +78,8 @@ http_archive(
 
 http_archive(
    name = "rules_foreign_cc",
-   strip_prefix = "rules_foreign_cc-main",
-   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/main.zip",
+   strip_prefix = "rules_foreign_cc-0.1.0",
+   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip",
 )
 
 load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
```

**Comment by sharyu** [comment]
> Thanks.
> Will you apply this patch (`git apply`) to `master` branch?
> 
> ```diff
> diff --git a/WORKSPACE b/WORKSPACE
> index ffdaf2c..cf30d2b 100644
> --- a/WORKSPACE
> +++ b/WORKSPACE
> @@ -78,8 +78,8 @@ http_archive(
>  
>  http_archive(
>     name = "rules_foreign_cc",
> -   strip_prefix = "rules_foreign_cc-main",
> -   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/main.zip",
> +   strip_prefix = "rules_foreign_cc-0.1.0",
> +   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip",
>  )
>  
>  load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
> ```

After applying this fix, above error disappeared. Thanks!

**Comment by Leuconoe** [comment]
it works. Thank you.

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/commit/780d405da003f472f2b8e14fdd9c71ef21c616f6 fixed it.
