### ISSUE TITLE
How to Disable Gesture Effects (e.g., Thumbs-Up, Peace Sign)?

### ISSUE THREAD

**Issue by ozawa2** [homuler/MediaPipeUnityPlugin#1276]
### Plugin Version or Commit ID

v0.15.0

### Unity Version

2022.3.51f1

### Your Host OS

Mac OS Sequoia 15.1

### Target Platform

UnityEditor

### Description

Where can I disable the effects triggered when making a thumbs-up or peace sign gesture? Additionally, could you let me know which file handles this processing?

**Comment by homuler** [comment]
> Where can I disable the effects triggered when making a thumbs-up or peace sign gesture?

I have no idea about the functionality you're mentioning. Which scene or API are you referring to?

**Comment by ozawa2** [comment]
I was mistaken. It appears that the following functionality was working on its own. My apologies.
https://support.apple.com/en-us/105117
