### ISSUE TITLE
Request for Guidance on Customizing Calculators

### ISSUE THREAD

**Issue by Candlend** [homuler/MediaPipeUnityPlugin#1278]
### Plugin Version or Commit ID

v0.15.0

### Unity Version

2022.3.53f1

### Your Host OS

macos Sequoia 15.1.1

### Target Platform

iOS

### Description

I’m looking to add a Custom Calculator or tweak the existing Calculator in MediaPipeUnityPlugin. I saw there’s a section for Custom Calculators in the wiki, but it’s empty.

I want to modify HolisticLandmarkGpu to only include body and hand landmarks, leaving out the facial ones. In the original MediaPipe, there’s a holistic_landmark_gpu.pbtxt file that I can edit, but it seems like the structure in MediaPipeUnityPlugin is different.

Could anyone guide me on how to do this? Any tips or pointers would be awesome!

Thanks a bunch!

**Comment by Candlend** [comment]
In fact, what I want is to modify or add a subgraph.

**Comment by homuler** [comment]
If you want to modify an existing subgraph, you need to apply a patch to MediaPipe and rebuild the plugin.
For more details, please refer to https://github.com/homuler/MediaPipeUnityPlugin/issues/242#issuecomment-900249401 and https://github.com/homuler/MediaPipeUnityPlugin/issues/1122.
Please see also https://github.com/homuler/MediaPipeUnityPlugin/issues/277#issuecomment-921433238.

**Comment by Candlend** [comment]
Where is the built-in subgraph information originally stored in MediaPipe so that the MediaPipeUnityPlugin can access it? Can I just modify or add something new like .pbtxt file? @homuler

**Comment by homuler** [comment]
It depends on your use case.
If simply combining existing subgraphs is sufficient, defining a `CalculatorGraph` within your Unity project should be enough (e.g. [`holistic_gpu.txt`](https://github.com/homuler/MediaPipeUnityPlugin/blob/c691e7c85bcffd7e669fe71a08e86dab77bf6b75/Assets/MediaPipeUnity/Samples/Scenes/Legacy/Holistic/holistic_gpu.txt)).
On the other hand, if you need to modify the subgraphs defined internally by MediaPipe (e.g. [`HolisticLandmarkGpu`](https://github.com/google-ai-edge/mediapipe/blob/afebe9d36ac0f76a725e49d1fe638035bcecfa7c/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt) in the example above), you will need to apply a patch regardless of whether they are defined in C++ or pbtxt.

> Where is the built-in .pbtxt subgraph data stored so that MediaPipeUnityPlugin can access it?

It is in `libmediapipe_c.*`.

> Can I just modify or add something new like .pbtxt file?

Both are possible. You can use them as long as they are included in the library.

For example, in https://github.com/homuler/MediaPipeUnityPlugin/commit/be7cf4415e93ec6d559d5589e0a14fe61c9f499b, a new subgraph is being added (note that this is not a patch to MediaPipe).
On the other hand, when adding functionality to a subgraph, I usually apply a patch (see https://github.com/homuler/MediaPipeUnityPlugin/blob/b669ac117b05a2302973698ed7cf223f343c63d3/third_party/mediapipe_extension.diff)

**Comment by Candlend** [comment]
Is it possible to define a subgraph externally?

**Comment by homuler** [comment]
It depends on what you mean by 'external' (if it refers to your application code, then no; if it refers to code outside of MediaPipe but within the plugin, then yes).

I believe I’ve explained it in quite a bit of detail, so if there’s anything unclear, please ask them more specifically.

**Comment by homuler** [comment]
@Candlend I hope the above error is fixed by https://github.com/homuler/MediaPipeUnityPlugin/pull/1293.

It seems that if Xcode version is 16.x, building the library fails.
