### ISSUE TITLE
How do I Enable the Masking of the background with the "MultiPoseLandmarkListWithMaskAnnotation" ?

### ISSUE THREAD

**Issue by DMLV-dev** [homuler/MediaPipeUnityPlugin#1279]
### Plugin Version or Commit ID

v0.15.0

### Unity Version

2022.3.34f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

I'm trying to have a virtual background the the user is visible and also the skeleton.
can you help me with this.

**Comment by homuler** [comment]
Could you tell me specifically what you don't understand?

If you're using `PoseLandmarker` and the [`outputSegmentationMasks`](https://github.com/homuler/MediaPipeUnityPlugin/blob/c691e7c85bcffd7e669fe71a08e86dab77bf6b75/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Landmark%20Detection/PoseLandmarkDetectionConfig.cs#L67) option is enabled, the mask will be rendered by calling `PoseLandmarkerResultAnnotationController.Draw*`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/c691e7c85bcffd7e669fe71a08e86dab77bf6b75/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Landmark%20Detection/PoseLandmarkerRunner.cs#L122

**Comment by DMLV-dev** [comment]
thank you!
