### ISSUE TITLE
HolisticTrackingSolution (sync mode) is about 25% slower in v0.15.0 compared to v0.14.4.

### ISSUE THREAD

**Issue by fengkan** [homuler/MediaPipeUnityPlugin#1280]
### Description

I want to check the time spent on each result obtained in HolisticTrackingSolution, so I made the following modifications,

HolisticTrackingSolution in v0.15.0

```
        if (runningMode.IsSynchronous())
        {
          screen.ReadSync(textureFrame);

          var task = graphRunner.WaitNextAsync();
          yield return new WaitUntil(() => task.IsCompleted);

          var result = task.Result;
          _poseDetectionAnnotationController.DrawNow(result.poseDetection);
          _holisticAnnotationController.DrawNow(result.faceLandmarks, result.poseLandmarks, result.leftHandLandmarks, result.rightHandLandmarks);
          _poseWorldLandmarksAnnotationController.DrawNow(result.poseWorldLandmarks);
          _segmentationMaskAnnotationController.DrawNow(result.segmentationMask);
          _poseRoiAnnotationController.DrawNow(result.poseRoi);

          // add this line
          PrintFrameTime(result.poseWorldLandmarks);

          result.segmentationMask?.Dispose();
        }
```
HolisticTrackingSolution in v0.14.4
```
    protected override IEnumerator WaitForNextValue()
    {
      var task = graphRunner.WaitNextAsync();
      yield return new WaitUntil(() => task.IsCompleted);

      var result = task.Result;
      _poseDetectionAnnotationController.DrawNow(result.poseDetection);
      _holisticAnnotationController.DrawNow(result.faceLandmarks, result.poseLandmarks, result.leftHandLandmarks, result.rightHandLandmarks);
      _poseWorldLandmarksAnnotationController.DrawNow(result.poseWorldLandmarks);
      _segmentationMaskAnnotationController.DrawNow(result.segmentationMask);

      _poseRoiAnnotationController.DrawNow(result.poseRoi);

      // add this line
      PrintFrameTime(result.poseWorldLandmarks);

      result.segmentationMask?.Dispose();
    }
```
PrintFrameTime function,
```
    private float _lastFrameTime;
    private void PrintFrameTime(LandmarkList poseWorldLandmarks)
    {
      float currentTime = Time.time;
      float deltaTime = currentTime - _lastFrameTime;
      Debug.Log($"Frame time difference: {deltaTime:F4} seconds");
      _lastFrameTime = currentTime;
    }
```
I am using Win11 on an i9-12900k. The time difference in v0.14.4 is about 0.04s, while it is 0.055s in v0.15.0.

Is this expected behavior?  Is there any way to improve performance in v0.15.0? Thank you very much.

**Comment by homuler** [comment]
That's because some frames are consumed to read the input image asynchronously in v0.15.0.
https://github.com/homuler/MediaPipeUnityPlugin/blob/c691e7c85bcffd7e669fe71a08e86dab77bf6b75/Assets/MediaPipeUnity/Samples/Scenes/Legacy/Holistic/HolisticTrackingSolution.cs#L143-L144

If you prefer, read the input image synchronously as in v0.14.4.

**Comment by fengkan** [comment]
Thank you for the prompt reply.

I copied the function below from TextureFrame.cs in 0.14.4, 
```
    public void ReadTextureFromOnCPU(Texture src)
    {
      var textureBuffer = LoadToTextureBuffer(src);
      SetPixels32(textureBuffer.GetPixels32());
    }
```
And changed the Line 143 of HolisticTrackingSolution in 0.15.0 to
```
         textureFrame.ReadTextureFromOnCPU(imageSource.GetCurrentTexture());
```

It did improve to 0.045 per frame! I would like to confirm if this approach aligns with your suggestion. Is there any room for further improvement? Thank you, and have a great weekend!

**Comment by homuler** [comment]
> I would like to confirm if this approach aligns with your suggestion.

Your implementation is as I intended.

> Is there any room for further improvement?

Of course, there is room for performance improvement, but in terms of comparison with version 0.14.4, I don't think there are any specific points.
