### ISSUE TITLE
How to detect the nearest human tracked in MultiPoseLandmarkListWithMaskAnnotation?

### ISSUE THREAD

**Issue by DMLV-dev** [homuler/MediaPipeUnityPlugin#1281]
### Plugin Version or Commit ID

v0.15.0

### Unity Version

2022.3.34f1

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Description

Hi thanks you for this wonderful plugin.
how can I detect the nearest user and make it the primary user being tracked?

**Comment by homuler** [comment]
For questions about how to use MediaPipe itself, please ask the MediaPipe community.
