### ISSUE TITLE
The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by Aashutosh-Dabhade** [homuler/MediaPipeUnityPlugin#130]
When I Import this project I am getting the below error. However, I have created  .so file for the android platform.
The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)
The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)
The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

What could the be reason?

**Comment by homuler** [comment]
I guess you've failed to build the native libraries actually, though I don't know on which OS you're running UnityEditor.
cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/105

**Comment by Aashurosh** [comment]
I am running on windows platform.
Unity version 2019.4.10
Though .so file was created on linux.
could you please share the working .so file library if possible on adabhade17@gmail.com

**Comment by homuler** [comment]
> Though .so file was created on linux.

Then you may forget to copy necessary files, which had been generated under `Packages`.
And note that you cannot run sample scenes on Windows (including UnityEditor) unless you build native libraries on Windows.

**Comment by olegplichko** [comment]
Run in the same issue on Mac OS today. Did anybody managed to solve it?

**Comment by fly-dk** [comment]
> > Though .so file was created on linux.
> 
> Then you may forget to copy necessary files, which had been generated under `Packages`. And note that you cannot run sample scenes on Windows (including UnityEditor) unless you build native libraries on Windows.

I meet the same problem！How to build .so and .dll?Please.

**Comment by LGuilhermeRodrigues** [comment]
@fly-dk Basically, if you use Windows like me, you have to build .dll in order to work in Windows and UnityEditor.
Then, you need a Linux Machine to do the same step: install the plugin and compile the .so file.
After that, you will merge the Packages folder of both machines.
Check if there are .so, .dll and .meta files on the packages folder and then you can open unity editor

**Comment by fly-dk** [comment]
> @fly-dk基本上，如果你像我一样使用Windows，你必须构建.dll才能在Windows和UnityEditor中工作。然后，您需要一台Linux机器来执行相同的步骤：安装插件并编译.so文件。之后，您将合并两台计算机的"包"文件夹。检查包文件夹上是否有.so，.dll和.meta文件，然后您可以打开unity编辑器
Thank you for your answer!I use the same windows system as you.But I still have something inunderstanded. Which folder are these files in in detail?Thank you again!
