### ISSUE TITLE
Cannot build for Windows 10

### ISSUE THREAD

**Issue by titoasty** [homuler/MediaPipeUnityPlugin#132]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): desktop cpu/gpu
- Bazel version: 4.0.0
- Python version: 3.9.4
- GCC/G++ version: 
- Unity version: 2020.3.0f1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

I've got a build error at the beginning with the bazel command.
The weird thing is that I can copy/paste the bazel command and run it in the console and it works.

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

python build.py build --desktop gpu -v

**Full logs**

```
D:\MediaPipeUnityPlugin-master>python build.py build --desktop gpu -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "D:\MediaPipeUnityPlugin-master\build.py", line 362, in <module>
    Argument().command().run()
  File "D:\MediaPipeUnityPlugin-master\build.py", line 102, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\MediaPipeUnityPlugin-master\build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

(last line is in french means file not foud. but does not specify any file)

**Additional context**

**Comment by homuler** [comment]
Can you run `bazel --version` ?
If not, please set the path to `bazel` to `%PATH%`.

In addition to that, you cannot build native libraries for Desktop GPU on Windows, so please run `python build.py build --desktop cpu -v` instead.

**Comment by titoasty** [comment]
`D:\MediaPipeUnityPlugin-master>bazel --version
bazel 4.0.0`

same problem for cpu version

**Comment by homuler** [comment]
Can you run the below command?
```bat
bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Python39//python.exe //mediapipe_api:mediapipe_proto_srcs
```

**Comment by titoasty** [comment]
Ok I think I finally found it.
I installed bazel with npm, and python didn't like that (although terminal found it)
Solved, thanks!
