### ISSUE TITLE
Bazel can't find the following tools:     cl.exe, link.exe, lib.exe, ml64.exe

### ISSUE THREAD

**Issue by Aashurosh** [homuler/MediaPipeUnityPlugin#134]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): windows 10
- Target (e.g. desktop cpu, android arm64): android arm64
- Bazel version: 4.0.0
- Python version: 3.7.0
- GCC/G++ version:
- Unity version: 2019.4.10
- Android NDK version (if building for Android): 19
- Xcode version (if building for iOS):

**Describe the problem**

I have installed bazel 4.0.0 and build tools as mentioned in the steps. 
error shows 
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe

but I checked in the following directory and these files are present there.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

cd Mediapipe
python build.py build --desktop cpu --android arm64 -v

**Full logs**
C:\Users\USER>cd C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master

C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --android arm64 -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//USER//AppData//Local//Programs//Python//Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/_bzl/todeqlfy/external/com_google_protobuf/BUILD:168:11: Compiling src/google/protobuf/compiler/parser.cc [for host] failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command external/local_config_cc/vc_installation_error_x64.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 ... (remaining 38 argument(s) skipped)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture

Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

Target //mediapipe_api:mediapipe_proto_srcs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.386s, Critical Path: 0.17s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 362, in <module>    Argument().command().run()
  File "C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 102, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//USER//AppData//Local//Programs//Python//Python39//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Additional context**

![image](https://user-images.githubusercontent.com/69786970/115408609-a36cf200-a20e-11eb-85b5-a9330e5402d8.png)

**Comment by homuler** [comment]
You cannot build native libraries for Android on Windows.
cf. https://github.com/homuler/MediaPipeUnityPlugin#android-1

Please build them using WSL 2 or Linux or macOS.

**Comment by Aashurosh** [comment]
I am getting the same error even when I build for windows.
I have installed Bazel using scoop.

python build.py build --desktop cpu

**Comment by homuler** [comment]
I see.
Have you installed Microsoft Build Tools 2019, in addition to Microsoft Visual C++ 2019 Redistributable?
https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

If so, I guess you have installed it to non-default path.
In that case, you need to set some environment variables for bazel.
https://docs.bazel.build/versions/master/windows.html#build-c-with-msvc

**Comment by Aashurosh** [comment]
solved this issue by correcting the environment variable 
BAZEL_WINSDK_FULL_VERSION to 10.0.19041.0
Bazel website had mentioned a lower version.
also changed BAZEL_VC_FULL_VERSION to 14.16.27023
* check version in respective locations.
