### ISSUE TITLE
Failing : Unity MediaPipe Plugin

### ISSUE THREAD

**Issue by dhanajik** [homuler/MediaPipeUnityPlugin#135]
Hi Homuler,

Great work. 

 J am developing an android app that will monitor the user exercise accuracy like push up, abs, etc. including reps and counts.

I have built Mediapipe (https://github.com/google/mediapipe) on Ubuntu and created "libmediapipe_c.so
" file successfully. 

I have copied "libmediapipe_c.so" in this project /Assets/Plugins and trying to run the project but it's not working for me.

Please let me know whether it's a correct approach or not.

Please provide guidelines or correct approaches that will help me to build a gym exercise android application using Unity and Mediapipe.

Thank you
Dhan

**Comment by homuler** [comment]
> I have copied "libmediapipe_c.so" in this project /Assets/Plugins and trying to run the project but it's not working for me.
> Please let me know whether it's a correct approach or not.

This plugin assumes that `libmediapipe_c.so` is built following the steps described [here](https://github.com/homuler/MediaPipeUnityPlugin#installation-guide), so if you built a shared library and named it `libmediapipe_c.so`, it would not work.
