### ISSUE TITLE
Windows 10 Build Issue: no such target '//mediapipe_api:mediapipe_proto_srcs'

### ISSUE THREAD

**Issue by dauntless3** [homuler/MediaPipeUnityPlugin#136]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): Desktop CPU, Android
- Bazel version: 3.7.2
- Python version: 3.9.4
- GCC/G++ version: -
- Unity version: 2019.4.24f1
- Android NDK version (if building for Android): -
- Xcode version (if building for iOS): -

**Describe the problem**

When building on Win10 for desktop CPU and android, I encountered the error below:

python build.py build --desktop cpu --android arm64 -v

ERROR: Skipping '//mediapipe_api:mediapipe_proto_srcs': no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD

WARNING: Target pattern parsing failed.

**Steps to reproduce the issue**

Successful Build:
1. bazel-bin\mediapipe\examples\desktop\hello_world\hello_world.exe  
2. bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" mediapipe/examples/desktop/hello_world

Not Successful:
3. python build.py build --desktop cpu --android arm64 -v
4. >bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" //mediapipe_api:mediapipe_proto_srcs

**Full logs**

Log for (3):

python build.py build --desktop cpu --android arm64 -v

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=/usr/bin/python3 //mediapipe_api:mediapipe_proto_srcs`
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/users/asus/mediapipe_repo/mediapipe/WORKSPACE:53:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/f75p3gig/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Skipping '//mediapipe_api:mediapipe_proto_srcs': no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD
INFO: Elapsed time: 0.196s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "C:\Users\ASUS\mediapipe_repo\mediapipe\build.py", line 362, in <module>
    Argument().command().run()
  File "C:\Users\ASUS\mediapipe_repo\mediapipe\build.py", line 102, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\ASUS\mediapipe_repo\mediapipe\build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=/usr/bin/python3', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

Log for (4): 

bazel --output_user_root C:/_bzl build -c opt --action_env 

PYTHON_BIN_PATH="C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" //mediapipe_api:mediapipe_proto_srcs
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/users/asus/mediapipe_repo/mediapipe/WORKSPACE:53:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/f75p3gig/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Skipping '//mediapipe_api:mediapipe_proto_srcs': no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD
INFO: Elapsed time: 0.402s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by homuler** [comment]
It may sound weird, but are you using this repository?

> DEBUG: Repository rules_foreign_cc instantiated at:
C:/users/asus/mediapipe_repo/mediapipe/WORKSPACE:53:13: in
Repository rule http_archive defined at:

I cannot get why this log was output, becuase `rules_foreign_cc` should have been instantiated at [WORKSPACE:79:13](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/WORKSPACE#L79).

**Comment by dauntless3** [comment]
Hi homuler, thank you for your reply! Yes I was using that repository. 

Not sure why but there were some differences between the one which I had and the one which you mentioned (https://github.com/homuler/MediaPipeUnityPlugin/blob/master/WORKSPACE#L79).

I've tried replacing my version of WORKSPACE with the one you mentioned but I still have the following error:

python build.py build --desktop cpu --android arm64 -v

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//ASUS//AppData//Local//Programs//Python//Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
ERROR: Skipping '//mediapipe_api:mediapipe_proto_srcs': no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//mediapipe_api:mediapipe_proto_srcs': target 'mediapipe_proto_srcs' not declared in package 'mediapipe_api' defined by C:/users/asus/mediapipe_repo/mediapipe/mediapipe_api/BUILD
INFO: Elapsed time: 0.498s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "C:\Users\ASUS\mediapipe_repo\mediapipe\build.py", line 362, in <module>
    Argument().command().run()
  File "C:\Users\ASUS\mediapipe_repo\mediapipe\build.py", line 102, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\ASUS\mediapipe_repo\mediapipe\build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//ASUS//AppData//Local//Programs//Python//Python39//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

Perhaps I should raise this issue at mediapipe github?

**Comment by homuler** [comment]
I don't know what you have done exactly, but your local repository is broken, so please clone it again.
```sh
git clone https://github.com/homuler/MediaPipeUnityPlugin.git
cd MediaPipeUnityPlugin
python build.py build --desktop cpu -v
```

> Perhaps I should raise this issue at mediapipe github?

This project is independent of https://github.com/google/mediapipe.git , so don't create issues about this repo there.

**Comment by dauntless3** [comment]
Thanks. I'll start afresh, reinstall everything and clone again. It should work.

You're right, I'll not create the issue regarding this repo in that github.

**Comment by dauntless3** [comment]
It's working now. Thank you! 

When building for desktop cpu, I did encounter the same issue with the missing open_world3410.lib as I did when installing mediapipe: [Missing input file 'external/windows_opencv/x64/vc15/lib/opencv_world3410.lib'](https://github.com/google/mediapipe/issues/1926). 

I had 3414 but not 3410. It was resolved by editing mediapipeunityplugin/third_party/opencv_windows.BUILD - the value 3410 was changed to 3414.
