### ISSUE TITLE
Android Build fail on Ubuntu 20.4

### ISSUE THREAD

**Issue by dhanajik** [homuler/MediaPipeUnityPlugin#137]
**System information**
- OS Platform and Distribution :  Linux Ubuntu 20.04
- Target (e.g. desktop cpu, android arm64): android arm64
- Bazel version: 4.0
- Python version: 3.9
- GCC/G++ version: 9.3
- Unity version:
- Android NDK version (if building for Android): 18

**Describe the problem**
Building setup on Ubuntu 20 => Build fail
python3.9 build.py build  --android arm64 -v

****** Error******
WARNING: 'Google.Protobuf' already has a dependency defined for 'System.Memory'.
Installing 'Google.Protobuf 3.15.6'.
'Google.Protobuf' already has a dependency defined for 'System.Memory'.

**Steps to reproduce the issue**
python3.9 build.py build --desktop cpu --android arm64 -v

**Full logs**
DEBUG (build.py): Running `nuget install -o .nuget`
WARNING: 'Google.Protobuf' already has a dependency defined for 'System.Memory'.
Installing 'Google.Protobuf 3.15.6'.
'Google.Protobuf' already has a dependency defined for 'System.Memory'.
Traceback (most recent call last):
  File "/mnt/MediaPipeUnityPlugin/build.py", line 362, in <module>
    Argument().command().run()
  File "/mnt/MediaPipeUnityPlugin/build.py", line 109, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/mnt/MediaPipeUnityPlugin/build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nuget', 'install', '-o', '.nuget']' returned non-zero exit status 1.
Administrator@ITLSER046V2:/mnt/MediaPipeUnityPlugin$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Additional context**

**Comment by dhanajik** [comment]
Please ingnore the above error

I have upgrated Nuget to 5.8 and the above has gone. Now I am getting the following  error.

INFO: Build options --cpu, --crosstool_top, --fat_apk_cpu, and 1 more have changed, discarding analysis cache.
ERROR: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 0.163s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 50 targets configured)
Traceback (most recent call last):
  File "/mnt/MediaPipeUnityPlugin/build.py", line 362, in <module>
    Argument().command().run()
  File "/mnt/MediaPipeUnityPlugin/build.py", line 143, in run
    self._run_command(self._build_android_commands())
  File "/mnt/MediaPipeUnityPlugin/build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.

**Comment by homuler** [comment]
Have you set `ANDROID_HOME` and `ANDROID_NDK_HOME`? 
https://github.com/homuler/MediaPipeUnityPlugin#linux

**Comment by dhanajik** [comment]
Yes, both paths have been set. I am using SDK -27 and NDK 21

**Comment by dhanajik** [comment]
Thank you very much for your help.

Now I am getting the below error
----------------------------------


WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
ERROR: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/62287a80b8c3cce9469b940655f907dd/external/linux_opencv/BUILD.bazel", line 30, column 16, in <toplevel>
                srcs = glob(
Error in glob: pattern cannot be absolute
ERROR: /root/.cache/bazel/_bazel_root/62287a80b8c3cce9469b940655f907dd/external/com_google_mediapipe/third_party/BUILD:178:6: no such target '@linux_opencv//:opencv': target 'opencv' not declared in package '' defined by /root/.cache/bazel/_bazel_root/62287a80b8c3cce9469b940655f907dd/external/linux_opencv/BUILD.bazel and referenced by '@com_google_mediapipe//third_party:opencv_binary'
INFO: Repository android_opencv instantiated at:
  /mnt/MediaPipeUnityPlugin/WORKSPACE:261:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/62287a80b8c3cce9469b940655f907dd/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'android_opencv' used the following cache hits instead of downloading the corresponding file.
 * Hash 'cdb0e190c3734edd4052a3535d9e4310af912a9f70a421b1621711942a1028d5' for https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip
If the definition of 'android_opencv' was updated, verify that the hashes were also updated.
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: Analysis failed
INFO: Elapsed time: 58.059s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (74 packages loaded, 9266 targets configured)
    currently loading: @rules_jvm_external//private/templates
    Fetching ...external/android_opencv; Extracting /root/.cache/bazel/_bazel_root/62287a80b8c3cce9469b940655f907dd/external/android_opencv/temp1446890644398602053/opencv-3.4.3-android-sdk.zip 4s
Traceback (most recent call last):
  File "/mnt/MediaPipeUnityPlugin/build.py", line 362, in <module>
    Argument().command().run()
  File "/mnt/MediaPipeUnityPlugin/build.py", line 143, in run
    self._run_command(self._build_android_commands())
  File "/mnt/MediaPipeUnityPlugin/build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.

**Comment by homuler** [comment]
Have you changed `opencv_linux.BUILD` or `WORKSPACE` ?
If so, please share the contents.

> Error in glob: pattern cannot be absolute

Maybe glob patterns start with `/`.
