### ISSUE TITLE
Found unchecked GL error: GL_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by elblogbruno** [homuler/MediaPipeUnityPlugin#14]
Looking at android logcat, I have seen after some seconds with multi-hand tracking graph, this error does pop up and tracking does not work anymore,
 
![image](https://user-images.githubusercontent.com/10481058/96333031-d79d0580-1067-11eb-83f0-39915ab65632.png)
![image](https://user-images.githubusercontent.com/10481058/96333044-e71c4e80-1067-11eb-9fbd-0169b5cd4866.png)

`Found unchecked GL error: GL_OUT_OF_MEMORY`

Thanks.
Bruno

**Comment by homuler** [comment]
Will you tell me which device you use?

**Comment by elblogbruno** [comment]
Oppo Reno 2 with android 10
