### ISSUE TITLE
fatal error C1001: An internal error has occurred in the compiler.

### ISSUE THREAD

**Issue by Aashutosh-Dabhade** [homuler/MediaPipeUnityPlugin#140]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): windows
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 4.0.0
- Python version: 3.9.0
- GCC/G++ version:
- Unity version: 2019.4.10
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

I have set up the environment as described in the steps.
build.py is compiling till 4544 steps and then gives this error.
I am not sure whether this is an environment setup error or am I missing something here.

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

python build.py build --desktop cpu

**Full logs**

C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master>python build.py build --desktop cpu
INFO (build.py): Building protobuf sources...
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 676 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 0.808s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
Feeds used:
  C:\Users\USER\.nuget\packages\
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

All packages listed in C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\packages.config are already installed.
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 46 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 0.365s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (0 packages loaded, 7683 targets configured).
INFO: Found 1 target...
ERROR: C:/_bzl/todeqlfy/external/com_google_mediapipe/mediapipe/util/tracking/BUILD:398:11: Compiling mediapipe/util/tracking/streaming_buffer.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 37 argument(s) skipped)
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): error C2244: 'mediapipe::StreamingBuffer::AddData': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(351): note: see declaration of 'mediapipe::StreamingBuffer::AddData'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): error C2244: 'mediapipe::StreamingBuffer::AddDataImpl': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(367): note: see declaration of 'mediapipe::StreamingBuffer::AddDataImpl'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.880s, Critical Path: 1.55s
INFO: 98 processes: 98 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 362, in <module>
    Argument().command().run()
  File "C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 128, in run
    self._run_command(self._build_desktop_commands())
  File "C:\Users\USER\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 47, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//USER//AppData//Local//Programs//Python//Python39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.
**Additional context**

![image](https://user-images.githubusercontent.com/69786970/116210160-3e5e5280-a760-11eb-9ce7-54a291a6273d.png)

![Capture](https://user-images.githubusercontent.com/69786970/116184301-20cbc180-a73d-11eb-9cb8-245268730a29.JPG)
![Capture2](https://user-images.githubusercontent.com/69786970/116184404-51136000-a73d-11eb-8c2a-b15ae9f18940.JPG)

**Comment by homuler** [comment]
Same as #145
