### ISSUE TITLE
Gesture Recognition

### ISSUE THREAD

**Issue by AlanWuJinliang** [homuler/MediaPipeUnityPlugin#142]
Does the project contain the function of Gesture Recognition?

it is easy to know the hand gesture,  like  one 、two、three、ok....

like this :https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html

**Comment by homuler** [comment]
If such a calculator is not included in mediapipe's repository, no.

**Comment by AlanWuJinliang** [comment]
see this :https://gist.github.com/TheJLifeX/74958cc59db477a91837244ff598ef4a
