### ISSUE TITLE
Macos Build Error

### ISSUE THREAD

**Issue by some2014** [homuler/MediaPipeUnityPlugin#146]
**System information**
MacOs BigSur
- Target (e.g. desktop cpu, android arm64):
- i7 8700k
- Bazel version:
- 3.7.2
- Python version:
- 3.9
- Unity version:
- 2019
- Android NDK version (if building for Android):
- 18.1.5063045
- Xcode version (if building for iOS):
- 12

**Describe the problem**
Build for Desktop, Android, and iOS:
python build.py build --desktop cpu --android arm64 --ios arm64 -v

**Full logs**

ERROR: /Users/yjkj/MediaPipeUnityPlugin/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: no such target '//third_party:opencv': target 'opencv' not declared in package 'third_party' defined by /Users/yjkj/MediaPipeUnityPlugin/third_party/BUILD and referenced by '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib'
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.290s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 86 targets configured)
Traceback (most recent call last):
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 153, in run
    self._run_command(self._build_android_commands())
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.

**Comment by homuler** [comment]
It's already fixed by https://github.com/homuler/MediaPipeUnityPlugin/commit/24fe5dbfed6e5a9bc40821898542d3c6906ea11f

**Comment by some2014** [comment]
Dear developer, thank you for your reply. 
Still can not compile through, this a new problem:

ERROR: /private/var/tmp/_bazel_yjkj/bc6146d9f43fa91d16d51d7b8a49995d/external/com_google_protobuf/BUILD:1009:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
ERROR: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed; build aborted: Analysis of target '@com_google_protobuf//:cc_toolchain' failed
INFO: Elapsed time: 36.137s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 10326 targets\
 configured)
Traceback (most recent call last):
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 162, in run
    self._run_command(self._build_ios_commands())
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=ios_arm64', '--copt=-fembed-bitcode', '--apple_bitcode=embedded', '//mediapipe_api/objc:MediaPipeUnity']' returned non-zero exit status 1.

**Comment by some2014** [comment]
> It's already fixed by [24fe5db](https://github.com/homuler/MediaPipeUnityPlugin/commit/24fe5dbfed6e5a9bc40821898542d3c6906ea11f)

Dear developer, thank you for your reply.
Still can not compile through, this a new problem:

ERROR: /private/var/tmp/_bazel_yjkj/bc6146d9f43fa91d16d51d7b8a49995d/external/com_google_protobuf/BUILD:1009:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
ERROR: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed; build aborted: Analysis of target '@com_google_protobuf//:cc_toolchain' failed
INFO: Elapsed time: 36.137s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 10326 targets
configured)
Traceback (most recent call last):
File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 392, in 
Argument().command().run()
File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 162, in run
self._run_command(self._build_ios_commands())
File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 51, in _run_command
return subprocess.run(command_list, check=True)
File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=ios_arm64', '--copt=-fembed-bitcode', '--apple_bitcode=embedded', '//mediapipe_api/objc:MediaPipeUnity']' returned non-zero exit status 1.

**Comment by homuler** [comment]
Please use Bazel 3.7.2 to build for iOS.
https://github.com/homuler/MediaPipeUnityPlugin#prerequisites

**Comment by some2014** [comment]
> Please use Bazel 3.7.2 to build for iOS.
> cf. Step 4 in https://github.com/homuler/MediaPipeUnityPlugin#macos

bazel version:
Build label: 3.7.2

ERROR: /Users/yjkj/MediaPipeUnityPlugin/mediapipe_api/objc/BUILD:21:14: in ios_framework rule //mediapipe_api/objc:MediaPipeUnity: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_yjkj/bc6146d9f43fa91d16d51d7b8a49995d/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 579, column 58, in _ios_framework_impl
		link_result = linking_support.register_linking_action(
	File "/private/var/tmp/_bazel_yjkj/bc6146d9f43fa91d16d51d7b8a49995d/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 102, column 47, in _register_linking_action
		return apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'stamp'
ERROR: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed; build aborted: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed
INFO: Elapsed time: 1.353s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 10432 targets configured)
Traceback (most recent call last):
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 162, in run
    self._run_command(self._build_ios_commands())
  File "/Users/yjkj/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=ios_arm64', '--copt=-fembed-bitcode', '--apple_bitcode=embedded', '//mediapipe_api/objc:MediaPipeUnity']' returned non-zero exit status 1.

**Comment by homuler** [comment]
I'm not sure, but if you're testing a branch other than `master`, please checkout latest `master`.
If you're testing `master`, then your local cache looks somewhat broken, so please clear cache.
```sh
python build.py clean
```

> File "/private/var/tmp/_bazel_yjkj/bc6146d9f43fa91d16d51d7b8a49995d/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 579, column 58, in _ios_framework_impl
link_result = linking_support.register_linking_action(

This repository uses `rules_apple` 0.19.0, but [ios_rule.bzl](https://github.com/bazelbuild/rules_apple/blob/0.19.0/apple/internal/ios_rules.bzl) does not have 579 lines (but latest version does).

**Comment by some2014** [comment]
> I'm not sure, but if you're testing a branch other than `master`, please checkout latest `master`.
> If you're testing `master`, then your local cache looks somewhat broken, so please clear cache.
> 
> ```shell
> python build.py clean
> ```
> 
> > File "/private/var/tmp/_bazel_yjkj/bc6146d9f43fa91d16d51d7b8a49995d/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 579, column 58, in _ios_framework_impl
> > link_result = linking_support.register_linking_action(
> 
> This repository uses [`rules_apple` 0.19.0](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/WORKSPACE#L302), but [ios_rule.bzl](https://github.com/bazelbuild/rules_apple/blob/0.19.0/apple/internal/ios_rules.bzl) does not have 579 lines (but latest version does).

After Redownload master, the problem has been solved perfectly. Thank you very much!
