### ISSUE TITLE
Box Tracking question

### ISSUE THREAD

**Issue by chrisError** [homuler/MediaPipeUnityPlugin#148]
the mediapipe docs state that BoxTracking can work either work using Object Detection (as per the current demo) or "the starting position can also be provided manually by the user". 

Does anyone know / has anyone been able to work out how to set a user-defined region to track that isn't set by object detection?

thanks!

**Comment by chrisError** [comment]
have moved this question over to the mediapipe repo issues.

**Comment by homuler** [comment]
As far as I know, Object Detection and Instant Motion Tracking uses [BoxTrackingSubgraph](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/tracking/subgraphs/box_tracking_gpu.pbtxt) internally, and it receives the position to track as an input.
