### ISSUE TITLE
Failed to load AssetBundle on Build

### ISSUE THREAD

**Issue by antoniomarino50242** [homuler/MediaPipeUnityPlugin#149]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): MacOs
- Target (e.g. desktop cpu, android arm64): desktop
- Bazel version: bazel 3.7.2
- Python version: Python 2.7.16
- Unity version: 2019.4.18f1

**Describe the problem**
Hi, 
I'm working with a MacBook on a project with your MediaPipe plugin.
After creating the build for Mac of my project I can't use the Mediapipe's detection.
If I run my build I see all my scene but not the detection.
If I create a development build for Mac and I can see the development console with the following error:
-Unable to open archive file: /Contents/Resources/Data/StreamingAssets/AssetBundles/mediapipe/models
-Failed to load the AssetBundle
-EntryPointNotFoundException: mp_GpuResources_Create_Pv
-Failed to read data for the AssetBundle 'models'
 
After creating the build for Windows I see the same issues.
Can you show me a way to create a build to visualize the detection of MediaPipe?
I look forward to your reply.
Thanks

**Additional context**
I add screenshot of my issues both on Mac and Windows too.
![IMG_1978](https://user-images.githubusercontent.com/39876596/116904957-a7e9cf80-ac3e-11eb-9596-0f329b7ad116.JPG)
![IMG_1979](https://user-images.githubusercontent.com/39876596/116904990-b2a46480-ac3e-11eb-8828-0855b26d0600.JPG)
![IMG_1980](https://user-images.githubusercontent.com/39876596/116905003-b7691880-ac3e-11eb-8501-dd2e896dbd1d.JPG)
![IMG_1981](https://user-images.githubusercontent.com/39876596/116905012-ba640900-ac3e-11eb-9b75-f5903a598db8.JPG)

**Comment by homuler** [comment]
First, it looks like that you're trying to run MediaPipe with GPU, but this option is not supported on macOS. (cf. https://github.com/homuler/MediaPipeUnityPlugin#desktop)

Second, probably you're trying to load model files from AssetBundle, but you may not have built it yet.
See https://docs.unity3d.com/Manual/AssetBundles-Workflow.html and https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Assets/Mediapipe/Editor
