### ISSUE TITLE
EntryPointNotFoundException: MpGpuResourcesCreate

### ISSUE THREAD

**Issue by yellowflash07** [homuler/MediaPipeUnityPlugin#15]
Getting an error while running GPU scene

```
EntryPointNotFoundException: MpGpuResourcesCreate
Mediapipe.GpuResources.Create () (at Assets/MediaPipe/SDK/Scripts/Gpu/GpuResources.cs:29)
SceneDirector+<Start>d__13.MoveNext () (at Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:42)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

```
Waiting for assets to be loaded...
UnityEngine.Debug:Log(Object)
<RunGraph>d__19:MoveNext() (at Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:132)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```

I have run the build assetbundle

**Comment by homuler** [comment]
It may not be related directly, but https://github.com/homuler/MediaPipeUnityPlugin/commit/31d3deb11045c112aac2281991a90176c68ac7a9 introduced a bug, so please pull the latest commit first.

And then, will you run below commands and restart UnityEditor?
```sh
make gpu
make install
```

**Comment by yellowflash07** [comment]
after running the specified commands unity stops responding as soon as it goes into play mode.

the error, I mentioned while opening this issue comes after running

`make android_arm`

then is resolved by

`make gpu/cpu`

I'm also getting a error for make android_arm but I will open a separate issue for that.

**Comment by yellowflash07** [comment]
but the cpu scene after 

`make cpu`

runs perfectly.

**Comment by homuler** [comment]
> after running the specified commands unity stops responding as soon as it goes into play mode.

This is the bug I mentioned in https://github.com/homuler/MediaPipeUnityPlugin/issues/15#issuecomment-712905800.

Please pull the latest commit first, then run `make gpu && make install`.
If the problem is still not fixed, please let me know.

**Comment by yellowflash07** [comment]
issue fixed after pulling the latest commit. thanks.
