### ISSUE TITLE
ubuntu20.04.2 nuget install unfind Google.Protobuf 3.15.6

### ISSUE THREAD

**Issue by jimzou** [homuler/MediaPipeUnityPlugin#151]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):
- Target (e.g. desktop cpu, android arm64):
- Bazel version:3.7.2
- Python version:3.9
- GCC/G++ version:9.3.0
- Android NDK version (if building for Android):21

**Describe the problem**
Prompt error when exec "python build.py build --desktop cpu --android arm64 --ios arm64 -v" : 

**Full logs**
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (42 packages loaded, 668 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 38.696s, Critical Path: 29.04s
INFO: 196 processes: 3 internal, 193 linux-sandbox.
INFO: Build completed successfully, 196 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
INFO (build.py): ==== build_proto_dlls_commands()...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Unable to find version '3.15.6' of package 'Google.Protobuf'.
Traceback (most recent call last):
  File "/home/jim/MyProjects/MediaPipeUnityPlugin-0.8.3/build.py", line 395, in <module>
    Argument().command().run()
  File "/home/jim/MyProjects/MediaPipeUnityPlugin-0.8.3/build.py", line 116, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/home/jim/MyProjects/MediaPipeUnityPlugin-0.8.3/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nuget', 'install', '-o', '.nuget', '-Source', 'https://api.nuget.org/v3/index.json']' returned non-zero exit status 1.

**Additional context**
when Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json` on Terminal
prompt:
Unable to find version '3.15.6' of package 'Google.Protobuf'.

**Comment by homuler** [comment]
Which version of nuget do you use?

By the way, if your host OS is Ubuntu 20.04, then it'd be easier to build native libraries in Docker container.
```sh
docker build -t mediapipe_unity:ubuntu . -f docker/linux/x86_64/Dockerfile.ubunt
docker run -it --mount type=bind,src=$PWD/Packages,dst=/home/mediapipe/Packages mediapipe_unity:ubuntu

# in the container
python build.py build --desktop cpu --android arm64 -v
```

**Comment by jimzou** [comment]
is caused by nuget low version,solved.
Than I will try the docker solution.
Thank you for your hard work！

**Comment by Aashutosh-Dabhade** [comment]
> is caused by nuget low version,solved.
> Than I will try the docker solution.
> Thank you for your hard work！

how did you install the new version?

**Comment by aycaecemgul** [comment]
I have the same problem, using ubuntu 18.04 LTS and NuGet version is 2.8.7.0. getting the same error.

**Comment by Aashutosh-Dabhade** [comment]
Install 20.04 and upgrade nuget using this line

nuget update -self

Or follow this link

https://stackoverflow.com/questions/38118548/how-to-install-nuget-from-command-line-on-linux
