### ISSUE TITLE
Building native libraries for Android on Windows 10

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#152]
> Android
> You cannot build native libraries for Android on Windows 10, so use WSL 2 instead.

Hello @homuler , I was wondering why building native libraries for Android on Windows 10 is not allowed. Why we have to move to WSL 2? I know Mediapipe doesn't officially support it but may I know what could be the reason?

Is this a strict restriction? If not, I'll look to contribute to that part.

**Comment by homuler** [comment]
I guess this is caused by https://github.com/tensorflow/tensorflow/issues/38525#issuecomment-616064713 .

**Comment by midopooler** [comment]
Hey @homuler , thanks for the quick response. 
I want to map our 3D avatar using landmarks. As the landmarks are projected on a 2D canvas, I am not able to map landmarks in a 3D space. Give me some suggestions on this?

**Comment by homuler** [comment]
I have succeeded in building `mediapipe_android.aar` on my Windows machine.
But currently, it is too complicated and requires almost hobby-like procedures, so I'll leave it as is.
https://github.com/bazelbuild/bazel/issues/7982#issuecomment-981050307

As a hobby, I may modify it to run on Windows Docker later on.
