### ISSUE TITLE
z-coordinate value not proportional with x and y.

### ISSUE THREAD

**Issue by philiprkk** [homuler/MediaPipeUnityPlugin#153]
When visualizing landmark positions in full-body tracking, the z value seems to be upscaled dramatically. 
I've attached a screenshot of the landmark coordinates represented in 3D space. I'm I doing something wrong or is the data supposed to look like this?

![image](https://user-images.githubusercontent.com/57251565/117107754-63ffe300-ad82-11eb-9620-06af75e07641.png)

**Comment by philiprkk** [comment]
It seems when standing completely straight it also estimates the feet being well behind the hip and knees. 

![image](https://user-images.githubusercontent.com/57251565/117123777-bef00500-ad97-11eb-9294-38a2be12cb6e.png)

**Comment by homuler** [comment]
Will you ask questions about models at [MediaPipe repo](https://github.com/google/mediapipe)? I cannot answer them.

As far as I know, `z` is [experimental value](https://developers.google.com/ml-kit/vision/pose-detection#z_coordinate) and its accuracy is not high.
As to scale factor, please see also [this](https://google.github.io/mediapipe/solutions/pose.html#output).
