### ISSUE TITLE
libmediapipe_c.dll error and EntryPointNotFoundException

### ISSUE THREAD

**Issue by gruossomonica** [homuler/MediaPipeUnityPlugin#155]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10 Pro
- Target (e.g. desktop cpu, android arm64): desktop
- Bazel version: 3.7.2
- Python version: 3.7.4
- GCC/G++ version: 5.1.0
- Unity version: 2019.4.18.f1

**Describe the problem**
Error using your hand tracking mediapipe unity plugin in my code. I obtained libmediapipe_c.dll error and EntryPointNotFoundException when I tryed to solve it. 

**Steps to reproduce the issue**
MediaPipe Hello World runs without problems. Then I installed other dependencies and ran `make cpu PYTHON_BIN_PATH="C://Python37//Python.exe"` obtaining the following
![mediapipe_make](https://user-images.githubusercontent.com/48350177/117338946-7459b000-ae9f-11eb-89c0-ac5c11e22b9c.PNG)

Then, I opened my project in Unity, which includes your code for mediapipe hand tracking in an existing work. I got the following error when I played the run button in the editor
![mediapipe_unity_error1](https://user-images.githubusercontent.com/48350177/117340056-c3ecab80-aea0-11eb-9be5-adf6506ad4a4.PNG)

Subsequentely I copied the `libmediapipe_c.dll` in `my_project/Assets/MediaPipe/SDK/Plugins` from `my_project/C/bazel-out/x64_windows-opt/bin/mediapipe_api `. Then I checked `Load on startup` in the plugin inspector and click `Apply` button.

Finally, I restarted Unity and I got the following error
![mediapipe_unity_error2](https://user-images.githubusercontent.com/48350177/117340310-07dfb080-aea1-11eb-9616-c2ad8c93ed61.PNG)

Loooking forward to your reply.

Best Regards, 

Monica Gruosso

**Comment by homuler** [comment]
Please pull the latest commit and run `python build.py build --desktop cpu --include_opencv_libs -v`.
Now you can import this plugin as a local package.
