### ISSUE TITLE
MacOS build can't run on other MacOS devices. Failed to initialize WebCamTexture

### ISSUE THREAD

**Issue by antoniomarino50242** [homuler/MediaPipeUnityPlugin#157]
**System information**
- OS Platform and Distribution: MacOS 
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 3.7.2
- Python version: 3.9.5
- GCC/G++ version: 4.2.1
- Unity version:2019.4.18.f1

**Describe the problem**
Hi Homuler,
I'm working with your latest plugin of Mediapipe. The MacOs build doesn't work on other Mac and notify me "Failed to initialize WebCamTexture".  If I want other devices to run the MacOS stand alone, what can I do?

**Full logs**
[Player.log](https://github.com/homuler/MediaPipeUnityPlugin/files/6446104/Player.log)

Loooking forward to your reply.

Best Regards

**Comment by homuler** [comment]
In the sample scene (`DesktopDemo`), the resolution of input camera is [given at build time](https://github.com/homuler/MediaPipeUnityPlugin/blob/4ca0f5f289b06e610c88cee744d1da50fb270356/Assets/Mediapipe/Samples/Scripts/WebCamScreenController.cs#L7-L8), but the built app will not work on devices which don't support the specified resolution.
