### ISSUE TITLE
Reference to the body landmark numbers?

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#158]
Hello @homuler, could you please describe me what reference its taking in this code of yours. 
https://github.com/homuler/MediaPipeUnityPlugin/blob/dd9986746cb746e06cc7a4ec846f59eaa3cc3990/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Annotation/PoseLandmarkListAnnotationController.cs#L9-L17
I can't find the exact code in the repo which is assigning a number to the body landmarks, like this one 
![Screenshot_1](https://user-images.githubusercontent.com/43686606/117693217-6a0b1f00-b1db-11eb-9d29-00bdc8c7e1dd.png)

Its taken from this link https://developers.google.com/ml-kit/vision/pose-detection

**Comment by midopooler** [comment]
I have been facing issues in using transform.position of the Nodes. 
I tried accessing the 12,14 nodes from the full body landmarks and instead of the arm nodes, I got the fingers nodes from the Hand tracking landmarks. 
Is there anything to differentiate between the different model's landmarks since both of them include landmarks from 1-20 (with the same numbering)
I'm referring to the landmarks I'm getting from this image
![Screenshot_2](https://user-images.githubusercontent.com/43686606/118362462-35b5ab00-b5ad-11eb-9f1c-3dced45d1777.png)
Reference to the code is https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Annotation/LandmarkListAnnotationController.cs

**Comment by homuler** [comment]
> Is there anything to differentiate between the different model's landmarks since both of them include landmarks from 1-20 (with the same numbering)

It depends on `CalculatorGraphConfig` you use.
In general, you know what kind of values will flow through in which stream, so you can distinguish full boy landmarks from hand landmarks, even if they are both typed `List<NormalizedLandmark>`.

https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/Assets/Mediapipe/Samples/Graphs/Holistic/Resources/holistic_desktop_gpu.txt#L35-L37

**Comment by midopooler** [comment]
Hi @homuler , I got what you are trying to say above. But even after that, I'm unable to use pose instead of hand landmarks. 

Okay let's take this example in this code
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Annotation/LandmarkListAnnotationController.cs#L75-L76
Let me write this line at line number 77
`var c = Nodes[20];`
It will give the Pinky_Tip node. And if I write 
`var d = Nodes[21];`
It will return an error of calling array outside its limit, i.e 21 doesn't exist in the array/list.

Then, it must be concluded that only hand tracking graphs are being used in the given script. 
Now please tell me how could change it to full-body pose one instead of hand one? Do we have to do it from the inspector or from the script itself?

**Comment by midopooler** [comment]
Hey @homuler, if you have noticed this issue, Could you please assist me?

I just want a correct snippet of how to call transform.position of different landmarks of pose?

**Comment by homuler** [comment]
#296 implements `PointListAnnotation` and this will work regardless of the input list size, so I close this.
If you have any questions, please reopen it.
