### ISSUE TITLE
Demo doesn't work on Windows

### ISSUE THREAD

**Issue by antoniomarino50242** [homuler/MediaPipeUnityPlugin#159]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): windows 10

**Describe the problem**
Hi homuler.
I'm working with your latest Mediapipe's plugin with a Mac. 
When i build the demo for macOs it works fine on all other macs.
When I create the demo for Windows from the mac it doesn't work and notify me "dllNotFoundException Mediapipe_c"
What can I do to fix this problem and make it work on windows?

**Full logs**
Mono path[0] = 'C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Managed'
Mono config path = 'C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/MonoBleedingEdge/etc'
PlayerConnection initialized from C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55250
Multi-casting "[IP] 192.168.1.51 [Port] 55250 [Flags] 2 [Guid] 2046208138 [EditorId] 128146549 [Version] 1048832 [Id] WindowsPlayer(Jennifer-laptop) [Debug] 0 [PackageName] WindowsPlayer [ProjectName] Vaso3DMediapipe" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55250]
PlayerConnection already initialized - listening to [0.0.0.0:55250]
Initialize engine version: 2019.4.18f1 (3310a4d4f880)
[Subsystems] Discovering subsystems at path C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
d3d11: QueryInterface(IDXGIFactory5) failed (80004002).
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon HD 8400 (ID=0x9830)
    Vendor:   
    VRAM:     1509 MB
    Driver:   13.251.9001.1001
Begin MonoManager ReloadAssembly
- Completed reload, in  0.346 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 2.740236 ms
Graph Changed: Hand Tracking
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
GraphSelectorController:OnValueChanged(Dropdown) (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/GraphSelectorController.cs:68)
GraphSelectorController:InitializeOptions() (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/GraphSelectorController.cs:55)
GraphSelectorController:Start() (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/GraphSelectorController.cs:30)
 
(Filename: /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/GraphSelectorController.cs Line: 68)

Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c.dll
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c.dll
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c.dll
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c.dll
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c.dll
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/mediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c.dll
Fallback handler could not load library C:/Users/Jennifer Grieco/Desktop/windowsDemoDeveloper/Vaso3DMediapipe_Data/Mono/libmediapipe_c
DllNotFoundException: mediapipe_c
  at (wrapper managed-to-native) Mediapipe.SafeNativeMethods.mp__SetCustomGlobalPathResolver__P(Mediapipe.ResourceManager/PathResolver)
  at Mediapipe.ResourceManager..ctor () [0x00008] in /Users/antonio/Università/VasoNuovaVersione/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/ResourceManager.cs:20 
  at Mediapipe.AssetBundleManager..ctor () [0x00000] in /Users/antonio/Università/VasoNuovaVersione/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/AssetBundleManager.cs:20 
  at AssetBundleLoader.Start () [0x00001] in /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/ResourceManager/AssetBundleLoader.cs:5 
 
(Filename: /Users/antonio/Università/VasoNuovaVersione/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/ResourceManager.cs Line: 20)

WebCamDevice Changed: HP Truevision HD
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
WebCamDeviceSelectorController:OnValueChanged(Dropdown) (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/WebCamDeviceSelectorController.cs:61)
WebCamDeviceSelectorController:ResetOptions(WebCamDevice[]) (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/WebCamDeviceSelectorController.cs:56)
<Start>d__2:MoveNext() (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/WebCamDeviceSelectorController.cs:45)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/WebCamDeviceSelectorController.cs Line: 61)

WebCamTexture Graphics Format: 88
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
<ResetScreen>d__16:MoveNext() (at /Users/antonio/Università/VasoNuovaVersione/Assets/Mediapipe/Samples/Scripts/WebCamScreenController.cs:54)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Looking forward to your reply
Best Regards

**Comment by pjbaron** [comment]
I'm facing the same situation when building on Windows for Windows (10 Pro).

I have noticed that the dll file is called libmediapipe_c.dll while Safe/UnsafeNativeMethods are looking for mediapipe_c but adjusting the string there generated the same error.

I ran dependencywalker on the libmediapipe_c.dll and it said that the dependency on opencv_world3410.dll was failing.  However I can see that dll in the Plugins/OpenCV folder and even moving it into the same folder as the mediapipe dll reported the same issue in DP.

Currently I'm waiting for a clean build from a new pull to a new folder to complete... if that fails I'll try again after a reboot in case a broken dll is loaded and stuck.

I'll update here if I find a fix or come up with anything else to test.

**Comment by homuler** [comment]
@antoniomarino50242

> When I create the demo for Windows from the mac it doesn't work and notify me "dllNotFoundException Mediapipe_c"
What can I do to fix this problem and make it work on windows?

If you've built native libraries on macOS, then this plugin won't work on Windows, because the built libraries are not compatible with Windows.
Please build them on Windows again. https://github.com/homuler/MediaPipeUnityPlugin#windows

**Comment by homuler** [comment]
@pjbaron Probably you've started UnityEditor before installing `libmediapipe_c.dll` or `opencv_world3410.dll`, then UnityEditor deleted their meta files.
