### ISSUE TITLE
New mediapipe update

### ISSUE THREAD

**Issue by philiprkk** [homuler/MediaPipeUnityPlugin#160]
Quick question, Mediapipe just released an update to their pose tracking accuracy. https://github.com/google/mediapipe/releases/tag/v0.8.4

When can we expect 0.8.4 to be included in the plugin?

Thanks for all the work you've done on this!

**Comment by homuler** [comment]
I'm planning to upgrade this weekend.
But I cannot assert that I can finish it this weekend, since I don't know how difficult it is yet.

**Comment by philiprkk** [comment]
Sounds good. Looking forward to it!

**Comment by homuler** [comment]
Now [v0.6.0](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.6.0) is released, which supports MediaPipe v0.8.4.
