### ISSUE TITLE
wsl2 Ubuntu 20.04 LTS Android build failed -no matching toolchains

### ISSUE THREAD

**Issue by Aashutosh-Dabhade** [homuler/MediaPipeUnityPlugin#161]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): wsl2 Ubuntu 20.04LTS 
- Target (e.g. desktop cpu, android arm64): android arm64
- Bazel version:4.0
- Python version:3.9
- GCC/G++ version:9.3
- Unity version:2019.25.1f
- Android NDK version (if building for Android): r19
- Xcode version (if building for iOS):

**Describe the problem**
I am getting issues while building libraries for the android on wsl2(ubuntu 20.04).
Although I have successfully build library and .apk for mediapipe repository.
the android path is as follows.
$ANDROID_HOME=/root/Android/Sdk
$ANDROID_NDK_HOME=/root/Android/Sdk/ndk-bundle/android-ndk-r19c

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

python3.9 build.py build --android arm64 --opencv=cmake --opencv_deps=ffmpeg -v

**Full logs**

root@DESKTOP-MOU5O95:/home/aashutosh/mediapipe4/MediaPipeUnityPlugin-master# python3.9 build.py build --android arm64 --opencv=cmake --opencv_deps=ffmpeg -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (43 packages loaded, 666 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 5.643s, Critical Path: 0.19s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  /root/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /home/aashutosh/mediapipe4/MediaPipeUnityPlugin-master/packages.config are already installed.
DEBUG (build.py): Copying '.nuget/System.Buffers.4.4.0/lib/netstandard2.0/System.Buffers.dll' to 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget/Google.Protobuf.3.15.6/lib/netstandard2.0/Google.Protobuf.dll' to 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget/System.Memory.4.5.3/lib/netstandard2.0/System.Memory.dll' to 'build/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Memory.dll'...
DEBUG (build.py): Copying '.nuget/System.Runtime.CompilerServices.Unsafe.4.5.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll' to 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build/Plugins/Protobuf/System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_assets`
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe_api:mediapipe_assets (18 packages loaded, 46 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 1.325s, Critical Path: 0.65s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_assets.zip' to 'build/Resources'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Android...
DEBUG (build.py): Running `bazel build -c opt --config=android_arm64 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android`
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3214a78bf55a4fc910e84191acf2e25e/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --cpu, --crosstool_top, --fat_apk_cpu, and 1 more have changed, discarding analysis cache.
ERROR: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 0.245s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 56 targets configured)
Traceback (most recent call last):
  File "/home/aashutosh/mediapipe4/MediaPipeUnityPlugin-master/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/aashutosh/mediapipe4/MediaPipeUnityPlugin-master/build.py", line 153, in run
    self._run_command(self._build_android_commands())
  File "/home/aashutosh/mediapipe4/MediaPipeUnityPlugin-master/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.
root@DESKTOP-MOU5O95:/home/aashutosh/mediapipe4/MediaPipeUnityPlugin-master#
**Additional context**
![image](https://user-images.githubusercontent.com/69786970/117838037-95534400-b297-11eb-8bb3-4b0800cea9f0.png)

**Comment by homuler** [comment]
Please check if you really have set `ANDROID_HOME` and `ANDROID_NDK_HOME`.
```sh
echo $ANDROID_HOME
echo $ANDROID_NDK_HOME`
```

It looks like you logged in as `root` user but your current directory is under another user(`aashutosh`)'s home directory.
If you've set those environment variables for `aashutosh`, they are not set for `root` automatically.

**Comment by Aashutosh-Dabhade** [comment]
Hey, thanks!
You were right. $ANDROID_HOME and $ANDROID_NDK_HOME path were not set for the root user.
I moved mediapipe directory to the root folder and it worked.
Build successfully completed.

**Comment by holaworlds** [comment]
Hi, I got the similar error but I've set ANDROID_HOME and ANDROID_NDK_HOME.

I've run this build command on Macos:
`sudo python build.py build --desktop cpu --android arm64 --opencv=cmake`
Error I got: 

 While resolving toolchains for target `//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type`

<img width="1431" alt="Screen Shot 2021-08-03 at 8 40 12 PM" src="https://user-images.githubusercontent.com/13123340/128061202-78e4d74d-ba32-430d-9233-a1c53094f034.png">
