### ISSUE TITLE
How to pass external textures instead of using WebCamTexture

### ISSUE THREAD

**Issue by manisharan-ys** [homuler/MediaPipeUnityPlugin#163]
Hi

An ARSession is already running on phone. I get camera texture from AR camera preview. I am trying to pass it to MediaPipe graph. Is it possible? If possible can you please suggest the process. Thank you.

**Comment by homuler** [comment]
If the graphics API is OpenGL ES, yes.
But note that it's only available on Android currently (see #126 for iOS support).

To pass an external texture, you need to get its texture name (cf. https://docs.unity3d.com/ScriptReference/Texture.GetNativeTexturePtr.html) first.
https://github.com/homuler/MediaPipeUnityPlugin/blob/92cad4bbe9ba52514034c52ac5b5f0a99accab06/Assets/Mediapipe/Samples/Scripts/DemoGraph.cs#L79-L82

If you have it, you can build `GpuBuffer` from it, and pass that to MediaPipe through `CalculatorGraph#AddPacketToInputStream` API.

https://github.com/homuler/MediaPipeUnityPlugin/blob/92cad4bbe9ba52514034c52ac5b5f0a99accab06/Assets/Mediapipe/Samples/Scripts/DemoGraph.cs#L99-L112

**Comment by manisharan-ys** [comment]
Ok. Let me tell you my requirement here. 
Because ARKit already uses device camera already to show camera preview, I am not able to use WebCamTexture. 
ARKit provides me a texture2D.
I need to pass this texture to MediaPipe Graph and render joints/lines on top of it.
And doing it on iPhone is my first priority. Android is later priority. 

FYI, Unity iOS OpenGLES is deprecated. So I am using Metal Graphics API and samples are working fine with Metal graphics.

Thank you.

**Comment by homuler** [comment]
> FYI, Unity iOS OpenGLES is deprecated. 

Thank you. I know that but to pass texture's native pointer to MediaPipe is not supported yet on iOS.

**Comment by manisharan-ys** [comment]
Okay. Thanks

**Comment by manisharan-ys** [comment]
Actually I am trying to integrate mediapipe with ARKit to use iPhone depth and get 3D world coordinates of the human body tracking.

If mediapipe already provides 3D world coordinates or depth (z), I don't even need to do this. 

I see all the annotations rendered in 2D on image. Does Mediapipe also provide Z/Depth value for pose tracking. Please clarify me on this.

Thanks.

**Comment by manisharan-ys** [comment]
Hi. did you get a chance to read my above message. I appreciate you suggestions. thank you.

**Comment by homuler** [comment]
> Does Mediapipe also provide Z/Depth value for pose tracking.

Please see the official information.
https://google.github.io/mediapipe/solutions/pose.html#output

**Comment by manisharan-ys** [comment]
Able to pass external textures.
1) Disable webcamtexture.play
2) Assign external texture to output texture

**Comment by Bruce-yu199** [comment]
@manisharan-ys Hi, Have you successfully integrate mediapipe with ARKit to use iPhone depth? And may i ask how  you made it
