### ISSUE TITLE
Camera orientation

### ISSUE THREAD

**Issue by jacquesfeng123** [homuler/MediaPipeUnityPlugin#165]
I am trying to run FaceDetection on Unity. 

When I run on my macbook, the FaceDetection works perfectly.

However, when I run on IOS or android, the facemesh is at best 90 degree rotated in the z axis, most often random, and quite often flashing (not being able to detect the face). The iris are also jumping all over the place. 

Also each time I set the playerSettings - player - default orientation to different orientations, it goes nuts.

WebCamTexture.videoRotationAngle does not fix that.

I suspect it has to do with the auto-rotation/gyro capabilities of the phone, but I do not know how to fix that. Please Help.

**Comment by emreboyraz0** [comment]
Did you find any solution?

**Comment by emreboyraz0** [comment]
For Portrait mode give 90 to MainCamera's z index of rotation.
