### ISSUE TITLE
DllNotFoundException while I build linux android version

### ISSUE THREAD

**Issue by jerrysheen** [homuler/MediaPipeUnityPlugin#166]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Ubuntu 20.04.2 LTS
- Target (e.g. desktop cpu, android arm64): android
- Bazel version:  3.7.2
- Python version:  3.9.4
- GCC/G++ version:  9.3.0
- Unity version:   2019.4.26
- Android NDK version (if building for Android): 19.2.5345600
- Xcode version (if building for iOS):

**Describe the problem**
Hey I think I already succesffuly built the android version on linux using docker.
while I can't run the android version on unity, It shows DllNotFound.

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.
![image](https://user-images.githubusercontent.com/19220015/118368724-1af72c80-b5d5-11eb-90aa-421acab03c49.png)
And I already set the load on startup for mediapipe_android, and in side the same place I can see the aar  file.
![image](https://user-images.githubusercontent.com/19220015/118368988-411ccc80-b5d5-11eb-9663-cae0304b0b73.png)

I'm curious that have I set the wrong opencv path here?
![image](https://user-images.githubusercontent.com/19220015/118369366-aec8f880-b5d5-11eb-9052-4844545cce9a.png)
Since my openCV file is inside my  /usr/lib/x86_64-linux-gnu

![image](https://user-images.githubusercontent.com/19220015/118369417-dcae3d00-b5d5-11eb-9f42-02e4a2d70288.png)

**Full logs**

**Additional context**

**Comment by homuler** [comment]
You need to build native libraries for Desktop to run scenes on UnityEditor.
So please run the below command and restart UnityEditor.

```sh
python build.py build --desktop gpu -vv
```

**Comment by jerrysheen** [comment]
> You need to build native libraries for Desktop to run scenes on UnityEditor.
> So please run the below command and restart UnityEditor.
> 
> ```shell
> python build.py build --desktop gpu -vv
> ```

Then could you please tell me how can I run Unity Android version, as you can see I switched to Android platform in unity, but failed to get mediapipe.

**Comment by homuler** [comment]
Have you run the below command successfully?
> ```sh
> python build.py build --desktop gpu -vv
> ```

**Comment by jerrysheen** [comment]
No , it shows the following error:

```
ERROR: /home/st/.cache/bazel/_bazel_st/3695023b97f4d1792ddeaeae288fe1c2/external/com_google_mediapipe/mediapipe/calculators/tensor/BUILD:625:11: C++ compilation of rule '@com_google_mediapipe//mediapipe/calculators/tensor:image_to_tensor_converter_gl_buffer' failed (Exit 1): gcc failed: error executing command 
  (cd /home/st/.cache/bazel/_bazel_st/3695023b97f4d1792ddeaeae288fe1c2/sandbox/linux-sandbox/1574/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/st/anaconda3/envs/py3.9/bin:/home/st/anaconda3/condabin:/home/st/.local/bin:/home/st/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/anaconda3/bin:/home/st/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/com_google_mediapipe/mediapipe/calculators/tensor/_objs/image_to_tensor_converter_gl_buffer/image_to_tensor_converter_gl_buffer.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/com_google_mediapipe/mediapipe/calculators/tensor/_objs/image_to_tensor_converter_gl_buffer/image_to_tensor_converter_gl_buffer.pic.o' -fPIC -DMEDIAPIPE_PROFILER_AVAILABLE -iquote external/com_google_mediapipe -iquote bazel-out/k8-opt/bin/external/com_google_mediapipe -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_github_glog_glog -iquote bazel-out/k8-opt/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-opt/bin/external/com_github_gflags_gflags -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/FP16 -iquote bazel-out/k8-opt/bin/external/FP16 -Ibazel-out/k8-opt/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/k8-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -Ibazel-out/k8-opt/bin/external/FP16/_virtual_includes/FP16 -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/FP16/include -isystem bazel-out/k8-opt/bin/external/FP16/include -w -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc -o bazel-out/k8-opt/bin/external/com_google_mediapipe/mediapipe/calculators/tensor/_objs/image_to_tensor_converter_gl_buffer/image_to_tensor_converter_gl_buffer.pic.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command 
  (cd /home/st/.cache/bazel/_bazel_st/3695023b97f4d1792ddeaeae288fe1c2/sandbox/linux-sandbox/1574/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/st/anaconda3/envs/py3.9/bin:/home/st/anaconda3/condabin:/home/st/.local/bin:/home/st/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/anaconda3/bin:/home/st/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/com_google_mediapipe/mediapipe/calculators/tensor/_objs/image_to_tensor_converter_gl_buffer/image_to_tensor_converter_gl_buffer.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/com_google_mediapipe/mediapipe/calculators/tensor/_objs/image_to_tensor_converter_gl_buffer/image_to_tensor_converter_gl_buffer.pic.o' -fPIC -DMEDIAPIPE_PROFILER_AVAILABLE -iquote external/com_google_mediapipe -iquote bazel-out/k8-opt/bin/external/com_google_mediapipe -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_github_glog_glog -iquote bazel-out/k8-opt/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-opt/bin/external/com_github_gflags_gflags -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/FP16 -iquote bazel-out/k8-opt/bin/external/FP16 -Ibazel-out/k8-opt/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/k8-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -Ibazel-out/k8-opt/bin/external/FP16/_virtual_includes/FP16 -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/FP16/include -isystem bazel-out/k8-opt/bin/external/FP16/include -w -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc -o bazel-out/k8-opt/bin/external/com_google_mediapipe/mediapipe/calculators/tensor/_objs/image_to_tensor_converter_gl_buffer/image_to_tensor_converter_gl_buffer.pic.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::GlProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc:315:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 43.129s, Critical Path: 24.75s
INFO: 541 processes: 136 internal, 405 linux-sandbox.
```

**Comment by homuler** [comment]
Well, please fill in required fields -> https://github.com/homuler/MediaPipeUnityPlugin/issues/166#issue-892476363

I guess your GCC version is less than 8 (Ubuntu 18.04?).

**Comment by jerrysheen** [comment]
> Well, please fill in required fields -> [#166 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/166#issue-892476363)
> 
> I guess your GCC version is less than 8 (Ubuntu 18.04?).

Sorry for the inconvinience, I already modify it, yes my gcc version is less than 8

**Comment by jerrysheen** [comment]
I built it successfully, but still can't find the dll.

This is my opencv_linux.BUILD, I can find the required file at /lib/x86_64-linux-gnu/
![image](https://user-images.githubusercontent.com/19220015/118677092-8b4cba80-b82e-11eb-9697-42215719b964.png)

and This is my linux_opencv config, I suspect whether it's right or not.
![image](https://user-images.githubusercontent.com/19220015/118677350-c6e78480-b82e-11eb-9418-8e8e09d3f2ed.png)

![image](https://user-images.githubusercontent.com/19220015/118677045-81c35280-b82e-11eb-810b-edcc7e93e474.png)

And here is what in the unity
![image](https://user-images.githubusercontent.com/19220015/118676964-6f491900-b82e-11eb-9acb-c6500a1fc823.png)

can you please help me ? thanks

**Comment by jerrysheen** [comment]
> I built it successfully, but still can't find the dll.
> 
> This is my opencv_linux.BUILD, I can find the required file at /lib/x86_64-linux-gnu/
> ![image](https://user-images.githubusercontent.com/19220015/118677092-8b4cba80-b82e-11eb-9697-42215719b964.png)
> 
> and This is my linux_opencv config, I suspect whether it's right or not.
> ![image](https://user-images.githubusercontent.com/19220015/118677350-c6e78480-b82e-11eb-9418-8e8e09d3f2ed.png)
> 
> ![image](https://user-images.githubusercontent.com/19220015/118677045-81c35280-b82e-11eb-810b-edcc7e93e474.png)
> 
> And here is what in the unity
> ![image](https://user-images.githubusercontent.com/19220015/118676964-6f491900-b82e-11eb-9acb-c6500a1fc823.png)
> 
> can you please help me ? thanks

Well I'm quite confused about what I should set in WORKSPACE and opencv_linux.Build.

According to my understanding :
if I set opencv_linux. build  to 
```
 #          "lib/x86_64-linux-gnu/libopencv_core.so",
 #           "lib/x86_64-linux-gnu/libopencv_calib3d.so",
 #           "lib/x86_64-linux-gnu/libopencv_features2d.so",
 #           "lib/x86_64-linux-gnu/libopencv_highgui.so",
 #           "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
 #           "lib/x86_64-linux-gnu/libopencv_imgproc.so",
 #           "lib/x86_64-linux-gnu/libopencv_video.so",
 #           "lib/x86_64-linux-gnu/libopencv_videoio.so",
```
Then I should set WORSPACE to 
```
new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr",
)

```


while if I set opencv_linux. build  to 
```
            "lib/libopencv_core.so",
            "lib/libopencv_calib3d.so",
           "lib/libopencv_features2d.so",
            "lib/libopencv_highgui.so",
            "lib/libopencv_imgcodecs.so",
            "lib/libopencv_imgproc.so",
            "lib/libopencv_video.so",
            "lib/libopencv_videoio.so",
```
Then I should set WORSPACE to 
```
new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "path to opencv/build",
)

```

Am I rifght ? I'm quite confused about it..

**Comment by homuler** [comment]
> Then I should set WORSPACE to
> ```txt
> new_local_repository(
>     name = "linux_opencv",
>     build_file = "@//third_party:opencv_linux.BUILD",
>     path = "path to opencv/build",
> )
> ```

No, `path` must be the installed directory.
[new_local_repository](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository) define the specified path as its project root directory.
Say you have below files on your local machine.
```txt
/path/to/project1/lib/x.so
/path/to/project1/lib/y.so
/path/to/project1/include/x.h
/path/to/project1/include/y.h
/path/to/project2/lib/x.so
```

In this case, to import `project1`, your `WORKSPACE` file would be like this.
```starlark
new_local_repository(
    name = "project1",
    build_file = "@//third_party:project1.BUILD",
    path = "/path/to/project1",
)
```

Then, in `third_party/project1.BUILD`, you can access files under `/path/to/project1` (note that you cannot access `/path/to/project2/lib/x.so`).
```starlark
cc_library(
    name = "opencv",
    srcs = [
      # relative paths from /path/to/project1
      "lib/x.so",
      "lib/y.so",
    ],
    hdrs = [
      "include/x.h",
      "include/y.h",
    ]),
    includes = [
      "include/",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```

**Comment by homuler** [comment]
By the way, you don't need to install OpenCV necessarily.
Run `python build.py build --desktop --opencv=cmake -vv`, then OpenCV will be built and linked statically.

cf. https://github.com/homuler/MediaPipeUnityPlugin#build-command
