### ISSUE TITLE
ERROR: PKGBUILD contains CRLF characters and cannot be sourced.

### ISSUE THREAD

**Issue by TheBricktop** [homuler/MediaPipeUnityPlugin#169]
**System information**
- Linux Ubuntu 20.04, WSL2
-  android arm64

**Describe the problem**

**Steps to reproduce the issue**
Set up a docker image with linux containers on w10 with ubuntu 20.04 WSL2
tried to run provided docker build command
got stuck on ffmpeg build

the error probably fires because of the win10 line endings

**Full logs**

C:\Users\Student\Documents\GitHub\MediapipeUnityPlugin>docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile
[+] Building 4.9s (25/32)
 => [internal] load build definition from Dockerfile                                                            0.0s
 => => transferring dockerfile: 32B                                                                             0.0s
 => [internal] load .dockerignore                                                                               0.0s
 => => transferring context: 2B                                                                                 0.0s
 => [internal] load metadata for docker.io/library/archlinux:latest                                             2.3s
 => [auth] library/archlinux:pull token for registry-1.docker.io                                                0.0s
 => [internal] load build context                                                                               0.0s
 => => transferring context: 70.97kB                                                                            0.0s
 => [builder  1/10] FROM docker.io/library/archlinux:latest@sha256:cc43265632a26d85865ef26f3066da170dc159c571b  0.0s
 => CACHED [builder  2/10] RUN if [[ "${RANKMIRROS}" ]]; then         pacman -Syu pacman-contrib --needed --no  0.0s
 => CACHED [builder  3/10] RUN pacman -Syuu sudo --needed --noconfirm                                           0.0s
 => CACHED [builder  4/10] RUN echo -e "%wheel ALL=(ALL) NOPASSWD: ALL\n" > /etc/sudoers.d/01_wheel             0.0s
 => CACHED [builder  5/10] RUN useradd -u 1000 -m mediapipe && usermod -aG wheel mediapipe                      0.0s
 => CACHED [builder  6/10] WORKDIR /home/mediapipe                                                              0.0s
 => CACHED [builder  7/10] RUN sudo pacman -Sy base-devel git glibc unzip --needed --noconfirm                  0.0s
 => CACHED [builder  8/10] RUN git clone https://aur.archlinux.org/yay.git                                      0.0s
 => CACHED [builder  9/10] RUN cd yay && makepkg -si --noconfirm                                                0.0s
 => CACHED [builder 10/10] RUN rm -rf yay                                                                       0.0s
 => CACHED [android 1/5] RUN yay -Sy android-sdk android-sdk-build-tools android-sdk-platform-tools android-pl  0.0s
 => CACHED [android 2/5] RUN curl -L https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zi  0.0s
 => CACHED [android 3/5] RUN sudo unzip android-ndk.zip -d /opt                                                 0.0s
 => CACHED [android 4/5] RUN sudo mv /opt/android-ndk-r21e /opt/android-ndk                                     0.0s
 => CACHED [android 5/5] RUN rm android-ndk.zip                                                                 0.0s
 => CACHED [stage-2  1/12] COPY --from=android /opt/android-sdk /opt/android-sdk                                0.0s
 => CACHED [stage-2  2/12] COPY --from=android /opt/android-ndk /opt/android-ndk                                0.0s
 => CACHED [stage-2  3/12] RUN mkdir ffmpeg                                                                     0.0s
 => CACHED [stage-2  4/12] ADD docker/linux/x86_64/ffmpeg/ ffmpeg/                                              0.0s
 => ERROR [stage-2  5/12] RUN cd ffmpeg &&     yay -Sy &&     makepkg -si --needed --noconfirm &&     cd .. &&  2.5s
------
 > [stage-2  5/12] RUN cd ffmpeg &&     yay -Sy &&     makepkg -si --needed --noconfirm &&     cd .. &&     rm -rf ffmpeg:
#25 0.254 :: Synchronizing package databases...
#25 0.676  core is up to date
#25 0.676  extra is up to date
#25 0.676 downloading community.db...
#25 2.449 ==> ERROR: PKGBUILD contains CRLF characters and cannot be sourced.
------
executor failed running [/bin/sh -c cd ffmpeg &&     yay -Sy &&     makepkg -si --needed --noconfirm &&     cd .. &&     rm -rf ffmpeg]: exit code: 12

**Additional context**

**Comment by homuler** [comment]
I guess you've configured git to replace LF with CRLF when checking out files (cf. `core.autocrlf`).

**Comment by TheBricktop** [comment]
Yes ive found how to fix it fast using Notepad++, just open the pkgbuild with np++ and EOL convert with linux endings

**Comment by homuler** [comment]
> Yes ive found how to fix it fast using Notepad++, just open the pkgbuild with np++ and EOL convert with linux endings

Well, please make sure that Git keeps LFs in all the files.
This time, LFs in `vmaf-model-path.patch`  must be replaced with CRLF.

**Comment by TheBricktop** [comment]
Thank You for quick response. It started building properly.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843014178
