### ISSUE TITLE
Anyway it runs on a Windows Desktop?

### ISSUE THREAD

**Issue by tutu5110** [homuler/MediaPipeUnityPlugin#17]
Any ways to get around in Windows? Thanks for your work!

**Comment by homuler** [comment]
I believe that the native plugin(dll) can be built on Windows with some effort (minor code changes), but I have not tried it yet.
However, we cannot make use of GPU acceleration on Windows in any case, because MediaPipe does not support it.

**Comment by Densen90** [comment]
I would also be interested in doing that, @tutu5110  if you figure it out I would be happy to hear about it.

**Comment by time2smile** [comment]
Same here

**Comment by luanolavolucas** [comment]
> I believe that the native plugin(dll) can be built on Windows with some effort (minor code changes), but I have not tried it yet.
> However, we cannot make use of GPU acceleration on Windows in any case, because MediaPipe does not support it.

Could you give some pointers about this? I'm really interesting in building a native dll to use in Windows Unity. I've built the project in Lubuntu and dragged the files over to Windows and experienced the DllNotFoundError. I suppose there's no way to fix that without building the whole thing correctly, right?

**Comment by homuler** [comment]
Some problems may remain, but today I confirmed that the plugin works on Windows.
To [install MediaPipe on Windows](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) itself doesn't look as straightforward as on Linux for me, but once you succeed it, you can [build this plugin](https://github.com/homuler/MediaPipeUnityPlugin#windows-10) too.
