### ISSUE TITLE
Import into Unity 

### ISSUE THREAD

**Issue by aidenpearce001** [homuler/MediaPipeUnityPlugin#170]
**System information**
- OS Platform: Windows 10
- Target: Desktop cpu
- Bazel version: 4.0.0
- Python version: 3.9
- GCC/G++ version:
- Unity version: Unity 2020.3.8f1 (64-bit)
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
After build complete i dont know how to import what i just build into Unity
![image](https://user-images.githubusercontent.com/56188293/118590399-91aa4a80-b7cc-11eb-94df-d249424b6e6c.png)
What I have is some foder:
- bazel-bin
- bazel-mediapipeunityplugin
- bazel-out
- bazel-testlogs
- and _bzl in C:/

**Steps to reproduce the issue**
I'm buid by using this command:
python build.py build --desktop cpu --include_opencv_libs -v

Everything work fine

**Comment by homuler** [comment]
If you'd like to run the sample app, all the required libraries have been installed, so just [open the project](https://docs.unity3d.com/Manual/GettingStarted.html). 
If you'd like to import this plugin into existing projects, see https://docs.unity3d.com/2020.3/Documentation/Manual/upm-ui-local.html

**Comment by aidenpearce001** [comment]
> If you'd like to run the sample app, all the required libraries have been installed, so just [open the project](https://docs.unity3d.com/Manual/GettingStarted.html).
> If you'd like to import this plugin into existing projects, see https://docs.unity3d.com/2020.3/Documentation/Manual/upm-ui-local.html

This is what I get when o try to import package.json in Packages/com.github.homuler.mediapipe, help me sir !
![image](https://user-images.githubusercontent.com/56188293/118766846-2f724800-b8a7-11eb-9471-edbf690191a3.png)

**Comment by homuler** [comment]
> This is what I get when o try to import package.json in Packages/com.github.homuler.mediapipe

I guess you tried importing `Packages/com.github.homuler.mediapipe` to this project, but you don't need to do that. 
Please just select `DesktopDemo` scene (`Assets/Mediapipe/Samples/Scenes/DesktopDemo.unity`) and run it.
If the scene does not work, then please tell me.

**Comment by aidenpearce001** [comment]
> > This is what I get when o try to import package.json in Packages/com.github.homuler.mediapipe
> 
> I guess you tried importing `Packages/com.github.homuler.mediapipe` to this project, but you don't need to do that.
> Please just select `DesktopDemo` scene (`Assets/Mediapipe/Samples/Scenes/DesktopDemo.unity`) and run it.
> If the scene does not work, then please tell me.

But what i want its import the package that i just build and the package.json only in Packages/com.github.homuler.mediapipe so that Packages/com.github.homuler.mediapipe its the only Package that i can import into my project

**Comment by homuler** [comment]
Can you run the sample scene (`DesktopDemo`)?
If so, the above error (`Plugins: Failed to load 'C:/path/to/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.` ) is expected on Windows currently, so please just ignore it.

**Comment by aidenpearce001** [comment]
> Can you run the sample scene (`DesktopDemo`)?
> If so, the above error (`Plugins: Failed to load 'C:/path/to/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.` ) is expected on Windows currently, so please just ignore it.

When i build and run its work perfectly, but when i press play i get this error
![image](https://user-images.githubusercontent.com/56188293/119022792-32665900-b9cb-11eb-93ce-80d391be5be8.png)

Will it's affect the project, sir?

**Comment by homuler** [comment]
Yes, you need to make sure that the sample app runs.
Will you run `git checkout Packages/com.github.homuler.mediapipe/Runtime` and start UnityEditor again?

**Comment by jjjhhjjh** [comment]
I am having the same problem. What should I do
