### ISSUE TITLE
 Build successfully but meet the "missing a using directive or an assembly reference" error

### ISSUE THREAD

**Issue by jerrysheen** [homuler/MediaPipeUnityPlugin#175]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):Linux Ubuntu 20.04
- Target (e.g. desktop cpu, android arm64):desktop cpu/gpu
- Bazel version:  3.7.2
- Python version:  3.9.4
- GCC/G++ version: 9.3.0
- Unity version: 2019.4.26
- Android NDK version (if building for Android):  /
- Xcode version (if building for iOS):  /

**Describe the problem**
I've successfully built the linux desktop version
But when I open it in unity it shows error as follows:
**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.
![image](https://user-images.githubusercontent.com/19220015/118833685-3b382b80-b8f4-11eb-8777-de4155f83022.png)
![image](https://user-images.githubusercontent.com/19220015/118834064-881c0200-b8f4-11eb-8e41-c7573e601eb7.png)

**Full logs**

**Additional context**

please help me with this problem

**Comment by homuler** [comment]
At v0.6.0, the sample app's Unity version becomes 2020.3.8f1. Does this error occur with Unity 2020.3.8f1?

**Comment by jerrysheen** [comment]
Yes, After change the version to 2020.3.8.f1, the error was gone, but still I meet the dll not found error:
![image](https://user-images.githubusercontent.com/19220015/119285895-b0e62380-bc75-11eb-9602-07735f2645fe.png)
This time I use `python build.py build --desktop gpu --opencv=cmake -v` to config my file

**Comment by philiprkk** [comment]
In my experience you can can ignore that error when opening Unity. Hope this applies to you as well 😅

**Comment by homuler** [comment]
If the build command finishes successfully, I guess there are some missing dependencies.
Please run the below command and check if `libmediapipe_c.so` fails to link some libraries. 
```sh
ldd Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.so
```
