### ISSUE TITLE
namespace error

### ISSUE THREAD

**Issue by jjjhhjjh** [homuler/MediaPipeUnityPlugin#177]
There are errors in some namespaces How can I fix it?

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(3,32): error CS0234: The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(31,62): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\ClassificationAnnotationController.cs(13,49): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\DetectionAnnotationController.cs(44,49): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraph.cs(32,30): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectPacket.cs(4,36): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

**Comment by homuler** [comment]
Please use [this template](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-installation-issue.md) to describe your issue.

Have you run [build command](https://github.com/homuler/MediaPipeUnityPlugin#build-command) and did it finish successfully?

**Comment by jjjhhjjh** [comment]
> Please use [this template](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-installation-issue.md) to describe your issue.
> 
> Have you run [build command](https://github.com/homuler/MediaPipeUnityPlugin#build-command) and did it finish successfully?

System information

OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): window10 pro
Target (e.g. desktop cpu, android arm64):desktop cpu/gpu
Bazel version: 4.00
Python version: 3.7
GCC/G++ version: 8.1.0
Unity version: 2020.3.8f
Android NDK version (if building for Android): /
Xcode version (if building for iOS): /

Describe the problem
I wanted to build Android on desktop,
I simply opened the project in Unity and the error is displayed as shown in the picture. How do I fix it




![K-115](https://user-images.githubusercontent.com/8858397/119057925-585e1e80-ba08-11eb-95ca-defc3b0c0861.png)
![K-116](https://user-images.githubusercontent.com/8858397/119057927-598f4b80-ba08-11eb-92ee-a9e797b6d86a.png)

**Comment by homuler** [comment]
Please build native libraries first.
https://github.com/homuler/MediaPipeUnityPlugin#installation-guide

**Comment by jjjhhjjh** [comment]
An error occurs while running the HelloWorld example. How do I fix it
![K-001](https://user-images.githubusercontent.com/8858397/119448947-f0436b80-bd6c-11eb-9f40-e77d804c10be.png)

**Comment by jjjhhjjh** [comment]
> Please build native libraries first.
> https://github.com/homuler/MediaPipeUnityPlugin#installation-guide

**Comment by jjjhhjjh** [comment]
The build was successful, but when I open it in Unity I get the error, what's the problem?


![K-001](https://user-images.githubusercontent.com/8858397/119932608-4d822b80-bfbe-11eb-88e4-2ca3c724af75.png)
