### ISSUE TITLE
mediapipe_android failed to build in docker

### ISSUE THREAD

**Issue by aidenpearce001** [homuler/MediaPipeUnityPlugin#179]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10 (WSL2)
- Target (e.g. desktop cpu, android arm64): android arm64
- Bazel version: 4.0.0
- Python version: 3.9 
- GCC/G++ version: 11.1.0
- Unity version:
- Android NDK version (if building for Android): 4.9
- Xcode version (if building for iOS):

**Describe the problem**
![image](https://user-images.githubusercontent.com/56188293/119082240-dbdb3800-ba27-11eb-990d-051bffd711f7.png)

**Steps to reproduce the issue**
I got this error when tried to excute: 
bazel build -c opt --config=android_arm64 mediapipe_api/java/com/github/homuler/mediapipe/mediapipe_android --sandbox_debug --verbose_failures 

**Full logs**
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "b1788ea6d99fed9bdd32a0fb15badf8a1dd0e26eb60cc58ea845571b5e4ca54b"
DEBUG: Repository rules_cc instantiated at:
  /home/mediapipe/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /home/mediapipe/WORKSPACE:34:23: in <toplevel>
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:AudioDataConsumer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:AudioDataProcessor.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:AudioDataProducer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:CameraHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:CameraXPreviewHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:ExternalTextureConverter.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:FrameProcessor.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:MicrophoneHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:PermissionHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:TextureFrameConsumer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:TextureFrameProcessor.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/components:TextureFrameProducer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:AndroidAssetUtil.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:AndroidPacketCreator.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:AndroidPacketGetter.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:AppTextureFrame.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:AssetCache.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:AssetCacheDbHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:Compat.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:GlSyncToken.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:Graph.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:GraphGlSyncToken.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:GraphProfiler.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:GraphService.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:GraphTextureFrame.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:MediaPipeException.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:MediaPipeRunner.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:Packet.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:PacketCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:PacketCreator.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:PacketGetter.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:PacketListCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:PacketWithHeaderCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:ProtoUtil.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:SurfaceOutput.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:TextureFrame.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:TextureReleaseCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:TypeNameRegistry.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/framework:TypeNameRegistryLite.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/glutil:CommonShaders.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/glutil:EglManager.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/glutil:ExternalTextureRenderer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/glutil:GlThread.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/glutil:ShaderUtil.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
WARNING: /home/mediapipe/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:4:14: in srcs attribute of android_library rule //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: please do not import '@com_google_mediapipe//mediapipe/java/com/google/mediapipe/glutil:TextureRenderer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
INFO: Analyzed target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/com_google_absl/absl/synchronization/BUILD.bazel:30:11: Compiling absl/synchronization/internal/graphcycles.cc [for host] failed: (Exit 1): process-wrapper failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/983/execroot/mediapipe_api && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/install/7d2b3f5c6b30e908ff6ea9e8458da328/process-wrapper '--timeout=0' '--kill_delay=15' /usr/sbin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.d '-frandom-seed=bazel-out/host/bin/external/com_google_absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.o' -iquote external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -g0 -g0 '-std=c++17' -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare -DNOMINMAX -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_absl/absl/synchronization/internal/graphcycles.cc -o bazel-out/host/bin/external/com_google_absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.o) process-wrapper failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/983/execroot/mediapipe_api && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/install/7d2b3f5c6b30e908ff6ea9e8458da328/process-wrapper '--timeout=0' '--kill_delay=15' /usr/sbin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.d '-frandom-seed=bazel-out/host/bin/external/com_google_absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.o' -iquote external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -g0 -g0 '-std=c++17' -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare -DNOMINMAX -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_absl/absl/synchronization/internal/graphcycles.cc -o bazel-out/host/bin/external/com_google_absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.o)
external/com_google_absl/absl/synchronization/internal/graphcycles.cc: In member function 'void absl::lts_2020_09_23::synchronization_internal::GraphCycles::RemoveNode(void*)':
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:26: error: 'numeric_limits' is not a member of 'std'
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before '>' token
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:52: error: '::max' has not been declared; did you mean 'std::max'?
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/algorithm:62,
                 from external/com_google_absl/absl/synchronization/internal/graphcycles.cc:38:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/stl_algo.h:3467:5: note: 'std::max' declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 25.613s, Critical Path: 25.29s
INFO: 265 processes: 131 internal, 134 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Additional context**
As i know "Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found" its not the problem because the other mirror its work :https://github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz is working fine

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843222262

Will you try Ubuntu container, please?

**Comment by aidenpearce001** [comment]
> [#172 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843222262)
> 
> Will you try Ubuntu container, please?

Tks bro its work perfect i will close this, tks you!
