### ISSUE TITLE
EntryPointNotFoundException: MpGpuResourcesGlContext

### ISSUE THREAD

**Issue by elblogbruno** [homuler/MediaPipeUnityPlugin#18]
Hello @homuler !
First of all I use this to post the issue as well as to ask if you have an email you can share with me, I would like to contact you.
Going to the point, I updated by recalling `make android_arm` and `make install`, because I found out mediapipe updated hand graphs for more speed.

Now running the app gives this error:

![image](https://user-images.githubusercontent.com/10481058/98733612-11300a80-23a1-11eb-8ff6-cdc891676c06.png)

Maybe the update has changed something?
Thanks
Bruno

**Comment by homuler** [comment]
Will you pull the latest commit and try again?
At least, current source does not include the entry point called `MpGpuResourcesGlContext`.

> if you have an email you can share with me, I would like to contact you.

If you're OK, I'm in the official slack and you can DM to me there.
https://google.github.io/mediapipe/#community

By the way, I have not updated MediaPipe version yet (using v0.7.11 now), so I think the performance has not changed.

**Comment by elblogbruno** [comment]
Thanks for such a fast answer! I'll dm you!

**Comment by homuler** [comment]
Now it uses MediaPipe 0.8.0.

**Comment by elblogbruno** [comment]
Ok I will try that! Thanks
good job!
