### ISSUE TITLE
MacOS Build Issues

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#180]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Mac i5 2020 
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 3.7.2
- Python version: 3.9
- GCC/G++ version: 4.2.1
- Unity version: 2019.4.26f1
- Android NDK version (if building for Android): 22.x
- Xcode version (if building for iOS): 12.x

**Describe the problem**
Hello @homuler, Over this weekend, I've been trying to run your repository on a Macbook. And as usual, I'm getting build issues. I'm able to run hello-world using the official mediapipe repository but here I'm getting the following build issues in my terminal. 

**Full logs**
![Screenshot_2](https://user-images.githubusercontent.com/43686606/119256220-4a152b80-bbdd-11eb-8d94-98bd0bb3941e.png)
![Screenshot_3](https://user-images.githubusercontent.com/43686606/119256223-4bdeef00-bbdd-11eb-8b9b-5b3e47a0a166.png)

**Comment by shivaylamba** [comment]
@homuler Hi! could you help with this issue?

**Comment by homuler** [comment]
Have you installed Android SDK and Java?
