### ISSUE TITLE
Error while initializing graph

### ISSUE THREAD

**Issue by manisharan-ys** [homuler/MediaPipeUnityPlugin#181]
Hi.

I extracted texture from AR Foundation (ARKit). Trying to pass this texture to Mediapipe. In the process, At the time of initializing graph getting the following error.

WARNING: Logging before InitGoogleLogging() is written to STDERR
F20210524 20:22:12.422282 79132864 calculator_graph.cc:125] Non-OK-status: Initialize(config) status: NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: FaceDetectionFrontCpu; Unable to find Calculator "FaceDetectionFrontCpu"
*** Check failure stack trace: ***

What could be the reason for this error?

Can I pass a texture of any size or should it be constant 640*480?

Thank you.

**Comment by homuler** [comment]
Please use [issue templates](https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/.github/ISSUE_TEMPLATE/build-installation-issue.md) and describe your environment (tool versions, target platform, etc...).

If your target platform is iOS, then you may have built your app with [`Use GPU` unchecked](https://github.com/homuler/MediaPipeUnityPlugin#desktop).
Please check `Use GPU` and build it again.

**Comment by manisharan-ys** [comment]
"Use GPU" worked. thank you.
