### ISSUE TITLE
gl_animation_overlay_calculator lost the code about android

### ISSUE THREAD

**Issue by RMiTiG** [homuler/MediaPipeUnityPlugin#182]
My goal is to render the sneaker.obj by the Mediapipe in the graph (Objectron)
The build command I used : python build.py build --desktop cpu --android arm64
And the box can be rendered successfully on my android (SystemInfo.graphicsDeviceVersion is opengl es 3.2)
But it seem like that the obj_asset_name and obj_texture doesn't work at all
Then I follow this method : https://qiita.com/akicchi/items/bab85ddbb7e17e9ca42c
It's crash on the android,then I compare the gl_animation_overlay_calculator I used to the google/mediapipe(0.8.4)
I found that the calculator lost some code about android and it's handled in the file "MediaPipeUnityPlugin/third_party/mediapipe_model_path.diff"
I search the reason in commit history but failed, why that is so?

**Comment by homuler** [comment]
It's because `GlAnimationOverlayCalculator` uses APIs that are only available on Android.

cf. https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/object_detection_3d/calculators/gl_animation_overlay_calculator.cc#L375

Those APIs are used to read local files such as `*.tflite`, but to use those APIs on Unity, we need to access MediaPipe's Java APIs.
After all, MediaPipe's Java APIs are based on its C++ APIs, so I chose to use C++ APIs exclusively when we read local files (see [ResourceManager.cs](https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/ResourceManager.cs) and [resource_util_custom.cc](https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/mediapipe_api/util/resource_util_custom.cc)).

It'd be better if we can rewrite `GlAnimationOverlayCalculator` and make it work on other devices than Android, but I thought we would rather render 3D textures with Unity (at least we can receive `ModelMatrix` data from MediaPipe), so I simply removed related code.

**Comment by RMiTiG** [comment]
Thanks for great explanation! It would be more easier to try-on tresting if it work.But my target devices is mobile, and the docs show that the objectron crashes sometimes on ios.Is it necessary for me to make it work on ios? Or, Will it be fixed in the future?

And I agree that rendering by unity better than mediapipe.I also working on accessing the output stream.Grateful for any suggestion.

**Comment by homuler** [comment]
> Is it necessary for me to make it work on ios? Or, Will it be fixed in the future?

I was not planning to fix it, but PRs are welcome!
MediaPipe [usually call `PathToResourceAsFile`](https://github.com/google/mediapipe/blob/ae05ad04b3ae43d475ccb2868e23f1418fea8746/mediapipe/calculators/tflite/tflite_tensors_to_classification_calculator.cc#L103-L104) to resolve file paths, but it doesn't in `GlAnimationOverlayCalculator`.
This plugin utilizes `PathToResourceAsFile`, so I guess if `GlAnimationOverlayCalculator` calls this API, this issue can be fixed.

> I also working on accessing the output stream.Grateful for any suggestion.

If you can access `model_mask_matrices`, it will help us to render 3D models by Unity.
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Graphs/ObjectDetection3d/Resources/object_detection_3d_gpu.txt#L140

To receive data from `model_mask_matrices`, you need to define `output_stream` and [poll](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Scripts/DemoGraph.cs#L139) or [subscribe](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Graphs/InstantMotionTracking/Scripts/InstantMotionTrackingGraph.cs#L57) it.
Please see below links for more details.
https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/Assets/Mediapipe/Samples/Graphs/HandTracking/Resources/hand_tracking_desktop_gpu.txt#L35
https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/Assets/Mediapipe/Samples/Graphs/HandTracking/Resources/hand_tracking_desktop_gpu.txt#L87

If I don't misunderstand `model_mask_matrices`, the output type is `TimedModelMatrixProtoList`.
You can use `TimedModelMatrixProtoListPacket` as a `Packet` class to receive data from the stream.

**Comment by emreboyraz0** [comment]
Hi;


> Thanks a lot! I have got the model_matrices and mask_model_matrices both in Android and iOS through your suggestion. The InstantMotionTrackingGraph contains all the code I need.
> As the issue answered,I am closing it now.

1 - Can you share your solution code with us? I have mask problem but could not understand Homuler's solution.

2 - Also Is your textures are seems black in IOS? if not how did you solved problem?

**Comment by RMiTiG** [comment]
> 1 - Can you share your solution code with us? I have mask problem but could not understand Homuler's solution.
>
> 2 - Also Is your Objectron 3d textures are seems black in IOS ? if not how did you solved problem?
@emreboyraz0 Sorry for late reply.MediaPipe render model and texture by GlAnimationOverlayCalculator which is use AAssetManager to handle the file path.And AAssetManager is only works for Android.That is why textures are seems black in IOS (lost texture).If you want to solve this problem,you can try to use PathToResourceAsFile instead of AAssetManager just like Homuler said.
My solution is render in Unity instead of GlAnimationOverlayCalculator(At least render better).And we need to export the orientation and position, the scale of box from calculator .That is what Homuler means.

**Comment by emreboyraz0** [comment]
Thanks for reply. I rendering 3d models in unity using InstantMotionTrackingGraph codes. It gives 
`        var matrix = Matrix4x4FromBytes(matrices);
`
1 - But can not figure it out how to assign matrix to 3d models. I extract scale, rotation and position but I can not figure it out correctly. Because rotation and positioning not exactly same with Mediapipe's rendered model.

2 - Also did you occlude your leg ? because my foot in inside of shoe.

**Comment by RMiTiG** [comment]
@emreboyraz0
>how to assign matrix to 3d models

Sorry that I don't konw beacuse I need the eight bounding point's position,so I export lifted_objects instead of model_matrix to receive the position in screen coordinate.To export lifted_objects, we need to define it's packet, reference https://github.com/homuler/MediaPipeUnityPlugin/issues/187.
>did you occlude your leg 

MediaPipe doesn't support the occlusion and distinguish between the left and right.We need to use hack for these.You can see https://github.com/google/mediapipe/issues/1453 and  https://github.com/google/mediapipe/issues/1860.
For occlusion hack,I think the most easiest way is to add a mask model which tranform as same as the shoe's transform.Then give a shader to the mask model with ColorMask as 0.And you can realize the occlusion after adjusting the render queue.
Maybe we only can trian a new model to fix these problem.Glad that if anyone have other ideas.

**Comment by nenenkosi** [comment]
@RMiTiG 

> Thanks a lot! I have got the model_matrices and mask_model_matrices both in Android and iOS through your suggestion. The InstantMotionTrackingGraph contains all the code I need.
> As the issue was answered,I am closing it now.

Hi can you please explain in detail how you solved this issue coz am struggling to rendered the shoe in unity using the model_matrices and mask_model_matrices and tell me which files were modified any kind of help will be highly appreciated

**Comment by emreboyraz0** [comment]
> @emreboyraz0
> 
> > how to assign matrix to 3d models
> 
> Sorry that I don't konw beacuse I need the eight bounding point's position,so I output lifted_objects instead of model_matrix to receive the position in screen coordinate.To ouput lifted_objects, we need to define it's packet, reference #187.
> 
> > did you occlude your leg
> 
> MediaPipe doesn't support the occlusion and distinguish between the left and right.We need to use hack for these.You can see [google/mediapipe#1453](https://github.com/google/mediapipe/issues/1453) and [google/mediapipe#1860](https://github.com/google/mediapipe/issues/1860).
> For occlusion hack,I think the most easiest way is to add a mask model which tranform as same as the shoe's transform.Then give a shader to the mask model with ColorMask as 0.And you can realize the occlusion after adjusting the render queue.
> Maybe we only can trian a new model to fix these problem.Glad that if anyone have other ideas.

@RMiTiG thanks for you reply

I tried occulusion hack as you said.

`Shader "AR Proxy"
{
    
    SubShader {
         Tags { "RenderType"="Opaque" "Queue"="Geometry-1"}
         colormask 0
         Pass {
             Stencil {
                 Ref 2
                 Comp Greater
                 Pass Replace
             }
     
             CGPROGRAM
             #pragma vertex vert
             #pragma fragment frag
             struct appdata {
                 float4 vertex : POSITION;
             };
             struct v2f {
                 float4 pos : SV_POSITION;
             };
             v2f vert(appdata v) {
                 v2f o;
                 o.pos = UnityObjectToClipPos(v.vertex);
                 return o;
             }
             half4 frag(v2f i) : SV_Target {
                 return half4(1,0,0,1);
             }
             ENDCG
         }
     }
}`

is my shader. 

![Screenshot_2021-07-27-15-02-40-887_com rgbkod calvanodeneme](https://user-images.githubusercontent.com/39331199/127150988-1c06d5b1-6e6d-4404-ae40-89da5518ebf4.png)

But cylinder look black. Do you know any idea why is black? or did you find any solution to make fake occulusion?

**Comment by nenenkosi** [comment]
@emreboyraz0 I have 

>  cylinder look black. Do you know any idea why is black? or did you find any solution to make fake occulusion?

**Comment by nenenkosi** [comment]
> But cylinder look black. Do you know any idea why is black? or did you find any solution to make fake occulusion?

**Comment by nenenkosi** [comment]
> But cylinder look black. Do you know any idea why is black? or did you find any solution to make fake occlusion?

@emreboyraz0  I have found the solution to that issue of **fake occlusion** and it’s working fine and I don’t mind sharing it with you the only problem I have is I have been asking you to help me with the issue of rendering the shoe in unity to getting the position, scale, and rotation from Matrix4x4. #204 
But you have not replied please help me with that issue as you have solved it.
And I will also be sharing the full code to do the fake occlusion also to help everyone in the community

**Comment by emreboyraz0** [comment]
how did you solve fake occulusion without rendering model in Unity? If you passed model to GlAnimationOverlayCalculator as mask it will not solve my problem.

**Comment by emreboyraz0** [comment]
@RMiTiG okey I found a shader to make fake occulusion. If you need this fake occulusion shader, I can mail you .

**Comment by nenenkosi** [comment]
> how did you solve fake occulusion without rendering model in Unity? If you passed model to GlAnimationOverlayCalculator as mask it will not solve my problem.

@emreboyraz0 sorry for the late reply I am not using GlAnimationOverlayCalculator for occlusion I just used a shader for my IOS device. I can render the model on Unity my problem is making it track my feet using the position, scale, and rotation from Matrix4x4. So that’s the part I need help with

**Comment by gametack** [comment]
> @RMiTiG okey I found a shader to make fake occulusion. If you need this fake occulusion shader, I can mail you .

Can you please explain how you achieved the occlusion? For rendering the shoe in place of the box, did you end up swapping the box model for the shoe model using GlAnimationOverlayCalculator or use the example in the OP first pose?

**Comment by holaworlds** [comment]
Hi @homuler @RMiTiG when you say we can use InstantMotionTrackingGraph scripts, do you mean use the whole class and inherent it or copy the relevant parts into ObjectDetection3d graph ? I am a little confused.

**Comment by RICKYLIKEBIRD** [comment]
hi someone can show any tutorials for how use shoes model render?
I tried to learn the previous issues but I have no idea at all
Sorry I really don't know anything about this
@holaworlds  @nenenkosi  @emreboyraz0  @RMiTiG

**Comment by nenenkosi** [comment]
@RICKYLIKEBIRD I didn’t complete the shoe rendering project so on my side I had some work projects that I had to do and they are taking all of my time so can the other guys please try and help you if I do get the time I will eventually help

**Comment by RICKYLIKEBIRD** [comment]
@nenenkosi thank you repleace
I am trying to understand these codes on my own
I'm waiting for someone else to answer me
Hope there will be good news

**Comment by AbdallahKATAIE** [comment]
@emreboyraz0 could you please share your shader to my mail ? kataieabdallah@hotmail.com
It looks transparent in the scene, but looks black on camera:
![image](https://user-images.githubusercontent.com/49809099/134491500-5878f006-8380-4e3c-8b31-02072b549a62.png)

**Comment by UX3D-mazzini** [comment]
Does anybody of you would like to spend some words on this problem? I can email you  if you want to help me..
