### ISSUE TITLE
Would using async / await pattern for running the graph imrove the performance?

### ISSUE THREAD

**Issue by TheBricktop** [homuler/MediaPipeUnityPlugin#185]
As in the title, im interested in decoupling the framerate of graph alone and the application visuals, that way the kalman (or other filter) interpolation could fake smooth animation of for example hands.
I tried unitask with unity mediapipe tflite plugin, and it worked pretty well .

**Comment by ROBYER1** [comment]
@TheBricktop  did you have any luck with this? We noticed on desktop, if the FPS is 60 fps it runs smooth, if the framerate is less like on mobile Android/IOS the framerate needs to be 30fps tops really and after a minute or so, the pose detection is very out of sync.

**Comment by homuler** [comment]
By #296 , now the sample app can run graphs asynchronously, so I close this issue.

I think I would use UniTask in a real environment too, but I didn't write a sample code that uses UniTask because I didn't want to increase the dependencies of the plugin.
