### ISSUE TITLE
error in unity

### ISSUE THREAD

**Issue by jjjhhjjh** [homuler/MediaPipeUnityPlugin#186]
**System information**
OS Platform: Windows 10
Target: Desktop cpu
Bazel version: 4.1.0
Python version: 3.9.5
GCC/G++ version:
Unity version: Unity 2020.3.8f1 (64-bit)
Android NDK version (if building for Android):
Xcode version (if building for iOS):

**Describe the problem**
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python39//python.exe" mediapipe/examples/desktop/hello_world

The build was successful through that command, but I get the error in Unity, what's the problem?

![K-002](https://user-images.githubusercontent.com/8858397/120127853-7cd1ac00-c1fb-11eb-813a-bf7dc3837477.png)

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Full logs**

**Additional context**

**Comment by homuler** [comment]
> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python39//python.exe" mediapipe/examples/desktop/hello_world

I'm not sure what you mean, but this project is independent of google's mediapipe repository, so what you've done at mediapipe repository does not affect this plugin at all.

Please build required files.
1. Close UnityEditor
2. Checkout all files (`git checkout .`)
3. Run `python build.py build --desktop cpu --include_opencv_libs -v`

See also [this](https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor-1)

**Comment by jjjhhjjh** [comment]
> > bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python39//python.exe" mediapipe/examples/desktop/hello_world
> 
> I'm not sure what you mean, but this project is independent of google's mediapipe repository, so what you've done at mediapipe repository does not affect this plugin at all.
> 
> Please build required files.
> 
> 1. Close UnityEditor
> 2. Checkout all files (`git checkout .`)
> 3. Run `python build.py build --desktop cpu --include_opencv_libs -v`
> 
> See also [this](https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor-1)


I wrote it wrong above.

python build.py build --desktop cpu --include_opencv_libs -v   

The build was successful through the command,
When I open the demo scene in Unity, an error like the picture appears.

**Comment by homuler** [comment]
Will you share the output of the above command?

In addition to that, below steps are also very important, so please follow them if you haven't.
> 1. Close UnityEditor
> 2. Checkout all files (git checkout .)

UnityEditor deletes `.meta` files if the corresponding file does not exist at that time. If `libmediapipe_c.dll.meta` or `opencv_world3410.dll.meta` are deleted, sample app won't work on Windows.

**Comment by jjjhhjjh** [comment]
> 위 명령의 출력을 공유 하시겠습니까?
> 
> 그 외에도 아래 단계도 매우 중요하므로 그렇지 않은 경우 따르십시오.
> 
> > 1. UnityEditor 닫기
> > 2. 모든 파일 체크 아웃 (git checkout.)
> 
> UnityEditor `.meta`는 해당 시점에 해당 파일이 없으면 파일을 삭제 합니다. 경우 `libmediapipe_c.dll.meta`또는 `opencv_world3410.dll.meta`삭제, 샘플 응용 프로그램은 Windows에서 작동하지 않습니다.




This is the output result of the command.


![K-003](https://user-images.githubusercontent.com/8858397/120252434-7573d680-c2bf-11eb-80f6-7b5c45b538f0.png)

**Comment by homuler** [comment]
You're using OpenCV 3.4.14, not the default version 3.4.10.
Please [load it on startup](https://docs.unity3d.com/Manual/PluginInspector.html) or try OpenCV 3.4.10.

**Comment by jjjhhjjh** [comment]
> You're using OpenCV 3.4.14, not the default version 3.4.10.
> Please [load it on startup](https://docs.unity3d.com/Manual/PluginInspector.html) or try OpenCV 3.4.10.

thanks  i will try

**Comment by jjjhhjjh** [comment]
Thank you, I succeeded in running it in Unity Editor. Now all that's left is to extract the apk file, I'll try it thanks
