### ISSUE TITLE
What to do after building android libraries in Ubuntu Docker Container on Windows 10

### ISSUE THREAD

**Issue by philiprkk** [homuler/MediaPipeUnityPlugin#188]
Running ubuntu container through Docker on Windows 10. It looks like I've successfully built the android libraries.
![image](https://user-images.githubusercontent.com/57251565/120300513-4c0d7780-c2cc-11eb-81b1-223011476563.png)

I'm a bit of a Docker noob, so my question is..now what? How do I use whatever it is I have made to create android builds of the sample project in Unity?

Thanks again for all hard work.

(EDIT)

So I open the project in Unity, try to build an android apk, and it tells me it's missing the required ndk. How/where do I find the correct ndk?

**Comment by iamkim17** [comment]
I have the same issue. I don't know what to do next after this, I'm also new to Docker. Do we need to copy the Packages folder in docker container in Unity project folder?

Thank you!

**Comment by homuler** [comment]
When you run `build.py` on Docker with the exact command written in README, required native libraries will be built and installed to your local machine.

If you cannot run sample scene on UnityEditor or built app does not work, this is another problem, so please share the error logs.
There are different reasons why errors occur, and without logs, we cannot solve the problem.
