### ISSUE TITLE
Build failed - Desktop cpu - Windows 10

### ISSUE THREAD

**Issue by PawelklosPL** [homuler/MediaPipeUnityPlugin#191]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10 pro (10.0.19042 Build 19042)
- Target (e.g. desktop cpu, android arm64): Desktop cpu
- Bazel version: 4.0.0
- Python version: 3.9.5
- GCC/G++ version: GCC 10.2.0
- Unity version: 2020.3.6f1

**Describe the problem**

Error occurs while building.

**Steps to reproduce the issue**

https://github.com/homuler/MediaPipeUnityPlugin#windows
I did all the points from the first to the last. At the last step, I got an error. 

**Full logs**

C:\UnityAddon>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/msys64/home/pawel/_bazel_pawel/qtosowyg/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: Skipping '/mediapipe_api:mediapipe_proto_srcs': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
WARNING: Target pattern parsing failed.
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
INFO: Elapsed time: 35.720s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/c/UnityAddon/build.py", line 392, in <module>
    Argument().command().run()
  File "/c/UnityAddon/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/c/UnityAddon/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Additional context**

I think the problem is with the bazel version. Should i check it on an older version of bazel?

**Comment by TheBricktop** [comment]
Are you using docker image?

**Comment by PawelklosPL** [comment]
> Are you using docker image?

no, I am using the normal windows installation (Desktop / UnityEditor).
Should I try docker image?

**Comment by TheBricktop** [comment]
I was succesfull with docker image on win10 and android, so I can only recommend this way. Its pretty straightforward.

**Comment by forger-rev** [comment]
I got the same error code...
Is it possible that I am using AMD Radeo Graphics Card so it does not work ?

**Comment by homuler** [comment]
It occurs because `cmd.exe` treat `/` as a command option's prefix and the argument `//mediapipe_api:...` is interpreted as `/mediapipe_api:...`, that is invalid syntax for bazel.
https://stackoverflow.com/questions/34647591/passing-windows-slash-based-parameters-to-a-program-from-bash-script

Maybe `/C` option does the trick but I'm not sure.
https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/docker/windows/x86_64/Dockerfile#L9

**Comment by homuler** [comment]
@PawelklosPL I can't reproduce the error, so if you are still interested in this issue, I would appreciate it if you could check if it is fixed.

**Comment by keidakat** [comment]
I'm having the same issue with bazel release 4.2.1 and Python 3.9.6.

Here is the build command I'm running:
python build.py build --desktop cpu --include_opencv_libs -v

and here is what it results in:
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
ERROR: Skipping '/mediapipe_api:mediapipe_proto_srcs': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
WARNING: Target pattern parsing failed.
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
INFO: Elapsed time: 0.074s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/c/Users/keida/git/MediaPipe/mediapipe/MediaPipeUnityPlugin-0.7.0/MediaPipeUnityPlugin/build.py", line 424, in <module>
    Argument().command().run()
  File "/c/Users/keida/git/MediaPipe/mediapipe/MediaPipeUnityPlugin-0.7.0/MediaPipeUnityPlugin/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/c/Users/keida/git/MediaPipe/mediapipe/MediaPipeUnityPlugin-0.7.0/MediaPipeUnityPlugin/build.py", line 50, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
@keidakat Does it still occur with the latest commit https://github.com/homuler/MediaPipeUnityPlugin/commit/702434d58e78f28702e952f9f35ee6eaaa2d4afb ?

**Comment by keidakat** [comment]
I tried installing the latest python (3.10) using the windows installer and double-checked that the PATH pointed to the right place but the error persists still stating mentioning python 3.9 so it looks like I've somehow still got this pointing to the wrong place despite the bin path and environment variable path both pointing to the correct one. I've run out of time to mess with it tonight but will update later if I can find out what I've done wrong.

**Comment by homuler** [comment]
Please share your logs and `PATH`.

If the path in the log is like this,
> File "/usr/lib/python3.9/subprocess.py", line 528, in run

then MSYS python is used, so you need to change the order in `PATH`.

**Comment by keidakat** [comment]
It indeed has that path in the log, but I'm not entirely sure how. I've changed the path environment variable and the python bin path variable to 3.10 and I can't find where it's getting this 3.9 from. 
 
![image](https://user-images.githubusercontent.com/27837516/137244569-93a3508f-77ea-4268-8f5b-bc24e6e82584.png)

log starting from the set python_bin_path:

> C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin>set PYTHON_BIN_PATH=C:\Users\keida\AppData\Local\Programs\Python\Python310\python.exe
> 
> C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin>python build.py build --desktop cpu --include_opencv_libs -v
> INFO (build.py): Building protobuf sources...
> DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
> ERROR: Skipping '/mediapipe_api:mediapipe_proto_srcs': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
> WARNING: Target pattern parsing failed.
> ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
> INFO: Elapsed time: 0.089s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> Traceback (most recent call last):
>   File "/c/Users/keida/git/MediaPipe/mediapipe/MediaPipeUnityPlugin-0.7.0/MediaPipeUnityPlugin/build.py", line 444, in <module>
>     Argument().command().run()
>   File "/c/Users/keida/git/MediaPipe/mediapipe/MediaPipeUnityPlugin-0.7.0/MediaPipeUnityPlugin/build.py", line 112, in run
>     self._run_command(self._build_proto_srcs_commands())
>   File "/c/Users/keida/git/MediaPipe/mediapipe/MediaPipeUnityPlugin-0.7.0/MediaPipeUnityPlugin/build.py", line 52, in _run_command
>     return subprocess.run(' '.join(command_list), check=True, shell=shell)
>   File "/usr/lib/python3.9/subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'bazel build -c opt //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

Is there a third place I may be forgetting or should I just try completely uninstalling 3.9 and see if that solves it? Though if the issue is that it's looking for something from 3.9 and not finding it I'm not sure that would solve it.

**Comment by homuler** [comment]
How about running `C:\Users\keida\AppData\Local\Programs\Python\Python310\Scripts\python.exe build.py build --desktop cpu --opencv cmake -vv`?

I think your `PATH` is wrong but I'm not sure since it is truncated in the above image.

**Comment by keidakat** [comment]
> 'C:\Users\keida\AppData\Local\Programs\Python\Python310\Scripts\python.exe' is not recognized as an internal or external command,
> operable program or batch file.

is what The command you suggested results in.
Here are the top two (and the only python listed) from my Path Variable

![image](https://user-images.githubusercontent.com/27837516/137255069-ed4c6028-5c33-4a5c-ba86-a581fda9db06.png)

**Comment by homuler** [comment]
Sorry, maybe `C:\Users\keida\AppData\Local\Programs\Python\Python310\python.exe build.py build --desktop cpu --opencv cmake -vv`.
I mean, try running `python.exe` with the absolute path.

**Comment by homuler** [comment]
It looks like you cannot use Python 3.10 currently.
https://github.com/tensorflow/tensorflow/pull/51782

Will you try with Python 3.9 again, please?

**Comment by keidakat** [comment]
That indeed seemed to fix the numpy problem, but I'm not sure whether the whole build has succeeded or not. There are no errors and it states the build succeeded, but then it also has a traceback on "nuget install -o .nuget -Source https://api.nuget.org/v3/index.json"

> C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin>C:\Users\keida\AppData\Local\Programs\Python\Python39\Scripts\pip.exe install numpy --user
> Collecting numpy
>   Using cached numpy-1.21.2-cp39-cp39-win_amd64.whl (14.0 MB)
> Installing collected packages: numpy
>   WARNING: The script f2py.exe is installed in 'C:\Users\keida\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed numpy-1.21.2
> WARNING: You are using pip version 21.2.3; however, version 21.3 is available.
> You should consider upgrading via the 'C:\Users\keida\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
> 
> C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin>C:\Users\keida\AppData\Local\Programs\Python\Python39\python.exe build.py build --desktop cpu --opencv cmake -vv
> INFO (build.py): Building protobuf sources...
> DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//keida//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'com_google_absl' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'com_google_protobuf' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'com_google_googletest' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'rules_python' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'bazel_skylib' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/org_tensorflow/third_party/repo.bzl:108:14:
> Warning: skipping import of repository 'pybind11' because it already exists.
> DEBUG: C:/_bzl/4jbh3wdk/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
> INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (18 packages loaded, 661 targets configured).
> INFO: Found 1 target...
> Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
>   bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
> INFO: Elapsed time: 39.104s, Critical Path: 31.65s
> INFO: 199 processes: 11 internal, 188 local.
> INFO: Build completed successfully, 199 total actions
> DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
> INFO (build.py): Built protobuf sources
> INFO (build.py): Downloading dlls...
> DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
> 'nuget' is not recognized as an internal or external command,
> operable program or batch file.
> Traceback (most recent call last):
>   File "C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin\build.py", line 444, in <module>
>     Argument().command().run()
>   File "C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin\build.py", line 119, in run
>     self._run_command(self._build_proto_dlls_commands())
>   File "C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin\build.py", line 52, in _run_command
>     return subprocess.run(' '.join(command_list), check=True, shell=shell)
>   File "C:\Users\keida\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'nuget install -o .nuget -Source https://api.nuget.org/v3/index.json' returned non-zero exit status 1.

**Comment by homuler** [comment]
Please read the installation guide.
https://github.com/homuler/MediapipeUnityPlugin#desktopunityeditor-1

**Comment by keidakat** [comment]
Yep, realized after I sent that that nuget was in the wrong folder. 

Looks like it was able to run through most of it then got hung up on some weird path issue given that:

> can't open file '/c/_bzl/4jbh3wdk/execroot/mediapipe_api/C:\_bzl\4jbh3wdk\execroot\mediapipe_api\bazel-out\x64_windows-opt-ST-bc707ddf08b7\bin\external\org_tensorflow\tensorflow\tools\git\gen_git_source.zip'

has the drive in the middle of the path... I've included the full error below and will keep trying to track down where it is pulling this path from.

> ERROR: C:/_bzl/4jbh3wdk/external/org_tensorflow/tensorflow/core/util/BUILD:376:24: Action external/org_tensorflow/tensorflow/core/util/version_info.cc failed: (Exit 2): bash.exe failed: error executing command
>   cd C:/_bzl/4jbh3wdk/execroot/mediapipe_api
>   SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\OpenNI\Bin;C:\Program Files\OpenNI\Bin64;C:\Program Files (x86)\Touch Portal\plugins\adb\platform-tools;C:\msys64\usr\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\keida\_bazel_keida\install\ecbdcc700f261b3edf6ad41ebfc6c7bb\embedded_tools\third_party\grpc\bazel;C:\Users\keida\_bazel_keida\install\ecbdcc700f261b3edf6ad41ebfc6c7bb\embedded_tools\third_party\grpc;C:\Users\keida\_bazel_keida\bazel;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\keida\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\keida\AppData\Local\Programs\Python\Python310\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\OpenNI\Bin;C:\Program Files\OpenNI\Bin64;C:\Program Files (x86)\Touch Portal\plugins\adb\platform-tools;C:\msys64\usr\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\keida\_bazel_keida\install\ecbdcc700f261b3edf6ad41ebfc6c7bb\embedded_tools\third_party\grpc\bazel;C:\Users\keida\_bazel_keida\install\ecbdcc700f261b3edf6ad41ebfc6c7bb\embedded_tools\third_party\grpc;C:\Users\keida\_bazel_keida\bazel;C:\Users\keida\AppData\Loc;C:\Users\keida\.dotnet\tools;C:\Users\keida\git\MediaPipe\mediapipe\nuget;
>     SET PROCESSOR_ARCHITECTURE=AMD64
>     SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
>     SET PROCESSOR_LEVEL=6
>     SET PROCESSOR_REVISION=a505
>     SET PYTHON_BIN_PATH=C://Users//keida//AppData//Local//Programs//Python//Python39//python.exe
>     SET ProgramData=C:\ProgramData
>     SET RUNFILES_MANIFEST_ONLY=1
>   C:/msys64/usr/bin/bash.exe -c bazel-out/x64_windows-opt-ST-bc707ddf08b7/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source.exe --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref bazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/core/util/version_info.cc
> Execution platform: @local_execution_config_platform//:platform
> /usr/bin/python: can't open file '/c/_bzl/4jbh3wdk/execroot/mediapipe_api/C:\_bzl\4jbh3wdk\execroot\mediapipe_api\bazel-out\x64_windows-opt-ST-bc707ddf08b7\bin\external\org_tensorflow\tensorflow\tools\git\gen_git_source.zip': [Errno 2] No such file or directory
> Target //mediapipe_api:mediapipe_desktop failed to build
> INFO: Elapsed time: 108.651s, Critical Path: 75.95s
> INFO: 2017 processes: 641 internal, 1376 local.
> FAILED: Build did NOT complete successfully
> Traceback (most recent call last):
>   File "C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin\build.py", line 444, in <module>
>     Argument().command().run()
>   File "C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin\build.py", line 141, in run
>     self._run_command(self._build_desktop_commands())
>   File "C:\Users\keida\git\MediaPipe\mediapipe\MediaPipeUnityPlugin-0.7.0\MediaPipeUnityPlugin\build.py", line 52, in _run_command
>     return subprocess.run(' '.join(command_list), check=True, shell=shell)
>   File "C:\Users\keida\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//keida//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/issues/191#issuecomment-942909609
Maybe you've edited both of System Variable `Path` and User Variable `Path` , and System Variable `Path` begins with `C:\msys64\user\bin;`.
