### ISSUE TITLE
How to get 3d landmarks form handtracking graph?

### ISSUE THREAD

**Issue by TheBricktop** [homuler/MediaPipeUnityPlugin#192]
I think that there should be some modifications done to the graph itself but since its kinda hard to read for a newcomer I cant quite figure where one could change the output stream from 2d to 3d features.

**Comment by ROBYER1** [comment]
Did you have any luck with this? I am trying to use the FetchNextPoseWorldLandmarks() call but it returns a LandmarkList which isn't compatible with the required NormalizedLandmarkList that HolisticValue uses

**Comment by TheBricktop** [comment]
Im in the process of compiling the next release to check the new pipeline with world landmarks that @homuler made but im not sure how to use it yet.

**Comment by ROBYER1** [comment]
You may run into this issue we had where the latest release Holistic tracking has a lot of latency after 30-60 seconds on windows or android at least - https://github.com/homuler/MediaPipeUnityPlugin/issues/219

See a example video from that post [here](https://photos.google.com/share/AF1QipOX7Nd_pdFU7AbA6t8BYIwcvHe5IHAO39cP6L2fdMCeb4izXjtXCRGpHwiFpJ2aDQ?key=eVlfSVFXV3JNWVpaWG1tcjFtdHFBWEhDcTN5TFlB), we had to roll back to Mediapipe 0.8.4

**Comment by midopooler** [comment]
Hi @TheBricktop , Did you tried out my repo?
I tried calling Hand landmarks from within the Holistic Model. 
Here's how [https://github.com/midopooler/CharacterAnimationUsingMediapipe/blob/holistic-pose/Assets/Mediapipe/Samples/Graphs/Holistic/Scripts/HolisticGraph.cs#L109](url)

Though I have used Right Hand only as of now, You can use the same for the Left Hand as well.

**Comment by johnnymakk** [comment]
Hi @midopooler 
Is your repo still available?
Thanks!

**Comment by homuler** [comment]
Close this because sample code are added.
Please reopen it if you have any questions.
