### ISSUE TITLE
Error when trying to build the docker image

### ISSUE THREAD

**Issue by Emad-Eldeen** [homuler/MediaPipeUnityPlugin#194]
**System information**
- OS Platform and Distribution: Docker on Windows 10 (Linux containers)

**Describe the problem**
Error when trying to build the docker image

**Steps to reproduce the issue**
in repo folder, run: docker build -t mediapipe_unity:latest . -f docker/linux/x86_64/Dockerfile

**Full logs**

 [internal] load build definition from Dockerfile                                                                                             0.1s
 => => transferring dockerfile: 3.74kB                                                                                                           0.1s
 => [internal] load .dockerignore                                                                                                                0.1s2
 => => transferring context: 2B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/archlinux:latest                                                                              0.0s
 => [base  1/10] FROM docker.io/library/archlinux:latest                                                                                         0.0s
 => [internal] load build context                                                                                                                0.1s
 => => transferring context: 6.79kB                                                                                                              0.1s
 => CACHED [base  2/10] RUN if [[ "${RANKMIRROS}" ]]; then         pacman -Syu pacman-contrib --needed --noconfirm &&         {             rea  0.0s
 => CACHED [base  3/10] RUN pacman -Syuu archlinux-keyring sudo --needed --noconfirm                                                             0.0s
 => CACHED [base  4/10] RUN echo -e "%wheel ALL=(ALL) NOPASSWD: ALL\n" > /etc/sudoers.d/01_wheel                                                 0.0s
 => CACHED [base  5/10] RUN useradd -u 1000 -m mediapipe && usermod -aG wheel mediapipe                                                          0.0s
 => CACHED [base  6/10] WORKDIR /home/mediapipe                                                                                                  0.0s
 => CACHED [base  7/10] RUN sudo pacman -Sy base-devel git glibc jdk11-openjdk unzip zip --needed --noconfirm                                    0.0s
 => CACHED [base  8/10] RUN git clone https://aur.archlinux.org/yay.git                                                                          0.0s
 => CACHED [base  9/10] RUN cd yay && makepkg -si --noconfirm                                                                                    0.0s
 => CACHED [base 10/10] RUN rm -rf yay                                                                                                           0.0s
 => [android 1/6] WORKDIR /tmp                                                                                                                   0.0s
 => [android 2/6] RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -o commandlinetools.zip &&     13.6s
 => [android 3/6] RUN sudo unzip commandlinetools.zip -d /opt/android                                                                            0.9s
 => [android 4/6] RUN yes | /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --licenses                                         2.1s
 => [android 5/6] RUN /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --install     "platforms;android-30"     "platform-to  219.3s
 => [android 6/6] RUN rm commandlinetools.zip                                                                                                    0.4s
 => [builder 1/7] COPY --from=android /opt/android /opt/android                                                                                 23.7s
 => [builder 2/7] RUN mkdir ffmpeg                                                                                                               0.3s
 => [builder 3/7] ADD docker/linux/x86_64/ffmpeg/ ffmpeg/                                                                                        0.1s
 => ERROR [builder 4/7] RUN cd ffmpeg &&     yay -Sy &&     makepkg -si --needed --noconfirm &&     cd .. &&     rm -rf ffmpeg                  37.7s
------
 > [builder 4/7] RUN cd ffmpeg &&     yay -Sy &&     makepkg -si --needed --noconfirm &&     cd .. &&     rm -rf ffmpeg:
#24 0.426 :: Synchronizing package databases...
#24 37.55 error: failed retrieving file 'core.db' from mirror.pkgbuild.com : Resolving timed out after 10000 milliseconds
#24 37.55  core downloading...
#24 37.55  extra downloading...
#24 37.55  community downloading...
#24 37.55 error: failed retrieving file 'core.db' from mirror.rackspace.com : Resolving timed out after 10000 milliseconds
#24 37.62 ==> ERROR: PKGBUILD contains CRLF characters and cannot be sourced.
------
executor failed running [/bin/sh -c cd ffmpeg &&     yay -Sy &&     makepkg -si --needed --noconfirm &&     cd .. &&     rm -rf ffmpeg]: exit code: 12

D:\MediaPipeUnityPlugin>

**Comment by homuler** [comment]
Same as #169
See also https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843014178

**Comment by Emad-Eldeen** [comment]
Thanks!
