### ISSUE TITLE
Issue with ios build

### ISSUE THREAD

**Issue by Emad-Eldeen** [homuler/MediaPipeUnityPlugin#199]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Linux Docker
- Target (e.g. desktop cpu, android arm64): ios arm64

**Describe the problem**
I am trying building for ios but with an older commit from your repo (de132bd). and getting error in the build process.
It would be great if you get provide me with a hint how to solve this issue.

**Steps to reproduce the issue**
```sh
git clone https://github.com/google/mediapipe.git
cd mediapipe
git checkout 0.8.2
docker build --tag=mediapipe .
docker run -it --name mediapipe mediapipe:latest

in the docker container:
// dotnet installation 
cd /
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt-get update
apt-get install -y aspnetcore-runtime-2.1 dotnet-sdk-3.1
git clone https://github.com/homuler/MediaPipeUnityPlugin.git
cd MediaPipeUnityPlugin
git checkout de132bd
sed -i -e 's/lib\/libopencv/lib\/x86_64-llinux-gnu\/libopencv/g' C/third_party/opencv_linux.BUILD
make ios_arm64
```

**Full logs**
make ios_arm64
mkdir -p .build
curl -L https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz -o .build/protobuf-3.13.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0    551      0 --:--:-- --:--:-- --:--:--   551
100 5154k  100 5154k    0     0  3429k      0  0:00:01  0:00:01 --:--:-- 6203k
tar xf .build/protobuf-3.13.0.tar.gz -C .build
dotnet restore .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln && \
dotnet build -c Release .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
  Determining projects to restore...
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/Google.Protobuf.csproj (in 284 ms).
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj (in 284 ms).
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/AddressBook.csproj (in 284 ms).
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/Google.Protobuf.JsonDump.csproj (in 284 ms).
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj (in 302 ms).
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/Google.Protobuf.Conformance.csproj (in 309 ms).
  Restored /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj (in 311 ms).
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Google.Protobuf -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll
  Google.Protobuf -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard1.1/Google.Protobuf.dll
  Google.Protobuf -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard2.0/Google.Protobuf.dll
  Google.Protobuf.JsonDump -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/bin/Release/netcoreapp2.1/Google.Protobuf.JsonDump.dll
  AddressBook -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/bin/Release/netcoreapp2.1/AddressBook.dll
  Google.Protobuf.Benchmarks -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/bin/Release/netcoreapp3.1/Google.Protobuf.Benchmarks.dll
  Google.Protobuf.Test.TestProtos -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard1.1/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test.TestProtos -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/net45/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test.TestProtos -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard2.0/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/net451/Google.Protobuf.Test.dll
  Google.Protobuf.Test -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll
  Google.Protobuf.Conformance -> /MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/bin/Release/netcoreapp2.1/Google.Protobuf.Conformance.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.28
cd C && bazel build -c opt --config=ios_arm64 --copt=-fembed-bitcode --apple_bitcode=embedded mediapipe_api/objc:MediaPipeUnity mediapipe_api:mediapipe_assets mediapipe_api:mediapipe_proto_srcs
DEBUG: /root/.cache/bazel/_bazel_root/de3c76406078cb2218dae867db59221a/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
INFO: Build option --cpu has changed, discarding analysis cache.
ERROR: /root/.cache/bazel/_bazel_root/de3c76406078cb2218dae867db59221a/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'
ERROR: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.249s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 193 targets configured)
    Fetching @ios_opencv; fetching
Makefile:55: recipe for target 'ios_arm64' failed
make: *** [ios_arm64] Error 1
#

**Comment by homuler** [comment]
You cannot build native libraries for iOS on Linux containers, since Xcode is not installed.

**Comment by Emad-Eldeen** [comment]
@homuler Thank you for your reply.
I took the time to switch to mac OS. 
I installed mediapipe and ran the HelloWorld successfully. 
Then I installed xcode and all the requirements for your plugin, and then I ran 'python build.py build  --ios arm64 -v' and got exactly the same error:
'ERROR: /private/var/tmp/_bazel_admin/7f97831b1f9043817a24b33810ab71d7/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'
![image](https://user-images.githubusercontent.com/46440916/123462541-bfb05500-d5ea-11eb-9625-4bfd9fe30979.png)

**Comment by Emad-Eldeen** [comment]
@homuler Thank you for your reply.
I took the time to switch to mac OS. 
I installed mediapipe and ran the HelloWorld successfully. 
Then I installed xcode and all the requirements for your plugin, and then I ran 'python build.py build  --ios arm64 -v' and got exactly the same error:
'ERROR: /private/var/tmp/_bazel_admin/7f97831b1f9043817a24b33810ab71d7/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'
![image](https://user-images.githubusercontent.com/46440916/123462541-bfb05500-d5ea-11eb-9625-4bfd9fe30979.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): macOS v11.4
- Target Platform: IOS
- MediaPipeUnityPlugin version or commit id: HEAD
- Bazel version: 3.7.2
- GCC/G++ version:
- Xcode version (if the target platform is iOS): 12.5.1

**Comment by MRLesile** [comment]
> @homuler感谢您的回复。
> 我花时间切换到 mac OS。
> 我安装了 mediapipe 并成功运行了 HelloWorld。
> 然后我安装了 xcode 和插件的所有要求，然后我运行了“python build.py build --ios arm64 -v”并得到了完全相同的错误：
> “错误：/private/var/tmp/_bazel_admin/7f97831b1f904381​​7a24b33810ab71d7/ external/local_config_cc/BUILD:48:19: 在 cc_toolchain_suite 规则中@local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' 不包含用于 cpu 'ios_arm64' 的工具链
> ![图片](https://user-images.githubusercontent.com/46440916/123462541-bfb05500-d5ea-11eb-9625-4bfd9fe30979.png)
> 
> **系统信息**
> 
> * 操作系统平台和发行版（例如 Linux Ubuntu 20.04）：macOS v11.4
> * 目标平台：IOS
> * MediaPipeUnityPlugin 版本或提交 ID：HEAD
> * 巴泽尔版本：3.7.2
> * GCC/G++ 版本：
> * Xcode 版本（如果目标平台是 iOS）：12.5.1

解决了吗

**Comment by MRLesile** [comment]
> > @homuler感谢您的回复。
> > 我花时间切换到 mac OS。
> > 我安装了 mediapipe 并成功运行了 HelloWorld。
> > 然后我安装了 xcode 和插件的所有要求，然后我运行了“python build.py build --ios arm64 -v”并得到了完全相同的错误：
> > “错误：/private/var/tmp/_bazel_admin/7f97831b1f904381​​ 7a24b33810ab71d7/external/local_config_cc/BUILD:48:19: 在 cc_toolchain_suite_cc: cc_toolchain_suite config_cc:tool_chainsuite 规则中@local_chain '@local_config_cc//:toolchain' 不包含用于 cpu 'ios_arm64' 的工具链
> > ![图片](https://user-images.githubusercontent.com/46440916/123462541-bfb05500-d5ea-11eb-9625-4bfd9fe30979.png)
> > **系统信息**
> > 
> > * 操作系统平台和发行版（例如Linux Ubuntu 20.04）：macOS v11.4
> > * 目标平台：IOS
> > * MediaPipeUnityPlugin 版本或提交 ID：HEAD
> > * 巴泽尔版本：3.7.2
> > * GCC/G++ 版本：
> > * Xcode 版本（如果目标平台是 iOS）：12.5.1
> 
> 解决

请问你解决了吗

**Comment by Longgood-Anny** [comment]
I have the same problem. Have you solved the problem?

<img width="760" alt="截圖 2021-11-10 下午4 22 55" src="https://user-images.githubusercontent.com/93504662/141076774-38d2e549-e313-4343-a904-7e61b0a0e083.png">

**Comment by homuler** [comment]
See #350
