### ISSUE TITLE
Build Android on MacOS failed: google_toolbox_for_mac, objc_library rule, Expected action_config for 'objc-fully-link' to be configured

### ISSUE THREAD

**Issue by zhchaoxing** [homuler/MediaPipeUnityPlugin#200]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): macOS 11.4 Big Sur
- Target (e.g. desktop cpu, android arm64): android arm64
- Bazel version: export USE_BAZEL_VERSION=3.7.2
- Python version: 3.9.5
- GCC/G++ version:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
- Unity version: N/A
- Android NDK version (if building for Android): android-ndk-r18b
Installed with https://raw.githubusercontent.com/google/mediapipe/master/setup_android_sdk_and_ndk.sh

#step1:
./setup_android_sdk_and_ndk.sh

#step2:
vi ~/.bashrc
export ANDROID_HOME=$PATH:$HOME/Android/Sdk
export ANDROID_NDK_HOME=$PATH:$HOME/Android/Sdk/ndk-bundle/android-ndk-r18b

- Xcode version (if building for iOS):

**Describe the problem**
Run into error regarding to "google_toolbox_for_mac/BUILD.bazel:21:13: in objc_library rule @google_toolbox_for_mac//:GTM_Defines: Expected action_config for 'objc-fully-link' to be configured" while building in MacOS.

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

sudo python build.py build --android arm64 -v

**Full logs**

......

INFO (build.py): Building native libraries for Android...
DEBUG (build.py): Running `bazel build -c opt --config=android_arm64 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android`
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build options --cpu, --crosstool_top, --define, and 2 more have changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/com_google_mediapipe/mediapipe/gpu/BUILD:249:13: in objc_library rule @com_google_mediapipe//mediapipe/gpu:pixel_buffer_pool_util: Expected action_config for 'objc++-compile' to be configured
INFO: Repository android_opencv instantiated at:
  /Users/hal/Documents/GitHub/MediaPipeUnityPlugin/WORKSPACE:266:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_root/6ed42a7e59fbe6f00feb7169613a9105/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: Analysis of target '@com_google_mediapipe//mediapipe/gpu:pixel_buffer_pool_util' failed
INFO: Elapsed time: 5.061s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 17116 targets configured)
Traceback (most recent call last):
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 153, in run
    self._run_command(self._build_android_commands())
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.

**Additional context**

**Comment by homuler** [comment]
Will you run commands without `sudo`?

```sh
python build.py build --android arm64 -vv
```

**Comment by zhchaoxing** [comment]
> Will you run commands without `sudo`?
> 
> ```shell
> python build.py build --android arm64 -vv
> ```

I had permission error so I used sudo. Desktop build is successful with sudo.

`
python build.py build --android arm64 -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_hal/6ed42a7e59fbe6f00feb7169613a9105/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 0.301s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Failed to read NuGet.Config due to unauthorized access. Path: '/Users/hal/.config/NuGet/NuGet.Config'.
  Access to the path '/Users/hal/.config/NuGet' is denied.
  Permission denied
Traceback (most recent call last):
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 116, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nuget', 'install', '-o', '.nuget', '-Source', 'https://api.nuget.org/v3/index.json']' returned non-zero exit status 1.
`

**Comment by homuler** [comment]
Check the permission of `/Users/hal/.config/NuGet/NuGet.Config`.

**Comment by zhchaoxing** [comment]
> Check the permission of `/Users/hal/.config/NuGet/NuGet.Config`.

Thank you very much for your help! 
I tried fixing permission issues one after another and didn't see a clear end, and I saw posts online saying mac upgraded from previous OS versions may suffer from permission and other issues, so I reinstalled my mac and had a clean slate. 
I can build desktop and iOS successfully now, but I still can't get through with the android build process. 
With the following errors, should I open a new issue?

`
ERROR: /private/var/tmp/_bazel_hal/4d294ce02a5757430c63e953e834c5f3/external/bazel_tools/tools/jdk/BUILD:350:14: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1): java failed: error executing command 
  (cd /private/var/tmp/_bazel_hal/4d294ce02a5757430c63e953e834c5f3/sandbox/darwin-sandbox/8541/execroot/mediapipe_api && \
  exec env - \
  external/remotejdk11_macos/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/arm64-v8a-opt/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/remotejdk11_macos/lib/tools.jar DumpPlatformClassPath bazel-out/arm64-v8a-opt/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/local_jdk)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox java failed: error executing command 
  (cd /private/var/tmp/_bazel_hal/4d294ce02a5757430c63e953e834c5f3/sandbox/darwin-sandbox/8541/execroot/mediapipe_api && \
  exec env - \
  external/remotejdk11_macos/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/arm64-v8a-opt/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/remotejdk11_macos/lib/tools.jar DumpPlatformClassPath bazel-out/arm64-v8a-opt/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/local_jdk)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1853)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 7.177s, Critical Path: 2.61s
INFO: 160 processes: 127 internal, 29 darwin-sandbox, 4 worker.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 153, in run
    self._run_command(self._build_android_commands())
  File "/Users/hal/Documents/GitHub/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--verbose_failures', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.
`
[output.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6642650/output.txt)
