### ISSUE TITLE
Unable to change webcamtexture's size

### ISSUE THREAD

**Issue by aidenpearce001** [homuler/MediaPipeUnityPlugin#201]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10 (WSL2)
Target (e.g. desktop cpu, android arm64): android arm64
Bazel version: 4.0.0
Python version: 3.9
GCC/G++ version: 11.1.0
Unity version:
Android NDK version (if building for Android): 4.9
Xcode version (if building for iOS):

![image](https://user-images.githubusercontent.com/56188293/122361727-b8050680-cf81-11eb-8f7b-b8e77e31e5b4.png)

Can I pass a texture of any size or should it be constant 640*480?

Thank you.

**Comment by philiprkk** [comment]
Generally for computer webcams it should have a 16:9 aspect ratio. For all phone cameras it's usually 640x480. 1920x1080 instead of 1280x720 for instance might cause more lag than what it's worth.

**Comment by aidenpearce001** [comment]
> Generally for computer webcams it should have a 16:9 aspect ratio. For all phone cameras it's usually 640x480. 1920x1080 instead of 1280x720 for instance might cause more lag than what it's worth.

tks !
