### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by GORILA1221** [homuler/MediaPipeUnityPlugin#202]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: bazel 5.0.0-pre.20210604.6
- Python version: Python 3.9.5
- GCC/G++ version: 
- Unity version: Unity 2020.3.8f1 (64-bit)
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

Build error

ERROR: Traceback (most recent call last):
        File "C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
                ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: error loading package '@com_google_mediapipe//mediapipe/gpu': at C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

C:\Windows\system32>cd C:\Unity_Project\MediaPipeUnityPlugin-master_(1)

C:\Unity_Project\MediaPipeUnityPlugin-master_(1)>set PYTHON_BIN_PATH=C:\Users\Professional\AppData\Local\Programs\Python\Python39\python.exe

C:\Unity_Project\MediaPipeUnityPlugin-master_(1)>python build.py build --desktop cpu --include_opencv_libs -v

**Full logs**

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//Professional//AppData//Local//Programs//Python//Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "4bb45afea6a738f069b113092b2ed6ccde8d0c789bb67d30033984a6a5dd74e5"
DEBUG: Repository rules_cc instantiated at:
  C:/unity_project/mediapipeunityplugin-master_(1)/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/gyqckxaa/external/bazel_tools/tools/build_defs/repo/http.bzl:339:31: in <toplevel>
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 831 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 1.801s, Critical Path: 0.07s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  C:\Users\Professional\.nuget\packages\
  https://api.nuget.org/v3/index.json

Все пакеты, перечисленные в C:\Unity_Project\MediaPipeUnityPlugin-master_(1)\packages.config, уже установлены.
DEBUG (build.py): Copying '.nuget\Google.Protobuf.3.15.6\lib\netstandard2.0\Google.Protobuf.dll' to 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll' to 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll' to 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Copying '.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll' to 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//Professional//AppData//Local//Programs//Python//Python39//python.exe //mediapipe_api:mediapipe_assets`
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "4bb45afea6a738f069b113092b2ed6ccde8d0c789bb67d30033984a6a5dd74e5"
DEBUG: Repository rules_cc instantiated at:
  C:/unity_project/mediapipeunityplugin-master_(1)/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/gyqckxaa/external/bazel_tools/tools/build_defs/repo/http.bzl:339:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 47 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 1.228s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'build\Resources'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//Professional//AppData//Local//Programs//Python//Python39//python.exe --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop`
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/gyqckxaa/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build option --define has changed, discarding analysis cache.
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "4bb45afea6a738f069b113092b2ed6ccde8d0c789bb67d30033984a6a5dd74e5"
DEBUG: Repository rules_cc instantiated at:
  C:/unity_project/mediapipeunityplugin-master_(1)/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/gyqckxaa/external/bazel_tools/tools/build_defs/repo/http.bzl:339:31: in <toplevel>
ERROR: Traceback (most recent call last):
        File "C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
                ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: error loading package '@com_google_mediapipe//mediapipe/gpu': at C:/_bzl/gyqckxaa/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
INFO: Elapsed time: 1.053s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 305 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/gpu
Traceback (most recent call last):
  File "C:\Unity_Project\MediaPipeUnityPlugin-master_(1)\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Unity_Project\MediaPipeUnityPlugin-master_(1)\build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "C:\Unity_Project\MediaPipeUnityPlugin-master_(1)\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//Professional//AppData//Local//Programs//Python//Python39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

C:\Unity_Project\MediaPipeUnityPlugin-master_(1)>

**Additional context**

**Comment by httc805155** [comment]
Same here, don't know how to fixe it

**Comment by homuler** [comment]
Please use bazel 4.0.0.

**Comment by GORILA1221** [comment]
Installed Basel 4.0.0, there was a long installation, an error appeared
Uninstalled Pyton and installed 3.9.0
Now an error like this:

FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Unity_Project\MediaPipeUnityPlugin-master(1)\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Unity_Project\MediaPipeUnityPlugin-master(1)\build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "C:\Unity_Project\MediaPipeUnityPlugin-master(1)\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//Professional//AppData//Local//Programs//Python//Python39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

C:\Unity_Project\MediaPipeUnityPlugin-master(1)>

**Comment by homuler** [comment]
Please run `python build.py build --desktop cpu --include_opencv_libs -vv` (note that `-vv` is appended) and attach the **full** log.

**Comment by GORILA1221** [comment]
[log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6839773/log.txt)

**Comment by homuler** [comment]
```txt
ERROR: C:/_bzl/qqwea4ny/external/com_google_mediapipe/mediapipe/graphs/object_detection_3d/subgraphs/BUILD:24:26: Executing genrule @com_google_mediapipe//mediapipe/graphs/object_detection_3d/subgraphs:renderer_cpu_inc failed: (Exit -1073741502): bash.exe failed: error executing command
  cd C:/_bzl/qqwea4ny/execroot/mediapipe_api
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\msys64\usr\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\bazel;C:\nuget;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Professional\AppData\Local\Programs\Python\Python39;C:\Users\Professional\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\Professional\AppData\Local\Microsoft\WindowsApps
    SET PYTHON_BIN_PATH=C://Users//Professional//AppData//Local//Programs//Python//Python39//python.exe
    SET RUNFILES_MANIFEST_ONLY=1
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/com_google_mediapipe/mediapipe/framework/tool/encode_as_c_string.exe "bazel-out/x64_windows-opt/bin/external/com_google_mediapipe/mediapipe/graphs/object_detection_3d/subgraphs/renderer_cpu.binarypb" > "bazel-out/x64_windows-opt/bin/external/com_google_mediapipe/mediapipe/graphs/object_detection_3d/subgraphs/renderer_cpu.inc"
```

`encode_as_c_string.exe` failed and exit code is `-1073741502` (`STATUS_DLL_INIT_FAILED`).
I guess you've not installed `msys2` properly and some dlls are broken or missing.

If you can use Windows 10 Pro, I recommend you use [Docker](https://github.com/homuler/MediaPipeUnityPlugin#docker-for-windows-experimental).

**Comment by GORILA1221** [comment]
Thank you sir!
Reinstalled msys2
Everything is working
