### ISSUE TITLE
Received data to 3d model rendered in unity

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#204]
I am using ObjectDetection3d to show shoes on foot.

I used TimedModelMatrixProtoListPacket as a Packet class to receive data from the stream.
1 - I got Matrix with `var matrix = Matrix4x4FromBytes(matrixProtoList.ModelMatrix[0].MatrixEntries);`

` ShoeModelTransform.localScale = matrix.lossyScale;
   ShoeModelTransform.localRotation = matrix.rotation;
   ShoeModelTransform.localPosition = matrix.GetColumn(3);`
Also I assign matrix4x4 to shoe model transform as above.

But I can not exactly figure it out(You can see in image1).

2 - Also Model not track my foot position, it always in the middle. (You can see in image 2)

ps: black model from mediapipe, colored model from unity in IOS.

Can you help me how to solve my problems?
Thanks
![image1](https://user-images.githubusercontent.com/39331199/123105142-39580f80-d440-11eb-9430-362651a7914d.jpg)
![image2](https://user-images.githubusercontent.com/39331199/123105163-3ceb9680-d440-11eb-8edb-99a7714f2e86.jpg)

**Comment by emreboyraz0** [comment]
@homuler  can you help for getting position, scale and rotation from Matrix4x4. I tried everything but can not get proper solution.

**Comment by emreboyraz0** [comment]
Okey I found a solution. I closing issue.

**Comment by nenenkosi** [comment]
@emreboyraz0 Hi can you please explain in detail how you solved this issue coz am struggling to rendered the shoe in unity and tell me which files were modified any kind of help will be highly appreciated

**Comment by UX3D-mazzini** [comment]
hi can you please explain how you did it?
