### ISSUE TITLE
Build Error win10

### ISSUE THREAD

**Issue by Perhacept** [homuler/MediaPipeUnityPlugin#205]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):Windows 10
- Target (e.g. desktop cpu, android **arm64):**desktop cpu
- Bazel version:3.7.2
- Python version: 3.9.5(anaconda environment)
- GCC/G++ version: gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
- Unity version: 2020.3.8f1c1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
failed to build the native libraries 

**Steps to reproduce the issue**
I followed the Installation Guide for windows
until step 6: Run build command
(I use anaconda environment to run python 3.9.5)

conda activate py39
cd C:\Users\22757\Desktop\unitylearning_20210106_134810\MediaPipeUnityPlugin-master
set PYTHON_BIN_PATH=C:\Users\22757\Anaconda3\envs\py39\python.exe
python build.py build --desktop cpu --include_opencv_libs -v

**Full logs**
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 451.028s, Critical Path: 186.17s
INFO: 1501 processes: 701 internal, 800 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Users\22757\Desktop\unitylearning_20210106_134810\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\22757\Desktop\unitylearning_20210106_134810\MediaPipeUnityPlugin-master\build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "C:\Users\22757\Desktop\unitylearning_20210106_134810\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\22757\Anaconda3\envs\py39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//22757//Anaconda3//envs//py39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

**Comment by homuler** [comment]
Please run the below command (with `-vv`) and share the log.
```bat
python build.py build --desktop cpu --include_opencv_libs -vv
```
