### ISSUE TITLE
Update mediapipe version?

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#207]
Hello @homuler , In order to upgrade my mediapipe version for this unity project. 
If I take a pull on my main repository of mediapipe (the google one). Would that work in my case?
If not, how do you suggest upgrading the mediapipe version?

I'm asking this because in the new update they released world coordinates of landmarks. Try it out here https://codepen.io/mediapipe/full/jOMbvxw

**Comment by homuler** [comment]
MediaPipe v0.8.6 is supported now.
https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.6.2

**Comment by midopooler** [comment]
I tried to run the build.py commands separately for this release. And I'm getting these logs
My current system is Windows10. 
![image](https://user-images.githubusercontent.com/43686606/125195594-ecfc3480-e273-11eb-8dd3-7fce1d9cabdd.png)
