### ISSUE TITLE
MediaPipe Pose real-world 3D coordinates.

### ISSUE THREAD

**Issue by Manisharan-ritwik** [homuler/MediaPipeUnityPlugin#208]
Hi. Mediapipe is also providing POSE_WORLD_LANDMARKS along with POSE_LANDMARKS., may be in new version.

https://google.github.io/mediapipe/solutions/pose.html

In the description you've mentioned the mediapipe version is 0.8.3.1. I would like to know if you are planning to update mediapipe version or provide the world landmarks feature? Or Can you please let me know a possible way to get this feature in unity? Thanks.

**Comment by NathanielEssenberg** [comment]
I am looking forward to this being included as well :)

I tried the **0.8.6 branch**, but so far I noticed no commits to update the pose tracking in this repo. I tried to modify this project to use the POSE_WORLD_LANDMARKS but my knowledge of MediaPipeUnityPlugin is not good enough to make that work...

**Comment by homuler** [comment]
I suspect this feature does not work on GPU currently, so I stop upgrading mediapipe version.
https://github.com/google/mediapipe/issues/2251

**Comment by homuler** [comment]
MediaPipe v0.8.6 is supported now.
https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.6.2

**Comment by ROBYER1** [comment]
As mentioned here, the code for fetching pose world 3d landmarks is written but not used and I am struggling to make use of it - is there any example/guidance on how to get the pose world landmarks and use them in your example scene?
https://github.com/homuler/MediaPipeUnityPlugin/issues/219

**Comment by NathanielEssenberg** [comment]
I don't think the example scene has any new visualization features for the 3D landmarks, but you can get them yourself from the mentioned function
`private LandmarkList FetchNextPoseWorldLandmarks() { return FetchNext(poseWorldLandmarksStreamPoller, poseWorldLandmarksPacket, poseWorldLandmarksStream); }`
in whatever way suits you best. It works very similar to the 2D data; for me it worked fine. And then you can create a visualization however you like. I am using my own rendering stuff, but I imagine it would not be too hard to duplicate the 2D example visualization and modify it for 3D
