### ISSUE TITLE
Can't get the DLL to load in Editor

### ISSUE THREAD

**Issue by Densen90** [homuler/MediaPipeUnityPlugin#21]
Hi there,

I installed the mediapipe libraries and got the cpu examples to work.
I can also run your commands 'make cpu' and 'make install'.

Nonetheless I get the "DllNotFoundException: mediapipe_c" exception when running the CPU example scene. If I try to load the libmediapipe_c plugin on startup I get the following warning 
"Plugins: Couldn't open Assets/MediaPipe/SDK/Plugins/libmediapipe_c.so, error: Assets/MediaPipe/SDK/Plugins/libmediapipe_c.so: undefined symbol: _ZN2cv6String8allocateEm"

I installed OpenCV as mentioned in the mediapipe installation guide. I am running on Ubuntu 18.04.5 LTS and Unity 2019.4.15f1

I would be grateful for any help.

**Comment by homuler** [comment]
Maybe OpenCV is not installed under `/usr/lib` (e.g. `/usr/lib/x86_64-linux-gnu`).
https://github.com/homuler/MediaPipeUnityPlugin#opencv

In this case, please update [opencv_linux.BUILD](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/third_party/opencv_linux.BUILD#L32) according to your environment.

**Comment by Densen90** [comment]
Hi there, thank you very much, also for your fast answer. You were right the libraries were under /usr/lib/x86_64-linux-gnu

For anyone encountering this issue maybe the following is helping:
1. update [opencv_linux.BUILD](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/third_party/opencv_linux.BUILD#L32) for opencv, so instead of 'lib/libopencv*.so' it is 'lib/x86_64-linux-gnu/libopencv*.so'
2. rerun make cpu and make install
3. if unity was open, restart or reimport everything

That worked for me!

Thanks again!
