### ISSUE TITLE
How to remove shoe rendered in Mediapipe

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#213]
I am using shoes in Unity with model_matrices. But I am seeing 2 shoe in mobile, one of them rendered in mediapipe, and second rendered in unity. I want to remove shoe rendered in mediapipe. How can I do that? I removed GlAnimationOverlayCalculator in object_detection_3d_android but then graph not working. Can you help for my issue?

**Comment by homuler** [comment]
After removing `GlAnimationOverlayCalculator`, `ObjectDetection3dGraph` should inherit `DemoGraph`, not `OfficialDemoGraph`.

**Comment by emreboyraz0** [comment]
what is the difference DemoGraph and OfficialDemoGraph? Which part of OfficialDemoGraph trigger the rendering shoe in mediapipe?

**Comment by RMiTiG** [comment]
@emreboyraz0 Have you set the ImageCroppingCalculator's output video to GlScalerCalculator's input? 
And we need to new FetchNextxxx to receive output stream instead of ObserveOutputStream if we use DemoGraph.

**Comment by emreboyraz0** [comment]
@RMiTiG no just used homuler's version

**Comment by nenenkosi** [comment]
@emreboyraz0 and @RMiTiG I have been reading and following all the issues and I see that you guys have managed have to get the 3D shoe object_detection on both Android and IOS working and it’s been giving me problems so can I please get your Twitter usernames so I can follow you’ll so I get assistance from you’ll or can you please share a GitHub link to the work project on the 3D shoe object_detection coz I really need assistance this is my email nenenkosi@gmail.com

**Comment by emreboyraz0** [comment]
@homuler Please Can you explain "what is the difference DemoGraph and OfficialDemoGraph? Which part of OfficialDemoGraph trigger the rendering shoe in mediapipe?"

**Comment by emreboyraz0** [comment]
@homuler Which part of OfficialDemoGraph should not I use to remove shoe that rendered in mediapipe.

**Comment by homuler** [comment]
> what is the difference DemoGraph and OfficialDemoGraph? Which part of OfficialDemoGraph trigger the rendering shoe in mediapipe?

It's rather involved.

`DemoGraph` does not have default implementation of `RenderOutput`, so the subclass need to implement it.
In `OfficialDemoGraph`'s case, it only draws the image that MediaPipe returned.

On iOS and Desktop, it's straightforward (see the below code).
https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/Assets/Mediapipe/Samples/Graphs/OfficialDemo/Scripts/OfficialDemoGraph.cs#L104-L116

On Android, `OfficialDemoGraph` passes OpenGL's texture name to MediaPipe
https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/Assets/Mediapipe/Samples/Graphs/OfficialDemo/Scripts/OfficialDemoGraph.cs#L81-L86
and MediaPipe renders the result image to the texture.

However, this feature is not supported officially, so this plugin modified `GlScalerCalculator`
https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/third_party/mediapipe_extension.diff#L135-L146
and changes CalculatorGraphConfig accordingly (on Android devices only).
https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/Assets/Mediapipe/Samples/Graphs/OfficialDemo/Scripts/OfficialDemoGraph.cs#L35-L60

**Comment by homuler** [comment]
> I removed GlAnimationOverlayCalculator in object_detection_3d_android but then graph not working.

I don't know what do you mean by 'not working', but if it is that the screen becomes blank, you need to render the input image as other graphs do.
https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/Assets/Mediapipe/Samples/Graphs/FaceDetection/Scripts/FaceDetectionGraph.cs#L40

**Comment by emreboyraz0** [comment]
When I remove only GlAnimationOverlayCalculator it give below errors.

```
MediaPipeException: MediaPipe Aborted, refer glog files for more details
07-12 16:22:26.692 17354 17381 E Unity   :   at Mediapipe.MpReturnCodeExtension.Assert (Mediapipe.MpReturnCode code) [0x00000] in <00000000000000000000000000000000>:0 
07-12 16:22:26.692 17354 17381 E Unity   :   at Mediapipe.CalculatorGraph..ctor (System.Byte[] serializedConfig) [0x00000] in <00000000000000000000000000000000>:0 
07-12 16:22:26.692 17354 17381 E Unity   :   at OfficialDemoGraph.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
07-12 16:22:26.692 17354 17381 E Unity   :   at DemoGraph.Initialize (Mediapipe.GpuResources gpuResources, Mediapipe.GlCalculatorHelper gpuHelper) [0x00000] in <00000000000000000000000000000000>:0 
07-12 16:22:26.692 17354 17381 E Unity   :   at SceneDirector+<RunGraph>d__25.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
07-12 16:22:26.692 17354 17381 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 

```

**Comment by emreboyraz0** [comment]
![ss](https://user-images.githubusercontent.com/39331199/125301950-2b592880-e334-11eb-9cab-0205f5ba573a.jpeg)
basically I want to remove black shoe (rendered in mediapipe). I can render shoe with position,rotation and scale in unity too. So dont need to show black shoe that rendered in mediapipe.

**Comment by nenenkosi** [comment]
@emreboyraz0 Can you please explain in detail how you were able to render the shoe with position, rotation and scale in unity. Please name the files you got the 3D coordinates and where you modified the files if you have any customized code that you have cane you please share it or explain how you did it

**Comment by RMiTiG** [comment]
@emreboyraz0  I have removed MediaPipe's rendering successfully both in two ways as follows:
First and the easier way
Just remove the GlAnimationOverlayCalculator and modify the input/ouput.I don't know why you failed.It's graph(android) just like this("#" is removed for showing):
```
input_stream: "input_video"
input_stream: "WIDTH:input_width"
input_stream: "HEIGHT:input_height"
input_side_packet: "LABELS_CSV:allowed_labels"
input_side_packet: "MODEL_SCALE:model_scale"
input_side_packet: "MODEL_TRANSFORMATION:model_transformation"
input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      flip_vertically: true
    }
  }
}

node: {
  calculator: "ImageCroppingCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_stream: "WIDTH:input_width"
  input_stream: "HEIGHT:input_height"
  node_options: {
    [type.googleapis.com/mediapipe.ImageCroppingCalculatorOptions] {
      border_mode: BORDER_REPLICATE
    }
  }
}

node {
  calculator: "ObjectronGpuSubgraph"
  input_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_side_packet: "LABELS_CSV:allowed_labels"
  input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
  output_stream: "FRAME_ANNOTATION:lifted_objects"
}

node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  output_stream: "MODEL_MATRICES:model_matrices"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationsToModelMatricesCalculatorOptions] {
      # Re-scale the CAD model to the size of a unit box
      model_scale: [0.04, 0.04, 0.04]
      # Bring the box CAD model to objectron's coordinate system. This
      # is equivalent of -pi/2 rotation along the y-axis (right-hand rule):
      # Eigen::AngleAxisf(-M_PI / 2., Eigen::Vector3f::UnitY())
      model_transformation: [0.0,  0.0, -1.0,  0.0]
      model_transformation: [0.0,  1.0,  0.0,  0.0]
      model_transformation: [1.0,  0.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  0.0,  1.0]
    }
  }
}

node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  input_side_packet: "MODEL_SCALE:model_scale"
  input_side_packet: "MODEL_TRANSFORMATION:model_transformation"
  output_stream: "MODEL_MATRICES:mask_model_matrices"
}

node: {
  calculator: "GlScalerCalculator"
  input_stream: "VIDEO:throttled_input_video_3x4"
  output_stream: "VIDEO:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.GlScalerCalculatorOptions] {
      flip_vertical: true
    }
  }
}
```

The second way, just like homuler said, you don't need to ouput the vedio any more after you use DemoGraph,but it has lots of differences with OfficailDemoGraph so I sugguest you to reference [FaceMeshGraph](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Graphs/FaceMesh/Scripts/FaceMeshGraph.cs), now [ObjectDetectionGraph](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Graphs/ObjectDetection/Scripts/ObjectDetectionGraph.cs) as well.And I found that we can use ObserveOutputStream in DemoGraph in the same way（I'm wrong before).
In the graph,you need to remove the GlScalerCalculator and set another output to FlowLimiterCalculator's FINISHED.
If I only need the model_matrices,my graph(android) just like this:
```
input_stream: "input_video"
input_stream: "WIDTH:input_width"
input_stream: "HEIGHT:input_height"
input_side_packet: "LABELS_CSV:allowed_labels"
input_side_packet: "MODEL_SCALE:model_scale"
input_side_packet: "MODEL_TRANSFORMATION:model_transformation"
input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
output_stream: "model_matrices"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:model_matrices"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      flip_vertically: true
    }
  }
}

node: {
  calculator: "ImageCroppingCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_stream: "WIDTH:input_width"
  input_stream: "HEIGHT:input_height"
  node_options: {
    [type.googleapis.com/mediapipe.ImageCroppingCalculatorOptions] {
      border_mode: BORDER_REPLICATE
    }
  }
}

node {
  calculator: "ObjectronGpuSubgraph"
  input_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_side_packet: "LABELS_CSV:allowed_labels"
  input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
  output_stream: "FRAME_ANNOTATION:lifted_objects"
}

node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  output_stream: "MODEL_MATRICES:model_matrices"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationsToModelMatricesCalculatorOptions] {
      # Re-scale the CAD model to the size of a unit box
      model_scale: [0.04, 0.04, 0.04]
      # Bring the box CAD model to objectron's coordinate system. This
      # is equivalent of -pi/2 rotation along the y-axis (right-hand rule):
      # Eigen::AngleAxisf(-M_PI / 2., Eigen::Vector3f::UnitY())
      model_transformation: [0.0,  0.0, -1.0,  0.0]
      model_transformation: [0.0,  1.0,  0.0,  0.0]
      model_transformation: [1.0,  0.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  0.0,  1.0]
    }
  }
}
```
iOS is the same.

**Comment by emreboyraz0** [comment]
@homuler and @RMiTiG thanks for your helps.

@RMiTiG `input_stream: "VIDEO:throttled_input_video_3x4"` solved issue when i remove GlAnimationOverlayCalculator.

and 

` public override void RenderOutput(WebCamScreenController screenController, TextureFrame textureFrame) {

    screenController.DrawScreen(textureFrame);
  }`

removed rendered shoe.

**Comment by holaworlds** [comment]
Hi @emreboyraz0 , quick question for you. 

Does this `screenController.DrawScreen(textureFrame)` script renders Bounding Box or Shoe object ? I can't render shoe object and was looking for rendering mask object part but unfortunately wasn't successful though.
