### ISSUE TITLE
Fetching world landmarks doesn't work with back camera in android and iOS

### ISSUE THREAD

**Issue by Manisharan-ritwik** [homuler/MediaPipeUnityPlugin#217]
Hi. Now we are able to fetch world coordinates. It works fine but on iOS and Android, with back camera, getting the following issue.

 "tflite_inference_calculator.cc:1012] Please ensure input GPU tensor is 4 channels."

thanks you for your continuous support..

**Comment by homuler** [comment]
Will you share the full log, please?
