### ISSUE TITLE
Holistic Model flickers in the latest release

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#219]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): Windows 10
- Target Platform: Default (pc)
- Mobile Device (if the target is Android or iOS): NA
- MediaPipeUnityPlugin version or commit id: Latest 0.6.2   commit a754416741d4a16ce8b49c2adee77196bd762a47
- Bazel version: 4.0.0
- GCC/G++ version: NA
- Android NDK version (if the target platform is Android):NA
- Xcode version (if the target platform is iOS):NA

**Describe the current behavior**
The Holistic model flickers a lot in the latest commit. Earlier it worked very well. 

**Describe the expected behavior**
Earlier it was much more stable. 

**Steps to reproduce the issue**

I just cloned it and ran the build.py commands  `python build.py build --desktop cpu --include_opencv_libs -v
`

**Full logs**

![Screenshot_4](https://user-images.githubusercontent.com/43686606/125780576-64bf51de-ab72-47c3-86b4-7dc2ff6b13ce.png)

**Additional context**

Below is a screen recording of how it is going, 
https://photos.app.goo.gl/6rQbLjrTLPXxeUPe7

What do you think have gone wrong here? Rest of the solutions/graphs are running well as they were working in older versions.

**Comment by midopooler** [comment]
In addition, the following snippet seems to be unused. Could you please make a small documentation on how to use the world landmarks from this graph? That would be much helpful. 

`private LandmarkList FetchNextPoseWorldLandmarks() 
{
    return FetchNext(poseWorldLandmarksStreamPoller, poseWorldLandmarksPacket, poseWorldLandmarksStream);
  }`
 

https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Graphs/Holistic/Scripts/HolisticGraph.cs#L146-L148

**Comment by ROBYER1** [comment]
> In addition, the following snippet seems to be unused. Could you please make a small documentation on how to use the world landmarks from this graph? That would be much helpful.
> 
> `private LandmarkList FetchNextPoseWorldLandmarks() { return FetchNext(poseWorldLandmarksStreamPoller, poseWorldLandmarksPacket, poseWorldLandmarksStream); }`
> 
> https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Graphs/Holistic/Scripts/HolisticGraph.cs#L146-L148

@homuler Is there any example of how to use the world landmarks? I am trying to figure this out currently but the HolisticValue output only supports NormalizedLandMarkList rather than the returned LandmarkList. Just trying to get the world points from the 3d pose using the code in this push - https://github.com/homuler/MediaPipeUnityPlugin/commit/abbade082cbed35209f5c28ca5790f6c59c5e045

**Comment by midopooler** [comment]
@ROBYER1 definitely documentation is required. BTW, If you get it running, please do mention the process in this issue!

**Comment by ROBYER1** [comment]
Similar results here also, finding that the holistic graph, after running for about 60 seconds is lagging behind the user's body, this behaviour is consistent in Editor on Windows and on Android builds. Other graphs like the facemesh (solo) and pose track fine

**Comment by midopooler** [comment]
AFAIK, world landmarks are only available for the pose tracking graph and not for holistic. I hope @homuler knows about this? 

References:- https://codepen.io/mediapipe/

**Comment by ROBYER1** [comment]
> AFAIK, world landmarks are only available for the pose tracking graph and not for holistic. I hope @homuler knows about this?
> 
> References:- https://codepen.io/mediapipe/

Nope, available for holistic too, see here in the docs: https://google.github.io/mediapipe/solutions/holistic.html

Can you confirm you are getting similar latency/lag and drift with Holistic after 60 secs or so of running?

**Comment by ROBYER1** [comment]
But holistic was running okay on an earlier version before? I may have to roll back if so but also the 3d pose points are something we may need...

**Comment by midopooler** [comment]
Yes, it did worked well before 
I am using the previous version only for my [demonstrations](https://github.com/midopooler/CharacterAnimationUsingMediapipe).

**Comment by ROBYER1** [comment]
Thanks, pulling that down to take a look and compare now

**Comment by ROBYER1** [comment]
I can verify the latency issue is gone when rolling back to Mediapipe version 0.8.4 with this [commit](https://github.com/homuler/MediaPipeUnityPlugin/commit/24576ce968c05c748c1ed56f82866c30ea9190d4), seems in 0.8.6 at least the Holistic tracking has some latency after 30-60seconds for us on windows and android

**Comment by homuler** [comment]
I think #296 fixed this issue.
If the problem still continues, please reopen it.
