### ISSUE TITLE
Always stuck somewhere

### ISSUE THREAD

**Issue by libaibaba** [homuler/MediaPipeUnityPlugin#220]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): win10 Docker Win10
- Target (e.g. desktop cpu, android arm64): android arm64

**Describe the problem**
Always stuck somewhere...When I execute `python build.py build --android arm64 -v` ，It will run smoothly for a while, but gradually it will stop somewhere

**logs**
1：
  [Sched] .../modules/holistic_landmark:face_landmarks_from_pose_to_recrop_roi_graph_text_to_binary_graph; 2848s
    [Sched] ...//mediapipe/modules/pose_landmark:pose_detection_to_roi_graph_text_to_binary_graph; 2847s
    [Sched] ...//mediapipe/modules/pose_detection:pose_detection_gpu_graph_text_to_binary_graph; 2846s ...
2：
	    [Sched] Linking external/com_google_mediapipe/.../calculators/libiris_to_render_data_calculator.pic.lo; 1129s
    [Sched] Linking external/org_tensorflow/tensorflow/lite/core/api/libop_resolver.pic.a; 1123s
    [Sched] Linking external/org_tensorflow/tensorflow/lite/delegates/gpu/common/task/libtensor_desc.pic.a; 1112s ...
3：
	  [Sched] Linking external/com_google_protobuf/protoc; 3068s
    [Sched] Building external/bazel_tools/.../com/google/devtools/build/android/ResourceProcessorBusyBox.jar (); 3067s
    [Sched] Building external/bazel_tools/.../java/com/google/devtools/build/android/desugar/Desugar.jar (); 3067s ...
4：
   [Sched] Linking external/com_google_mediapipe/mediapipe/framework/libexecutor.pic.a; 1035s
    [Sched] Linking external/com_google_absl/absl/time/internal/cctz/libcivil_time.pic.a; 1034s
    [Sched] Linking external/com_google_absl/absl/flags/libflag_internal.pic.a; 1033s ...

This is where I stopped four times.This question is a bit similar [https://github.com/homuler/MediaPipeUnityPlugin/issues/154](url).

This is my distribution
`docker run --cpus=5 --memory=6192m ^
    --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages ^
    -it mediapipe_unity:linux`
Do you have any suggestions?（Please forgive my English, it comes from translation engine）

**Comment by libaibaba** [comment]
When I allocated 1 CPU and 1 g of memory, it changed
`docker run --cpus=1 --memory=1024m ^
    --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages ^
    -it mediapipe_unity:linux`
FAILED LOG:
`clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/motion_estimation-5bf84b.cpp
clang: note: diagnostic msg: /tmp/motion_estimation-5bf84b.sh
clang: note: diagnostic msg:

********************
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 13506.932s, Critical Path: 11545.11s
INFO: 2647 processes: 439 internal, 2208 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 153, in run
    self._run_command(self._build_android_commands())
  File "/home/mediapipe/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--verbose_failures', '--config=android_arm64', '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android']' returned non-zero exit status 1.`

It's the only "normal" thing that bothers me for four days.（Please forgive my English, it comes from translation engine）

**Comment by homuler** [comment]
Please check CPU and RAM usage during compiling. If RAM usage gets 100%, then thrashing would occur.
Also note that your container may run out of memory if you assign too small memory to it.
