### ISSUE TITLE
Using additional (pose) parameters

### ISSUE THREAD

**Issue by NathanielEssenberg** [homuler/MediaPipeUnityPlugin#222]
Hello,

I first want to thank you for getting the 3D pose detection up and running so quickly :).

I have a question though, because I do not have much experience with the details of graphs.
I managed to toggle smooth landmarks in the pose graph by adding "input_side_packet: "SMOOTH_LANDMARKS:smooth_landmarks"" to the PoseLandmarkGpu/Cpu node in the graphs. And the bool value was already being loaded into a SidePacket form C#. This seems to work fine.
But I saw on the MediaPipe site that there is also a MIN_TRACKING_CONFIDENCE parameter that I would like to play with. However, when I add that to the graph and the SidePacket in the same way, Unity Editor just crashes. I did not find much about enabling this parameter in MediaPipe, except some python examples.
Does this only work on Gpu? (I did not try making an Android build yet but I will)
Or otherwise, is there any way to modify these kind of parameters? (For pose, there are also MIN_DETECTION_CONFIDENCE and STATIC_IMAGE_MODE, for instance, although I don't need to change those)

Thank you for the great work :)

**Comment by homuler** [comment]
I'm not familiar with Python APIs, but I suppose [min_tracking_confidence](https://google.github.io/mediapipe/solutions/holistic#min_tracking_confidence) is only supported in Python (and maybe CPU only).

See https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/python/solution_base.py#L393 and https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/python/solutions/holistic.py#L115

`smooth_landmarks` can be passed to MediaPipe through `input_side_packet`, but `min_tracking_confidence` is not declared as such. In the above code, they rewrite the `CalculatorConfig` dynamically like [this](https://github.com/homuler/MediaPipeUnityPlugin/blob/a754416741d4a16ce8b49c2adee77196bd762a47/Assets/Mediapipe/Samples/Graphs/OfficialDemo/Scripts/OfficialDemoGraph.cs#L49-L54) (of course, you can apply a patch and modify the definitions of internal graphs (e.g. `PoseLandmarkGpu`) instead).

> However, when I add that to the graph and the SidePacket in the same way, Unity Editor just crashes. 

I'm not sure but there may be some bugs in your code. If the given side packet is not used in the `CalculatorConfig`, it is usually ignored.

**Comment by NathanielEssenberg** [comment]
Thank you for the explanation. I understand the problem, but I have no experience with modifying the internal graphs, so I will not try that now :).

Just to clarify, what I mentioned was that I just did this in the C#:

`sidePacket = new SidePacket();`
`sidePacket.Emplace("smooth_landmarks", new BoolPacket(smoothLandmarks));`
**_`sidePacket.Emplace("min_tracking_confidence", new FloatPacket(minTrackingConfidence));`_**

And modified the pose_tracking_XXX.txt files in the samples like this:

`node {`
`  calculator: "PoseLandmarkXXX"`
`  input_stream: "IMAGE:transformed_input_video"`
`  input_side_packet: "SMOOTH_LANDMARKS:smooth_landmarks"`
**_`  input_side_packet: "MIN_TRACKING_CONFIDENCE:min_tracking_confidence"`_**
`  output_stream: "LANDMARKS:pose_landmarks"`
`  output_stream: "WORLD_LANDMARKS:pose_world_landmarks"`
`  output_stream: "DETECTION:pose_detection"`
`  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks"`
`}`

But I understand that the input_side_packet is not defined in the referenced internal graph, and that is why this crashes. (The smooth_landmarks side packet works fine, of course)

Thank you for your help, I will close this and look into modifying graphs another day :)
