### ISSUE TITLE
Legs without shoes

### ISSUE THREAD

**Issue by raavii** [homuler/MediaPipeUnityPlugin#223]
**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): `Windows 10 20H2`
Target (e.g. desktop cpu, android arm64): `Android arm64`
Bazel version: `4.1.0`
Python version: `3.9.6`
Unity version: `2020.3.14f1`
Android NDK version (if building for Android): `19`

**Describe the problem**
Good day. I am using the ObjectDetection3d module from the example. Please help me how to teach this to recognize feet without shoes. Thanks.

**Comment by ROBYER1** [comment]
Seems this is more of an issue or question to raise with the Google Mediapipe team tbh
