### ISSUE TITLE
Python Build failing.

### ISSUE THREAD

**Issue by Najaf93** [homuler/MediaPipeUnityPlugin#224]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): Desktop
- Bazel version: bazel 5.0.0-pre.20210720.2
- Python version: Python 3.9.5
- GCC/G++ version:6.3.0
- Unity version:2020.3.8f1
- Android NDK version (if building for Android):android-ndk-r21e
- Xcode version (if building for iOS):

**Describe the problem**
I couldn't make it run on unity, I followed all the steps. Lots of error showing in unity also i think those errors are due to failed build.

**Steps to reproduce the issue**
after setting up all the environments i ran this command:"python build.py build --desktop cpu --include_opencv_libs -v" on the root folder of the unity project

**Full logs**
ERROR: Traceback (most recent call last):
        File "C:/_bzl/x2bju7r6/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
                ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "C:/_bzl/x2bju7r6/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "C:/_bzl/x2bju7r6/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: error loading package '@com_google_mediapipe//mediapipe/gpu': at C:/_bzl/x2bju7r6/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
INFO: Elapsed time: 1.998s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 365 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/gpu
Traceback (most recent call last):
  File "D:\MediaPipe\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\MediaPipe\MediaPipeUnityPlugin-master\build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "D:\MediaPipe\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Python39//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

**Additional context**

**Comment by homuler** [comment]
Same as https://github.com/homuler/MediaPipeUnityPlugin/issues/202
Please use bazel 4.0.0.

**Comment by Najaf93** [comment]
@homuler  Thanks man.
