### ISSUE TITLE
Build.py syntax errors

### ISSUE THREAD

**Issue by holaworlds** [homuler/MediaPipeUnityPlugin#225]
**Describe the problem**

Hi, there are couple syntax error in build.py file. I attached one example. I tried to clean but there are plenty syntax errors and I don't want to ruin the code. thx

**Steps to reproduce the issue**
I used linux Docker and Macos steps. Both use same build.py file, therefore problem persists regardless of the platform. 

**Full logs**
  File "build.py", line 46
    self.console.v(f"Running `{' '.join(command_list)}`")
SyntaxError: invalid syntax
                                                       ^

**Comment by dhruvmodhapp** [comment]
Yes, the Same issue I am facing for macOS setup.

**Comment by holaworlds** [comment]
no need anymore

**Comment by dhruvmodhapp** [comment]
> no need anymore

Do You get a solution for this? Please let me know how to fix this

**Comment by homuler** [comment]
Probably you're using Python 2.x.
Please use Python >= 3.9.0.
https://github.com/homuler/MediaPipeUnityPlugin#prerequisites
