### ISSUE TITLE
DllNotFoundException: mediapipe_c | NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Arham-Aalam** [homuler/MediaPipeUnityPlugin#227]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):  Windows
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 4.1.0
- Python version: 3.7.8
- GCC/G++ version: 19.16.27045 for x64
- Unity version: 2020
- Android NDK version (if building for Android): 
- Xcode version (if building for iOS):

**Describe the problem**
Plugins: Failed to load 'C:/Users/arham/Documents/extras/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.

**Steps to reproduce the issue**
I tried to open in editor by clicking over DemoDesktop scene.
Also tried to import it as package, Even I also reinstalled the Unity 2020.

**Full logs**
```
Plugins: Failed to load 'C:/Users/arham/Documents/extras/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.
DllNotFoundException: mediapipe_c
Mediapipe.ResourceManager..ctor () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/ResourceManager.cs:20)
Mediapipe.LocalAssetManager..ctor () (at <e2b237ecb26f4097b4aa4033f48ffa11>:0)
LocalAssetLoader.Start () (at Assets/Mediapipe/Samples/Scripts/ResourceManager/LocalAssetLoader.cs:5)
NullReferenceException: Object reference not set to an instance of an object
LocalAssetLoader.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) (at Assets/Mediapipe/Samples/Scripts/ResourceManager/LocalAssetLoader.cs:9)
DemoGraph.PrepareDependentAsset (System.String assetName, System.String uniqueKey, System.Boolean overwrite) (at Assets/Mediapipe/Samples/Scripts/DemoGraph.cs:192)
DemoGraph.PrepareDependentAsset (System.String assetName, System.Boolean overwrite) (at Assets/Mediapipe/Samples/Scripts/DemoGraph.cs:196)
FaceDetectionGraph.PrepareDependentAssets () (at Assets/Mediapipe/Samples/Graphs/FaceDetection/Scripts/FaceDetectionGraph.cs:57)
DemoGraph.Initialize () (at Assets/Mediapipe/Samples/Scripts/DemoGraph.cs:46)
SceneDirector+<RunGraph>d__23.MoveNext () (at Assets/Mediapipe/Samples/Scripts/SceneDirector.cs:171)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e414e10bfe5f45729ff122f3359de21b>:0)
```

**Additional context**
Even I ignore this DLL error and run the scene but it is producing following error:
```
NullReferenceException: Object reference not set to an instance of an object
LocalAssetLoader.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) (at Assets/Mediapipe/Samples/Scripts/ResourceManager/LocalAssetLoader.cs:9)
DemoGraph.PrepareDependentAsset (System.String assetName, System.String uniqueKey, System.Boolean overwrite) (at Assets/Mediapipe/Samples/Scripts/DemoGraph.cs:192)
DemoGraph.PrepareDependentAsset (System.String assetName, System.Boolean overwrite) (at Assets/Mediapipe/Samples/Scripts/DemoGraph.cs:196)
FaceDetectionGraph.PrepareDependentAssets () (at Assets/Mediapipe/Samples/Graphs/FaceDetection/Scripts/FaceDetectionGraph.cs:57)
DemoGraph.Initialize () (at Assets/Mediapipe/Samples/Scripts/DemoGraph.cs:46)
SceneDirector+<RunGraph>d__23.MoveNext () (at Assets/Mediapipe/Samples/Scripts/SceneDirector.cs:171)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e414e10bfe5f45729ff122f3359de21b>:0)
```

**Comment by Arham-Aalam** [comment]
@homuler  Any hint?

**Comment by jsaon-L** [comment]
Looks like this question
https://github.com/homuler/MediaPipeUnityPlugin#troubleshooting
check `libmediapipe_c.dll`  `load on startup` enable and restart editor

**Comment by zoggie** [comment]
i have the same problem.   Even after setting "Load on startup" the error comes back when i restart unity. 
Despite the error, everything is working except for objectron3d which i understand is not supported currently.

When compiling, the build seems to succeed but it does not load MediaPipeUnityPlugin_Data/Mono/mediapipe_c.dll

**Comment by homuler** [comment]
It usually occurs when you start Unity before building native libraries (Unity removes `.meta` files).
cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/186#issuecomment-851253589

> Even after setting "Load on startup" the error comes back when i restart unity.

On Windows, please just ignore this error if it works.
It seems that `libmediapipe_c.dll` must be loaded after OpenCV but we cannot specify the order.

**Comment by Arham-Aalam** [comment]
Thanks @homuler  it worked, 
In my case I was using ```OpenCV 3.4.15``` So my DLL file was ```opencv_world3415.dll``` but the meta file was ```opencv_world3410.dll.meta```, So instead of changing my OpenCV version I try to rename meta as ```opencv_world3415.dll.meta``` and it worked!
