### ISSUE TITLE
ARFoundation Handtracking Android 

### ISSUE THREAD

**Issue by JuuGuy** [homuler/MediaPipeUnityPlugin#231]
Any support for integrating ARFoundation/ARCore, specifically handtracking  (ex.pass XRCpuImage to mediapipe)?

**Comment by homuler** [comment]
Not yet, but you can use it if you convert the input data to `NativeArray`, `byte[]` or `Texture`.

**Comment by homuler** [comment]
I don't want to add dependencies, so there are currently no plans for support.
To integrate this plugin with `ARFoundation`, copy the pixel data of `XRCpuImage` into `NativeArray` and initialize an `ImageFrame` using it (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1096698719).
