### ISSUE TITLE
How to strip/remove unused modes to reduce app build size (Android/IOS)?

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#232]
I already saw some examples of how to strip out unused models from around March before the SDK folder was moved into a Unity package - [Streaming Assets](https://github.com/homuler/MediaPipeUnityPlugin/issues/92#issuecomment-801016410) and [Symbol info stripping](https://github.com/homuler/MediaPipeUnityPlugin/issues/65#issuecomment-782481610). It seems there is no way I can see of setting Assetbundles to 'none' for the resources in Packages/MediaPipe Plugin/Runtime/Resources.

How can we strip out he models we don't need, are they only included now if code references them or do I need to go and delete them from the Package folder now?

**Comment by NathanielEssenberg** [comment]
I can share the things I did so far (focusing on Android)...

**For AssetBundles:**
- I suspect that both the assetbundle and the original resources might be included in a build. I could be wrong. To be safe, I modified the BuildProcessor so depending on the target platform (i.e. depending whether assetbundles are being used or not), it temporarily moves the resources or assetbundles folder to a different folder so it is not included in the build. And I move it back in that script when the build is finished.
- I didn't see how to unassign the assetbundle unused graph resources either, so I just deleted the ones I am not using.  However, if you don't want to remove them but just exclude them from the assetbundle, you can still find their assetbundle name in the meta file if you open it in a text editor, and change it there.

**For the binaries:**
- I tried to make the --linkopt="-s" work, which was a bit of trial-and-error. When I thought I got it to work it didn't make a difference, so either the symbols are already excluded in the current version or I did something wrong. Compared to the sizes mentioned in those posts, I am assuming the symbols are already gone by now because my binary is smaller than mentioned there.
- Make sure in Unity that the binaries for different platforms are only included for those platforms. If they are not already.
- Finally, I have commented out the graphs I am not using in the mediapipe_api/BUILD file.

Currently, my Android arm64 .aar binary is 81 mb for just pose tracking, and a Unity project with just pose tracking (Full only) compiles to around 100 mb for Android.

If there is anything more I can do, or if I am doing something wrong, I would also like to know how we can best reduce the size of the binaries as much as possible.
I noticed, for example, that the posetrackinggpu.apk demo from MediaPipe is only 21 mb in total. So I am curious if we can reduce the .aar binary to something like 10-20 mb as well :)

**Comment by ROBYER1** [comment]
I figured that all out myself also and reached the same sizes. Ian wondering also if we can get that build size down much smaller as you said the samples were 20mb. We are using holistic so I got holistic down to 100mb in Unity build size. Bearing in mind holistic includes Pose, Face, Iris and Hands graphs, you may be able to comment out more in your Build file if you are using just Pose.

**Comment by ROBYER1** [comment]
> I can share the things I did so far (focusing on Android)...
> 
> **For AssetBundles:**
> 
> * I suspect that both the assetbundle and the original resources might be included in a build. I could be wrong. To be safe, I modified the BuildProcessor so depending on the target platform (i.e. depending whether assetbundles are being used or not), it temporarily moves the resources or assetbundles folder to a different folder so it is not included in the build. And I move it back in that script when the build is finished.
> * I didn't see how to unassign the assetbundle unused graph resources either, so I just deleted the ones I am not using.  However, if you don't want to remove them but just exclude them from the assetbundle, you can still find their assetbundle name in the meta file if you open it in a text editor, and change it there.
> 
> **For the binaries:**
> 
> * I tried to make the --linkopt="-s" work, which was a bit of trial-and-error. When I thought I got it to work it didn't make a difference, so either the symbols are already excluded in the current version or I did something wrong. Compared to the sizes mentioned in those posts, I am assuming the symbols are already gone by now because my binary is smaller than mentioned there.
> * Make sure in Unity that the binaries for different platforms are only included for those platforms. If they are not already.
> * Finally, I have commented out the graphs I am not using in the mediapipe_api/BUILD file.
> 
> Currently, my Android arm64 .aar binary is 81 mb for just pose tracking, and a Unity project with just pose tracking (Full only) compiles to around 100 mb for Android.
> 
> If there is anything more I can do, or if I am doing something wrong, I would also like to know how we can best reduce the size of the binaries as much as possible.
> I noticed, for example, that the posetrackinggpu.apk demo from MediaPipe is only 21 mb in total. So I am curious if we can reduce the .aar binary to something like 10-20 mb as well :)

Hey, would you be able to possibly share your 'BUILD' file from the 'mediapipe_api' folder please? We have decided also to just use Pose rather than holistic, however my trimmed down Build file seems to work fine for Desktop but not android builds - seems there is some dependency I am deleting from the Build file that needs to stay there but we took out like 12-15 lines so it's a very long process of trial and error!

If I could see what you removed from the Build file it would help a lot!

**Comment by ROBYER1** [comment]
> I can share the things I did so far (focusing on Android)...
> 
> **For AssetBundles:**
> 
> * I suspect that both the assetbundle and the original resources might be included in a build. I could be wrong. To be safe, I modified the BuildProcessor so depending on the target platform (i.e. depending whether assetbundles are being used or not), it temporarily moves the resources or assetbundles folder to a different folder so it is not included in the build. And I move it back in that script when the build is finished.
> * I didn't see how to unassign the assetbundle unused graph resources either, so I just deleted the ones I am not using.  However, if you don't want to remove them but just exclude them from the assetbundle, you can still find their assetbundle name in the meta file if you open it in a text editor, and change it there.
> 
> **For the binaries:**
> 
> * I tried to make the --linkopt="-s" work, which was a bit of trial-and-error. When I thought I got it to work it didn't make a difference, so either the symbols are already excluded in the current version or I did something wrong. Compared to the sizes mentioned in those posts, I am assuming the symbols are already gone by now because my binary is smaller than mentioned there.
> * Make sure in Unity that the binaries for different platforms are only included for those platforms. If they are not already.
> * Finally, I have commented out the graphs I am not using in the mediapipe_api/BUILD file.
> 
> Currently, my Android arm64 .aar binary is 81 mb for just pose tracking, and a Unity project with just pose tracking (Full only) compiles to around 100 mb for Android.
> 
> If there is anything more I can do, or if I am doing something wrong, I would also like to know how we can best reduce the size of the binaries as much as possible.
> I noticed, for example, that the posetrackinggpu.apk demo from MediaPipe is only 21 mb in total. So I am curious if we can reduce the .aar binary to something like 10-20 mb as well :)

Hey, would you be able to possibly share your 'BUILD' file from the 'mediapipe_api' folder please? We have decided also to just use Pose rather than holistic, however my trimmed down Build file seems to work fine for Desktop but not android builds - seems there is some dependency I am deleting from the Build file that needs to stay there but we took out like 12-15 lines so it's a very long process of trial and error!

If I could see what you removed from the Build file it would help a lot!

**Comment by ROBYER1** [comment]
[BUILD.zip](https://github.com/homuler/MediaPipeUnityPlugin/files/6975904/BUILD.zip)

Here is the build file that I am using just for Pose Full model, build apk size from Unity is around 127mb.
Let me know if you have any more tips for stripping!

Paste in case the zip doesn't stay up:
`load("@rules_pkg//:pkg.bzl", "pkg_zip")
load("//mediapipe_api:import_model.bzl", "pkg_asset")

cc_library(
    name = "mediapipe_c",
    deps = [
        ":calculators",
        "//mediapipe_api/external:glog",
        "//mediapipe_api/external:protobuf",
        "//mediapipe_api/external:stdlib",
        "//mediapipe_api/framework:calculator",
        "//mediapipe_api/framework:calculator_graph",
        "//mediapipe_api/framework:output_stream_poller",
        "//mediapipe_api/framework:timestamp",
        "//mediapipe_api/framework/formats:classification",
        "//mediapipe_api/framework/formats:detection",
        "//mediapipe_api/framework/formats:image_frame",
        "//mediapipe_api/framework/formats:landmark",
        "//mediapipe_api/framework/formats:rect",
        "//mediapipe_api/framework/port:logging",
        "//mediapipe_api/graphs/object_detection_3d/calculators:model_matrix",
        "//mediapipe_api/modules/face_geometry/protos:face_geometry",
        "//mediapipe_api/util:resource_util",
    ] + select({
        "@com_google_mediapipe//mediapipe/gpu:disable_gpu": [],
        "//conditions:default": [
            "//mediapipe_api/gpu:gl_base",
            "//mediapipe_api/gpu:gl_context",
            "//mediapipe_api/gpu:gl_calculator_helper",
            "//mediapipe_api/gpu:gl_texture_buffer",
            "//mediapipe_api/gpu:gpu_buffer",
            "//mediapipe_api/gpu:gpu_buffer_format",
            "//mediapipe_api/gpu:gpu_shared_data_internal",
        ],
    }) + select({
        "@com_google_mediapipe//mediapipe/gpu:disable_gpu": [],
        "@com_google_mediapipe//mediapipe:ios": [],
        "//conditions:default": [
            "//mediapipe_api/gpu:egl_surface_holder",
        ],
    }),
    visibility = ["//visibility:public"],
    alwayslink = True,
)

cc_binary(
    name = "libmediapipe_c.so",
    deps = [":mediapipe_c"],
    linkshared = True,
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "libmediapipe_c.dylib",
    deps = [":mediapipe_c"],
    linkshared = True,
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "libmediapipe_c.dll",
    deps = [":mediapipe_c"],
    linkshared = True,
    linkstatic = True,
    visibility = ["//visibility:public"],
)

alias(
    name = "libmediapipe_c",
    actual = select({
        "@com_google_mediapipe//mediapipe:macos": ":libmediapipe_c.dylib",
        "@com_google_mediapipe//mediapipe:windows": ":libmediapipe_c.dll",
        "//conditions:default": ":libmediapipe_c.so",
    }),
)

# It is recommended that you include only neccessary calculators.
cc_library(
    name = "calculators",
    deps = [
        "@com_google_mediapipe//mediapipe/calculators/core:pass_through_calculator",
        "@com_google_mediapipe//mediapipe/calculators/core:packet_presence_calculator",
        "@com_google_mediapipe//mediapipe/calculators/core:flow_limiter_calculator",
        "@com_google_mediapipe//mediapipe/calculators/image:image_transformation_calculator",
    ] + select({
        "@com_google_mediapipe//mediapipe/gpu:disable_gpu": [
            "@com_google_mediapipe//mediapipe/graphs/pose_tracking:pose_tracking_cpu_deps",
            "@com_google_mediapipe//mediapipe/graphs/tracking:desktop_calculators",
        ],
        "//conditions:default": [
            # ATTENTION!
            #   If you're building for Android with debug symobls (--compilation_mode=dbg), exclude `instant_motion_tracking_deps`
            #   or exclude the other deps defined under `mediapipe/graphs`.
            #   Otherwise the app will crash (MediaPipe may have some bugs).
            "@com_google_mediapipe//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
            "@com_google_mediapipe//mediapipe/graphs/tracking:mobile_calculators",
        ],
    }),
)

cc_library(
    name = "common",
    srcs = ["common.cc"],
    hdrs = ["common.h"],
    deps = [
        "@com_google_mediapipe//mediapipe/framework/port:logging",
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
)

pkg_zip(
    name = "mediapipe_desktop",
    srcs = [":libmediapipe_c"],
)

pkg_asset(
    name = "mediapipe_assets",
    srcs = [
        "@com_google_mediapipe//mediapipe/modules/pose_detection:pose_detection.tflite",
        "@com_google_mediapipe//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",
    ],
)

pkg_zip(
    name = "mediapipe_proto_srcs",
    srcs = [
        "//mediapipe_api/framework:calculator_cs",
        "//mediapipe_api/framework:calculator_options_cs",
        "//mediapipe_api/framework:mediapipe_options_cs",
        "//mediapipe_api/framework:packet_factory_cs",
        "//mediapipe_api/framework:packet_generator_cs",
        "//mediapipe_api/framework:status_handler_cs",
        "//mediapipe_api/framework:stream_handler_cs",
        "//mediapipe_api/framework/formats:classification_cs",
        "//mediapipe_api/framework/formats:detection_cs",
        "//mediapipe_api/framework/formats:landmark_cs",
        "//mediapipe_api/framework/formats:location_data_cs",
        "//mediapipe_api/framework/formats:matrix_data_cs",
        "//mediapipe_api/framework/formats:rasterization_cs",
        "//mediapipe_api/framework/formats:rect_cs",
        "//mediapipe_api/graphs/instant_motion_tracking/calculators:sticker_buffer_cs",
        "//mediapipe_api/graphs/object_detection_3d/calculators:model_matrix_cs",
        "//mediapipe_api/modules/face_geometry/protos:face_geometry_cs",
        "//mediapipe_api/modules/face_geometry/protos:mesh_3d_cs",
    ],
    # TODO: keep directory structure
)

pkg_zip(
    name = "opencv_libs",
    srcs = select({
        "@opencv//:source_build": ["@opencv//:opencv_libs"],
        "@com_google_mediapipe//mediapipe:windows": ["@windows_opencv//:opencv_libs"],
        "@com_google_mediapipe//mediapipe:macos": [],
        "@com_google_mediapipe//mediapipe:android": [],
        "@com_google_mediapipe//mediapipe:ios": [],
        "//conditions:default": ["@linux_opencv//:opencv_libs"],
    }),
)
`

**Comment by NathanielEssenberg** [comment]
Sure I can share the BUILD file. Not much going on there. But I actually ran into an issue as well:
I switched my project to Vulkan (on Android) earlier this week, and it broke pose tracking. Seems to be maybe an issue with the texturepool. I still have to try the vanilla project because I made some changes., before I open a new issue here. It works fine on OpenGL ES 3.
[BUILD.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6980111/BUILD.txt)

As for --linkopt="-s"... After some trial and error, I forced it to be added to the build command in build.py. I am not 100% sure it worked, but at least it compiled (after a few tries). But it made 0 difference.

**Comment by ROBYER1** [comment]
I got the stripping working (only needed for android) by using --strip_all at the end of the build command you use, e.g.

`python build.py build --android arm64 --strip_all`

By doing that and stripping the build script down to the basics of what we needed, our Unity build for Pose detection only is about 40mb which nearly 25-30mb of it Unity engine assets anyway I believe

**Comment by NathanielEssenberg** [comment]
I see... In newer version of MediaPipeUnity --strip_all was replaced with --linkopt=-s, though.
I tried linkopt before, but I definitely did it wrong back then. I just tried it again and it seems to work with this fix: https://github.com/homuler/MediaPipeUnityPlugin/issues/65#issuecomment-835934392

So I replaced the return of the linkopt in build.py as described there, and used build command
`python build.py build --android arm64 --linkopt=-s -vv`

Android .aar is about 12 mb that way for just pose, which is really great imo :)
