### ISSUE TITLE
Windows docker blocking

### ISSUE THREAD

**Issue by tisaud** [homuler/MediaPipeUnityPlugin#233]
**System information**
- Windows [version 10.0.19042.1110]
- Docker Desktop 3.5.2

**Describe the problem**
Whether blocking is normal here?

**Steps to reproduce the issue**
just run
docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile

**Full logs**
![1](https://user-images.githubusercontent.com/33447003/128343708-75a1915b-f7e1-48b7-97bd-4da45124e30d.PNG)

**Comment by norbykov** [comment]
Please see the instructions for installation in the Readme.md file:

"This process will hang when MSYS2 is being installed.
If this issue occurs, remove C:\ProgramData\Docker\tmp\hcs*\Files\$Recycle.Bin\ manually (hcs* is random name).
cf. https://github.com/docker/for-win/issues/8910"

**Comment by tisaud** [comment]
Sorry, I overlooked it,now it works,thank you.

**Comment by tisaud** [comment]
Blocked again！
Full logs
![2](https://user-images.githubusercontent.com/33447003/128482107-cd23cc5e-d1f0-442d-bf1a-8a7b02290f1e.PNG)

**Comment by tisaud** [comment]
Please ignore this issue, it just took some time to download,thank you
