### ISSUE TITLE
CalculatorGraphConfig missing on project

### ISSUE THREAD

**Issue by sr229** [homuler/MediaPipeUnityPlugin#235]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 11 (10.22000.120)
- Target (e.g. desktop cpu, android arm64): desktop
- Bazel version: 
- Python version: 3.9
- GCC/G++ version: 5
- Unity version: 2019.4.23f1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

Building the project solution yields an error since `CalculatorGraphConfig` is missing in the project solution.

**Comment by holaworlds** [comment]
I can see it under this path:

`.../MediaPipeUnityPlugin-master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraphConfig.cs`

**Comment by sr229** [comment]
> I can see it under this path:
> 
> `.../MediaPipeUnityPlugin-master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraphConfig.cs`

This only contains the extension class but not the class itself. Perhaps it was defined somewhere else?

**Comment by homuler** [comment]
`CalculatorGraphConfig` is defined [here](https://github.com/google/mediapipe/blob/b899d17f185f6bcbf3f5947d3e134f8ce1e69407/mediapipe/framework/calculator.proto#L224).

If you run `build.py` successfully, `Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Calculator.cs` will be compiled.
