### ISSUE TITLE
How I can pull rotation matrix ? 

### ISSUE THREAD

**Issue by holaworlds** [homuler/MediaPipeUnityPlugin#237]
Hi,

I checked ObjectDetection3dGraph, OfficialDemoGraph, DemoGraph but can not see the way I can pull rotation matrix and use it. Or another question, where did 3D BB renderer got called in these classes? 

thanks for your help!

**Comment by DrQwertySilence** [comment]
From what I know you need to calculate it (I don't know if this Package has some utility for that). What I do is:

1. Get some vertices that are somewhat stable (the one that form the "face oval" excluding the jaw and the forehead are good)
2. Calculate the centroid of the previous vertices.
3. Get a stable reference point in the front of the face (the ones from the nose are pretty good) and form a vector with the previous vertex (try to make it parallel to unity's Z axis so you don't have to adjust it latter).

With that vector you should be able to do what you want.

**Comment by holaworlds** [comment]
Hi  DrQwertySilence, thank you for explanation, I'm using shoe example. I want to render my own shoe game object using detected 3D Bounding Box.  Which scripts are u using to manipulate/pull rotation/translation data ?

**Comment by DrQwertySilence** [comment]
If you know the box vertices (8 vertices) you should be able to use Unity's `Quaternion.LookRotation(Vector3 forward, Vector3 up)` function.
![box_edges](https://user-images.githubusercontent.com/1941149/128975759-c19d61cf-4bd2-4f9c-8ea9-e8e81e10fd3c.png)
Pick those two edges and pass them to the previous function.

**Comment by holaworlds** [comment]
I was hoping that these 3 rotations (x,y,z) calculated somewhere in the project already and I can use it to render and rotate my objects. Do you know by chance how can I do this?

**Comment by ROBYER1** [comment]
I saw that there was the addition of RotationAngle in the HolisticLandmarkListAnnotation.cs and also in a HierarchicalAnnotation.cs script but couldn't find an example in pose or holistic samples that reads these rotation angle values

**Comment by emirhanylmzz** [comment]
@holaworlds @ROBYER1 Did you get any solutions ?

**Comment by homuler** [comment]
`CameraCoordinate.GetApproximateQuaternion` can be used to get a `Quaternion`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/738f3f7eccc391bac943e68bbc2178c97a5db124/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/CameraCoordinate.cs#L209-L218
