### ISSUE TITLE
We are also working on MediaPipeUnity plugin, can we talk?

### ISSUE THREAD

**Issue by tutu5110** [homuler/MediaPipeUnityPlugin#238]
Hey Homuler, nice work! Do you have an email address? We are working on similar things and wonder if we can collaborate. Thanks!

**Comment by homuler** [comment]
I'm sorry, I can't give you a response without more details.

**Comment by tutu5110** [comment]
Ah sure! I am a Ph.D student from Brown University in US. This is the link to our group's public page, https://hci.brown.edu/
Please let me know what else I can provide. Thanks!
