### ISSUE TITLE
Can not render sneaker 3D Model on deteced shoe.

### ISSUE THREAD

**Issue by holaworlds** [homuler/MediaPipeUnityPlugin#239]
OS Platform and Distribution : Macos
Target :android arm64
Python version: 3.9
Unity version: 2021.1.15
Android NDK version (if building for Android):10
**Describe the current behavior**

I want to render my 3d shoe object, I see there is an input called sneaker_texture in ObjectDetection3d prefab but i can't see any object rendered.  Detection works perfectly, but I can't see sneaker rendered. 

@homuler  Do you see rendered model by default when running the example or do I have to do additional implementation?

**Comment by RICKYLIKEBIRD** [comment]
@holaworlds  Do you have a solution?

**Comment by D3m0n92** [comment]
Same question...

**Comment by homuler** [comment]
Close this now `Point3D` data are accessible.
Please reopen the issue if you have any questions.
