### ISSUE TITLE
How to modify NUM_HANDS

### ISSUE THREAD

**Issue by Densen90** [homuler/MediaPipeUnityPlugin#24]
Hi there,

in the mediapipe examples i can set the NUM_HANDS variable in the MainActivity.java for hand tracking. Where inside your project can I edit this to have more than two hands detected?

Thanks and cheers!

**Comment by homuler** [comment]
`num_hands` is defined in [`HandTrackingGraph` config](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipe/Examples/Resources/hand_tracking_mobile.txt#L23) and you can set value to it through `SidePacket` (see https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipe/Examples/Scripts/HandTracking/HandTrackingGraph.cs#L51).

**Comment by Densen90** [comment]
Hi there,

thanks for your help!

I assume I have to change     "sidePacket.Emplace("num_hands", new IntPacket(2));"
to     sidePacket.Emplace("num_hands", new IntPacket(3));
or     sidePacket.Emplace("num_hands", new IntPacket(4));

With a value of 1 or 2 it works pretty good, but with a value above that, it either doesn't recognize a third hand or the recognition gets very flicky and jumpy.

Do you have an idea on how to avoid this?

Thank you again!

**Comment by Densen90** [comment]
I also updated your repository and tha android hand tracking does work worse now, I don't even get tha position of the finger joints etc.
Any idea how I could fix that?

Thanks again and you are doing great work!

**Comment by homuler** [comment]
> With a value of 1 or 2 it works pretty good, but with a value above that, it either doesn't recognize a third hand or the recognition gets very flicky and jumpy.

Can you get more than 2 hand landmark lists? If so, this is only annotation problems.
Please change the value of `DefaultMaxSize` of [MultiHandLandmarkListsAnnotation](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipe/Examples/Objects/Annotation/MultiHandLandmarkListsAnnotation.prefab).
![handlandmarklist-annotation](https://user-images.githubusercontent.com/4690128/100723890-a3a65580-3405-11eb-81ab-7716d6569dec.png)

> I don't even get tha position of the finger joints etc.

I confirmed it. I'll investigate it later.

**Comment by homuler** [comment]
In Progress

I'm investigating it now, but haven't detected the cause yet.
I suspect that the input data is broken (e.g. the channel order is wrong, etc...).

**Comment by homuler** [comment]
memo:
At least, `PalmDetectionGpu` seems to be working, but [ThresholdingCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_gpu.pbtxt#L86) returns false (that is, hands are not present in the input) and no landmark data are output.

[InferenceCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_gpu.pbtxt#L48) may not be working, or the input tensor (`input_tensor`) of the calculator may be invalid.

**Comment by homuler** [comment]
I'm sorry I cannot specify the commit that fixed the problem, but it's fixed at https://github.com/homuler/MediaPipeUnityPlugin/commit/4a656876fe79993630151642665ca6679ea68328 .
