### ISSUE TITLE
win10 cpu build error

### ISSUE THREAD

**Issue by Joel-Ee** [homuler/MediaPipeUnityPlugin#241]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): windows 10
- Target Platform: windows 10
- Mobile Device (if the target is Android or iOS): none
- MediaPipeUnityPlugin version or commit id: 0.6.2
- Bazel version: 4.0.0
- GCC/G++ version: Visual C++ Build Tools 2019
- Android NDK version (if the target platform is Android): none
- Xcode version (if the target platform is iOS): none

**Describe the current behavior**
Executing build command:
     python build.py build --desktop cpu --include_opencv_libs -v
     Failed with an error occurred during the fetch of repository 'local_execution_config_python'
**Describe the expected behavior**
   It should finished build package successfully
**Steps to reproduce the issue**

Describe the exact steps to reproduce the issue.
Do as tutorial instructions to compile plugin in system mentioned above step by step.

If you have changed or written code, please provide minimum code.
None!

**Full logs**
Please attach Editor.log (if it occurs on Unity Editor) or Player.log (if it occurs at runtime).
See https://docs.unity3d.com/Manual/LogFiles.html

python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//Administrator//AppData//Local//Programs//Python//Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/44c890cd46fd9aad2b3bf4b13c5f36d8cff795c3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/mn7i5no2/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository local_execution_config_python instantiated at:
  D:/joelaaset/mediapipeunityplugin-master/WORKSPACE:450:14: in <toplevel>
  C:/_bzl/mn7i5no2/external/org_tensorflow/tensorflow/workspace2.bzl:1087:19: in workspace
  C:/_bzl/mn7i5no2/external/org_tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  C:/_bzl/mn7i5no2/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/mn7i5no2/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
信息: 用提供的模式无法找到文件。
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/mn7i5no2/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
信息: 用提供的模式无法找到文件。
INFO: Repository com_google_protobuf instantiated at:
  D:/joelaaset/mediapipeunityplugin-master/WORKSPACE:177:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/mn7i5no2/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository rules_java instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:229:6: in <toplevel>
  C:/_bzl/mn7i5no2/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  C:/_bzl/mn7i5no2/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  D:/joelaaset/mediapipeunityplugin-master/WORKSPACE:35:23: in <toplevel>
  C:/_bzl/mn7i5no2/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/mn7i5no2/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/mn7i5no2/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Repository command failed
信息: 用提供的模式无法找到文件。
INFO: Elapsed time: 1.124s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (7 packages)
Traceback (most recent call last):
  File "D:\JoelAaset\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\JoelAaset\MediaPipeUnityPlugin-master\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\JoelAaset\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//Administrator//AppData//Local//Programs//Python//Python39//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Additional context**

**Comment by ROBYER1** [comment]
Have you tried using Docker?
