### ISSUE TITLE
open unity error

### ISSUE THREAD

**Issue by MRLesile** [homuler/MediaPipeUnityPlugin#247]
I pulled the latest project from GIT, but an error was reported when I opened it from Unity[
![1629338587788](https://user-images.githubusercontent.com/24579953/129995882-0c724f33-306d-4d5e-ae82-6a34de18ecb5.jpg)
](url)

**Comment by jsaon-L** [comment]
你需要跟著Readme 先build 才能使用

**Comment by MRLesile** [comment]
> 你需要跟着Read me 先build 才能使用

我按照了他的方式Build过了，你是Window上跑的还是Mac 上，我是Mac上

**Comment by jsaon-L** [comment]
Windows原生 Mac Linux 我都構建成功過 你肯定build失敗了

**Comment by MRLesile** [comment]
> Windows原生 Mac Linux 我都構建成功過 你肯定build失敗了

哥们私聊请教一下呀

**Comment by jsaon-L** [comment]
你qq多少

**Comment by MRLesile** [comment]
> 你qq多少

909566321

**Comment by wnn2216520305** [comment]
哥们方便加下 2216520305,当前Build过程中遇到问题，请教下

**Comment by ChrisJHullEPM** [comment]
MediaPipe hasn't been built correctly. You should go back through the instructions provided.

**Comment by ROBYER1** [comment]
You need to build Mediapipe following the instructions in the Readme...
