### ISSUE TITLE
[IOS/Android] Pose Tracking Freezing when moving quickly offscreen or during faster movements occasionally

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#248]
**System information**
Platform and Distribution: IOS 14 - Tested on iPhone 7 and current Gen iPad. Android 10 on Sony Xperia XZ3 
- MediaPipeUnityPlugin version or commit id: https://github.com/homuler/MediaPipeUnityPlugin/commit/a754416741d4a16ce8b49c2adee77196bd762a47
- Android NDK version (if the target platform is Android): r21d bundled with Unity 2021.1.17f1
- Xcode version (if the target platform is iOS): 12.5.1 (12E507)

**Describe the current behavior**
Using just the Pose tracking graph in the Desktop Demo build to run on IOS/Android in builds we are noticing sometimes the app is prone to crashing when the user moves off screen quickly or it is intermittently crashing during fast hand/body movements on occasion. Even just picking the phone up and wobbling it around can sometimes crash. During this time, observed memory and CPU usage isn't spiking or anything crazy, and Xcode/Logcat give us no crash logs and don't even register it as a crash. To the logs it just thinks the app is still running but it is frozen.

This is not reproducible in the Editor on Windows or mac which makes me suspect this behaviour is mobile only, as well as this I noticed most people on the github issues here aren't doing much on-device testing anyway so I would assume to most it appears that mediapipe pose detection is running fine always because it does so in the Editor, but not on device when deployed.

**Describe the expected behavior**
The pose detection graph should run as expected on mobile and run without any crashing like it does in Editor.

**Steps to reproduce the issue**
1. Build mediapipe for android on windows docker and build mediapipe for ios on Mac
2. Build and run the Desktopdemo scene on IOS iphone or an Android phone, choose the pose detection graph, switch to front camera and wave the phone around + move in and out of the camera view quickly to create a crash/freeze

I am happy to share the example project we are using privately with you if this helps.

**Comment by mgarbade** [comment]
I remember that we had similar issues with the 0.6.2 release of the plugin. The problem came from mediapipe itself. At some point mediapipe was trying to invert an empty matrix which produces an error. Errors in mediapipe cause the whole plugin to crash. We had to recompile the plugin with a fix in mediapipe that checks if the matrix is not empty before inverting it.
