### ISSUE TITLE
use Gyro in Objectron3d

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#249]
Hi;
I am using objectron3d and render 3d models in Unity. 

Can you help how can i using gyro in objectron3d to slow rotation and movement on camera. 

 InstantMotionTracking graph using gyro with "imu_rotation_matrix". How can i use gyro like that?

Regards

**Comment by homuler** [comment]
I feel like this is out of scope for this plugin, but can you describe in more detail what you want to do?
