### ISSUE TITLE
[IOS/Android] Changing camera on the Pose Detection graph a few times causes a crash - stop start of graph issue

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#250]
System information
Platform and Distribution: IOS 14 - Tested on iPhone 7 and current Gen iPad. Android 10 on Sony Xperia XZ3

MediaPipeUnityPlugin version or commit id: a754416
Android NDK version (if the target platform is Android): r21d bundled with Unity 2021.1.17f1
Xcode version (if the target platform is iOS): 12.5.1 (12E507)

Describe the current behavior
Using just the Pose tracking graph in the Desktop Demo build to run on IOS/Android in builds we are noticing consistently the app is prone to crashing when changing the camera device using the dropdown. Xcode/Logcat give us no crash logs and don't even register it as a crash. To the logs it just thinks the app is still running but it is frozen.

I found this issue when trying to find ways to compensate for the latency that creeps in on the Pose detection graph when using the latest repo from around https://github.com/homuler/MediaPipeUnityPlugin/commit/a754416741d4a16ce8b49c2adee77196bd762a47
I also tried using this fix but it caused an occasional crash on mobile devices too https://github.com/homuler/MediaPipeUnityPlugin/issues/244#issuecomment-900315679

This is not reproducible in the Editor on Windows or mac which makes me suspect this behaviour is mobile only, as well as this I noticed most people on the github issues here aren't doing much on-device testing anyway so I would assume to most it appears that mediapipe pose detection is running fine always because it does so in the Editor, but not on device when deployed.

Describe the expected behavior
The pose detection graph should run as expected on mobile and run without any crashing like it does in Editor.

Steps to reproduce the issue

1. Build mediapipe for android on windows docker and build mediapipe for ios on Mac
2. Build and run the Desktopdemo scene on IOS iphone or an Android phone, choose the pose detection graph, switch between front and back camera at least 10-15 times to see a crash.

3. This crash can also be reproduced if you call the stop / start graph functions yourself programmatically - I had this running in an invokeRepeating  function every 30 seconds or so which is where I noticed that crash.

I am happy to share the example project we are using privately with you if this helps.

**Comment by homuler** [comment]
Close this issue for lack of activities.

**Comment by ROBYER1** [comment]
Apologies, I am looking into this issue now - we are using Mediapipe 0.8.4, is there a way for us to backport this patch there or will we need to move ahead into using Mediapipe 0.8.8?

**Comment by homuler** [comment]
I recommend you use the latest version, but if you want to use an older version, apply a patch as follows:

1. Create a patch file and place it under [`third_party/`](https://github.com/homuler/MediaPipeUnityPlugin/tree/4d90ac44627dd0996792e56fdc0817a7b15ada4a/third_party).
2. Update WORKSPACE (append the patch file path under the below line).
   https://github.com/homuler/MediaPipeUnityPlugin/blob/4d90ac44627dd0996792e56fdc0817a7b15ada4a/WORKSPACE#L60

See also https://github.com/homuler/MediaPipeUnityPlugin/issues/242#issuecomment-900249401.
