### ISSUE TITLE
How to import the MediaPipeUnityPlugin to another Unity project.

### ISSUE THREAD

**Issue by Luis-Alves2** [homuler/MediaPipeUnityPlugin#252]
Hello All,

I've been trying to use the Facemesh 3D part of MediaPipeUnityPlugin inside another Unity project , however even though I managed to find and insert the libmediapipe_c.dll into the Assets folder,  I still can't find the name of the namespace required to utilise its methods. Could you please tell me how you managed to use the methods? 

Thank you!

**Comment by ROBYER1** [comment]
Copy the Packages > com.homuler... folder too

**Comment by mgarbade** [comment]
Any idea where I can access the output the mediapipe models, e.g. the detected keypoint / landmark locations  for further usage in Unity?

**Comment by Luis-Alves2** [comment]
Hi, @ROBYER1 and everyone, could you please elaborate on that? Should I copy the json files also included in the Plugin > Packages folder? I know that there is data on the plugin on the packages-lock, at the very least, however, there are other dependencies for my project which means that copying that file wouldn't solve my problems (or at least I think so).  There were also some compiler issue when I copied only the com.homuler folder, is this common, was it supposed to work from the get go?

**Comment by ROBYER1** [comment]
You need to read the readme here and build Mediapipe for your target platform https://github.com/homuler/MediaPipeUnityPlugin

**Comment by ROBYER1** [comment]
I think that Homuler is rewriting the plugin to make it easier to copy.. if you copy the com.homuler folder at least and also the Mediapipe folder in Assets that should work?

**Comment by LGuilhermeRodrigues** [comment]
> I think that Homuler is rewriting the plugin to make it easier to copy.. if you copy the com.homuler folder at least and also the Mediapipe folder in Assets that should work?

That works for me @ROBYER1,

I'd also like to mention that and my manifest.json in Packages Folder of the "parent project" has the line:
`"com.github.homuler.mediapipe": "file:com.github.homuler.mediapipe",`
and packages-lock.json:
`    "com.github.homuler.mediapipe": {`
`      "version": "file:com.github.homuler.mediapipe",`
`      "depth": 0,`
`      "source": "embedded",`
`      "dependencies": {}`
`    },`
I don't remember if that files are automatically generated or I've added by hand, but maybe it can help @Luis-Alves2

**Comment by homuler** [comment]
You can [import it as a local package](https://docs.unity3d.com/Manual/upm-ui-local.html) after building native libraries, not if you need to add the whole source code to your repository.

I'm wondering if it would be better to prepare a script to creating `unitypackage` file, but I'm not sure what would be best, so if you have an opinion, please let me know.

**Comment by mgarbade** [comment]
I could import the DesktopDemo project into my project. I had to:
- export the destop demo scene as a package
- copy the com.homuler.... folder inside the package folder of my project
- adapt the json file in my project (via file comparison program

**Comment by Luis-Alves2** [comment]
Thanks everyone, I followed what Robyer and LGuilhermeRodrigues said and it seems to work just fine.

**Comment by nenenkosi** [comment]
@Luis-Alves2 nice I haven’t tried it yet can you please outline all the steps you took to make it work.
One question did it decrease the app bundle size on mobile without you stripping or optimizing the app size?
