### ISSUE TITLE
NodeAnnotations didn't follow Webcamtexture while I was rotating  Webcamtexture.

### ISSUE THREAD

**Issue by armstrong0919** [homuler/MediaPipeUnityPlugin#253]
I got the problem which is rotate the entire  NodeAnnotations.
And just figured out this way to solve the problem.
But not sure if there's a better solution
any suggestion?

1. open the script which named "AnnotationController".

2.Add an extension method.
public static class Extension
{
    public static Vector3 TransformPointUnscaled(this Transform transform, Vector3 position)
    {
        var localToWorldMatrix = Matrix4x4.TRS(transform.position, transform.rotation, Vector3.one);
        return localToWorldMatrix.MultiplyPoint3x4(position);
    }

    public static Vector3 InverseTransformPointUnscaled(this Transform transform, Vector3 position)
    {
        var worldToLocalMatrix = Matrix4x4.TRS(transform.position, transform.rotation, Vector3.one).inverse;
        return worldToLocalMatrix.MultiplyPoint3x4(position);
    }
}

3. switch method GetPositionFromNormalizedPoint to area below
  protected Vector3 GetPositionFromNormalizedPoint(Transform screenTransform, float x, float y, bool isFlipped)
 {
      var relX = (isFlipped ? -1 : 1) * (x - 0.5f);
      var relY = 0.5f - y;
      var RelScale = Vector3.Scale(new Vector3(relX, relY, 0), ScaleVector(screenTransform));
     Vector3 Rotated_vector = new Vector3(-RelScale.x, 0, -RelScale.y);
     return screenTransform.TransformPointUnscaled(Rotated_vector);
    }

**Comment by homuler** [comment]
Fixed by #296 
Now `PointAnnotation` supports rotation.
