### ISSUE TITLE
python build.py build  --ios arm64 error

### ISSUE THREAD

**Issue by MRLesile** [homuler/MediaPipeUnityPlugin#254]
ERROR: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
		apple_support.run_shell(
	File "/private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/build_bazel_apple_support/lib/apple_support.bzl", line 326, column 26, in _run_shell
		ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
ERROR: Analysis of target '//mediapipe_api/objc:MediaPipeUnity' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed
INFO: Elapsed time: 0.385s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 7116 targets configured)

**Comment by homuler** [comment]
Please describe the issue in [this format](https://github.com/homuler/MediaPipeUnityPlugin/blob/b8ea5c1fb0b5f0eeebb5de731147d2db46a76e23/.github/ISSUE_TEMPLATE/build-installation-issue.md).

If you're using bazel >= 4.0.0, please use 3.7.2.
See [here](https://github.com/homuler/MediaPipeUnityPlugin#prerequisites) and https://github.com/google/mediapipe/issues/1551
