### ISSUE TITLE
other

### ISSUE THREAD

**Issue by RICKYLIKEBIRD** [homuler/MediaPipeUnityPlugin#255]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):windows
- Target (e.g. desktop cpu, android arm64):cpu
- Bazel version:3.7.2
- Python version:3.9
- GCC/G++ version:
- Unity version:
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

I edit  third_party/opencv_windows.BUILD and WORKSPACE.
Because my opencv is 4.5.3
![1](https://user-images.githubusercontent.com/52875633/130787722-53582196-301c-4b4d-9c90-a74ce2254b24.PNG)
![2](https://user-images.githubusercontent.com/52875633/130787742-c15be0e8-5e4f-4c33-9136-ba6aa8ba9aae.PNG)
but when I build python build.py build --desktop cpu --include_opencv_libs -v
![3](https://user-images.githubusercontent.com/52875633/130787806-4d90885c-abbc-4bd4-8593-ba343925e853.PNG)
Any error in my modification?

**Comment by homuler** [comment]
You also need to change SHA256, because bazel caches archives (or you can simply remove this line).
https://github.com/homuler/MediaPipeUnityPlugin/blob/b8ea5c1fb0b5f0eeebb5de731147d2db46a76e23/WORKSPACE#L231


Please note that some features does not work with OpenCV 4.x.
