### ISSUE TITLE
I want use unity build Android but failed

### ISSUE THREAD

**Issue by RICKYLIKEBIRD** [homuler/MediaPipeUnityPlugin#257]
I want to build an Android app in unity
I have successfully opened the demo program
But when it’s built on a mobile phone, it can’t start the camera smoothly.
Maybe you have some ideas?

**Comment by EmilioSantillana** [comment]
Did you follow the steps and run build.py with docker? https://github.com/homuler/MediaPipeUnityPlugin#android

If yes also check if you are running Scene Director using GPU, android needs that.

**Comment by RICKYLIKEBIRD** [comment]
![335639](https://user-images.githubusercontent.com/52875633/133201551-b4f092f9-833e-4739-958f-0b29fdb6f58c.jpg)
@EmilioSantillana  I do this https://github.com/homuler/MediaPipeUnityPlugin#android
and open checked use GPU,but the camara still not work

**Comment by homuler** [comment]
Please share the log.
```sh
adb logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"
```

**Comment by RICKYLIKEBIRD** [comment]
![image](https://user-images.githubusercontent.com/52875633/133208331-41a94032-6f6d-415b-ab6f-044e72bc516c.png)
@homuler  thank you help

**Comment by homuler** [comment]
It's same as https://github.com/homuler/MediaPipeUnityPlugin/issues/119
