### ISSUE TITLE
Camera Resolution

### ISSUE THREAD

**Issue by EmilioSantillana** [homuler/MediaPipeUnityPlugin#258]
Hi everyone.
The issue is really weird and i dont know why it happends... 
I´m trying to make an app for android that recognizes your pose and the 3d model can follow you, all good with that but i´m trying to change the resolution to portrait and when i do that in "Web Cam Screen Controller" script it throws an error saying this:

![image](https://user-images.githubusercontent.com/49165704/131226574-dc23a94b-09ba-417f-8755-a033024da6c6.png)

I really appreciate if you read and answer my post.
Thanks!

**Comment by EmilioSantillana** [comment]
Ignore the last error of "Camisa.cs"

**Comment by homuler** [comment]
Fixed by #296
