### ISSUE TITLE
Did you need help testing on IOS?

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#26]
I have access to a mac and an Iphone 11 if you needed assistance with supporting IOS, I would be keen to help contribute if you have any pointers on what you think is needed?

**Comment by yosun** [comment]
Likewise. Have all iPhones and iPads for testing :) including the latest 12 pro max ;)

**Comment by homuler** [comment]
Thank you, iOS is supported now.
I only tested with iPad Air (4th gen) and I'm happy if you try it with other devices.
