### ISSUE TITLE
DllNotFoundException: mediapipe_c (Win10 Unity)

### ISSUE THREAD

**Issue by shubhank008** [homuler/MediaPipeUnityPlugin#260]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):  Windows 10 (with Unity 2020.2)
- Target (e.g. desktop cpu, android arm64):    (Desktop/Windows)
- Unity version: 2020.2
-Built during Dockerfile

**Describe the problem**  
Compiled using DockerFile and got the build success with the .dll files, but when using in Unity it throws a DllNotFoundException: mediapipe_c  
I tried using Load on Startup but then it throws  

```
Plugins: Failed to load 'D:/Unity Projects/sofiqeunity/Sofiqe/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

Screenshots attached
<img width="195" alt="Unity_JSm9nFtf9t" src="https://user-images.githubusercontent.com/3790163/131515789-8813d610-646e-41b2-bd72-0ccf47e6b599.png">
<img width="766" alt="Unity_15Efgm1F65" src="https://user-images.githubusercontent.com/3790163/131515796-1bb1fb38-5315-426f-aa2b-fd7665aef7ce.png">
<img width="766" alt="Unity_3KoyBtiqqU" src="https://user-images.githubusercontent.com/3790163/131515798-20322ad2-158d-4ae9-a5dd-09119d20e766.png">

**Comment by shubhank008** [comment]
I do not know what I could be missing if I built using docker and even tried importing and installing the OpenCV asset from assetstore.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/186#issuecomment-851253589 .
You also need to load `opencv_world_3410.dll` on startup.

Even after that, `DllNotFoundException` will be output when Unity Editor starts, but just ignore it.
The correct way to do this is to load OpenCV first, but there seems to be no way to specify the loading order at the moment.

**Comment by shubhank008** [comment]
> See [#186 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/186#issuecomment-851253589) .
> You also need to load `opencv_world_3410.dll` on startup.
> 
> Even after that, `DllNotFoundException` will be output when Unity Editor starts, but just ignore it.
> The correct way to do this is to load OpenCV first, but there seems to be no way to specify the loading order at the moment.

I had already loaded opencv on startup, I tried using your recommended way of trying to load mediapipe on startup as well, but just doing that and applying the change throws the missing dependency error  which shouldn't be the case with docker compile and opencv also existing.  
Loading opencv throws no error.  

I tried ignoreing the DLLException and keeping load at startup disabled for mediapipe and run my standalone build on laptop, but there was no output from my webcam in the demo.

```
Plugins: Failed to load 'D:/Unity Projects/sofiqeunity/Sofiqe/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by homuler** [comment]
Can you run it on UnityEditor?

**Comment by shubhank008** [comment]
> Can you run it on UnityEditor?

Nope, all the above errors are from Unity Editor itself, I had only tried to run standalone to try and ignore the errors as you had hinted the same to someone else in another issue.

**Comment by homuler** [comment]
> but just doing that and applying the change throws the missing dependency error

It is expected as I mentioned at https://github.com/homuler/MediaPipeUnityPlugin/issues/260#issuecomment-909769036 .

> I tried ignoreing the DLLException and keeping load at startup disabled for mediapipe 

No, `Load on startup` must be checked, even though DLLNotFoundException will be thrown every time UnityEditor starts.
Just checkout `.meta` files and restart UnityEditor, and play sample scenes.

If sample scenes does not work, then please share the Editor.log.

**Comment by shubhank008** [comment]
> > but just doing that and applying the change throws the missing dependency error
> 
> It is expected as I mentioned at [#260 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/260#issuecomment-909769036) .
> 
> > I tried ignoreing the DLLException and keeping load at startup disabled for mediapipe
> 
> No, `Load on startup` must be checked, even though DLLNotFoundException will be thrown every time UnityEditor starts.
> Just checkout `.meta` files and restart UnityEditor, and play sample scenes.
> https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll.meta#L9
> 
> If sample scenes does not work, then please share the Editor.log.

Thanks a lot, got it working now. 
Trick that worked for me was, disable load on start for both files, restart unity.  
Enable load on start for opencv file, restart unity.  
Enable load on start for mediapipe file, restart unity.  
After that also it threw the not found error but then I just ignored it and the demo worked in Editor play mode.  

However, I couldn't get it to work in standalone build mode.  
Attaching the player.log file.  
[Player.log](https://github.com/homuler/MediaPipeUnityPlugin/files/7090271/Player.log)

**Comment by homuler** [comment]
> However, I couldn't get it to work in standalone build mode.

Please uncheck `Use GPU`.
https://github.com/homuler/MediaPipeUnityPlugin#desktop

**Comment by homuler** [comment]
> Trick that worked for me was, disable load on start for both files, restart unity.
Enable load on start for opencv file, restart unity.
Enable load on start for mediapipe file, restart unity.

This error occurs when you first start UnityEditor before building native libraries.
It's usually fixed by running `git checkout Packages/com.github.homuler.mediapipe/Runtime/Plugins/` and restarting UnityEditor.

**Comment by shubhank008** [comment]
> > However, I couldn't get it to work in standalone build mode.
> 
> Please uncheck `Use GPU`.
> https://github.com/homuler/MediaPipeUnityPlugin#desktop

GPU is unchecked before I built the standalone build.  

And weird, I am pretty sure I had first built the libraries and then launched unity editor, but it might have been a meta-files issues as I reviewing a project from someone else and pulled their git commit.

**Comment by homuler** [comment]
> as I reviewing a project from someone else and pulled their git commit.

Well, then please ask them. I close this issue now.
> EntryPointNotFoundException: mp_GpuResources_Create__Pv
  at (wrapper managed-to-native) Mediapipe.UnsafeNativeMethods.mp_GpuResources_Create__Pv(intptr,intptr&)
  at Mediapipe.GpuResources.Create (System.IntPtr externalContext) [0x00000] in <1b0f6e3f81db4629a3d6b5f2146544bf>:0 
  at SceneDirector.SetupGpuResources () [0x00049] in <63672909b5964adfb0dca645fef604fa>:0 

This error won't occur on my repo as far as `Use GPU` is not checked.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/Assets/Mediapipe/Samples/Scripts/SceneDirector.cs#L114-L116

**Comment by homuler** [comment]
If the problem still occurs at https://github.com/homuler/MediaPipeUnityPlugin/commit/d58ab72c8149fce183ce804aef2e218f74ff70dc , please reopen the issue.

**Comment by smtabatabaie** [comment]
> See [#186 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/186#issuecomment-851253589) . You also need to load `opencv_world_3410.dll` on startup.
> 
> Even after that, `DllNotFoundException` will be output when Unity Editor starts, but just ignore it. The correct way to do this is to load OpenCV first, but there seems to be no way to specify the loading order at the moment.
Do you still need opencv_world_3410.dll if you build on an M1 Mac? I run git checkout and opencv_world3416.dll.meta and opencv_world3416d.dll.meta gets created but it doesn't create dll files, the meta files also get deleted after I switch to my Unity Editor.

**Comment by mgarbade** [comment]
After quite a while I re-bumped in to this problem again (when moving to a new computer). Here is how I solved it:

- Open Visual Studio installler
- Install C++ Desktop Developer tools
- relaunch Unity-Editor 
-> now mediapipe_c.dll will be found

My Config:
- Unity 2020.3.26f1
- MediaPipeUnityPlugin Plugin version 10.1
- Windows 10 Pro
