### ISSUE TITLE
IOS - YOUR_BUNDLE_ID_HERE default name in the build script prevents build uploading to Apple

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#261]
Could we please change the 'YOUR_BUNDLE_ID_HERE' default name as when the plugin is built for IOS, it produces an invalid CFBundleidentifier which is only apparent when going to upload the app to Testflight where the issue is flagged.

That and also some advice in the getting started guide for IOS notifying users to change that bundle id?

**Comment by homuler** [comment]
I agree it would be good to have some documentation on this.
It would be better if we can specify the bundle id from `build.py`.

> Could we please change the 'YOUR_BUNDLE_ID_HERE' default name as when the plugin is built for IOS

I've actually never released it to the AppStore before, can you tell me how to get it to work?
Probably the content of [Info.plist](https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/mediapipe_api/objc/Info.plist) is not appropriate too (at least, `CFBundlePackageType` should be `FMWK`).

I thought that we must specify the Bundle ID and that this value needed to be unique globally, so I am currently setting a dummy value to avoid conflicts.

**Comment by ROBYER1** [comment]
> I agree it would be good to have some documentation on this.
> It would be better if we can specify the bundle id from `build.py`.
> 
> > Could we please change the 'YOUR_BUNDLE_ID_HERE' default name as when the plugin is built for IOS
> 
> I've actually never released it to the AppStore before, can you tell me how to get it to work?
> Probably the content of [Info.plist](https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/mediapipe_api/objc/Info.plist) is not appropriate too (at least, `CFBundlePackageType` should be `FMWK`).
> 
> I thought that we must specify the Bundle ID and that this value needed to be unique globally, so I am currently setting a dummy value to avoid conflicts.

All I did was change the 'YOUR_BUNDLE_ID' string to something without the '_' characters, so I changed it to YOURBUNDLEID and rebuilt, the app uploaded fine after.

The only issue really was the generated CFBundle (or similar) framework path became something like 'IOSapp/YOUR_/BUNDLE_/HERE' as the underscore '_' character is not permitted in the strings for that path, it actually seemed to break the path. I was surprised the IOS app worked after seeing that!

**Comment by jsaon-L** [comment]
I also encountered this problem

**Comment by RoyAmoyal** [comment]
can I use this library for my iPhone unity app? will it build in xcode for my iphone?

**Comment by ROBYER1** [comment]
Closing this issue as it is going to be fixed in the future through the build script via this closed PR https://github.com/homuler/MediaPipeUnityPlugin/pull/342

**Comment by homuler** [comment]
Sorry, I reopen this to leave it as a reminder.

**Comment by homuler** [comment]
fixed by https://github.com/homuler/MediaPipeUnityPlugin/commit/06423ca40c0a6d3daf8519505f62e8a7cd592719

**Comment by ROBYER1** [comment]
Thanks, I noticed that some plugins and things even like unity framework sign their own bundle id with their own preset id or even a generic one. I'm glad you updated the readme to mention this as sometimes people get as far as uploading the app to testflight/Apple servers then they finally get the bundle id warning.

**Comment by homuler** [comment]
With this change, it became no longer possible to build the plugin in the first place (validation error will occur).
