### ISSUE TITLE
Error at build with repository 'rules_python'

### ISSUE THREAD

**Issue by torreb1990** [homuler/MediaPipeUnityPlugin#262]
Any help? Pls I'm wasting a lot of hours trying to install all this stuffs....

ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/zo2y7x2p/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/zo2y7x2p/external/rules_python): The System Cannot find the File Specified
 (error: 2)
ERROR: C:/users/user/mediapipe_api/BUILD:173:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git init C:/_bzl/zo2y7x2p/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/zo2y7x2p/external/rules_python): The System Cannot find the File Specified
 (error: 2)
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed

**Comment by torreb1990** [comment]
now the error changed:

ERROR: An error occurred during the fetch of repository 'com_google_mediapipe':
   Traceback (most recent call last):
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                patch(ctx)
        File "C:/_bzl/zo2y7x2p/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, column 22, in patch
                ctx.patch(patchfile, strip)
Error in patch: Unable to load package for //third_party:mediapipe_opencv.diff: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - C:/users/user/third_party
ERROR: error loading package '': Encountered error while reading extension file 'apple/repositories.bzl': no such package '@build_bazel_rules_apple//apple': no such package '@com_google_mediapipe//third_party': Unable to load package for //third_party:mediapipe_opencv.diff: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - C:/users/user/third_party

**Comment by homuler** [comment]
> java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/zo2y7x2p/external/rules_python): The System Cannot find the File Specified

I guess you've not set  PATH correctly.
cf. https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/docker/windows/x86_64/Dockerfile#L16

Can you run `git` command?

**Comment by torreb1990** [comment]
Yes, It worked but now I have other issue:

ERROR: C:/users/user/mediapipeunityplugin-master/mediapipe_api/framework/formats/BUILD:98:17: Executing genrule //mediapipe_api/framework/formats:location_data_cs failed (Exit 1): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
mv: cannot stat 'bazel-out/x64_windows-opt/bin/LocationData.cs': No such file or directory

**Comment by homuler** [comment]
OK. Please describe the issue in [this format](https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/.github/ISSUE_TEMPLATE/build-installation-issue.md)

In addition to that, please run `python build.py build --desktop cpu --include_opencv_libs -vvv` and share the log.

**Comment by torreb1990** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):windows
Target (e.g. desktop cpu, android arm64):cpu
Bazel version:3.7.2
Python version:3.9.7
GCC/G++ version:
Unity version:2020.3.8f1

Describe the problem:

ERROR: C:/users/alvaro/mediapipeunityplugin-master/mediapipe_api/graphs/object_detection_3d/calculators/BUILD:20:17: Executing genrule //mediapipe_api/graphs/object_detection_3d/calculators:model_matrix_cs failed (Exit 1): bash.exe failed: error executing command


Steps to reproduce the issue:
cd C:\Users\user\MediaPipeUnityPlugin-master

set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC

set BAZEL_VC_FULL_VERSION=14.16.27023

set BAZEL_WINSDK_FULL_VERSION=10.0.20348.0

pip install virtualenv

virtualenv env

env\Scripts\activate

pip install numpy

set PYTHON_BIN_PATH=C:\Users\user\MediaPipeUnityPlugin-master\env\Scripts\python.exe

python build.py build --desktop cpu --include_opencv_libs -vvv

Full logs: 
[log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/7090021/log.txt)

**Comment by homuler** [comment]
I wonder if it's related to `PATH`, but I'm not sure.
Could you look into this log more closely?
```txt
mkdir -p bazel-out/x64_windows-opt/bin/Graphs/ObjectDetection3d
bazel-out/host/bin/external/com_google_protobuf/protoc.exe     --proto_path=.     --proto_path=bazel-out/x64_windows-opt/bin/Graphs/ObjectDetection3d     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/x64_windows-opt/bin/Graphs/ObjectDetection3d mediapipe/graphs/object_detection_3d/calculators/model_matrix.proto
mv bazel-out/x64_windows-opt/bin/Graphs/ObjectDetection3d/ModelMatrix.cs $(dirname bazel-out/x64_windows-opt/bin/mediapipe_api/graphs/object_detection_3d/calculators/ModelMatrix.cs)
```

This log corresponds to the following code.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/mediapipe_api/csharp_proto_src.bzl#L23-L32

This code compiles a `.proto` file into `.cs` file and moves the generated file to an appropriate directory.
However, in your environment, the target `.cs` file seems not to be generated.
I'd like to know if it's not generated actually or generated somewhere else, or `mv` command fails somewhat, etc...

For example, I think you can check if `protoc` runs successfully like this.
```diff
diff --git a/mediapipe_api/csharp_proto_src.bzl b/mediapipe_api/csharp_proto_src.bzl
index fe8fe9f..4b658b3 100644
--- a/mediapipe_api/csharp_proto_src.bzl
+++ b/mediapipe_api/csharp_proto_src.bzl
@@ -28,6 +28,8 @@ $(location @com_google_protobuf//:protoc) \
     --proto_path=$$(pwd)/external/com_google_protobuf/src \
     --proto_path=$$(pwd)/external/com_google_mediapipe \
     --csharp_out={outdir} {}
+echo $$?
+ls -alh {outdir}
 mv {outdir}/{outfile} $$(dirname $(location {outfile}))
 """.format(proto_src, outdir=outdir, outfile=csharp_out),
         tools = [
```

**Comment by homuler** [comment]
Close this issue for lack of activities.
If there is any new information, please reopen it.
