### ISSUE TITLE
How to get keypoints / landmarks from Mediapipe model 

### ISSUE THREAD

**Issue by mgarbade** [homuler/MediaPipeUnityPlugin#263]
I could successfully build binaries using a linux docker container and after that build an apk using Unity under Windows (Windows Unity Editor is not running  though). Anyways, next I'd like to interact with the model.

Where can I find the detected keypoints landmarks that the mediapipe pose model detects?

**Comment by homuler** [comment]
I'm sorry for the late reply.

In the sample app, those data can be accessed synchronously
https://github.com/homuler/MediaPipeUnityPlugin/blob/7bb877de4887ad4bf23c72b39649c41bb3650d54/Assets/Mediapipe/Samples/Scenes/Face%20Detection/FaceDetectionSolution.cs#L102
or asynchronously.
https://github.com/homuler/MediaPipeUnityPlugin/blob/7bb877de4887ad4bf23c72b39649c41bb3650d54/Assets/Mediapipe/Samples/Scenes/Face%20Detection/FaceDetectionSolution.cs#L111

In general, you can get outputs from MediaPipe by registering `OutputStreamPoller` (synchronously) or registering callbacks (asynchronously).

See 
https://github.com/homuler/MediaPipeUnityPlugin/blob/7bb877de4887ad4bf23c72b39649c41bb3650d54/Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs#L324-L333
and
https://github.com/homuler/MediaPipeUnityPlugin/blob/7bb877de4887ad4bf23c72b39649c41bb3650d54/Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs#L351-L353
for more details.

I'll add some more documentation later.

**Comment by sho1003s** [comment]
Excuse me.
I want to extract landmarks from holistic and reflect them in my avatar in Unity. However, I didn't know how to get the landmark. Would you please teach me?

**Comment by homuler** [comment]
I don't know if I'm understanding what you're asking, but if you're asking where you can access the landmark data in the Holistic sample scene, you can get them synchronously here
https://github.com/homuler/MediaPipeUnityPlugin/blob/9c3db9ad6872d5dfac411aec37d51ec1950e7fc1/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs#L129

or read them in callbacks,
https://github.com/homuler/MediaPipeUnityPlugin/blob/9c3db9ad6872d5dfac411aec37d51ec1950e7fc1/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs#L140-L142
that are registered here.
https://github.com/homuler/MediaPipeUnityPlugin/blob/9c3db9ad6872d5dfac411aec37d51ec1950e7fc1/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs#L92

**Comment by nenenkosi** [comment]
MediaPipeUnityPlugin/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs

Lines 140 to 142 in 9c3db9a

 void OnPoseDetectionOutput(Detection poseDetection) { 
   poseDetectionAnnotationController.DrawLater(poseDetection); 
 }

**Comment by nenenkosi** [comment]
@homuler I just try the above solution to get the keypoints / landmarks from my objectron and I get the data as in the below image
<img width="1166" alt="Screenshot 2021-09-30 at 07 45 06" src="https://user-images.githubusercontent.com/34231866/135394405-f67af5c7-ef8b-492a-9de4-e2ce720ae9e4.png">

but when I try and get the values inside the object I keep getting this error below.  What am I doing wrong coz I tried getting the annotations,scale ,translation and rotation they are all giving me the same error  
<img width="1170" alt="Screenshot 2021-09-30 at 07 48 21" src="https://user-images.githubusercontent.com/34231866/135395099-cebb1cce-e205-4b8b-8e67-57d41626ed9c.png">

**Comment by homuler** [comment]
@nenenkosi I think you should use VS Code or some IDE and enable code completions.
`FrameAnnotation#annotations` -> `FrameAnnotation#Annotations` is correct.
https://github.com/homuler/MediaPipeUnityPlugin/blob/9c3db9ad6872d5dfac411aec37d51ec1950e7fc1/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/CuboidListAnnotation.cs#L59

**Comment by nenenkosi** [comment]
@homuler Thanks for your help the problem was that I was using FrameAnnotation.annotations with a small letter "**a**" coz that what the console showed me thanks a lot man

**Comment by sho1003s** [comment]
Thanks for your help. I tried to get keypoints / landmarks but I couldn't get these.
so sorry.. could you teach me more details please?

about  MediaPipeUnityPlugin/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs
I understood 'value' has keypoints and landmarks. After that  each AnnotationController drawing to use value.
So these value (value.faceLandmarks, value.poseLandmarks etc..)have keypoints and landmarks right?
I thought so and tried to get it using Debug.Log, but it only showed the type.
I think it was caused by the description of Debug.Log, but I could not solve it.

Could you please tell me if it fits the current way and how to write it to output the value?

**Comment by sho1003s** [comment]
So sorry for lack of study.
I don’t know what does enable code completions mean?

I tried Debug.Log(value.poseLandmarks) but I didn’t get landmarks…

I wrote Debug.log(“a”) 134 lines (under the poseRoiAnnotationController.Drawnow),but I couldn’t get a.

**Comment by laukaho** [comment]
![image](https://user-images.githubusercontent.com/13497872/135950085-9e0b12b4-2565-4525-b761-635b70d586f0.png)
I think you don't need to do anything inside the AnnotationController to get the landmarks.
What you have to do is register your own function to above UnityEvent from the graphRunner. Then, you can get your landmarks .

> So sorry for lack of study. I don’t know what does enable code completions mean?
> 
> I tried Debug.Log(value.poseLandmarks) but I didn’t get landmarks…
> 
> I wrote Debug.log(“a”) 134 lines (under the poseRoiAnnotationController.Drawnow),but I couldn’t get a.

**Comment by sho1003s** [comment]
@laukaho Thank you for your help. To be honest, I don't really understand.
For example, suppose I have a function in my program file to get a landmark. Is it possible to store the landmark value in the function by registering the function in the if statement of the photo?

**Comment by laukaho** [comment]
@sho1003s 
I think you have to study a bit about `UnityEvent` and `Action` in C#

[https://docs.unity3d.com/ScriptReference/Events.UnityEvent.html](url)
[https://docs.microsoft.com/en-us/dotnet/api/system.action-1?view=net-5.0](url)

**Comment by k0hh2** [comment]
'Debug.Log (value.poseLandmarks)'
I was able to display the landmarks with Debug.Log

' (value.poseLandmarks [0])'
But I try to retrieve only one with, I got the following error.

'Cannot apply indexing with [] to an expression of type'NormalizedLandmarkList''

How can I specify the part such as the keypoint of the nose and take it out?

**Comment by k0hh2** [comment]
`Debug.Log (value.poseLandmarks)`
I was able to display the landmarks with Debug.Log

`Debug.Log (value.poseLandmarks[0])`
But I try to retrieve only one with, I got the following error.

`Cannot apply indexing with [] to an expression of type'NormalizedLandmarkList`

How can I specify the part such as the keypoint of the nose and take it out?

**Comment by GearType** [comment]
Thank you for all of the development. It would be very appreciated to have a working code sample or unity scene that focuses on retrieving the landmark data as usable 3D coordinates, and perhaps an example of using that data to manipulate an object in a unity 3d scene.

**Comment by GearType** [comment]
> Cannot apply indexing with [] to an expression of type'NormalizedLandmarkList

Same issue...been attempting to retrieve individual landmark coordinates. In my case, was using 'Debug.Log(leftHandLandmarks);' within 'public HolisticTrackingValue FetchNextValue() {}' of 'HolisticTrackingGraph.cs', or 'Debug.Log (value.leftHandLandmarks);'  within 'if (runningMode == RunningMode.Sync) {}' (with mode set to sync in the 'Solution' GameObject) of HolisticTrackingSolution.cs

I am able to get the entire list of 21 landmarks as expected for the hand model. However, I cannot figure out how to get individual landmark coordinates.

Any help here would be appreciated.

**Comment by homuler** [comment]
It's easy to resolve compilation errors if you have code completion enabled in your editor (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/263#issuecomment-930946759).

If you're using VS Code, see below links.
https://code.visualstudio.com/docs/other/unity
https://forum.unity.com/threads/intellisense-not-working-for-visual-studio-code.812040/#post-5858986

> with mode set to sync in the 'Solution' GameObject) of HolisticTrackingSolution.cs

Running mode can be switched at runtime from UI (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-932074718).

**Comment by ROBYER1** [comment]
In our case I just went through the UI Canvas to find the annotation controller drawing the dots on screen, simply made the private list of their locations public instead then read the position values from that.

**Comment by k0hh2** [comment]
> 私たちの場合、UIキャンバスを調べて、画面上にドットを描画しているアノテーションコントローラーを見つけ、その場所のプライベートリストを公開してから、そこから位置の値を読み取りました。

Thank you.
Can this process get the z coordinate?

**Comment by ROBYER1** [comment]
> > 私たちの場合、UIキャンバスを調べて、画面上にドットを描画しているアノテーションコントローラーを見つけ、その場所のプライベートリストを公開してから、そこから位置の値を読み取りました。
> 
> Thank you. Can this process get the z coordinate?

Yes, if you go and check the positions you will get the x, y, and z, the same goes for the 3D pose example in the PoseTracking scene if you make the private list of points public you can access them easily. Please try this.

**Comment by mgarbade** [comment]
I tried to retrieve pose keypoints by adding an Action inside the "PoseTrackingSolution.cs"

```
    public event Action<LandmarkList> MediapipePredictionsReceived;
```

This only works in "Sync" RunningMode but not in "Async" RunningMode.

Here is the code I added to [these lines](https://github.com/homuler/MediaPipeUnityPlugin/blob/6b8c6743f23539f7604e74dc260b01e0f58f1707/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/PoseTrackingSolution.cs#L122-L125)

```
    private void OnPoseWorldLandmarksOutput(object stream, OutputEventArgs<LandmarkList> eventArgs)
    {
        // send skeleton to ailib
        if (eventArgs.value != null)
        {
            MediapipePredictionsReceived?.Invoke (eventArgs.value);
        }
        _poseWorldLandmarksAnnotationController.DrawLater(eventArgs.value);
    }
```

This leads to the following error:

```
MediaPipeException: FAILED_PRECONDITION: Graph has errors: 
UnityEngine.UnityException: get_realtimeSinceStartup can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
  at (wrapper managed-to-native) UnityEngine.Time.get_realtimeSinceStartup()
  at Nukklear.myApp.AILib.MediaPipePersonRecognition.OnMediapipePredictionsReceived (Mediapipe.LandmarkList poseWorldLandmarks) [0x0000a] in C:\Users\garbade\Git\myworkspace\myApp_homuler\myApp\Assets\myApp\Scripts\AILib\impl\MediaPipePersonRecognition.cs:47 
  at Mediapipe.Unity.PoseTracking.PoseTrackingSolution.OnPoseWorldLandmarksOutput (System.Object stream, Mediapipe.Unity.OutputEventArgs`1[TValue] eventArgs) [0x0000f] in C:\Users\garbade\Git\myworkspace\myApp_homuler\myApp\Assets\MediaPipeUnity\Samples\Scenes\Pose Tracking\PoseTrackingSolution.cs:137 
  at Mediapipe.Unity.OutputStream`2[TPacket,TValue].InvokeIfOutputStreamFound (System.IntPtr graphPtr, System.Int32 streamId, System.IntPtr packetPtr) [0x0009c] in C:\Users\garbade\Git\myworkspace\myApp_homuler\myApp\Packages\com.github.homuler.mediapipe\Runtime\Scripts\Unity\OutputStream.cs:376 
Mediapipe.Status.AssertOk () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:48)
Mediapipe.Unity.GraphRunner.AddPacketToInputStream[T] (System.String streamName, Mediapipe.Packet`1[TValue] packet) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:183)
Mediapipe.Unity.GraphRunner.AddTextureFrameToInputStream (System.String streamName, Mediapipe.Unity.TextureFrame textureFrame) (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:200)
Mediapipe.Unity.PoseTracking.PoseTrackingGraph.AddTextureFrameToInputStream (Mediapipe.Unity.TextureFrame textureFrame) (at Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/PoseTrackingGraph.cs:117)
Mediapipe.Unity.PoseTracking.PoseTrackingSolution.AddTextureFrameToInputStream (Mediapipe.Unity.TextureFrame textureFrame) (at Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/PoseTrackingSolution.cs:89)
Mediapipe.Unity.ImageSourceSolution`1+<Run>d__12[T].MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs:103)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d3b66f0ad4e34a55b6ef91ab84878193>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

**Comment by homuler** [comment]
@mgarbade Please read the error message.

> UnityEngine.UnityException: get_realtimeSinceStartup can only be called from the main thread.

So you can't call `Time.realTimeSinceStartup` from a thread other than the main thread, that's why your code doesn't work in Async mode.

I've not written a tutorial on how to use asynchronous callbacks, so please refer to [this article](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Advanced-Topics#unityengineunityexception--can-only-be-called-from-the-main-thread) for now.

**Comment by VimalMollyn** [comment]
I am able to get the poseLandmarks ([0,1]) using a synchronous call. How can I convert these to image coordinates?

**Comment by dayowoo** [comment]
> @homuler I just try the above solution to get the keypoints / landmarks from my objectron and I get the data as in the below image <img alt="Screenshot 2021-09-30 at 07 45 06" width="1166" src="https://user-images.githubusercontent.com/34231866/135394405-f67af5c7-ef8b-492a-9de4-e2ce720ae9e4.png">
> 
> but when I try and get the values inside the object I keep getting this error below. What am I doing wrong coz I tried getting the annotations,scale ,translation and rotation they are all giving me the same error <img alt="Screenshot 2021-09-30 at 07 48 21" width="1170" src="https://user-images.githubusercontent.com/34231866/135395099-cebb1cce-e205-4b8b-8e67-57d41626ed9c.png">

Hello. Can you explain how to look at the log?
