### ISSUE TITLE
Docker for Windows (experimental) - stuck at "installing unzip..."

### ISSUE THREAD

**Issue by FUBAR2077** [homuler/MediaPipeUnityPlugin#266]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):
- Target (e.g. desktop cpu, android arm64):
- Bazel version:
- Python version:
- GCC/G++ version:
- Unity version:
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
I try to setup Docker for Windows (experimental) package but it gets stuck on "installing unzip..." step

**Steps to reproduce the issue**
just
`docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile`
and wait as it gets stuck

**Full logs**

> ###################################################################
> #                                                                 #
> #                                                                 #
> #                   C   A   U   T   I   O   N                     #
> #                                                                 #
> #                  This is first start of MSYS2.                  #
> #       You MUST restart shell to apply necessary actions.        #
> #                                                                 #
> #                                                                 #
> ###################################################################
> 
> 
> :: Synchronizing package databases...
> downloading mingw32.db...
> downloading mingw32.db.sig...
> downloading mingw64.db...
> downloading mingw64.db.sig...
> downloading ucrt64.db...
> downloading ucrt64.db.sig...
> downloading clang64.db...
> downloading clang64.db.sig...
> downloading msys.db...
> downloading msys.db.sig...
> :: Starting core system upgrade...
> resolving dependencies...
> warning: terminate other MSYS2 programs before proceeding
> looking for conflicting packages...
> 
> Packages (4) filesystem-2021.06-1  msys2-runtime-3.2.0-15  pacman-6.0.0-7  pacman-mirrors-20210706-1
> 
> Total Download Size:    8.59 MiB
> Total Installed Size:  43.22 MiB
> Net Upgrade Size:       0.82 MiB
> 
> :: Proceed with installation? [Y/n]
> :: Retrieving packages...
> downloading filesystem-2021.06-1-x86_64.pkg.tar.zst...
> downloading msys2-runtime-3.2.0-15-x86_64.pkg.tar.zst...
> downloading pacman-mirrors-20210706-1-any.pkg.tar.zst...
> downloading pacman-6.0.0-7-x86_64.pkg.tar.zst...
> checking keyring...
> checking package integrity...
> loading package files...
> checking for file conflicts...
> checking available disk space...
> :: Processing package changes...
> upgrading filesystem...
> upgrading msys2-runtime...
> upgrading pacman-mirrors...
> upgrading pacman...
> :: To complete this update all MSYS2 processes including this terminal will be closed. Confirm to proceed [Y/n]
> :: Synchronizing package databases...
>  mingw32 downloading...
>  mingw64 downloading...
>  ucrt64 downloading...
>  clang64 downloading...
>  msys downloading...
> :: Starting core system upgrade...
>  there is nothing to do
> :: Starting full system upgrade...
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (34) bsdtar-3.5.1-2  ca-certificates-20210119-2  curl-7.78.0-1  dash-0.5.11.4-1  glib2-2.68.4-1  gnupg-2.2.29-1  grep-3.6-1  icu-69.1-1  info-6.8-1  less-590-1  libcurl-7.78.0-1  libedit-20210714_3.1-1  libexpat-2.4.1-1  libgcrypt-1.9.3-1  libgnutls-3.7.2-1  libgpgme-1.16.0-1  libhogweed-3.7.3-1  libidn2-2.3.2-1  libksba-1.6.0-1  libnettle-3.7.3-1  libnghttp2-1.44.0-1  libopenssl-1.1.1.l-1  libp11-kit-0.24.0-1  libpcre-8.45-1  libpcre2_8-10.37-1  libreadline-8.1.001-1  libsqlite-3.36.0-2  libxml2-2.9.12-2  nano-5.8-1  nettle-3.7.3-1  openssl-1.1.1.l-1  p11-kit-0.24.0-1  pacman-contrib-1.4.0-2  wget-1.21.1-3
> 
> Total Download Size:   28.73 MiB
> Total Installed Size:  93.02 MiB
> Net Upgrade Size:       0.49 MiB
> 
> :: Proceed with installation? [Y/n]
> :: Retrieving packages...
>  libexpat-2.4.1-1-x86_64 downloading...
>  libhogweed-3.7.3-1-x86_64 downloading...
>  libnettle-3.7.3-1-x86_64 downloading...
>  icu-69.1-1-x86_64 downloading...
>  libreadline-8.1.001-1-x86_64 downloading...
>  libxml2-2.9.12-2-x86_64 downloading...
>  bsdtar-3.5.1-2-x86_64 downloading...
>  libopenssl-1.1.1.l-1-x86_64 downloading...
>  openssl-1.1.1.l-1-x86_64 downloading...
>  libpcre-8.45-1-x86_64 downloading...
>  libgcrypt-1.9.3-1-x86_64 downloading...
>  glib2-2.68.4-1-x86_64 downloading...
>  less-590-1-x86_64 downloading...
>  info-6.8-1-x86_64 downloading...
>  libp11-kit-0.24.0-1-x86_64 downloading...
>  p11-kit-0.24.0-1-x86_64 downloading...
>  ca-certificates-20210119-2-any downloading...
>  libidn2-2.3.2-1-x86_64 downloading...
>  libnghttp2-1.44.0-1-x86_64 downloading...
>  libsqlite-3.36.0-2-x86_64 downloading...
>  libedit-20210714_3.1-1-x86_64 downloading...
>  libcurl-7.78.0-1-x86_64 downloading...
>  curl-7.78.0-1-x86_64 downloading...
>  grep-3.6-1-x86_64 downloading...
>  dash-0.5.11.4-1-x86_64 downloading...
>  libgnutls-3.7.2-1-x86_64 downloading...
>  libksba-1.6.0-1-x86_64 downloading...
>  nettle-3.7.3-1-x86_64 downloading...
>  gnupg-2.2.29-1-x86_64 downloading...
>  libgpgme-1.16.0-1-x86_64 downloading...
>  libpcre2_8-10.37-1-x86_64 downloading...
>  nano-5.8-1-x86_64 downloading...
>  pacman-contrib-1.4.0-2-x86_64 downloading...
>  wget-1.21.1-3-x86_64 downloading...
> checking keyring...
> checking package integrity...
> loading package files...
> checking for file conflicts...
> checking available disk space...
> :: Processing package changes...
> upgrading libexpat...
> upgrading libhogweed...
> upgrading libnettle...
> upgrading icu...
> upgrading libreadline...
> upgrading libxml2...
> upgrading bsdtar...
> upgrading libopenssl...
> upgrading openssl...
> upgrading libpcre...
> upgrading libgcrypt...
> upgrading glib2...
> upgrading less...
> upgrading info...
> upgrading libp11-kit...
> upgrading p11-kit...
> upgrading ca-certificates...
> upgrading libidn2...
> upgrading libnghttp2...
> upgrading libsqlite...
> upgrading libedit...
> upgrading libcurl...
> upgrading curl...
> upgrading grep...
> upgrading dash...
> upgrading libgnutls...
> upgrading libksba...
> upgrading nettle...
> upgrading gnupg...
> ==> Appending keys from msys2.gpg...
> ==> Locally signing trusted keys in keyring...
> ==> Importing owner trust values...
> ==> Disabling revoked keys in keyring...
> ==> Updating trust database...
> gpg: next trustdb check due at 2022-01-23
> upgrading libgpgme...
> upgrading libpcre2_8...
> upgrading nano...
> upgrading pacman-contrib...
> upgrading wget...
> :: Running post-transaction hooks...
> (1/1) Updating the info directory file...
> :: Synchronizing package databases...
>  mingw32 downloading...
>  mingw64 downloading...
>  ucrt64 downloading...
>  clang64 downloading...
>  msys downloading...
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (35) expat-2.4.1-1  heimdal-7.7.0-2  openssh-8.6p1-1  perl-Authen-SASL-2.16-2  perl-Clone-0.45-2  perl-Convert-BinHex-1.125-1  perl-Encode-Locale-1.05-1  perl-Error-0.17029-1  perl-File-Listing-6.14-1  perl-HTML-Parser-3.76-1  perl-HTML-Tagset-3.20-2  perl-HTTP-Cookies-6.10-1  perl-HTTP-Daemon-6.12-1  perl-HTTP-Date-6.05-1  perl-HTTP-Message-6.32-1  perl-HTTP-Negotiate-6.01-2  perl-IO-HTML-1.004-1  perl-IO-Socket-SSL-2.071-1  perl-IO-Stringy-2.113-1  perl-LWP-MediaTypes-6.04-1  perl-MIME-tools-5.509-1  perl-MailTools-2.21-1  perl-Net-HTTP-6.21-1  perl-Net-SMTP-SSL-1.04-1  perl-Net-SSLeay-1.90-1  perl-TermReadKey-2.38-2  perl-TimeDate-2.33-1  perl-Try-Tiny-0.30-1  perl-URI-5.09-1  perl-WWW-RobotRules-6.02-2  perl-libwww-6.55-1  vim-8.2.3182-1  git-2.33.0-1  patch-2.7.6-1  unzip-6.0-2
> 
> Total Download Size:   16.50 MiB
> Total Installed Size:  91.35 MiB
> 
> :: Proceed with installation? [Y/n]
> :: Retrieving packages...
>  expat-2.4.1-1-x86_64 downloading...
>  vim-8.2.3182-1-x86_64 downloading...
>  heimdal-7.7.0-2-x86_64 downloading...
>  openssh-8.6p1-1-x86_64 downloading...
>  perl-Error-0.17029-1-any downloading...
>  perl-Authen-SASL-2.16-2-any downloading...
>  perl-Encode-Locale-1.05-1-any downloading...
>  perl-HTTP-Date-6.05-1-any downloading...
>  perl-File-Listing-6.14-1-any downloading...
>  perl-HTML-Tagset-3.20-2-any downloading...
>  perl-Clone-0.45-2-x86_64 downloading...
>  perl-IO-HTML-1.004-1-any downloading...
>  perl-LWP-MediaTypes-6.04-1-any downloading...
>  perl-URI-5.09-1-any downloading...
>  perl-HTTP-Message-6.32-1-any downloading...
>  perl-HTML-Parser-3.76-1-x86_64 downloading...
>  perl-HTTP-Cookies-6.10-1-any downloading...
>  perl-HTTP-Daemon-6.12-1-any downloading...
>  perl-HTTP-Negotiate-6.01-2-any downloading...
>  perl-Net-HTTP-6.21-1-any downloading...
>  perl-WWW-RobotRules-6.02-2-any downloading...
>  perl-Try-Tiny-0.30-1-any downloading...
>  perl-libwww-6.55-1-any downloading...
>  perl-TimeDate-2.33-1-any downloading...
>  perl-MailTools-2.21-1-any downloading...
>  perl-IO-Stringy-2.113-1-any downloading...
>  perl-Convert-BinHex-1.125-1-any downloading...
>  perl-MIME-tools-5.509-1-any downloading...
>  perl-Net-SSLeay-1.90-1-x86_64 downloading...
>  perl-IO-Socket-SSL-2.071-1-any downloading...
>  perl-Net-SMTP-SSL-1.04-1-any downloading...
>  perl-TermReadKey-2.38-2-x86_64 downloading...
>  git-2.33.0-1-x86_64 downloading...
>  patch-2.7.6-1-x86_64 downloading...
>  unzip-6.0-2-x86_64 downloading...
> checking keyring...
> checking package integrity...
> loading package files...
> checking for file conflicts...
> checking available disk space...
> :: Processing package changes...
> installing expat...
> installing vim...
> installing heimdal...
> installing openssh...
> installing perl-Error...
> installing perl-Authen-SASL...
> installing perl-Encode-Locale...
> installing perl-HTTP-Date...
> installing perl-File-Listing...
> installing perl-HTML-Tagset...
> installing perl-Clone...
> installing perl-IO-HTML...
> installing perl-LWP-MediaTypes...
> installing perl-URI...
> installing perl-HTTP-Message...
> installing perl-HTML-Parser...
> installing perl-HTTP-Cookies...
> installing perl-HTTP-Daemon...
> installing perl-HTTP-Negotiate...
> installing perl-Net-HTTP...
> installing perl-WWW-RobotRules...
> installing perl-Try-Tiny...
> installing perl-libwww...
> Optional dependencies for perl-libwww
>     perl-LWP-Protocol-https: for https:// url schemes
> installing perl-TimeDate...
> installing perl-MailTools...
> installing perl-IO-Stringy...
> installing perl-Convert-BinHex...
> module test... pass.
> installing perl-MIME-tools...
> installing perl-Net-SSLeay...
> installing perl-IO-Socket-SSL...
> installing perl-Net-SMTP-SSL...
> installing perl-TermReadKey...
> installing git...
> Optional dependencies for git
>     python: various helper scripts
>     subversion: git svn
> installing patch...
> Optional dependencies for patch
>     ed: for patch -e functionality
> installing unzip...

**Additional context**
Maybe internal container MSYS2 shell is required?

```
#This is first start of MSYS2.                  #
#       You MUST restart shell to apply necessary actions.        #
#
```

**Comment by homuler** [comment]
Follow this instruction, please.
https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor

> This process will hang when MSYS2 is being installed.
If this issue occurs, remove C:\ProgramData\Docker\tmp\hcs*\Files\$Recycle.Bin\ manually (hcs* is random name).
cf. https://github.com/docker/for-win/issues/8910

**Comment by FUBAR2077** [comment]
sorry... totally missed this, thank you :)
