### ISSUE TITLE
Need help for gestures implementation with MediaPipe Pose tracking using Unity and a Web camera.

### ISSUE THREAD

**Issue by UnityQueriesAsk** [homuler/MediaPipeUnityPlugin#267]
Hi, Thank you so much for the Plugin.

I am going to use this MediaPipe Unity plugin for my project. In that project I need to implement Jump, Run, SwipeLeft, SwipeRight and etc gestures with Mediapipe Pose tracking using a Web camera.

Can you please confirm that the Jump, Run, SwipeLeft, SwipeRight, and etc gestures are possible with Mediapipe Pose tracking?

If possible can you please help me or share some of the references for the above gestures implementation using Unity.

Thanks in advance.

**Comment by ROBYER1** [comment]
Have you tried monitoring the angles and distances between the on screen tracked body points in the pose sample? That is how I am doing this and I would advise to do the same.
