### ISSUE TITLE
Syntax error when running build ubuntu 18.04

### ISSUE THREAD

**Issue by Hakazaba** [homuler/MediaPipeUnityPlugin#268]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Linux ubuntu 18.04
- Target (e.g. desktop cpu, android arm64): desktop linux
- Bazel version: 4.2.1
- Python version: 2.7.17
- GCC/G++ version:7.5.0

When running python build.py build --desktop gpu -v
`desktop gpu -v
  File "build.py", line 46
    self.console.v(f"Running `{' '.join(command_list)}`")
                                                       ^
SyntaxError: invalid syntax
`

**Comment by LGuilhermeRodrigues** [comment]
According to the README file, you should use Python >= 3.9.0

**Comment by Hakazaba** [comment]
Thanks, new it was something dumb
