### ISSUE TITLE
Objectron support possible?

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#27]
Will you be investigating MediaPipe Objectron integration at some point?

**Comment by yosun** [comment]
there should probably be a way to generalize support for different models for this similar to OpenCVForUnity's DNN modules?

**Comment by homuler** [comment]
I'm sorry for the late reply.
I read the source code in the official repository just now, and I think it can be implemented if it's unnecessary to annotate the result visually on Unity (that is, plugin renders the image MediaPipe generates directly).

**Comment by kitmek1** [comment]
C:\Users\kitme\OneDrive\Desktop\New folder (2)\MediaPipeUnityPlugin>make cpu
./.build/protobuf-3.13.0/csharp/buildall.sh
process_begin: CreateProcess(NULL, bash C:\Users\kitme\OneDrive\Desktop\New folder (2)\MediaPipeUnityPlugin\.build\protobuf-3.13.0\csharp\buildall.sh, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:61: recipe for target '.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll' failed
mingw32-make.exe: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 2
i have this error can you help me?

**Comment by shivaylamba** [comment]
@midopooler also is facing issue in running this, apparently there is a config file missing which is not Loading objectron model in Unity. @homuler can you look into it
