### ISSUE TITLE
Help to resolve the below errors that I am getting in the command prompt.

### ISSUE THREAD

**Issue by UnityQueriesAsk** [homuler/MediaPipeUnityPlugin#272]
System information :
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10 Pro
- Target (e.g. desktop cpu, android arm64): Desktop cpu/gpu
- Bazel version: 4.2.0
- Python version: 3.9.6
- GCC/G++ version:
- Unity version: 2020.3.17f1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

Describe the problem :
Hi, I am getting the errors in the command prompt when I run the below command :
python build.py build --desktop cpu --include_opencv_libs -v

Full logs :

(env) D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin>python build.py build --desktop cpu -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=D:////MediaPipie-Pose-Tracking//MediaPipeUnityPlugin//env//Scripts//python.exe //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Can you please help me to resolve the above errors.

Thanks in advance.

**Comment by homuler** [comment]
Please run with `-vv` or `-vvv` and share the log.
```sh
python build.py build --desktop cpu --include_opencv_libs -vv
```

However, I strongly recommend you use Docker because your OS is Windows 10 Pro.
https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor

**Comment by UnityQueriesAsk** [comment]
Hi, Thank you so much for your response. I have run the both commands :

python build.py build --desktop cpu --include_opencv_libs -vv
python build.py build --desktop cpu --include_opencv_libs -vvv

I am getting the same errors that I got previously. I am attaching the logs, Please check : 

(env) D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin>python build.py build --desktop cpu --include_opencv_libs -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=D:////MediaPipie-Pose-Tracking//MediaPipeUnityPlugin//env//Scripts//python.exe --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


(env) D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin>python build.py build --desktop cpu --include_opencv_libs -vvv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=D:////MediaPipie-Pose-Tracking//MediaPipeUnityPlugin//env//Scripts//python.exe --verbose_failures --sandbox_debug //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\\MediaPipie-Pose-Tracking\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Can you please help me to solve these errors.

Thank you.

**Comment by homuler** [comment]
Have you installed bazel?
```sh
bazel --version
```

**Comment by UnityQueriesAsk** [comment]
Yes, I have installed bazel. I am using bazel version 4.2.0

D:\\MediaPipie-Pose-Tracking>bazel --version
bazel 4.2.0

**Comment by homuler** [comment]
Hmm... it's sure that `bazel` path is not resolved from Python, but I don't know why if you set the path to `%PATH%`.
If there is one thing that is suspicious, it is that the Python being run and the Python being set to `PYTHON_BIN_PATH` are different.

However, I don't want to waste time supporting a problem that won't occur if you use Docker, so please use Docker if you can't solve the problem on your own.

**Comment by UnityQueriesAsk** [comment]
I am attaching my python path, Please check once : 

C:\Users\>where python
C:\Users\\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\\AppData\Local\Programs\Python\Python39\python.exe

Sure, I will use the Docker. Can I build the .exe file from Unity If I use the Docker?

Thanks.

**Comment by Thaina** [comment]
I am not proficient in python but I try to hack and log the error in those line directly like this
![image](https://user-images.githubusercontent.com/1042507/133184132-25649165-d610-47b1-b620-e5b89adc655c.png)

And it seem like this maybe a bug in subprocess lib itself that it not split `bazel` from the args into executable. So executable is `none` and not found

**Comment by Thaina** [comment]
Manually add `shell=True` here seem to let me run bazel

![image](https://user-images.githubusercontent.com/1042507/133185012-ce6456f5-496b-4d45-92c1-e48cd63c3c4a.png)
