### ISSUE TITLE
Project opening with errors

### ISSUE THREAD

**Issue by deemonansh** [homuler/MediaPipeUnityPlugin#274]
**System information**

-OS: MacOS Big Sur 11.4
- Target: android arm64
- Bazel version: 4.2.1
- Python version: 3.9.7
- Unity version:2020.3.14

**Describe the problem**

Hello People I am trying to run example. I have cloned the project and also installed all the perquisites. but still after opening the project I am getting number of errors. specifically 77 issues every time I import it . I am adding screenshot for errors. can someone help me out?
<img width="1784" alt="Screenshot 2021-09-07 at 3 37 00 PM" src="https://user-images.githubusercontent.com/18465294/132330950-8853645a-f0c5-4b6b-a6d3-ad458e8a531f.png">

**Comment by AbdallahKATAIE** [comment]
I believe that's because you have the wrong Unity version.
You're supposed to run the project on 2020.3.8f1.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/186#issuecomment-851170261

**Comment by deemonansh** [comment]
> See [#186 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/186#issuecomment-851170261)

Thank you so much. Its solved it.

**Comment by deemonansh** [comment]
Its not working for android build

**Comment by homuler** [comment]
See https://github.com/google/mediapipe/issues/54#issuecomment-705064578

**Comment by deemonansh** [comment]
> See [google/mediapipe#54 (comment)](https://github.com/google/mediapipe/issues/54#issuecomment-705064578)

I have tried with this also.  getting the same error.

**Comment by homuler** [comment]
Will you try bazel 3.7.2?
In any case, build for iOS will fail with bazel 4.2.1.
https://github.com/homuler/MediaPipeUnityPlugin#prerequisites

**Comment by deemonansh** [comment]
I am building for android only

**Comment by homuler** [comment]
> python build.py build --desktop cpu --android arm64 --ios arm64 -v

It looks like you're building for iOS too, but even if you don't, just try it anyway.
If the problem continues, please file an issue to [bazel](https://github.com/bazelbuild/bazel).

**Comment by deemonansh** [comment]
Thanks build successfully after bazel version 3.7.2. but getting this error in unity editor.

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Timestamp.cs(23,26): error CS0115: 'Timestamp.Equals(Object)': no suitable method found to override

 can you tell me about this?

**Comment by homuler** [comment]
I'm not sure, but are you using a different branch or a different repository?
In fact, MediaPipe has a class called `Object`, the name of which conflicts with `System.Object`.
However, since this class does not exist in the master branch, I believe that this error does not occur usually.
