### ISSUE TITLE
Object_Detection_3D_cpu missing

### ISSUE THREAD

**Issue by AbdallahKATAIE** [homuler/MediaPipeUnityPlugin#276]
**System information**
- OS Platform and Distribution : Windows 10 Home
- Target: desktop cpu, android arm64
- Bazel version: 4.2.1
- Python version: 3.9.6
- Unity version:2020.3.8f1

**After following the steps for the windows Desktop/UnityEditor installation process, I ran the build command and it worked properly, then I opened the project with Unity and got the "missing libmediapipe_c.dll" error, which we're supposed to ignore as you mentioned here https://github.com/homuler/MediaPipeUnityPlugin/issues/260#issuecomment-909769036
However, my real problem is that when I run the project and test the ObjectDetection3D, it says that config is missing

![image](https://user-images.githubusercontent.com/49809099/132485005-4516aed3-4abf-4540-a283-07a3c9d8d883.png)

I looked in the entire repository and couldn't find the object_detection_3d_cpu.txt config file, how can I solve this issue or generate it if it needs to ?
**

**Steps to reproduce the issue**

- Open Unity Project and get this error :

![image](https://user-images.githubusercontent.com/49809099/132485478-d4b2a1ba-f088-4318-aec7-716614c3ceb0.png)

- Ignore it and run the project.

- Switch to Object Detection 3D :
![image](https://user-images.githubusercontent.com/49809099/132485747-55bdc163-bfa5-4dc0-8636-151fea90c70e.png)

-The camera stream freezes

Error logs :
![image](https://user-images.githubusercontent.com/49809099/132485361-95956ba9-bef2-4dfe-88f3-abace210c028.png)

**Comment by homuler** [comment]
Currently Objecton CPU is not supported.
https://github.com/homuler/MediaPipeUnityPlugin#example-graphs

It is implemented at [new-sample branch](https://github.com/homuler/MediaPipeUnityPlugin/tree/new-sample) and if there's no problem, it will be released this month.

**Comment by homuler** [comment]
#296 implemented this.
