### ISSUE TITLE
Custom Pose Graph?

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#277]
I have a modified graph of Pose which I made in .pbtxt format (I made the changes in the original mediapipe repository)
Now, I simply want it to run that custom graph inside this unity project. Please explain the whole procedure. @homuler 

Also, I have planned to make three files of `resources`, `Objects`, and `scripts` inside the Assets\Mediapipe\Samples\Graphs\CustomGraph. What else to do?

**Comment by homuler** [comment]
It depends on the contents of your configuration file.
If the input/output has not changed, then simply replacing [files](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Assets/Mediapipe/Samples/Graphs/PoseTracking/Resources) should work.

**Comment by midopooler** [comment]
> It depends on the contents of your configuration file.
If the input/output has not changed, then simply replacing files should work.

I have custom input/outputs in the .pbtxt files.
Even though I have replaced them in this unity project by changing the .pbtxt to .txt file format. What else do here?

**Comment by homuler** [comment]
The input/output type in C++ is important, so I can't give you specifics without knowing that.
In order to communicate data with MediaPipe, we need to use `Packet` class, which must be implemented for each corresponding type.
The work depends on whether the corresponding `Packet` has already been implemented or not.

**Comment by midopooler** [comment]
Thanks, that was helpful. I have some more points to ask here. 
As I can see, in the `WORKSPACE` file, mediapipe repository is being downloaded from an `http_archive` command in bazel. 
![image](https://user-images.githubusercontent.com/43686606/132840832-fdca7410-9431-4bb0-b6e3-2dd18d49328a.png)

Here, I am thinking of using `new_local_repository` command instead of `http_archive`, just as done for openCV. 
![image](https://user-images.githubusercontent.com/43686606/132840703-142362d8-6cf7-4a69-aeff-5a256fe6433a.png)
so that the local mediapipe repository (mine fork) can be used instead of downloading it from github release URL. 

What do you think, Am I going in the right direction?

**Comment by homuler** [comment]
Yes, you can use `new_local_repository`. https://github.com/homuler/MediaPipeUnityPlugin/issues/242#issuecomment-900249401 may be related.
However, if your forked repository is also hosted by GitHub, I think changing `urls` at `http_archive` is more portable than using `new _local_repository`.

**Comment by midopooler** [comment]
Thanks @homuler, your comment at #242 really helps. 
Also, to add, I see `PrepareDependentAssets` in all the graphs. I guess it generates .bytes files instead of accessing them. (Correct me if I'm wrong)

![image](https://user-images.githubusercontent.com/43686606/133621602-7ba4408f-99c7-4967-b9b2-94ba94284408.png)

What actually are these .bytes files? I see a lot of these files at `\Packages\com.github.homuler.mediapipe\Runtime\Resources` . If I have my custom input/output streams in my fork of mediapipe. Do I need to generate these files at runtime corresponding to the stream name or what is the actual process? I tried to dig in your code but couldn't find answer to this.

**Comment by homuler** [comment]
> I guess it generates .bytes files instead of accessing them. (Correct me if I'm wrong)

Yes, that's right.
Some calculators will read `*.tflite` or `.txt` files on which they are dependent, so we need to save those files beforehand.
cf. https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/tflite/tflite_tensors_to_classification_calculator.cc#L106

> What actually are these .bytes files?

Binary files those calculators depend on, and in most cases `*.tflite` files.
Unity does not accept arbitrary extensions for assets (cf. https://docs.unity3d.com/Manual/class-TextAsset.html), so I change extensions here.
https://github.com/homuler/MediaPipeUnityPlugin/blob/92dd55579f2faeabf49338974ddb1d15ae54b683/mediapipe_api/import_model.bzl#L52-L59

When you run `build.py` script, dependent model files will be zipped up and extracted under `Packages/com.github.homuler.mediapipe/Runtime/Resources`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/92dd55579f2faeabf49338974ddb1d15ae54b683/mediapipe_api/BUILD#L141-L171

> Do I need to generate these files at runtime corresponding to the stream name or what is the actual process?

As you inferred, you need to save dependent model files before running the graph by calling `PrepareDependentAsset`.
Even if you can't list them all exactly, you can usually know which files are missing by reading error logs.
If some dependent files don't exist under `Packages/com.github.homuler.mediapipe/Runtime/Resources`, you need to import them .

**Comment by homuler** [comment]
See https://stackoverflow.com/questions/16190387/when-applying-a-patch-is-there-any-way-to-resolve-conflicts
