### ISSUE TITLE
Docker Windows failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest

### ISSUE THREAD

**Issue by AbdallahKATAIE** [homuler/MediaPipeUnityPlugin#278]
**System information**
- OS Platform and Distribution : **Windows 10 Home (I installed Hyper-V manually and I was able to start docker afterwards)**
- Target: desktop cpu, android arm64
- Bazel version: 4.2.1
- Python version: 3.9.6
- Unity version:2020.3.8f1

So I've seen this, someone asked it before but there was no answer (maybe because he didn't do it in the correct format)

**Error log :**

```
C:\Users\katai\Desktop\Unity\MediaPipeUnityPlugin-master>docker build -t mediapipe_unity:windows . -f docker/windows/x86[+] Building 0.6s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                      0.0s
 => => transferring dockerfile: 32B                                                                              0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019                               0.5s
------
 > [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:1be9c8378b8c32d31538253a4b96169f5138a5f6d4c0a04e8d8f9a80b9ac8097: not found
```

**Steps to reproduce the issue**

cd into the repo and `docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile`

**Comment by homuler** [comment]
You need to [switch to windows container](https://docs.docker.com/desktop/windows/) first.
However, if you are using Windows 10 Home, I guess this feature is probably disabled whatever if you installed Hyper-V manually (https://docs.docker.com/desktop/windows/install/).

**Comment by homuler** [comment]
@AbdallahKATAIE Is it resolved?

**Comment by AbdallahKATAIE** [comment]
Yes thank you, can you please answer my new issue ? https://github.com/homuler/MediaPipeUnityPlugin/issues/293
It's not resolved.
