### ISSUE TITLE
Toggle graph processing in runtime

### ISSUE THREAD

**Issue by Aashutosh-Dabhade** [homuler/MediaPipeUnityPlugin#283]
Hi @homuler 
I am working on a project where I need hand tracking, pose detection, holistic and face mesh.
but I need them at different levels or scenes. I can toggle the graph rendering. but it runs in the background.
I want to pause the entire processing and enable it whenever I want.
for eg. If I want only pose and Hands, face mesh processing (not just rendering) should be disabled on runtime.
could you please suggest what should I do?

**Comment by homuler** [comment]
If you can stop the graph completely for a while, then call `CalculatorGraph#Stop` and dispose the `CalculatorGraph` instanse.
https://github.com/homuler/MediaPipeUnityPlugin/blob/92dd55579f2faeabf49338974ddb1d15ae54b683/Assets/Mediapipe/Samples/Scripts/DemoGraph.cs#L117-L131

When you'd like to run the graph again, then you can instantiate another graph with the same config.

If you don't want to dispose the instance, then you can  just leave the graph.
`CalculatorGraph` won't run if you don't pass input data to them.


See also [calculator_graph.h](https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/framework/calculator_graph.h).

**Comment by Aashutosh-Dabhade** [comment]
Hi @homuler ,
I tried your method and it stopped all the graphs, but as I mentioned, I need to toggle specific graphs in runtime.
I am trying to toggle it in this way...

```
public void StopFaceMesh()
    {
        faceMeshGraph.Stop();
    }
```
 ```
public void StartFaceMesh()
    {
        faceMeshGraph.StartRun();
    }

```
but I am getting this error (PFA image)
![issue mediapipe](https://user-images.githubusercontent.com/69786970/133078201-2c9303c4-2dc6-4dc9-b812-ce6d10aa4743.JPG)


how can I do it for specific graphs?

**Comment by homuler** [comment]
Have you read all the sentences?
Once you stopped the graph, you cannot restart it.
>  then call CalculatorGraph#Stop and dispose the CalculatorGraph instanse.

That is, you need to call `CalculatorGraph#Dispose` and you cannot access the instance again.
> When you'd like to run the graph again, then you can instantiate another graph with the same config.

So the following code is not allowed.
```cs
faceMeshGraph.Stop(); // pseudo code, since CalculatorGraph does not have a method named` Stop`.
// Do something
faceMeshGraph.StartRun();
```

The former method I mentioned above is like this.
```cs
var faceMeshGraph = new CalculatorGraph(config);
// Do something
// Stop
faceMeshGraph.CloseAllPacketSources().Assert();
faceMeshGraph.WaitUntilDone().Assert();
faceMeshGraph.Dispose();
faceMeshGraph = null;

// Do something
// When the faceMeshGraph is needed again
faceMeshGraph = new CalculatorGraph(config); // instantiate again with the same config
```

And the latter is like this.
```cs
var faceMeshGraph = new CalculatorGraph(config);

while (true) {
  // Unity's event loop
  faceMeshGraph.AddPacketToInputStream(inputStream, packet).Assert();
  // Do something
}
// When you'd like to stop the graph, just leave it.
// faceMeshGraph won't process data if you don't call `AddPacketToInputStream`

// When faceMeshGraph is needed again, reuse the instance.
faceMeshGraph.AddPacketToInputStream(inputStream, packet).Assert();
```

> but it runs in the background.

I'm not quite sure what you're having trouble with, but is it consuming a lot of resources in the background?

**Comment by Aashutosh-Dabhade** [comment]
Hi @homuler,
My platform is android, and one of my scene is quite heavy. I just need pose tracking in that scene.
when I keep holistic graph in the same scene, fps drops.

I have checked your solution as well. but I found another method where we can just simply change the graph from GraphSelector script.
and to toggle the entire mediapipe processing, I have used the following method from SceneDirector.cs

```
public void StartGraph() {
    if (graphRunner != null) {
      Debug.Log("The graph is already running");
      return;
    }

    if (IsGpuEnabled()) {
      SetupGpuResources();
    }
    graphRunner = StartCoroutine(RunGraph());
  }

 public void StopGraph() {
    if (graphRunner != null) {
      StopCoroutine(graphRunner);
      graphRunner = null;
    }

    if (graphContainer != null) {
      Destroy(graphContainer);
    }
  }
```

**Comment by elblogbruno** [comment]
Sorry to reopen the issue, but @Aashutosh-Dabhade how did you achieve to run multiple graphs at the same time?

**Comment by elblogbruno** [comment]
Ok got it working hehe!
