### ISSUE TITLE
Getting error in new-sample on Android app 

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#285]
**System information**
- OS Platform and Distribution - MacOS BigSur
- Target Platform:
- Mobile Device (if the target is Android or iOS): Android 11 Xiaomi note 10
- MediaPipeUnityPlugin version or commit id: new-sample

**Describe the current behavior**

All scenes working good in unity but in android camera working but all graphs not working and getting 

`09-16 14:05:50.212  6808  6832 E Unity   : FileNotFoundException: jar:file:///data/app/~~aQzDfWXS4HchzzvhOPC8ow==/com.rgbkod.shoesCal-smsV_PqGmkGZq1u_IkWGFg==/base.apk!/assets/face_detection_short_range.bytes is not found
09-16 14:05:50.212  6808  6832 E Unity   :   at Mediapipe.Unity.FileSystemResourceManager.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) [0x00000] in <00000000000000000000000000000000>:0 
09-16 14:05:50.212  6808  6832 E Unity   :   at Mediapipe.Unity.FaceDetection.FaceDetectionGraph.PrepareDependentAssets () [0x00000] in <00000000000000000000000000000000>:0 
09-16 14:05:50.212  6808  6832 E Unity   :   at Mediapipe.Unity.GraphRunner.Start () [0x00000] in <00000000000000000000000000000000>:0 
09-16 14:05:50.212  6808  6832 E Unity   : 
09-16 14:05:50.497  6808  6832 E Unity   : Unsupported destination format in Graphics.ConvertTexture (59). This is likely because the device does not support this format as a rendertarget format.
09-16 14:05:50.497  6808  6832 E Unity   : Mediapipe.Unity.FaceDetection.<Run>d__16:MoveNext()
09-16 14:05:50.497  6808  6832 E Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
09-16 14:05:50.497  6808  6832 E Unity   : 
09-16 14:05:50.497  6808  6832 E Unity   : [ line 1816976456]
09-16 14:05:50.497  6808  6832 E Unity   : 
09-16 14:05:50.508  6808  6832 E Unity   : MediaPipeException: INTERNAL: Graph has errors: 
09-16 14:05:50.508  6808  6832 E Unity   : Calculator::Open() for node "facedetectionshortrangegpu__inferencecalculator__facedetectionshortrangegpu__InferenceCalculator" failed: ; (resolved_path)!=(nullptr)pe_api/util/resource_util_custom.cc:18) 
09-16 14:05:50.508  6808  6832 E Unity   : Calculator::Open() for node "facedetectionfullrangegpu__inferencecalculator__facedetectionfullrangegpu__InferenceCalculator" failed: ; (resolved_path)!=(nullptr)pe_api/util/resource_util_custom.cc:18) 
09-16 14:05:50.508  6808  6832 E Unity   :   at Mediapipe.Status.AssertOk () [0x00000] in <00000000000000000000000000000000>:0 
09-16 14:05:50.508  6808  6832 E Unity   :   at Mediapipe.Unity.FaceDetection.FaceDetectionSolution+<Run>d__16.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
09-16 14:05:50.508  6808  6832 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
`

What should I do?

**Comment by emreboyraz0** [comment]
Could you help to solve problem please?

**Comment by homuler** [comment]
> What should I do?

I think you should wait for the next release, since this is a working branch (well, actually, I just pushed the fixed commit yesterday).

**Comment by emreboyraz0** [comment]
can not download new-sample again. Github only download master files. @homuler can you fix the link please?

**Comment by sahilshaikh-me** [comment]
From where do I get sample apk any know ?
