### ISSUE TITLE
excuse me. Could you help me please...

### ISSUE THREAD

**Issue by sho1003s** [homuler/MediaPipeUnityPlugin#286]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):Mac OS Catalina 10.15.7
- Target (e.g. desktop cpu, android arm64):desktop cpu
- Bazel version:4.2.1
- Python version:3.9.0
- GCC/G++ version:gcc 11.2.0
- Unity version:2020.3.14.f
- Android NDK version (if building for Android):nothing
- Xcode version (if building for iOS):nothing

**Describe the problem**
build error (CalledProcessError)
**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.
Thank you for disclosing a great plugin.
I tried the plug-in by referring to the READ.ME you disclosed. I cloned git under my home directory and proceeded with the steps for Mac OS. I got an error when I ran the last build command, and I didn't know the cause, so I asked a question.

usr/local/bin/nuget: line 2: mono: command not found
Traceback (most recent call last):
  File "/Users/w...ss/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/w...ss/MediaPipeUnityPlugin/build.py", line 116, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/Users/w...ss/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/Users/w...ss/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nuget', 'install', '-o', '.nuget', '-Source', 'https://api.nuget.org/v3/index.json']' returned non-zero exit status 127.

**Full logs**

we..s@Well...noMacBook-Pro MediaPipeUnityPlugin % python build.py build --desktop gpu --opencv=cmake -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/44c890cd46fd9aad2b3bf4b13c5f36d8cff795c3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /Users/w...ss/MediaPipeUnityPlugin/WORKSPACE:35:23: in <toplevel>
  /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_w...ssdd3515652988650c871d4e0387c89bd4/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "86bf1c24e8f859fb5c66d931f33dc8283427e7370d2b0d178658893bcd3c49e9"
DEBUG: Repository rules_cc instantiated at:
  /Users/w...ssMediaPipeUnityPlugin/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_w...ss/dd3515652988650c871d4e0387c89bd4/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 110.465s, Critical Path: 107.40s
INFO: 203 processes: 3 internal, 200 darwin-sandbox.
INFO: Build completed successfully, 203 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading protobuf dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
/usr/local/bin/nuget: line 2: mono: command not found
Traceback (most recent call last):
  File "/Users/w...ss/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/w...ss/MediaPipeUnityPlugin/build.py", line 116, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/Users/w...ss/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/Users/w...ss/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nuget', 'install', '-o', '.nuget', '-Source', 'https://api.nuget.org/v3/index.json']' returned non-zero exit status 127.

**Additional context**
<img width="1440" alt="スクリーンショット 2021-09-17 17 05 16" src="https://user-images.githubusercontent.com/69140548/133747654-64614cf0-fc67-4dc1-8c99-2f38f4c6110a.png">

**Comment by homuler** [comment]
How did you install `nuget`?

**Comment by sho1003s** [comment]
Thank you for your support.
I installed nuget to use brew command.
brew install nuget.

<img width="872" alt="スクリーンショット 2021-09-17 19 30 38" src="https://user-images.githubusercontent.com/69140548/133769118-154792ce-c5f6-4ce2-8580-7cc1b42b277c.png">
<img width="1070" alt="スクリーンショット 2021-09-17 19 31 08" src="https://user-images.githubusercontent.com/69140548/133769129-f626379e-04ee-470d-b4b5-97d615e958e5.png">

**Comment by homuler** [comment]
You're getting an error when installing `nuget`, right?
Run `brew link --overwrite mono` or follow https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference#macoslinux .

**Comment by sho1003s** [comment]
so sorry... 
I did command "brew link --overwrite mono" ,after that one more try building.
I think I've made it, but I got other error...



external/com_google_protobuf/src/google/protobuf/port_def.inc:151:44: note: expanded from macro 'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
9 warnings generated.
ERROR: /private/var/tmp/_bazel_wellness/dd3515652988650c871d4e0387c89bd4/external/rules_foreign_cc/toolchains/BUILD.bazel:71:10: BootstrapGNUMake external/rules_foreign_cc/toolchains/make [for host] failed: (Exit 1): bash failed: error executing command /bin/bash -c bazel-out/host/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

---------------------------------------------------------------------------------------

FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/wellness/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/wellness/MediaPipeUnityPlugin/build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "/Users/wellness/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/Users/wellness/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--copt', '-DMESA_EGL_NO_X11_HEADERS', '--copt', '-DEGL_NO_X11', '--@opencv//:switch=cmake', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

sorry,Since the result of the command is long, I made a video.


Uploading 画面収録 2021-09-17 21.22.15.mov…

**Comment by sho1003s** [comment]
so sorry...
I did command "brew link --overwrite mono" ,after that one more try building.
I think I've made it, but I got other error...

external/com_google_protobuf/src/google/protobuf/port_def.inc:151:44: note: expanded from macro 'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED attribute((deprecated))
^
9 warnings generated.
ERROR: /private/var/tmp/_bazel_wellness/dd3515652988650c871d4e0387c89bd4/external/rules_foreign_cc/toolchains/BUILD.bazel:71:10: BootstrapGNUMake external/rules_foreign_cc/toolchains/make [for host] failed: (Exit 1): bash failed: error executing command /bin/bash -c bazel-out/host/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

FAILED: Build did NOT complete successfully
Traceback (most recent call last):
File "/Users/wellness/MediaPipeUnityPlugin/build.py", line 392, in 
Argument().command().run()
File "/Users/wellness/MediaPipeUnityPlugin/build.py", line 135, in run
self._run_command(self._build_desktop_commands())
File "/Users/wellness/MediaPipeUnityPlugin/build.py", line 51, in _run_command
return subprocess.run(command_list, check=True)
File "/Users/wellness/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--copt', '-DMESA_EGL_NO_X11_HEADERS', '--copt', '-DEGL_NO_X11', '--@opencv//:switch=cmake', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.
[error command all.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/7185560/error.command.all.txt)

**Comment by homuler** [comment]
Will you try bazel 3.7.2?

**Comment by sho1003s** [comment]
Thank you for your support.
I did uninstall Bazel 4.2.1 &Install Bazel 3.7.2, after that I tried again.
I got other error but error code changed before.

ERROR: /private/var/tmp/_bazel_wellness/dd3515652988650c871d4e0387c89bd4/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/BUILD:266:11: C++ compilation of rule '@org_tensorflow//tensorflow/lite/delegates/gpu/gl:gl_shader' failed (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:16:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_shader.h:23:
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/portable_gl31.h:21:10: fatal error: 'EGL/egl.h' file not found
#include <EGL/egl.h>

[error command allV2.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/7189138/error.command.allV2.txt)

**Comment by homuler** [comment]
GPU is not supported on macOS, so please specify `python build.py build --desktop cpu --opencv=cmake -vv` instead.
https://github.com/homuler/MediaPipeUnityPlugin#platforms

**Comment by sho1003s** [comment]
Thank you so much for your support.
I tried python build.py build --desktop cpu --opencv=cmake -vv command.
I got other error that "BUILD:54:10 error executing shell command" ...

[error command allV3.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/7189300/error.command.allV3.txt)

**Comment by homuler** [comment]
What is the result of executing this command? (you need to [install OpenCV](https://github.com/homuler/MediaPipeUnityPlugin#macos) if you've not)
```sh
python build.py build --desktop cpu --opencv=local -vv
```

**Comment by sho1003s** [comment]
thank you for your support!
Maybe I could install MediapipeUnityPlugIn!
Is this correct?
[python build.py build --desktop cpu --opencv=local -vv log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/7190945/python.build.py.build.--desktop.cpu.--opencv.local.-vv.log.txt)

**Comment by homuler** [comment]
It looks fine to me.
I can't be sure, but you may need to install Xcode to use `--opencv=cmake`.
If you have time, it would be great if you could install Xcode and give it a try.

**Comment by sho1003s** [comment]
Thank you so much for your support.
I'll try to install Xcode.
