### ISSUE TITLE
CPU config file is missing in ObjectDetection3d/Resources

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#289]
I found that the CPU config file is missing for the ObjectDetection3D 
![image](https://user-images.githubusercontent.com/43686606/133993882-b9ef8b03-2cdd-428b-b09c-e58e2653c7e1.png)

I tried to assign it myself but I didn't find the file inside the resources folder either. 
![image](https://user-images.githubusercontent.com/43686606/133994063-67bd5835-40a4-42e5-a508-1a2a4bb9bf69.png)

Further, on running it gives me this error
![image](https://user-images.githubusercontent.com/43686606/133994006-183c3e5b-f2f6-4b05-a964-d099bff667d4.png)

Does it work only on GPU? (asking this since I used this command for the bazel `python build.py build --desktop cpu --include_opencv_libs -v`  ) Or I am missing something?

**Comment by homuler** [comment]
> Does it work only on GPU?

Yes. 
Please see https://github.com/homuler/MediaPipeUnityPlugin/issues/276#issuecomment-915234103 for more details.

**Comment by midopooler** [comment]
ohh I didn't got this issue when I searched "objectron". Thanks
