### ISSUE TITLE
Pre Build Pacakge

### ISSUE THREAD

**Issue by ali-najjar** [homuler/MediaPipeUnityPlugin#292]
**Request a pre-built package**

Hello. If possible, insert the pre-built version of the package. Using docker or build by the system itself may be difficult for some systems

For example, I have a problem with creating an Android plugin that is related to the system

**Comment by homuler** [comment]
There are no plans to distribute pre-built packages at this time, as they are not usable in a real environment.
Will you tell me a specific example of an environment where it's still difficult to build native libraries even with Docker?

**Comment by ali-najjar** [comment]
> There are no plans to distribute pre-built packages at this time, as they are not usable in a real environment.
> Will you tell me a specific example of an environment where it's still difficult to build native libraries even with Docker?

Thanks for answering
For example, I live in Iran and Google has restricted the access of the people of my country to its services
To build an Android plugin, I have to use different VPNs and this causes connection problems in different parts.

Of course, building packages is still possible. Especially using Docker has made the job easier. However, I thought maybe downloading pre-built packages might be cheaper

**Comment by homuler** [comment]
I thought about it, but if it's just a network problem, I think it's better to solve it on another layer, so I still don't plan to distribute pre-built packages.

> Of course, building packages is still possible.

Rather, if you have built it successfully, I think it would be better for you to distribute your pre-built binaries for others who are in a similar situation.
