### ISSUE TITLE
ARCore 

### ISSUE THREAD

**Issue by AbdallahKATAIE** [homuler/MediaPipeUnityPlugin#293]
**System information**
- OS Platform and Distribution : **Windows 10 Home (I installed Hyper-V manually and I was able to start docker afterwards)**
- Target: android arm64
- Bazel version: 4.2.1
- Python version: 3.9.6
- Unity version:2020.3.8f1

**Steps to reproduce the issue**
after I tested the build on my phone and everything worked fine, I installed ARCore and ARFoundation in the project because I want to add occlusion to my 3D shoe model.
Right after that I just added an XR object : 

![image](https://user-images.githubusercontent.com/49809099/134148777-3ee01772-9ff7-4e78-a366-7112821979b9.png)

Activating it is enough to give me the following error log : 
![image](https://user-images.githubusercontent.com/49809099/134148598-b0c12ffe-9a93-44b1-8733-a505137a6514.png)

What can I do to make ARCore work ?
Thanks in advance

**Comment by nenenkosi** [comment]
@AbdallahKATAIE first are you able to render and track your own shoe model with objectron graph and if yes then you can create your own shader for occlusion. 
But if you preferred using ARCore and ARFoundation for occlusion that’s fine to send me your email and I will send you the code for occlusion.

**Comment by AbdallahKATAIE** [comment]
@nenenkosi if I create my own shader for occlusion, will it take consideration of the lights in the environment I'm in ?
Please email me here : kataieabdallah@hotmail.com 
for the occlusion code and how to create a shader if possible.
Thank you!

**Comment by ROBYER1** [comment]
Does ARCore work in a separate scene by itself with no Mediapipe included? I would think the issue is that Mediapipe is already using the camera through the webcam script and ARCore is also trying to access the camera.

**Comment by GiovanniTurri** [comment]
@AbdallahKATAIE how have you managed to integrate AR Foundation in MediaPipe?
Thank you!

**Comment by AbdallahKATAIE** [comment]
> @AbdallahKATAIE how have you managed to integrate AR Foundation in MediaPipe? Thank you!

I managed to get everything working, including the full try-on project, the Occlusion Shader fix, Rotation, Translation, Scale matrix etc...
here's my email if you need them : kataieabdallah@hotmail.com

**Comment by NeerajMehta** [comment]
Hey, can you share how you make it work?

**Comment by AbdallahKATAIE** [comment]
Good Morning,
I’ve been actually selling it. Here are the products I’m selling :


  *   Detection
  *   Shoe Model superposition (rotation, position, scale)
  *   Occlusion Shader Fix + setup
  *   Firebase Integration (download shoe models from the internet)

Are you interested ?





Abdallah KATAIE
Unity3D VR/AR & Web MERN Software Engineer
______________________________________________
My Company:
https://thedmcorporation.netlify.app/
My Portfolio:
https://abdallahkataie.wordpress.com/
What’sApp Business: +33 6 33 93 79 37
www.linkedin.com/in/abdallah-kataie-09086b140/<http://www.linkedin.com/in/abdallah-kataie-09086b140/>
10 Square Des Caleïdes • 49000 - Angers, France


De : Neeraj Singh ***@***.***>
Envoyé le :11 October 2022 07:01
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [homuler/MediaPipeUnityPlugin] ARCore (#293)


Hey, can you share how you make it work?

**Comment by NeerajMehta** [comment]
I can buy but I need media pipeline with Face mesh and light estimation  from ARCore

**Comment by AbdallahKATAIE** [comment]
Alright,
So you’re buying the setup, correct ?






Abdallah KATAIE
Unity3D VR/AR & Web MERN Software Engineer
______________________________________________
My Company:
https://thedmcorporation.netlify.app/
My Portfolio:
https://abdallahkataie.wordpress.com/
What’sApp Business: +33 6 33 93 79 37
www.linkedin.com/in/abdallah-kataie-09086b140/<http://www.linkedin.com/in/abdallah-kataie-09086b140/>
10 Square Des Caleïdes • 49000 - Angers, France


De : Neeraj Singh ***@***.***>
Envoyé le :11 October 2022 08:27
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [homuler/MediaPipeUnityPlugin] ARCore (#293)


I can buy but I need media pipeline with Face mesh and light estimation from ARCore

**Comment by AbdallahKATAIE** [comment]
Hey,

Yeah, that wouldn’t be a problem, we will probably have to do it over Discord so you can share your screen, and I will tell you how to do it step by step and give you my project which is fully setup already.

I’ve been selling this service for 700$, If you’re really interested, please let me know which payment method do you prefer ? (bank transfer, Revolut, Paypal).







Abdallah KATAIE
Unity3D VR/AR & Web MERN Software Engineer
______________________________________________
My Company:
https://thedmcorporation.netlify.app/
My Portfolio:
https://abdallahkataie.wordpress.com/
What’sApp Business: +33 6 33 93 79 37
www.linkedin.com/in/abdallah-kataie-09086b140/<http://www.linkedin.com/in/abdallah-kataie-09086b140/>
10 Square Des Caleïdes • 49000 - Angers, France


De : Neeraj Singh ***@***.***>
Envoyé le :11 October 2022 16:56
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [homuler/MediaPipeUnityPlugin] ARCore (#293)


Yes setup means setting up of arcore basic face mesh with media pipe line.

**Comment by NeerajMehta** [comment]
Share me your skype Id

**Comment by AbdallahKATAIE** [comment]
Here’s my Skype ID :

kataieabdallah







Abdallah KATAIE
Unity3D VR/AR & Web MERN Software Engineer
______________________________________________
My Company:
https://thedmcorporation.netlify.app/
My Portfolio:
https://abdallahkataie.wordpress.com/
What’sApp Business: +33 6 33 93 79 37
www.linkedin.com/in/abdallah-kataie-09086b140/<http://www.linkedin.com/in/abdallah-kataie-09086b140/>
10 Square Des Caleïdes • 49000 - Angers, France


De : Neeraj Singh ***@***.***>
Envoyé le :11 October 2022 18:03
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [homuler/MediaPipeUnityPlugin] ARCore (#293)


Share me your skype Id

**Comment by NeerajMehta** [comment]
I have pinged you

**Comment by AbdallahKATAIE** [comment]
Hey Neeraj,

I haven’t received any response from you after our call discussion.
Can you please let me know if there are any updates ??

Have a good day.


De : Neeraj Singh ***@***.***>
Envoyé le :11 October 2022 20:28
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [homuler/MediaPipeUnityPlugin] ARCore (#293)


I have pinged you
