### ISSUE TITLE
Support Play Asset Delivery(PAD)?

### ISSUE THREAD

**Issue by siisee11** [homuler/MediaPipeUnityPlugin#294]
### System information

OS Platform and Distribution : Windows 10
Target: android arm64
Unity version:2020.3.7f1

I decided to use Play Asset Delivery Plugin (https://github.com/google/play-unity-plugins , 
 https://developer.android.com/codelabs/unity-gamepad#0) to reduce size of abb.

As long as I know, this module use streaming asset, so `LoadAssetBundle()` try to load asset from Streaming directory. I got 'Unable to open archive file: jar:file:///......../assets/mediapipe'

![image](https://user-images.githubusercontent.com/8529835/134636857-90850a87-8aa0-461a-827a-f140f635d179.png)

How can I integrate this plugin with PAD?

I really appreciate your plugin!

**Comment by homuler** [comment]
Have you built AssetBundle (see https://github.com/homuler/MediaPipeUnityPlugin/issues/246#issuecomment-903088129) ?

By the way, I have rewritten the sample app completely, and now you don't have to build `AssetBundle`, so I'm hoping that the solution became trivial.

**Comment by siisee11** [comment]
I just load asset from PAD(https://github.com/google/play-unity-plugins) and write them to cache where this module(before new sample app) originally write to, then it works. Thank you. I'll try new sample app later!
