### ISSUE TITLE
Support MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE

### ISSUE THREAD

**Issue by sgRollon** [homuler/MediaPipeUnityPlugin#295]
Hi ! Could you help me? I can't find how i can set confidence of handtracking in this plugin. MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE from https://google.github.io/mediapipe/solutions/hands.html#static_image_mode

I guess i have some problem with sensitivity, and i think i can fix them with these parameters.

**Comment by homuler** [comment]
Currently those options are not supported (see https://github.com/homuler/MediaPipeUnityPlugin/issues/222 for more details).
However, I'm planning to support them in the future.

**Comment by BrandonBartram98** [comment]
Is there an update on supporting tracking confidence? Would be very helpful in my project that's using holistic.

**Comment by homuler** [comment]
Waiting for https://github.com/protocolbuffers/protobuf/pull/9591 to be released.

**Comment by homuler** [comment]
Although you need to build `Google.Protobuf.dll` manually, now you can test MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE by changing the values of the corresponding fields.
https://github.com/homuler/MediaPipeUnityPlugin/blob/42106737e3d4b57efddd2e4d8e646b7b8e283fba/Assets/Mediapipe/Samples/Scenes/Face%20Detection/FaceDetectionGraph.cs#L26
