### ISSUE TITLE
Does this work on android or ios?

### ISSUE THREAD

**Issue by elblogbruno** [homuler/MediaPipeUnityPlugin#3]
Great work, I would like to know if this can work on android. I need to have the multi hand tracking working on unity and haven't found anyone achieving it even myself.
Thanks
Cordially
Bruno

**Comment by homuler** [comment]
Thank you.
Currently, it runs only on Linux.
I'm planning to try to run it on Android or iOS if I finish implementing some important features.

**Comment by elblogbruno** [comment]
That would be awesome!
Thank you

**Comment by homuler** [comment]
It is not documented well, but now sample scenes can be run on Android.
As to iOS, please wait for a while, because I don't have any iOS devices yet...

**Comment by elblogbruno** [comment]
Thanks for everything!
I will try to run it on my phone as soon as possible!

**Comment by homuler** [comment]
Now iOS is also supported.
