### ISSUE TITLE
WebGL build errors

### ISSUE THREAD

**Issue by PedroKBrant** [homuler/MediaPipeUnityPlugin#303]
Hi everyone, 
I would like to know if it´s possible to build my project using the MediaPipe Plugin on WebGL plataform, and if so, how I could do it? Thanks in advance
Pedro Brant 

**System information**
- OS Platform and Distribution: Windows 10 Pro, 20H2
- Target: desktop cpu
- Bazel version: 4.1.0
- Python version: 3.9
- GCC/G++ version:  10.3.0
- Unity version: 2020.3.8f

**Steps to reproduce the issue**
File -> Build Settings... -> WebGL -> Build and Run

**Full logs**
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(68,75): error CS0103: The name 'OutputVideoCallback' does not exist in the current context
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(68,100): error CS0103: The name 'outputVideoCallbackHandle' does not exist in the current context
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(109,11): error CS0103: The name 'outputImageLock' does not exist in the current context
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(110,11): error CS0103: The name 'outputImage' does not exist in the current context
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(112,35): error CS0103: The name 'outputImage' does not exist in the current context
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(113,7): error CS0103: The name 'outputImage' does not exist in the current context
Assets\Mediapipe\Samples\Graphs\OfficialDemo\Scripts\OfficialDemoGraph.cs(114,7): error CS0103: The name 'outputImage' does not exist in the current context

![image](https://user-images.githubusercontent.com/34447224/135668670-d571d5ec-29d7-42ce-a7fc-5005e1ab0473.png)

**Comment by homuler** [comment]
No, it's not possible.
duplicates #49
