### ISSUE TITLE
Run application in background on Android.

### ISSUE THREAD

**Issue by ghnew-unity** [homuler/MediaPipeUnityPlugin#307]
I am developing an application on Android. I want the application to run in background. I define a graph and a TextureFrame to let them run when application runs in background. But the graph and the TextureFrame can not run correctly after applicaton goes to background. I use PushInput and RenderOutput functions. Could you tell me whether I can run the application in background on Android by this method? How can I do? Thank you.

**Comment by ROBYER1** [comment]
I wasn't aware of any app that can access the camera in the background on Android, is this actually possible?

**Comment by ghnew-unity** [comment]
Hi. My application can access the camera when it goes to background. But, unfortunately, I cannot let Mediapipe run when application runs in background. I think Goolge makes Mediapipe run only as an application, not a service. Am I right?

**Comment by ROBYER1** [comment]
I believe so, the majority of android apps I have tried out for camera in background close or lose the camera while in the background, probably for privacy reasons? For the same privacy reason, is there a purpose to running the camera in the background? Why not have an app where the app runs while on screen with any info the user needs?

**Comment by ghnew-unity** [comment]
I understand your meaning. It seems a little difficult to realize the goal.
