### ISSUE TITLE
Where do i find the models and libraries?

### ISSUE THREAD

**Issue by Hakazaba** [homuler/MediaPipeUnityPlugin#31]
Could you please give a little bit more information on where to find these files?

**Comment by homuler** [comment]
The libraries such as `libmediapipe_c.so` will be generated under `C/bazel-bin` when you run `make` (cf. https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Makefile#L35).
And when you run `make install`, they will be copied to `Assets/Mediapipe/SDK/Plugins` (cf. https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Makefile#L60).
Incidentally, the libraries' source files are placed under [`C`](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/C).

As to model files, they are zipped when you run `make`, and copied to `Assets/Mediapipe/SDK/Models` when you run `make install` (cf. https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Makefile#L76).

**Comment by Hakazaba** [comment]
Oh, do i not need to move these files manually?

**Comment by homuler** [comment]
Yes. Please see [README](https://github.com/homuler/MediapipeUnityPlugin#build) for more details.

**Comment by Hakazaba** [comment]
Thanks for the help, sorry its a little bit silly as i had the impression from the readme that i needed to move files and then run install afterwards. Its all working wonderfully now.

It seems that pose detection only detects the upper body, is there way to use the full body pose detection model?

**Comment by homuler** [comment]
> It seems that pose detection only detects the upper body, is there way to use the full body pose detection model?

You can copy [the config from the official repo](https://github.com/google/mediapipe/tree/master/mediapipe/graphs/pose_tracking) and define it by yourself, but I have not added the example yet (only upgraded the MediaPipe version).

I'm planning to update the example in one or two weeks.

**Comment by Hakazaba** [comment]
Interesting. Are you planning to add holistic too?

**Comment by homuler** [comment]
Yes.

**Comment by Hakazaba** [comment]
Awesome
If' you're adding holistic, you might be intending to already, but it would be a good idea to use iris instead of facemesh. I was a bit disappointed when i noticed holistic couldn't really detect blinking very well.

**Comment by homuler** [comment]
I added a Holistic sample.
This sample does not output iris landmarks, but you can customize the config and get those landmarks.

**Comment by homuler** [comment]
I changed my mind and I modified Holistic to detect iris landmarks optionally (default is on).
