### ISSUE TITLE
Issue Making the build work for Android (APK) - Docker for Windows issues.

### ISSUE THREAD

**Issue by JManBenten** [homuler/MediaPipeUnityPlugin#317]
Docker for Windows and Hyper V enabled
Currently I have Docker installed, have the git cloned and tried the commands.

I am getting various issues such as 

`C:\Windows\system32>cd C:\UnityProjects\MediaPipeUnity

C:\UnityProjects\MediaPipeUnity>docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile
[+] Building 0.2s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 3.57kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019                               0.2s
------
 > [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:3fef9b0eac4a5d8b7d455dd07c3d8d3947657cc98bc48b0a02546ca5d782a4d5: not found`

Not exactly sure if I'm doing it correctly.

![image](https://user-images.githubusercontent.com/89081332/137515572-42c2818a-8032-479b-b968-c840deba8fd5.png)

**Comment by homuler** [comment]
Please use a Linux image.
cf. https://github.com/homuler/MediaPipeUnityPlugin#android
