### ISSUE TITLE
make cpu/gpu error

### ISSUE THREAD

**Issue by liuuuuu** [homuler/MediaPipeUnityPlugin#32]
i run `make cpu` error
this my console

ljl@ubuntu:~/MediaPipeUnityPlugin$ make cpu
cd C && bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe_api:libmediapipe_c //mediapipe_api:mediapipe_models //mediapipe_api:mediapipe_proto_srcs
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/ljl/MediaPipeUnityPlugin/C/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/3ad62ba5ff3f288a76b92482ec50d8e6/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fc58ff069f150c81abd10231bb1d9fbff0ba9322e03c9396518db4d054d5f2e6"
DEBUG: Repository rules_cc instantiated at:
  /home/ljl/MediaPipeUnityPlugin/C/WORKSPACE:72:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/3ad62ba5ff3f288a76b92482ec50d8e6/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /home/ljl/MediaPipeUnityPlugin/C/WORKSPACE:30:23: in <toplevel>
  /home/ljl/.cache/bazel/_bazel_ljl/3ad62ba5ff3f288a76b92482ec50d8e6/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /home/ljl/.cache/bazel/_bazel_ljl/3ad62ba5ff3f288a76b92482ec50d8e6/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/3ad62ba5ff3f288a76b92482ec50d8e6/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/Maratyszcza/FP16/archive/4dfe081cf6bcd15db339cf2680b9281b8451eeb3.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/094e692629d57ddb932fcc993193626f60daa61b.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/pthreadpool/archive/77f9d3bcfabd1bdb910dd33b549d5290b968ef05.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/FXdiv/archive/63058eff77e11aa15bf531df5dd34395ec3017c8.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/psimd/archive/072586a71b55b7f8c584153d223e95687148a900.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
ERROR: /home/ljl/MediaPipeUnityPlugin/C/mediapipe_api/BUILD:103:10: PackageZip mediapipe_api/mediapipe_models.zip failed (Exit 127): build_zip failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/rules_pkg/build_zip -o bazel-out/k8-opt/bin/mediapipe_api/mediapipe_models.zip -d / -t 315532800 -m 0555 ... (remaining 12 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox build_zip failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/rules_pkg/build_zip -o bazel-out/k8-opt/bin/mediapipe_api/mediapipe_models.zip -d / -t 315532800 -m 0555 ... (remaining 12 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
INFO: Elapsed time: 0.392s, Critical Path: 0.17s
INFO: 131 processes: 131 internal.
FAILED: Build did NOT complete successfully
make: *** [Makefile:38: cpu] Error 1

**Comment by elblogbruno** [comment]
If you run 'python' on the terminal, what do you get?

**Comment by liuuuuu** [comment]
ljl@ubuntu:~/MediaPipeUnityPlugin$ python

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

ljl@ubuntu:~/MediaPipeUnityPlugin$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by elblogbruno** [comment]
ok here is the problem! you need to install python
https://realpython.com/installing-python/
follow the tutorial on how to install the python programing language!

**Comment by elblogbruno** [comment]
oh didn't notice
you have python3 install

**Comment by elblogbruno** [comment]
you need to change the alias from 'python3' to 'python'

**Comment by elblogbruno** [comment]
https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu

**Comment by liuuuuu** [comment]
ohh thank very much,i need it

**Comment by elblogbruno** [comment]
you're welcome
