### ISSUE TITLE
need help in unity importing

### ISSUE THREAD

**Issue by RayanMadan** [homuler/MediaPipeUnityPlugin#321]
![image](https://user-images.githubusercontent.com/48159187/137893559-9df85c7e-b1c1-46fe-91e7-74bd77bd38cb.png)

it throws 220 errors while importing. my current version is 2020.3.8f1 what can i do to fix this?

**Comment by longgood** [comment]
I am sorry for what you are encounter, please provide your basic information while compiling.
Such as OS, Unity Version, what is your setup etc.

if you are working on windows build.
Here is the step-by-step video to tech you how to setup. That benefit me a lot.
https://www.youtube.com/watch?v=kMJOmzmMxZw

**Comment by RayanMadan** [comment]
> 
> 
> I am sorry for what you are encounter, please provide your basic information while compiling. Such as OS, Unity Version, what is your setup etc.
> 
> if you are working on windows build. Here is the step-by-step video to tech you how to setup. That benefit me a lot. https://www.youtube.com/watch?v=kMJOmzmMxZw

OS: windows 11 home
Unity: 2020.3.8f1
setup: 8gb 3200mhz, amd ryzen 7 5800h, rtx 3050(laptop)+amd radeon integrated graphics

and that is the exact tutorial i followed, it resulted in a successful build of the plugin, however when i open the StartScene, it gives these errors even though the specified files are present (all of them are errors caused by missing files).

**Comment by RayanMadan** [comment]
never mind the project just worked?? all i did was open it up the next day so i guess its resolved. thanks though
