### ISSUE TITLE
issue in taking android build

### ISSUE THREAD

**Issue by im-subash** [homuler/MediaPipeUnityPlugin#323]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): android 
- Bazel version: 4.2.0
- 
- Python version: 3.9.7
- GCC/G++ version: 6.3.0
- Unity version: 20.3.17f1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS): N/A

**Describe the problem**
I tried taking the build for android, but i'm getting error. I'm trying to take build in anyway possible. Could you please help. I have almost tried all the possible fixes given on this repo, but still i'm not able to fix it. May be there is something i have misunderstood. 

--Initially i could not procced past the Docker for Windows. Error as mentioned below.
--I have installed the docker for windows as well.
-- I have a Ubuntu software in my machine and unable to docker build for linux too. Error is similar to https://github.com/homuler/MediaPipeUnityPlugin/issues/169
-- I was able to docker build for ubuntu but the last step for taking android build is not working, (python build.py build --desktop cpu --opencv=cmake -v). error is similar to https://github.com/homuler/MediaPipeUnityPlugin/issues/191 
-- 

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.
C:\Users\subas\Desktop\mediapipeSample\MediaPipeUnityPlugin>docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile

**Full logs**
C:\Users\subas\Desktop\mediapipeSample\MediaPipeUnityPlugin>docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile
[+] Building 0.9s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019                               0.8s
------
 > [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:3fef9b0eac4a5d8b7d455dd07c3d8d3947657cc98bc48b0a02546ca5d782a4d5: not found

**Additional context**
-- I have tried all possible methods here in this repo but could not complete,  can you please assist me in this. 
-- I wish to know more on this, is it possible to connect on imsubash1909@gmail.com ?

wish you here from you asap,
thanks for your assistance.

**Comment by homuler** [comment]
> --I have tried changing the LF to CRLF, still no luck
-- Changed the autocrlf to false, still no luck.

Well, did you actually check that the line feed code is LF after that?
If you don't know what's happening, please clone the repository again.

**Comment by im-subash** [comment]
I cannot change the entire file as i have made few changes that i needed. Is there any particular file which has to be changed to execute it?

-- I have took the latest docker folder from git and replaced. 
-- here is the error i get when replacing the docker file

C:\Users\subas\Desktop\ShoeTryon>docker run --cpus=3 --memory=8192m --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages -it mediapipe_unity:ubuntu
mediapipe@31bd3deef8a7:~$
mediapipe@31bd3deef8a7:~$ python build.py build --android arm64 -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
2021/10/20 16:34:15 Downloading https://releases.bazel.build/4.2.1/release/bazel-4.2.1-linux-x86_64...
2021/10/20 16:34:44 could not download Bazel: could not copy from https://releases.bazel.build/4.2.1/release/bazel-4.2.1-linux-x86_64 to /home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.1-linux-x86_64/bin/download442734228: unexpected EOF
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/mediapipe/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '--verbose_failures', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by im-subash** [comment]
Hi, i am able to build docker image with ubuntu. but building the apk file is an issue.
Here in the error i can see bazel is not downloading..

DEBUG (build.py): Running bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs
2021/10/20 16:34:15 Downloading https://releases.bazel.build/4.2.1/release/bazel-4.2.1-linux-x86_64...
2021/10/20 16:34:44 could not download Bazel: could not copy from https://releases.bazel.build/4.2.1/release/bazel-4.2.1-linux-x86_64 to /home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.1-linux-x86_64/bin/download442734228: unexpected EOF

is there anything I'm missing. Should i change something.

**Comment by homuler** [comment]
See this. https://github.com/bazelbuild/bazel/issues/1338
Maybe you're assigning too much memory to the running container.
