### ISSUE TITLE
Error during make android_arm

### ISSUE THREAD

**Issue by hulsmeier** [homuler/MediaPipeUnityPlugin#33]
Ubuntu 18.04

`ERROR: /home/alexander/MediaPipeUnityPlugin/C/mediapipe_api/gpu/BUILD:64:11: C++ compilation of rule '//mediapipe_api/gpu:gpu_buffer' failed (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=29' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target ... (remaining 74 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang '-D__ANDROID_API__=29' -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target ... (remaining 74 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from mediapipe_api/gpu/gpu_buffer.cc:2:
In file included from ./mediapipe_api/gpu/gpu_buffer.h:10:
./mediapipe_api/gpu/gl_texture_buffer.h:41:33: error: 'mp_GlTextureBuffer__GetProducerContext' has C-linkage specified, but returns user-defined type 'const SharedGlContext &' (aka 'const shared_ptr<mediapipe::GlContext> &') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
MP_CAPI(const SharedGlContext&) mp_GlTextureBuffer__GetProducerContext(mediapipe::GlTextureBuffer* gl_texture_buffer);
                                ^
In file included from mediapipe_api/gpu/gpu_buffer.cc:2:
./mediapipe_api/gpu/gpu_buffer.h:18:39: error: 'mp_GpuBuffer__GetGlTextureBufferSharedPtr' has C-linkage specified, but returns user-defined type 'const SharedGlTextureBuffer &' (aka 'const shared_ptr<mediapipe::GlTextureBuffer> &') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
MP_CAPI(const SharedGlTextureBuffer&) mp_GpuBuffer__GetGlTextureBufferSharedPtr(mediapipe::GpuBuffer* gpu_buffer);
`
Getting the above error when running make android_arm. I'm able to build the official examples without any problems.
Make gpu also completes succcessfully.

**Comment by homuler** [comment]
I don't know why, but `-w` options does not seem to take effect.
Will you test if https://github.com/homuler/MediaPipeUnityPlugin/commit/461d019eb04545397aa398496e8e066140eb5312 (latest commit) fixed it?

**Comment by hulsmeier** [comment]
Still getting the same error unfortunately.

**Comment by homuler** [comment]
Thank you for sharing the errors.
I also fixed them at https://github.com/homuler/MediaPipeUnityPlugin/commit/125893786efebcfbb3e48e72a1c6c5f69fed0830.
