### ISSUE TITLE
How to Switch to Linux containers on window

### ISSUE THREAD

**Issue by milindmoreykitmek** [homuler/MediaPipeUnityPlugin#330]
**System information**
Window 10 ,
I am trying to build native lib for android using docker. Is possible to create .apk file on windows 10.
We got error of native lib. can you show steps , how to use docker for build apk for android

**Comment by ROBYER1** [comment]
Docker desktop has a command for changing from Windows to Linux dockers, if you right click the desktop icon on the bottom right. If you are struggling with something that simple, I wish you luck with getting this plugin running as there are many more complex things to figure out than just switching docker modes on Windows.
