### ISSUE TITLE
is there guide for users using macos m1?

### ISSUE THREAD

**Issue by choigawoon** [homuler/MediaPipeUnityPlugin#331]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): MacOS
- Target (e.g. desktop cpu, android arm64): ios
- Bazel version: 
- Python version: 3.9.7
- GCC/G++ version:
- Unity version: 2020.3.8f1
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

i've followed the guides for macos but
the brew for M1 is different with it for intel, so i lost the way.

About python

> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % which brew
> /opt/homebrew/bin/brew
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % where python 
> /usr/bin/python
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % where python3
> /opt/homebrew/bin/python3
> /usr/bin/python3
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % where pip3
> /opt/homebrew/bin/pip3
> /usr/bin/pip3

About nuget

> nuget: The x86_64 architecture is required for this software.
> Error: nuget: An unsatisfied requirement failed this build.
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % arch -x86_64 brew install nuget
> Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
> To rerun under ARM use:
>     arch -arm64 brew install ...
> To install under x86_64, install Homebrew into /usr/local.
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % softwareupdate --install-rosetta
> I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
> Type A and press return to agree:  A
> 2021-10-29 23:51:07.168 softwareupdate[49380:225495] Package Authoring Error: 071-97390: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
> Install of Rosetta 2 finished successfully
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % arch -x86_64 brew install nuget 
> Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
> To rerun under ARM use:
>     arch -arm64 brew install ...
> To install under x86_64, install Homebrew into /usr/local.
> choigawoon@choegaun-ui-Macmini MediaPipeUnityPlugin % which brew

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Full logs**

**Additional context**

**Comment by homuler** [comment]
> is there guide for users using macos m1?

I don't have any m1 mac machines, so I don't know how to make it work and there's no official guide.
I think it's possible to install NuGet if you do it right, but probably you need to do something to build `libmediapipe_c.dylib`.
cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/81

**Comment by ROBYER1** [comment]
See this issue from Google, still open https://github.com/google/mediapipe/issues/1514

**Comment by homuler** [comment]
I bought a m1 mac mini and confirmed this plugin works on it, so I'll update README later.

**Comment by ROBYER1** [comment]
> I bought a m1 mac mini and confirmed this plugin works on it, so I'll update README later.

Did you manage to build the plugin on the M1 mac? Or do you mean it just runs in editor? I haven't been able to build the plugin on my M1 mac mini but I also don't have a webcam that works on the M1 mac yet so I can't test if the plugin runs in editor. I had to build the plugin on an Intel Mac and copy it over to the M1 from there I could do builds for IOS.

**Comment by homuler** [comment]
I confirmed that it runs on UnityEditor (2021.2.2f1 for Apple Silicon) and the built sample app works on my m1 mac without Rosetta 2.

**Comment by choigawoon** [comment]
thanks a ton, i've seen it now. i'll try soon

**Comment by FUBAR2077** [comment]
awesome @homuler !

**Comment by homuler** [comment]
I'll document it later, but not right away, so I just write an overview here.
There needs extra steps to install NuGet on M1 Mac.

> 4. Install Bazelisk and NuGet

To install NuGet, Rosetta 2 is required.
```sh
/usr/sbin/softwareupdate --install-rosetta

# Install Homebrew using Rosetta 2
# Before running the command, please check https://brew.sh/ for the correct URL
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install NuGet using Rosetta 2
arch -x86_64 /usr/local/homebrew/bin/brew install nuget
```

**Comment by sh0ckwav** [comment]
> I confirmed that it runs on UnityEditor (2021.2.2f1 for Apple Silicon) and the built sample app works on my m1 mac without Rosetta 2.

What are the script changes necessary to run this on 2021.2? I get a lot of errors about Landmarks and couldn't run it.

On 2020.3 when I run the sample scene I get `Global config does not exist` first and then `DllNotFoundException`. I am able to build `libmediapipe_c.dylib` successfully and have tried various OpenCV build scripts but the directory is empty.

**Comment by homuler** [comment]
Updated the document > https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#m1-mac

@sh0ckwav Please pull the latest commit first.
If you still encounter some errors and you're sure the same issue isn't created yet, please create a new issue with the error logs.
