### ISSUE TITLE
build error On windows

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#332]
**HP ML110 SERVER GPU = quadro + CPU = XEON**
- OS Platform and Distribution (WSL2):
- Target (e.g. desktop cpu):
- Bazel version: 4.0.0
- Python version:Python 3.9.7
- GCC/G++ version:
- Unity version:2020  2.2.0

**Describe the problem**

in the end of the build 
i got blow error
``
**Steps to reproduce the issue**
python build.py build --desktop cpu --include_opencv_libs -vv

--------------------------

**Full logs**INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="M://mediapipe//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "853f9480ceb0eccf458226d412cd2c67b4b73374bc2e8f64d63babed4c12e0b9"
DEBUG: Repository rules_cc instantiated at:
  M:/mediapipe/mediapipeunityplugin/WORKSPACE:84:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  M:/mediapipe/mediapipeunityplugin/WORKSPACE:41:23: in <toplevel>
  C:/_bzl/toesf3zy/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 681 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 18.758s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  C:\Users\ehsN\.nuget\packages\
  https://api.nuget.org/v3/index.json

All packages listed in M:\mediapipe\MediaPipeUnityPlugin\packages.config are already installed.
DEBUG (build.py): Copying '.nuget\Google.Protobuf.3.15.6\lib\netstandard2.0\Google.Protobuf.dll' to 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll' to 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll' to 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Copying '.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll' to 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="M://mediapipe//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_assets`
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  M:/mediapipe/mediapipeunityplugin/WORKSPACE:41:23: in <toplevel>
  C:/_bzl/toesf3zy/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "853f9480ceb0eccf458226d412cd2c67b4b73374bc2e8f64d63babed4c12e0b9"
DEBUG: Repository rules_cc instantiated at:
  M:/mediapipe/mediapipeunityplugin/WORKSPACE:84:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 26 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 2.869s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'build\Resources'...
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'Assets\StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="M://mediapipe//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop`
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/toesf3zy/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "853f9480ceb0eccf458226d412cd2c67b4b73374bc2e8f64d63babed4c12e0b9"
DEBUG: Repository rules_cc instantiated at:
  M:/mediapipe/mediapipeunityplugin/WORKSPACE:84:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  M:/mediapipe/mediapipeunityplugin/WORKSPACE:41:23: in <toplevel>
  C:/_bzl/toesf3zy/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/toesf3zy/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (0 packages loaded, 8071 targets configured).
INFO: Found 1 target...
INFO: From Compiling absl/base/internal/cycleclock.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/base/log_severity.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/base/internal/throw_delegate.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/base/internal/unscaledcycleclock.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/base/internal/spinlock.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/base/internal/thread_identity.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/base/internal/sysinfo.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/status/status.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/debugging/symbolize.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/notification.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/barrier.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/status/status_payload_printer.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/internal/create_thread_identity.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/internal/per_thread_sem.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/blocking_counter.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/internal/waiter.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/synchronization/mutex.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling tensorflow/lite/stderr_reporter.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
INFO: From Compiling tensorflow/lite/kernels/cpu_backend_gemm_eigen.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
INFO: From Compiling ruy/thread_pool.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
INFO: From Compiling absl/flags/reflection.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling ruy/block_map.cc:
cl : Command line warning D9002 : ignoring unknown option '-O3'
ERROR: C:/_bzl/toesf3zy/external/com_google_mediapipe/mediapipe/util/tracking/BUILD:552:11: Compiling mediapipe/util/tracking/motion_analysis.cc failed: (Exit 2): cl.exe failed: error executing command
  cd C:/_bzl/toesf3zy/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=2a07
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=M://mediapipe//MediaPipeUnityPlugin//env//Scripts//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\ehsN\AppData\Local\Temp
    SET TMP=C:\Users\ehsN\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/com_google_mediapipe /Ibazel-out/x64_windows-opt/bin/external/com_google_mediapipe /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf /Iexternal/com_github_glog_glog /Ibazel-out/x64_windows-opt/bin/external/com_github_glog_glog /Iexternal/com_github_gflags_gflags /Ibazel-out/x64_windows-opt/bin/external/com_github_gflags_gflags /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/windows_opencv /Ibazel-out/x64_windows-opt/bin/external/windows_opencv /Ibazel-out/x64_windows-opt/bin/external/com_github_glog_glog/_virtual_includes/windows_glog_headers /Ibazel-out/x64_windows-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/src /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/windows_opencv/include /Ibazel-out/x64_windows-opt/bin/external/windows_opencv/include /DMEDIAPIPE_DISABLE_GPU=1 /DGOOGLE_GLOG_DLL_DECL=__declspec(dllexport) /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /w /D_USE_MATH_DEFINES /std:c++17 /Fobazel-out/x64_windows-opt/bin/external/com_google_mediapipe/mediapipe/util/tracking/_objs/motion_analysis/motion_analysis.obj /c external/com_google_mediapipe/mediapipe/util/tracking/motion_analysis.cc
Execution platform: @local_execution_config_platform//:platform
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): error C2244: 'mediapipe::StreamingBuffer::AddData': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(351): note: see declaration of 'mediapipe::StreamingBuffer::AddData'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(352): note: 'void mediapipe::StreamingBuffer::AddData(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<Types,std::default_delete<Types>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): error C2244: 'mediapipe::StreamingBuffer::AddDataImpl': unable to match function definition to an existing declaration
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(367): note: see declaration of 'mediapipe::StreamingBuffer::AddDataImpl'
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: definition
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: existing declarations
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &)'
        with
        [
            _Ty=std::string
        ]
external/com_google_mediapipe\mediapipe/util/tracking/streaming_buffer.h(369): note: 'void mediapipe::StreamingBuffer::AddDataImpl(const std::vector<std::string,std::allocator<_Ty>> &,std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::unique_ptr<Pointers,std::default_delete<Pointers>>...)'
        with
        [
            _Ty=std::string
        ]
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 309.663s, Critical Path: 285.63s
INFO: 496 processes: 208 internal, 288 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "M:\mediapipe\MediaPipeUnityPlugin\build.py", line 444, in <module>
    Argument().command().run()
  File "M:\mediapipe\MediaPipeUnityPlugin\build.py", line 141, in run
    self._run_command(self._build_desktop_commands())
  File "M:\mediapipe\MediaPipeUnityPlugin\build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\ehsN\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="M://mediapipe//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

**Comment by homuler** [comment]
Same as #226
