### ISSUE TITLE
How to reduce android apk size

### ISSUE THREAD

**Issue by manisharan18** [homuler/MediaPipeUnityPlugin#335]
Hi. I am using this package for an android app. But the app size is around 300 MB. Is there a way to reduce the app size. Please suggest. Looking forward to your reply. Thanks.

**Comment by LGuilhermeRodrigues** [comment]
There is a closed issue about reducing the size, check #232.

**Comment by ROBYER1** [comment]
This issue can probably be closed as it is a dupe

**Comment by homuler** [comment]
I wrote an answer in Wiki.
https://github.com/homuler/MediaPipeUnityPlugin/wiki/FAQ#how-to-reduce-the-plugin-size

I'll add more on how to remove unused model files and calculators.

**Comment by dogadogan** [comment]
@homuler, did you get a chance to explain how to remove unused model files and calculators somewhere? :)

I'm only using the object detector, so it would be great to know how to remove the other models.

Also, I had started out with the MediaPipeUnityPlugin-all.zip from the release page, so any pointers on how to (later) make the Unity project more compact would be helpful!
