### ISSUE TITLE
Issue running Docker run build commands on Windows 10 for Android/Windows builds

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#336]
**System information**
- OS Platform and Distribution Windows 10
- Target Platform: Android/Windows
- MediaPipeUnityPlugin version or commit id: 4d90ac44627dd0996792e56fdc0817a7b15ada4a

**Describe the current behavior**
When using the example build commands on the latest commits, I get this error from Docker - 
`docker: Error response from daemon: %!C(string=is not a valid Windows path)D%!\(MISSING)Packages.`

Is there something simple I am missing here? I've tried from within and outside of the packages folder also - I had the same issue with the old build commands on mediapipe 0.8.4 commits but I was able to resolve them by putting the exact windows paths into the build command like this in the old build command:

`docker run --cpus=16 --memory=16000m --mount type=bind,src=C:\Unity_Projects\MediaPipeLatest\Packages,dst=/home/mediapipe/Packages -it mediapipe_unity:linux`

So I tried the same with the new command that has multiple 'mount' paths in it now:

`docker run --cpus=16 --memory=16000m --mount type=bind,src=C:\Unity_Projects\MediaPipeLatest\Packages,dst=/home/mediapipe/Packages --mount type=bind,src=C:\Unity_Projects\MediaPipeLatest\Assets,dst=C:\mediapipe\Assets -it mediapipe_unity:linux`

Which then gives me this error:
`docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/mediapipe/Assets' mount path must be absolute.`

Also only a minor issue but when I copy paste the command directly from the readme on Git into powershell and I get this - 
"
docker run --cpus=16 --memory=8192m ^
    --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages ^
    --mount type=bind,src=%CD%\Assets,dst=C:\mediapipe\Assets ^
    -it mediapipe_unity:linux
"
So I have to remove the '^'s as it tries to run each command as a separate line (no big deal)

**Describe the expected behavior**
Example build command paths should just work in Docker Windows

**Steps to reproduce the issue**
Try running the example build commands, perhaps try cloning the project to a new folder on a different drive on your pc first?

Screenshot:
![image](https://user-images.githubusercontent.com/10745594/139822112-f7135a34-2fa4-4949-83ec-0adfdc4dde8f.png)

**Comment by ROBYER1** [comment]
I tried changing the second mount's dst= from C:/mediapipe/Assets to /home/mediapipe/Assets as that dst seemed to work in the original build command I edited, now I can get to the build step but I am just building now to see if it actually builds. I think the main issue is since the new Sample scenes got added, the extra mount in the build command was causing these issues.

`docker run --cpus=16 --memory=16000m --mount type=bind,src=C:\Unity_Projects\MediaPipeLatest\Packages,dst=/home/mediapipe/Packages --mount type=bind,src=C:\Unity_Projects\MediaPipeLatest\Assets,dst=/home/mediapipe/Assets -it mediapipe_unity:linux
`

**Comment by homuler** [comment]
It seems that the command was copied and pasted incorrectly.
https://github.com/homuler/MediaPipeUnityPlugin/commit/2994e4425d347260006e15edc8d375e0d35a3b0f fixed it.
