### ISSUE TITLE
Request - add strip command by default in Readme build commands

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#337]
Is it possible to update the build commands in the readme with the strip command versions? I haven't seen a use case for production apps to build mediapipe with the debug symbols included + it adds at least 200mb+ to android apk builds.

Something like this:

`python build.py build --android arm64 --linkopt=-s -vv`

Thanks!

**Comment by homuler** [comment]
Thank you for your suggestion.
I am planning to take some time off this year and update the documentation.
I will describe how to use the plugin and FAQ, including how to reduce the size of the plugin.

**Comment by homuler** [comment]
I wrote it in Wiki.
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#build-command
https://github.com/homuler/MediaPipeUnityPlugin/wiki/FAQ#how-to-reduce-the-plugin-size
