### ISSUE TITLE
Build error on Mac - Fatal Error

### ISSUE THREAD

**Issue by clement0204** [homuler/MediaPipeUnityPlugin#338]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): `macOS Big Sur 11.6`
- Target (e.g. desktop cpu, android arm64): `desktop cpu`
- Bazel version: `4.2.1`
- Python version: `3.10.0`
- GCC/G++ version: `none`
- Unity version: `2020.3.19f1`
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

Hi ! I'm trying to build the plugin on my Mac but I'm facing an issue. I've followed all the steps until the build command and the bash returns a fatal issue as followed :

`python build.py build --desktop gpu -v`

![Capture d’écran 2021-11-02 à 13 48 49](https://user-images.githubusercontent.com/93545145/139849596-2b2a92a9-c7e2-49f4-8719-bfa899e73117.png)

I've seen on internet that this error might be linked to a BUILD file but I don't know which one I'm supposed to modify and how. Thank you for your help !!

**Comment by homuler** [comment]
Please use bazel 3.7.2 and python 3.9.x.
cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/274

Note that you cannot build for GPU on macOS, so the correct command is `python build.py build --desktop cpu -vv`.
