### ISSUE TITLE
surface tracking

### ISSUE THREAD

**Issue by Vladislav489** [homuler/MediaPipeUnityPlugin#34]
hi, very cool plugin, please tell me how to implement surface tracking?

**Comment by homuler** [comment]
What do you mean by "surface tracking"?
If it isn't implemented by [MediaPipe](https://google.github.io/mediapipe/solutions/solutions.html) yet, you need to train the model and/or implement calculators first.

**Comment by Vladislav489** [comment]
> Что вы имеете в виду под «отслеживанием поверхности»?
> Если это еще не реализовано [MediaPipe](https://google.github.io/mediapipe/solutions/solutions.html) , вам нужно сначала обучить модель и / или реализовать калькуляторы.

I need the object to appear on the table in AR without markers. Is this implemented?

**Comment by homuler** [comment]
You may need [3D Objectron](https://google.github.io/mediapipe/solutions/objectron.html), but it does not work yet. (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/27)

I have not tried it yet so I'm not sure, but you can probably get the 3D location data of the detected object (without rendering annotations) now.

**Comment by Vladislav489** [comment]
> You may need [3D Objectron](https://google.github.io/mediapipe/solutions/objectron.html), but it does not work yet. (cf. #27)
> 
> I have not tried it yet so I'm not sure, but you can probably get the 3D location data of the detected object (without rendering annotations) now.

if you can do it, I am ready to pay you, we really need it now

**Comment by homuler** [comment]
OK, I'll investigate it soon (maybe this weekend), but regrettably, the published Objectron model seems to detect only 4 classes (shoes, chairs, mugs, and cameras) so if you'd like to track a table, I think you need to train a model first.
https://github.com/google-research-datasets/Objectron/

**Comment by Vladislav489** [comment]
> Хорошо, я скоро исследую это (возможно, в эти выходные), но, к сожалению, опубликованная модель Objectron, похоже, обнаруживает только 4 класса (обувь, стулья, кружки и камеры), поэтому, если вы хотите отслеживать стол, я думаю сначала вам нужно обучить модель.
> https://github.com/google-research-datasets/Objectron/



> Хорошо, я скоро исследую это (возможно, в эти выходные), но, к сожалению, опубликованная модель Objectron, похоже, обнаруживает только 4 класса (обувь, стулья, кружки и камеры), поэтому, если вы хотите отслеживать стол, я думаю сначала вам нужно обучить модель.
> https://github.com/google-research-datasets/Objectron/

We need an object to appear on the surface, a table or something else does not matter) Here is an example https://www.youtube.com/watch?v=F3s3M0mokNc&t=81s

**Comment by homuler** [comment]
I see, like this one? -> https://google.github.io/mediapipe/solutions/instant_motion_tracking

**Comment by Vladislav489** [comment]
Yes it is

**Comment by Vladislav489** [comment]
Can you do this?

> Понятно, как этот? -> https://google.github.io/mediapipe/solutions/instant_motion_tracking

**Comment by SergeyAME** [comment]
@Vladislav489  If you do not need to track moving objects, just use ARFoundation (https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html). You don't need mediapipe.

**Comment by Vladislav489** [comment]
> @Vladislav489 If you do not need to track moving objects, just use ARFoundation (https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html). You don't need mediapipe.

ArFoundation uses ARcore and im think mediapipe works very well for me.

**Comment by Vladislav489** [comment]
ArCore has low supported devices

**Comment by SergeyAME** [comment]
You want to use it on "low end" devices, that doesn't support ARCore? I'm not sure, that performance will be enough. In our application we set requirements similar to ARCore. Because performance for FaceTracking and HandTracking was not enough on low end Android devices :(

**Comment by Vladislav489** [comment]
And just surface tracking will be hard on devices not supported by ARCore?

**Comment by Vladislav489** [comment]
I had information that mediapipe can work on any device that has a gyroscope

**Comment by SergeyAME** [comment]
At current moment MediaPipeUnityPlugin didn't have example for [InstantMotionTracking](https://google.github.io/mediapipe/solutions/instant_motion_tracking). If you want to test performance, you can just [download APK](https://drive.google.com/file/d/1KnaBBoKpCHR73nOBJ4fL_YdWVTAcwe6L/view?usp=sharing) from mediapipe samples and run it on your target device.

**Comment by Vladislav489** [comment]
This works well enough even on unsupported devices, the question remains, can you please suggest alternatives? Maybe OpenCV will work well and handle most devices or PTAM?

**Comment by Vladislav489** [comment]
Another question can you do this with mediapipe? I can pay, this is a very important function

**Comment by Vladislav489** [comment]
> В настоящий момент у MediaPipeUnityPlugin нет примера для [InstantMotionTracking](https://google.github.io/mediapipe/solutions/instant_motion_tracking) . Если вы хотите проверить производительность, вы можете просто [загрузить APK](https://drive.google.com/file/d/1KnaBBoKpCHR73nOBJ4fL_YdWVTAcwe6L/view?usp=sharing) из образцов mediapipe и запустить его на своем целевом устройстве.

Are you still here?

**Comment by Vladislav489** [comment]
We see how work OpenCV and we really need Mediapipe

**Comment by Almazikman** [comment]
> 
> 
> At current moment MediaPipeUnityPlugin didn't have example for [InstantMotionTracking](https://google.github.io/mediapipe/solutions/instant_motion_tracking). If you want to test performance, you can just [download APK](https://drive.google.com/file/d/1KnaBBoKpCHR73nOBJ4fL_YdWVTAcwe6L/view?usp=sharing) from mediapipe samples and run it on your target device.
Oh wow I tried to find this mechanic, but I failed. I tested that application and it works perfectly. But a new question appeared, how to do this in Unity? I need your aid.

**Comment by homuler** [comment]
I think those steps are required at least.

- Build native libraries with necessary calculators (update [BUILD](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/mediapipe_api/BUILD#L69))
- Copy the graph config from the official repository
- Setup the graph (implement `DemoGraph#StartRun`)
   - https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/MainActivity.java#L154
   - Port missing APIs (for example, currently the plugin does not have the API to create `Packet<Sticker>`)

And if you'd like MediaPipe to render 3D objects,
- import resource files to Unity
- Create a patch to read resource files in Unity (see https://github.com/google/mediapipe/blob/master/mediapipe/graphs/object_detection_3d/calculators/gl_animation_overlay_calculator.cc#L335)
- Port additional APIs

If you render 3D objects in Unity,
- Port APIs to get matrices
- Get matrices from the graph and render 3D objects based on them

**Comment by homuler** [comment]
Android Demo.

https://user-images.githubusercontent.com/4690128/108624694-d05c8d00-7489-11eb-9bfa-53a122c6142f.mp4

**Comment by Almazikman** [comment]
Looks good, how I can reproduce this thing in my project?

**Comment by Vladislav489** [comment]
> Android Demo.
> 
>  unity-chan.mp4

Very Cool! When and how can you use it?

**Comment by homuler** [comment]
Instant Motion Tracking is released at [v0.5.0](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.5.0).
Above sample is not included in this repository, but you can get `Matrix4x4` for a 3D model to rotate and translate it.

**Comment by Vladislav489** [comment]
> Instant Motion Tracking is released at [v0.5.0](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.5.0).
> Above sample is not included in this repository, but you can get `Matrix4x4` for a 3D model to rotate and translate it.

I am very glad to hear this, I was waiting for this very much, now I will download it, try it in my work, write the result

**Comment by Almazikman** [comment]
> Instant Motion Tracking is released at [v0.5.0](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.5.0).
> Above sample is not included in this repository, but you can get `Matrix4x4` for a 3D model to rotate and translate it.

I installed mediapipe by instruction on Mac and I managed to start Hello World template, but, I have a problem with make cpu && make install

My terminal:
`MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make cpu && make install
mkdir -p .build
curl -L https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz -o .build/protobuf-3.13.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0    357      0 --:--:-- --:--:-- --:--:--   357
100 5154k    0 5154k    0     0   661k      0 --:--:--  0:00:07 --:--:--  589k
tar xf .build/protobuf-3.13.0.tar.gz -C .build
dotnet restore .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln && \
	dotnet build -c Release .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
/bin/sh: dotnet: command not found
make: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 127
MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make gpu
dotnet restore .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln && \
	dotnet build -c Release .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
/bin/sh: dotnet: command not found
make: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 127
MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make install
mkdir -p Assets/MediaPipe/SDK/Plugins/Protobuf
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/MediaPipe/SDK/Plugins/Protobuf
cp: .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/*: No such file or directory
make: *** [install-protobuf] Error 1
MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ `

Because of this issue in Unity I have a lot of errors like #62 
Any ideas how to fix it?
