### ISSUE TITLE
Building Project results in black screen

### ISSUE THREAD

**Issue by GearType** [homuler/MediaPipeUnityPlugin#340]
I am able to successfully play the Start Scene and access the various demos from within Unity, but when I build the project (including all scenes), the build launches but the screen is black. Are there specific prerequisites and settings needed to run a build outside of Unity? Running on Windows 10.

**Comment by homuler** [comment]
Please read the log first and check to see if the same issue has already been created or resolved.
If you don't find any similar issues, then use [this format](https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/.github/ISSUE_TEMPLATE/build-installation-issue.md) and share the log.

**Comment by GearType** [comment]
Thank you, and appreciate the development.

**Comment by yiusay** [comment]
For people who encounter this issue in the future. I solved the issue as follow. 

In the project window, go to Packages/MediaPipe Plugin/Runtime/Plugin. Then, select libmediapipe_c and, in the inspector, check "Load on startup" and click "Apply".
