### ISSUE TITLE
Handtracking Layers is not rendering on top of AR camera layer

### ISSUE THREAD

**Issue by teamcrossfever** [homuler/MediaPipeUnityPlugin#345]
Handtracking Layers is not rendering on top of AR camera layer

In the scenario the hand tracking is not being shown.  Seems to be the AR camera is over taking the hand tracking layer

**Comment by homuler** [comment]
Excuse me, but are you sure you're submitting the issue to the right repository?
ARCamera is not used here for now.

**Comment by teamcrossfever** [comment]
whoops
