### ISSUE TITLE
WIndows 10 desktop CPU build errors.

### ISSUE THREAD

**Issue by Geralt967** [homuler/MediaPipeUnityPlugin#346]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): desktop cpu
- Bazel version: 4.2.1
- Python version: 3.9.8
- GCC/G++ version: 
- Unity version: 2020.3.15
- Android NDK version (if building for Android): -
- Xcode version (if building for iOS): -

Can't build a native libraries for Windows 10. 

I have performed the installation according to your installation guide. When I try to build a native libraries using this command "python build.py build --desktop cpu --opencv=cmake -v. I get the following errors: 

E:\Projects\Unity\MediaPipeUnityPlugin>python build.py build --desktop cpu --opencv=cmake -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//ДНС//AppData//Local//Programs//Python//Python39-32//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/sk2fthsz/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository local_execution_config_python instantiated at:
  E:/projects/unity/mediapipeunityplugin/WORKSPACE:452:14: in <toplevel>
  C:/_bzl/sk2fthsz/external/org_tensorflow/tensorflow/workspace2.bzl:1087:19: in workspace
  C:/_bzl/sk2fthsz/external/org_tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  C:/_bzl/sk2fthsz/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/sk2fthsz/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\─═╤\AppData\Local\Programs\Python\Python39-32\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths = site.gets(...)): ?? ??????? ????? ????????? ????.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\─═╤\AppData\Local\Programs\Python\Python39-32\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths = site.gets(...)): ?? ??????? ????? ????????? ????.
 (error: 2)
INFO: Repository rules_java instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:255:6: in <toplevel>
  C:/_bzl/sk2fthsz/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  C:/_bzl/sk2fthsz/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository com_google_protobuf instantiated at:
  E:/projects/unity/mediapipeunityplugin/WORKSPACE:177:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/sk2fthsz/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\─═╤\AppData\Local\Programs\Python\Python39-32\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths = site.gets(...)): ?? ??????? ????? ????????? ????.
 (error: 2)
INFO: Elapsed time: 2.921s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (8 packages)
Traceback (most recent call last):
  File "E:\Projects\Unity\MediaPipeUnityPlugin\build.py", line 424, in <module>
    Argument().command().run()
  File "E:\Projects\Unity\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "E:\Projects\Unity\MediaPipeUnityPlugin\build.py", line 50, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\ДНС\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//ДНС//AppData//Local//Programs//Python//Python39-32//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by ROBYER1** [comment]
Does it work if you use the Docker build guide? I use the Docker one as it is easy to maintain the dependencies and flip around between different commits/versions 
https://github.com/homuler/MediaPipeUnityPlugin#docker-for-windows

**Comment by Geralt967** [comment]
As I can see it doesn't work with Windows 10 Home =(

**Comment by ROBYER1** [comment]
I know it might not be great to hear but if you can get a key for a more development friendly version of Windows 10, like Pro you will not need to worry about dependency conflicts/snags that you might get with building using the local Windows build process. Docker is a huge help as it pulls all the dependencies in for us when building without relying on anything installed to the local system.

If not, I hope you get some help with building it locally on Windows 10 as that build process should work too - I would suggest to look around the main Mediapipe Repo on github like this may fix your issue - https://github.com/google/mediapipe/issues/724

**Comment by homuler** [comment]
> File "C:/_bzl/sk2fthsz/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
> fail(
> Error in fail: Repository command failed
> java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\─═╤\AppData\Local\Programs\Python\Python39-32\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write("from future import print_function" + linesep);f.write("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('PYTHONPATH') is not None:" + linesep);f.write(" python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("try:" + linesep);f.write(" library_paths = site.gets(...)): ?? ??????? ????? ????????? ????.
> (error: 2)

I can't read the error message because it's garbled, so please re-paste the log (the message should be in English).

**Comment by Geralt967** [comment]
In fact, this was the problem in that PYTHONPATH had symbols in another language.
