### ISSUE TITLE
gcc: error trying to exec 'cc1plus': execvp: No such file or directory

### ISSUE THREAD

**Issue by elblogbruno** [homuler/MediaPipeUnityPlugin#35]
I Was trying to build for arm64 android and fails with this strange issue. I do have gcc and g++ installed, as I've seen on the internet solutions telling me to install them.

![2021-01-19 12_24_15-bruno-pc (bruno-pc)_ VNC Viewer](https://user-images.githubusercontent.com/10481058/105028508-68152880-5a51-11eb-9656-8c558f643ec0.png)

what could be wrong?
If I run make as sudo, I do get numpy missing issue m and I do have numpy installed.

Thanks
Great Job!
Bruno Moya

**Comment by homuler** [comment]
If the problem continues after running `make clean`, will you tell me the output of the below command?
```sh
cd C && /bazel build -c opt --config=android_arm64 --sandbox_debug //mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android
```

**Comment by elblogbruno** [comment]
The problem does continue after `make clean`
Here is the output:
![image](https://user-images.githubusercontent.com/10481058/105042728-e0391980-5a64-11eb-9d44-3c3037fe9ed3.png)

**Comment by homuler** [comment]
Are `ANDROID_HOME` and `ANDROID_NDK_HOME` set correctly?

**Comment by elblogbruno** [comment]
yes I always run this script that exports correct path for both variables 

![image](https://user-images.githubusercontent.com/10481058/105044440-05c72280-5a67-11eb-8610-522b7af477b4.png)

**Comment by elblogbruno** [comment]
by the moment I have seen i do have different g++ and gcc version,i will see if that is the issue

**Comment by elblogbruno** [comment]
it seems this was the issue, i had version gcc 7 but g++ 8 version installed. Did downgraded from g++8 version to g++7 and now it is not crashing.
https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version
Thanks
