### ISSUE TITLE
World hand landmarks

### ISSUE THREAD

**Issue by Geralt967** [homuler/MediaPipeUnityPlugin#351]
Hi,

The plugin contains MULTI_HAND_WORLD_LANDMARKS or it works only with MULTI_HAND_LANDMARKS?
I need to get the position of the  hand in Z axis.

**Comment by homuler** [comment]
Well, as far as I know, this feature has not been officially released yet (although it seems to be mentioned in the documentation).
But that's said, we've already got the Z value, since `Landmark` and `NormalizedLandmark` have Z.
