### ISSUE TITLE
Can I use lower version unity(2018) to run this project?

### ISSUE THREAD

**Issue by jerrysheen** [homuler/MediaPipeUnityPlugin#36]
HI, thanks for providing this plugin, now I've successfully run it on unity 2019.
I was wondering can I run it on unity 2018?  If can't how can I rebuild the work to fulfill this purpose?
Thanks!

**Comment by jerrysheen** [comment]
I've been tried the whole day and can't find any solutions for that ... could u provide any solutions? 
Thanks!

**Comment by homuler** [comment]
OK, I'll check tomorrow.

**Comment by homuler** [comment]
It looks to me that at least SDK itself works, so I think you should update scripts under `Assets/MediaPipe/Examples`.
I tested `DesktopGPU` scene at [test/unity-2018](https://github.com/homuler/MediaPipeUnityPlugin/tree/test/unity-2018) branch (UI object is broken, but graphs run).

**Comment by jerrysheen** [comment]
Hi, Homuler, Thanks for your reply, I've tested it on both windows and Linux, and successfully import all the file into Unity (without any dll conflict compare to the old version). really thanks for your help !!
now I'm trying to build something on the windows unity 2018 platforms using CPU. Can I just work on the current SDK? (I mean do I only need to modify example scene without changing any config file?) Thanks!

**Comment by jerrysheen** [comment]
When I try to run it on linux, I got this error:
![image](https://user-images.githubusercontent.com/19220015/105573925-c2dea680-5d15-11eb-9636-37cb7cc1c632.png)
it seam almost same as what i've met on windows... :/

**Comment by homuler** [comment]
In the linux case, it's because OpenCV is not loaded.

**Comment by jerrysheen** [comment]
Yes, I figured it out. Thanks for your help. 👍 👍 👍 
Could you help me with the windows cpu version?
Since my original program is running on that and can hardly change the version :>

the story goes like this: I'm trying to build a unity application with my friends. and I found mediapipe really helpful to tracking the movement.. I used to work on the CPP version and successfully extract landmark without frame stuck...(probably worked for a week). But this week me and my groupmate try to communicate between the original program and C++ mediapipe. We've tried lots of ways..(RTSP, webRTC, virtual camera) to help to send the image from the original unity app to the C++ mediapipe and send data back... but all failed. I got stuck here. But lucky for me I found your reposity and I think maybe I can use it as a pluggin to my unity 2018 program.
Still, I have lots of work to do, but seam it's a good start....
So could you help me again for running this on windows？ thanks ! 🥇

**Comment by homuler** [comment]
Please try copying `libmediapipe_c.dll` and `opencv_world3410.dll` under the `Editor` directory.
https://forum.unity.com/threads/dllnotfoundexception-when-depend-on-another-dll.31083/#post-238893

**Comment by jerrysheen** [comment]
Hi homuler,
I've tried it but still got the error:
![捕获1](https://user-images.githubusercontent.com/19220015/105655394-f169a680-5efa-11eb-90b0-a8446bb7c042.PNG)
I try to move my `libmediapipe_c.dll` and `opencv_world3410.dll` to /Asset/Mediapipe/Editor(both mata and dll file itself), but it can't work on windows.

and I find the dll file I've compiled doesn't contains `loadonstart `function, both windows2018 and linux2018.

By the way when I not build assetbundle, there is an error :
![捕获](https://user-images.githubusercontent.com/19220015/105656061-5b368000-5efc-11eb-8591-25f553119e60.PNG)
but after build it's fine. 

Please help me to fix the DLL not found Exception.

**Comment by homuler** [comment]
> /Asset/Mediapipe/Editor

Not there, see the above post more carefully.
> c:\program files\unity\editor

**Comment by jerrysheen** [comment]
Thanks, now the error is gone!

**Comment by jerrysheen** [comment]
The original problem is fixed, gonna try to fulfill the funtion on unity2018
