### ISSUE TITLE
How can I get multi_hand_world_landmarks

### ISSUE THREAD

**Issue by Kredo6666** [homuler/MediaPipeUnityPlugin#360]
As https://google.github.io/mediapipe/solutions/hands.html mentioned, Mediapipe can output _multi_hand_world_landmarks_, I tried to use it in unity by compling Python script into exe and sending _multi_hand_world_landmarks_ to C# script. It works pretty good with 3D model, but .exe cannot run on Android and IOS.
![HandTrackingUnity](https://user-images.githubusercontent.com/49152594/143857557-6ce91b80-1126-4ede-9369-d366b69cb6c2.gif)
I found this plugin and tried to convert _handLandmarks_ in HandTrackingSolution.cs into _multi_hand_world_landmarks_, but it's too hard for me to calculate them correctly. Hope the plugin can providing _multi_hand_world_landmarks_ directly or give me some advice how to achieve it.
Thanks！

**Comment by homuler** [comment]
This project depends on MediaPipe v0.8.8 (the latest version at the moment), that does not includes this feature as far as I know. 
cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/351

Note that source files under `Assets` are only sample code.
You can write and use your own config file that outputs `multi_hand_world_landmarks` once MediaPipe releases it and this project supports that version.
