### ISSUE TITLE
Wrong values coming from matrix

### ISSUE THREAD

**Issue by AbdallahKATAIE** [homuler/MediaPipeUnityPlugin#364]
**System information**
- OS Platform and Distribution : **Windows 10 Home (I installed Hyper-V manually and I was able to start docker afterwards)**
- Target: android arm64
- Bazel version: 4.2.1
- Python version: 3.9.6
- Unity version:2020.3.8f1

**Steps to reproduce the issue**
So I'm still using the older version of Objectron (ObjectDetection3dGraph.cs) and I can't update my project to the new version yet.

I want to know the coordinates of the landmarks of my bounding box, so I'm using this function : 

```
    [AOT.MonoPInvokeCallback(typeof(CalculatorGraph.NativePacketCallback))]
    static IntPtr MatrixCallback(IntPtr packetPtr)
    {
        try
      {
          using (var packet = new TimedModelMatrixProtoListPacket(packetPtr, false))
          {
                var matrixProtoList = packet.Get();
              if (matrixProtoList.ModelMatrix.Count > 0)
              {
                     var matrix = Matrix4x4FromBytes(matrixProtoList.ModelMatrix[0].MatrixEntries);
                    Stablematrix = matrix;
                  }
          }

          return Status.Ok().mpPtr;
      }
      catch (Exception e)
      {
          return Status.FailedPrecondition(e.ToString()).mpPtr;
      }
    }
```

So I load a 3D model in the scene and I apply its rotations to Stablematrix's rotations.
However, `Stablematrix.rotation.Eulerangles.y` rotation doesn't perfectly match the bounding box's rotation.
The further I get from my sneaker, the more difference there is between the bounding box's rotation and the actual values I'm getting from `Stablematrix`.
Why is there a difference between the two ? is there a way to get the landmarks directly from the bounding box' information instead of having to use this matrix?

Thank you in advance.

**Comment by homuler** [comment]
Well, I think I've been asked similar things before (https://github.com/homuler/MediaPipeUnityPlugin/issues/325).
I'm not going to support older versions in depth, but to begin with, do you understand that the value of y in the Euler angle does not correspond to `Quaternion.y`?

I don't deny the possibility that there was a bug in `Matrix4x4FromBytes`, but can you confirm that you calculate `Quaternion` correctly from the `Matrix4x4`?
