### ISSUE TITLE
Windows 10 build issue with bazel and android build tools

### ISSUE THREAD

**Issue by CharlotteGrossmann** [homuler/MediaPipeUnityPlugin#370]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows10
Target (e.g. desktop cpu, android arm64): desktop cpu
Bazel version: 4.2.0
Python version: 3.9.1
GCC/G++ version: Visual C++ Community 2019
Unity version: 2020
I'm having problems building the whole thing. It get's two errors saying "Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided" and then it fails with this error: File "C:\Users\lomeg\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

Steps to reproduce the issue
python build.py build --desktop cpu --opencv=cmake -v

Full logs
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe //mediapipe_api:mediapipe_proto_srcs
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/44c890cd46fd9aad2b3bf4b13c5f36d8cff795c3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build options --action_env, --features, and --python_path have changed, discarding analysis cache.
ERROR: Error fetching repository: C:/users/lomeg/documents/_uni/_1.semester/mediapipeunityplugin/WORKSPACE:306:23: Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided
INFO: Repository com_google_protobuf instantiated at:
C:/users/lomeg/documents/_uni/_1.semester/mediapipeunityplugin/WORKSPACE:177:13: in
Repository rule http_archive defined at:
C:/_bzl/5bd7red7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided
INFO: Elapsed time: 193.532s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (23 packages loaded, 22 targets configured)
currently loading: @com_google_mediapipe//mediapipe/framework ... (6 packages)
Fetching @local_execution_config_python; fetching
Traceback (most recent call last):
File "C:\Users\lomeg\Documents_UNI_1.Semester\MediaPipeUnityPlugin\build.py", line 392, in
Argument().command().run()
File "C:\Users\lomeg\Documents_UNI_1.Semester\MediaPipeUnityPlugin\build.py", line 109, in run
self._run_command(self._build_proto_srcs_commands())
File "C:\Users\lomeg\Documents_UNI_1.Semester\MediaPipeUnityPlugin\build.py", line 51, in _run_command
return subprocess.run(command_list, check=True)
File "C:\Users\lomeg\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

Additional context
I followed this tutorial https://www.youtube.com/watch?v=kMJOmzmMxZw in addition to the installation guide provided here

**Comment by homuler** [comment]
How about using bazel 4.2.1?

**Comment by CharlotteGrossmann** [comment]
I switched to bazel 4.2.1 but I think I still get the same exact error:

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe //mediapipe_api:mediapipe_proto_srcs`
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: Error fetching repository: C:/users/lomeg/documents/_uni/_1.semester/mediapipeunityplugin/WORKSPACE:306:23: Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided
INFO: Repository com_google_protobuf instantiated at:
  C:/users/lomeg/documents/_uni/_1.semester/mediapipeunityplugin/WORKSPACE:177:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/5bd7red7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided
INFO: Elapsed time: 14.760s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (23 packages loaded, 22 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (6 packages)
    Fetching @local_execution_config_python; fetching
Traceback (most recent call last):
  File "C:\Users\lomeg\Documents\_UNI\_1.Semester\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\lomeg\Documents\_UNI\_1.Semester\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\lomeg\Documents\_UNI\_1.Semester\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\lomeg\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by homuler** [comment]
What is the output of `bazel --version`?

**Comment by CharlotteGrossmann** [comment]
bazel 4.2.1

**Comment by homuler** [comment]
Are you using a different repository by any chance?

> File "C:\Users\lomeg\Documents_UNI_1.Semester\MediaPipeUnityPlugin\build.py", line 392, in
Argument().command().run()

If you're using this repository (at the latest commit), `line 392` must be `line 443`.

**Comment by CharlotteGrossmann** [comment]
I was using an older commit and updated to the newest now. It still didn't change the error message though: 

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/5bd7red7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Error fetching repository: C:/users/lomeg/documents/_uni/_1.semester/mediapipeunityplugin/WORKSPACE:307:23: Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Bazel requires Android build tools version 30.0.0 or newer, 29.0.2 was provided
INFO: Elapsed time: 176.656s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 22 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (7 packages)
    Fetching @com_google_protobuf; fetching
    Fetching ...al/com_google_protobuf; Extracting C:/_bzl/5bd7red7/external/com_google_protobuf/temp9330003041592333629/v3.15.6.tar.gz
    Fetching @local_execution_config_python; fetching
Traceback (most recent call last):
  File "C:\Users\lomeg\Documents\_UNI\_1.Semester\MediaPipeUnityPlugin\build.py", line 443, in <module>
    Argument().command().run()
  File "C:\Users\lomeg\Documents\_UNI\_1.Semester\MediaPipeUnityPlugin\build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\lomeg\Documents\_UNI\_1.Semester\MediaPipeUnityPlugin\build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\lomeg\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//lomeg//Documents//_UNI//_1.Semester//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
I'm sorry, but I can't reproduce the error and I have no idea what caused it.
Will you remove below lines from `WORKSPACE` and try again?
https://github.com/homuler/MediaPipeUnityPlugin/blob/333279e132c9601b1809260732804eaede989d2a/WORKSPACE#L298-L309

**Comment by CharlotteGrossmann** [comment]
That worked! It installed without any errors. Thank you!
