### ISSUE TITLE
Unity Editor Colors messy after run

### ISSUE THREAD

**Issue by gilcu2** [homuler/MediaPipeUnityPlugin#374]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): ArchLinux
- Target Platform: Desktop
- Mobile Device (if the target is Android or iOS):
- MediaPipeUnityPlugin version or commit id: 333279e132c9601b1809260732804eaede989d2a
- Bazel version: 4.2.2
- GCC/G++ version: 11.1.0
- Android NDK version (if the target platform is Android):
- Xcode version (if the target platform is iOS):

**Describe the current behavior**
After run in Unity Editor the colors of the interfaz get messy. For be able to work need to close and start again. Like that problem related to have another scene in hierarchy like Pose Tracking
**Describe the expected behavior**
Unity Editor keep its colors after run the start scene
**Steps to reproduce the issue**
Open project with Unity Editor and play start scene

**Full logs**
Can not read then because of the problem

**Additional context**
Happens in several unity versions like 2021.2.5f1, 2020.3.4f1

**Comment by homuler** [comment]
Can you post a screenshot?
It looks to me like a problem with your Linux or UnityEditor in your environment, doesn't it happen in other projects?

**Comment by gilcu2** [comment]
![Screenshot from 2021-12-10 11-36-45](https://user-images.githubusercontent.com/4577745/145560746-6eb70ee7-edce-46c1-a839-2f1f0f69d45c.png)

**Comment by gilcu2** [comment]
Never notice in other projects

**Comment by homuler** [comment]
> Can not read then because of the problem

OK, please share [Editor.log](https://docs.unity3d.com/Manual/LogFiles.html).

Two things:
- Please use version 2020.3.*, since it's not tested using 2021.2.x.
- It's known that [this plugin doesn't work with OpenGL](https://github.com/homuler/MediaPipeUnityPlugin/wiki/FAQ#internalexception-internal--eglmakecurrent-returned-error-0x3000), so please use Vulkan as the graphic API.

**Comment by gilcu2** [comment]
Never notice in other projects

**Comment by gilcu2** [comment]
With Vulcan worked without problems. Thanks so much for all your work
