### ISSUE TITLE
Download failed: class java.io.IOException Premature EOF

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#375]
**System information**
Ubuntu 20.04
- Target (e.g. desktop cpu  Linux):
- Bazel version:
- Python version:3.4
- GCC/G++ version:8
- Unity version:
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Full logs**
ython build.py build --desktop cpu --opencv cmake -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
2021/12/14 12:56:11 Downloading https://releases.bazel.build/4.2.2/release/bazel-4.2.2-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository com_google_mediapipe instantiated at:
  /home/mediapipe/WORKSPACE:50:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/google/mediapipe/archive/v0.8.8.tar.gz failed: class java.io.IOException Premature EOF
ERROR: An error occurred during the fetch of repository 'com_google_mediapipe':
   Traceback (most recent call last):
	File "/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.8.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/com_google_mediapipe/temp5379232325038352553/v0.8.8.tar.gz: Premature EOF
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.8.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/com_google_mediapipe/temp5379232325038352553/v0.8.8.tar.gz: Premature EOF
ERROR: error loading package '': Encountered error while reading extension file 'apple/repositories.bzl': no such package '@build_bazel_rules_apple//apple': no such package '@com_google_mediapipe//third_party': java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.8.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/com_google_mediapipe/temp5379232325038352553/v0.8.8.tar.gz: Premature EOF
INFO: Elapsed time: 1997.908s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @build_bazel_rules_apple; Restarting. 1952s
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 443, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/mediapipe/build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Additional context**

**Comment by homuler** [comment]
> WARNING: Download from https://github.com/google/mediapipe/archive/v0.8.8.tar.gz failed: class java.io.IOException Premature EOF

I guess you have a network issue.
If you can download `https://github.com/google/mediapipe/archive/v0.8.8.tar.gz` using `wget` or `curl`, try again later.

**Comment by ehsanwwe** [comment]
you say right in the last night when i checked this link show me 404 not found but today is fixed
