### ISSUE TITLE
Installation issue..facing error during the installation

### ISSUE THREAD

**Issue by Jay-artist** [homuler/MediaPipeUnityPlugin#378]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): windows 10
- Target (e.g. desktop cpu, android arm64): desktop
- Bazel version: 4.2
- Python version: 3.9.6
- GCC/G++ version:
- Unity version: 2019.4.15
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
Error are occuring during the last step of installation

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem. 
Same as shown in the video

**Full logs**

**Additional context**

WARNING: Download from https://github.com/bazelbuild/rules_cc/archive/master.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'rules_cc':
   Traceback (most recent call last):
        File "C:/_bzl/k3udm4nm/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to C:/_bzl/k3udm4nm/external/rules_cc/temp5165866799698437181/master.zip: GET returned 404 Not Found
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/k3udm4nm/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to C:/_bzl/k3udm4nm/external/rules_cc/temp5165866799698437181/master.zip: GET returned 404 Not Found
INFO: Repository com_google_protobuf instantiated at:
  C:/users/jai/connection/mediapipeunityplugin/WORKSPACE:177:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/k3udm4nm/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target @rules_pkg//:build_zip: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to C:/_bzl/k3udm4nm/external/rules_cc/temp5165866799698437181/master.zip: GET returned 404 Not Found
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to C:/_bzl/k3udm4nm/external/rules_cc/temp5165866799698437181/master.zip: GET returned 404 Not Found
INFO: Elapsed time: 43.883s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 11 targets configured)
    currently loading: @bazel_tools//tools/cpp ... (7 packages)
Traceback (most recent call last):
  File "C:\Users\Jai\connection\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\Jai\connection\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\Jai\connection\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by LGuilhermeRodrigues** [comment]
It looks like this is already fixed by #211. Are you using the latest version of the plugin?
You can check your current WORKSPACE file and do this changes:
```diff
http_archive(
    name = "rules_cc",
-    strip_prefix = "rules_cc-master",
+    strip_prefix = "rules_cc-main",
-    urls = ["https://github.com/bazelbuild/rules_cc/archive/master.zip"],
+    urls = ["https://github.com/bazelbuild/rules_cc/archive/main.zip"],
)
```

**Comment by Jay-artist** [comment]
I did the changes recommended by you, but still I'm facing some errors

ERROR: C:/users/jai/connect/mediapipeunityplugin/WORKSPACE:80:18: syntax error at '=': expected ,
ERROR: error loading package 'external': Failed to parse WORKSPACE file
INFO: Elapsed time: 0.293s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "C:\Users\Jai\connect\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\Jai\connect\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\Jai\connect\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by LGuilhermeRodrigues** [comment]
try this:
```
http_archive(
    name = "rules_cc",
    strip_prefix = "rules_cc-main",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/main.zip"],
)
```

**Comment by homuler** [comment]
Use a newer version.

**Comment by Jay-artist** [comment]
New version of what all things??

**Comment by Jay-artist** [comment]
> try this:
> 
> ```
> http_archive(
>     name = "rules_cc",
>     strip_prefix = "rules_cc-main",
>     urls = ["https://github.com/bazelbuild/rules_cc/archive/main.zip"],
> )
> ```

**Comment by Jay-artist** [comment]
I changed the things but got new errors due after the changes i did which was recommended by you

ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/awfxpwvd/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/awfxpwvd/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/awfxpwvd/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe' is not executable. Is it the python binary?
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/awfxpwvd/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/awfxpwvd/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/awfxpwvd/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 36.311s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 22 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework/formats/annotation ... (6 packages)
    Fetching @com_google_protobuf; Restarting.
Traceback (most recent call last):
  File "C:\Users\Jai\connect\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\Jai\connect\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\Jai\connect\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by homuler** [comment]
> New version of what all things??

You're using an old version of the plugin, so download the latest version.

> Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//Jai//connection//MediaPipeUnityPlugin//env//Scripts//python.exe' is not executable. Is it the python binary?

Check your python path.

**Comment by Jay-artist** [comment]
Sir where can I get the new plugin ??
As I was following a video & I got this only plugin.

**Comment by homuler** [comment]
Well, it's published on this repository, and I'd rather like to ask you how you downloaded an older version.

**Comment by Jay-artist** [comment]
I took the new version of plugin which was provided in this repository. 
But now I'm facing this error
Sir, can you please help me

ERROR: An error occurred during the fetch of repository 'com_google_mediapipe':
   Traceback (most recent call last):
        File "C:/_bzl/sidmbi55/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/sidmbi55/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out
ERROR: error loading package '': Encountered error while reading extension file 'apple/repositories.bzl': no such package '@build_bazel_rules_apple//apple': no such package '@com_google_mediapipe//third_party': java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out
INFO: Elapsed time: 280.968s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @build_bazel_rules_apple; Restarting. 238s
Traceback (most recent call last):
  File "C:\Users\Jai\bridge\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\Jai\bridge\MediaPipeUnityPlugin\build.py", line 113, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\Jai\bridge\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//Jai//bridge//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
