### ISSUE TITLE
Cannot change the name of subgraph

### ISSUE THREAD

**Issue by fayang** [homuler/MediaPipeUnityPlugin#379]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): MacOS 11.6
- Target (e.g. desktop cpu, android arm64): desktop
- Bazel version: 4.2.2
- Python version: 3.9
- GCC/G++ version:
- Unity version: 2020.3.23
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
Cannot change the name of subgraph

**Steps to reproduce the issue**
1. Open ```mediapipe_api/modules/iris_landmark/BUILD```, change ```register_as = "IrisLandmarksFromFaceLandmarksCpu"``` to ```register_as = "IrisLandmarksFromFaceLandmarksCpu2"``` and save.
2. Run ```python build.py build --desktop cpu --include_opencv_libs -vv``` and build successfully.
3. Open ```Assets/Mediapipe/Samples/Scenes/Iris Tracking/iris_tracking_cpu.txt```, change ```calculator: "IrisLandmarksFromFaceLandmarksCpu"``` to ```calculator: "IrisLandmarksFromFaceLandmarksCpu2"``` and save.
4. In Unity, run and select "Iris Tracking" solution and get error "No registered object with name: IrisLandmarksFromFaceLandmarksCpu2"

**Full logs**
IrisTrackingSolution: Mediapipe.MediaPipeException: NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: IrisLandmarksFromFaceLandmarksCpu2; Unable to find Calculator "IrisLandmarksFromFaceLandmarksCpu2"
  at Mediapipe.Status.AssertOk ()

**Additional context**

Did I miss something to make this work? Thanks in advance.

**Comment by homuler** [comment]
I think you're doing in a correct way (I would change [this line](https://github.com/homuler/MediaPipeUnityPlugin/blob/47ee481b38af8be602b3e4103f08257bd16ba947/mediapipe_api/modules/iris_landmark/iris_landmarks_from_face_landmarks_cpu.pbtxt#L9) too, but it won't affect the results.).

Please check if `IrisLandmarksFromFaceLandmarksCpu2` is registered by running the below command.
```sh
objdump -t Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib | grep IrisLandmarksFromFaceLandmarksCpu
```

> 0000000000009034 l     F __TEXT,__text __ZN9mediapipe34IrisLandmarksFromFaceLandmarksCpu2D1Ev
0000000000009038 l     F __TEXT,__text __ZN9mediapipe34IrisLandmarksFromFaceLandmarksCpu2D0Ev

If `IrisLandmarksFromFaceLandmarksCpu` still exists (note that `Cpu` is followed by `2` in the above output), make sure you have saved the modified files and that you've not made any typos.

**Comment by fayang** [comment]
Thanks for your detailed replay, it works after restarting Unity:).
