### ISSUE TITLE
DllNotFoundException: mediapipe_c

### ISSUE THREAD

**Issue by elblogbruno** [homuler/MediaPipeUnityPlugin#38]
Hello,
Sorry for posting some issues lately!
I have build the sdk for windows succesfully, but get this issue when playing on editor.
What could it be?

**Comment by homuler** [comment]
What is the output when you check **Load on startup** in **Plugin load settings** of `libmediapipe_c.dll` and click **Apply**?
If it says
```txt
Plugins: Failed to load 'Assets/MediaPipe/SDK/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.
```
then please examine what are the missing dependencies. (cf. https://github.com/lucasg/Dependencies)

**Comment by elblogbruno** [comment]
I will check that thanks!

**Comment by elblogbruno** [comment]
got it working, i needed to load on startup and then change to desktop target
this  needs to be changed because if i am on android as target it runs the android code not the windows one:
![image](https://user-images.githubusercontent.com/10481058/105611416-7f3b7980-5db5-11eb-8b44-3860902171b8.png)

thanks

**Comment by elblogbruno** [comment]
![image](https://user-images.githubusercontent.com/10481058/105611789-b6128f00-5db7-11eb-844e-8de879c06b0e.png)
Simply add and or statement.

**Comment by homuler** [comment]
Fixed by https://github.com/homuler/MediaPipeUnityPlugin/commit/e37321911f905a4c48197b8a30a6b5a06e0ecbe3

**Comment by sewonist** [comment]
In my case, I've fixed with repair to c++ Redistributable for Visual Studio 2015, 2017 and 2019. 

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by smtabatabaie** [comment]
Hi, I'm also receiving this error when I run Start Scene "DllNotFoundException: "mediapipe_c". I'm running on MacOS with an M1 Mac and Unity2020.3.33f1 and I have built for desktop without GPU using "python build.py build --desktop cpu -vv" without any errors. I also checked "Load on startup" for "libmediapipe_c.dll" and my platform is "PC,mac & linus standalone" in my build settings. I'd appreciate it if you can help me with this.

**Comment by homuler** [comment]
@smtabatabaie See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#m1-mac.
> > :warning: use UnityEditor (Apple silicon) (>= 2021.2.2f1) to open the project.

`opencv_world*.dll` is only used on Windows, so you can ignore it safely.

**Comment by smtabatabaie** [comment]
> > I'm running on MacOS with an M1 Mac and Unity2020.3.33f1
> 
> @smtabatabaie See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#m1-mac.
> 
> > > ⚠️ use UnityEditor (Apple silicon) (>= 2021.2.2f1) to open the project.
> 
> `opencv_world*.dll` is only used on Windows, so you can ignore it safely.

Thanks very much. That was exactly the issue! I installed Unity Apple silicon and could run the scene in my editor.

**Comment by AbhisKmr** [comment]
> > > I'm running on MacOS with an M1 Mac and Unity2020.3.33f1
> > 
> > 
> > @smtabatabaie See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#m1-mac.
> > > > ⚠️ use UnityEditor (Apple silicon) (>= 2021.2.2f1) to open the project.
> > 
> > 
> > `opencv_world*.dll` is only used on Windows, so you can ignore it safely.
> 
> Thanks very much. That was exactly the issue! I installed Unity Apple silicon and could run the scene in my editor.

Hey @smtabatabaie how did you solve the issue I'm facing the same problem and I have the same system configure that you have 'Mac m1'

**Comment by smtabatabaie** [comment]
Hi AbhisKmr, I'm using 2022.1.0f1 on M1 Mac. Can you describe what you're getting in more detail? Thanks

**Comment by yalegria** [comment]
Having the same issue, using 2021.3.15f1, any help?
