### ISSUE TITLE
WebGL DLLNotFoundException: Unable To load DLL 'mediapipe_c': The specified module could not be found.

### ISSUE THREAD

**Issue by msandikli** [homuler/MediaPipeUnityPlugin#383]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10 Home Single Language 20H2 X64 
- Chrome Version: 96
- Target (e.g. desktop cpu, android arm64): WebGL
- Bazel version: 
- Python version: 3.9
- GCC/G++ version:
- Unity version: 2020.3.8f
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**

Hi, I'm trying to get the build for Web GL and I'm getting the errors in the screenshot. I know that the topic is duplicate and there is no WebGL support yet, but I need it, can you give me an idea how to proceed? Thank you so much

**Full logs**
![image](https://user-images.githubusercontent.com/69441254/146504680-b65be537-646e-4289-a892-9ae51df9e86c.png)
![image](https://user-images.githubusercontent.com/69441254/146504778-87fb4793-7e19-47a8-9046-5d6ae1783196.png)

**Additional context**
Thank you again

**Comment by homuler** [comment]
See https://github.com/google/mediapipe/issues/1818 and https://github.com/google/mediapipe/issues/877

Duplicates #49

**Comment by homuler** [comment]
See #395
