### ISSUE TITLE
java.io.IOException: Error downloading ...: Read timed out

### ISSUE THREAD

**Issue by PallaviPandurangPawar** [homuler/MediaPipeUnityPlugin#384]
Sir/ma'am,
Can you please give a solution to solve this error.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Windows 10
- Target (e.g. desktop cpu, android arm64): desktop
- Bazel version: 4.2
- Python version: 3.9
- GCC/G++ version:
- Unity version: 2019.4.15
- Android NDK version (if building for Android):
- Xcode version (if building for iOS):

**Describe the problem**
Facing issue during the installation 

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

set BAZEL_VC= C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC

set BAZEL_VS= C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

set BAZEL_VC_FULL_VERSION=14.29.30133

set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

pip install virtualenv

virtualenv env

env\Scripts\activate

pip install numpy

dir

set PYTHON_BIN_PATH=
C:\Users\pawar\link\MediaPipeUnityPlugin\env\Scripts\python.exe

python build.py build --desktop cpu --include_opencv_libs -v

**Full logs**

**Additional context**

ERROR: An error occurred during the fetch of repository 'com_google_mediapipe':
   Traceback (most recent call last):
        File "C:/_bzl/sidmbi55/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/sidmbi55/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out
ERROR: error loading package '': Encountered error while reading extension file 'apple/repositories.bzl': no such package '@build_bazel_rules_apple//apple': no such package '@com_google_mediapipe//third_party': java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out
INFO: Elapsed time: 280.968s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @build_bazel_rules_apple; Restarting. 238s
Traceback (most recent call last):
  File "C:\Users\pawar\link\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\pawar\link\MediaPipeUnityPlugin\build.py", line 113, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\pawar\link\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//pawar//ink//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by cjm1105** [comment]
did you install opencv? if you not then type
`python build.py build --desktop cpu --opencv=cmake -v`

**Comment by homuler** [comment]
> Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/google/mediapipe/archive/v0.8.9.tar.gz] to C:/_bzl/sidmbi55/external/com_google_mediapipe/temp9506750363564723181/v0.8.9.tar.gz: Read timed out

There is a problem with your network.
Can you download https://github.com/google/mediapipe/archive/v0.8.9.tar.gz ?
If so, try again.
Otherwise, see https://github.com/google/mediapipe/issues/581 and https://github.com/homuler/MediaPipeUnityPlugin/issues/281.

**Comment by PallaviPandurangPawar** [comment]
Sir , Sorry to bother you again I tried to run the code again in good network but still facing issues. 

Traceback (most recent call last):
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 120, in run
    self._run_command(self._build_proto_dlls_commands())
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nuget install -o .nuget -Source https://api.nuget.org/v3/index.json' returned non-zero exit status 1.

**Comment by homuler** [comment]
The important part of the log has been omitted, but I guess you've not finished the 8th step.
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10

**Comment by gabbar69** [comment]
set path for nuget and also for  MSYS2 and then install bazel and python 3.9.x and open the repo folder and change in build.py  and change **argparse.BooleanOptionalAction**  to **_'store_true'_** then

 open workspace file and find this lines 

**http_archive(
    name = "opencv",
    build_file = "@//third_party:opencv.BUILD",
    sha256 = "5e37b791b2fe42ed39b52d9955920b951ee42d5da95f79fbc9765a08ef733399",
    strip_prefix = "opencv-3.4.16",
    urls = ["https://github.com/opencv/opencv/archive/3.4.16.tar.gz"],
)**


**_changes_**
strip_prefix = "opencv-3.4.10",
 urls = ["https://github.com/opencv/opencv/archive/3.4.10.tar.gz"]

replace this changes

after that find this lines

**new_local_repository(
    name = "windows_opencv",
    build_file = "@//third_party:opencv_windows.BUILD",
    path = "C:\\opencv\\build",
)**

set your path for openCV.

after that open third party folder and find opencv_windows.BUILD file and open it

then find this lines

OPENCV_VERSION = "3416"  # 3.4.16

and replace with it with this

**OPENCV_VERSION = "3410"  # 3.4.10**


after that set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0



pip install numpy

pip install virtualenv
virtualenv env

env\Scripts\activate

pip install numpy





set PYTHON_BIN_PATH=C:\Users\Capermint\AppData\Local\Programs\Python\Python39\python.exe

python build.py build --desktop cpu --include_opencv_libs -v

**_try to build but you will get error for java.io_**

so in the error message you will get checksum no. which is different from 

**_sha256 = "5e37b791b2fe42ed39b52d9955920b951ee42d5da95f79fbc9765a08ef733399",_**

so copy that checksum no. and open workspace file and find this lines 

**http_archive(
    name = "opencv",
    build_file = "@//third_party:opencv.BUILD",
    sha256 = "5e37b791b2fe42ed39b52d9955920b951ee42d5da95f79fbc9765a08ef733399",
    strip_prefix = "opencv-3.4.10",
    urls = ["https://github.com/opencv/opencv/archive/3.4.10.tar.gz"],
)**

changes 

sha256 = "PASTE COPIES CHECKSUM CODE HERE",


AFTER THAT TRY AGAIN  

IF NOT ABLE TO BUILD THEN FEEL FREE TO CONTECT ME.

**Comment by PallaviPandurangPawar** [comment]
Sir I have changed the nuget path and sha256 checksum but facing these errors. 
Sir how can I get the proper solution for these errors? 

Server terminated abruptly (error code: 2, error message: 'Stream removed', log file: 'c:\_bzl\hlvrulrq\server\jvm.out')

Traceback (most recent call last):
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 113, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 37.

**Comment by gabbar69** [comment]
can you share your anydesk id on divyesh.sondagar.ds69@gmail.com

**Comment by homuler** [comment]
@PallaviPandurangPawar Please retry it a few times.
If the problem persists, run `python build.py build --desktop cpu --include_opencv_libs -vv` (note `-vv`) and share the _full_ log, please.

**Comment by homuler** [comment]
> can you share your anydesk id on divyesh.sondagar.ds69@gmail.com

@gabbar69 It looks to me like you're trying to run a scam. Can you tell me what the purpose is?

**Comment by PallaviPandurangPawar** [comment]
Sir, I resolved my nuget issue and tried to run the file again but got these errors.
This time it is showing that build is successfully completed but getting this errors. 
Sir please guide me to solve these errors.

INFO: Analyzed target //mediapipe_api:opencv_libs (0 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:opencv_libs up-to-date:
  bazel-bin/mediapipe_api/opencv_libs.zip
INFO: Elapsed time: 97.004s, Critical Path: 4.06s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\opencv_libs.zip' to 'build\Plugins\OpenCV'...
INFO (build.py): Built native libraries for Desktop
INFO (build.py): Installing built resources...
DEBUG (build.py): Copying 'build' to 'Packages\com.github.homuler.mediapipe\Runtime' recursively...
DEBUG (build.py): Running `cp -r build/* Packages\com.github.homuler.mediapipe\Runtime`
'cp' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 176, in run
    self._copytree(_BUILD_PATH, _INSTALL_PATH)
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 77, in _copytree
    self._run_command(['cp', '-r', f'{source}/*', dest])
  File "C:\Users\pawar\bridge\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cp -r build/* Packages\com.github.homuler.mediapipe\Runtime' returned non-zero exit status 1.

**Comment by homuler** [comment]
> 'cp' is not recognized as an internal or external command,

Probably you've not installed MSYS2 properly.
Read [step 1](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10) again carefully.
