### ISSUE TITLE
IOS build error for _glReadPixels

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#385]
Hi
tnx for helping us

the IOS build success without any error
so I add the plugin to project and ...

I publish IOS project without any problem

at Xcode when I want to build application
I got this two to error

Undefined. _glReadPixels and _glFlush for architecture arm64

```
Undefined symbols for architecture arm64:
  "_glReadPixels", referenced from:
      _UnsafeNativeMethods_glReadPixels_mB6CD520FF4A77019A700CDEB6646E61DED73EC85 in MediaPipeSDK4.o
     (maybe you meant: _UnsafeNativeMethods_glReadPixels_mB6CD520FF4A77019A700CDEB6646E61DED73EC85)
  "_glFlush", referenced from:
      _UnsafeNativeMethods_glFlush_m31511D22964C1C47F83A18E543AD163B2EEE80CD in MediaPipeSDK4.o
     (maybe you meant: _UnsafeNativeMethods_glFlush_m31511D22964C1C47F83A18E543AD163B2EEE80CD)
ld: symbol(s) not found for architecture arm64

```

**Comment by homuler** [comment]
Maybe you've started UnityEditor before building iOS framework and `MediaPipeUnity.framework.meta` was deleted.
Check `FrameworkDependencies`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/ee27e24e963c5485a36f5a63fc7215e732f4d49f/Packages/com.github.homuler.mediapipe/Runtime/Plugins/iOS/MediaPipeUnity.framework.meta#L80

See also https://github.com/homuler/MediaPipeUnityPlugin/issues/156
