### ISSUE TITLE
installation error Docker Windows Container

### ISSUE THREAD

**Issue by mostafamdy** [homuler/MediaPipeUnityPlugin#389]
Hi , I have problem in installation 
I use Docker Windows Container in windows10
when I try to run this command `python build.py build --desktop cpu --opencv cmake -vv`
it fails 
error log 

> ERROR: C:/_bzl/3vmcl3ou/external/com_google_protobuf/BUILD:211:11: Compiling src/google/proto
> buf/util/type_resolver_util.cc [for host] failed: (Exit 2): cl.exe failed: error executing co
> mmand
>   cd C:/_bzl/3vmcl3ou/execroot/mediapipe_api
>   SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14
> .29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program
>  Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\
> 10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;
> C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
>     SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.
> 29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Commo
> n7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\I
> DE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\
> BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Fil
> es (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files
> (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Wi
> ndows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program
> Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft
> .NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Co
> mmon7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\
> Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\C
> ommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019
> \BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
>     SET PWD=/proc/self/cwd
>     SET RUNFILES_MANIFEST_ONLY=1
>     SET TEMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
>     SET TMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
>   C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bi
> n/HostX64/x64/cl.exe @bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/type_res
> olver_util.obj.params
> Execution platform: @local_execution_config_platform//:platform
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\incl
> ude\xlocnum(1602): fatal error C1060: compiler is out of heap space
> Target //mediapipe_api:mediapipe_proto_srcs failed to build
> INFO: Elapsed time: 8.654s, Critical Path: 7.60s
> INFO: 131 processes: 129 internal, 2 local.
> FAILED: Build did NOT complete successfully
> Traceback (most recent call last):
>   File "C:\mediapipe\build.py", line 443, in <module>
>     Argument().command().run()
>   File "C:\mediapipe\build.py", line 112, in run
>     self._run_command(self._build_proto_srcs_commands())
>   File "C:\mediapipe\build.py", line 52, in _run_command
>     return subprocess.run(' '.join(command_list), check=True, shell=shell)
>   File "C:\Python\lib\subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --actio
> n_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSO
> R_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PR
> OCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero e
> xit status 1
>  
>   
> full log 
> C:\mediapipe>python build.py build --desktop cpu --opencv cmake -vv
> INFO (build.py): Building protobuf sources...
> DEBUG (build.py): Running bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_
> BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTUR
> E --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVIS
> ION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
> WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/toolchains/archive/
> d781e89e2ee797ea7afd0c8391e761616fc5d50d.tar.gz failed: class com.google.devtools.build.lib.b
> azel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archi
> ve/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.li
> b.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/0a8
> c6996bd6a58eb0e7e2fe049ac67bf663e1950.tar.gz failed: class com.google.devtools.build.lib.baze
> l.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/tensorflow/version_check.bzl:42:14:
> Current Bazel is not a release version, cannot check for compatibility.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/tensorflow/version_check.bzl:43:14: Make sure
>  that you are running at least Bazel 1.0.0.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'com_google_absl' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'com_google_protobuf' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'com_google_googletest' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'rules_python' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'bazel_skylib' because it already exists.
> DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:109:14:
> Warning: skipping import of repository 'pybind11' because it already exists.
> DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by mo
> difying arguments shallow_since = "1564776078 -0400"
> DEBUG: Repository rules_python instantiated at:
>   C:/mediapipe/WORKSPACE:41:23: in <toplevel>
>   C:/_bzl/3vmcl3ou/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
>   C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
> Repository rule git_repository defined at:
>   C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
> DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modify
> ing arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
> DEBUG: Repository rules_cc instantiated at:
>   C:/mediapipe/WORKSPACE:84:13: in <toplevel>
> Repository rule http_archive defined at:
>   C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets conf
> igured).
> INFO: Found 1 target...
> ERROR: C:/_bzl/3vmcl3ou/external/com_google_protobuf/BUILD:211:11: Compiling src/google/proto
> buf/timestamp.pb.cc [for host] failed: (Exit 2): cl.exe failed: error executing command
>   cd C:/_bzl/3vmcl3ou/execroot/mediapipe_api
>   SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14
> .29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program
>  Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\
> 10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;
> C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
>     SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.
> 29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Commo
> n7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\I
> DE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\
> BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Fil
> es (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files
> (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Wi
> ndows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program
> Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft
> .NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Co
> mmon7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\
> Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\C
> ommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019
> \BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
>     SET PWD=/proc/self/cwd
>     SET RUNFILES_MANIFEST_ONLY=1
>     SET TEMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
>     SET TMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
>   C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bi
> n/HostX64/x64/cl.exe @bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/timestam
> p.pb.obj.params
> Execution platform: @local_execution_config_platform//:platform
> external/com_google_protobuf/src\google/protobuf/wire_format_lite.h(1097): fatal error C1060:
>  compiler is out of heap space
> Target //mediapipe_api:mediapipe_proto_srcs failed to build
> INFO: Elapsed time: 12.341s, Critical Path: 11.50s
> INFO: 134 processes: 129 internal, 5 local.
> FAILED: Build did NOT complete successfully
> Traceback (most recent call last):
>   File "C:\mediapipe\build.py", line 443, in <module>
>     Argument().command().run()
>   File "C:\mediapipe\build.py", line 112, in run
>     self._run_command(self._build_proto_srcs_commands())
>   File "C:\mediapipe\build.py", line 52, in _run_command
>     return subprocess.run(' '.join(command_list), check=True, shell=shell)
>   File "C:\Python\lib\subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --actio
> n_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSO
> R_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PR
> OCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero e
> xit status 1

**Comment by homuler** [comment]
Please read the log before creating an issue.

> external/com_google_protobuf/src\google/protobuf/wire_format_lite.h(1097): fatal error C1060:
compiler is out of heap space

Depending on your machine, you need to adjust `--cpus` and `--memory` options. 
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/FAQ#how-much-cpu-and-memory-should-be-allocated-to-a-docker-container for more details.

By the way, as you know, there is a template for this kind of issue, so use [the format](https://github.com/homuler/MediaPipeUnityPlugin/blob/ee27e24e963c5485a36f5a63fc7215e732f4d49f/.github/ISSUE_TEMPLATE/build-installation-issue.md) to describe your issue.

**Comment by mostafamdy** [comment]
I'm sorry for wasting your time
but I have another problem can you help me 

> ERROR: C:/_bzl/3vmcl3ou/external/com_google_mediapipe/mediapipe/util/tracking/BUILD:410:11: Compiling mediapipe/util/tracking/motion_estimation.cc failed: (Exit 2): cl.exe failed: error executing command
  cd C:/_bzl/3vmcl3ou/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits
\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.
0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\P
rogram Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\
TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Prog
ram Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Fr
amework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\Windows\system32;C:\Program File
s (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\
Ninja
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=8e0c
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Python//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
    SET TMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe @bazel-out/x64_windows-opt/bin/external/com_google_mediapipe/mediapipe/util/tracking/_objs/motion
_estimation/motion_estimation.obj.params
Execution platform: @local_execution_config_platform//:platform
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\utility(319): warning C4244: '=': conversion from '_Ty' to '_Ty2', possible loss of data
        with
        [
            _Ty=int
        ]
        and
        [
            _Ty2=float
        ]
external/com_google_mediapipe/mediapipe/util/tracking/motion_estimation.cc(2131): note: see reference to function template instantiation 'std::pair<float,float> &std::pair<float,float>::operator =<float,int,0>(s
td::pair<float,int> &&) noexcept' being compiled
external/com_google_mediapipe/mediapipe/util/tracking/motion_estimation.cc(2130): note: see reference to function template instantiation 'std::pair<float,float> &std::pair<float,float>::operator =<float,int,0>(s
td::pair<float,int> &&) noexcept' being compiled
C:\_bzl\3vmcl3ou\execroot\mediapipe_api\external\eigen_archive\Eigen\src/Core/NumTraits.h(165): fatal error C1060: compiler is out of heap space
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 391.891s, Critical Path: 242.48s
INFO: 65 processes: 43 internal, 22 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\mediapipe\build.py", line 443, in <module>
    Argument().command().run()
  File "C:\mediapipe\build.py", line 141, in run
    self._run_command(self._build_desktop_commands())
  File "C:\mediapipe\build.py", line 52, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_e
nv PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake //mediapipe_api:mediapipe_desktop' returned non-z
ero exit status 1.

**Comment by homuler** [comment]
> but I have another problem can you help me

No, not another, just the same.
> C:_bzl\3vmcl3ou\execroot\mediapipe_api\external\eigen_archive\Eigen\src/Core/NumTraits.h(165): fatal error C1060: compiler is out of heap space

**Comment by mostafamdy** [comment]
thanks it works good 

but it takes a lot of time so can I copy 

> Packages\com.github.homuler.mediapipe\Runtime\Plugins\Android\mediapipe_android.aar

to  other projects  instead of building it again

**Comment by gabbar69** [comment]
@mostafamdy have you solve error?

**Comment by Thomas-Boi** [comment]
> thanks it works good
> 
> but it takes a lot of time so can I copy
> 
> > Packages\com.github.homuler.mediapipe\Runtime\Plugins\Android\mediapipe_android.aar
> 
> to other projects instead of building it again

That should be fine. As long as your other projects are Android, it would work. When in doubt, just try and test it
