### ISSUE TITLE
Progress update request

### ISSUE THREAD

**Issue by Hakazaba** [homuler/MediaPipeUnityPlugin#39]
First of all, thank you for the wonderful work you've been doing on this Homuler. 

Do you mind please releasing some a statement on how you're continuing to develop the mediapipe unity plugin and you're expectations on how long they will take?

I'm personaly interested in when you expect holistic to be ready

**Comment by homuler** [comment]
First, Holistic sample will be released this week.

> Do you mind please releasing some a statement on how you're continuing to develop the mediapipe unity plugin and you're expectations on how long they will take?

I'll try keeping [TODO list](https://github.com/homuler/MediaPipeUnityPlugin#todo) up to date, but for now I cannot say which feature will be implemented when.
