### ISSUE TITLE
Build on M1 mac failed(nuget command not found)

### ISSUE THREAD

**Issue by peke-tictactoe** [homuler/MediaPipeUnityPlugin#390]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): mac OS Monterey
- Target (e.g. desktop cpu, android arm64):desktop gpu
- Bazel version: 4.2.2
- Python version: 3.10.1
- GCC/G++ version: 13.0.0
- Unity version: 2020.3.23

**Describe the problem**
After doing the build command(python build.py build --desktop gpu -vv), it says nuget: command not found.

**Full logs**
MacBook-Pro:MediaPipeUnityPlugin $ python build.py build --desktop gpu -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/a87782c34d667d1c1a18fe82a9a7abfc72fd345b.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/fc70a32ecd248dd7612d75d2177125ed14541367.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_baze/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
DEBUG: Repository rules_cc instantiated at:
  /Users/xxx/MediaPipeUnityPlugin/WORKSPACE:84:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /Users/xxx/MediaPipeUnityPlugin/WORKSPACE:41:23: in <toplevel>
  /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /private/var/tmp/_bazel/4970e67c106780447d5d2e1b186e884f/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 19.573s, Critical Path: 16.10s
INFO: 214 processes: 3 internal, 211 darwin-sandbox.
INFO: Build completed successfully, 214 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
/bin/sh: nuget: command not found
Traceback (most recent call last):
  File "/Users/xxx/MediaPipeUnityPlugin/build.py", line 451, in <module>
    Argument().command().run()
  File "/Users/xxx/MediaPipeUnityPlugin/build.py", line 120, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/Users/xxx/MediaPipeUnityPlugin/build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/Users/xxx/.pyenv/versions/3.10.1/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nuget install -o .nuget -Source https://api.nuget.org/v3/index.json' returned non-zero exit status 127.

**Additional context**
I have done the [arch -x86_64 /usr/local/homebrew/bin/brew install nuget] command.

**Comment by homuler** [comment]
Probably your `PATH` does not include `/usr/local/Homebrew/bin`.
```sh
echo $PATH
```

If you're using `zsh`, your `.zprofile` should be like this.
```txt
# ~/.zprofile
export PATH=/usr/local/Homebrew/bin:$PATH

eval "$(/opt/homebrew/bin/brew shellenv)"
```

**Comment by peke-tictactoe** [comment]
Thank you. It worked fine. I thought I had included the PATH but I didn't.
