### ISSUE TITLE
Custom TFLite model for objection detection

### ISSUE THREAD

**Issue by MatheusPixlog** [homuler/MediaPipeUnityPlugin#393]
I'm trying to change the default object detection to a custom one that I created using EfficientDet-Lite however it´s not working properly, does anyone have a tutorial or a indication on how to help?

**Comment by homuler** [comment]
Are you able to run it with the official sample?
If not, please ask it in the official community.
If you can run it in C++ but not in Unity, then please share your current code.

**Comment by pasmai** [comment]
I would also like to know more about this. How to convert an existing `.tflite` model to `.bytes` and import it.

I have converted my model to `.pb` format and changed the ending to `.bytes` according to [this post](https://stackoverflow.com/questions/50239077/how-to-convert-tensorflow-pb-file-to-bytes).

I then went into all the files that referred to the old model and changed the name.
```sh
grep -l -r "mediapipe/models" . *.txt
./Mediapipe/Samples/Scenes/Object Detection/object_detection_cpu.txt
./Mediapipe/Samples/Scenes/Object Detection/object_detection_gpu.txt
./Mediapipe/Samples/Scenes/Object Detection/object_detection_opengles.txt
```

<br>

But I get this error:
```
Error tflite The model is not a valid Flatbuffer buffer
Error Unity MediaPipeException: INTERNAL: Graph has errors: 
Error Unity Calculator::Open() for node "TfLiteInferenceCalculator" failed: ; Failed to load model from path mediapipe/models/yolov5n6_size_320.tfliteflite_model_loader.cc:41) 
```

**Comment by homuler** [comment]
Please make sure `TFLiteInferenceCalculator` can load your custom model first.

> I would also like to know more about this. How to convert an existing .tflite model to .bytes and import it.
I have converted my model to .pb format and changed the ending to .bytes according to this post.

If you have a `.tflite` model file, all you need to do is just to change the extention from `.tflite` to `.bytes`.
`.tflite` and `.pb` are different format and I think `.pb` format won't work with `TFLiteInferenceCalculator`.

**Comment by pasmai** [comment]
Thank you, using `.tflite` model and changing the ending worked and it was able to load the model. 
But the inference result was not correct because I think it is not doing the Non-maximum Suppression (NMS) step correctly for this model.

**Comment by homuler** [comment]
> I think it is not doing the Non-maximum Suppression (NMS) step correctly for this model.

This is out of scope for this project, so if you want to ask someone, please ask elsewhere.

**Comment by Sketh14** [comment]
@pasmai Hey, did you find any solution to this by any chance? I am facing the same issue with the custom object detection as the model is not recognising the object properly. It only works if I place the camera up close to the object, but even that fails most of the time. I have tried it the official mediapipe version on Android and the results were far better than this.

I am checking out the code if it's working properly but that is the only thing that I can do. I don't have any knowledge on how the Inference Calculator Or the Non-Max Suppression Calculator works. Would really help me a lot if you have found a fix for this.

**Comment by UnityDev1021** [comment]
Leaving this here if anyone else is stuck. 
So I was checking out some other issues and found that there is a settings menu in the scene. On clicking that, there are 2 running modes Async and Sync modes. The object detection works properly on Sync mode although the frame rate is lower which I can understand as Inference takes time on cpu. So try switching to Sync mode, that will work out and in case you need any help for making custom model for object detection, please make sure that you are using ssd_mobilenet_v2 as that is the only supported version for object detection for mediapipe at the moment along with Tensorflow 1.15. Any model made with Tensorflow 2.0 and above would not work with mediapipe for now, hope they update this soon. 
Anyways, would like to know if there is anything else I can do to increase the frame rate, that would be helpful.

**Comment by pasmai** [comment]
@Sketh14 No updates from my side.

**Comment by FUBAR2077** [comment]
@UnityDev1021 I have ALMOST made it according to what you suggested - i have custom ssd_mobilenet_v2 model but I'm having a hard time converting it and using it with mediapipe. Any chance for quick call?
my email is gkiernozek@gmail.com 
I will show what I have and I would really appreciate any tips in this matter
