### ISSUE TITLE
why my MediaPipeUnity.framework has no .h file?

### ISSUE THREAD

**Issue by tyym1314** [homuler/MediaPipeUnityPlugin#394]
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2):12.0.1
- Target (e.g. desktop cpu, android arm64):ios arm64
- Bazel version:4.2.1
- Python version:3.9.9
- GCC/G++ version:
- Unity version:2020.3.23
- Android NDK version (if building for Android):none
- Xcode version (if building for iOS):13.1

when i completed doing the install,i run common "python build.py build --desktop cpu  --ios arm64 -vv"
then i found that ,the MediaPipeUnity.framework has no .h file,why????

**Comment by kottelo** [comment]
[https://github.com/homuler/MediaPipeUnityPlugin/issues/394#issue-1089576416](https://github.com/homuler/MediaPipeUnityPlugin/issues/394#issue-1089576416) @FUBAR2077

**Comment by kottelo** [comment]
Q tal el reloj

**Comment by kottelo** [comment]
chatsettingsbackup.db.crypt15

**Comment by homuler** [comment]
Because header files are not exported explicitly.
Please let me know if there are any use cases that require header files.
