### ISSUE TITLE
Objectron frame rate and tracking accuracy problem

### ISSUE THREAD

**Issue by H3NRILiN** [homuler/MediaPipeUnityPlugin#396]
Hi, I currently working on a project that try to mimic the try-on-shoe app like Wanna Kick using the Objectron.

Now, I already put the shoes into the scene, and using the FrameAnnotation to get Position, Rotation and Scale (I'm not using the scale Vector3 straight, but `(x+y+z)/3*Vector3.one` to maintain the shoe shape, but I'm not sure if it's right way to do it) 

However, I notice that the framerate on pc and android are both not high enough like Wanna Kick or Lens Studio. (30 PFS or higher)
![1640837956001](https://user-images.githubusercontent.com/43886037/147721439-d58da588-88ad-4f8a-b78b-be894d50138d.gif)

Furthermore, the tracking is not very accurate, it always has micro jiggling, and some angle of the foot is unrecognizable - either shoe is not showing or the shoe is dancing like crazy

I want to know if the frame rate and accuracy can be improved? and how? or are both inevitable?

thanks.

**Comment by homuler** [comment]
> I notice that the framerate on pc and android are both not high enough

First, please compare the performance with the official sample.
If it is significantly slower than the official one, please tell me where it takes a long time.

> I want to know if the frame rate and accuracy can be improved? and how? or are both inevitable?

Please ask it in the official community.

**Comment by nenenkosi** [comment]
> Now, I already put the shoes into the scene, and using the FrameAnnotation to get Position, Rotation, and Scale

@H3NRILiN can you please explain to me how you got the Position, Rotation on the shoe if you can share code or a GitHub link that can help to any kind of help will be highly appreciated

**Comment by H3NRILiN** [comment]
> > Now, I already put the shoes into the scene, and using the FrameAnnotation to get Position, Rotation, and Scale
> 
> @H3NRILiN can you please explain to me how you got the Position, Rotation on the shoe if you can share code or a GitHub link that can help to any kind of help will be highly appreciated

Hi, I followed the [#301 inst](https://github.com/homuler/MediaPipeUnityPlugin/issues/301#issuecomment-932098018) instruction to solve them

**Comment by harshitht789** [comment]
Hello ,
Im also trying to build objectron using unity project. While testing out the cup model, it doesnt even recognise the cup at all, whereas the original mediapipe(android build from mediapipe website) recognises the same cup accurately. Is there any additional build i have to do for objectron or are there any additional packages required to run objectron on unity.

<img src="https://user-images.githubusercontent.com/86595895/148192954-7fce56d8-75f6-4d3a-95f5-612310bb3546.jpg" width=25% height=25%> (Original Mediapipe)

<img src="https://user-images.githubusercontent.com/86595895/148192965-6c9a4cd0-8283-4d7b-991a-599c08815288.PNG" width=25% height=25%> (Unity Mediapipe Plugin)

**Comment by homuler** [comment]
@harshitht789 By default, the sample app uses Shoe model (cf. https://google.github.io/mediapipe/solutions/objectron.html#desktop).
To use Cup model, click settings button and select `Cup` from the Category dropdown.
![Screenshot_20220110_113127](https://user-images.githubusercontent.com/4690128/148712126-936114ec-4717-4473-941c-35ac1e4e34f5.png)

**Comment by nenenkosi** [comment]
> Hi, I followed the #301 inst instruction to solve them

@H3NRILiN thanks for your help I also followed the instructions but the only issue I have now is getting the correct position the value am getting are not correct or is there something am doing wrong because am using the same code you suggested here is my code below I tried to different methods but they don’t work 
`
  
       var rectTransform = GameObject.Find("Annotatable Screen").GetComponent<RectTransform>();

      // get postion with Translation values
       var getPostion = CameraCoordinate.GetLocalPosition(rectTransform , target.Translation[0], target.Translation[1], target.Translation[2], new Vector2(1.0f,1.0f), new Vector2(0.0f,0.0f), zScale, rotationAngle, isMirrored);

       // get postion with 3D point values
       var getPostionPoint3D = CameraCoordinate.GetLocalPositionPoint3D(rectTransform,target.Keypoints[0].Point3D,new Vector2(1.0f,1.0f), new Vector2(0.0f,0.0f), zScale, rotationAngle, isMirrored);
`
https://github.com/homuler/MediaPipeUnityPlugin/blob/0604681ed9cb41d5955709ffa7d537f20058ab00/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/CameraCoordinate.cs#L34-L47

**Comment by H3NRILiN** [comment]
> > Hi, I followed the #301 inst instruction to solve them
> 
> @H3NRILiN thanks for your help I also followed the instructions but the only issue I have now is getting the correct position the value am getting are not correct or is there something am doing wrong because am using the same code you suggested here is my code below I tried to different methods but they don’t work `
> 
> ```
>    var rectTransform = GameObject.Find("Annotatable Screen").GetComponent<RectTransform>();
> 
>   // get postion with Translation values
>    var getPostion = CameraCoordinate.GetLocalPosition(rectTransform , target.Translation[0], target.Translation[1], target.Translation[2], new Vector2(1.0f,1.0f), new Vector2(0.0f,0.0f), zScale, rotationAngle, isMirrored);
> 
>    // get postion with 3D point values
>    var getPostionPoint3D = CameraCoordinate.GetLocalPositionPoint3D(rectTransform,target.Keypoints[0].Point3D,new Vector2(1.0f,1.0f), new Vector2(0.0f,0.0f), zScale, rotationAngle, isMirrored);
> ```
> 
> `
> 
> https://github.com/homuler/MediaPipeUnityPlugin/blob/0604681ed9cb41d5955709ffa7d537f20058ab00/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/CameraCoordinate.cs#L34-L47

Hi, sorry for late reply

My solution is
```
Vector3 GetLocalPositionFromKeypoint(AnnotatedKeyPoint keyPoint, RotationAngle imageRotation, float zScale, bool isMirrored)
{
     var localPos = CameraCoordinate.GetLocalPosition(_screen, keyPoint.Point3D, _graph.focalLength, _graph.principalPoint, zScale, imageRotation, isMirrored);
     return localPos;
}
```

```
[SerializeField] ObjectronGraph _graph;
```

```
RotationAngle rotationAngle = _graph.rotation;
```

```
bool isMirrored = ImageSourceProvider.ImageSource.isFrontFacing;
```

zScale is 1

**Comment by RICKYLIKEBIRD** [comment]
> > > 嗨，我按照#301 inst 指令解決了它們
> > 
> > 
> > @H3NRILiN感謝您的幫助，我也按照說明進行操作，但我現在唯一的問題是獲得正確的位置，得到的值不正確，或者有什麼地方做錯了，因為我使用的是您在此處建議的相同代碼，下面是我的代碼我嘗試了不同的方法，但它們不起作用`
> > ```
> >    var rectTransform = GameObject.Find("Annotatable Screen").GetComponent<RectTransform>();
> > 
> >   // get postion with Translation values
> >    var getPostion = CameraCoordinate.GetLocalPosition(rectTransform , target.Translation[0], target.Translation[1], target.Translation[2], new Vector2(1.0f,1.0f), new Vector2(0.0f,0.0f), zScale, rotationAngle, isMirrored);
> > 
> >    // get postion with 3D point values
> >    var getPostionPoint3D = CameraCoordinate.GetLocalPositionPoint3D(rectTransform,target.Keypoints[0].Point3D,new Vector2(1.0f,1.0f), new Vector2(0.0f,0.0f), zScale, rotationAngle, isMirrored);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> > https://github.com/homuler/MediaPipeUnityPlugin/blob/0604681ed9cb41d5955709ffa7d537f20058ab00/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/CameraCoordinate.cs#L34-L47
> 
> 您好，抱歉回复晚了
> 
> 我的解決方案是
> 
> ```
> Vector3 GetLocalPositionFromKeypoint(AnnotatedKeyPoint keyPoint, RotationAngle imageRotation, float zScale, bool isMirrored)
> {
>      var localPos = CameraCoordinate.GetLocalPosition(_screen, keyPoint.Point3D, _graph.focalLength, _graph.principalPoint, zScale, imageRotation, isMirrored);
>      return localPos;
> }
> ```
> 
> `_graph`變量是 ObjectronGraph參考
> 
> ```
> [SerializeField] ObjectronGraph _graph;
> ```
> 
> imageRotation 參數是 RotationAangle 來自`_graph.rotation`
> 
> ```
> RotationAngle rotationAngle = _graph.rotation;
> ```
> 
> ```
> bool isMirrored = ImageSourceProvider.ImageSource.isFrontFacing;
> ```
> 
> zScale 為 1

@H3NRILiN 
Hi,I have a problem with the _screen variable,_screen is of type Mediapipe.Unity.Screen but the first parameter of GetLocalPosition is of type UnityEngine.RectTransform,maybe i overlooked something?
thanks you example.

**Comment by homuler** [comment]
@H3NRILiN 
> Furthermore, the tracking is not very accurate, it always has micro jiggling

I'm implementing `MIN_DETECTION_CONFIDENCE` / `MIN_TRACKING_CONFIDENCE` options (#295) and just tested them with Objectron.
At least, it seems that "micro jiggling" you mentioned can be reduced by increasing `MIN_DETECTION_CONFIDENCE`.
