### ISSUE TITLE
Failed to fetch an output packet. Ubuntu 20.04

### ISSUE THREAD

**Issue by yellowflash07** [homuler/MediapipeUnityPlugin#4]
After building the necessary libraries, running the scene gives warning errors:

Failed to fetch an output packet, rendering the input image
UnityEngine.Debug:LogWarning(Object)
DefaultGraphOnGPU:RenderOutput(Texture2D, Color32[]) (at Assets/Mediapipe/Examples/Scripts/DefaultGraphOnGPU.cs:19)
d__10:MoveNext() (at Assets/Mediapipe/Examples/Scripts/Director.cs:67)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

Any idea how to fix this?

**Comment by homuler** [comment]
Please tell me 
1. the resolution and FPS of your camera.
2. which files do you put under `Assets/SDK/Models`.

And if you modified the BUILD file, will you also paste your BUILD file contents?

**Comment by homuler** [comment]
This patch may be helpful.

`C/third_party/mediapipe_debug.patch`
```mediapipe_debug.patch
diff --git a/mediapipe/framework/calculator_graph.cc b/mediapipe/framework/calculator_graph.cc
index 702497f..ae2b250 100644
--- a/mediapipe/framework/calculator_graph.cc
+++ b/mediapipe/framework/calculator_graph.cc
@@ -934,6 +934,7 @@ void CalculatorGraph::RecordError(const ::mediapipe::Status& error) {
   {
     absl::MutexLock lock(&error_mutex_);
     errors_.push_back(error);
+    LOG(INFO) << error;
     has_error_ = true;
     scheduler_.SetHasError(true);
     for (const auto& stream : graph_output_streams_) {
```

`C/WORKSPACE`
```WORKSPACE
...
# mediapipe
http_archive(
  name = "com_google_mediapipe",
  sha256 = "67f4b98f837ef74f72014d25d3ede23d06518104cd9160f6e5938df4f6adf906",
  strip_prefix = "mediapipe-0.7.9",
  patches = [
      "@//third_party:mediapipe_debug.patch", # add this line
      "@//third_party:mediapipe_model_path.diff",
  ],
  patch_args = [
      "-p1",
  ],
  urls = ["https://github.com/google/mediapipe/archive/v0.7.9.tar.gz"],
)
...
```

With this, if you build libs and run the scene, some error logs must be output under `Logs/Mediapipe`.

**Comment by yellowflash07** [comment]
Ahhh i am sorry. i forgot to place the models! after cloning the git thrice i just forgot. 

it works perfectly!

**Comment by homuler** [comment]
Well, it is not convenient to put model files manually, so I'll change the build process probably.
