### ISSUE TITLE
Can't run DesktopCPU for the second time

### ISSUE THREAD

**Issue by jerrysheen** [homuler/MediaPipeUnityPlugin#40]
Hi, I'm trying to run the project on windows for DesktopCPU.

When I click the unity play button for the first time, everyting works perfect. But after I stop it and then play it for second time, the unity stuck and I have to restart the unity.

after restart then everyting can work again. please help me to figure it out...

thanks!

**Comment by jerrysheen** [comment]
Hi, homuler.
 Is this prblem caused because Glog didn't shutdown perfectly?  Since I did a little test for onApplicationQuit.

I add glog.shutdown(). And the unity project will then close instead of stuck...

Sorry thats just my guess. I'm new to unity

**Comment by homuler** [comment]
Thank you for your help!
I also suspect `SceneDirector#OnDisable` must be changed to `SceneDirector#OnApplicationQuit`, but I have not tested it yet.

**Comment by jsaon-L** [comment]
me too 
in unbuntu  can not quit UnityEditor

**Comment by homuler** [comment]
Fixed at https://github.com/homuler/MediaPipeUnityPlugin/commit/6cc0ed15ee74447cf651b76f01cb9bbe6bfece4b .
