### ISSUE TITLE
Memory issue with TextureFrame

### ISSUE THREAD

**Issue by patrick508** [homuler/MediaPipeUnityPlugin#400]
OS Platform and Distribution (e.g., Linux Ubuntu 20.04): Mac & Windows
Target Platform: IOS
Mobile Device (if the target is Android or iOS): Iphone 11
MediaPipeUnityPlugin version or commit id: 0.5.0
Xcode version (if the target platform is iOS): 13.2.1

The memory in our application keeps running up. I pin pointed it down a bit by just going throug the flow and commenting out some stuff. I ended up with the OnRelease event in the Release function in TextureFrame.cs

If I comment out this event memory doesn't run up. So I went 1 layer further and it brings me to the OnTextureFrameRelease() function in TextureFramePool.cs which listens to this event. And eventually the screenshot I attached below seems to be causing the trouble.
![image](https://user-images.githubusercontent.com/9352192/147951114-dfc814da-37db-46aa-a92f-98c69e35fa73.png)

The weird part is, if I comment out the GetID() call and just put a Guid.NewGuid() the memory also stops. Any idea? 

Steps to reproduce are running mediapipe on an image, but then constantly. So we keep feeding it frames(which we take from the camera). We make a snapshot > send it to mediapipe & ask for pose. We changed so much that pasting code here will result in a whole book. Hopefully this is enough

**Comment by homuler** [comment]
Please use [issue template](https://github.com/homuler/MediaPipeUnityPlugin/blob/efc7664e3ed5d997ee618c364bd2256896a43aae/.github/ISSUE_TEMPLATE/bug-report.md).

> The memory in our application keeps running up.

Is it reproducible in the sample app?

**Comment by patrick508** [comment]
> Please use [issue template](https://github.com/homuler/MediaPipeUnityPlugin/blob/efc7664e3ed5d997ee618c364bd2256896a43aae/.github/ISSUE_TEMPLATE/bug-report.md).
> 
> > The memory in our application keeps running up.
> 
> Is it reproducible in the sample app?

I updated the post! Also yes it's reproducable everytime. In the Unity editor & on device

**Comment by homuler** [comment]
Thanks.

> it's reproducable everytime.

I'd like to know if it occurs without any changes.
You say:
> We changed so much that pasting code here will result in a whole book.

If you can reproduce the issue with the sample app (without changes), then please describe the procedure when using the sample app _as is_. 
On the other hand, if you need to change some code, then the true cause may not be written in the description (please share the minimal code to reproduce the issue).

> MediaPipeUnityPlugin version or commit id: 0.5.0

The version is too old, so will you try v0.8.2 (without changing code)'s sample app and check if the issue occurs?

**Comment by homuler** [comment]
Closing it due to inactivity.
If the issue still exists and help is needed, please reopen it.
