### ISSUE TITLE
FEATURE SUGGESTION: Convert Issue Templates to Issue Forms

### ISSUE THREAD

**Issue by Thomas-Boi** [homuler/MediaPipeUnityPlugin#405]
**Describe the feature and the current behavior/state.**
Some of the Issues don't follow the template well. It was also a bit troublesome to fill out certain fields like the logs.

**Solution**
If you are interested, I can make PR converting your current templates to [Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) instead. A repo I maintain use them and it's great for me so far. It makes it easy to fill out fields and enforce mandatory fields too. 

**Additional context**
Add any other context here.

This is just a suggestion. The current templates work fine but it could be better. I can also make it for you only if you want the feature.

**Comment by homuler** [comment]
Thanks for the suggestion.
I didn't know that, but it looks good, so I'll use it later.

**Comment by homuler** [comment]
Done by #431
