### ISSUE TITLE
Use the plugin in another project

### ISSUE THREAD

**Issue by gilcu2** [homuler/MediaPipeUnityPlugin#407]
How can I use the plugin in another project and keep the plugin updated?
Maybe a git subrepo?
Someone have done this?

**Comment by homuler** [comment]
I'll write about it in the wiki later, but I think a combination of git submodule and [local package](https://docs.unity3d.com/Manual/upm-ui-local.html) will work.

**Comment by ROBYER1** [comment]
Having some issues on Windows with the bytes files for solutions not being moved across when exporting packages using the new package system. It's very close to a simple way to update and copy the files to new projects so hoping that issue can be fixed
https://github.com/homuler/MediaPipeUnityPlugin/issues/556

**Comment by homuler** [comment]
Now it is documented [here](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project).
