### ISSUE TITLE
build Hand tracking only

### ISSUE THREAD

**Issue by mostafamdy** [homuler/MediaPipeUnityPlugin#408]
How can I make build for specific mediapipe solution (Hand Tracking ) instead of building all  solutions  
using windows docker to build for android

**Comment by homuler** [comment]
1. Comment out unused calculators
https://github.com/homuler/MediaPipeUnityPlugin/blob/efc7664e3ed5d997ee618c364bd2256896a43aae/mediapipe_api/BUILD#L105-L140

2. Comment out unused models
https://github.com/homuler/MediaPipeUnityPlugin/blob/efc7664e3ed5d997ee618c364bd2256896a43aae/mediapipe_api/BUILD#L163-L189

3. Build and install again

If you've already installed the plugin, you may want to run `python build.py uninstall` first to remove unused assets.

**Comment by gabbar69** [comment]
> How can I make build for specific mediapipe solution (Hand Tracking ) instead of building all solutions using windows docker to build for android

@mostafamdy can you make build for android and is that working?

**Comment by mostafamdy** [comment]
for building only hand tracking solution I didn't  try it yet 
but I tried building for all mediapipe solutions and it works fine with windows docker but it take a lot of  time in building
