### ISSUE TITLE
Instant Motion Tracking

### ISSUE THREAD

**Issue by AlaaEltayeb** [homuler/MediaPipeUnityPlugin#41]
Hello there, thank you for the work you are doing here,

I noticed you are working of the instant motion tracking on  a new branch, do you have a time frame for it? I was trying to add to your plugin but it's a bit complicated for me.

Best Regards
Alaa Eltayeb

**Comment by homuler** [comment]
I just started to implement it and I hope to finish it in 2 weeks or so, but I'm not sure how long it will take actually.

**Comment by AlaaEltayeb** [comment]
Ok thank you

**Comment by Vladislav489** [comment]
> I just started to implement it and I hope to finish it in 2 weeks or so, but I'm not sure how long it will take actually.

Hello, have any update?

**Comment by Vladislav489** [comment]
can there be approximate dates?

**Comment by homuler** [comment]
Update:
It works on Desktop, but crashes on Android. I've not found the cause yet and it'll take more time.

**Comment by Vladislav489** [comment]
> Обновление:
> работает на рабочем столе, но вылетает на Android. Я еще не нашел причину, и это займет больше времени.
> 
> Даже официальные аварии APK под аналогичным условием (сборки `facedetectiongpu`с `instant_motion_tracking_deps`в режиме отладки).
> [google / mediapipe # 1617](https://github.com/google/mediapipe/issues/1617)

This is already a cool result, thanks for your work, I look forward to the next updates

**Comment by homuler** [comment]
released at [v0.5.0](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.5.0).
