### ISSUE TITLE
when i open the project , it show 

### ISSUE THREAD

**Issue by huangrainqi** [homuler/MediaPipeUnityPlugin#414]
Packages\com.github.homuler.mediapipe\Runtime\Scripts\External\SerializedProto.cs(10,12): error CS0246: The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)
Packages\com.github.homuler.mediapipe\Runtime\Scripts\Unity\Annotation\PointAnnotation.cs(10,24): error CS0234: The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)
Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListVectorPacket.cs(12,61): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionPacket.cs(16,21): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)
Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryPacket.cs(27,30): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)
Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraphConfigExtension.cs(13,84): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListPacket.cs(27,30): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

**Comment by homuler** [comment]
duplicates #177.

Read README first.
