### ISSUE TITLE
Getting, "Plugins: Couldn't open libmediapipe_c.dylib", warning and "DllNotFoundException: mediapipe_c" error during run.

### ISSUE THREAD

**Issue by likwifi** [homuler/MediaPipeUnityPlugin#418]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04, WSL2): Mac OS Monterey M1
- Target (e.g. desktop cpu, android arm64): arm64, silicone
- Bazel version:latest
- Python version:3.9.9
- GCC/G++ version:
- Unity version:2020.3.22f1
- Xcode version (if building for iOS):

**Describe the problem**
Getting, "Plugins: Couldn't open libmediapipe_c.dylib", warning and "DllNotFoundException: mediapipe_c" error during run.
All steps are completed per documentation build was successful.

**Steps to reproduce the issue**
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Full logs**
Warning on startup
Plugins: Couldn't open ...Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib, error: dlopen(...Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib, 0x0002): tried: '...Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libmediapipe_c.dylib' (no such file), '/usr/lib/libmediapipe_c.dylib' (no such file)

Error during run.
DllNotFoundException: mediapipe_c
Mediapipe.Glog.set_Logtostderr (System.Boolean value) (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/Glog.cs:27)
Mediapipe.Unity.GlobalConfigManager.SetFlags () (at Assets/Mediapipe/Samples/Common/Scripts/GlobalConfigManager.cs:118)
Mediapipe.Unity.Bootstrap+<Start>d__17.MoveNext () (at Assets/Mediapipe/Samples/Common/Scripts/Bootstrap.cs:48)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

**Additional context**

**Comment by homuler** [comment]
Please read https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception first

**Comment by Speykious** [comment]
This issue also persists on MediaPipe.NET (see [the following CI run](https://github.com/vignetteapp/MediaPipe.NET/runs/4885524520?check_suite_focus=true)).
[We have packaged all Mediapipe runtimes correctly](https://github.com/vignetteapp/MediaPipe.NET.Runtime) (`mediapipe_c.dll` on Windows, `libmediapipe_c.so` on Linux, `libmediapipe_c.dylib` on MacOS) and with bundled OpenCV (build argument `opencv=cmake`). Windows and Linux can detect and load the shared library correctly, but not MacOS for some reason.
We followed [the instructions](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception) (everything except 6) but unfortunately without success.
Running the `ostool -L <lib>` command (equivalent of `ldd` on Linux) seems to indicate that there are no missing dependencies...

**Comment by homuler** [comment]
@Speykious Your project has a completely different setup than this, so I don't think we can say it's the same problem.
In fact, the error message doesn't even tell us if the true library path (i.e. where `libmediapipe_c.dylib` exists) has really been searched.

> In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libmediapipe_c, 1): image not found

Have you set `DYLD_PRINT_LIBRARIES`?

**Comment by homuler** [comment]
@likwifi 
> '...Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), 

I guess you're not using Apple Silicon UnityEditor.
https://github.com/homuler/MediaPipeUnityPlugin/issues/388#issuecomment-1000059515

**Comment by Speykious** [comment]
> @Speykious Your project has a completely different setup than this, so I don't think we can say it's the same problem. In fact, the error message doesn't even tell us if the true library path (i.e. where `libmediapipe_c.dylib` exists) has really been searched.
> 
> > In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libmediapipe_c, 1): image not found
> 
> Have you set `DYLD_PRINT_LIBRARIES`?

I did, but couldn't find anything related to `mediapipe`, even by filtering with `grep`...

**Comment by Speykious** [comment]
Update: I think you were right in pointing the completely different setup. Upon trying the following command to try to force it to load the library:
```
DYLD_INSERT_LIBRARIES=./bin/Debug/net6.0/osx-x64/libmediapipe_c.dylib dotnet test --filter "FullyQualifiedName~TimestampTest.IsDisposed_ShouldReturnFalse_When_NotDisposedYet" --runtime osx-x64
```

It turned out that there was an *undefined symbol* in our `libmediapipe_c.dylib` library:
![image](https://user-images.githubusercontent.com/13885008/150472715-73acb40e-2bdb-45ac-aa6f-a36537cd330c.png)

I'll have to investigate why this symbol is undefined.

**Comment by likwifi** [comment]
> @likwifi
> 
> > '...Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')),
> 
> I guess you're not using Apple Silicon UnityEditor. See [#388 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/388#issuecomment-1000059515).

solved my issue, thanks.

**Comment by homuler** [comment]
@Speykious Maybe AVFoundation is not installed to your environment.

**Comment by Speykious** [comment]
Maybe. Though it didn't work after installing FFmpeg, which I assume installs AVFoundation when on Mac. I'll have to check.
