### ISSUE TITLE
Steps to implement mediapipe API to existing unity project

### ISSUE THREAD

**Issue by likwifi** [homuler/MediaPipeUnityPlugin#422]
**Describe the feature and the current behavior/state.**
I'm trying to add a pose tracking feature so that my character at the unity scene will be able to repeat movements captured by pose tracking from a selfie camera.
Not sure how exactly to do that, as there is no guide for implementing this for a working application.
Any advice on how this can be achieved?

**Comment by ROBYER1** [comment]
Have you built the sample app from this repo to see it all running? That is essentially an empty project just with Mediapipe in it. Then you can go ahead and copy across the files needed to make it run in your other project easily.

**Comment by homuler** [comment]
Is this same as #411?

**Comment by likwifi** [comment]
I'm a newbie at Unity,
per instructions, it is required to open start scene, then hand tracking scene,
these scenes contain some extra elements like canvas, some buttons, etc.
can't find any API for getting just pose movements from just camera input,
https://www.youtube.com/watch?v=eZbi08dNCOU
currently watching some tutorial on how to achieve pose tracking for project from scratch.
It will be very useful if there is some official API on how to configure this from just a camera input.
