### ISSUE TITLE
How can I use dataset from google repo?

### ISSUE THREAD

**Issue by gittiekchan** [homuler/MediaPipeUnityPlugin#425]
I want to use the dataset from google [repo](https://github.com/google-research-datasets/Objectron) or this already use?. What should I do?
Thank you.

**Comment by homuler** [comment]
Well, actually I don't know what you'd like to know exactly.
This project aims to run MediaPipe (graphs and trained models) on Unity and is not concerned with how to train a model from data set.

Are you asking how to run Objectron or Objectron models which MediaPipe has not publish yet (e.g. bike, laptop) ?

**Comment by gittiekchan** [comment]
I want to improve the tracking quality for shoe. So I just ask about can we use that dataset in Unity?

**Comment by homuler** [comment]
I see.
Obviously this has nothing to do with this project, so please ask where it is relevant.
