### ISSUE TITLE
mediapipe unity plugin low FPS

### ISSUE THREAD

**Issue by CYChuang** [homuler/MediaPipeUnityPlugin#430]
Hello everyone:
We use mediapipe unity plugin build a project like video
https://drive.google.com/file/d/1rRrlYNVcPWF70FS-Ux69YmX5hqBWyVxt/view?usp=sharing
However the FPS is very low.
We want to know it's the mediapipe's problem or we can fix it by other solution.
If someone know how to slove it, please tell me thanks.

**Comment by homuler** [comment]
Please run [the official example](https://google.github.io/mediapipe/solutions/objectron.html) on your device.
If your app (and this plugin's sample app) runs noticeably slower than the official example, please let me know.

**Comment by gianluca-amprimo** [comment]
> Please run [the official example](https://google.github.io/mediapipe/solutions/objectron.html) on your device.
> If your app (and this plugin's sample app) runs noticeably slower than the official example, please let me know.

Hello @homuler, i have posted a similar issue for handtracking, if you can check it out. The same issue is  happening both with my code and with the official example when running the build outside the editor.

**Comment by brian-studioRouleau** [comment]
I don't know if it's related, and I was going to do some additional testing-- but I noticed that going from Unity 2020.3.22f1 to a higher version (in our case, 2021.2.8f1), caused additional lag/fps dropping, both on android and ios.  Definitely noticed a difference in performance between the two Unity versions.

**Comment by nenenkosi** [comment]
> We use mediapipe unity plugin build a project like video
https://drive.google.com/file/d/1rRrlYNVcPWF70FS-Ux69YmX5hqBWyVxt/view?usp=sharing

@CYChuang I just watched the video and am happy with the results. 
I have been trying to get the shoe position for a long time and I am not successful I followed all the instructions and code snippet provided with no success can you please explain to me how you got the shoe position and how you did the shoe occlusion please share the shader you used to get the shoe occlusion can you please send it to my email at nenenkosi@gmail.com

Any kind of help will be highly appreciated
