### ISSUE TITLE
Pose landmarks Vs Pose world landmarks confusion

### ISSUE THREAD

**Issue by Hakazaba** [homuler/MediaPipeUnityPlugin#432]
### Description

Hello, I am trying to use the mediapipe unity plugin to drive a 3D rig, and am a little confused about how to do so. Currently i am using the data from poseworldlandmarks and i'm confused with how the data all seems to be relative to the hips. Can i make this data relative to world instead?

Alternatively, should i be using poselandmarks?

**Comment by homuler** [comment]
>  i'm confused with how the data all seems to be relative to the hips.

Please read the official document.
https://google.github.io/mediapipe/solutions/pose.html#pose_world_landmarks

> `x`, `y` and `z`: Real-world 3D coordinates in meters with the origin at the center between hips.

**Comment by Hakazaba** [comment]
Based on this, it seems there is no way to get the depth of the midpoint of the hips. Is that right?

**Comment by homuler** [comment]
It depends on how much accuracy you need.
If you know FoV of the camera, I think you can estimate it (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/327#issuecomment-962595883)

**Comment by Hakazaba** [comment]
Hmm, i suppose the distance between the two hips can be used to figure it out in a similar way. Thank you

**Comment by NurbNerb** [comment]
Yes indeed. I had to create a midpoint for hips and spine and get bearing rotations from left and right hips. The same went for shoulders, Spine and Neck.
