### ISSUE TITLE
How i can detect the front and the back of hand 

### ISSUE THREAD

**Issue by rabiaoutanarhrite** [homuler/MediaPipeUnityPlugin#433]
### Description

im looking for detecting the front and the back of hand , is there any way to do that using mediapipe ?

**Comment by homuler** [comment]
> If you don't know how to use MediaPipe itself, please ask it in the official community.

Please ask it elsewhere next time.
Since we know whether the detected hand is the right or left hand (cf. https://google.github.io/mediapipe/solutions/hands.html#multi_handedness), we can determine the orientation of the palm by the position of the thumb.
