### ISSUE TITLE
Would I use Window 10 Home to run the example?

### ISSUE THREAD

**Issue by tomtomtong** [homuler/MediaPipeUnityPlugin#434]
### Description

I only use Window 10 Home. I ask my friend to compile the required libraries to me by Window 10 Professional.
Would I use the libraries to run the Unity example in Window 10 Home ?

Thank for any reply.

**Comment by homuler** [comment]
If you're asking whether the libraries (i.e. `libmediapipe_c.dll`) compiled on Windows 10 Pro can run on your Windows 10 Home, the answer is yes.

**Comment by tomtomtong** [comment]
Thx This is really a big help.
