### ISSUE TITLE
Unable to start web camera on windows standalone app

### ISSUE THREAD

**Issue by PallaviPandurangPawar** [homuler/MediaPipeUnityPlugin#436]
### Plugin Version or Commit ID

0.6.2

### Unity Version

2020.3.23f1

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Command Sequences

Hello Sir,
I have search about this error in the past issues i.e #186 , #260 , #227 
But could not solve my error.
I wanted to build standalone app on windows, but web camera is not working.
Please help me to build a standalone app. 

Plugins: Failed to load 'C:/Users/Jai/jewelleryconnect/MediaPipeUnityPlugin/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dll' because one or more of its dependencies could not be loaded.

Images attached are 
1) Inspector image of opencv
2) Inspector image of libmediapipe_c.dll
3) Image of Standalone app

![Opencv](https://user-images.githubusercontent.com/71063679/151606176-4a252558-fad1-4787-877b-983fa92ac3a8.jpeg)
![mediapipe](https://user-images.githubusercontent.com/71063679/151606180-f2e44248-a239-4c68-9285-68f2e83c6ffb.jpeg)
![Standalone](https://user-images.githubusercontent.com/71063679/151606272-51c0e770-2108-4a6e-b672-c78ef2d7f683.jpeg)

### Log

I have followed all your steps for installment of the plugin.
Things are working perfectly in Unity Editor but when it comes to standalone app the web camera does not get started.

**Comment by TKTSWalker** [comment]
Make sure the system settings allow Unity to use the camera, otherwise the camera is nonexistent!

**Comment by homuler** [comment]
> Make sure you're using the latest version.

Please use v0.8.2.

**Comment by PallaviPandurangPawar** [comment]
Hello Sir,
Sir when I build the standalone app for DesktopDemo unity scene from MediaPipeUnityPlugin github folder then web camera gets on in the standalone app.
![hand](https://user-images.githubusercontent.com/71063679/152179262-796e9815-2fa4-46af-accc-f011438bae95.JPG)

Sir, when I try to implement same thing in another project folder so in this web camera does not get started.
![bracelet](https://user-images.githubusercontent.com/71063679/152179824-3eb623d4-e17f-4240-9d91-6b593f5ea0d4.jpeg)

**Comment by homuler** [comment]
So the original error has been resolved?
If you have solved the problem, I'm glad if you describe the cause and/or how you solved it, so that you can help others who face the same problem later.

If you don't know how to import the plugin to another project, please try to find similar issues first (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/437#issuecomment-1025055230), and if they still don't resolve your problem, please open a new issue.

**Comment by PallaviPandurangPawar** [comment]
I got my resolved by changing the version of opencv ie 
default version is 3.4.10 and I had 3.4.16 
Replace this opencv version to default version and it will start working.

**Comment by KiranJodhani** [comment]
Make sure Asset Loader Type in Bootstrap is Streaming Asset. I was facing issue. Changing to this worked for me
Cheers

**Comment by rafaelski** [comment]
I will explain a set of steps that many users have reported to have helped them resolve webcam issues in the standalone build using the MediaPipe Unity examples, without changing the original flow of the Image Segmentation project.

1. Configure the Asset Loader in Bootstrap
Open the Hierarchy of the Image Segmentation scene.
Look for the GameObject called “Bootstrap” (or check the “Solution” object that contains the Bootstrap component).
In the Inspector, locate the “Asset Loader Type” property.
Change this property to Streaming Asset.
This option ensures that the models and resources are loaded from the StreamingAssets folder, which has been essential for the standalone build to be able to access the webcam reliably.

2. Configure the Player Settings for Windows
Go to Edit > Project Settings > Player.
In the Other Settings tab for Windows, uncheck the Auto Graphics API for Windows option.
Next, in the list of graphics APIs, add Direct3D11 (remove other APIs if present).
This setting improves compatibility and has helped some users resolve issues with WebCamTexture in standalone.
3. Check Windows 11 Privacy Settings
Open Windows Settings (press Windows + I).
Select Privacy & Security, then Camera.
Make sure that:
Allow apps to access your camera is enabled;
Allow desktop apps to access your camera is also enabled.
Test using another application (such as the Windows Camera app) to confirm that the webcam is working normally.
4. Run the Application as Administrator
After generating the build, right-click on the executable and choose Run as administrator.
Running with elevated privileges can help ensure that there are no camera access blocks.
5. Force the Built-in Camera to Be Selected (if necessary)
In the Image Segmentation project, the webcam initialization script (ImageSource.cs) typically uses the first device listed. If the device selected in your build is not the correct one, you can:

Open the ImageSource.cs script (located in Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/ImageSource.cs) and temporarily add a log to list all available devices using WebCamTexture.devices.
Check the logs to see if the built-in device appears and, if necessary, modify the selection to force the use of the built-in device (for example, selecting the one whose name contains "integrated" or "built-in").
Note: This modification is for diagnostic purposes only and, once you have confirmed which device works, you can keep this logic without changing the functionality of the rest of your pipeline.
6. Verify that Resources Are Included in the Build
Make sure that the StreamingAssets folder is included in the build. This is important to ensure that MediaPipe templates and files are loaded correctly.
In the Bootstrap Object Inspector, confirm that all asset references (templates, etc.) are correct and pointing to the StreamingAssets folder.
Recap
Asset Loader Type: Bootstrap → Streaming Asset
Player Settings: Disable Auto Graphics API; use Direct3D11
Windows Privacy: Allow camera access for desktop applications
Runtime: Run as administrator
Diagnostics: List devices in the log to confirm that the integrated camera is being selected
StreamingAssets: Verify that assets are included in the build
These are the steps that the community has reported to resolve webcam issues in standalone builds using the MediaPipe Unity examples. I recommend following this list, testing each step, and checking the logs (e.g. by adding Debug.Log at strategic points in the ImageSource script) to identify that the webcam is initializing correctly.
