### ISSUE TITLE
how to use this plugin in another Unity Project

### ISSUE THREAD

**Issue by adjsnlxx** [homuler/MediaPipeUnityPlugin#437]
### Description

how to import this plugin and how to use this plugin

**Comment by homuler** [comment]
duplicates #252, #407 

The main body of the plugin can be found under [Packages/com.github.homuler.mediapipe](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Packages/com.github.homuler.mediapipe) and at least you need to import or copy it to your project.
If you'd like to use sample code as a template, you may also want to copy [Assets/Mediapipe/Samples](https://github.com/homuler/MediaPipeUnityPlugin/tree/master/Assets/Mediapipe/Samples).

See https://docs.unity3d.com/Manual/PackagesList.html for more details.
