### ISSUE TITLE
MediaPipe Framework not found error while building  for iOs.

### ISSUE THREAD

**Issue by Arccus-games** [homuler/MediaPipeUnityPlugin#440]
### Description

While building an xcode build of the project, build is failed and I am seeing this error. MediaPipe framework not found. I xcode framework sections there is framework added but it was grayed out. After this, I check Packages\com.github.homuler.mediapipe\Runtime\Plugins\iOS\MediaPipeUnity.framework and this folder is empty. Even in the xcode build folder, Frameworks\com.github.homuler.mediapipe\Runtime\Plugins\iOS\ folder is empty.

**Comment by homuler** [comment]
You need to build framework first (cf. https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation).
And if you need help, please use [Build/Install issue form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build-install-issue.yml).
