### ISSUE TITLE
lift_2d_frame_annotation_to_3d_calculator.pb.obj.params file can't open issue

### ISSUE THREAD

**Issue by ADOHI** [homuler/MediaPipeUnityPlugin#442]
### Plugin Version or Commit ID

v0.8.9

### Unity Version

2020.3.23f1

### Your Host OS

windows 10 home

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version
MSVC\14.29.30133
Windows Kits\10\bin\10.0.19041.0
_No response_

### Command Sequences

python build.py build --desktop cpu --opencv=cmake -v

### Log

'bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params' can't open

params file may auto generated.
how can I fix this bug?

### Additional Context

ERROR: C:/_bzl/j73jnxas/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/BUILD:98:24: Compiling external/com_google_mediapipe/mediapipe/modules/objectron/calculators/lift_2d_frame_annotation_to_3d_calculator.pb.cc [for tool] failed: (Exit 2): cl.exe failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/objectron/calculators:lift_2d_frame_annotation_to_3d_calculator_cc_proto)
  cd /d C:/_bzl/j73jnxas/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt
    SET PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Professional\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\adohi\AppData\Local\Temp
    SET TMP=C:\Users\adohi\AppData\Local\Temp
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params
Configuration: 2d16bb6853a2ad2e9b1657623e26be38536ee030d16e19f00e4fcccd03dcd67a
Execution platform: @local_execution_config_platform//:platform
Microsoft (R) C/C++ optimal compiler version 19.30.30705(x64)
Copyright (c) Microsoft Corporation. All rights reserved.

cl : error D8022 : 'bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params' can't open

_No response_

**Comment by homuler** [comment]
1. Run with `-vv` option and attach _FULL_ log (not an excerpt), please.
> Attach full log in text format.
When executing build command, make sure to add -vv option (e.g. python build.py build --desktop cpu -vv).

2. Fill **[Windows Only] Visual Studio C++ and Windows SDK Version**
> _Required_ if your host OS is _Windows_ and the Target Platform is _UnityEditor_ or PC Standalone.

**Comment by ADOHI** [comment]
Where is log file path?
I cannot find :(

**Comment by ADOHI** [comment]
It was my fault :( 
maybe VS version problem.

**Comment by ADOHI** [comment]
ERROR: C:/_bzl/j73jnxas/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/BUILD:98:24: Compiling external/com_google_mediapipe/mediapipe/modules/objectron/calculators/lift_2d_frame_annotation_to_3d_calculator.pb.cc [for tool] failed: (Exit 2): cl.exe failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/objectron/calculators:lift_2d_frame_annotation_to_3d_calculator_cc_proto)
  cd /d C:/_bzl/j73jnxas/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\adohi\AppData\Local\Temp
    SET TMP=C:\Users\adohi\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params
# Configuration: 2d16bb6853a2ad2e9b1657623e26be38536ee030d16e19f00e4fcccd03dcd67a
# Execution platform: @local_execution_config_platform//:platform
Microsoft (R) C/C++ 최적화 컴파일러 버전 19.29.30139(x64)
Copyright (c) Microsoft Corporation. All rights reserved.

cl : 명령줄 error D8022 : 'bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params'을(를) 열 수 없습니 다.
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 29.141s, Critical Path: 27.95s
INFO: 340 processes: 127 internal, 213 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "c:\Mediapipe\MediaPipeUnityPlugin-master\build.py", line 451, in <module>
    Argument().command().run()
  File "c:\Mediapipe\MediaPipeUnityPlugin-master\build.py", line 142, in run
    self._run_command(self._build_desktop_commands())
  File "c:\Mediapipe\MediaPipeUnityPlugin-master\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//adohi//AppData//Local//Microsoft//WindowsApps//PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

**Comment by homuler** [comment]
Well, by full log, I mean _all the output_ from running `build.py` (like https://github.com/homuler/MediaPipeUnityPlugin/issues/423).
Also, there are two different logs posted, but please post only the correct one in the Description.

**Comment by ADOHI** [comment]
It was bazel preview version problem :(
Downgrade to 5.0.0 version, it solved
