### ISSUE TITLE
Web Camera is not loading in standalone app of new project with same MediaPipeUnityPlugin 

### ISSUE THREAD

**Issue by PallaviPandurangPawar** [homuler/MediaPipeUnityPlugin#443]
### Plugin Version or Commit ID

0.6.2

### Unity Version

2020.3.8f1

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Command Sequences

Hello Sir,
Sir when I build the standalone app for DesktopDemo unity scene from MediaPipeUnityPlugin github folder then web camera gets on and work perfectly in the standalone app.
Sir, when I try to implement same thing in another project folder then in this web camera does not get started.

 

### Log

Also I refered the similar issues #437 , #407 , #252 .
But couldn't find the solution for my issues.
![bracelet](https://user-images.githubusercontent.com/71063679/152518091-1ce4c84a-3709-4ed6-bb80-51ffc40c4430.jpeg)

Please Sir guide me over this issue.

**Comment by homuler** [comment]
Please follow the instructions on the form.

- > Make sure you're using the latest version.
- > Required if your host OS is Windows and the Target Platform is UnityEditor or PC Standalone.
- > List the commands and operations you performed, in order and as best you can.
- > Attach full log in text format.
