### ISSUE TITLE
Google.Protobuf.dll is not found can you help me?

### ISSUE THREAD

**Issue by kitmek1** [homuler/MediaPipeUnityPlugin#45]
C:\Users\kitme\OneDrive\Desktop\New folder (2)\MediaPipeUnityPlugin>make cpu
./.build/protobuf-3.13.0/csharp/buildall.sh
process_begin: CreateProcess(NULL, bash C:\Users\kitme\OneDrive\Desktop\New folder (2)\MediaPipeUnityPlugin\.build\protobuf-3.13.0\csharp\buildall.sh, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:61: recipe for target '.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll' failed
mingw32-make.exe: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 2

**Comment by homuler** [comment]
Check %PATH% and make sure that the path to bash can be resolved. 
https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

**Comment by kitmek1** [comment]
I am getting this error when I build this example using bazel

INFO: Repository local_execution_config_python instantiated at:
  C:/users/kitme/mediapipe/WORKSPACE:387:13: in <toplevel>
  C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/tensorflow/workspace.bzl:74:20: in tf_workspace
  C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/tensorflow/workspace.bzl:90:27: in tf_repositories
  C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Repository command failed
File "<string>", line 1
    from os import linesep;f = open('script.py', 'w');f.write("from __future__ import print_function" + linesep);f.write("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('PYTHONPATH') is not None:" + linesep);f.write("  python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("try:" + linesep);f.write("  library_paths = site.getsitepackages()" + linesep);f.write("except AttributeError:" + linesep);f.write("  from distutils.sysconfig import get_python_lib" + linesep);f.write("  library_paths = [get_python_lib()]" + linesep);f.write("all_paths = set(python_paths + library_paths)" + linesep);f.write("paths = []" + linesep);f.write("for path in all_paths:" + linesep);f.write("  if os.path.isdir(path):" + linesep);f.write("    paths.append(path)" + linesep);f.write("if len(paths) >=1:" + linesep);f.write("  print(paths[0])" + linesep);f.close();from os import system;system("C:\Users\kitme\AppData\Local\Programs\Python\Python39\python.exe script.py");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/kitme/_bazel_kitme/mw4t6tje/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Repository command failed
File "<string>", line 1
    from os import linesep;f = open('script.py', 'w');f.write("from __future__ import print_function" + linesep);f.write("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('PYTHONPATH') is not None:" + linesep);f.write("  python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("try:" + linesep);f.write("  library_paths = site.getsitepackages()" + linesep);f.write("except AttributeError:" + linesep);f.write("  from distutils.sysconfig import get_python_lib" + linesep);f.write("  library_paths = [get_python_lib()]" + linesep);f.write("all_paths = set(python_paths + library_paths)" + linesep);f.write("paths = []" + linesep);f.write("for path in all_paths:" + linesep);f.write("  if os.path.isdir(path):" + linesep);f.write("    paths.append(path)" + linesep);f.write("if len(paths) >=1:" + linesep);f.write("  print(paths[0])" + linesep);f.close();from os import system;system("C:\Users\kitme\AppData\Local\Programs\Python\Python39\python.exe script.py");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed
File "<string>", line 1
    from os import linesep;f = open('script.py', 'w');f.write("from __future__ import print_function" + linesep);f.write("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('PYTHONPATH') is not None:" + linesep);f.write("  python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("try:" + linesep);f.write("  library_paths = site.getsitepackages()" + linesep);f.write("except AttributeError:" + linesep);f.write("  from distutils.sysconfig import get_python_lib" + linesep);f.write("  library_paths = [get_python_lib()]" + linesep);f.write("all_paths = set(python_paths + library_paths)" + linesep);f.write("paths = []" + linesep);f.write("for path in all_paths:" + linesep);f.write("  if os.path.isdir(path):" + linesep);f.write("    paths.append(path)" + linesep);f.write("if len(paths) >=1:" + linesep);f.write("  print(paths[0])" + linesep);f.close();from os import system;system("C:\Users\kitme\AppData\Local\Programs\Python\Python39\python.exe script.py");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
INFO: Elapsed time: 5.283s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 11 targets configured)
FAILED: Build did NOT complete successfully (14 packages loaded, 11 targets configured)

**Comment by homuler** [comment]
Well, you're building `mediapipe` official example so I'd like you to ask in the place other than here...(I cannot even know what command you run)

But maybe it's because you didn't specifiy `--action_env` (see No.9 https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows)

**Comment by kitmek1** [comment]
ok thanks i will check some solution for that..

**Comment by homuler** [comment]
closes because build command has changed.
