### ISSUE TITLE
Disabling smoothLandmarks in PoseTrackingGraph has no effect

### ISSUE THREAD

**Issue by link1375** [homuler/MediaPipeUnityPlugin#452]
### Description

The `GraphRunner` has the option to disable `smoothingLandmarks`. So I wonder if I just cannot see a difference if its disabled or if there is another problem.
My goal is to get the landmarks for every frame without smoothing them e.g. if I move my arm, the landmarks should be on my arm and not at the correct position a few milliseconds later. Is this possible?

Desired Position:
![mediapipe_smooth_3](https://user-images.githubusercontent.com/33375235/154476707-3475479d-4e12-4c40-a278-04315843df05.png)
Undesired Position:
![mediapipe_smooth_2](https://user-images.githubusercontent.com/33375235/154476711-22ddafba-e1f6-43f3-8c4f-b22bc85f95ce.png)

EDIT: In the [docs](https://google.github.io/mediapipe/solutions/pose.html) I found two properties `static_image_mode` and `smooth_landmarks` which might have an impact. I saw the the latter is set in `BuildSidePacket` in the `PoseTrackingGraph` class, but setting those values to `false` and `true` respectively, does not change anything

**Comment by homuler** [comment]
> if I move my arm, the landmarks should be on my arm and not at the correct position a few milliseconds later. Is this possible?

Certainly there was a bug and `smooth_landmarks` was not working (thank you for reporting it), but I think this is independent of your issue.
If you're running the sample app with the default options, try running it in asynchronous mode (see https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-932074718).

**Comment by link1375** [comment]
I just replaced the Scene folder from the current master (with your fix) with my Scene folder (commit 75a736a) but still the landmarks are smoothed. Actually, I already tried this fix ([see here](https://stackoverflow.com/questions/71180126/how-to-disable-smoothing-pose-estimation-landmarks-in-mediapipe-unity-plugin)) without success.

**Comment by homuler** [comment]
> If you're running the sample app with the default options, try running it in asynchronous mode (see https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-932074718).

Sorry, I wrote the exact opposite.
Please try running it in _synchronous_ mode (forget about `smooth_landmarks` for a while).

> Also I tried to build the latest version, but when I run the start scene I get an error

I don't know the cause of the error from this information, but maybe #459 fixes it.

P.S.
> I saw the the latter is set in BuildSidePacket in the PoseTrackingGraph class, but setting those values to false and true respectively, does not change anything

You can change those values from the UI of the sample app.
