### ISSUE TITLE
Unable to use Hand Tracking Graph in different Scenes

### ISSUE THREAD

**Issue by Jay-artist** [homuler/MediaPipeUnityPlugin#453]
### Description

Hello Sir,
I wanted to use Hand Tracking Graph in two different Scenes in unity. 
Can you please give me some Solution of how I can use Hand Tracking Graph in two different scenes !!

**Comment by Arham-Aalam** [comment]
Try to explore the [wiki](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Advanced-Topics)
You can checkout #446 issue as well.
