### ISSUE TITLE
Memory leak in `SerializeProtoVector`

### ISSUE THREAD

**Issue by Speykious** [homuler/MediaPipeUnityPlugin#457]
### Plugin Version or Commit ID

v0.8.2

### Your Host OS

Arch Linux

### Target Platform

All platforms

### Build Command

python build.py build --no-install --no-protobuf --desktop gpu --opencv cmake -vv

### Bug Description

Because of `SerializeProtoVector`'s current `Dispose` function, a memory leak occurs -for example- as soon as a secondary output stream is observed with `ObserveOutputStream`.

### Steps to Reproduce the Bug

- Create a program that makes use of `ObserveOutputStream`.
- Make it so that MediaPipe detects something - for example, the face when using a face mesh graph, or the hand when using hand tracking.
- When it detects the face/hand/pose/etc., notice the memory of the program going up by about one megabyte every 8 seconds.

### Additional Context

This is where the memory leak originates from:
https://github.com/homuler/MediaPipeUnityPlugin/blob/6a1d120a531495941297bb4d41bcf20027b942db/Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/SerializedProtoVector.cs#L21-L24

It is only deleting the `SerializeProtoVector` array and doesn't delete the individual `SerializeProto`s.
It should be:
```cs
  public void Dispose() 
  {
    unsafe
    {
      var protoPtr = (SerializedProto*)data;
      for (int i = 0; i < size; i++)
        protoPtr[i].Dispose();
    }
    UnsafeNativeMethods.mp_api_SerializedProtoArray__delete(data); 
  }
```

I gotta say, it has taken us **months** to find that out... What a relief!

**Comment by homuler** [comment]
Thank you for reporting the issue.
https://github.com/homuler/MediaPipeUnityPlugin/commit/7bb877de4887ad4bf23c72b39649c41bb3650d54#diff-5f380dba80be1384314c2c43b90a4ec21be2dd11f08dff924b1d965dba6de7da introduced it.

Maybe I misunderstood that it was unnecessary to free memory because `SerializedProto` is `struct`, but actually `SerializedProto` allocates memory for `const char* str`.
