### ISSUE TITLE
fatal error C1001: An internal error has occurred in the compiler.

### ISSUE THREAD

**Issue by EverSinceWWI** [homuler/MediaPipeUnityPlugin#46]
ERROR: C:/_bzl/kbkinlco/external/org_tensorflow/tensorflow/lite/kernels/BUILD:663:11: Compiling tensorflow/lite/kernels/elementwise.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 66 argument(s) skipped)
cl : Command line warning D9002 : ignoring unknown option '-O3'
external/org_tensorflow/tensorflow/lite/kernels/elementwise.cc(299): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1518)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
INFO: Elapsed time: 138.722s, Critical Path: 135.43s
INFO: 511 processes: 221 internal, 290 local.
FAILED: Build did NOT complete successfully
make: *** [Makefile:46: cpu] Error 1
![err](https://user-images.githubusercontent.com/32314108/106677454-0e683e80-65b9-11eb-8068-940b8d21229a.png)

I run " make cpu PYTHON_BIN_PATH="C://python_36//python.exe" " and i got an internal compiler error, how can I solve it? I'm on Windows 10.

Thank you

**Comment by homuler** [comment]
To build mediapipe, Visual C++ Build Tools 2019 is required, not 2017.
https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

**Comment by EverSinceWWI** [comment]
Thank you! I installed 2019 and it worked nicely.

Unfortunately now when I run "make install" I get this error:

C:\Users\EverSince\MediaPipeUnityPlugin>make install
mkdir -p Assets/MediaPipe/SDK/Plugins/Protobuf
The syntax of the command is incorrect.
make: *** [Makefile:132: Assets/MediaPipe/SDK/Plugins/Protobuf] Error 1
![err2](https://user-images.githubusercontent.com/32314108/106754465-4e690900-662d-11eb-8412-137831170820.png)

**Comment by homuler** [comment]
First, try updating your `make` command.
If it does not work, you may need to specify `SHELL=bash`.
https://stackoverflow.com/questions/45889953/how-to-force-make-to-use-bash-as-a-shell-on-windows-msys2

**Comment by EverSinceWWI** [comment]
`make` was already up to date, and SHELL=bash didn't work either.

I manually copied files following the Makefile code on lines 72, 76, 98, 105. Now when I run `make install` again, it gives me this:

`C:\Users\EverSince\MediaPipeUnityPlugin>make install
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/MediaPipe/SDK/Plugins/Protobuf
process_begin: CreateProcess(NULL, cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/MediaPipe/SDK/Plugins/Protobuf, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:72: install-protobuf] Error 2`

although the target directory exist, and contains these files: 
![err3](https://user-images.githubusercontent.com/32314108/106865077-fa146680-66ca-11eb-81c6-aa66938ef05b.png)

I hope I didn't do anything stupid by manually copying files, but I couldn't find any other solution to those errors.
If I open the project in Unity, this error appears:
`Assets\MediaPipe\SDK\Scripts\External\Protobuf.cs(20,14): error CS0012: The type 'ReadOnlySequence<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

![err4](https://user-images.githubusercontent.com/32314108/106865855-0a791100-66cc-11eb-986b-814a372a1262.png)

**Comment by homuler** [comment]
Can you run `cp` command?

**Comment by EverSinceWWI** [comment]
nope, it gives me:
`'cp' is not recognized as an internal or external command,
operable program or batch file.`

maybe it's because I'm on windows?

**Comment by homuler** [comment]
Maybe you haven't install it yet with MSYS2 (perhaps `make` isn't also installed), or `C:\msys64` and `C:\msys64\usr\bin` are not set to `%PATH%` .
https://www.msys2.org/

**Comment by EverSinceWWI** [comment]
This is the system variable:
![image](https://user-images.githubusercontent.com/32314108/106898157-209ac780-66f4-11eb-98b9-a34178c5be80.png)

with MSYS2 I run `pacman -Syu` and `pacman -S base-devel gcc vim cmake`

but still didn't work:
```
C:\Users\EverSince\MediaPipeUnityPlugin>make install SHELL="C:\msys64\mingw64.exe"
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/MediaPipe/SDK/Plugins/Protobuf
process_begin: CreateProcess(NULL, cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/MediaPipe/SDK/Plugins/Protobuf, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:72: install-protobuf] Error 2
```

**Comment by homuler** [comment]
I mean
1. Install missing commands with `pacman` (using MSYS2).
2. Set the paths to those commands in the `%PATH%` environment variable.

And judging from the above image, you haven't finished the 1st step ↓ properly.
https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows
> Install MSYS2 and edit the %PATH% environment variable.
>
> If MSYS2 is installed to C:\msys64, add C:\msys64\usr\bin to your %PATH% environment variable.

cf. https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/path

**Comment by EverSinceWWI** [comment]
now it worked perfectly! My bad, I'm not so familiar with environment variables.
