### ISSUE TITLE
Extended Dataset for Objectron?

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#463]
### Description

Hi @homuler , 
Objectron currently supports only a few object's compatibility. Do you have any idea how to add more compatibility of objects, for example like headphones, piano etc

I know I should write this over the main mediapipe repo but I thought of asking you as well.

**Comment by homuler** [comment]
As far as I know, there are no datasets for headphones or piano, so you will need to prepare them first (cf. https://github.com/google-research-datasets/Objectron).
For more information, read https://google.github.io/mediapipe/solutions/objectron.html

> I know I should write this over the main mediapipe repo but I thought of asking you as well.

Then please don't open an issue here.
