### ISSUE TITLE
error: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.

### ISSUE THREAD

**Issue by SalvishGoomanee** [homuler/MediaPipeUnityPlugin#464]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2019.4.18f1

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++ : 14.29.30133
Windows SDK :  10.0.18362.0

### Command Sequences

`python build.py build --desktop cpu --include_opencv_libs -v`

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//
Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapip
e_api:mediapipe_proto_srcs`
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/a87782c34d667d1c1a18fe82a9a7abfc72fd345b.tar.gz failed: class java.io.File
NotFoundException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException
 GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/fc70a32ecd248dd7612d75d2177125ed14541367.tar.gz failed: class java.io.Fil
eNotFoundException GET returned 404 Not Found
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/unitymediapipe/mediapipeunityplugin/WORKSPACE:327:23: fetching android_ndk_repository rule //external:androidndk: Eit
her the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/unitymediapipe/mediapipeunityplugin/WORKSPACE:31:23: in <toplevel>
  C:/_bzl/mxecnww6/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/mxecnww6/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/mxecnww6/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable mu
st be set.
INFO: Elapsed time: 0.149s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/modules/objectron/calculators ... (11 packages)
    Fetching @com_google_protobuf; fetching
    Fetching @local_config_cc_toolchains; Restarting.
    Fetching @rules_foreign_cc_framework_toolchain_macos_commands; fetching
    Fetching @rules_foreign_cc_framework_toolchain_windows_commands; fetching
    Fetching @ninja_1.10.2_toolchains; fetching
    Fetching @rules_foreign_cc_framework_toolchain_linux_commands; fetching
Traceback (most recent call last):
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 113, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\gooma\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//
venv-efacec//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISI
ON //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#either-the-path-attribute-of-android_ndk_repository-or-the-android_ndk_home-environment-variable-must-be-set

**Comment by SalvishGoomanee** [comment]
I do not understand the above solution. Can you be a bit more precise? Thanks

**Comment by homuler** [comment]
Remove these lines.
https://github.com/homuler/MediaPipeUnityPlugin/blob/3698b6145e756c0abc5b0a8f1032591c57525b6f/WORKSPACE#L326-L337

**Comment by SalvishGoomanee** [comment]
Thanks! It seems to work as I got build files generated. But I got this  error now also, concerning nuget. 



INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//
Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapip
e_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
DEBUG: Repository rules_cc instantiated at:
  C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/unitymediapipe/mediapipeunityplugin/WORKSPACE:96:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/mxecnww6/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (65 packages loaded, 911 targets configured).
INFO: Found 1 target...
[11 / 207] 128 actions, 12 running
[12 / 207] 128 actions, 12 running
[12 / 207] 128 actions, 12 running
[14 / 207] 128 actions, 12 running
[14 / 207] 128 actions, 12 running
[16 / 207] 128 actions, 13 running
[19 / 207] 128 actions, 12 running
[19 / 207] 128 actions, 13 running
[20 / 207] 128 actions, 13 running
[21 / 207] 128 actions, 12 running
[23 / 207] 128 actions, 12 running
[23 / 207] 128 actions, 12 running
[23 / 207] 128 actions, 13 running
[24 / 207] 128 actions, 13 running
[25 / 207] 128 actions, 12 running
[25 / 207] 128 actions, 12 running
[26 / 207] 128 actions, 12 running
[26 / 207] 128 actions, 12 running
[28 / 207] 128 actions, 12 running
[28 / 207] 128 actions, 12 running
[29 / 207] 128 actions, 12 running
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 74.645s, Critical Path: 59.08s
INFO: 207 processes: 11 internal, 196 local.
INFO: Build completed successfully, 207 total actions
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
'nuget' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 120, in run
    self._run_command(self._build_proto_dlls_commands())
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\gooma\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nuget install -o .nuget -Source https://api.nuget.org/v3/index.json' returned non-zero exit status 1.



I downloaded the latest nuget from https://www.nuget.org/downloads and placed in `C:\NuGet\` folder. Could that be a problem? Thanks.

**Comment by SalvishGoomanee** [comment]
Thanks for quick reply. 
I did, running again `python build.py build --desktop cpu --include_opencv_libs -v` from CMD with my venv configured and nuget as well I get this:



INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="=C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/mxecnww6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/unitymediapipe/mediapipeunityplugin/WORKSPACE:481:14: in <toplevel>
  C:/_bzl/mxecnww6/external/org_tensorflow/tensorflow/workspace2.bzl:877:19: in workspace
  C:/_bzl/mxecnww6/external/org_tensorflow/tensorflow/workspace2.bzl:89:27: in _tf_toolchains
  C:/_bzl/mxecnww6/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/mxecnww6/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/mxecnww6/external/org_tensorflow/third_party/py/python_configure.bzl:276:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/mxecnww6/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/mxecnww6/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/mxecnww6/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='=C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//Scripts//python.exe' is not executable. Is it the python binary?
ERROR: C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/unitymediapipe/mediapipeunityplugin/WORKSPACE:481:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/mxecnww6/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/mxecnww6/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/mxecnww6/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='=C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//Scripts//python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='=C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//Scripts//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 0.520s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

Traceback (most recent call last):
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 451, in <module>
    Argument().command().run()
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 113, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\UnityMediapipe\MediaPipeUnityPlugin\build.py", line 53, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\gooma\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="=C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
> Error in fail: Configuration Error: --define PYTHON_BIN_PATH='=C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//Scripts//python.exe' is not executable. Is it the python binary?

I think this error occurs because the path you set to `PYTHON_BIN_PATH` is wrong.
Now, https://github.com/homuler/MediaPipeUnityPlugin/pull/468 eliminates the need to set `PYTHON_BIN_PATH` entirely, pull the latest commit and try again, please.

**Comment by SalvishGoomanee** [comment]
I pulled the new commit. And I got this after running the following command:

(venv-efacec) C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\MediaPipeUnityPlugin>python build.py build --desktop cpu --opencv cmake -vv

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//venv-efacec//
Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_
failures //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/kfxhslrz/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/mediapipeunityplugin/WORKSPACE:327:23: fetching android_ndk_repository rule //external:androidndk: Either the path at
tribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
INFO: Repository com_google_protobuf instantiated at:
  C:/users/gooma/desktop/python/pythonproject/infprojects/efacec/mediapipeunityplugin/WORKSPACE:189:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/kfxhslrz/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable mu
st be set.
INFO: Elapsed time: 8.152s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (16 packages loaded, 22 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (10 packages)
    Fetching @local_execution_config_python; Restarting.
Traceback (most recent call last):
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\MediaPipeUnityPlugin\build.py", line 448, in <module>
    Argument().command().run()
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\MediaPipeUnityPlugin\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\gooma\Desktop\Python\pythonProject\InFProjects\efacec\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\gooma\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//gooma//Desktop//Python//pythonProject//InFProjects//efacec//
venv-efacec//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISI
ON --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
I don't know if you're joking, so to answer you seriously, you're repeating your original question (https://github.com/homuler/MediaPipeUnityPlugin/issues/464#issue-1148149417) now.

**Comment by SalvishGoomanee** [comment]
It is the output I got. I can see that but do not understand what is wrong in the build.py.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/464#issuecomment-1050790931

**Comment by SalvishGoomanee** [comment]
OK, I got the instructions to copy build folders into `Packages\com.github.homuler.mediapipe\Runtime`.

Upon launching in Unity I have just this error: 

`Library\PackageCache\com.unity.2d.common@4.1.0\Runtime\InternalBridge\InternalEngineBridge.cs(21,35): error CS1061: 'SpriteRenderer' does not contain a definition for 'IsUsingDeformableBuffer' and no accessible extension method 'IsUsingDeformableBuffer' accepting a first argument of type 'SpriteRenderer' could be found (are you missing a using directive or an assembly reference?)`

I did check `Load on startup` in the inspector for both the mediapipe plugin and the opencv plugin. 

Thanks for help on this (hopefully) final step!

**Comment by homuler** [comment]
Please use [the specified version](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/ProjectSettings/ProjectVersion.txt) of Unity (i.e. 2020.3.x).
I think you can still use this plugin with 2019.4.x (not tested though), but the sample app does not work with an older version.

**Comment by SalvishGoomanee** [comment]
Same error with Unity 2020.3.8f1 and it prompts me to `Enter safe mode` before launch.

**Comment by homuler** [comment]
1. Close the UnityEditor
2. Download Unity 2020.3.30f1
3. Run `git checkout .`
   - If you've not cloned this project, download and build it again.
4. Run `rm -rf Library`
5. Reopen the project

If the issue still occurs, do a clean install.

**Comment by SalvishGoomanee** [comment]
Works like a charm!! :)

Thanks a lot for all the support.
