### ISSUE TITLE
Windows 10/11 - il2cpp support (not working in il2cpp builds)

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#465]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2021.2.10f1 or higher

### Your Host OS

Windows 10 and 11

### Target Platform

Windows Standalone

### Target Device

Windows Desktop Devices

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++ : 14.29.30133
Windows SDK : 10.0.18362.0

### Build Command

python build.py build --desktop cpu --opencv cmake -vv

### Bug Description

When building the project to Windows build target, only mono builds work, in some projects we are using il2cpp for performance in build runtime and build compile time optimizations. Is there any possibility of il2cpp support?

### Steps to Reproduce the Bug

1. Open the repo on Windows in any Unity Editor Version with windows il2cpp module installed with Unity
2. Make sure build target is windows desktop
3. Edit>Project Settings>Player>Other Settings> Configuration> Scripting Backend> il2cpp
4. Build and run, see build doesn't work, use a [build console log tool ](https://github.com/yasirkula/UnityIngameDebugConsole)like this to see the error

### Log

```
DllNotFoundException: Unable to load DLL 'mediapipe_c'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_c' because of 'Failed to open the requested dynamic library (0x06000000) - The specified module could not be found.  (WinError:0000007e)
Mediapipe.Glog.set_Logtostderr (System.Boolean value) (at <00000000000000000000000000000000>:0)
Mediapipe.Unity.GlobalConfigManager.SetFlags () (at <00000000000000000000000000000000>:0)
Mediapipe.Unity.Bootstrap+<Start>d__17.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)

```

### Screenshot/Video

![error](https://user-images.githubusercontent.com/10745594/155346308-408a4bc0-dd70-4502-b94b-47ad860db301.JPG)

**Comment by homuler** [comment]
I think it is fixed by #455 and #459.
Will you try again with the latest commit?
