### ISSUE TITLE
Build issue, FileNotFoundError

### ISSUE THREAD

**Issue by mahi-ghan** [homuler/MediaPipeUnityPlugin#466]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.27f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual studio = 16.11.10
Windows SDK= 10.0.19041.0

### Command Sequences

python build.py build --desktop cpu --include_opencv_libs -v

### Log

Microsoft Windows [Version 10.0.19041.1415]
(c) Microsoft Corporation. All rights reserved.

C:\Users\HC>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
Traceback (most recent call last):
  File "C:\Users\HC\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\HC\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\HC\build.py", line 272, in _build_proto_srcs_commands
    commands = self._build_common_commands()
  File "C:\Users\HC\build.py", line 189, in _build_common_commands
    python_bin_path = os.environ['PYTHON_BIN_PATH'].replace('\\', '//')
  File "C:\Users\HC\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYTHON_BIN_PATH'

C:\Users\HC>virtualenv env
created virtual environment CPython3.10.2.final.0-64 in 4062ms
  creator CPython3Windows(dest=C:\Users\HC\env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\HC\AppData\Local\pypa\virtualenv)
    added seed packages: numpy==1.22.2, pip==22.0.3, setuptools==60.9.3, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

C:\Users\HC>env\Scripts\activate

(env) C:\Users\HC>set PYTHON_BIN_PATH=C:\Users\HC\env\Scripts\python.exe

(env) C:\Users\HC>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//HC//env//Scripts//python.exe //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "C:\Users\HC\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\HC\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\HC\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\HC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\HC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\HC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

(env) C:\Users\HC>

### Additional Context

i added path of nuget, baxel.exe in environment variables.

**Comment by homuler** [comment]
> i added path of nuget, baxel.exe in environment variables.

The error message tells you that `bazel` is not found, so if you thought you set the path to `PATH`, you must have set it the wrong way.

**Comment by mahi-ghan** [comment]
Thank you for pointing out, I carefully repeated steps but now I am getting "Build not successfully complete" ERROR.
The following is my the log


(env) C:\Users\HC\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//HC//MediaPipeUnityPlugin-master//env//Scripts//python.exe //mediapipe_api:mediapipe_proto_srcs`
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository rules_python instantiated at:
  C:/users/hc/mediapipeunityplugin-master/WORKSPACE:34:23: in <toplevel>
  C:/_bzl/tzoaebx4/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/tzoaebx4/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/tzoaebx4/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
                init(ctx, git_repo)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init C:/_bzl/tzoaebx4/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/tzoaebx4/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: C:/users/hc/mediapipeunityplugin-master/mediapipe_api/BUILD:167:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git init C:/_bzl/tzoaebx4/external/rules_python' while working with @rules_python:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("git" init C:/_bzl/tzoaebx4/external/rules_python): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.993s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @rules_pkg//
Traceback (most recent call last):
  File "C:\Users\HC\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\HC\MediaPipeUnityPlugin-master\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\HC\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\HC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//HC//MediaPipeUnityPlugin-master//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by homuler** [comment]
Please check the troubleshooting page first.
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#javaioioexception-error-srcmainnativewindowsprocesscc202-createprocesswcommand-

**Comment by mahi-ghan** [comment]
> Please check the troubleshooting page first. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#javaioioexception-error-srcmainnativewindowsprocesscc202-createprocesswcommand-

I have checked that page but I am unable to resolve my error. I reinstalled everything, there is error in fetching repository rules_cc but I am unable to find a solution to that. Can you please guide me, would really appreciate!



C:\Users\HC\MediaPipeUnityPlugin-master>python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//HC//MediaPipeUnityPlugin-master//env//Scripts//python.exe //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/tzoaebx4/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7
INFO: Repository rules_cc instantiated at:
  C:/users/hc/mediapipeunityplugin-master/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_cc':
   Traceback (most recent call last):
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888/master.zip to C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888/master.zip to C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
INFO: Repository com_google_protobuf instantiated at:
  C:/users/hc/mediapipeunityplugin-master/WORKSPACE:177:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/tzoaebx4/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target @rules_pkg//:build_zip: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error extracting C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888/master.zip to C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error extracting C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888/master.zip to C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888: Prefix "rules_cc-master" was given, but not found in the archive. Here are possible prefixes for this archive: "rules_cc-main".
INFO: Elapsed time: 3.667s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (7 packages)
    Fetching C:/_bzl/tzoaebx4/external/rules_cc; Extracting C:/_bzl/tzoaebx4/external/rules_cc/temp6119172102503333888/master.zip
Traceback (most recent call last):
  File "C:\Users\HC\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\HC\MediaPipeUnityPlugin-master\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\HC\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\HC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//HC//MediaPipeUnityPlugin-master//env//Scripts//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by mahi-ghan** [comment]
I tried getting sha256sum but access is denied

C:\> certUtil -hashfile C:\_bzl\tzoaebx4\external\rules_cc\temp6119172102503333888\master.zip SHA256
Access is denied.

**Comment by mahi-ghan** [comment]
Hey thank you, I was able to successfully build and run the mediapipe graphs in unity. 
However, I want to build an android APK, I just followed the standard way of building and running an android apk through unity build settings but the apk didn't work. Is there anyway I can successfully build apk for mediapipe handtracking algorithm using unity? Will really appreciate every bit of guidance!!

**Comment by homuler** [comment]
Well, you didn't read from the first line, did you...
> > :warning: You cannot build libraries for Android with the following steps.
If you use Window 10 Pro, go to [Docker Windows Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-windows-container). Otherwise, go to [Docker Linux Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container).
