### ISSUE TITLE
Uncomplete build

### ISSUE THREAD

**Issue by NachoSaanchez** [homuler/MediaPipeUnityPlugin#467]
### Plugin Version or Commit ID

idk

### Unity Version

2020.3.20f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual studio = 16.11.5
Windows SDK= 10.0.19041.0

### Command Sequences

`python build.py build --desktop cpu --include_opencv_libs -v`

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//USUARIO//AppData//Local//Microsoft//WindowsApps//python.exe --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/jxtrex3m/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: C:/users/usuario/desktop/tfg/aprender/mediapipe/mediapipeunityplugin/WORKSPACE:288:23: fetching android_ndk_repository rule //external:androidndk: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
INFO: Elapsed time: 0.507s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/modules/face_geometry/protos ... (6 packages)
    Fetching @local_config_cc_toolchains; fetching
    Fetching @androidsdk; Restarting.
    Fetching @com_google_protobuf; fetching
Traceback (most recent call last):
  File "C:\Users\USUARIO\Desktop\TFG\Aprender\mediapipe\MediaPipeUnityPlugin\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\Users\USUARIO\Desktop\TFG\Aprender\mediapipe\MediaPipeUnityPlugin\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\USUARIO\Desktop\TFG\Aprender\mediapipe\MediaPipeUnityPlugin\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//USUARIO//AppData//Local//Microsoft//WindowsApps//python.exe', '--verbose_failures', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by homuler** [comment]
duplicates #464
