### ISSUE TITLE
Standalone executable does not shut down

### ISSUE THREAD

**Issue by jerrysheen** [homuler/MediaPipeUnityPlugin#47]
Hi, homuler, I found a bug:
When I try to build the scene DesktopCPU, after I got exe file in windows and run it, the program can't find the webcam and show gray screen like this:
![image](https://user-images.githubusercontent.com/19220015/106707851-e0bcdd00-662c-11eb-85ad-d0f893e971a3.png)

**Comment by homuler** [comment]
Did you build AssetBundle?

**Comment by jerrysheen** [comment]
Do you mean right click here and build assetbundle?
![image](https://user-images.githubusercontent.com/19220015/106720350-55e4de00-663e-11eb-83d7-94e30155cb32.png)

Yes I did..

**Comment by homuler** [comment]
Will you share the Player log, please?

Maybe the log is output at `C:\Users\username\AppData\LocalLow\DefaultCompany\MediaPipeUnityPlugin\Player.log` or so.

**Comment by jerrysheen** [comment]
[output_log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/5917520/output_log.txt)
Ok the log looks like this, so I try to add libmediapipe_c.dll to /MediaPipeUnityPlugin_Data/Mono/.
The camera can on, but another bug occurs.
I can't shut down the program, when I click close button the exe file will stuck(seems still be some graph not shutdown properly problem... :/)

**Comment by homuler** [comment]
Fixed by https://github.com/homuler/MediaPipeUnityPlugin/commit/85c77aa079aa18233f422503e9b457a762233212
