### ISSUE TITLE
Converting (x,y,z) to Axis-Angle Representation

### ISSUE THREAD

**Issue by Shreeshail-Hingane** [homuler/MediaPipeUnityPlugin#473]
### Description

I am interested in the problem of getting pose data from MediaPipe [Pose](https://google.github.io/mediapipe/solutions/pose.html) and using it to animate 3D avatars in Unity. MediaPipe Pose's data is in the form of (x,y,z) co-ordinates of the 33 landmarks (for each frame).

Do the 3D avatars use data in this format? Or does it have to be converted to some other format, like the Axis-Angle Representation (i.e. Quaternions). Could you also point me to the relevant source code files where the (x,y,z) data from MediaPipe Pose is passed to the object to be animated?

Thanks.

**Comment by ROBYER1** [comment]
Have you already taken a look at the sample app in this repo where you can easily see the coordinates being passed through the code to draw the annotations on screen?

See in Holistic for example https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingGraph.cs

**Comment by Shreeshail-Hingane** [comment]
I looked at https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/Mediapipe/Samples/Scenes/Pose%20Tracking/PoseTrackingGraph.cs.
Could you point to the line of code in the above script where the co-ordinates are being passed?

**Comment by ROBYER1** [comment]
Here is an easier way if you are stuck, make line 17 of list annotation `public List<T> _children; `
https://github.com/homuler/MediaPipeUnityPlugin/blob/a3b90d13eac636ff837d52723eaa6f0046adb459/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/ListAnnotation.cs#:~:text=private%20List%3CT%3E%20_children%3B

Then in another script where you want to access the points, make a reference to the PointListAnnotation component (which inherits from ListAnnotation). Make sure to find the component in your scene and hook it up.

This is pseudocode so please check 
e.g.
`public PointListAnnotation poseScript;

void Update()
{
Debug.Log(poseScript._children[1].transform.position.ToString());
}
`

**Comment by Shreeshail-Hingane** [comment]
I see. Though this simply draws the landmarks on the screen. I'm interested in whether these can be used to animate avatars.

**Comment by Shreeshail-Hingane** [comment]
i.e. whether the repo itself has demo code to animate avatars using the landmarks data (ex: this [video](https://www.youtube.com/watch?v=K-_krrs05qw)). Or would I have to write the code for that part myself?

**Comment by homuler** [comment]
> Do the 3D avatars use data in this format?

I think it depends on your avatar format.

> whether these can be used to animate avatars.

I think it also depends on the requirements, but you can use those landmark data to implement a system for VTubers.

> whether the repo itself has demo code to animate avatars using the landmarks data (ex: this [video](https://www.youtube.com/watch?v=K-_krrs05qw)).

No.

> Or would I have to write the code for that part myself?

Yes.
Please read README, too.
> The goal of this project is to port the MediaPipe API (C++) one by one to C# so that it can be called from Unity.

Providing a one-stop solution is outside the scope of this project.

**Comment by ROBYER1** [comment]
> i.e. whether the repo itself has demo code to animate avatars using the landmarks data (ex: this [video](https://www.youtube.com/watch?v=K-_krrs05qw)). Or would I have to write the code for that part myself?

Homuler is already doing a fantastic job maintaining and supporting this repo + the many samples within the app.
I think if you have a specific use-case such as yours, some work is required on your part to create the solution you need using the samples as a starting point.

If you look around at the forks of this repo there are already a few public forks using this Mediapipe plugin to animate 3D characters also which may help you.

Best of luck!

**Comment by Shreeshail-Hingane** [comment]
Sure, thanks.

**Comment by portari** [comment]
Hi @Shreeshail-Hingane. I am needing to do the same thing. Did you manage to do the animation? I've already built a software that (on android) recognizes the coordinates with Pose and sends it over the network to a Windows machine, where a Unity application receives these coordinates and needs to animate an avatar, as in the video you posted. I happen to have the same problem (needing Quaternions or not). I managed to make an application that shows the points connected to lines (in Unity itself) with the sent coordinates. Everything is alright. I tried to do it by Animation Riggs in Unity, but I don't have the rotation information. I'm lost! You got it? Could help? Thanks.

**Comment by Shreeshail-Hingane** [comment]
Hi @portari. There are two solutions I found useful which perform this conversion from (x,y,z) joint locations to joint rotations:
1] This GitHub repo: https://github.com/yeemachine/kalidokit
2] This paper: https://openaccess.thecvf.com/content/CVPR2021/papers/Li_HybrIK_A_Hybrid_Analytical-Neural_Inverse_Kinematics_Solution_for_3D_Human_CVPR_2021_paper.pdf

**Comment by portari** [comment]
> Hi @portari. There are two solutions I found useful which perform this conversion from (x,y,z) joint locations to joint rotations: 1] This GitHub repo: https://github.com/yeemachine/kalidokit 2] This paper: https://openaccess.thecvf.com/content/CVPR2021/papers/Li_HybrIK_A_Hybrid_Analytical-Neural_Inverse_Kinematics_Solution_for_3D_Human_CVPR_2021_paper.pdf

Thanks a lot. I will try both!
