### ISSUE TITLE
Build Libraries on Windows 10 NOT complete successfully 

### ISSUE THREAD

**Issue by HakuWang** [homuler/MediaPipeUnityPlugin#476]
### Plugin Version or Commit ID

v0.8.3

### Unity Version

2020.3.30f1

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

VisualStudio C++: 14.29.30133
Windows SDK: 10.0.19041.0

### Command Sequences

python build.py build --desktop cpu --include_opencv_libs -vv

### Log

E:\SVN\YZDH\VideoBasedFacialAnim\MediaPipeUnityPlugin>python build.py build --desktop cpu --include_opencv_libs -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="D://Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/pvzfk72w/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository rules_python instantiated at:
  E:/svn/yzdh/videobasedfacialanim/mediapipeunityplugin/WORKSPACE:31:23: in <toplevel>
  C:/_bzl/pvzfk72w/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, column 10, in _update
                fetch(ctx, git_repo)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 136, column 13, in fetch
                _git(
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, column 15, in _git
                _error(ctx.name, start + list(args), st.stderr)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
BUG: run-command.c:513: disabling cancellation: Invalid argument
      0 [main] git 1265 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, column 10, in _update
                fetch(ctx, git_repo)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 136, column 13, in fetch
                _git(
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, column 15, in _git
                _error(ctx.name, start + list(args), st.stderr)
        File "C:/_bzl/pvzfk72w/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
BUG: run-command.c:513: disabling cancellation: Invalid argument
      0 [main] git 1265 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
ERROR: E:/svn/yzdh/videobasedfacialanim/mediapipeunityplugin/mediapipe_api/BUILD:193:8: //mediapipe_api:mediapipe_proto_srcs depends on @rules_pkg//:build_zip in repository @rules_pkg which failed to fetch. no such package '@rules_python//python': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
BUG: run-command.c:513: disabling cancellation: Invalid argument
      0 [main] git 1265 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.517s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @rules_pkg//
Traceback (most recent call last):
  File "E:\SVN\YZDH\VideoBasedFacialAnim\MediaPipeUnityPlugin\build.py", line 448, in <module>
    Argument().command().run()
  File "E:\SVN\YZDH\VideoBasedFacialAnim\MediaPipeUnityPlugin\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "E:\SVN\YZDH\VideoBasedFacialAnim\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "D:\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="D://Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

I followed the Installation guide in https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide and added everything needed to the %Path% environment varible.  
I tried with python 3.9.6, azel 4.2.1, vs 2019, nuget 5.10.0.
I run the build command in cmd.exe and got errors in the log file. I will try the  [Docker Windows Container] on my windows 10 enterprise, but i'd appreciate it if you could help me.

**Comment by homuler** [comment]
> Error in fail: error running 'git fetch origin refs/heads/:refs/remotes/origin/ refs/tags/:refs/tags/' while working with @rules_python:
BUG: run-command.c:513: disabling cancellation: Invalid argument
0 [main] git 1265 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump

I've not seen this error, so I'm not sure, but I guess it's because the `git` path is not resolved to the one you should have installed at [the 2nd step in the guide](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10) (maybe you've installed `git` in a different way?).

**Comment by HakuWang** [comment]
I installed git by MSYS2. I ran 'where git' in cmd.exe,  and will get log 'C:\msys64\usr\bin\git.exe'.

**Comment by homuler** [comment]
Probably this is related to https://github.com/msys2/MINGW-packages/issues/3351.
I think it's a matter of `PATH` order, but I don't know.

**Comment by HakuWang** [comment]
Thank you for you quick responses. I did not install mingw-w64 GCC at the 7th step in the https://www.msys2.org/. Do i need to install it ?

**Comment by homuler** [comment]
No, you don't (though it's still for Windows, since MSYS is for Windows).
You may want to see Dockerfile.
https://github.com/homuler/MediaPipeUnityPlugin/blob/47dbdc40c418ddf3d7ecbafabbf635e654a0aeba/docker/windows/x86_64/Dockerfile#L30-L34

**Comment by HakuWang** [comment]
I have not soved this problem. I‘m wondering if it is possible to bypass the build step on my desktop now ？or  will it be possible in the future ?

**Comment by homuler** [comment]
> I have not soved this problem.

What is your `PATH` value?
And can you run `git fetch` from `cmd.exe`? (if not, you've not installed `git` properly)

> I‘m wondering if it is possible to bypass the build step on my desktop now ？or will it be possible in the future ?

I'm considering publishing this plugin to AssetStore, but have no immediate plans to do so.

> Since i am new to docker, if i use docker on windows, can i use unity to develop and build andriod apks freely as on original windows ?

I recommend that you always use Docker as long as it is available.
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/FAQ#is-there-any-negative-impact-on-performance-by-using-docker.
> Docker is only used to build native libraries, not at runtime, so there is no impact on performance.
It is possible that the build time will increase (especially when the host OS is Windows), but unless you are building libraries repeatedly, it should be much less stressful than installing all the dependent tools manually.

**Comment by HakuWang** [comment]
> And can you run `git fetch` from `cmd.exe`? (if not, you've not installed `git` properly)
> 
> >

I can not run 'git fetch' from 'cmd.exe' only, but if i keep MSYS2 opened and cd to the same directory，i can run git command from 'cmd.exe' and the building have been successful. Now i can run the Start scene within unity. Thanks a lot.

By the way,  i have also tried [Docker Windows Container]，and stucked in the installing unzip... process. I did remove the folder manully like the step-3 of the installtion guide, but it still stucked. Maybe it‘s normal that the building of image cost hours? I will try it again and post the logs later.

**Comment by homuler** [comment]
> Maybe it‘s normal that the building of image cost hours?

It depends on your machine. Especially it tends to take a lot of time to install Visual Studio.
Note that you may need to remove folders under `$Recycle.Bin` repeatedly.

**Comment by HakuWang** [comment]
Thanks a lot. I  built successfully by [Docker Windows Container] .
