### ISSUE TITLE
"docker/windows/x86_64/Dockerfile" can not execute completely

### ISSUE THREAD

**Issue by a591537394** [homuler/MediaPipeUnityPlugin#478]
### Plugin Version or Commit ID

v0.8.3

### Unity Version

2020.3.30f1

### Your Host OS

Windows10 Education

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

VisualStudio C++: 14.29.30133
Windows SDK: 10.0.22000.194

### Command Sequences

docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile

### Log

![image](https://user-images.githubusercontent.com/45918609/156919993-dce2c682-3dbc-4782-8760-3f7af5204119.png)

not anything log had been throw
the dockerfile was running to that place "installing p7zip" ,and then the process program had been not action. 
![image](https://user-images.githubusercontent.com/45918609/156919140-2f59ae2e-99a5-4d07-806d-e9188b13750e.png)

**Comment by a591537394** [comment]
No matter how long i wait, it also can't finish execution

**Comment by homuler** [comment]
Please read [the installation guide](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-windows-container) more carefully.

> This process will hang when MSYS2 is being installed.
If this issue occurs, remove `C:\ProgramData\Docker\tmp\hcs*\Files\$Recycle.Bin\` manually (hcs* is random name).
cf. https://github.com/docker/for-win/issues/8910
