### ISSUE TITLE
iam facing this problem when iam building it for android 

### ISSUE THREAD

**Issue by AhmedEmadEldinHussin** [homuler/MediaPipeUnityPlugin#48]
cd C && bazel build -c opt --config=android_arm64 mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android mediapipe_api:mediapipe_models mediapipe_api:mediapipe_proto_srcs
Starting local Bazel server and connecting to it...
ERROR: While resolving toolchains for target //mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 3.176s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded, 119 targets c\
onfigured)
make: *** [Makefile:52: android_arm64] Error 1

**Comment by homuler** [comment]
Maybe the same issue as https://github.com/homuler/MediaPipeUnityPlugin/issues/42 .
Try this -> https://github.com/homuler/MediaPipeUnityPlugin/issues/42#issuecomment-767962207

**Comment by AhmedEmadEldinHussin** [comment]
okay thank you Iam goint to try it now

**Comment by homuler** [comment]
Will you run this command and share the output, please?

```sh
echo $ANDROID_HOME
echo $ANDROID_NDK_HOME
make android_arm64
```

I'd like to make sure that you run `make` with the envorinment varibales set, because you set those variables in only current session ↓.
https://github.com/homuler/MediaPipeUnityPlugin/issues/42#issuecomment-773098484

**Comment by homuler** [comment]
And wil you tell me your `gcc` and `g++` version, please?

**Comment by homuler** [comment]
It was already resolved ↓.
https://github.com/homuler/MediaPipeUnityPlugin/issues/42#issuecomment-773128891

**Comment by AhmedEmadEldinHussin** [comment]
now when i opened a new terminal to check the variables it is not giving me any result
gcc 
9.3.0
g++ 
9.3.0

**Comment by homuler** [comment]
If you'd like to set those variables in all the bash session, you should edit such a file as `.bash_profile`.

**Comment by AhmedEmadEldinHussin** [comment]
Okay I will do that
Thanks for your help and your time🙂
