### ISSUE TITLE
Running project in Unity Editor for android arm64 build

### ISSUE THREAD

**Issue by appSimfusion** [homuler/MediaPipeUnityPlugin#480]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.29.f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor, Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 16.10.3

### [Android Only] Android Build Tools and NDK Version

Build tools: 30.0.2
NDK: 21.4.7075529

### Command Sequences

python build.py build --desktop cpu --opencv=cmake -v
python build.py build --android arm64 -vv

### Log

(Please read my step by step description in Additional Context about what Im doing to have better unstanding)
Building Android APK , install app in Android phone success, but while I debug in unity editor it return error:
**Log:**DllNotFoundException: mediapipe_c
Mediapipe.Glog.set_Logtostderr (System.Boolean value) (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/Glog.cs:27)
Mediapipe.Unity.GlobalConfigManager.SetFlags () (at Assets/Mediapipe/Samples/Common/Scripts/GlobalConfigManager.cs:118)
Mediapipe.Unity.Bootstrap+<Start>d__17.MoveNext () (at Assets/Mediapipe/Samples/Common/Scripts/Bootstrap.cs:48)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <d3b66f0ad4e34a55b6ef91ab84878193>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

### Additional Context

What is my target: Develop unity game for Android, need to play and debug in Unity Editor.
What is the problem: Project fail to run in Unity Editor.

I have read #455 and #459
I built my project 2022/2/28(should be after the fix), which I should have mediapipe_c instead of libmediapipe_c.
In Unity Editor I have a libmediapipe_c.so.
![20220307@libmediapipe_c](https://user-images.githubusercontent.com/88776023/157029477-016d5046-486f-43a5-b6b6-0dfa5c917d72.png)
What is my question: 
1. Is the above fix suppose to fix the dll issue in Unity Editor for Android build?
2. Is my build invalid because I got libmediapipe_c instead  of mediapipe_c ?
3. Does libmediapipe_c.so related to libmediapipe_c.dll? So I can prove my build is correct or not.

What did I do:
1. I followed installation guide: https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide
2. Build project finish for Android (python build.py build --android arm64 -vv).
3. Play project with Start Scene in Unity, error Log occur.
6. Built android APK success, without error.
7. Add custom coddings into project.
8. Debug with abd logcat
9. Debug logcat will be inconvenient in future development

**Comment by appSimfusion** [comment]
Thanks for quick respone!!
However I fail to clone v0.8.3

**Error thrown:**
ERROR: /home/mediapipe/mediapipe_api/framework/BUILD:131:17: Executing genrule //mediapipe_api/framework:packet_factory_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/189/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.1-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/framework/packet_factory.proto
mv bazel-out/k8-opt/bin/PacketFactory.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/framework/PacketFactory.cs)
')
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
Target //mediapipe_api:mediapipe_proto_srcs failed to build

**Also, some of the files are missing:**
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/fc70a32ecd248dd7612d75d2177125ed14541367.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/a87782c34d667d1c1a18fe82a9a7abfc72fd345b.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

What did I do: 
     1).Follow installing guide of Docker linux container: [https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container](url)
     2).Failed on Step 5

Possible cause of this issue: Im using v0.8.9 of mediapipe instead of 0.8.3
	1). At MediaPipeUnityPlugin/README.md it said the mediapipe is 0.8.9 : This is a Unity (2020.3.30f1) [Native Plugin](https://docs.unity3d.com/Manual/NativePlugins.html) to use [MediaPipe](https://github.com/google/mediapipe) (0.8.9).
        2). I got SDK and NDK path error, so that I commented out the android_ndk_repository() line according to this : [https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#either-the-path-attribute-of-android_ndk_repository-or-the-android_ndk_home-environment-variable-must-be-set](url)

What will I try:
        1). Get a clone of v0.8.3
        2). repeat steps of Docker linux container

Provide the whole cmd log in case you need it:
[https://drive.google.com/file/d/1O7ArXs23Ky7FXSjrDoNAmhkhH5UXAeH8/view?usp=sharing](url)

**Comment by appSimfusion** [comment]
> What will I try: 
> 1). Get a clone of v0.8.3 
> 2). repeat steps of Docker linux container

Update: found out that I already using v0.8.3
Will try getting SDK and NDK to api_level 21

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#binbash-line-1-r-command-not-found.

NDK's API level is irrelevant to native libraries built for Desktop.

**Comment by appSimfusion** [comment]
> See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#binbash-line-1-r-command-not-found.
> 
> NDK's API level is irrelevant to native libraries built for Desktop.

Understood, Thanks for advice.
So I tried to get 0.8.3 and getting same error.

Error thrown:
ERROR: /home/mediapipe/mediapipe_api/framework/BUILD:131:17: Executing genrule //mediapipe_api/framework:packet_factory_cs failed: (Exit 127): bash failed: error executing command
(cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/189/execroot/mediapipe_api &&
exec env -
PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.1-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc --proto_path=. --proto_path=bazel-out/k8-opt/bin --proto_path=$(pwd)/external/com_google_protobuf/src --proto_path=$(pwd)/external/com_google_mediapipe --csharp_out=bazel-out/k8-opt/bin mediapipe/framework/packet_factory.proto
mv bazel-out/k8-opt/bin/PacketFactory.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/framework/PacketFactory.cs)
')
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
Target //mediapipe_api:mediapipe_proto_srcs failed to build

What did I do:
1).Follow installing guide of Docker linux container: [https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container](https://github.com/homuler/MediaPipeUnityPlugin/issues/url)
2). Not able to run git apply docker/linux/x86_64/pacman.patch in step 3. 
![pacmen](https://user-images.githubusercontent.com/88776023/157229516-1275f10b-557e-45ec-a789-4dc832018498.jpg)
3). Run docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile
4). Failed on Step 5

What will I try:
1). What and where to get the pacman.patch
2). docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile.ubuntu

**Comment by homuler** [comment]
> >See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#binbash-line-1-r-command-not-found.
>
> Understood, Thanks for advice.
So I tried to get 0.8.3 and getting same error.

Have you really checked the above link?
> Probably you've set core.autocrlf=true in .gitconfig (run git config -l).
Check out the source code as it is without changing the line feed code.
>
> See https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace for more details.

What I mean here is that this error occurs because you have changed the line feed code of the source files (i.e. LF -> CR+LF), maybe unconsciously.

> 2). Not able to run git apply docker/linux/x86_64/pacman.patch in step 3.

Never mind, this step is stale and I've just updated the documentation.

**Comment by appSimfusion** [comment]
> > > See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#binbash-line-1-r-command-not-found.
> > 
> > 
> > Understood, Thanks for advice.
> > So I tried to get 0.8.3 and getting same error.
> 
> Have you really checked the above link?

Sorry I must have missed your point here

> > Probably you've set core.autocrlf=true in .gitconfig (run git config -l).
> > Check out the source code as it is without changing the line feed code.
> > See https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace for more details.
> 
> What I mean here is that this error occurs because you have changed the line feed code of the source files (i.e. LF -> CR+LF), maybe unconsciously.
> 
> > 2). Not able to run git apply docker/linux/x86_64/pacman.patch in step 3.
> 
> Never mind, this step is stale and I've just updated the documentation.

Im sorry that I have missed your point, and I have just get it work now!
I corrected the line feed code fixed and it worked.
Thank you for all your assistance and patience!
