### ISSUE TITLE
bazel 5.0.0 find Android NDK error and bazel 4.2.2 compling error

### ISSUE THREAD

**Issue by wildfire2015** [homuler/MediaPipeUnityPlugin#485]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.30f1

### Your Host OS

win10

### Target Platform

UnityEditor

### Command Sequences

python build.py build --desktop cpu --include_opencv_libs -vv

### Log

PS F:\mygit\Work\MediaPipeUnityPlugin> python build.py build --desktop cpu --include_opencv_libs -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root D:/bazel/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//pq//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: D:/bazel/_bzl/gfczg2k6/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: F:/mygit/work/mediapipeunityplugin/WORKSPACE:327:23: fetching android_ndk_repository rule //external:androidndk: java.io.IOException: Expected directory at F:/AndroidSDK/ndk/23.1.7779620/platforms but it is not a directory or it does not exist. Unable to read the Android NDK at F:/AndroidSDK/ndk/23.1.7779620, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is correct, the contents in the Android NDK directory may have been modified.
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Expected directory at F:/AndroidSDK/ndk/23.1.7779620/platforms but it is not a directory or it does not exist. Unable to read the Android NDK at F:/AndroidSDK/ndk/23.1.7779620, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is correct, the contents in the Android NDK directory may have been modified.
INFO: Elapsed time: 336.848s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (52 packages loaded, 23 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework/formats/annotation ... (10 packages)
    Fetching @local_execution_config_python; fetching
    Fetching @com_google_protobuf; Restarting.
Traceback (most recent call last):
  File "F:\mygit\Work\MediaPipeUnityPlugin\build.py", line 447, in <module>
    Argument().command().run()
  File "F:\mygit\Work\MediaPipeUnityPlugin\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "F:\mygit\Work\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\pq\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root D:/bazel/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//pq//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

i build with bazel 4.2.2 ,get an compling error

ERROR: D:/bazel/_bzl/gfczg2k6/external/com_google_mediapipe/mediapipe/modules/holistic_landmark/calculators/BUILD:21:11: Compiling mediapipe/modules/holistic_landmark/calculators/hand_detections_from_pose_to_rects_calculator.cc failed: (Exit 2): cl.exe failed: error executing command
  cd D:/bazel/_bzl/gfczg2k6/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
    SET PROCESSOR_LEVEL=23
    SET PROCESSOR_REVISION=7100
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Users//pq//AppData//Local//Programs//Python//Python39//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\pq\AppData\Local\Temp
    SET TMP=C:\Users\pq\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe @bazel-out/x64_windows-opt/bin/external/com_google_mediapipe/mediapipe/modules/holistic_landmark/calculators/_objs/hand_detections_from_pose_to_rects_calculator/hand_detections_from_pose_to_rects_calculator.obj.params
Execution platform: @local_execution_config_platform//:platform
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30136 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 error D8022 :无法打开“bazel-out/x64_windows-opt/bin/external/com_google_mediapipe/mediapipe/modules/holistic_landmark/calculators/_objs/hand_detections_from_pose_to_rects_calculator/hand_detections_from_pose_to_rects_calculator.obj.params”
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 45.128s, Critical Path: 41.01s
INFO: 372 processes: 160 internal, 212 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "F:\mygit\Work\MediaPipeUnityPlugin\build.py", line 447, in <module>
    Argument().command().run()
  File "F:\mygit\Work\MediaPipeUnityPlugin\build.py", line 143, in run
    self._run_command(self._build_desktop_commands())
  File "F:\mygit\Work\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\pq\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root D:/bazel/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//pq//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

then i use the bazel 5.0.0, when find android ndk ,i set the folder F:/AndroidSDK/ndk/23.1.7779620 but get an subfolder F:/AndroidSDK/ndk/23.1.7779620/platforms

**Comment by homuler** [comment]
Maybe the same issue as #442.
You are free to not follow the guide (e.g. installing `bazel` instead of `bazelisk`), but I will not support you in that case.
