### ISSUE TITLE
Syntax Error on build.py

### ISSUE THREAD

**Issue by Magistrix93** [homuler/MediaPipeUnityPlugin#486]
### Plugin Version or Commit ID

v0.7.0

### Unity Version

2019.4.31

### Your Host OS

macOS Monterey 12

### Target Platform

UnityEditor, Mac Standalone

### Command Sequences

python build.py build --desktop cpu

### Log

File "build.py", line 47
    self.console.v(f"Running `{' '.join(command_list)}`")

### Additional Context

python version : Python 3.9.10

bazel version: bazel 5.0

gcc version: 
Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: arm64-apple-darwin21.3.0
Thread model: posix

Nuget version: NuGet Version: 5.9.0.7134

**Comment by homuler** [comment]
Please, please, please read the document.

> - Make sure you're using the latest version.
> - Check [the troubleshooting page](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#troubleshooting) to see if the solution is listed there.
> - Check to make sure someone hasn't already opened a similar [issue](https://github.com/homuler/MediaPipeUnityPlugin/issues).

There are too many mistakes and it is beyond the limit of free support.

**Comment by Magistrix93** [comment]
Solved using this command

python3 build.py build --desktop cpu

It was trying to use python 2.7 even with 3.9.10 installed

**Comment by Magistrix93** [comment]
How when I try to build now I get this error:

ERROR: /private/var/tmp/_bazel_simone/dc904105e2b07f787553d11f58e8ee6e/external/com_google_mediapipe/mediapipe/modules/holistic_landmark/BUILD:230:26: Executing genrule @com_google_mediapipe//mediapipe/modules/holistic_landmark:hand_visibility_from_hand_landmarks_from_pose_graph failed: (Aborted): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

tried with 

python3 build.py build --desktop cpu
python3 build.py build --desktop cpu --include_opencv_lib
python3 build.py build --desktop cpu --opencv cmake
python3 build.py build --desktop cpu --opencv local
