### ISSUE TITLE
Any example for `ResourceManager`?

### ISSUE THREAD

**Issue by Speykious** [homuler/MediaPipeUnityPlugin#488]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

any (?)

### Your Host OS

Arch Linux

### Target Platform

Windows Standalone, Linux Standalone

### Description

At first, it was unclear to me how to use the `ResourceManager` abstract class.
However, after digging in the code, I found that the `IntPtr output` parameter is supposed to be an `std::string*` on the C++ side.
This is the C++ delegate type:
```cpp
typedef bool ResourceProvider(const char* path, std::string* output);
```
This is a big problem because C++ does not provide any ABI for its C++ types. Thus I cannot use any C++ string method such as `output->clear()` or `output->append([...])`, which are what the `GetContents()` method from Mediapipe uses:
```cpp
absl::Status GetContents(absl::string_view file_name, std::string* output,
                         bool read_as_binary) {
  FILE* fp = fopen(file_name.data(), read_as_binary ? "rb" : "r");
  if (fp == NULL) {
    return mediapipe::InvalidArgumentErrorBuilder(MEDIAPIPE_LOC)
           << "Can't find file: " << file_name;
  }

  output->clear();
  while (!feof(fp)) {
    char buf[4096];
    size_t ret = fread(buf, 1, 4096, fp);
    if (ret == 0 && ferror(fp)) {
      return mediapipe::InternalErrorBuilder(MEDIAPIPE_LOC)
             << "Error while reading file: " << file_name;
    }
    output->append(std::string(buf, ret));
  }
  fclose(fp);
  return absl::OkStatus();
}
```
Is there a way that I can reproduce the above function in C#, or does it need a C interface type capable of using C++'s `std::string*` methods?

### Additional Context

We'd like to use a `ResourceManager` to provide Mediapipe resources from a DLL for instance.

**Comment by Speykious** [comment]
I just remembered: there is an `StdString` type in `External`. However, it doesn't contain all methods of the C++ `std::string`.
So I think what I can do is contribute some methods to make the resource manager possible to use.

**Comment by Speykious** [comment]
Update: for now, the following delegate works.
```cs
        public unsafe override ResourceProvider ProvideResource => (path, output) =>
        {
            Console.WriteLine($"ResourceProvider: providing resource '{path}'");
            using StdString strOutput = new StdString(output);
            using StdString resource = new StdString(File.ReadAllBytes(path));
            resource.Swap(strOutput);
            return true;
        };
```
I do think there's a better way to implement this, but at least now people will know that this solution exists :)

**Comment by homuler** [comment]
Actually, `LocalResourceManager` implements such a method.
https://github.com/homuler/MediaPipeUnityPlugin/blob/42106737e3d4b57efddd2e4d8e646b7b8e283fba/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/LocalResourceManager.cs#L72-L99

**Comment by Speykious** [comment]
Oh! Funny how I didn't find that earlier... Thanks.
I guess the issue is resolved now
