### ISSUE TITLE
Hand Tracking - track a hand wear a glove in blue color

### ISSUE THREAD

**Issue by appSimfusion** [homuler/MediaPipeUnityPlugin#489]
### Feature Description

Tracking a hand that wear blue glove

### Current Behaviour/State

We tested hand tracking feature while user wear glove in blue color and creamy white(very close to skin color).
Track success :
Wearing creamy white glove
Track fail :
Wearing blue color glove

So we guess color domain have affected hand detection.
Is there any way to switch the color domain of detecting a hand?
Or if we get it wrong, how should we track a hand with blue glove on?

### Additional Context

You can check our screenshot here, where the hand tracking fail to detect a hand wearing blue glove:
https://drive.google.com/file/d/14jn4RPZ3x6uXFtP01ZftsET-bAP6nnnh/view?usp=sharing

P.S. Your plugin works truly well and is very stable, Thank you for your efford!

**Comment by homuler** [comment]
A similar issue seems to have been created in the official repositories (https://github.com/google/mediapipe/issues/3091).

In most cases, this project does not modify the behavior of MediaPipe, so if the detection results themselves are problematic, please ask in the official community.

> Is there any way to switch the color domain of detecting a hand?

At least, you can swap the RGB channels (e.g. R <-> B), but it is probably not what you are looking for, as this method can only be used if you know the color of the glove beforehand (and of course, it changes the color of everything other than the glove, so the result would be unreliable).
