### ISSUE TITLE
Cannot open plugin in Unity 2021.2.3f1

### ISSUE THREAD

**Issue by aaronvdbrugge** [homuler/MediaPipeUnityPlugin#490]
### Plugin Version or Commit ID

Current version

### Unity Version

Unity 2021.2.3f1

### Your Host OS

MacOS

### Target Platform

UnityEditor

### Description

I get a whole range of errors:

![image](https://user-images.githubusercontent.com/45329627/158091226-59ba9e77-5f50-4e9d-8ec6-7a75bbcf7bbc.png)

**Comment by homuler** [comment]
Please read https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation
