### ISSUE TITLE
Build fails with macOS Monterey 12.3 because /usr/bin/python is removed

### ISSUE THREAD

**Issue by kotran88** [homuler/MediaPipeUnityPlugin#494]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.29f1

### Your Host OS

Mac OS Monterrey 12.3

### Target Platform

Android

### Description

I'm using m1 MacBook silicon  ,
what is weird to me in wiki page....
brew install command is wrong...I think...
what I know is arch -arm64 brew install 
not just brew install...

and then... I just followed all the wiki 's m1 Mac precess until 4. Install Basilisk. 
```

pedrojung@pedroui-MacBookPro ~ % python3.9 --version
Python 3.9.10
pedrojung@pedroui-MacBookPro ~ % which brew
/opt/homebrew/bin/brew
pedrojung@pedroui-MacBookPro ~ % which bazelisk
/opt/homebrew/bin/bazelisk
pedrojung@pedroui-MacBookPro ~ % vim ~/.zshrc    
pedrojung@pedroui-MacBookPro ~ % clear              
pedrojung@pedroui-MacBookPro ~ % which b
pedrojung@pedroui-MacBookPro ~ % python --version
zsh: command not found: python
pedrojung@pedroui-MacBookPro ~ % 
```

there's one problem in doing 5. Install NuGet. 
/usr/sbin/softwareupdate --install-rosetta
it cause Installing Rosetta 2 on this system is not supported. ,  So I skip it. 
and...I install brew again with 

arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
arch -x86_64 /usr/local/Homebrew/bin/brew install nuget

and then. I add path with command 
vim ~/.zshrc    
because ~/.zprofile is not working with error
```
pedrojung@pedroui-MacBookPro mediapipeUnityPlugin-master % sudo ~/.zprofile                                   
Password:
sudo: /Users/pedrojung/.zprofile: command not found
```

then I added path as described in wiki 

I already installed Xcode so skip installing Xcode. 

Then~ I thought I finished process , I download GitHub repo 
and the run build command
python build.py build --desktop cpu --android arm64 --ios arm64 -vv 
because I will run it on android and iOS app. 
but it cause error 

```

  /Users/pedrojung/arbasicprojectforshoes/MediaPipeUnityPlugin-master/WORKSPACE:96:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_pedrojung/0a15291d931ea3e072a81c5ed0f97251/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/pedrojung/arbasicprojectforshoes/MediaPipeUnityPlugin-master/mediapipe_api/BUILD:194:8: PackageZip mediapipe_api/mediapipe_proto_srcs.zip failed: (Exit 127): build_zip failed: error executing command 
  (cd /private/var/tmp/_bazel_pedrojung/0a15291d931ea3e072a81c5ed0f97251/sandbox/darwin-sandbox/216/execroot/mediapipe_api && \
  exec env - \
    PATH=/Users/pedrojung/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/opt/homebrew/bin:/Users/pedrojung/.nvm/versions/node/v14.17.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/pedrojung/Downloads/flutter/bin:/Users/pedrojung/Downloads/flutter/bin \
  bazel-out/darwin_arm64-opt-exec-50AE0418/bin/external/rules_pkg/pkg/private/zip/build_zip -o bazel-out/darwin_arm64-dbg/bin/mediapipe_api/mediapipe_proto_srcs.zip -d / -t 315532800 -m 0555 --manifest bazel-out/darwin_arm64-dbg/bin/mediapipe_api/mediapipe_proto_srcs.manifest)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
env: python: No such file or directory
Target //mediapipe_api:mediapipe_proto_srcs failed to build
INFO: Elapsed time: 0.180s, Critical Path: 0.03s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/pedrojung/arbasicprojectforshoes/MediaPipeUnityPlugin-master/build.py", line 447, in <module>
    Argument().command().run()
  File "/Users/pedrojung/arbasicprojectforshoes/MediaPipeUnityPlugin-master/build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/Users/pedrojung/arbasicprojectforshoes/MediaPipeUnityPlugin-master/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c dbg --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
```

what may be the problem? I look into error I think...it's about bazel...????
and...env: python: No such file or directory...???

I typed on python --version on zsh command terminal , 
cause error 
```
pedrojung@pedroui-MacBookPro ~ % python --version
zsh: command not found: python
```

but with python3.9 --version , it's okay. 
```
pedrojung@pedroui-MacBookPro ~ % python3.9 --version
Python 3.9.10
```

**Comment by homuler** [comment]
It looks like that macOS Monterey 12.3 removed `/usr/bin/python` (https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes).

Please set the path to `python` manually.
```sh
export PATH="$(brew --prefix)/opt/python/libexec/bin":$PATH
```

See also https://docs.brew.sh/Homebrew-and-Python.

**Comment by homuler** [comment]
Unfortunately, `rules_apple` does not seem to export the `PATH` set by the user, so we cannot build the iOS framework with macOS Monterey 12.3 now.

I've not investigated this problem closely, but an issue is created at the `rules_python` repository.
https://github.com/bazelbuild/rules_python/issues/660

**Comment by homuler** [comment]
I confirmed that the build finished successfully with bazel 5.0.0, so I'll update `.bazelversion`.
