### ISSUE TITLE
How to get position(x,y,z) of hand landmark?

### ISSUE THREAD

**Issue by G1ackhand** [homuler/MediaPipeUnityPlugin#497]
### Plugin Version or Commit ID

v.0.8.2

### Unity Version

2020.3.29f1

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### Description

Hi, I'm a Korean college student and I'm preparing a graduation project.
Our team is trying to develop a finger counter to make an AR game(like this video = https://youtu.be/p5Z_GGRCI5s ).
But to do this, we need to get the x, y, z values ​​for each landmark.
How can I access it?

### Additional Context

First, our team is studying by looking at the solution script under Handtracking, but I don't know how to do it.
Thank you for your cooperation!

**Comment by homuler** [comment]
> our team is studying by looking at the solution script under Handtracking, but I don't know how to do it.

Can you list specifically (e.g. showing the code) which parts you don't understand?
If they say they don't understand everything, all I can do is ask them to look at the code.

Anyway, a little older code might give you a better idea of what is going on.
https://github.com/homuler/MediaPipeUnityPlugin/blob/a16d74c0a170f3bf271df7a09a7b63f46a55a5f1/Assets/Mediapipe/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs
