### ISSUE TITLE
no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type

### ISSUE THREAD

**Issue by kotran88** [homuler/MediaPipeUnityPlugin#499]
### Plugin Version or Commit ID

v0.82(latest)

### Unity Version

2020.3.30

### Your Host OS

window 10 Professional

### Target Platform

Android

### [Android Only] Android Build Tools and NDK Version

30.0.3
NDK : 23.0.7272597

### Command Sequences

python build.py build --android arm64 --android_ndk_api_level 21 -vv

### Log

DEBUG: C:/_bzl/hmjgtv3e/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --copt, --cpu, --crosstool_top, and 6 more have changed, discarding analysis cache.
ERROR: C:/users/pedro/downloads/mediapipeunityplugin-master/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:10:14: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted:
INFO: Elapsed time: 0.288s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 167 targets configured)
Traceback (most recent call last):
  File "C:\Users\pedro\Downloads\MediaPipeUnityPlugin-master\build.py", line 436, in <module>
    Argument().command().run()
  File "C:\Users\pedro\Downloads\MediaPipeUnityPlugin-master\build.py", line 155, in run
    self._run_command(self._build_android_commands())
  File "C:\Users\pedro\Downloads\MediaPipeUnityPlugin-master\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,

### Additional Context

what may be the problem? 
problem is that on mac monterrey 12.3 & window, it cause same error log. 
what I want is to implement objectron example on android device with unity.

**Comment by homuler** [comment]
Set `ANDROID_HOME` and `ANDROID_NDK_HOME`.
Please also note that Bazel does not support NDK >= r22 yet.
cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#android-configuration

By the way, using Docker is far easier to build `mediapipe_android.aar`.
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container

**Comment by smtabatabaie** [comment]
I'm trying to run build.py for android following the document on my M1 Mac. I installed android studio and installed build tools 30.0.3 and also ndk 20.1.5948944 and also set ANDROID_HOME and ANDROID_NDK_HOME in my ~/.zprofile and I can also see them set when I run printenv. but when I run "python3 build.py build --android arm64 -vv" to build for android I get the following errors: 
ERROR: /Users/smtabatabaie/UnityWorkSpace/MediapipeUnity_homuler2/MediaPipeUnityPlugin2/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:10:14: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
---------------------------------------------------------
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: 

I'd appreciate it if you can help me with this.

**Comment by smtabatabaie** [comment]
I'm trying to run build.py for android following the document on my M1 Mac. I installed android studio and installed build tools 30.0.3 and also ndk 20.1.5948944 and also set ANDROID_HOME and ANDROID_NDK_HOME in my ~/.zprofile and I can also see them set when I run printenv. but when I run "python3 build.py build --android arm64 -vv" to build for android I get the following errors:

ERROR: /Users/smtabatabaie/UnityWorkSpace/MediapipeUnity_homuler2/MediaPipeUnityPlugin2/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:10:14: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type

ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted: 

I'd really appreciate it if you can help me with this.

**Comment by smtabatabaie** [comment]
> I'm trying to run build.py for android following the document on my M1 Mac. I installed android studio and installed build tools 30.0.3 and also ndk 20.1.5948944 and also set ANDROID_HOME and ANDROID_NDK_HOME in my ~/.zprofile and I can also see them set when I run printenv. but when I run "python3 build.py build --android arm64 -vv" to build for android I get the following errors:
> 
> ERROR: /Users/smtabatabaie/UnityWorkSpace/MediapipeUnity_homuler2/MediaPipeUnityPlugin2/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:10:14: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
> 
> ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted:
> 
> I'd really appreciate it if you can help me with this.

I could fix it by downloading and running setup_android_sdk_and_ndk.sh, it's a bash script from mediapipe repository which sets android SDK and android ndk.
