### ISSUE TITLE
How to obtain the landmark positions in handtracking?

### ISSUE THREAD

**Issue by yellowflash07** [homuler/MediaPipeUnityPlugin#5]
Hello, the scene is running perfectly. I would like to know how to obtain the position of the 21 landmarks of the hand. preferably in vector information

**Comment by homuler** [comment]
I'm developing now, and I'll implement the feature this weekend.
Currently, you can get landmarks only on FaceMesh scenes.

cf. https://github.com/homuler/MediapipeUnityPlugin/blob/master/Assets/Mediapipe/Examples/FaceMesh/Scripts/FaceMeshGraph.cs#L41

**Comment by yellowflash07** [comment]
Awesome! looking forward to it! great work!!!

**Comment by yellowflash07** [comment]
is this done yet? if so how do i get the landmarks? is it in a unity friendly format?

**Comment by homuler** [comment]
You can get landmarks here.
https://github.com/homuler/MediapipeUnityPlugin/blob/master/Assets/Mediapipe/Examples/HandTracking/Scripts/HandTrackingGraph.cs#L51

Please note that the coordinates of landmarks are upside down (in mediapipe, (0, 0) is the top-left point).

**Comment by ManuelRibeiro89247** [comment]
Hello, im currently using the latest release version of the Plugin and cant seem to find a way to obtain the position of the 21 landmarks of the hand. I may be mistaken, but the current HandTrackingGraph.cs file is very different from [this] (https://github.com/homuler/MediapipeUnityPlugin/blob/de4d054f4795ed47997da205b0a152c64d309760/Assets/Mediapipe/Examples/HandTracking/Scripts/HandTrackingGraph.cs#L95). is it still possible to get the landmarks or do i need to use another version of the plugin?
