### ISSUE TITLE
i  got those errors after buiding the project to android and i uploaded it into unity.

### ISSUE THREAD

**Issue by kitmek1** [homuler/MediaPipeUnityPlugin#50]
![Screenshot from 2021-02-04 15-19-47](https://user-images.githubusercontent.com/78305321/106885872-ab7fc000-66fc-11eb-8396-89e8c99d01bf.png)
here is the screen shot of the errors can you guide me further how it runs..
here is some errors:
Error 1:
Assets/MediaPipe/SDK/Scripts/Annotation/AnnotationController.cs(3,32): error CS0234: The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)
Error 2:
 Assets/MediaPipe/SDK/Scripts/Framework/CalculatorGraphConfig.cs(1,20): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)
others are also like that.....

**Comment by homuler** [comment]
Did you run `make install`?

**Comment by kitmek1** [comment]
okay thank you it is installed\
