### ISSUE TITLE
Apple intel + silicon build

### ISSUE THREAD

**Issue by Magistrix93** [homuler/MediaPipeUnityPlugin#501]
### Plugin Version or Commit ID

v0.8.3

### Unity Version

2021.2.2

### Your Host OS

macOS Monterey 12.3

### Target Platform

Mac Standalone

### Description

I have the dylib plugin builded for both apple silicon cpu and intel cpu but I can't use both in my project because they have the same name and can't use cpu check realtime because plugin name it's a constant.

There is a way to use both in the same project/build?

**Comment by homuler** [comment]
You can create a universal library by yourself.
```sh
lipo -create -output libmediapipe_c.so libmediapipe_c_x86.so libmediapipe_c_arm.so
```

cf. https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by Magistrix93** [comment]
> You can create a universal library by yourself.
> 
> ```shell
> lipo -create -output libmediapipe_c.so libmediapipe_c_x86.so libmediapipe_c_arm.so
> ```
> 
> cf. https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

Thanks now we have an universal plugin for both systems!

**Comment by ROBYER1** [comment]
> You can create a universal library by yourself.
> 
> ```shell
> lipo -create -output libmediapipe_c.so libmediapipe_c_x86.so libmediapipe_c_arm.so
> ```
> 
> cf. https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

There is no longer a file for the Mac plugin called libmediapipe_c.so, so do I need to use a different command? I only have libmediapipe_c.dylib
