### ISSUE TITLE
Examples Freeze on M1 mac Unity 2021.2.16f1 memory leak

### ISSUE THREAD

**Issue by FUBAR2077** [homuler/MediaPipeUnityPlugin#503]
### Plugin Version or Commit ID

b1c7b61b6def14ef926651e8a98e849329cbc641

### Unity Version

2021.2.16f1

### Your Host OS

macOS Big Sur 11.5.2

### Target Platform

Mac Standalone

### Target Device

MacBook 13-inch M1, 2020

### Build Command

python build.py build --desktop cpu --opencv=cmake -vv

### Bug Description

Whole scene inside Unity freezes after a short while (under 3 mins).

### Steps to Reproduce the Bug

Bootstrap set to CPU.
Run StartScene then switch to holistic for fastest crash effect.

### Log

Log does not show anything strange. 
RAM is skyrocketing and macOS seems to be killing app on RAM limit.
[Editor-prev.log](https://github.com/homuler/MediaPipeUnityPlugin/files/8334445/Editor-prev.log)

### Screenshot/Video

![Screenshot 2022-03-23 at 16 45 55](https://user-images.githubusercontent.com/4373019/159739472-b7e1ee0a-76ec-4467-855b-6bec5bb17dc6.png)

**Comment by FUBAR2077** [comment]
It's probable that problem exists on other platforms as well - just iOS / macOS just poorly handles GC. I assume that Annotation Points cause this as they spawn and despawn, but there can be other sources as well. I'll see tomorrow if disabling drawing will help.

**Comment by homuler** [comment]
I am aware of this issue, but have never seen it occur anywhere other than on the M1 mac.
And I did not investigate this in detail as it could be a UnityEditor issue.
Does this problem occur when running the built (standalone) app?

> RAM is skyrocketing and macOS seems to be killing app on RAM limit.

If macOS killed the process, I think UnityEditor will not freeze but die silently.

**Comment by homuler** [comment]
maybe same as #392

**Comment by FUBAR2077** [comment]
> Does this problem occur when running the built (standalone) app?

Unfortunately yes. I even disabled annotations and it still uses memory up to freeze point.

**Comment by Magistrix93** [comment]
Same behaviour here, both editor and build

**Comment by homuler** [comment]
As @merlin-rtzr has checked out (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/392#issuecomment-1008790333), `Texture.GetNativeTexturePtr` seems to block the main thread.

Now I think this issue is duplicated and close it.
