### ISSUE TITLE
media pipe .dll file is not available can you check the issue

### ISSUE THREAD

**Issue by kitmek1** [homuler/MediaPipeUnityPlugin#51]
hello 
i run the project in unity and i get this issue all things i installed but still i get this error you can check the screenshot here.
![Screenshot from 2021-02-04 18-00-01](https://user-images.githubusercontent.com/78305321/106903324-4d120c00-6713-11eb-94d8-a39d6a4c2888.png)
i make a build for android also and it will not work on android also so how can i make it run..
here is error : 
DllNotFoundException: mediapipe_c
Mediapipe.ResourceUtil.InitializeResourceManager (Mediapipe.ResourceManager resourceManager) (at Assets/MediaPipe/SDK/Scripts/Util/ResourceUtil.cs:4)
SceneDirector+<Start>d__16.MoveNext () (at Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:60)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

thanks.

**Comment by homuler** [comment]
I updated README.
https://github.com/homuler/MediapipeUnityPlugin#installation

Please run `make && make install` anyway.
`make android_arm64` build libraries for Android (`mediapipe_android.aar`), but not for Desktop (`libmediapipe_c.so`).

**Comment by kitmek1** [comment]
okay thank you It worked  on unity but after building the apk

**Comment by homuler** [comment]
At latest commit, you can run examples on Unity Editor if the target platform isn't PC standalone.
