### ISSUE TITLE
Facial/hand recognition not working with custom image source

### ISSUE THREAD

**Issue by yoranmandema** [homuler/MediaPipeUnityPlugin#512]
### Description

Hello, I'm trying to make a custom image source that uses the color image from Unity's ARCameraManager so that I can use the depth image at the same time to hopefully make real measurements using both MediaPipe's landmarks and Unity's depth map generated at runtime.

The problem I'm running in at the moment is that this  custom image source does not work with any pose, facial or hand recognition solutions and thus doesn't place any landmarks. Any other solution like the object detection or hair segmentation solutions do seem to work.

I have tried to play around with different image formats (RGBA32, RGB24, BGRA32 etc) but none of those seem to matter in this case. I have also tried flipping the image upside down and rotating the device to see if MediaPipe is getting the wrong orientation of the image but this did not give me any results either.

Does anyone know if I might be missing something in my custom image source?

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/issues/343 may be helpful.
If your problem isn't still solved by it, please create another issue using [support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).
