### ISSUE TITLE
Pose Detection Not Working For The iOS build

### ISSUE THREAD

**Issue by UnityDev1021** [homuler/MediaPipeUnityPlugin#513]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.21f1

### Your Host OS

Windows 10 Home

### Target Platform

iOS

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 14.29.30135
Window SDK: 10.0.19041.685

### [iOS Only] XCode Version

13.2.1 (13C100)

### Command Sequences

I have build the iOS and desktop framework using the command :-
python build.py build --desktop cpu  --ios arm64 -vv

### Log

2022-04-06 15:14:40.042293+0530 MediaPipeUnityPlugin[1302:315917] Built from '2020.3/staging' branch, Version '2020.3.21f1 (a38c86f6690f)', Build type 'Development', Scripting Backend 'il2cpp'
2022-04-06 15:14:40.043795+0530 MediaPipeUnityPlugin[1302:315917] MemoryManager: Using 'Default' Allocator.
-> applicationDidFinishLaunching()
PlayerConnection initialized from /private/var/containers/Bundle/Application/442306F9-8031-4C8A-A556-32F42DFF9C58/MediaPipeUnityPlugin.app/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55000
Broadcasting "[IP] 169.254.1.97 [Port] 55000 [Flags] 19 [Guid] 2322942060 [EditorId] 1118275934 [Version] 1048832 [Id] iPhonePlayer(PsiBorgs-iPhone):56000 [Debug] 1 [PackageName] iPhonePlayer [ProjectName] MediaPipeUnityPlugin" to [169.254.255.255:54997]...
Waiting for connection from host on [0.0.0.0:55000]...
Remaining time:8s
Remaining time:7s
Remaining time:6s
Remaining time:5s
Remaining time:4s
Remaining time:3s
Remaining time:2s
Remaining time:1s
Remaining time:0s
Timed out. Continuing without host connection.
Started listening to [0.0.0.0:55000]
Starting managed debugger on port 56000
PlayerConnection already initialized - listening to [0.0.0.0:55000]
2022-04-06 15:14:50.258729+0530 MediaPipeUnityPlugin[1302:315917] Metal GPU Frame Capture Enabled
2022-04-06 15:14:50.258850+0530 MediaPipeUnityPlugin[1302:315917] Metal API Validation Enabled
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A13 GPU
Initialize engine version: 2020.3.21f1 (a38c86f6690f)
2022-04-06 15:14:51.041886+0530 MediaPipeUnityPlugin[1302:315917] Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x100fc85f0>.
2022-04-06 15:14:51.042559+0530 MediaPipeUnityPlugin[1302:315917] Unbalanced calls to begin/end appearance transitions for <UnityDefaultViewController: 0x100e14750>.
UnloadTime: 4.978750 ms
Chose Kippie Uppie
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
OpScreenScript:PlayClickedKU_S()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 7.272042 ms
System memory in use before: 30.3 MB.
System memory in use after: 30.4 MB.

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 1054.
Total: 1.105417 ms (FindLiveObjects: 0.089292 ms CreateObjectMapping: 0.036250 ms MarkObjects: 0.925833 ms  DeleteObjects: 0.053083 ms)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 8.574917 ms
System memory in use before: 30.5 MB.
System memory in use after: 30.5 MB.

Unloading 13 unused Assets to reduce memory usage. Loaded Objects now: 1029.
Total: 1.083292 ms (FindLiveObjects: 0.056625 ms CreateObjectMapping: 0.025042 ms MarkObjects: 0.572000 ms  DeleteObjects: 0.429125 ms)

Wrong Case Selected For Instruction Script
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
InsScript:NextClicked()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 8.404042 ms
System memory in use before: 30.7 MB.
System memory in use after: 30.3 MB.

Unloading 15 unused Assets to reduce memory usage. Loaded Objects now: 987.
Total: 2.238542 ms (FindLiveObjects: 0.245708 ms CreateObjectMapping: 0.049958 ms MarkObjects: 1.534917 ms  DeleteObjects: 0.407167 ms)

Bootstrap: Starting console window...
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Start>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Bootstrap: Setting global flags...
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Start>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

GlobalConfigManager: Global config file does not exist: /var/mobile/Containers/Data/Application/1BBDB4DE-E8F9-4E6A-B880-D48BE5271318/Documents/Cache/globalConfig.env
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogDebug(String, Object)
Mediapipe.Unity.GlobalConfigManager:get_Config()
Mediapipe.Unity.GlobalConfigManager:get_GlogLogtostderr()
Mediapipe.Unity.GlobalConfigManager:SetFlags()
Mediapipe.Unity.<Start>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Bootstrap: Initializing AssetLoader...
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Start>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Bootstrap: Preparing ImageSource...
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Start>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Bootstrap: Loading the first scene...
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Start>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.226542 ms
Calling Initializer
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Mediapipe.Unity.PoseTracking.PoseTrackingSolution:AssetInitializer()
Mediapipe.Unity.PoseTracking.PoseTrackingSolution:Awake()

Calling Initializer
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Mediapipe.Unity.PoseTracking.PoseTrackingSolution:AssetInitializer()
Mediapipe.Unity.PoseTracking.PoseTrackingSolution:Awake()

DetectionAnnotationController: Adding RectTransform to Annotation Layer
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogVerbose(String, Object)
Mediapipe.Unity.AnnotationController`1:Start()

System memory in use before: 34.0 MB.
System memory in use after: 34.1 MB.

Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 2845.
Total: 1.174083 ms (FindLiveObjects: 0.086500 ms CreateObjectMapping: 0.033750 ms MarkObjects: 1.037333 ms  DeleteObjects: 0.016333 ms)

PoseTrackingGraph: Config Type = CPU
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Initialize>d__39:MoveNext()
Mediapipe.Unity.<Run>d__20:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.WaitForResult:.ctor(MonoBehaviour, IEnumerator, Int64)
Mediapipe.Unity.GraphRunner:WaitForInit(RunningMode)
Mediapipe.Unity.<Run>d__12:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.ImageSourceSolution`1:Play()
Mediapipe.Unity.<Start>d__4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

PoseTrackingGraph: Running Mode = Sync
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, String, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:Log(LogLevel, String, Object)
Mediapipe.Unity.Logger:LogInfo(String, Object)
Mediapipe.Unity.<Initialize>d__39:MoveNext()
Mediapipe.Unity.<Run>d__20:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.WaitForResult:.ctor(MonoBehaviour, IEnumerator, Int64)
Mediapipe.Unity.GraphRunner:WaitForInit(RunningMode)
Mediapipe.Unity.<Run>d__12:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.ImageSourceSolution`1:Play()
Mediapipe.Unity.<Start>d__4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Waiting for WebCamTexture to start
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
Mediapipe.Unity.MemoizedLogger:Log(LogLevel, Object)
Mediapipe.Unity.Logger:Log(LogLevel, Object)
Mediapipe.Unity.Logger:LogVerbose(Object)
Mediapipe.Unity.<WaitForWebCamTexture>d__50:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

JumpingJack: Mediapipe.MediaPipeException: NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: PoseLandmarkCpu; Unable to find Calculator "PoseLandmarkCpu"
  at Mediapipe.Status.AssertOk () [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.GraphRunner+<Initialize>d__39.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.WaitForResult+<Run>d__20.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.MonoBehaviour.StartCoroutine (System.Collections.IEnumerator routine) [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.WaitForResult..ctor (UnityEngine.MonoBehaviour runner, System.Collections.IEnumerator inner, System.Int64 timeoutMillisec) [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.GraphRunner.WaitForInit (Mediapipe.Unity.RunningMode runningMode) [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.ImageSourceSolution`1+<Run>d__12[T].MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.MonoBehaviour.StartCoroutine (System.Collections.IEnumerator routine) [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.ImageSourceSolution`1[T].Play () [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.Solution+<Start>d__4.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:LogError(String, Object)
Mediapipe.Unity.MemoizedLogger:LogError(String, Object)
Mediapipe.Unity.Logger:LogError(String, Object)
Mediapipe.Unity.<Run>d__12:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

### Additional Context

The Desktop version works great on the Unity Editor without any flaw, but as soon as I build the intermediate files for the iOS and use the X-Code for building the app, it outputs the above error.

**Comment by homuler** [comment]
> PoseTrackingGraph: Config Type = CPU

Probably you have set `CPU` to `Inference Mode` to build for Desktop, but the sample app for iOS only supports `GPU`.
Please revert the change and build again.

**Comment by UnityDev1021** [comment]
@homuler Thanks For the info!!! I read somewhere that the inference mode has to be CPU so I set it to that, will try this method once and get back with the results.
