### ISSUE TITLE
Rasterization.cs errors, Need to remove to get a fresh 0.9.0 project to startup.

### ISSUE THREAD

**Issue by vltmedia** [homuler/MediaPipeUnityPlugin#518]
### Plugin Version or Commit ID

v0.9.0

### Unity Version

Rasterization.cs errors, Need to remove to get a fresh 0.9.0 project to startup.

### Your Host OS

Windows10

### Target Platform

UnityEditor

## Linux
```python build.py build --desktop gpu --android arm64 --opencv cmake -v```

## Windows
``` python build.py build --desktop cpu --opencv cmake -vv```

### Bug Description

After successfully building the v0.9.0 Plugin, upon opening the project in Unity, I am seeing a bunch of errors pertaining to ```Packages\com.github.homuler.mediapipe\Runtime\Scripts\Protobuf\Framework\Formats\Rasterization.cs ``` saying that things have been already defined.

I fixed this by either removing the file, or commenting everything in the file out (for dirty backup). 

A basic test of the solutions showed that everything still works for Windows 10 Editor and built, along with Linux Editor and builds after the removal of Rasterization.cs

### Steps to Reproduce the Bug

1. Build v0.9.0
2. Open the new project with Unity Hub
3. Errors occur.

### Log

![MP_090_Rasterization](https://user-images.githubusercontent.com/39071455/162253268-76256be3-f8e2-49fe-8e9a-d43151c71cc3.jpg)

**Comment by homuler** [comment]
`Rasterization.cs` path has changed at v0.9.0, so you need to remove it.
Please read [the relase note](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.9.0) for more details.

> To upgrade your local plugin version, please uninstall the current version first since some file paths have changed.
> ```sh
> python build.py uninstall
> python build.py build ...
> ```
