### ISSUE TITLE
Hand Landmarks returning values in reverse order

### ISSUE THREAD

**Issue by am-badshah** [homuler/MediaPipeUnityPlugin#519]
### Description

I am simply trying to check the Y values of a single finger (for instance Index finger) but I am getting values in reverse. The TIP y value is the smallest among the 4 values, MCP (base of the finger) is the highest value. 

` public void OnLeftHandLandmarksOutput(NormalizedLandmarkList landmarks)
{
 if (landmarks == null) return;
    Debug.Log("Index:  MCP = " + landmarks.Landmark[5].Y + " PIP = " + landmarks.Landmark[6].Y + " IP = " + 
    landmarks.Landmark[7].Y + " TIP = " + landmarks.Landmark[8].Y);
}`

OUTPUT: // MCP = 0.6847914 PIP = 0.6020046 IP = 0.5503851 TIP = 0.4998825
I even checked the x values and they seem to be reversed as well. 

Please let me know if i am doing something wrong

**Comment by homuler** [comment]
1. `ImageFrame` and `GpuBuffer` use the Image Coordinate System with the origin being at the top-left corner, whereas the origin is at the bottom-left corner in the Unity Screen Coordinate.
The output values also use the Image Coordinate System, so you need to reverse the `y` value.

2. `HandLandmarkTracking(GPU|CPU)` expects the input image to be mirrored (cf. https://google.github.io/mediapipe/solutions/hands#multi_handedness),
   > Note that handedness is determined assuming the input image is mirrored, i.e., taken with a front-facing/selfie camera with images flipped horizontally. If it is not the case, please swap the handedness output in the application.

   so the sample app flips the input image before sending it to MediaPipe (note that the 3rd argument (`expectToBeMirrored`) is set to `true`).
https://github.com/homuler/MediaPipeUnityPlugin/blob/a07f43dd588ce9425a8548a2e8debd3529c3e4e2/Assets/Mediapipe/Samples/Scenes/Hand%20Tracking/HandTrackingGraph.cs#L235
https://github.com/homuler/MediaPipeUnityPlugin/blob/a07f43dd588ce9425a8548a2e8debd3529c3e4e2/Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs#L265

`ImageCoordinate` class provides helper methods to transform coordinates.
https://github.com/homuler/MediaPipeUnityPlugin/blob/a07f43dd588ce9425a8548a2e8debd3529c3e4e2/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/ImageCoordinate.cs#L11-L16

Please also check out how the `AnnotationController` classes use these methods to annotate images.
