### ISSUE TITLE
In a shared project with git, the handness data values ​​are incorrect.

### ISSUE THREAD

**Issue by ADOHI** [homuler/MediaPipeUnityPlugin#525]
### Description

Development environment is window 10, not docker.

In a shared project with git, the handness data values ​​are incorrect.
Except for the project owner's pc, the data value is expressed as -1. (Other hand recognition data values ​​are correct).

Is this a problem caused by not doing pre-installation(like bazel, etc) on all PCs?  If so, is this a problem that can be solved using Docker?

I confirmed that the build shared after downloading it as a zip file works on all PCs.
Therefore, it is not considered that there is a problem with the project uploaded to git itself.

**Comment by homuler** [comment]
> I confirmed that the build shared after downloading it as a zip file works on all PCs.
Therefore, it is not considered that there is a problem with the project uploaded to git itself.

Maybe you're talking about the problem occurring among your project members, but the context is so lacking that I don't understand it at all.

If you need help, please use [bug report form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abug&template=bug_report.yml) or [support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml) and create the issue again.
