### ISSUE TITLE
after building it for unity and building  apk the apk is not working

### ISSUE THREAD

**Issue by kitmek1** [homuler/MediaPipeUnityPlugin#53]
after building the example for Android the example is not working

**Comment by homuler** [comment]
Please share the log, I cannot track down the cause without it.

If you haven't build AssetBundle yet, then you need to build it (it's not automated yet).
cf. https://github.com/homuler/MediaPipeUnityPlugin#android-1

**Comment by kitmek1** [comment]
yeah sure thanks for help now it works...
