### ISSUE TITLE
ARfoundation with MediaPipeUnityPlugin

### ISSUE THREAD

**Issue by yacineTazerout** [homuler/MediaPipeUnityPlugin#530]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.19f

### Your Host OS

Windows 11

### Target Platform

Android

### Description

Hi, how can i make the plugin work with ARfoundation ?

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/343 and https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#imageframe.

**Comment by yacineTazerout** [comment]
@homuler  ok thank you i'll chech
