### ISSUE TITLE
NEED A COMPREHENSIVE VIDEO GUIDE!!!!

### ISSUE THREAD

**Issue by TE-Devharajan-Rangarajan** [homuler/MediaPipeUnityPlugin#538]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2020.3.33f1

### Your Host OS

Windows 10 Pro

### Target Platform

Windows Standalone, Android

### Description

I request a video guide for the complete setup and how to use it in the other projects. All the video support are either old or don't help us understand things properly. Please help!!!! Also need to know if they work when built as Android app.

**Comment by homuler** [comment]
Have you read [theGetting Started page](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started)?

**Comment by TE-Devharajan-Rangarajan** [comment]
Yes @homuler The part of integrating just the handtracking has been so hard. Kindly help.

**Comment by homuler** [comment]
Sorry, I don't seem to be broad-minded enough to help you _kindly_.
Sometimes people come to OSS communities who mistakenly think they are customers, but I am not professionally trained to deal well with such people.

For those who are interested in this issue:
I will never prepare a video guide, but I'm writing [a tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial) these days.
It's not finished yet, but I'm going to complete it as soon as I regain my motivation, so please wait until then.
Thank you for your patience and support.
