### ISSUE TITLE
How to set MIN_TRACKING_CONFIDENCE to increase the quality of body tracking in holisticLandmarkCpu?

### ISSUE THREAD

**Issue by a591537394** [homuler/MediaPipeUnityPlugin#539]
### Plugin Version or Commit ID

v0.8.3

### Unity Version

2020.3.30f1

### Your Host OS

Windows10 Education

### Target Platform

UnityEditor, Windows Standalone

### Description

I had tryed this way, but when i run it ,editor will collapse directly.
![image](https://user-images.githubusercontent.com/45918609/164182408-95c2cede-bd65-41c7-9d50-eb1cae3ff85d.png)

how can i increase 'MIN_TRACKING_CONFIDENCE ' just like the python example below?
![image](https://user-images.githubusercontent.com/45918609/164184349-5c0cc3b8-a6f9-43e2-bffa-af1cd3e1a65a.png)

**Comment by homuler** [comment]
Please pull the latest version.
You can set these parameters from the UI.
![min-confidence-config](https://user-images.githubusercontent.com/4690128/164197627-a1534132-60a7-49c8-9b37-4a986b0d78eb.png)

**Comment by a591537394** [comment]
oh , nice job
