### ISSUE TITLE
When will Instant Motion Tracking be ready?

### ISSUE THREAD

**Issue by Vladislav489** [homuler/MediaPipeUnityPlugin#54]
Hi, following the thread on Instant Motion Tracking, you wrote that you will finish in about 2 weeks, how much work is left?

**Comment by homuler** [comment]
There's nothing I can say with certainty yet.

duplicates #41

**Comment by Vladislav489** [comment]
> There's nothing I can say with certainty yet.
> 
> duplicates #41

can there be approximate dates?
