### ISSUE TITLE
VideoSource::Play() is called before Start()

### ISSUE THREAD

**Issue by wonwoolee** [homuler/MediaPipeUnityPlugin#541]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2020.3.32f1

### Your Host OS

Ubuntu 20.04

### Target Platform

UnityEditor

### Build Command

python build.py build --desktop gpu --opencv cmake 

### Bug Description

VideoSource::Play() is called before VideoSource::Start() so that `InvalidOperationException: Video is not selected` is raised.

### Steps to Reproduce the Bug

1. Open Pose Tracking Scene
2. Set a video clip to Video Source attached Solution game object
3. Set Default image source to Video in bootstrap attached to Solution game object
4. Start Pose Tracking from Pose Tracking scene (not starting the Start scene)

### Log

VideoSource::Play()
UnityEngine.Debug:Log (object)
Mediapipe.Unity.VideoSource/<Play>d__18:MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/VideoSource.cs:66)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
Mediapipe.Unity.ImageSourceSolution`1<Mediapipe.Unity.PoseTracking.PoseTrackingGraph>:Play () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs:35)
Mediapipe.Unity.Solution/<Start>d__4:MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/Solution.cs:27)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

InvalidOperationException: Video is not selected
Mediapipe.Unity.VideoSource+<Play>d__18.MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/VideoSource.cs:79)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.ImageSourceSolution`1:Play() (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs:35)
Mediapipe.Unity.<Start>d__4:MoveNext() (at Assets/MediaPipeUnity/Samples/Common/Scripts/Solution.cs:27)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

VideoSource::Start()
UnityEngine.Debug:Log (object)
Mediapipe.Unity.VideoSource:Start () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/VideoSource.cs:43)

**Comment by homuler** [comment]
Thank you for reporting the issue!
