### ISSUE TITLE
System.MissingMethodException: Constructor on type 'Mediapipe.NormalizedLandmarkListPacket' not found.

### ISSUE THREAD

**Issue by MoneyWonders** [homuler/MediaPipeUnityPlugin#542]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2020.3.33f1 & 2021.2.11f1

### Your Host OS

Windows 10 Professional 21H2 & macOS Monterey 12.3

### Target Platform

Android, iOS

### Target Device

Samsung Galaxy A70 & Apple iPhone 12 Pro

### [Android Only] Android Build Tools and NDK Version

NDK: r19 which is installed with Unity

### [iOS Only] XCode Version

XCode 13.3.1

### Build Command

Android: python build.py build --android arm64 --linkopt=-s -vv
iOS: python build.py build --ios arm64 -vv
Windows & macOS: python build.py build --desktop cpu --opencv cmake -vv

### Bug Description

We rewrite a PoseTrackingSolution of sample to merge Bootstrap and bind graphRunner.OnPoseLandmarksOutput only (without other callbacks and annotations).  It works fine on Unity Editor (Windows & macOS) and mobile device (Android & iOS) in all running modes but Async.  MediaPipe will crash on Android & iOS in Async mode and Unity Editor, Sync & Non Blocking Sync mode is OK.
We found it fails in InvokeIfOutputStreamFound() of OutputStream.cs in line 373:
outputStream.referencePacket.SwitchNativePtr(packetPtr);
System can't found constructor of Mediapipe.NormalizedLandmarkListPacket in referencePacket get.

### Steps to Reproduce the Bug

Here is our code:
public class PoseTracking : MonoBehaviour
{
    [SerializeField] private PoseTrackingGraph _graphRunner;
    [SerializeField] private WebCamSource _webcamSource;
    [SerializeField] private RunningMode _runningMode = RunningMode.Async;
    [SerializeField] private Camera _camera;
    [SerializeField] private RawImage _background;

#if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
    private InferenceMode inferenceMode = InferenceMode.GPU;
#else
    private InferenceMode inferenceMode = InferenceMode.CPU;
#endif

    private TextureFrame _textureFrame = null;
    private bool _textureFrameReady = true;

    private Vector3[] _viewOutputs = new Vector3[33];
    private Vector3[] _worldOutputs = new Vector3[33];
    private bool _updateData = false;

    void LateUpdate()
    {
        if (_updateData)
        {
            for (int i = 0; i < _viewOutputs.Length; i++)
                _worldOutputs[i] = _camera.ViewportToWorldPoint(_viewOutputs[i]);

            _updateData = false;
        }
    }

    IEnumerator Start()
    {
        AssetLoader.Provide(new StreamingAssetsResourceManager());

        if (inferenceMode == InferenceMode.GPU)
            yield return GpuManager.Initialize();

        var graphInitRequest = _graphRunner.WaitForInit(_runningMode);

        yield return _webcamSource.Play();
        _background.texture = (WebCamTexture)_webcamSource.GetCurrentTexture();

        yield return graphInitRequest;

        if (!_runningMode.IsSynchronous())
            _graphRunner.OnPoseLandmarksOutput += OnPoseLandmarksOutputAsync;

        _graphRunner.StartRun(_webcamSource);

        _textureFrame = new TextureFrame(_webcamSource.textureWidth, _webcamSource.textureHeight);
        _textureFrame.OnRelease.AddListener(OnTextureFrameRelease);

        while (true)
        {
            while (!_textureFrameReady) yield return null;

            _textureFrame.ReadTextureFromOnCPU((WebCamTexture)_webcamSource.GetCurrentTexture());
            _textureFrameReady = false;
            _graphRunner.AddTextureFrameToInputStream(_textureFrame);

            yield return new WaitForEndOfFrame();

            if (_runningMode.IsSynchronous())
                yield return WaitForNextValue();
        }
    }

    private IEnumerator WaitForNextValue()
    {
        Detection poseDetection = null;
        NormalizedLandmarkList poseLandmarks = null;
        LandmarkList poseWorldLandmarks = null;
        ImageFrame segmentationMask = null;
        NormalizedRect roiFromLandmarks = null;

        if (_runningMode == RunningMode.Sync)
        {
            var _ = _graphRunner.TryGetNext(out poseDetection, out poseLandmarks, out poseWorldLandmarks, out segmentationMask, out roiFromLandmarks, true);
        }
        else if (_runningMode == RunningMode.NonBlockingSync)
        {
            yield return new WaitUntil(() => _graphRunner.TryGetNext(out poseDetection, out poseLandmarks, out poseWorldLandmarks, out segmentationMask, out roiFromLandmarks, false));
        }

        OnPoseLandmarksOutput(poseLandmarks);
    }

    private void OnPoseLandmarksOutput(NormalizedLandmarkList output)
    {
        if ((output == null) || (output.Landmark.Count < 1))
            return;

        for (int i = 0; i < output.Landmark.Count; i++)
        {
            _viewOutputs[i].x = output.Landmark[i].X;
            _viewOutputs[i].y = 1.0f - output.Landmark[i].Y;
            _viewOutputs[i].z = 1.0f - output.Landmark[i].Z;
        }

        if (_runningMode.IsSynchronous())
        {
            for (int i = 0; i < output.Landmark.Count; i++)
                _worldOutputs[i] = _camera.ViewportToWorldPoint(_viewOutputs[i]);
        }
        else
        {
            _updateData = true;
        }
    }

    private void OnPoseLandmarksOutputAsync(object stream, OutputEventArgs<NormalizedLandmarkList> eventArgs)
    {
        OnPoseLandmarksOutput(eventArgs.value);
    }

    private void OnTextureFrameRelease(TextureFrame textureFrame)
    {
        _textureFrameReady = true;
    }
}

### Log
```
System.MissingMethodException: Constructor on type 'Mediapipe.NormalizedLandmarkListPacket' not found.
  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Packet`1[TValue].Create[TPacket] (System.IntPtr packetPtr, System.Boolean isOwner) [0x00000] in <00000000000000000000000000000000>:0 
  at Mediapipe.Unity.OutputStream`2[TPacket,TValue].get_referencePacket () [0x00000] in <000000000000000000
```

**Comment by homuler** [comment]
How about preserving all the `MediaPipeSDK.dll`?

```xml
<assembly fullname="MediaPipeSDK" preserve="all"/>
```

cf. https://docs.unity3d.com/Manual/ManagedCodeStripping.html#LinkXMLAnnotation

**Comment by MoneyWonders** [comment]
After put a "link.xml" file in Assets directory, this issue is gone !
<linker>
  <assembly fullname="MediaPipeSDK" preserve="all"/>
</linker>

But the Async mode become very lag, and the response time is over 3 seconds ...
Maybe add [Preserve] attribute into code is better way, we will try it later.
Thanks a lot :)

**Comment by MoneyWonders** [comment]
We found three ways to solve this problem:
1. Put "link.xml" in Assets directory.
\<linker>
\<assembly fullname="MediaPipeSDK">
\<type fullname="Mediapipe.NormalizedLandmarkListPacket" preserve="all"/>
\</assembly>
\</linker>
2. Add [Preserve] attribute in "NormalizedLandmarkListPacket.cs"
using UnityEngine.Scripting;
namespace Mediapipe
{
  public class NormalizedLandmarkListPacket : Packet<NormalizedLandmarkList>
  {
    public NormalizedLandmarkListPacket() : base(true) { }
    [Preserve]
    public NormalizedLandmarkListPacket(IntPtr ptr, bool isOwner = true) : base(ptr, isOwner) { }
    ....
  }
}
3. Use Unity 2021 and set "Managed Stripping Level" to "Minimal" in Project Settings -> Other Settings

Way 2 is our final choice and make this issue transparently to user.
