### ISSUE TITLE
Mediapipe initialization fails after changing between scenes 

### ISSUE THREAD

**Issue by wonwoolee** [homuler/MediaPipeUnityPlugin#547]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2020.3.32f1

### Your Host OS

Ubuntu 20.04

### Target Platform

Android

### Build Command

python build.py build. --desktop gpu --android arm64 --opencv cmake -v 

### Bug Description

Let's say we have two scenes, `SceneA` and `SceneB`. 
`SceneB` has everything for Mediapipe unity plugins, like bootstrap,  pose tracking graph, pose tracking solution, etc. 
In my unity project, `SceneA` select a video clip and pass it to `SceneB` to run pose estimation on the video. 

When I change scenes multiple times, Mediapipe unity plugin fails to initialize correctly. It only works the first time I use it. 
For example, I change scenes in the order of  `SceneA` - `SceneB` (1st time) - `SceneA` - `SceneB` (2nd time). 
Mediapipe fails in the 2nd initialization. 

FYI, when changing scenes from the `SceneB`, to save resources, I stop the graph, shutdown GPU resources. Then, Mediapipe pipeline is re-initialized from scratch, when `SceneB` is loaded. 

### Steps to Reproduce the Bug

Please see the description 

### Log

```
05-03 17:07:17.815 19162 19187 I Unity   : MovieManager:OnDestroy()
05-03 17:07:17.815 19162 19187 I Unity   :
05-03 17:07:17.817 19162 19187 I Unity   : PoseTracker: PoseTracker::Init() Started
05-03 17:07:17.817 19162 19187 I Unity   : <Start>d__22:MoveNext()
05-03 17:07:17.817 19162 19187 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
05-03 17:07:17.817 19162 19187 I Unity   :
05-03 17:07:17.819 19162 19187 W Unity   : PoseTracker: Warning AssetLoader is already initialized
05-03 17:07:17.819 19162 19187 W Unity   : <Start>d__22:MoveNext()
05-03 17:07:17.819 19162 19187 W Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
05-03 17:07:17.819 19162 19187 W Unity   :
05-03 17:07:17.819 19162 19187 I Unity   : PoseTracker: Initializing GPU resources...
05-03 17:07:17.819 19162 19187 I Unity   : <Start>d__22:MoveNext()
05-03 17:07:17.819 19162 19187 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
05-03 17:07:17.819 19162 19187 I Unity   :
05-03 17:07:17.830 19162 19187 I Unity   : PoseTracker: Initializing PoseTrackingGraph...
05-03 17:07:17.830 19162 19187 I Unity   : <Start>d__22:MoveNext()
05-03 17:07:17.830 19162 19187 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
05-03 17:07:17.830 19162 19187 I Unity   :
05-03 17:07:17.844 19162 19187 E Unity   : PoseTracker: Mediapipe.MediaPipeException: FAILED_PRECONDITION: System.NullReferenceException: Object reference not set to an instance of an object.
05-03 17:07:17.844 19162 19187 E Unity   :   at Mediapipe.CalculatorGraph.SetGpuResources (Mediapipe.GpuResources gpuResources) [0x00000] in <00000000000000000000000000000000>:0
05-03 17:07:17.844 19162 19187 E Unity   :   at Mediapipe.Unity.GraphRunner.InitializeCalculatorGraph () [0x00000] in <00000000000000000000000000000000>:0
05-03 17:07:17.844 19162 19187 E Unity   :   at Mediapipe.Unity.GraphRunner+<Initialize>d__39.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
05-03 17:07:17.844 19162 19187 E Unity   :   at Mediapipe.Unity.WaitForResult+<Run>d__20.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
05-03 17:07:17.844 19162 19187 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
05-03 17:07:17.844 19162 19187 E Unity   :   at Mediapipe.Unity.WaitForResult..ctor (UnityEngine.MonoBehaviour runner, System.Collections.IEnumerator inner, System.Int64 timeoutMillisec) [0x00000] in <00000000000000000000000000000000>:0
05-03 17:07:17.844 19162 19187 E Unity   :   at Mediapipe.Unity.GraphRunne
```

**Comment by homuler** [comment]
When you need help, please use [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).
I think this is not the plugin's bug but your bug, so I can't say anything without seeing your code.

> PoseTracker: Mediapipe.MediaPipeException: FAILED_PRECONDITION: System.NullReferenceException: Object reference not set to an instance of an object.

You should check why `System.NullReferenceException` is thrown first.
Did you confirm that `MediaPipe.GpuResources` is not null?

> I stop the graph, shutdown GPU resources.

I think you don't need to shut down GPU resources, but if you did, you need to initialize them again.

**Comment by UnityDev1021** [comment]
@wonwoolee  I don't remember properly but a kind of same error occurred on my side also, could you check if you have turned "IsInitialized" to false?

 As when you call the GpuManager.Shutdown() from Bootstrap, the "IsInitialized" variable is not changed and thus the error occurs as far as I get it, I might be wrong.
[https://github.com/homuler/MediaPipeUnityPlugin/blob/77ba1a4d2249b8db09b3a1e975a01f6e50d21e33/Assets/MediaPipeUnity/Samples/Common/Scripts/GpuManager.cs#L38-L42](url)

Setting "IsInitialized" to false under GpuManager.Shutdown() works for me.
[https://github.com/homuler/MediaPipeUnityPlugin/blob/77ba1a4d2249b8db09b3a1e975a01f6e50d21e33/Assets/MediaPipeUnity/Samples/Common/Scripts/GpuManager.cs#L105-L118](url)

**Comment by wonwoolee** [comment]
@homuler
Hi, it turns out that the issue was about `GpuManager.Shutdown()`. I fixed my problem by not calling `GpuManager.Shutdown()`. 

@UnityDev1021 
I'm sorry I didn't try your fix yet. I made my own walkaround.
