### ISSUE TITLE
BUILD FAILED when I finally build my unity project

### ISSUE THREAD

**Issue by dimplehh** [homuler/MediaPipeUnityPlugin#548]
### Plugin Version or Commit ID

0.9.1

### Unity Version

2020.3.30f1

### Your Host OS

window 10

### Target Platform

Windows Standalone

### Command Sequences

I tried to build my unity project that I had installed mediapipe unity plugin.
When I entered 'Build settings' and selected platforms such as universal windows platforms, The errors occur consistently.
I want to know how I build my unity project so I hope you to help me please.

### Log

Win32Exception: ApplicationName='D:\unity\2020.3.30f1\Editor\Data\il2cpp\build/deploy/netcoreapp3.1/UnityLinker.exe', CommandLine='@D:/navatar/navatar_mediapipe/MediaPipeUnityPlugin/Temp/StagingArea/Data/Managed/response.rsp', CurrentDirectory='D:\navatar\navatar_mediapipe\MediaPipeUnityPlugin\Temp\StagingArea\Data\Managed', Native error= 지정된 파일을 찾을 수 없습니다.

System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <0463b2ef957545c0a51b42f372cd4fbb>:0)
System.Diagnostics.Process.Start () (at <0463b2ef957545c0a51b42f372cd4fbb>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
UnityEditor.Utils.Program.Start (System.EventHandler exitCallback) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditor.Utils.Program.Start () (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.AssemblyStripper.RunAssemblyLinker (System.Collections.Generic.IEnumerable`1[T] args, System.String& out, System.String& err, System.String linkerPath, System.String workingDirectory) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.AssemblyStripper.StripAssembliesTo (System.String outputFolder, System.String& output, System.String& error, System.Collections.Generic.IEnumerable`1[T] linkXmlFiles, UnityEditorInternal.UnityLinkerRunInformation runInformation) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.AssemblyStripper.RunAssemblyStripper (UnityEditorInternal.UnityLinkerRunInformation runInformation) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.AssemblyStripper.StripAssemblies (System.String managedAssemblyFolderPath, UnityEditorInternal.BaseUnityLinkerPlatformProvider unityLinkerPlatformProvider, UnityEditorInternal.IIl2CppPlatformProvider il2cppPlatformProvider, UnityEditor.RuntimeClassRegistry rcr, UnityEditor.ManagedStrippingLevel managedStrippingLevel) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <68089899e4c84456bfc1de3436accf4a>:0)
PostProcessWinRT.RunIL2CPPForProjectBuild () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1910)
PostProcessWinRT.RunIL2CPP () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1879)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEditor.UWP.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:86)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.UWP.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:90)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions)
<>c:<.cctor>b__0_0(BuildPlayerOptions) (at Assets/Mediapipe/Editor/BuildProcessor.cs:9)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

--------------------------------------------------------------------------------------------------------------------------------------------

Build completed with a result of 'Failed' in 27 seconds (27165 ms)
UnityEditor.BuildPlayerWindow/DefaultBuildMethods:BuildPlayer (UnityEditor.BuildPlayerOptions)
UnityEditorStartup/<>c:<.cctor>b__0_0 (UnityEditor.BuildPlayerOptions) (at Assets/Mediapipe/Editor/BuildProcessor.cs:9)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

--------------------------------------------------------------------------------------------------------------------------------------------

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ca] in <68089899e4c84456bfc1de3436accf4a>:0 
  at UnityEditorStartup+<>c.<.cctor>b__0_0 (UnityEditor.BuildPlayerOptions buildPlayerOptions) [0x00005] in D:\navatar\navatar_mediapipe\MediaPipeUnityPlugin\Assets\Mediapipe\Editor\BuildProcessor.cs:9 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00072] in <68089899e4c84456bfc1de3436accf4a>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by homuler** [comment]
The Universal Windows Platform is not supported, so I'm not sure you can build & run it, but at least I could build it so I think this error is caused by your local environment (can you confirm you can build another app for Universal Windows Platform?).
Please try `PC Standalone` and let me know if it still fails.
