### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by khaledwesif** [homuler/MediaPipeUnityPlugin#549]
### Plugin Version or Commit ID

.

### Unity Version

2020.3.12f1

### Your Host OS

OS Platform and Distribution (e.g., Linux Ubuntu , WSL2): windows 10

### Target Platform

Linux Standalone

### Command Sequences

 python3.9 build.py build --desktop cpu -v

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /home/sheetos/MediaPipeUnityPlugin-master/WORKSPACE:35:23: in <toplevel>
  /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fd225c89de0e7400a9a570feaf631a19dd1f1e57cb7b2f9308be4657a2fdf00c"
DEBUG: Repository rules_cc instantiated at:
  /home/sheetos/MediaPipeUnityPlugin-master/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (66 packages loaded, 889 targets configured).
INFO: Found 1 target...
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-bin -> /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/execroot/mediapipe_api/bazel-out/k8-opt/bin:  /home/sheetos/MediaPipeUnityPlugin-master/bazel-bin (File exists)
  cannot create symbolic link bazel-testlogs -> /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/execroot/mediapipe_api/bazel-out/k8-opt/testlogs:  /home/sheetos/MediaPipeUnityPlugin-master/bazel-testlogs (File exists)
  cannot create symbolic link bazel-out -> /home/sheetos/.cache/bazel/_bazel_sheetos/346c51f94ea567525607434341c35b37/execroot/mediapipe_api/bazel-out:  /home/sheetos/MediaPipeUnityPlugin-master/bazel-out (File exists)
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-MediaPipeUnityPlugin-master/bazel-out/k8-opt/bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 1042.919s, Critical Path: 312.26s
INFO: 203 processes: 7 internal, 196 processwrapper-sandbox.
INFO: Build completed successfully, 203 total actions
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Scripts/Protobuf'...
Traceback (most recent call last):
  File "/home/sheetos/MediaPipeUnityPlugin-master/build.py", line 392, in <module>
    Argument().command().run()
  File "/home/sheetos/MediaPipeUnityPlugin-master/build.py", line 110, in run
    self._unzip(
  File "/home/sheetos/MediaPipeUnityPlugin-master/build.py", line 88, in _unzip
    shutil.unpack_archive(source, dest)
  File "/usr/lib/python3.9/shutil.py", line 1256, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/lib/python3.9/shutil.py", line 1151, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip is not a zip file

**Comment by homuler** [comment]
Please give me the correct information.

> ### Your Host OS
> OS Platform and Distribution (e.g., Linux Ubuntu , WSL2): windows 10

The logs are obviously different from those output on Windows 10.

> WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':

Maybe somehow you've created directories named `bazel-*`.
If so, run `rm -rf bazel-*` and try again.
