### ISSUE TITLE
Windows executable not starting inference

### ISSUE THREAD

**Issue by Neleac** [homuler/MediaPipeUnityPlugin#551]
### Description

Everything works perfectly in editor. However, when I build and run the executable, it gets stuck in the initial black screen.
In editor, when I run Start Scene, Bootstrap.cs prints many lines on the black screen, then changes to next scene.
In the executable, these lines are never printed, so my guess is that Boostrap is not loading, thus preventing inference.
Are there additional steps that I need to perform to build the final executable? 

I'm using Windows 10, Unity 2021.2.14f1, and plugin SHA 3698b6145e756c0abc5b0a8f1032591c57525b6f

**Comment by Neleac** [comment]
Solved: make sure this box is checked

![image](https://user-images.githubusercontent.com/31634644/167063916-1f8a6e52-3225-48bf-ba42-47fa3bf6186d.png)

**Comment by homuler** [comment]
Please use [the build/install issue form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build-install-issue.yml).

> Are there additional steps that I need to perform to build the final executable?

Well, you've not described what you've done, so I can't answer this question.
Most likely, you have linked `mediapipe_c.dll` to your local OpenCV and have not copied `opencv_world3416.dll` (with `--include_opencv_libs`) or set the path to it.
If so, I recommend you upgrade the plugin version and build it again.
Most of those path problems will be resolved automatically.

See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception.

**Comment by homuler** [comment]
@Neleac https://github.com/homuler/MediaPipeUnityPlugin/issues/551#issuecomment-1119236292
This step is unnecessary in the versions >= v0.8.4.
