### ISSUE TITLE
How does Android use this MediaPipeUnityPlugin

### ISSUE THREAD

**Issue by 9276** [homuler/MediaPipeUnityPlugin#554]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

20220506

### Your Host OS

windows10

### Target Platform

Android

### Command Sequences

1

### Log

1

**Comment by 9276** [comment]
why invalid

**Comment by homuler** [comment]
@9276 Well, I have no idea what you're asking me.
The reason why it is invalid is that only `1` is entered in the required fields.
