### ISSUE TITLE
Unable to Build for Android using Docker Linux on Window 10 pro

### ISSUE THREAD

**Issue by hadysysdev** [homuler/MediaPipeUnityPlugin#555]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2020.33f

### Your Host OS

Docker Linux Windows 10 WSL2

### Target Platform

Android

### Command Sequences

- docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile
- docker run --cpus=12 --memory=16g --mount type=bind,src="$(pwd)"/Packages,dst=/home/mediapipe/Packages --mount type=bind,src="$(pwd)"/Assets,dst=/home/mediapipe/Assets -it mediapipe_unity:linux
-  python build.py build --android arm64 -vv

### Log

mediapipe@d373dc0df5aa:~$ python build.py build --android arm64 -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
2022/05/10 06:27:37 Downloading https://releases.bazel.build/5.0.0/release/bazel-5.0.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found    
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/fc70a32ecd248dd7612d75d2177125ed14541367.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/a87782c34d667d1c1a18fe82a9a7abfc72fd345b.tar.gz failed: class java.io.FileNotFoundException GET returned 
404 Not Found
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "114cfbf3e3d281ef2d12c3870810b729c66cf7e8f070c66ff016afecd5ccc54d"
DEBUG: Repository rules_cc instantiated at:
  /home/mediapipe/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (100 packages loaded, 1232 targets configured).
INFO: Found 1 target...
ERROR: /home/mediapipe/mediapipe_api/calculators/image/BUILD:125:17: Executing genrule //mediapipe_api/calculators/image:opencv_encoded_image_to_image_frame_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/197/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \    
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/image/opencv_encoded_image_to_image_frame_calculator.proto
mv bazel-out/k8-opt/bin/OpencvEncodedImageToImageFrameCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/image/OpencvEncodedImageToImageFrameCalculator.cs)
')
# Configuration: 8996d1cb5d6a56c632bde29478229ea396aab83079d9472573b74ebbb8c7336b
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/tensor/BUILD:103:17: Executing genrule //mediapipe_api/calculators/tensor:tensors_to_segmentation_calculator_cs failed: (Exit 127): bash failed: error executing command 
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/186/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \    
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/tensor/tensors_to_segmentation_calculator.proto
mv bazel-out/k8-opt/bin/TensorsToSegmentationCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/tensor/TensorsToSegmentationCalculator.cs)
')
# Configuration: 8996d1cb5d6a56c632bde29478229ea396aab83079d9472573b74ebbb8c7336b
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/util/BUILD:89:17: Executing genrule //mediapipe_api/calculators/util:latency_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/203/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \    
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/util/latency.proto
mv bazel-out/k8-opt/bin/Latency.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/util/Latency.cs)
')
# Configuration: 8996d1cb5d6a56c632bde29478229ea396aab83079d9472573b74ebbb8c7336b
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/core/BUILD:32:17: Executing genrule //mediapipe_api/calculators/core:concatenate_vector_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/200/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \    
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/core/concatenate_vector_calculator.proto
mv bazel-out/k8-opt/bin/ConcatenateVectorCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/core/ConcatenateVectorCalculator.cs)
')
# Configuration: 8996d1cb5d6a56c632bde29478229ea396aab83079d9472573b74ebbb8c7336b
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: $'\r': command not found
Target //mediapipe_api:mediapipe_proto_srcs failed to build
INFO: Elapsed time: 192.770s, Critical Path: 58.18s
INFO: 326 processes: 141 internal, 185 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 450, in <module>   
    Argument().command().run()
  File "/home/mediapipe/build.py", line 109, in run        
    self._run_command(self._build_proto_srcs_commands())   
  File "/home/mediapipe/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#binbash-line-1-r-command-not-found.

**Comment by maaz9898** [comment]
@hadysysdev I am facing the same issue, could you please elaborate the fix?
Not being able to resolve it

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/172#issuecomment-843014178
