### ISSUE TITLE
Could this be used with Unity ARFoundation

### ISSUE THREAD

**Issue by hadysysdev** [homuler/MediaPipeUnityPlugin#557]
### Description

I am currently working on a school project involving AR, and am very new to Unity and game engine as a whole. Part of my project involves user interaction improvement. I wanted to create a mobile AR Game in which the player can interact using their hands. 

I tested The Mobile AR library called Manomtion but was unsuccessful in getting it to work. I am trying to test this project and would like to know if I could combine it with ARFoundation? if so could you please point me to some documents I can reference?

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/530#issuecomment-1100505221.
I'm writing [a tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial) (not finished yet) and it will be helpful, too.

But note that this will not be an easy path if you are not familiar with ARFoundation, since the project does not expose such an API that directly receives `XRImage` as the input.

**Comment by hadysysdev** [comment]
> See [#530 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/530#issuecomment-1100505221). I'm writing [a tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial) (not finished yet) and it will be helpful, too.
> 
> But note that this will not be an easy path if you are not familiar with ARFoundation, since the project does not expose such an API that directly receives `XRImage` as the input.

Thank you for taking the time to respond.  Though I have another quick question, Are the sample scene compatible with mobiles? I build the hand detection scene on an android after building the android lib. The app opens fine on the phone but cant seems to detect hands.

**Comment by homuler** [comment]
> Are the sample scene compatible with mobiles?

Yes. See [the matrix](https://github.com/homuler/MediaPipeUnityPlugin#example-solutions) for more details.

> The app opens fine on the phone but cant seems to detect hands.

If trouble occurs, it is a good idea to first check for error logs.

**Comment by homuler** [comment]
If there're no errors, it may be that the latency is too high and the result is not rendered on the screen.
In that case, try the sync mode or set a longer timeout value (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-932074718).
