### ISSUE TITLE
iOS app crashes due to low memory

### ISSUE THREAD

**Issue by UnityDev1021** [homuler/MediaPipeUnityPlugin#558]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2021.3.1f1

### Your Host OS

macOS Monterey 12.3.1

### Target Platform

iOS

### Description

Everything works fine when I run the PoseTrackingSolution alone but I am trying to combine both **Pose Tracking** and **Object Tracking** in a single Scene. I have successfully run both of these in the same scene, but my problem is that when I use a **GateCalculator** to check if the Object Detection should work or not, the memory suddenly starts to increase and never goes back down:-
![Screenshot 2022-05-11 at 2 32 16 PM](https://user-images.githubusercontent.com/92006984/167814262-56e8ebbf-751a-47a9-97f5-4a847474f577.png)

Now I have tried to remove the Object Detection code **(edit : GateCalculator only, as the rest of Object Detection code works fine)** from the pose_tracking_gpu graph and it works flawlessly again but whenever I add it back, the memory just increases.

So I tried to remove the code one at a time to check what is wrong and found out that just by having the gate calculator, the memory sky-rockets and without it, it works properly:-
![Screenshot 2022-05-11 at 2 50 50 PM](https://user-images.githubusercontent.com/92006984/167816368-ed00746d-bef2-4397-9068-f55bb260c657.png)

Is there any workaround to this? I have added all of the necessary code to the PoseTrackingSolution and PoseTrackingGraph, no worries in that. It would be very helpful if I can find why the memory keeps increasing when I add the GateCalculator in the pose_tracking_gpu graph.

**Comment by ROBYER1** [comment]
Which pose graph are you using, heavy, normal or light?

**Comment by homuler** [comment]
> Is there any workaround to this?

Perhaps you are just using `GateCalculator` incorrectly (e.g. the `output_stream` is not used and the result is piled up in a queue), but please ask questions about how to use Calculator in the MediaPipe repository, not here.

**Comment by UnityDev1021** [comment]
@ROBYER1 I am using the full version.
![Screenshot 2022-05-12 at 2 53 37 PM](https://user-images.githubusercontent.com/92006984/168038241-713b5cf5-e517-427b-9d94-0ee3a6617389.png)


@homuler Yeah, sorry if I did not word it correctly. I have used the `GateCalculator` in my previous project for android which I am porting to Unity. You can check the code of the graph in the below screenshot:-
![Screenshot 2022-05-12 at 2 47 42 PM](https://user-images.githubusercontent.com/92006984/168036979-cb56fc16-c92a-48c7-a338-477f7eb07640.png)
 
The `GateCalculator `works perfectly for android but with Unity, it causes a crash on `iOS`. Again it might be that I am doing something wrong but when I remove the `GateCalculator`, it works perfectly with `Object Detection`.

**Comment by homuler** [comment]
Well...if you really need help, share _all the parts_ needed to understand the issue in _text_ format.

I'm not sure without seeing your whole code, but is it possible that you are only flowing the first packet to `enable_object_detection`? (you need to call `AddInputStream` in every frame)
If so, I think you should use `input_stream_packet` instead of `input_stream`.

Anyway, again, please ask questions about how to use Calculator in the MediaPipe repository, not here.

**Comment by UnityDev1021** [comment]
@homuler Exactly that. I am passing a `BoolPacket` to allow or disallow the below `ObjectDetection` nodes, but I am not calling it every frame. I am only calling it once, do I need to call it every frame? Is it necessary? I am doing this.
![Screenshot 2022-05-12 at 4 43 00 PM](https://user-images.githubusercontent.com/92006984/168062553-0fd98ded-9065-47b0-a187-91d797781102.png)

This is the code I am using to pass the BoolPacket to the `enable_object_detection` stream.
![Screenshot 2022-05-12 at 4 42 14 PM](https://user-images.githubusercontent.com/92006984/168063017-137fd8f9-5cc0-4265-8d33-1e544b7329c6.png)

I did not want to use a `side packet` as I don't understand them well, but might try it out in the future. Will update on the side packet code for solution.

Thanks Anyway. You can close this thread now. Will get back if I get a solution out of this.

**Comment by homuler** [comment]
> I am only calling it once, do I need to call it every frame? Is it necessary?

I think yes.
See https://google.github.io/mediapipe/framework_concepts/synchronization.html#input-policies for more details.

(I have changed some of the text to bold)
> To explain how it works, we need to introduce the definition of a settled timestamp. We say that a timestamp in a stream is _settled_ if it lower than the timestamp bound. In other words, a timestamp is settled for a stream once the state of the input at that timestamp is irrevocably known: either there is a packet, or there is the **certainty** that a packet with that timestamp will not arrive.
>
> ...
>
> One consequence of this deterministic behavior is that, for nodes with multiple input streams, there can be a theoretically unbounded wait for a timestamp to be settled, and **an unbounded number of packets can be buffered in the meantime**. (Consider a node with two input streams, one of which keeps sending packets while the other sends nothing and does not advance the bound.)

> I did not want to use a `side packet` as I don't understand them well, but might try it out in the future.

Unlike `Packet` to the `input_stream`, `SidePacket` only needs to be set once when calling `CalculatorGraph#StartRun`, maybe because it does not have its timestamp.

See https://google.github.io/mediapipe/framework_concepts/framework_concepts.html#side-packets for more details.
> A side packet connection between nodes carries a single packet (with unspecified timestamp). It can be used to provide some data that will remain constant, whereas a stream represents a flow of data that changes over time.

Once you understand `SidePacket` but if you don't know how to use `SidePacket` _in C#_, then you can ask it here.

P.S.
> share all the parts needed to understand the issue in text format.

Please share your code in _text_ format next time.
If I wanted to reproduce it on my local machine, I would have to type all the codes, right?
