### ISSUE TITLE
Mac make cpu error: ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by stevensroczynski** [homuler/MediaPipeUnityPlugin#56]
Just came across this project yesterday. Super excited it exists, but having a hard time getting it to build. I'm suspect this issue originates from the 404 bazel seems to be throwing when it tries to download whatever that hash represents. I posted the entire stack trace below.

`cd C && bazel  build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe_api:mediapipe_desktop mediapipe_api:mediapipe_models mediapipe_api:mediapipe_proto_srcs
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "83a471cef94e4c2301de6e6a1d6289f84f325b17f3dce3b6be8139d874358d6d"
DEBUG: Repository rules_foreign_cc instantiated at:
  /Users/ssrocz698/workspaces/personal-stuff/MediaPipeUnityPlugin/C/WORKSPACE:79:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository local_execution_config_python instantiated at:
  /Users/ssrocz698/workspaces/personal-stuff/MediaPipeUnityPlugin/C/WORKSPACE:428:13: in <toplevel>
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/tensorflow/workspace.bzl:74:20: in tf_workspace
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/tensorflow/workspace.bzl:90:27: in tf_repositories
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
	File "/private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
		return execute(
	File "/private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
	File "/private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
		return execute(
	File "/private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "4fc66738a55efcc6e2195da98ea8c7f4f1d9ad42a084cadd0724c59f5c8930c0"
DEBUG: Repository rules_cc instantiated at:
  /Users/ssrocz698/workspaces/personal-stuff/MediaPipeUnityPlugin/C/WORKSPACE:73:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  /Users/ssrocz698/workspaces/personal-stuff/MediaPipeUnityPlugin/C/WORKSPACE:30:23: in <toplevel>
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 0.606s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (3 packages)
    Fetching @local_config_cc_toolchains; fetching
    Fetching @com_google_protobuf; fetching
    Fetching ...otobuf; Extracting /private/var/tmp/_bazel_ssrocz698/88d07cf205c496cd0ccf14975b81f846\
/external/com_google_protobuf/temp1817026531808061512/v3.11.4.tar.gz
make: *** [cpu] Error 1`

**Comment by homuler** [comment]
Yoy may not have installed numpy.
https://google.github.io/mediapipe/getting_started/troubleshooting.html#missing-necessary-python-packages

I'll update README later.

**Comment by stevensroczynski** [comment]
Interestingly, I did have numpy installed, but reinstalling it with pip fixed the issue. Thanks.
