### ISSUE TITLE
How to access landmark in code?

### ISSUE THREAD

**Issue by Auti-Nic** [homuler/MediaPipeUnityPlugin#560]
### Description

I was reading through the whole Pose Track module but still cannot figure out how to get landmark of body in code. Can someone help me plz?

**Comment by philiprkk** [comment]
In PoseTrackingSolution at line 60 you could write something like this to get pose landmarks out (in sync mode at least)

`      if (runningMode == RunningMode.Sync)
      {
        NormalizedLandmarkList poseLandmarks;
        var _ = graphRunner.TryGetNext(out var _, out poseLandmarks, out var _, out var _, true);

        Vector2 noseLandmark = new Vector2(poseLandmarks.Landmark[0].X, poseLandmarks.Landmark[0].Y);
      }`
