### ISSUE TITLE
Documentation: how to build

### ISSUE THREAD

**Issue by aosyatnik** [homuler/MediaPipeUnityPlugin#566]
### Description

Hey, I'm trying to build on Windows in Linux Container described here: https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container

I'm not sure how should I run `build.py` as it's not presented neither in container nor in repo (master branch). How to complete step 5?
```
python build.py build --android arm64 -vv
```
This is how container looks like:
![image](https://user-images.githubusercontent.com/8158404/168427922-6094d996-fdb2-468b-aa9b-db3356481977.png)

**Comment by aosyatnik** [comment]
ok, I got it. I needed to download 0.9.1 version, not master branch. Closing.

**Comment by homuler** [comment]
I think you were using [google/mediapipe](https://github.com/google/mediapipe), not this repository, and that's why the master branch did not work.
