### ISSUE TITLE
DllNotFoundException: mediapipe_c assembly Mediapipe.Protobuf

### ISSUE THREAD

**Issue by aosyatnik** [homuler/MediaPipeUnityPlugin#567]
### Description

Hi, team.
Thank you very much for your hard work!
I'm very new in Unity development, so please don't judge me too much. I would love to test sample scene on my phone (Galaxy s22), if it's even possible. I have built v0.9.1 in Docker Linux and it looks ok?:
![image](https://user-images.githubusercontent.com/8158404/168443039-53727930-db60-48cd-8eba-7a7f20b3eef7.png)

I used `arm64`.

I mean I didn't get any error, during build, so I assume this is ok.

The next error I get, when I try to run "Start scene":
```
DllNotFoundException: mediapipe_c assembly:<unknown assembly> type:<unknown type> member:(null)
Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/Protobuf.cs:16)
Mediapipe.Unity.Bootstrap+<Init>d__16.MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs:44)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <40205bb2cb25478a9cb0f5e54cf11441>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.Bootstrap:OnEnable() (at Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs:36)
```
```
MissingReferenceException: The variable _availableSources of VideoSource doesn't exist anymore.
You probably need to reassign the _availableSources variable of the 'VideoSource' script in the inspector.
Mediapipe.Unity.VideoSource.set_video (UnityEngine.Video.VideoClip value) (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/VideoSource.cs:26)
Mediapipe.Unity.VideoSource.Start () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/VideoSource.cs:45)
```
![image](https://user-images.githubusercontent.com/8158404/168443083-a9fd1a5c-4e49-4d80-a8fa-e6a723651c9d.png)

Maybe something wrong with my configs?
![image](https://user-images.githubusercontent.com/8158404/168443094-53b73156-eb88-4001-ac1a-0a1390cf3e2e.png)

**Comment by LGuilhermeRodrigues** [comment]
The error you getting is about your unity editor or your phone? If it's about the error the unity editor, you won't be able to run unless you build for you windows desktop too

**Comment by aosyatnik** [comment]
> The error you getting is about your unity editor or your phone? If it's about the error the unity editor, you won't be able to run unless you build for you windows desktop too

Thanks for reply. Does it mean, that I also need to follow these steps? https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10

**Comment by homuler** [comment]
If your Windows is not Pro, yes.
See https://github.com/homuler/MediaPipeUnityPlugin/issues/492#issuecomment-1072024773 for more details.
