### ISSUE TITLE
How to get rid of the green flashing on the screen?

### ISSUE THREAD

**Issue by jameseneir** [homuler/MediaPipeUnityPlugin#568]
### Description

When I played the pose tracking scene, it worked but the screen kept flashing green(except for the pose). Is it a common issues or it's just that I didn't build it right?

**Comment by zigzagoon1** [comment]
> ### Description
> When I played the pose tracking scene, it worked but the screen kept flashing green(except for the pose). Is it a common issues or it's just that I didn't build it right?

Did you solve this? Same is happening for me.
