### ISSUE TITLE
Windows 10 Pro Docker build - .bazelrc

### ISSUE THREAD

**Issue by StewieHF** [homuler/MediaPipeUnityPlugin#575]
### Plugin Version or Commit ID

v0.9.3

### Unity Version

2021.2.11f1

### Your Host OS

Windows 10 Pro

### Target Platform

Windows Standalone

### Command Sequences

docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile

### Log

I can get passed the MSYS2 issue when that hangs, but then once it gets the part 48/54 it has trouble finding .bazelrc and copying it across and stops. Does anyone else have this issue and how do you get around it?

**Comment by homuler** [comment]
Please share the log (cf. https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-install-issue.yml#description-log).

**Comment by StewieHF** [comment]
hi @homuler ill try and dig it out as i was using a spare gaming laptop running Win 10 Pro on that isnt to hand atm, but essentially its complaining about .bazelrc not being there to copy and i can confirm that its not present in the directory its building from, so i am wondering if there are general steps i need to do before hand for the docker build to work?

**Comment by homuler** [comment]
[This](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.bazelrc) is the `.bazelrc` and it exists at the project root.
So probably
- you're running the build command in the wrong folder, or
- you did not download the source code correctly

**Comment by StewieHF** [comment]
Yeah i dont have that, thank you ill probably just re-clone the whole project and start from scratch as sounds like something has gone wrong, thank you for the quick response
