### ISSUE TITLE
No camera image on mac demo

### ISSUE THREAD

**Issue by futuyao** [homuler/MediaPipeUnityPlugin#58]
I tried to run the demo on mac following the installation & build instructions, but the camera stream is not showing up. I wonder if there is an known issue?
<img width="1280" alt="Screen Shot 2021-02-09 at 11 32 35 AM" src="https://user-images.githubusercontent.com/10975110/107417710-ba82bb80-6aca-11eb-9376-79fca7bfd70f.png">

**Comment by homuler** [comment]
Please check this comment.
https://github.com/homuler/MediaPipeUnityPlugin/issues/44#issuecomment-768834398

If it doesn't resolve the problem, will you share Editor.log?

**Comment by futuyao** [comment]
Thanks for the reply. I couldn't find a resolution that fix the problem following the comment mentioned above. Editor.log is as attached.
[Editor.log](https://github.com/homuler/MediaPipeUnityPlugin/files/5973425/Editor.log)

**Comment by homuler** [comment]
I'd like to see the logs output when this problem occurred, but the attached log does not contain them (probably you started UnityEditor but did not run the example scene then). Those logs should have been also seen in Console Window.

> I couldn't find a resolution that fix the problem

If you have changed values randomly, please examine the available resolutions first.

**Comment by futuyao** [comment]
> I'd like to see the logs output when this problem occurred, but the attached log does not contain them (probably you started UnityEditor but did not run the example scene then). Those logs should have been also seen in Console Window.
> 
> > I couldn't find a resolution that fix the problem
> 
> If you have changed values randomly, please examine the available resolutions first (maybe 1280 x 720?).

Yeah I'm on 1280x720 but that one doesn't seem to fix it. Here's the console log, wonder if it's related?
![Screen Shot 2021-02-12 at 5 32 33 PM](https://user-images.githubusercontent.com/10975110/107837968-63921600-6d58-11eb-9fbe-5df17129cc5c.png)

**Comment by homuler** [comment]
Are you really **running** the example?

**Comment by homuler** [comment]
Judging from the above console image, you started Unity Editor but did not play the example scene.

Will you try this and share the Editor log?
1. Restart Unity Editor
2. Open `DesktopDemo` scene.
3. Enter play mode
4. Wait for 10 seconds
5. Exit play mode
6. Close Unity Editor

**Comment by homuler** [comment]
Ah, I'm sorry, maybe I misunderstood.
Are you running the example on PC standalone, not Unity Editor?
If so, please share the Player log, not Editor log.

And if you've not built AssetBundle file yet, see [this](https://github.com/homuler/MediaPipeUnityPlugin#desktop).

**Comment by Keerato** [comment]
I have the same issue,

After I build and run standalone builds. 
I got this error 
Failed to read data for the AssetBundle 'StreamingAssets\mediapipe'.
If you know how to solve this, please let me know.

[Player.log](https://github.com/homuler/MediaPipeUnityPlugin/files/6067143/Player.log)

**Comment by homuler** [comment]
@Keerato Will you pull the latest commit and try again, please?

**Comment by Keerato** [comment]
Thank you for your reply,

Now I know how to solve this issue.
@futuyao You should try to uncheck "Use GPU" of SceneDirector script in the DesktopDemo scene to use CPU mode and it might be worked.

@homuler Right now my issue was solved my fault is that when I install I run` make cpu ...` command and open Unity before I run `make install `command.  So, UnityEngine will create .meta file for every file instead of use make install to create the custom .meta file to make it a streaming asset.

I recommend you add `make install `command into Windows installation command to make it easier to follow the instructions.

**Comment by homuler** [comment]
Thank you. I updated README.

**Comment by homuler** [comment]
Closes this issue due to lack of activity.
