### ISSUE TITLE
Access is denied. 

### ISSUE THREAD

**Issue by 9276** [homuler/MediaPipeUnityPlugin#583]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

20220519

### Your Host OS

windows10

### Target Platform

Windows Standalone

### Command Sequences

python build.py build --desktop cpu --opencv cmake -vv

### Log

C:\mediapipe>docker run --cpus=10 --memory=32g ^ --mount type=bind,src=%CD%\Packages,dst=C:\mediapipe\Packages ^ --mount type=bind,src=%CD%\Assets,dst=C:\mediapipe\Assets ^ -it mediapipe_unity:windows
Microsoft Windows [Version 10.0.17763.2928]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\mediapipe>python build.py build --desktop cpu -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Python//pytho
n.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCE
SSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
Access is denied.
Traceback (most recent call last):
  File "C:\mediapipe\build.py", line 450, in <module>
    Argument().command().run()
  File "C:\mediapipe\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\mediapipe\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://
Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --act
ion_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returne
d non-zero exit status 1.

C:\mediapipe>

**Comment by homuler** [comment]
> C:\mediapipe>docker run --cpus=10 --memory=32g ^ --mount type=bind,src=%CD%\Packages,dst=C:\mediapipe\Packages ^ --mount type=bind,src=%CD%\Assets,dst=C:\mediapipe\Assets ^ -it mediapipe_unity:windows

I don't know the cause, but the prompt looks a bit strange to me since we usually run commands under the home folder (e.g. `C:\Users\homuler\...`), not `C:\mediapipe` (of course, it's OK in the Docker container).
I think it is most likely caused by your permission settings, so I recommend you check your folder permission settings or user permissions.

**Comment by 9276** [comment]
C:\Users\YouHu>docker run --cpus=10 --memory=32g ^ --mount type=bind,src=%CD%\Packages,dst=C:\mediapipe\Packages ^ --mount type=bind,src=%CD%\Assets,dst=C:\mediapipe\Assets ^ -it mediapipe_unity:windows
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: C:\Users\YouHu\Packages.
See 'docker run --help'.

**Comment by 9276** [comment]
i need new create Packages And Assets folder in home folder? dst=C:\mediapipe\Packages  here Packages  Refers to homuler/MediaPipeUnityPlugin/Packages  ?

**Comment by homuler** [comment]
Well, if you don't understand the meaning of commands, don't try to interpret the instructions in your own way.
Run the `docker run` command in the same folder as you ran the `docker build` command.

```bat
git clone https://github.com/homuler/MediaPipeUnityPlugin
cd MediaPipeUnityPlugin

docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile
docker run --cpus=10 --memory=32g ^
    --mount type=bind,src=%CD%\Packages,dst=C:\mediapipe\Packages ^
    --mount type=bind,src=%CD%\Assets,dst=C:\mediapipe\Assets ^
    -it mediapipe_unity:windows
```

You can skip the `docker build` command if you finished it.

**Comment by 9276** [comment]
I have another problem. I successfully built it in liunx, and then built APK in unity. However, only face detection scenes can be identified, and other scenes cannot
