### ISSUE TITLE
only face detection scenes can be identified, and other scenes cannot

### ISSUE THREAD

**Issue by 9276** [homuler/MediaPipeUnityPlugin#589]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

20220520

### Your Host OS

windows10

### Target Platform

Android

### Command Sequences

python build.py build --desktop cpu -vv

### Log

I have another problem. I successfully built it in liunx, and then built APK in unity. However, only face detection scenes can be identified, and other scenes cannot

**Comment by homuler** [comment]
Sorry, I don't get what you mean by "identified".
Can you share the screenshot or Video?
