### ISSUE TITLE
Unable to read the Android NDK 

### ISSUE THREAD

**Issue by Wayne-nulitics** [homuler/MediaPipeUnityPlugin#59]
When trying to build for Android (using Windows)
It's looking for "platforms" but NDK no longer uses that directory.

Unable to read the Android NDK at C:/Users/X/AppData/Local/Android/Sdk/ndk/22.0.7026061, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly?
Expected directory at C:/Users/X/AppData/Local/Android/Sdk/ndk/22.0.7026061/platforms but it is not a directory or it does not exist. Unable to read the Android NDK at C:/Users/X/AppData/Local/Android/Sdk/ndk/22.0.7026061, the path may be invalid.

**Comment by homuler** [comment]
Thank you for reporting the issue. I updated README.

First, `bazel` does not seem to support NDK r22 yet, so please try with NDK r21.
Second, [building mediapipe apks isn't possible on Windows](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) and so is this plugin. Probably building on WSL2 will work.
