### ISSUE TITLE
Bazel not finding valid C++ build tools

### ISSUE THREAD

**Issue by Luis-Alves2** [homuler/MediaPipeUnityPlugin#594]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2020.3.8f

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 14.29.30139.0
Windows SDK: 10.0.19041.0

### Command Sequences

1. Set Bazel variables:
2. set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
set BAZEL_VC_FULL_VERSION=14.29.30139.0
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0
3.Run build command :
python build.py build --desktop cpu --opencv=cmake -vv

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//Voxar//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/_bzl/fkv2puni/external/com_google_protobuf/BUILD:208:11: Compiling src/google/protobuf/reflection_ops.cc [for host] failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command
  cd /d C:/_bzl/fkv2puni/execroot/mediapipe_api
  SET INCLUDE=msvc_not_found
    SET PATH=msvc_not_found
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=msvc_not_found
    SET TMP=msvc_not_found
  external\local_config_cc\vc_installation_error_x64.bat @bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/reflection_ops.obj.params
# Configuration: f3cb267477348bd40775cd56b65a108859a27396130621170721d559a5ad7450
# Execution platform: @local_execution_config_platform//:platform

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture

Please check your installation following https://docs.bazel.build/versions/main/windows.html#using

Target //mediapipe_api:mediapipe_proto_srcs failed to build
INFO: Elapsed time: 0.960s, Critical Path: 0.29s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\NOTUX2R\MediaPipeUnityPlugin-0.10.0\build.py", line 450, in <module>
    Argument().command().run()
  File "C:\NOTUX2R\MediaPipeUnityPlugin-0.10.0\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\NOTUX2R\MediaPipeUnityPlugin-0.10.0\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\Voxar\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//Voxar//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

I`ve already tried to find a solution to this issue with the missing tools, which seems to be somewhat common: 
https://errorsfixing.com/why-bazel-does-not-find-visual-c-build-tools/
Almost every website appears to recommend changing the name of the directory from 2019 to 2017 (how that would work i do not know but you need to try everything). And so on the command sequences the path is indicating the use of 2017 Build tools however I`m using the 2019 build tools inside the 2017 directory.
The same error  ocurred when I tried to build in the `correct` directoy ,2019.
Has anyone else seen something like this?

**Comment by homuler** [comment]
Which version of the Windows are you using, 32-bit or 64bit?
cf. https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d

> But Bazel can't find the following tools:
cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture

See also https://github.com/bazelbuild/bazel/blob/17ed57ac5ad9b52bfc43e52ca40512f7114c58aa/tools/cpp/windows_cc_configure.bzl#L448-L467 to find out what your problems are.

Note that you need to install Visual C++ Build Tools _2019_ in the first place.
cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10

**Comment by Luis-Alves2** [comment]
@homuler thanks for the quick answer, Im using 64-bit windows. The same errors mentioned before happen when I use the 2019 directory (keep in mind that Ive used  Visual C++ Build Tools 2019 in both tries, only changing the name of the directory to 2017 before):
python build.py build --desktop cpu --opencv=cmake -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//Voxar//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/fkv2puni/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (96 packages loaded, 1244 targets configured).
INFO: Found 1 target...
ERROR: C:/_bzl/fkv2puni/external/com_google_protobuf/BUILD:515:10: Compiling src/google/protobuf/compiler/main.cc [for host] failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command
  cd /d C:/_bzl/fkv2puni/execroot/mediapipe_api
  SET INCLUDE=msvc_not_found
    SET PATH=msvc_not_found
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=msvc_not_found
    SET TMP=msvc_not_found
  external\local_config_cc\vc_installation_error_x64.bat @bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.obj.params
# Configuration: f3cb267477348bd40775cd56b65a108859a27396130621170721d559a5ad7450
# Execution platform: @local_execution_config_platform//:platform

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture

Please check your installation following https://docs.bazel.build/versions/main/windows.html#using

ERROR: C:/_bzl/fkv2puni/external/com_google_protobuf/BUILD:155:11: Compiling src/google/protobuf/arenastring.cc [for host] failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command
  cd /d C:/_bzl/fkv2puni/execroot/mediapipe_api
  SET INCLUDE=msvc_not_found
    SET PATH=msvc_not_found
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=msvc_not_found
    SET TMP=msvc_not_found
  external\local_config_cc\vc_installation_error_x64.bat @bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/arenastring.obj.params
# Configuration: f3cb267477348bd40775cd56b65a108859a27396130621170721d559a5ad7450
# Execution platform: @local_execution_config_platform//:platform

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture

Please check your installation following https://docs.bazel.build/versions/main/windows.html#using

Target //mediapipe_api:mediapipe_proto_srcs failed to build
INFO: Elapsed time: 25.858s, Critical Path: 0.74s
INFO: 131 processes: 131 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\NOTUX2R\MediaPipeUnityPlugin-0.10.0\build.py", line 450, in <module>
    Argument().command().run()
  File "C:\NOTUX2R\MediaPipeUnityPlugin-0.10.0\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\NOTUX2R\MediaPipeUnityPlugin-0.10.0\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\Voxar\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//Voxar//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
I also looked at the bazel build file of the link you sent, however, still cant find an issue :/

**Comment by homuler** [comment]
> I also looked at the bazel build file of the link you sent, however, still cant find an issue :/

Did you check if the files (i.e. `cl.exe`, `link.exe`, `lib.exe`, `ml64.exe`) really exist under the folder `Bazel` is looking for (e.g. `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30139.0\bin\HostX64\x64\cl.exe`)?

By the way, if there's only one VC instance is installed, you don't need to set environment variables (i.e. `BAZEL_VS`, `BAZEL_VC`, `BAZEL_VC_FULL_VERSION`).
