### ISSUE TITLE
I am going to install bazel 3.7.2, but following error occured. Target //src:bazel_nojdk failed to build

### ISSUE THREAD

**Issue by HiddenStar0412** [homuler/MediaPipeUnityPlugin#595]
### Plugin Version or Commit ID

v0.5.0

### Unity Version

2021.2.17

### Your Host OS

mac OS Montrery 12.4

### Target Platform

iOS

### [iOS Only] XCode Version

12.4

### Command Sequences

$ brew install bazel@3.7.2

### Log

$ brew install bazel@3.7.2
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

==> Downloading https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-dist.zip
Already downloaded: /Users/hiddenstar/Library/Caches/Homebrew/downloads/66156404c0229400fe72d2b4bf6bf0cac3b8d9e25f6d906842bb3b27e81de2c8--bazel-3.7.2-dist.zip
==> Installing bazel@3.7.2 from bazelbuild/tap
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.

==> ./compile.sh
Last 15 lines from /Users/hiddenstar/Library/Logs/Homebrew/bazel@3.7.2/01.compile.sh:
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 475.684s, Critical Path: 46.93s
INFO: 871 processes: 17 internal, 854 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/bazelbuild/homebrew-tap/issues

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.

### Additional Context

I am using a little old version of mediapipe. I already made an app by using this plugin on Windows and Android.
I am going to build ios framework for iOS build.
But I faced some issues on Mac OS Montrery and I thought I have to downgrade bazel.
but I faced this error during installing bazel@3.7.2

**Comment by homuler** [comment]
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/bazelbuild/homebrew-tap/issues
