### ISSUE TITLE
Stripped build always includes unused Packets, causes errors on IOS build in Xcode

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#596]
### Plugin Version or Commit ID

358f7b9ac6f08d4e4f7b1d1fac9d5458e2d1730f

### Unity Version

2022.1.2f1

### Your Host OS

MacOS M1 Mac 12.4 Monterey

### Target Platform

iOS

### Target Device

iPhone 6

### [iOS Only] XCode Version

13.4 (13F17a)

### Build Command

python build.py build  --ios arm64 --linkopt=-s -vv

### Bug Description

When building mediapipe with some unneeded models/graphs removed (e.g. Pose tracking only build), in Xcode the build will still contain and try to access packets/graphs which are not needed in the build or ones that have been removed. This doesn't affect desktop builds but it affects IOS builds and these errors pop up in Xcode.

This is caused by commenting out unused parts in the mediapipe_api BUILD file before building then trying to build just the required demo scene e.g. Pose tracking only 

### Steps to Reproduce the Bug

1. Pull down the Repo from the commit mentioned above
2. Replace or edit the mediapipe_api/BUILD file to match this one: [BUILD.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/8797724/BUILD.txt)
3. Build mediapipe using the command from above
4. Open the project in Unity, set to only build the Posetracking sample for IOS
5. Set Player Settings > Stripping to MInimal or Low (should be Minimal by default)
6. Try to build and run to IOS, see errors in Xcode

### Log

Showing Recent Messages
Undefined symbol: _mp_Packet__GetTimedModelMatrixProtoList

Undefined symbol: _mp_Packet__GetFrameAnnotation

Undefined symbol: _mp__MakeAnchor3dVectorPacket_At__PA_i_Rt

Undefined symbol: _mp_Packet__GetFaceGeometry

Undefined symbol: _mp_Anchor3dArray__delete

Undefined symbol: _mp_Packet__GetFaceGeometryVector

Undefined symbol: _mp_Packet__GetAnchor3dVector

Undefined symbol: _mp__MakeAnchor3dVectorPacket__PA_i

### Screenshot/Video

![Screenshot 2022-05-30 at 12 26 18 pm](https://user-images.githubusercontent.com/10745594/171000492-437eba23-c42f-41c0-ace3-b0340f361143.png)

### Additional Context

The workaround for this currently is to edit these files so that they have commented out `UnsafeNativeMethods` and ```DllImport(MediaPipeLibrary, ExactSpelling = true)]
    public static extern MpReturnCode``` for the problematic or remaining methods, as well as making any functions calling them to return `null` values
    
File names:
FaceGeometryPacket.cs
FaceGeometryVectorPacket.cs
FrameAnnotationPacket.cs
TimedModelMatrixProtoListPacket.cs
Anchor3dVector.cs
InstantMotionTracking_Unsafe.cs
Anchor3dVectorPacket.cs
Protobuf_Unsafe.cs
Zip of files
[FixedFiles.zip](https://github.com/homuler/MediaPipeUnityPlugin/files/8798838/FixedFiles.zip)

I wonder if there is some way to make these just return nothing if they are not used in the demo scenes? This fix works for us for now.

I also had to go do this to get the app actually running on IOS which may help others:
1. Change the Bootstrap asset loader type to Streaming Assets
2. Go to Build Phases, expand Embedded Frameworks and select all Code Sign on Copy checkboxes for the build to install in Xcode then once running, the device camera wouldn't work until I opened the camera menu in app, selected image then webcam again and changed the device camera to front, once I hit exit the use camera permission showed and I could then see the camera on IOS.

**Comment by homuler** [comment]
> Replace or edit the mediapipe_api/BUILD file to match this one: [BUILD.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/8797724/BUILD.txt)

If you don't want to modify C# source files, you cannot change the `deps` of `mediapipe_c` (i.e. `//mediapipe_api/graphs/object_detection_3d/calculators:model_matrix`, `//mediapipe_api/graphs/instant_motion_tracking/calculators:transformations`, `//mediapipe_api/modules/face_geometry/protos:face_geometry`, `//mediapipe_api/modules/objectron/calculators:annotation`).

**Comment by ROBYER1** [comment]
> > Replace or edit the mediapipe_api/BUILD file to match this one: [BUILD.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/8797724/BUILD.txt)
> 
> If you don't want to modify C# source files, you cannot change the `deps` of `mediapipe_c` (i.e. `//mediapipe_api/graphs/object_detection_3d/calculators:model_matrix`, `//mediapipe_api/graphs/instant_motion_tracking/calculators:transformations`, `//mediapipe_api/modules/face_geometry/protos:face_geometry`, `//mediapipe_api/modules/objectron/calculators:annotation`).

I understand, hopefully this issue will be useful for anyone else who finds this as I detailed what we did to get it working.
