### ISSUE TITLE
error : invalid argument '-std=c++17' not allowed with 'C'

### ISSUE THREAD

**Issue by yjy020892** [homuler/MediaPipeUnityPlugin#597]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Pro

### Target Platform

UnityEditor, Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++ : 14.29.30133
Window SDK : 10.0.19041.0

### [Android Only] Android Build Tools and NDK Version

NDK : 21.4.7075529

### Command Sequences

python build.py build --desktop cpu --android arm64 -vv

### Log

c -o bazel-out/android-arm64-v8a-opt/bin/external/XNNPACK/_objs/jit_memory/memory.pic.o
# Configuration: 7a3db7fbb1e9e1c115eeff7d61aefa767c812e76439a8ec70cc92f6b9a33bf81
# Execution platform: @local_execution_config_platform//:platform
error: invalid argument '-std=c++17' not allowed with 'C'
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 303.061s, Critical Path: 208.67s
INFO: 929 processes: 381 internal, 548 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Unity\MediaPipeUnityPlugin\build.py", line 450, in <module>
    Argument().command().run()
  File "C:\Unity\MediaPipeUnityPlugin\build.py", line 147, in run
    self._run_command(self._build_android_commands())
  File "C:\Unity\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\strato\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Unity//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.

### Additional Context

I don't know if I posted the error log correctly.

There was a toolchain error earlier, but I solved it by looking at the Troubleshooting.

However, this error was not in Troubleshooting, so I left a post.

Help me plz. T^T

**Comment by homuler** [comment]
> 5. Install [Bazelisk](https://docs.bazel.build/versions/main/install-bazelisk.html) and add the location of the executable to %PATH% environment variable.

Have you installed `Bazelisk`, not `Bazel`?

**Comment by yjy020892** [comment]
Thanks for the quick reply.
I had bazel installed, so I reinstalled it with bazelisk.
After that, the old error disappeared and a new error appeared.


# Configuration: fd42ac5739ac46ac722abb276fe7432014168e62660ea2a163f9f7d55e49aed9
# Execution platform: @local_execution_config_platform//:platform
external/XNNPACK/src/qs8-gemm/gen/4x16-minmax-fp32-aarch64-neon-mlal-lane-prfm-cortex-a53.S:11:10: fatal error: 'xnnpack/assembly.h' file not found
#include <xnnpack/assembly.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 214.694s, Critical Path: 171.90s
INFO: 703 processes: 209 internal, 494 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\Unity\MediaPipeUnityPlugin\build.py", line 450, in <module>
    Argument().command().run()
  File "C:\Unity\MediaPipeUnityPlugin\build.py", line 147, in run
    self._run_command(self._build_android_commands())
  File "C:\Unity\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\strato\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Unity//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.

**Comment by yjy020892** [comment]
> > 5. Install [Bazelisk](https://docs.bazel.build/versions/main/install-bazelisk.html) and add the location of the executable to %PATH% environment variable.
> 
> Have you installed `Bazelisk`, not `Bazel`?

Thanks for the quick reply.
I had bazel installed, so I reinstalled it with bazelisk.
After that, the old error disappeared and a new error appeared.

Configuration: fd42ac5739ac46ac722abb276fe7432014168e62660ea2a163f9f7d55e49aed9
Execution platform: @local_execution_config_platform//:platform
external/XNNPACK/src/qs8-gemm/gen/4x16-minmax-fp32-aarch64-neon-mlal-lane-prfm-cortex-a53.S:11:10: fatal error: 'xnnpack/assembly.h' file not found
#include <xnnpack/assembly.h>
^~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 214.694s, Critical Path: 171.90s
INFO: 703 processes: 209 internal, 494 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
File "C:\Unity\MediaPipeUnityPlugin\build.py", line 450, in
Argument().command().run()
File "C:\Unity\MediaPipeUnityPlugin\build.py", line 147, in run
self._run_command(self._build_android_commands())
File "C:\Unity\MediaPipeUnityPlugin\build.py", line 54, in _run_command
return subprocess.run(' '.join(command_list), check=True, shell=shell)
File "C:\Users\strato\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Unity//MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10

> :warning: You cannot build libraries for Android with the following steps.
If you use Window 10 Pro, go to [Docker Windows Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-windows-container). Otherwise, go to [Docker Linux Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container).

**Comment by yjy020892** [comment]
thx bro
