### ISSUE TITLE
Objectron predicts low confidence and tracking jitter

### ISSUE THREAD

**Issue by Phantomxm2021** [homuler/MediaPipeUnityPlugin#598]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3f1

### Your Host OS

MacOS M1

### Target Platform

iOS

### Description

Hi,
I'm try to create a shoes try-on app, but there are some problems:

1. Low confidence
2. tracking jitter
3. Need to set `FOCAL_LENGTH ` and `PRINCIPAL_POINT`  

What do I need to do to get rid of these two problems？

As shown in the video effect.

https://user-images.githubusercontent.com/82647748/171526093-6fc1f1dc-6824-4889-8527-732d5b841d21.mp4

Thanks in advance.

### Code to Reproduce the issue

```
var tmp_Rotation = CameraCoordinate.GetApproximateQuaternion(target);
sneaker.rotation = tmp_Rotation;
var tmp_Position = screen.rect.GetPoint(target.Keypoints[0].Point3D,
Application.isEditor ? Vector2.one : new Vector2(2.0975f, 1.5731f), Vector2.zero, 1, rotationAngle, isMirrored); 
sneaker.localPosition = tmp_Position;
sneaker.localScale = (target.Scale[0] + target.Scale[1] + target.Scale[2]) / 3 * Vector3.one * 90000 ;
```

**Comment by homuler** [comment]
How about setting a larger value to [`ObjectronGraph#minDetectionConfidence`](https://github.com/homuler/MediaPipeUnityPlugin/blob/358f7b9ac6f08d4e4f7b1d1fac9d5458e2d1730f/Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronGraph.cs#L30) (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/396#issuecomment-1062632062)?

**Comment by nenenkosi** [comment]
> var tmp_Position = screen.rect.GetPoint(target.Keypoints[0].Point3D,
Application.isEditor ? Vector2.one : new Vector2(2.0975f, 1.5731f), Vector2.zero, 1, rotationAngle, isMirrored); 
sneaker.localPosition = tmp_Position;

@Phantomxm2021 nice work to get it running I would like to know how did you get the **screen.rect**  from please explain or share some code on how you got it and also please tell me how did you do your occlusion did you use a shader or something else.

Any kind of help will be highly appreciated thanks.

**Comment by Phantomxm2021** [comment]
> How about setting a larger value to [`ObjectronGraph#minDetectionConfidence`](https://github.com/homuler/MediaPipeUnityPlugin/blob/358f7b9ac6f08d4e4f7b1d1fac9d5458e2d1730f/Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronGraph.cs#L30) (cf. [#396 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/396#issuecomment-1062632062))?

Although adjusting [ObjectronGraph#minDetectionConfidence](https://github.com/homuler/MediaPipeUnityPlugin/blob/358f7b9ac6f08d4e4f7b1d1fac9d5458e2d1730f/Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronGraph.cs#L30) will lead to a decrease in the recognition success rate, it solves the problem of recognition errors and reduces jitter.

**Comment by Phantomxm2021** [comment]
> > var tmp_Position = screen.rect.GetPoint(target.Keypoints[0].Point3D,
> > Application.isEditor ? Vector2.one : new Vector2(2.0975f, 1.5731f), Vector2.zero, 1, rotationAngle, isMirrored);
> > sneaker.localPosition = tmp_Position;
> 
> @Phantomxm2021 nice work to get it running I would like to know how did you get the **screen.rect** from please explain or share some code on how you got it and also please tell me how did you do your occlusion did you use a shader or something else.
> 
> Any kind of help will be highly appreciated thanks.

## About  Screen rect
The **screen.rect** is a gameobject of  Annotatable Screen. 
And it's a RectTransform component, we can using `GameObject.Find("Annotatable Screen").GetComponent<RectTransform>();` to got it.

## About Occlusion
We wrote a shader for it.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/82647748/171990775-92a158da-0d9c-4fd0-bcd5-c0c67f6b0314.png">


```Shader
Shader "Custom/ObjectOcclusionShader"
{
    SubShader
    {
        Tags { "RenderType"="Opaque" }
        Tags { "Queue" = "Geometry-1" }
        ZWrite On
        ZTest LEqual
        ColorMask 0

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            
            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
            };

            struct v2f
            {
                float4 vertex : SV_POSITION;
            };

            v2f vert (appdata v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                return o;
            }
            
            fixed4 frag (v2f i) : SV_Target
            {
                return fixed4(0.0, 0.0, 0.0, 0.0);
            }
            ENDCG
        }
    }
}

```

**Comment by nenenkosi** [comment]
@Phantomxm2021  thanks a lot for all your help I implemented everything as you suggested but am getting different results I tried modifying it but am still not getting the wrong results I think they is something wrong with my implementation and the occlusion shader is black on my side.

Please can you have a look at my implementation and help me in any way you can here is a link to my git repo [https://github.com/nenenkosi/MediaPipeUnityPlugin-copy](https://github.com/nenenkosi/MediaPipeUnityPlugin-copy).

I created a file named WearShoe.cs that’s where I implemented the code here is the code below.


`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mediapipe.Unity.CoordinateSystem;

namespace Mediapipe.Unity.Objectron
{
  public class WearShoe : MonoBehaviour
  {
    public GameObject Shoeblender;
    [SerializeField] private ObjectronSolution _objectronSolution;
   
    private GameObject sneaker;

    void Start()
    {
      sneaker = Instantiate(Shoeblender, new Vector3(0, 0, 0), Quaternion.identity);
    }

    void Update()
    {
      var x = _objectronSolution._frameAnnotation;
      
      if (x != null)
      {
        DrawShoe(x.Annotations[0]);
      }
    }

    private void DrawShoe(ObjectAnnotation target)
    {
      var isMirrored = false;
      var rotationAngle = RotationAngle.Rotation0;;
    
      var screen = GameObject.Find("Annotatable Screen").GetComponent<RectTransform>();
  
      var tmp_Rotation = CameraCoordinate.GetApproximateQuaternion(target);
      var tmp_Position = screen.rect.GetPoint(target.Keypoints[0].Point3D,
      Application.isEditor ? Vector2.one : new Vector2(2.0975f, 1.5731f), Vector2.zero, 1, rotationAngle, isMirrored); 

      sneaker.transform.rotation = tmp_Rotation;
      sneaker.transform.localPosition = tmp_Position;
      sneaker.transform.localScale = (target.Scale[0] + target.Scale[1] + target.Scale[2]) / 3 * Vector3.one * 3 ;

    }
  }
}
`

Please help me thank in advance

**Comment by homuler** [comment]
Lowering `MIN_TRACKING_CONFIDENCE` (e.g. `0.3`) may also stabilize the detection in some cases.

@Phantomxm2021 May I close the issue?

**Comment by Phantomxm2021** [comment]
> 

Yes, Thank you.

**Comment by burungiu** [comment]
I have a problem, the capsule and sphere are black on the iPhone. Do you know how to solve it? I used the shader which you wrote in a early comment.
