### ISSUE TITLE
Mapping Hand Tracking points to 3D points

### ISSUE THREAD

**Issue by smtabatabaie** [homuler/MediaPipeUnityPlugin#599]
### Description

Hi, Are there any ways to map hand tracking points to 3d locations in the scene? The sample shows the points in 2D and in a canvas, But what I'm looking for is a way to map them to 3d points in my scene, and I wanted to ask if anyone has tried that.
Thanks

**Comment by homuler** [comment]
> The sample shows the points in 2D and in a canvas

Try setting `true` to `visualizeZ` (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/94#issuecomment-973545978).
![Screenshot_20220603_114634-1](https://user-images.githubusercontent.com/4690128/171777057-95853af9-53c7-4cb2-ad25-b90daf1de4b5.png)

See also https://google.github.io/mediapipe/solutions/hands.html#output.

**Comment by homuler** [comment]
> What I want to achieve is to have each of users hand's landmarks in 3d space and show a 3d hand in my scene.

What is preventing you from implementing it by yourself?
The returned value is explained in the official document and how to convert the coordinate system is explained in the tutorial.
Which part is unclear to you?

> I also wanted to ask if there's any way to get the rotation info of landmarks.

If MediaPipe does not implement such a calculator, you will need to calculate it.
