### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by yellowflash07** [homuler/MediapipeUnityPlugin#6]
Hello, while building the latest repo i am getting errors after successful build:

Test Run Successful.
Total tests: 1124
     Passed: 1124
 Total time: 7.3823 Seconds
# TODO build all the .proto files and output to the same directories
protoc --proto_path=Assets/Mediapipe/SDK/Scripts --csharp_out=Assets/Mediapipe/SDK/Scripts/Protobuf Assets/Mediapipe/SDK/Scripts/Protobuf/*.proto && \
protoc --proto_path=Assets/Mediapipe/SDK/Scripts --csharp_out=Assets/Mediapipe/SDK/Scripts/Protobuf/Annotation Assets/Mediapipe/SDK/Scripts/Protobuf/Annotation/*.proto
/bin/sh: 1: protoc: not found
make: *** [Makefile:36: mediapipe_protos] Error 127

How to fix this?

**Comment by homuler** [comment]
Please install protocol buffer compiler.
https://github.com/homuler/MediapipeUnityPlugin#protocol-buffer

**Comment by yellowflash07** [comment]
i have installed protocol buffer. it's installed under usr/local/lib ..it's a directory mismatch maybe? where do i change that?

**Comment by yellowflash07** [comment]
yep, it was path error. Fixed it with 

`export LD_LIBRARY_PATH=/usr/local/lib`
