### ISSUE TITLE
No AssetBundle has been set for this build.

### ISSUE THREAD

**Issue by Wayne-nulitics** [homuler/MediaPipeUnityPlugin#60]
Can't create Asset Bundles from Editor as explained under Desktop section.

Error from Unity when selection Build AssetBundles:

No AssetBundle has been set for this build.
UnityEditor.BuildPipeline:BuildAssetBundles(String, BuildAssetBundleOptions, BuildTarget)
CreateAssetBundles:BuildAllAssetBundles() (at Assets/MediaPipe/Editor/CreateAssetBundles.cs:15)

**Comment by philiprkk** [comment]
If you're on windows, make sure you also run "make install" to move all necessary files into the project.

**Comment by Wayne-nulitics** [comment]
Yes, have it working on Windows, everything is working as it should.
