### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'mediapipe_jni'. Tried the load the following dynamic libraries: Unable to load dynamic library 'mediapipe_jni' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "mediapipe_jni" not found

### ISSUE THREAD

**Issue by HiddenStar0412** [homuler/MediaPipeUnityPlugin#600]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

mac OS Montrery 12.4

### Target Platform

Android

### Description

You have successfully built a library for Android on Intel Mac and attempted to build a sample on Unity.
However, DllNotFoundException occurs on my device.
My test device is Asus Z017DA.
As you can see in logcat, the cpu of the device is arm64.

It seems to work properly on other devices.
I tested it by building it in both modes, arm64 and fat, but it is the same result.

When attempting the load library, an error like the attached image is displayed.
What do you think is the cause?

Thanks

[https://drive.google.com/file/d/1TsFRFM5FKMWeq2J2SbDc1MhATf9i6S-8/view?usp=sharing](url)

### Code to Reproduce the issue

public class LibTester : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
      LoadLibrary();
    }

  public void LoadLibrary()
  {
    using (var system = new AndroidJavaClass("java.lang.System"))
    {
      system.CallStatic("loadLibrary", "mediapipe_jni");
    }
  }
}

### Additional Context

https://drive.google.com/file/d/116sJQiqA5cR2pg8UDJR1ARR9nD1T1zAI/view?usp=sharing

**Comment by homuler** [comment]
Duplicates #171.

See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#android-configuration and https://github.com/homuler/MediaPipeUnityPlugin/issues/536#issuecomment-1105964717.
> To support older Android, you need to specify the API level for NDK when running `build.py`.
Otherwise, some symbols in `libmediapipe_jni.so` cannot be resolved and `DllNotFoundException` will be thrown at runtime.
