### ISSUE TITLE
Visibility/Presence always 0

### ISSUE THREAD

**Issue by Kasra-G** [homuler/MediaPipeUnityPlugin#601]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Home

### Target Platform

Windows Standalone

### Description

Visibility and Presence fields in a NormalizedLandmark for the HandTracking Solution seem to always be 0. Do you know if this is a bug or is it something that isn't supported right now?

### Additional Context

Only tested:
- Sync mode
- NormalizedLandmarks output in the HandTracking solution

Thanks for the port! :)

**Comment by homuler** [comment]
https://github.com/google/mediapipe/blob/50c92c6623a580206c0c1ff2141ecb7c9bea305d/mediapipe/framework/formats/landmark.proto
```proto
  // Landmark visibility. Should stay unset if not supported.
  // Float score of whether landmark is visible or occluded by other objects.
  // Landmark considered as invisible also if it is not present on the screen
  // (out of scene bounds). Depending on the model, visibility value is either a
  // sigmoid or an argument of sigmoid.
  optional float visibility = 4;

  // Landmark presence. Should stay unset if not supported.
  // Float score of whether landmark is present on the scene (located within
  // scene bounds). Depending on the model, presence value is either a result of
  // sigmoid or an argument of sigmoid function to get landmark presence
  // probability.
  optional float presence = 5;
```

> Do you know if this is a bug or is it something that isn't supported right now?

Please ask it in the official community.
