### ISSUE TITLE
Bazel Error :  git apply ..\mediapipe\third_party\bazel_android_fixes.diff

### ISSUE THREAD

**Issue by HiddenStar0412** [homuler/MediaPipeUnityPlugin#603]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Docker

### Target Platform

UnityEditor

### Command Sequences

git apply ..\mediapipe\third_party\bazel_android_fixes.diff

### Log

C:\mediapipe>git clone https://github.com/bazelbuild/bazel.git C:\bazel
Cloning into '/c/bazel'...
remote: Enumerating objects: 618446, done.
remote: Counting objects: 100% (1186/1186), done.
error: RPC failed; curl 56 OpenSSL SSL_read: Connection reset by peer, errno 104
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

C:\mediapipe>git clone https://github.com/bazelbuild/bazel.git C:\bazel
Cloning into '/c/bazel'...
remote: Enumerating objects: 618446, done.
remote: Counting objects: 100% (1186/1186), done.
remote: Compressing objects: 100% (637/637), done.
remote: Total 618446 (delta 509), reused 1028 (delta 387), pack-reused 617260
Receiving objects: 100% (618446/618446), 836.63 MiB | 14.48 MiB/s, done.
Resolving deltas: 100% (386733/386733), done.
Updating files: 100% (9340/9340), done.

C:\mediapipe>cd C:\bazel

C:\bazel>git checkout 5.0.0
Updating files: 100% (3703/3703), done.
Note: switching to '5.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 41feb616ae Release 5.0.0 (2022-01-19)

C:\bazel>git apply ..\mediapipe\third_party\bazel_android_fixes.diff
error: patch failed: src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt:14
error: src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt: patch does not apply
error: patch failed: src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java:31
error: src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java: patch does not apply

C:\bazel>

**Comment by homuler** [comment]
As far as your target platform is not Android, you can skip the 5th step in https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-windows-container.

**Comment by HiddenStar0412** [comment]
I'm targeting Android,too

**Comment by homuler** [comment]
By any chance, is the line feed code in the `third_party\bazel_android_fixes.diff` set to CR+LF?
cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows

At any rate, as noted in the document, this is an experimental step and I won't support you in the event of any errors.
If you don't know how to proceed, use a [Docker Linux Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container) instead.
