### ISSUE TITLE
Installation Guide - Docker Windows Container error

### ISSUE THREAD

**Issue by yjy020892** [homuler/MediaPipeUnityPlugin#608]
### Plugin Version or Commit ID

v.0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Pro

### Target Platform

UnityEditor, Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++ : 14.29.30133
Window SDK : 10.0.19041.0

### [Android Only] Android Build Tools and NDK Version

NDK : 21.4.7075529

### Command Sequences

git apply ..\mediapipe\third_party\bazel_android_fixes.diff

### Log

C:\bazel>git apply ..\mediapipe\third_party\bazel_android_fixes.diff
error: patch failed: src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.t
xt:14
error: src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt: patch does
 not apply
error: patch failed: src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java:31
error: src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java: patch does not apply

### Additional Context

In order to build and test Android in Unity Editor, Docker Windows Container was in progress.

A further question is, the end goal is to build in the Unity editor and run it in the Android environment. If I complete python build.py build --desktop cpu -vv and build it again on Android in Unity editor, is it done?

Take good care of me

**Comment by yjy020892** [comment]
I tried to build again using the Docker Linux Container process just in case, but this error occurred



ERROR: /home/mediapipe/mediapipe_api/framework/formats/object_detection/BUILD:20:17: Executing genrule //mediapipe_api/framework/formats/object_detection:anchor_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/194/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/framework/formats/object_detection/anchor.proto
mv bazel-out/k8-opt/bin/Anchor.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/framework/formats/object_detection/Anchor.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/tflite/BUILD:54:17: Executing genrule //mediapipe_api/calculators/tflite:tflite_converter_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/190/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/tflite/tflite_converter_calculator.proto
mv bazel-out/k8-opt/bin/TfliteConverterCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/tflite/TfliteConverterCalculator.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/graphs/object_detection_3d/calculators/BUILD:35:17: Executing genrule //mediapipe_api/graphs/object_detection_3d/calculators:model_matrix_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/193/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/graphs/object_detection_3d/calculators/model_matrix.proto
mv bazel-out/k8-opt/bin/ModelMatrix.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/graphs/object_detection_3d/calculators/ModelMatrix.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/tensor/BUILD:39:17: Executing genrule //mediapipe_api/calculators/tensor:tensor_converter_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/188/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/tensor/tensor_converter_calculator.proto
mv bazel-out/k8-opt/bin/TensorConverterCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/tensor/TensorConverterCalculator.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/util/BUILD:161:17: Executing genrule //mediapipe_api/calculators/util:rect_to_render_scale_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/187/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/util/rect_to_render_scale_calculator.proto
mv bazel-out/k8-opt/bin/RectToRenderScaleCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/util/RectToRenderScaleCalculator.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/modules/objectron/calculators/BUILD:120:17: Executing genrule //mediapipe_api/modules/objectron/calculators:frame_annotation_to_rect_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/191/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/modules/objectron/calculators/frame_annotation_to_rect_calculator.proto
mv bazel-out/k8-opt/bin/FrameAnnotationToRectCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/modules/objectron/calculators/FrameAnnotationToRectCalculator.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/framework/formats/BUILD:114:17: Executing genrule //mediapipe_api/framework/formats:detection_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/189/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/framework/formats/detection.proto
mv bazel-out/k8-opt/bin/Detection.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/framework/formats/Detection.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/util/BUILD:210:17: Executing genrule //mediapipe_api/calculators/util:thresholding_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/186/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/util/thresholding_calculator.proto
mv bazel-out/k8-opt/bin/ThresholdingCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/util/ThresholdingCalculator.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
ERROR: /home/mediapipe/mediapipe_api/calculators/tflite/BUILD:63:17: Executing genrule //mediapipe_api/calculators/tflite:tflite_tensors_to_segmentation_calculator_cs failed: (Exit 127): bash failed: error executing command
  (cd /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/sandbox/processwrapper-sandbox/192/execroot/mediapipe_api && \
  exec env - \
    PATH=/home/mediapipe/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/home/mediapipe/.npm-packages/bin:/home/mediapipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
mkdir -p bazel-out/k8-opt/bin
bazel-out/host/bin/external/com_google_protobuf/protoc     --proto_path=.     --proto_path=bazel-out/k8-opt/bin     --proto_path=$(pwd)/external/com_google_protobuf/src     --proto_path=$(pwd)/external/com_google_mediapipe     --csharp_out=bazel-out/k8-opt/bin mediapipe/calculators/tflite/tflite_tensors_to_segmentation_calculator.proto
mv bazel-out/k8-opt/bin/TfliteTensorsToSegmentationCalculator.cs $(dirname bazel-out/k8-opt/bin/mediapipe_api/calculators/tflite/TfliteTensorsToSegmentationCalculator.cs)
')
# Configuration: 11cb15b5840dd54e57552e3eb26e16a0b0c4c5938defa6cccdfff7c21e059876
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 1: $'\r': command not found
Target //mediapipe_api:mediapipe_proto_srcs failed to build
INFO: Elapsed time: 208.358s, Critical Path: 79.30s
INFO: 334 processes: 149 internal, 185 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 459, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/mediapipe/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by homuler** [comment]
duplicates #603.

See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows and https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#binbash-line-1-r-command-not-found.

> > :warning: You MUST NOT set `core.autocrlf` in `.gitconfig` (run `git config -l`). To build libraries successfully, you need to check out the source code as it is without changing the line feed code.
