### ISSUE TITLE
How to get posedetection keypoints

### ISSUE THREAD

**Issue by palnikhil** [homuler/MediaPipeUnityPlugin#610]
### Plugin Version or Commit ID

v0.8

### Unity Version

2020.3.29f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor, Windows Standalone, Linux Standalone

### Description

I am unable to get the body coordinates through poseLandmarks variable. Everytime I am running the command
Debug.Log(poseLandmark.landmark[0].x) . It is throwing the error.
Assets\Mediapipe\Samples\Scenes\Pose Tracking\PoseTrackingValue.cs(26,31): error CS1061: 'NormalizedLandmarkList' does not contain a definition for 'landmark' and no accessible extension method 'landmark' accepting a first argument of type 'NormalizedLandmarkList' could be found (are you missing a using directive or an assembly reference?)

### Code to Reproduce the issue

using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace Mediapipe.Unity.PoseTracking
{
  public class PoseTrackingValue
  {
    public readonly Detection poseDetection;
    public readonly NormalizedLandmarkList poseLandmarks;
    public readonly LandmarkList poseWorldLandmarks;
    public readonly NormalizedRect roiFromLandmarks;

    public PoseTrackingValue(Detection poseDetection, NormalizedLandmarkList poseLandmarks, LandmarkList poseWorldLandmarks, NormalizedRect roiFromLandmarks)
    {
      this.poseDetection = poseDetection;
      this.poseLandmarks = poseLandmarks;
      this.poseWorldLandmarks = poseWorldLandmarks;
      this.roiFromLandmarks = roiFromLandmarks;
      Debug.Log(poseLandmarks.landmark[0]);
    }
  }
}

### Additional Context

![image](https://user-images.githubusercontent.com/85008177/173624053-88e66fc6-6fcc-4cf2-bda2-e274893ab1c1.png)

**Comment by homuler** [comment]
See #560 and https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks.

I strongly recommend you enable code completions in your editor (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/263#issuecomment-964721887).
