### ISSUE TITLE
Ability to build Intel + M1 compatible plugin or at least Universal Plugin from M1 Mac?

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#611]
### Feature Description

Mentioned in this issue https://github.com/homuler/MediaPipeUnityPlugin/issues/501 I am struggling to make an Intel compatible build or a build which runs on both Intel and M1 macs from building on an M1 mac I have access to. 

Is there a way to build both the Intel and M1 compatible plugins from the M1 mac or even a Universal plugin as mentioned in the issue linked above?

### Current Behaviour/State

Requires use of a separate Intel and M1 Mac to build the separate plugins, then I assume use `lipo -create -output libmediapipe_c.so libmediapipe_c_x86.so libmediapipe_c_arm.so` to combine them into a Universal plugin?

**Comment by homuler** [comment]
> Is there a way to build both the Intel and M1 compatible plugins from the M1 mac or even a Universal plugin as mentioned in the issue linked above?

Theoretically, yes.
However, there is currently no way to cross-compile without changing the source files (i.e. both Intel mac and M1 mac are required).

**Comment by ROBYER1** [comment]
> > Is there a way to build both the Intel and M1 compatible plugins from the M1 mac or even a Universal plugin as mentioned in the issue linked above?
> 
> Theoretically, yes. However, there is currently no way to cross-compile without changing the source files (i.e. both Intel mac and M1 mac are required).

I spent over a week looking into why an M1 built Mediapipe plugin would work sometimes on an intel Mac - Can I request that in the Mac build section of the Wiki or somewhere else it could be mentioned that the build plugin will be intel/M1 only and that the Apple `lipo -create -output libmediapipe_c.so libmediapipe_c_x86.so libmediapipe_c_arm.so` command can be used on the two plugins if they are renamed appropriately (I assume rename the dylib file?) to put them together into a universal plugin for MacOS?

**Comment by homuler** [comment]
Now we can build a universal library on M1 Mac or Intel Mac.

```sh
python build.py build --desktop cpu --opencv cmake --macos_universal -vv
```

Note that NEON will be disabled when building it on Intel Mac.

**Comment by ROBYER1** [comment]
> Now we can build a universal library on M1 Mac or Intel Mac.
> 
> ```shell
> python build.py build --desktop cpu --opencv cmake --macos_universal -vv
> ```
> 
> Note that NEON will be disabled when building it on Intel Mac.

This is fantastic news, thanks for your hard work on this plugin as always! Mac development is a serious pain sometimes so this is a huge help ❤️
