### ISSUE TITLE
Need to use the landmark value of Pose Estimation

### ISSUE THREAD

**Issue by im-subash** [homuler/MediaPipeUnityPlugin#617]
### Description

I followed your getting started guide and was able to run successfully. 
However, I could not reuse those same for getting landmarks in pose estimation. 
I was able to get the landmark value for the official solution of face mesh but not for anything else. 
The normal scripts and official solution code(in tutorial folder) looks way different, 

Can you please help us with this issue on how easily we can get the points.

I'm able to print the pose estimation points, but I could not use it(could not take the value out and use).
I was able to print from below line only

Following https://github.com/homuler/MediaPipeUnityPlugin/issues/560 I tried below, 
if (runningMode == RunningMode.Sync)
{
    var _ = graphRunner.TryGetNext(out poseDetection, out poseLandmarks, out poseWorldLandmarks, out segmentationMask, out roiFromLandmarks, true);
    Vector2 noseLandmark = new Vector2(poseLandmarks.Landmark[0].X, poseLandmarks.Landmark[0].Y);
     Logger.LogDebug($"__rotation = {noseLandmark}");
}

// i'm not getting any logs from this piece of code. But i get the values inside OnPoseLandmarksOutput, here i could not access the values but could print

private void OnPoseLandmarksOutput(object stream, OutputEventArgs<NormalizedLandmarkList> eventArgs)
{
            _poseLandmarksAnnotationController.DrawLater(eventArgs.value);
            Logger.LogDebug($" output value {eventArgs.value}");
}

**Comment by homuler** [comment]
> here i could not access the values but could print

You can print the value because you can access it, can't you?
Note that you cannot call some Unity APIs from a thread other than the main thread (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Advanced-Topics#unityengineunityexception--can-only-be-called-from-the-main-thread).
