### ISSUE TITLE
How can I access the face landmark raw data?

### ISSUE THREAD

**Issue by Shariy** [homuler/MediaPipeUnityPlugin#619]
### Plugin Version or Commit ID

0.8.10

### Unity Version

2021.3.3f1

### Your Host OS

Window10

### Target Platform

UnityEditor, Windows Standalone

### Description

I succeeded in running the Face Mesh example in Unity by following the installation guide.

It was confirmed that face detection and landmarks (green points) were rendered using a webcam.

Here I want to get raw data about landmarks.
Which variables contain face landmark data?

**Comment by homuler** [comment]
Please read [the official document](https://google.github.io/mediapipe/solutions/face_mesh.html#output).
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks.

**Comment by Shariy** [comment]
Thanks for the reply!
It helped me a lot.

**Comment by dayowoo** [comment]
@homuler @Shariy 
![image](https://user-images.githubusercontent.com/44601601/183634334-f53ca587-3581-4b3c-a13e-1304828bd635.png)
![image](https://user-images.githubusercontent.com/44601601/183634479-ac29ec7f-86f2-46dc-9f66-de575c089623.png)

Hello, I would like to printed the facemsh landmark data. 
I modified the FaceMeshSolution.cs file.
How should I fix it? I looked at similar issues and tutorials, but it is difficult..
Thank you.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks.

> ```cs
>           if (multiFaceLandmarks != null && multiFaceLandmarks.Count > 0)
>           {
>             foreach (var landmarks in multiFaceLandmarks)
>             {
>               // top of the head
>               var topOfHead = landmarks.Landmark[10];
>               Debug.Log($"Unity Local Coordinates: {screenRect.GetPoint(topOfHead)}, Image Coordinates: {topOfHead}");
>             }
>           }
> ```

You're outputting `List<NormalizedLandmarkList>`, that's why the details are not shown.
Instead, output `NormalizedLandmarkList` or `NormalizedLandmark` (`NormalizedLandmarkList#Landmark[]`).

**Comment by dayowoo** [comment]
Thank you for your answer.

I want to know each key value name and coordinate value such as eyes, nose, and mouth in the face mesh. 
I printed out the landmark, and it seems toto be the location value of the face.
Did I understand correctly? Thank you.

**Comment by dayowoo** [comment]
I hope that the values of the eyebrow coordinates are the same regardless of the location of the camera when I am expressionless. 
(This is because the values of the eyebrow coordinates in the face are the same.) 
Do I need to implement a new code or is it already implemented? 
Please give me some advice. Thank you.

**Comment by bbq82828** [comment]
> 同步運行時，它們設置為`multiFaceLandmraks`.
> 
> https://github.com/homuler/MediaPipeUnityPlugin/blob/4302f4a174404ce5fff65fa2ce219ed71f8b9094/Assets/MediaPipeUnity/Samples/Scenes/Face%20Mesh/FaceMeshSolution.cs#L69
> 
> 當異步運行時，它們通過回調參數 ( `eventArgs`) 傳遞。
> 
> https://github.com/homuler/MediaPipeUnityPlugin/blob/4302f4a174404ce5fff65fa2ce219ed71f8b9094/Assets/MediaPipeUnity/Samples/Scenes/Face%20Mesh/FaceMeshSolution.cs#L93-L96

Sorry, I have a question. I use debug to read eventArgs.value and read the following data
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/56858145/185537064-c5d5383d-0748-4a8e-b1a8-cdfd04d0398b.png">
