### ISSUE TITLE
Unity scripts errors

### ISSUE THREAD

**Issue by Emad-Eldeen** [homuler/MediaPipeUnityPlugin#62]
Hello,

I did each and every step for the installation and configuration. However, opening the project in Unity, I am getting errors in the scripts. Did I miss something here? 

Thanks
![image](https://user-images.githubusercontent.com/46440916/108108794-60b55f00-7091-11eb-94f7-92e7b5b97cad.png)

**Comment by homuler** [comment]
Did you run `make install`?

**Comment by Emad-Eldeen** [comment]
This is a snapshot of the make process 
![image](https://user-images.githubusercontent.com/46440916/108162730-ff6fa900-70ed-11eb-812a-9ea439958b18.png)

**Comment by homuler** [comment]
I'd like to know your environments (OS and etc...).

And apparently `bazel` failed because of permission problems.
Will you tell me the output of the below commands?
```sh
which bazel
ls -alh C/
```

**Comment by Emad-Eldeen** [comment]
I am using the docker image from mediapipe githuib
[https://github.com/google/mediapipe/blob/master/Dockerfile](url)

os: ubuntu:18.04
bazel: BAZEL_VERSION=3.4.1

**Comment by homuler** [comment]
Well, I'd rather like to know the owner of `C/bazel-*` (I suspect `root` owns them), but I see.

You should have changed the Dockerfile or at least run commands not written in the [README](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/README.md), and without knowing the exact commands or operations you have done, I can't help you.

**Comment by Emad-Eldeen** [comment]
does this output help?
![image](https://user-images.githubusercontent.com/46440916/108311472-5a200800-71b5-11eb-956a-a432524063ce.png)

ps: I also run the make && make install as root user and it did not work

**Comment by homuler** [comment]
> You should have changed the Dockerfile or at least run commands not written in the README, and without knowing the exact commands or operations you have done, I can't help you.

As I mentioned earlier, I don't know what you have done so far.
If you are using a Docker image, you should have built that image, started the container and run some commands in it (and other commands on the host machine).
I'd like to know **exact** commands you have executed to do so, but I can't infer them from the information thus far.

Please tell me the **exact file** you use to build your Docker image (if you have changed https://github.com/google/mediapipe/blob/master/Dockerfile in some way) and clarify what commands you run in **Docker container** (e.g. `make && make install`, etc...) and what commands you run on **your host machine** (e.g. `git clone`, etc...).

**Comment by Emad-Eldeen** [comment]
Hello 

I started again from the beginning. These are the full set of commands I used:

```
Mediapipe and Hello World:
C:\Users\emadh\Desktop\test>git clone https://github.com/google/mediapipe.git
C:\Users\emadh\Desktop\test>cd mediapipe
C:\Users\emadh\Desktop\test\mediapipe>docker build --tag=mediapipetest .
C:\Users\emadh\Desktop\test\mediapipe>docker run -it --name mediapipetest mediapipetest
root@df7052de91f2:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
...
I20210221 09:43:43.822494    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822587    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822654    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822700    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822748    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822798    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822846    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822892    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822940    11 hello_world.cc:56] Hello World!
I20210221 09:43:43.822980    11 hello_world.cc:56] Hello World!

.NET:
root@df7052de91f2:~# wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
root@df7052de91f2:~# dpkg -i packages-microsoft-prod.deb
root@df7052de91f2:~# apt-get update
root@df7052de91f2:~# apt-get install -y aspnetcore-runtime-2.1
root@df7052de91f2:~# apt-get install -y dotnet-sdk-3.1

MediapipeUnityPlugin:
root@df7052de91f2:~# pip3 install numpy --user
root@df7052de91f2:~# git clone https://github.com/homuler/MediaPipeUnityPlugin.git
edited MediaPipeUnityPlugin/C/third_party/opencv_linux.BUILD as follows:
	cc_library(
    name = "opencv",
    srcs = glob(
        [
            "lib/x86_64-linux-gnu/libopencv_core.so",
            "lib/x86_64-linux-gnu/libopencv_calib3d.so",
            "lib/x86_64-linux-gnu/libopencv_features2d.so",
            "lib/x86_64-linux-gnu/libopencv_highgui.so",
            "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
            "lib/x86_64-linux-gnu/libopencv_imgproc.so",
            "lib/x86_64-linux-gnu/libopencv_video.so",
            "lib/x86_64-linux-gnu/libopencv_videoio.so",
        ],
    ),
    ...
	)
root@df7052de91f2:~# make cpu && make install
```

Building the project passed without any errors. I didnt get the previous errors. What I am getting now is 'DllNotFoundException: mediapipe_c' in Unity. I made sure that I have the right path for opencv.
ps: I built the project in the docker container and then copied it and ran it in Unity on windows. I think this should not be a problem.

**Comment by homuler** [comment]
> I built the project in the docker container and then copied it and ran it in Unity on windows. I think this should not be a problem.

Well, in fact it's the problem (native libraries don't work on different architectures). If it were not a problem, you would not have needed WSL or VM in the first place.
If you'd like to run it on Windows, please build it on Windows.

**Comment by Emad-Eldeen** [comment]
I copied the built project to ubuntu and it worked normally.
Thank you for the support

**Comment by Emad-Eldeen** [comment]
I am trying again to build the project again now with the exact same steps, but I am getting the following error in make cpu
```
ERROR: /root/.cache/bazel/_bazel_root/de3c76406078cb2218dae867db59221a/external/com_google_mediapipe/mediapipe/calculators/tensor/BUILD:599:11: C++ compilation of rule '@com_google_mediapipe//mediapipe/calculators/tensor:image_to_tensor_converter_opencv' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:106:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
INFO: Elapsed time: 50.849s, Critical Path: 50.01s
INFO: 499 processes: 499 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Makefile:46: recipe for target 'cpu' failed
make: *** [cpu] Error 1
root@c09a74d83417:/MediaPipeUnityPlugin#
```
I also tried to install a standalone ubuntu and went throw all the steps and got the same error.
What do you think the problem is? could it be that something has changed since then?
