### ISSUE TITLE
win11+python3.10.5+opencv4.6.0 Error

### ISSUE THREAD

**Issue by sunrui19941128** [homuler/MediaPipeUnityPlugin#622]
### Plugin Version or Commit ID

0.8.10

### Unity Version

2021.3.3f1

### Your Host OS

win11PRO

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

VisualStudioEnterprise 2022 17.2.4

### Command Sequences

python build.py build --desktop cpu -v

### Log

python build.py build --desktop cpu -v

ERROR: An error occurred during the fetch of repository 'opencv':
   Traceback (most recent call last):
        File "C:/_bzl/4vetja6y/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: Expected a file with a .zip, .jar, .war, .aar, .tar, .tar.gz, .tgz, .tar.xz, .txz, .tar.zst, .tzst, .tar.bz2, .ar or .deb suffix (got C:/_bzl/4vetja6y/external/opencv/temp11992497702644230897/opencv-4.6.0)
ERROR: D:/gitproject/mediapipeunityplugin/WORKSPACE:245:13: fetching http_archive rule //external:opencv: Traceback (most recent call last):
        File "C:/_bzl/4vetja6y/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: Expected a file with a .zip, .jar, .war, .aar, .tar, .tar.gz, .tgz, .tar.xz, .txz, .tar.zst, .tzst, .tar.bz2, .ar or .deb suffix (got C:/_bzl/4vetja6y/external/opencv/temp11992497702644230897/opencv-4.6.0)

**Comment by homuler** [comment]
You should have modified the `WORKSPACE` file (not mentioned here, though), and your error is caused by that change.
So review the change.
