### ISSUE TITLE
'opencv2/core/version.hpp' file not found on Mac

### ISSUE THREAD

**Issue by inaPhy** [homuler/MediaPipeUnityPlugin#626]
### Plugin Version or Commit ID

v0.8.10

### Unity Version

 2021.3.3f1

### Your Host OS

macOS Monterey 12.4

### Target Platform

iOS

### [iOS Only] XCode Version

13.4.1

### Command Sequences

ビルドを試みました
cd MediaPipeUnityPlugin
python build.py build --desktop cpu --android arm64 --ios arm64 -vv

以下のログのようなエラーが出て成功しません

### Log

1 warning generated.
INFO: From Linking external/com_google_absl/absl/flags/libflag.a [for host]:
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: bazel-out/host/bin/external/com_google_absl/absl/flags/libflag.a the table of contents is empty (no object file members in the library define global symbols)
ERROR: /private/var/tmp/_bazel_user-name/46416640a65851106d7df279baa01a04/external/com_google_mediapipe/mediapipe/util/BUILD:146:11: Compiling mediapipe/util/annotation_renderer.cc failed: (Aborted): wrapped_clang_pp failed: error executing command 
  (cd /private/var/tmp/_bazel_user-name/46416640a65851106d7df279baa01a04/sandbox/darwin-sandbox/1349/execroot/mediapipe_api && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.3 \
    PATH='/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/user-name/bin' \
    XCODE_VERSION_OVERRIDE=13.4.0.13F17a \
    ZERO_AR_DATE=1 \
  external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-std=c++11' 'DEBUG_PREFIX_MAP_PWD=.' -iquote external/com_google_mediapipe -iquote bazel-out/darwin-opt/bin/external/com_google_mediapipe -iquote external/com_google_protobuf -iquote bazel-out/darwin-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/darwin-opt/bin/external/zlib -iquote external/com_github_glog_glog -iquote bazel-out/darwin-opt/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/darwin-opt/bin/external/com_github_gflags_gflags -iquote external/com_google_absl -iquote bazel-out/darwin-opt/bin/external/com_google_absl -iquote external/macos_opencv -iquote bazel-out/darwin-opt/bin/external/macos_opencv -Ibazel-out/darwin-opt/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/darwin-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/darwin-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/darwin-opt/bin/external/zlib -isystem external/macos_opencv/opt/opencv@3/include -isystem bazel-out/darwin-opt/bin/external/macos_opencv/opt/opencv@3/include -MD -MF bazel-out/darwin-opt/bin/external/com_google_mediapipe/mediapipe/util/_objs/annotation_renderer/annotation_renderer.d '-DMEDIAPIPE_DISABLE_GPU=1' '-frandom-seed=bazel-out/darwin-opt/bin/external/com_google_mediapipe/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=12.3' -no-canonical-prefixes -pthread -w '-std=c++17' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target x86_64-apple-macosx -c external/com_google_mediapipe/mediapipe/util/annotation_renderer.cc -o bazel-out/darwin-opt/bin/external/com_google_mediapipe/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o)
#Configuration: 052e0b41cc26c8db217a0262e08c4196e8fdbce5be4f54e78fc17ef208f5b008
#Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_mediapipe/mediapipe/util/annotation_renderer.cc:15:
In file included from external/com_google_mediapipe/mediapipe/util/annotation_renderer.h:20:
external/com_google_mediapipe/mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: 'opencv2/core/version.hpp' file not found
#include <opencv2/core/version.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 115.761s, Critical Path: 96.05s
INFO: 1144 processes: 143 internal, 1001 darwin-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/user-name/MediaPipeUnityPlugin/build.py", line 450, in <module>
    Argument().command().run()
  File "/Users/user-name/MediaPipeUnityPlugin/build.py", line 138, in run
    self._run_command(self._build_desktop_commands())
  File "/Users/user-name/MediaPipeUnityPlugin/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

### Additional Context

opencvは以下の二つが混在しています
opencv@3だけにしても同様のエラーが出ました
opencv@2 2.4.13.7_12.reinstall
opencv@3 3.4.16_3

チェックしたこと
１，version.hppファイルは存在します
２，パスを確認しました→通っていると思います
　pkg-config --cflags opencv
　→ -I/usr/local/Cellar/opencv@3/3.4.16_3/include/opencv -I/usr/local/Cellar/opencv@3/3.4.16_3/include
３，opencvを再インストールして確かめてみましたが同じエラーが出ました
４，下記のアドレス先の方法も試しましたが同様のエラー出ました
https://teratail.com/questions/278733

１ヶ月以上悩まされています
なにとぞお力を貸してください

**Comment by homuler** [comment]
> ### Plugin Version or Commit ID
> v 0.8.10

Enter the plugin version, not the MediaPipe version.

If you're using v0.10.0, there's a bug so pull the latest commit (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/591#issuecomment-1136595805)

**Comment by inaPhy** [comment]
誠にありがとうございます
正直申しますと１ヶ月どころか２ヶ月ここで止まっておりました
やっとUnity上で実行できました。

iOS上で行いたい場合は，
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#intel-mac
の６番をやって

ビルドコマンドは
python build.py build --desktop cpu  --ios arm64 -vv --opencv cmake -vv
でよろしいいですか？

**Comment by homuler** [comment]
In English, please.
