### ISSUE TITLE
reference custom tflite model from inside graph definition

### ISSUE THREAD

**Issue by mgarbade** [homuler/MediaPipeUnityPlugin#632]
### Plugin Version or Commit ID

6b8c6743f23539f7604e74dc260b01e0f58f1707

### Unity Version

2020.3.26f1

### Your Host OS

Windows 10 Pro

### Target Platform

UnityEditor

### Description

I'd like to adapt the HelloWorld Scene with a graph that:
- accepts a simple float array as input
- converts the array into a tflite tensor
- runs a tflite model
- returns the output of the network (likewise a float array)

While this little toy example runs fine in mediapipe with some example driver code in c++, I cannot get it working in MediaPipeUnityPlugin.  

In C++ I just had to specify a relative path to the tflite model in the `TfLiteInferenceCalculator` section of the graph definition

`model_path: ""mediapipe/models/my_model.tflite""`

Obviously this line has to be changed when switching to Unity, but how?  
What are the exact steps to reference the tflite model correctly?  

### Code to Reproduce the issue

The graph definition looks like this:

```cs
var configText = @"
        input_stream: ""MATRIX:in""
        output_stream: ""FLOATS:out""

        node 
        {
          calculator: ""TfLiteConverterCalculator""
          input_stream: ""MATRIX:in""
          output_stream: ""TENSORS:image_tensor""
          options: 
          {
              [mediapipe.TfLiteConverterCalculatorOptions.ext]
              {
              zero_center: false
              }
          }
        }

        node 
        {
          calculator: ""TfLiteInferenceCalculator""
          input_stream: ""TENSORS:image_tensor""
          output_stream: ""TENSORS:tensor_features""
          options: 
          {
            [mediapipe.TfLiteInferenceCalculatorOptions.ext] 
            {
              model_path: ""mediapipe/models/my_model.tflite""
            }
          }
        }

        node 
        {
          calculator: ""TfLiteTensorsToFloatsCalculator""
          input_stream: ""TENSORS:tensor_features""
          output_stream: ""FLOATS:out""
        }
      ";
```

Here is the (not yet tested) driver code of the above graph:

```cs
      var graph = new CalculatorGraph(configText);
      var poller = graph.AddOutputStreamPoller<float[]>("out").Value();

      // load tflite model from assets
     // ... (not sure what to do here)

      Debug.Log("StartRun");
      graph.StartRun().AssertOk();
      for (var i = 0; i < 10; i++)
      {
        var floatArray = new float[6] { 0, 1, 2, 3, 4, 5 };
        var input = new FloatArrayPacket(floatArray, new Timestamp(i));
        graph.AddPacketToInputStream("in", input).AssertOk();
      }
      graph.CloseInputStream("in").AssertOk();

      Debug.Log("Poll output");
      var output = new FloatArrayPacket();
      while (poller.Next(output))
      {
        Debug.Log(output.Get());
      }


      graph.WaitUntilDone().AssertOk();
      graph.Dispose();

      Debug.Log("Done");
    }
```

### Additional Context

I tried 
- to rename `my_model.tflite` to StreamingAssets folder (where apparantly all other tflite model reside) and rename it to `my_model.bytes` but it's still unclear to me how to reference it from there in the graph definition.

**Comment by mgarbade** [comment]
Thanks for the quick reply! This is useful information for a higher level understanding of the Plugin.
Meanwhile I found a [hack](https://github.com/aisportscoach/MediaPipeUnityPlugin/blob/run_AR_graph_from_Unity/Assets/MediaPipeUnity/Samples/Scenes/Tutorial/HelloWorld.cs#L95-L128) to load the model at least when running the graph in UnityEditor.   

It appears that my next problem is that the graph expects an `Eigen::Matrix` rather than a vector of floats. 

```
MediaPipeException: INVALID_ARGUMENT: Graph has errors: 
Packet type mismatch on calculator outputting to stream "in": The Packet stores "float [0]", but "class Eigen::Matrix<float,-1,-1,0,-1,-1>" was requested.
Mediapipe.Status.AssertOk () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:48)
Mediapipe.Unity.HelloWorld.Start () (at Assets/MediaPipeUnity/Samples/Scenes/Tutorial/HelloWorld.cs:72)
```
So far I did not figure out to `Eigen::Matrix` as input package, but I guess this is for a different issue...

**Comment by homuler** [comment]
To pass `Eigen::Matrix` to MediaPipe, we need a `Packet<Eigen::Matrix>` class (in C#), but there are no such classes currently.
cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#packett

So you need to implement it (PR is welcome!).
It may be convenient to implement a function that converts [`mediapipe::MatrixData`](https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/framework/formats/matrix_data.proto) (in practice, it should be serialized to `const char*`) into `mediapipe::Packet<Eigen::Matrix>` since it's easy to handle protocol buffer classes in C# and it seems that `Eigen::Matrix` can be derived from `mediapipe::MatrixData` easily with `mediapipe::MatrixFromMatrixDataProto`.

I think an example from `Anchor3dVectorPacket` would be helpful in this case (you may want to implement `MpReturnCode mp__MakeMatrixPacket__PKc_i(const char* matrix_data, int size, mediapipe::Packet** packet_out)`).
https://github.com/homuler/MediaPipeUnityPlugin/blob/d70c6f32c61ef4a199f04c580e75337038e746be/mediapipe_api/graphs/instant_motion_tracking/calculators/transformations.cc#L11-L32
https://github.com/homuler/MediaPipeUnityPlugin/blob/d70c6f32c61ef4a199f04c580e75337038e746be/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/Anchor3dVectorPacket.cs#L22-L33

You can deserialize `const char*` to the corresponding protocol buffer class.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d70c6f32c61ef4a199f04c580e75337038e746be/mediapipe_api/framework/calculator_graph.cc#L27-L33
https://github.com/homuler/MediaPipeUnityPlugin/blob/d70c6f32c61ef4a199f04c580e75337038e746be/mediapipe_api/framework/calculator_graph.cc#L11-L16

**Comment by homuler** [comment]
> - then I would need one more CalculatorNode in the graph that converts my custom Protobuf matrix into an Eigen::Matrix !?
>    - in that case it might be easier to write a calculator that converts the already existing FloatArrayPacket into an Eigen::Matrix

No.
The error you reported in https://github.com/homuler/MediaPipeUnityPlugin/issues/632#issuecomment-1171430852 occurred because you sent a `FloatArrayPacket` to the `in` stream. By implementing `MatrixPacket : Packet<MatrixData>` (in C#) that manages `mediapipe::Packet` which holds `Eigen::Matrix` internally (in C++), it can be resolved (note that `mediapipe` is a namespace used in C++ and `Mediapipe` is a namespace used in C#).

> While I can create a `MatrixData matrix = new MatrixData();` object, I don't know how to 'fill it' with data. The only constructor I can find expects an already existing `MatrixData` object and clones data from there.

You can use setters to set values.
See [the official protocol buffer document](https://developers.google.com/protocol-buffers/docs/csharptutorial) for more details.

To pass `MatrixData` to the Unmanaged Code, serialize it like this.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d70c6f32c61ef4a199f04c580e75337038e746be/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraph.cs#L31

> Can all this be done in C#?

No. `MpReturnCode mp__MakeMatrixPacket__PKc_i(const char* matrix_data, int size, mediapipe::Packet** packet_out))` must be implemented in C++.
This function takes `matrix_data`, which is a serialized `MatrixData` (`byte[]` in C#).
In that function, I think you can convert `matrix_data` into `Eigen::Matrix` using [`mediapipe::MatrixFromMatrixDataProto`](https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/framework/formats/matrix.h#L39), then build `mediapipe::Packet` that holds `Eigen::Matrix` insternally.
The pointer to the built `mediapipe::Packet` needs to be set to `packet_out`.

**Comment by mgarbade** [comment]
So I will
1. add a set of C++ functions which will be exposed to C# similar to 
      - medipipe_api/.../transformations.cc, transformations.h 
      - for example a pair: 
        - medipipe_api/.../matrix_frame.cc, matrix_frame.h 
        - the minimum required functions in those files are similar to those in `transformations.cc` (?), i.e. :
```
MpReturnCode mp__MakeAnchor3dVectorPacket__PA_i(const mediapipe::Anchor3d* value, int size, mediapipe::Packet** packet_out)`
MpReturnCode mp__MakeAnchor3dVectorPacket_At__PA_i_Rt(const mediapipe::Anchor3d* value, int size, mediapipe::Timestamp* timestamp, mediapipe::Packet** packet_out)
```
not sure what `__PA_i` an `_At__PA_i_Rt` stands for (?), but it seems the first function creates a packet without timestamp and the second one with timestamp (which is propably what I need)

2. I will create a function to send data from C# to C++
     - for example (as you mentioned) a function 
```
 MpReturnCode mp__MakeMatrixPacket__PKc_i(const char* matrix_data, int size, mediapipe::Packet** packet_out))
```
-> wouldn't it be better / easier to send some kind of float array rather than const char* ? should be faster and easier for conversion or am I getting something wrong?

**Comment by homuler** [comment]
> not sure what `__PA_i` an `_At__PA_i_Rt` stands for (?), 

When porting, I make it a habit to add a suffix that is similar to the C++ mangling rules to distinguish functions with the same name (e.g. `mediapipe::CalculatorGraph()` -> `mp_CalculatorGraph__`, `mediapipe::CalculatorGraph(const CalculatorGraphConfig& config)` -> `mp_CalculatorGraph__PKc_i`).

I've not defined the rule strictly, but in this case,
- `MakeAnchor3dVectorPacket` represents `mediapipe::MakePacket<Anchor3d>`
- `MakeAnchor3dVectorPacket_At` represents `mediapipe::MakePacket<Anchor3d>.At(mediapipe::Timestamp)`
- `PA` represents a pointer to `Anchor3d` (the type of `value`)
- `i` reprensets `int` (the type of `size`, `i`)
- `Rt` represents a reference to `Timestamp` (the type of `timestamp`)

> wouldn't it be better / easier to send some kind of float array rather than const char* ? should be faster and easier for conversion or am I getting something wrong?

Maybe.

To initialize a `MatrixPacket`, you need to pass a value that represents `Eigen::Matrix`, and I thought `Mediapipe.MatrixData` would be convenient.
If you prefer `float[]` or `float[][]`, it would be OK.

Which one is easier would depend on the person. Assuming `mediapipe::MatrixFromMatrixDataProto`, I thought `Eigen::Matrix` could be handled more easily than `float[]`.
Probably `float[]` version would be faster, but `const char*` is actually a protocol buffer's serialized data, so I don't think `float[]` is clearly faster than the other.

P.S. You don't need to implement `mp__MakeMatrixPacket__PKc_i` in C#.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d70c6f32c61ef4a199f04c580e75337038e746be/Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Graphs/InstantMotionTracking_Unsafe.cs#L14-L18

**Comment by mgarbade** [comment]
regarding the second part of my question "how to fill the MatrixData object"  I guess I found the answer. It seem like the equivalent of this vector

```
var floatArray = new float[6] { 0, 1, 2, 3, 4, 5 };
```

is a MatrixData object filled via `.PacketData.Add` like this:

```
var matrix = new MatrixData();
matrix.PackedData.Add(0);
matrix.PackedData.Add(1);
matrix.PackedData.Add(2);
matrix.PackedData.Add(3);
matrix.PackedData.Add(4);
matrix.PackedData.Add(5);
```

**Comment by mgarbade** [comment]
Just in case you are interested, this is [work in progress](https://github.com/aisportscoach/MediaPipeUnityPlugin/commit/3324ef403244774229566ee728d7ac91c0a208b6)

**Comment by nenenkosi** [comment]
@mgarbade the link is giving me a 404 page I can’t access it I think the repo is private 

> Just in case you are interested, this is [work in progress](https://github.com/aisportscoach/MediaPipeUnityPlugin/commit/3324ef403244774229566ee728d7ac91c0a208b6)

**Comment by mgarbade** [comment]
ups, sorry. I just repaired the link. it should work now

**Comment by mgarbade** [comment]
It seems like I cannot convert a `const char *` into a MatrixData object. I assume that I'm doing the exact same as [this snippet] (https://github.com/google/mediapipe/blob/e6c19885c6d3c6f410c730952aeed2852790d306/mediapipe/examples/desktop/youtube8m/extract_yt8m_features.cc#L66-L77) from the official mediapipe repo. 

However in my case it only compiles if I use `mediapipe::file::GetContents` to write the serialized matrix data into a string:

```
MpReturnCode mp__MakeMatrixPacket__PKc_i(const char* matrix_data_serialized, int size, mediapipe::Packet** packet_out) {
  TRY
    mediapipe::Matrix matrix;

    // convert matrix data from char into mediapipe::MatrixData
    std::string content;
    mediapipe::MatrixData matrix_data;
    mediapipe::file::GetContents(matrix_data_serialized, &content);  // <-- using this function feels wrong!
    CHECK(matrix_data.ParseFromString(content));

    // fill matrix with data from matrix_data_serialized
    mediapipe::MatrixFromMatrixDataProto(matrix_data, &matrix);

    *packet_out = new mediapipe::Packet{mediapipe::MakePacket<mediapipe::Matrix>(matrix)};
    RETURN_CODE(MpReturnCode::Success);
  CATCH_EXCEPTION
}
```

As I said: it compiles, next will be testing. Meanwhile: Any feedback is welcome!
that "hack" was inspired by looking at `calculator_graph.cc`:

```
MpReturnCode mp_CalculatorGraph__PKc_i(const char* serialized_config, int size, mediapipe::CalculatorGraph** graph_out) {
  TRY_ALL
    auto config = ParseFromStringAsCalculatorGraphConfig(serialized_config, size);
    *graph_out = new mediapipe::CalculatorGraph(config);
    RETURN_CODE(MpReturnCode::Success);
  CATCH_ALL
}
```

**Comment by mgarbade** [comment]
me slowly moving forward. Meanwhile I've written some [C# functions to paste data](https://github.com/mgarbade/MediaPipeUnityPlugin/commit/b314439c3c30d56f3e2d0179af6ca83c644b3198) to the graph, but I'm still getting an Error:

```
MediaPipeException: INVALID_ARGUMENT: Graph has errors: 
Calculator::Open() for node "TfLiteInferenceCalculator" failed: ; Can't find file: mediapipe/models/adder_model_single_input_2x3.tflite
Mediapipe.Status.AssertOk () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:147)
Mediapipe.Unity.HelloWorld.Start () (at Assets/MediaPipeUnity/Tutorial/Hello World/HelloWorld.cs:94)

```
Though it looks like the conversion of my input data didn't crash. The data itself might be corrupt though. Is there a way to debug / step into the C++ code while running Unity?

**Comment by homuler** [comment]
> ```cc
> // convert matrix data from char into mediapipe::MatrixData
> std::string content;
> mediapipe::MatrixData matrix_data;
> mediapipe::file::GetContents(matrix_data_serialized, &content);  // <-- using this function feels wrong!
> CHECK(matrix_data.ParseFromString(content));
> ```

See
https://github.com/homuler/MediaPipeUnityPlugin/blob/a48603aa39ccee03d4ec158fd85778432aac9366/mediapipe_api/framework/calculator_graph.cc#L12-L13

What you should do here is convert `const char*` to `const std::string` and gives it to `ParseFromString`.
Although `mediapipe::file::GetContents` return `std::string`, as its name implies, it doesn't _convert_ it to `std::string` but _reads the contents_ from the given path.
`matrix_data_serialized` is not a file path (it is rather `content`), so it should always fail.

```cc
mediapipe::MatrixData matrix_data;
CHECK(matrix_data.ParseFromString(std::string(matrix_data_serialized, size)));
```

> Is there a way to debug / step into the C++ code while running Unity?

Please google it.

**Comment by mgarbade** [comment]
Found [a solution](https://stackoverflow.com/questions/72914814/visual-studio-code-attach-to-unity-process-for-debugging-c-based-dll/72942205#72942205) how to hit on C++ breakpoints inside the mediapipe_c.dll

That said, it seems that my code is breaking at 

```
    std::string content;
    mediapipe::MatrixData matrix_data;
    CHECK(matrix_data.ParseFromString(std::string(matrix_data_serialized, size)));

    // fill matrix with data from matrix_data_serialized
    mediapipe::MatrixFromMatrixDataProto(matrix_data, &matrix);  // <- THIS LINE
```

From what I can I see so far it looks like the way I'm putting data into "MatrixData" is wrong. The parser cannot infer any matrix shape (rows, cols) from the byte string.

Will look further into this tomorrow.

**Comment by mgarbade** [comment]
data input is working now. I simply had to manually [specify the shape of the input data](https://github.com/mgarbade/MediaPipeUnityPlugin/commit/101d954bc41c3a0d01015b8fce78449207e25677):
```
var matrix = new MatrixData();
matrix.PackedData.Add(0);
matrix.PackedData.Add(1);
matrix.PackedData.Add(2);
matrix.PackedData.Add(3);
matrix.PackedData.Add(4);
matrix.PackedData.Add(5);

matrix.Rows = 2;
matrix.Cols = 3;
```

Next problem: My graph returns a `vector<float>`, which I'm currently unable to receive.
The current code is crashing Unity:
```
var poller = graph.AddOutputStreamPoller<float[]>("out").Value();
//... 
//start graph
//...
Debug.Log("Poll output");
var output = new FloatArrayPacket();
while (poller.Next(output))  // <-- THIS LINE CAUSES UNITY CRASH
{
  Debug.Log(output.Get());
}
```

I'll keep on digging...

**Comment by homuler** [comment]
`FloatArrayPacket` stores `float[]`, not `std::vector<float>`.
To receive `std::vector<float>`, you need to implement a new Packet class (`FloatVectorPacket`) or a calculator to convert `std::vector<float>` to `float[]`.

**Comment by mgarbade** [comment]
puhh finally I got things working! 😄 🚀 🍻 
thanks a lot for your help @homuler !

I will try to clean the code a bit, feel free to comment the code quality in case you are interested in me creating a pull request out of this

**Comment by mgarbade** [comment]
FYI: I rebased my changes onto the current master. How should I go forward to make a pull request out of this?

- do you want to look at / give some feedback to the commits?
  - are variable names fine?
- should I clean up the commits -> sum up everything into two commits?
  -  one for C# 
  -  and one for C++ part)
- automatic tests seem to be failing, do I need to write some tests?
- what about binary files? 
  - I have a tiny tflite model (just adds "+1" to the input matrix)
  - should I commit that as well to make the matrix classification demo runnable?

**Comment by homuler** [comment]
> - do you want to look at / give some feedback to the commits?
>    - are variable names fine?

If you send me a PR, I'll review it.

> - should I clean up the commits

Please do it in a way that you think is best.

> - automatic tests seem to be failing, do I need to write some tests?

By default, tests will fail in a forked repository, so never mind.
It is preferable to write test code for the source code under `Packages` (e.g. https://github.com/homuler/MediaPipeUnityPlugin/blob/6efa5e1b75b7c6aa487254ade15fe7cd49fc6842/Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/BoolPacketTest.cs).

> should I commit that as well to make the matrix classification demo runnable?

No, you don't need to do so.
