### ISSUE TITLE
Docker build files not present

### ISSUE THREAD

**Issue by StewieHF** [homuler/MediaPipeUnityPlugin#633]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.2.11f1

### Your Host OS

Windows 10 Pro

### Target Platform

Windows Standalone

### Command Sequences

docker build -t mediapipe_unity:windows . -f docker/windows/x86_64/Dockerfile

docker run --cpus=16 --memory=32g ^
    --mount type=bind,src=%CD%\Packages,dst=C:\mediapipe\Packages ^
    --mount type=bind,src=%CD%\Assets,dst=C:\mediapipe\Assets ^
    -it mediapipe_unity:windows
    
python build.py build --desktop cpu --opencv cmake -vv

### Log

Target //mediapipe_api:mediapipe_desktop up-to-date:
  bazel-bin/mediapipe_api/mediapipe_desktop.zip
INFO: Elapsed time: 1320.722s, Critical Path: 1177.66s
INFO: 3669 processes: 1129 internal, 2540 local.
INFO: Build completed successfully, 3669 total actions
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_desktop.zip' to 'build\Plugins'...
INFO (build.py): Built native libraries for Desktop
INFO (build.py): Installing built resources...
DEBUG (build.py): Copying 'build' to 'Packages\com.github.homuler.mediapipe\Runtime' recursively...
DEBUG (build.py): Running `cp -r build/* Packages\com.github.homuler.mediapipe\Runtime`
INFO (build.py): Installed

### Additional Context

I have built the files on Windows via Docker twice now and its completed twice and at the end i see that it says its been successful and that its recursively copied the build folder to Packages\com.github.homuler\Runtime

yet there is nothing in that folder, its been bound and i saw the Assets folder update with files added, but no build files the way it did on the Mac side of things

**Comment by homuler** [comment]
> yet there is nothing in that folder, its been bound and i saw the Assets folder update with files added,

If the files under the `Assets` folder were copied correctly, but those under the `Packages` folder were not, maybe there's a problem with the `Packages` folder on your host machine.

Will you try the following steps?
1. Stop all the containers.
2. Remove all the stopped containers.
3. Start a new Docker container and build the plugin.

Note that you don't need to remove and build the Docker _image_ again.

**Comment by StewieHF** [comment]
Ah right the Packages folder is present too, maybe i have misunderstood how it builds on the PC as on the Mac i got a build folder with DLLs in etc, and i was unsure what the build files would be on the PC side of things as i need to combine the runtimes

**Comment by homuler** [comment]
> Ah right the Packages folder is present too

So is it resolved?

**Comment by StewieHF** [comment]
Ah think i have found it, in Runtime/Plugins, i can see the DLLs in there now, thanks ill give it a test
