### ISSUE TITLE
is there way to use a mix of iris detection and face detection landmark

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#636]
### Plugin Version or Commit ID

v0.01

### Unity Version

2020.1.3

### Your Host OS

Windows 10

### Target Platform

UnityEditor, Android, iOS

### Description

the face detection landmark is very high quality without any vibrate
but the iris detection is good just for eye landmarks and around of it is poor quality
i looking for a way to mix them

if mixing is posible
can i mix hair detection to other soloutions ?

**Comment by homuler** [comment]
First, if you want to know how to customize `CalculatorGraph`, please ask in the MediaPipe community.
> If you don't know how to use MediaPipe itself, please ask it in the official community.

> the face detection landmark is very high quality without any vibrate
but the iris detection is good just for eye landmarks and around of it is poor quality
i looking for a way to mix them

Which solution (or code) are you talking about?
Please speak in the terms of [the official documentation](https://google.github.io/mediapipe/solutions/solutions.html) (e.g. Face Detection, Face Mesh, Iris).

> i looking for a way to mix them

What do you mean by "mix them"?
Please explain using screenshots.

> can i mix hair detection to other soloutions ?

Do you mean Hair Segmentation?
Please tell us more specifically what you would like to do.

**Comment by ehsanwwe** [comment]
tanx for replay me

**Comment by homuler** [comment]
What would you like to achieve by doing so?
I see little difference in what these two solutions do.
Both can return facial and iris landmarks, so I think you don't usually need to _mix_ them.

**Comment by ehsanwwe** [comment]
highest quality of face landmark + current iris landmarks
in the "face mesh" sample scene
if i freeze my head front of the camera , landmarks are fix without jump
if i do it in the "iris traking" sample scene
the landmark of the iris and eye is fix but landmarks of around the face do jumping randomly

**Comment by homuler** [comment]
Will you share the screenshot or video, please? (both of `Face Mesh` and `Iris Tracking`)
And one thing I was wondering, have you noticed that the `Face Mesh` sample can also get iris landmarks?
If you have, why do you prefer the iris landmarks calculated in the `Iris Tracking` Scene than in the `Face Mesh` Scene?

**Comment by ehsanwwe** [comment]
https://user-images.githubusercontent.com/11198455/177171229-2d81a65f-2901-43c2-863b-5e891eb22f1c.mp4

i just use 469 landmarks (so both of them is good for me )

this video captured from Iris tracking
you can see the eyes land mark are fix and when i close eye they will be close
but in my cheek of face we have noise in landmark position

in your facemesh sample everythings is **reverse** :
    when i close my eyes eyes landmarks didn't close good 
    but the cheek landmarks have fix  position without noise

**Comment by amalcty** [comment]
Can you please share the code for using the facemesh?

**Comment by kennyluk123** [comment]
@ehsanwwe

**Comment by homuler** [comment]
close it because the solution is replaced with the Task API.
