### ISSUE TITLE
Getting error while building plugin for Android

### ISSUE THREAD

**Issue by maaz9898** [homuler/MediaPipeUnityPlugin#638]
### Plugin Version or Commit ID

V 0.10

### Unity Version

2021

### Your Host OS

Windows 11 pro

### Target Platform

Windows Standalone, Android

### Command Sequences

python build.py build --android arm64 -vv

### Log

![image](https://user-images.githubusercontent.com/53059467/177060966-dffb339b-b6b8-400d-b105-1e8239fc6ada.png)

**Comment by homuler** [comment]
duplicates #555.
