### ISSUE TITLE
DllNotFoundException: mediapipe_c assembly:<unknown assembly> type:<unknown type> member:(null) Mediapipe.UnsafeNativeMethods..cctor 

### ISSUE THREAD

**Issue by isug** [homuler/MediaPipeUnityPlugin#640]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

macOS

### Target Platform

iOS

### Description

I finished build.py Install with python.
but I run StartScene on Unity Editor, this error appeared.

DllNotFoundException: mediapipe_c assembly:<unknown assembly> type:<unknown type> member:(null)
Mediapipe.UnsafeNativeMethods..cctor () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/UnsafeNativeMethods.cs:29)
Rethrow as TypeInitializationException: The type initializer for 'Mediapipe.UnsafeNativeMethods' threw an exception.
Mediapipe.Protobuf.SetLogHandler (Mediapipe.Protobuf+LogHandler logHandler) (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/Protobuf.cs:16)
Mediapipe.Unity.Bootstrap+<Init>d__16.MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs:44)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Mediapipe.Unity.Bootstrap:OnEnable() (at Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs:36)
\

Maybe, there was no fix information of this problem on macOS at past issue.
How to fix this? Teach me Please.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception.
Make sure that `build.py` finishes successfully.
If you can confirm that, share the output of `build.py`, please.

**Comment by isug** [comment]
Thank you for Your Reply, homuler.

I already finished build.py successfully.
What do I share the output?  Does it means build.py console log? or other file?
Teach me please.
[build_py_20220705a.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9044118/build_py_20220705a.txt)

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception
Did you follow the 5th step?

> 5. When you cannot identify the cause...
If the error occurs on UnityEditor, try loading {lib}mediapipe_c.{so,dylib,dll} on startup.

In your case, try loading `libmediapipe_c.dylib` on startp.

**Comment by isug** [comment]
I already tried loading libmediapipe_c.dylib on startup like attached image.
Is My way right?

<img width="1680" alt="スクリーンショット 2022-07-06 9 57 17" src="https://user-images.githubusercontent.com/1052145/177440996-d0ec28fd-27a3-4cae-8d34-0d7d05c708bf.png">

**Comment by homuler** [comment]
Possibly are you using an M1 Mac?
If so, see https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#m1-mac.
> > :warning: use UnityEditor (Apple silicon) (>= 2021.2.2f1) to open the project.

**Comment by isug** [comment]
I am using Intel Mac.
So, I try with [https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#intel-mac](url)

**Comment by homuler** [comment]
When you check on `Load on startup` and click the `Apply` button, I guess a warning message appeared in your Console Window.
Please share that message (or the screenshot).

**Comment by isug** [comment]
This is message in my console.
Confirm please.

Plugins: Couldn't open /Users/takeshiasai/metadrip/MediaPipeUnityPlugin-master_20220704a/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib, error: dlopen(/Users/takeshiasai/metadrip/MediaPipeUnityPlugin-master_20220704a/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib, 0x0002): Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/Cellar/opencv@3/3.4.16_3/lib/libopencv_imgcodecs.3.4.16.dylib
  Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)Library not loaded: /usr/local/opt/libvpx/lib/libvpx.7.dylib
  Referenced from: /usr/local/Cellar/ffmpeg@4/4.4.2_3/lib/libavcodec.58.134.100.dylib
  Reason: tried: '/usr/local/opt/libvpx/lib/libvpx.7.dylib' (no such file), '/usr/local/lib/libvpx.7.dylib' (no such file), '/usr/lib/libvpx.7.dylib' (no such file)Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /usr/local/Cellar/ffmpeg@4/4.4.2_3/lib/libavformat.58.76.100.dylib
  Reason: tried: '/usr/local/opt/zeromq/lib/libzmq.5.dylib' (no such file), '/usr/local/lib/libzmq.5.dylib' (no such file), '/usr/lib/libzmq.5.dylib' (no such file)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

<img width="1680" alt="スクリーンショット 2022-07-06 11 49 25" src="https://user-images.githubusercontent.com/1052145/177458253-73875853-91cc-47ef-b5ad-80e7b42d49d3.png">

**Comment by homuler** [comment]
It seems that OpenCV is not linked correctly.
Did you build the plugin on another machine?

**Comment by isug** [comment]
I tried OpenCV uninstall and reinstall, and dependent libraries link.
but, not fixed...What do I do? mmm...

**Comment by homuler** [comment]
Has the warning message in the Console Windows changed?

At least, I think you can avoid this error by linking OpenCV statically.
```sh
python build.py build --desktop cpu --opencv cmake -vv
```

**Comment by isug** [comment]
After Trying this command, the problem has fixed!
Thank you very much! homuler!!!!!
