### ISSUE TITLE
Head segmentation in real time on a webcam video?

### ISSUE THREAD

**Issue by chris-hndz** [homuler/MediaPipeUnityPlugin#651]
### Description

Hi, I am looking for a solution to achieve head segmentation (hair with face segmentation) in real time on a webcam video. What do you recommend to achieve this with mediapipe? What segmentation or mediapipe tracking methods would be useful to achieve this?

![HeadSegmentation](https://user-images.githubusercontent.com/6933154/178130272-d81d8c3c-240c-443c-9f01-541f6d7d5bea.jpg)

Thanks in advance!

**Comment by homuler** [comment]
Please ask questions about MediaPipe in the MediaPipe community.
