### ISSUE TITLE
Handlandmark Visibility aways 0 in Holistic tracking

### ISSUE THREAD

**Issue by endink** [homuler/MediaPipeUnityPlugin#652]
### Plugin Version or Commit ID

0.10.1

### Unity Version

2021.3

### Your Host OS

Windows 10 home

### Target Platform

UnityEditor, Windows Standalone

### Build Command

build.py build --desktop cpu

### Bug Description

handlandmark Visibility aways 0 (HasVisibility is false) in Holistic tracking, but pose lanmark (WorldPoseOutput) has value. is it a bug?

### Steps to Reproduce the Bug

start play mode

### Log

no device

**Comment by homuler** [comment]
duplicates #601.

Please make sure that [the official example](https://google.github.io/mediapipe/solutions/holistic.html#example-apps) returns the visibility.
If it surely returns, please reopen the issue. 
If it doesn't, ask it in the MediaPipe community.
