### ISSUE TITLE
How to implement pose classification in unity

### ISSUE THREAD

**Issue by jsaon-L** [homuler/MediaPipeUnityPlugin#654]
### Description

I noticed Mediapipe Document 
https://google.github.io/mediapipe/solutions/pose_classification.html

I would like to know if this can be implemented in unity and how should it be implemented

**Example**
`pose classification`   `repetition`   `Sign Language Detection`
https://www.youtube.com/watch?v=doDUihpj6ro

**Any help is greatly appreciated**

**Comment by homuler** [comment]
Actually, there is little I can add to the document you shared.

You can train a k-NN classifier with your favorite language (e.g. Python).
Once you have trained it, 
- you can implement a Calculator to classify poses in C++
- or you can implement a pose classifier in C#.

In the latter case, you also need to implement a function to convert pose landmarks to the input format for the k-NN classifier.

**Comment by jsaon-L** [comment]
thanks 
i'm going to learn K-NN and implement a pose classifier in C#.
