### ISSUE TITLE
Interface Issues/Crashing the Editor 

### ISSUE THREAD

**Issue by Luis-Alves2** [homuler/MediaPipeUnityPlugin#655]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Description

Hello,

I've been trying out the tracking option on the plugin in the unity editor and most things seem to work just fine,  as I can see the resulting Landmarks and similar objects in most of them. However, on the editor, I couldn't see the nodes/graph/meshes being drawn over the object being tracked. For example, on the FaceMesh, the actual mesh is drawn very rarely. Initially I was unsure if it was working, but I can see the landmarks positions on the console when altering the code to do so. Could you please tell me if it is a common behavior, or if it is some kind of issue?

I have another question related to the accuracy of models like object detection or box tracking, which assigned wrong labels to certain objects. Is there any way to improve them? Besides that it seems that occasionally this tracking method crashes the unity editor, I'm unsure if I did something wrong regarding that and would appreciate any and every help.

Thank you for you attention and I apologize for any inconvenience.

**Comment by homuler** [comment]
> For example, on the FaceMesh, the actual mesh is drawn very rarely. Initially I was unsure if it was working, but I can see the landmarks positions on the console when altering the code to do so. Could you please tell me if it is a common behavior, or if it is some kind of issue?

See https://github.com/homuler/MediaPipeUnityPlugin/issues/586#issuecomment-1132348263.

> I have another question related to the accuracy of models like object detection or box tracking, which assigned wrong labels to certain objects. Is there any way to improve them?

I don't know. Please ask it in the MediaPipe community.

> Besides that it seems that occasionally this tracking method crashes the unity editor, I'm unsure if I did something wrong regarding that and would appreciate any and every help.

Maybe the same as https://github.com/homuler/MediaPipeUnityPlugin/issues/587.
