### ISSUE TITLE
Pose Tracking - static_image_mode support?

### ISSUE THREAD

**Issue by CookieHCl** [homuler/MediaPipeUnityPlugin#658]
### Description

Do you support [STATIC_IMAGE_MODE](https://google.github.io/mediapipe/solutions/pose.html) in Pose solution?

I've checked [PoseTrackingConfig.cs](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/PoseTrackingConfig.cs) and SidePackets that [PoseTrackingGraph.cs](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/PoseTrackingGraph.cs#L209-L246=) is sending, but I couldn't find how to set `STATIC_IMAGE_MODE`.

Is it possible to set `STATIC_IMAGE_MODE`? If so, how do I do it?

**Comment by homuler** [comment]
`STATIC_IMAGE_MODE` is not implemented in the Pose Tracking sample currently.
You need to set `use_prev_landmarks` to `false` at runtime using `ValidatedGraphConfig`.
Please see https://github.com/homuler/MediaPipeUnityPlugin/issues/642#issuecomment-1177484869 for more details.

**Comment by CookieHCl** [comment]
Thanks. Is this the correct way to set `use_prev_landmarks`?

```C#
bool STATIC_IMAGE_MODE = true;
_graph = new CalculatorGraph();

using (var validatedGraphConfig = new ValidatedGraphConfig())
{
	var graphConfig = CalculatorGraphConfig.Parser.ParseFromTextFormat(_textConfig.text);
	validatedGraphConfig.Initialize(graphConfig).AssertOk();

	var extensionRegistry = new ExtensionRegistry() { GateCalculatorOptions.Extensions.Ext };
	var cannonicalizedConfig = validatedGraphConfig.Config(extensionRegistry);
	var gateCalculators = cannonicalizedConfig.Node.Where((node) => node.Calculator == "GateCalculator").ToList();

	foreach (var calculator in gateCalculators)
	{
		if (calculator.Options.HasExtension(GateCalculatorOptions.Extensions.Ext))
		{
			var options = calculator.Options.GetExtension(GateCalculatorOptions.Extensions.Ext);

			// Set GateCalculator.Allow a.k.a use_prev_landmarks to STATIC_IMAGE_MODE
			options.Allow = STATIC_IMAGE_MODE;
		}
	}

	_graph.Initialize(cannonicalizedConfig);
}
```

**Comment by homuler** [comment]
Sorry, it seems that we don't need to modify the config dynamically.
Try adding an `input_side_packet` definition and setting the side packet at runtime.
```diff
diff --git a/Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt b/Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt
index 9a725b5..3b3ad9d 100644
--- a/Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt  
+++ b/Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt  
@@ -73,6 +73,7 @@ node {
   input_side_packet: "SMOOTH_LANDMARKS:smooth_landmarks"
   input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
   input_side_packet: "SMOOTH_SEGMENTATION:smooth_segmentation"
+  input_side_packet: "USE_PREV_LANDMARKS:use_prev_landmarks"
   output_stream: "LANDMARKS:pose_landmarks"
   output_stream: "WORLD_LANDMARKS:pose_world_landmarks"
   output_stream: "SEGMENTATION_MASK:segmentation_mask_gpu"
```

**Comment by CookieHCl** [comment]
Working great. Thanks for your help!
