### ISSUE TITLE
Unable to import to my project

### ISSUE THREAD

**Issue by CorgiMyth** [homuler/MediaPipeUnityPlugin#659]
### Plugin Version or Commit ID

latest

### Unity Version

2021.3.6f1

### Your Host OS

Windows 10 Home

### Target Platform

Windows Standalone, Android

### Description

Hello, I am new to unity and mediapipe. I had successfully installed the plugin and was able to run the start scene but I tried to import the package to my project and a bunch of errors popped out. *The build platform I used is android platform*

![Problems](https://user-images.githubusercontent.com/108348576/179407336-422441b9-91f8-4354-abe6-d9d19e4960af.png)

**Comment by homuler** [comment]
Please use [the Build/Install issue form](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-install-issue.yml).

> but I tried to import the package to my project

How did you do that?

**Comment by homuler** [comment]
You can also build a unity package or tarball (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project).
And if you want, you can download a prebuilt package, too (cf. https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1).
