### ISSUE TITLE
Official Solutions apk not working

### ISSUE THREAD

**Issue by fishhead012** [homuler/MediaPipeUnityPlugin#660]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.6f

### Your Host OS

window 10

### Target Platform

Android

### Description

1. com.github.homuler.mediapipe-0.10.1.tgz
download

2. Install mediapipe-0.10.1.tgz in Unity (by package manager)

3. Build Holistic, Pose Tracking, Hand Tracking as apk (all asset loader type)

4. webcam, image, video does not work. (with gpu mode)

**(pc build works fine)**

### Code to Reproduce the issue

No modified or added code.

**Comment by homuler** [comment]
Please use [the Bug Report form](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) and share the log.

Did you copy dependent assets to the `StreamingAssets` folder? (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/624#issuecomment-1164396217)

**Comment by fishhead012** [comment]
thank you!!

The action was successful.

I made a basic mistake.

**Comment by inaPhy** [comment]
Create a folder "StreamingAssets" and import all files in Packages/com.github.homuler.mediapipe/Runtime/Resources.
But it did not work!
