### ISSUE TITLE
Running Modes

### ISSUE THREAD

**Issue by aadityasp** [homuler/MediaPipeUnityPlugin#661]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.4f1

### Your Host OS

macOS Monterey 12.4

### Target Platform

UnityEditor, Windows Standalone, Mac Standalone, Android, iOS

### Description

I'm just curious about the differences between the three Running Modes- Sync, Async, and Non Blocking Sync. Especially, what is Non blocking sync expected to do? I observed that in Sync Mode, The segmentation mask was perfect, but it was running at lower FPS. Asyc mode runs at higher FPS but has a lag induced where the segmentation mask takes some time to catch up. Non Blocking sync is very laggy and choppy. I tested it on Editor, Windows, mac, android and ios. And observed the same results.(Interestingly, on Android, it defaults back to Async after couple of seconds of running it on Sync mode.)

Any insight on this is greatly appreciated, thanks!!

Attaching a video for your reference:

https://user-images.githubusercontent.com/14892793/179800560-8dd9a0d0-bce7-4746-8ac9-d030134b3d4c.mov

**Comment by ROBYER1** [comment]
> ### Sync mode
> * Send the current frame to MediaPipe, wait for the output, and render the result.
> * While waiting for the output, the Main Thread will be blocked.
> 
> #### Pros
> * Output is usually synchronized with the input image, so there appears to be no delay.
> * We can receive the output in the Main Thread, so it's easy to implement.
> 
> #### Cons
> * When the inference takes a long time, overall FPS will degrade.
> 
> ### Async mode
> * Send each frame to MediaPipe and don't wait for the output.
> * Once the inference finishes, the registered callback method will be called, and the result will be rendered.
> 
> #### Pros
> * The Main Thread won't be blocked.
> 
> #### Cons
> * When the inference takes a long time, lots of empty packets will be output (annotations will flicker).
>   
>   * To avoid this, set a larger value to `timeoutMilliSec`.
> * We receive the output in a thread other than the Main Thread, it's rather difficult to use the value since [most Unity APIs are not available](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Advanced-Topics#unityengineunityexception--can-only-be-called-from-the-main-thread).
> 
> ### Non-Blocking Sync mode
> * Mode between Async mode and Sync mode
> * It will try retrieving the output from the stream only when some values are in the stream.
> 
> #### Pros
> * The Main Thread won't be blocked.
> * We can receive the output in the Main Thread.
> * You can choose whether to prioritize synchronizing the input image with the output or to allow delays to increase FPS.
> 
> #### Cons
> * Lots of empty packets will be output (annotations will flicker).
>   
>   * In reality, you should drop them.
>   * Maybe I should change the specifications.
> * If the inference can run fast enough, the Sync Mode performs better.
> 
> P.S.
> 
> > (Interestingly, on Android, it defaults back to Async after couple of seconds of running it on Sync mode.)
> 
> I think this cannot happen.

It would be really useful to see this mentioned in the Wiki somewhere for sure to help explain how these modes work to anyone new

**Comment by aadityasp** [comment]
> P.S.
> 
> > (Interestingly, on Android, it defaults back to Async after couple of seconds of running it on Sync mode.)
> 
> I think this cannot happen.


Hi @homuler, Below is the video which shows it happening on Android. 

Initially the running mode is Async and you can see a bit of lag in the segmentation.. But After few seconds at 0:40 it goes back to Async mode. (Even though it doesn't explicitly say it's in async mode in the Settings menu). Later when I chose Sync option and saved it, it goes back to being Sync without any lag in segmentation.


https://user-images.githubusercontent.com/14892793/185167983-77e410ac-364a-407a-9fa2-9d395722661e.mp4
