### ISSUE TITLE
Game Build with Mediapipe shows black screen on Windows

### ISSUE THREAD

**Issue by palnikhil** [homuler/MediaPipeUnityPlugin#662]
### Plugin Version or Commit ID

v0.8

### Unity Version

2020.3.29f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor, Windows Standalone

### Command Sequences

File > Build Settings> PC,MAC & Linux Standalone > Build
On unity Editor, The holistic API is working fine and I am able to track myself. 
But as soon as I build a .exe after the build and I try to run the file. A black screen appears and no mediapipe api works
**On Unity Editor Window**
![image](https://user-images.githubusercontent.com/85008177/180050206-1fa1ab2a-a458-43c2-9168-5119e26489db.png)
**After Build**
![image](https://user-images.githubusercontent.com/85008177/180050726-9b47e245-0bde-49b0-a739-805ce225a97b.png)

### Log

The Build Command exits saying that the Build has finished. No Error Log is shown.

**Comment by homuler** [comment]
> ### Plugin Version or Commit ID
> v0.8

Please use the latest version

> The Build Command exits saying that the Build has finished. No Error Log is shown.

Check the Player.log.

**Comment by palnikhil** [comment]
It does not get resolved by that

**Comment by homuler** [comment]
Please share your Player.log.

**Comment by palnikhil** [comment]
![image](https://user-images.githubusercontent.com/85008177/180834078-ed7cf548-b1b4-4446-baf3-915d6a44a51d.png)
![image](https://user-images.githubusercontent.com/85008177/180834141-92dd5e15-d0e3-4ba4-93b5-0ef213f68c41.png)

**Comment by palnikhil** [comment]
I don't know if I am right but I think the problem is because of "No AssetBundle has been set for this build"
![image](https://user-images.githubusercontent.com/85008177/180836105-0f5d62b1-950c-4925-8fc9-c4938fcc2175.png)

**Comment by palnikhil** [comment]
![image](https://user-images.githubusercontent.com/85008177/180840706-63f198fb-2a09-4096-8945-7eaa47420141.png)
I got the error. But I do not know how to resolve it

**Comment by palnikhil** [comment]
This is my player.log

**Comment by homuler** [comment]
> DllNotFoundException: mediapipe_c
at (wrapper managed-to-native) Mediapipe.UnsafeNativeMethods.glog_FLAGS_logtostderr(bool)

This is the error (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception).
- How did you build the plugin? (e.g. `python build.py build --desktop cpu -vv`)
- What is the output of `dir Packages\com.github.homuler.mediapipe\Runtime\Plugins`.

**Comment by palnikhil** [comment]
The contents of dir 
![image](https://user-images.githubusercontent.com/85008177/180993379-872c659a-e6a5-41b3-b571-9270191a01d1.png)
I ran this command to build the plugin:
> python build.py build --desktop cpu -v

**Comment by palnikhil** [comment]
I managed to resolve it......
I just changed the filename in the Build.
( unitymediapipetest_Data > Plugins  > x86_64 > libmediapipe_c.dll ) --> ( unitymediapipetest_Data > Plugins > x86_64 > mediapipe_c.dll )
And it started working.

**Comment by palnikhil** [comment]
Thanks for helping!!!!

**Comment by homuler** [comment]
As I said in https://github.com/homuler/MediaPipeUnityPlugin/issues/662#issuecomment-1190941363, just upgrade the plugin version.
