### ISSUE TITLE
Unity Cloud Build for iOS Failed

### ISSUE THREAD

**Issue by yuanzichun** [homuler/MediaPipeUnityPlugin#663]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

Latest 2021.x

### Your Host OS

Mac

### Target Platform

Cloud Build iOS

### XCode Version

Latest 13.x

### Problem Description

We have tried building our products with Unity Gaming Services--Cloud Build. It was able to build for Android and Windows with the Cloud Build. However, cloud build for iOS failed. I tried to create an empty scene with only a cube, and it built just fine; however, I then added MediaPipe Package to the project(simply added it), and Unity Cloud Build failed(same provisioning profile and certificate). Interestingly, I could build it with Xcode locally and installed on my iPad. The error log is shown below.

### Log

19275:      ['/APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-cc1', '-cc1', '-triple', 'arm64-apple-ios11.0.0', '-emit-obj', '--mrelax-relocations', '-disable-llvm-passes', '-target-sdk-version=15.5', '-fvisibility-inlines-hidden-static-local-var', '-target-abi', 'darwinpcs', '-O2', '-x', 'ir', '0990', '-o', '0990.o']
19276:     -= Output =-
19277:     error: Invalid value (Producer: 'APPLE_1_1316.0.21.2.5_0' Reader: 'LLVM APPLE_1_1300.0.29.30_0')
19278:     1 error generated.
19279:     Exited with 1
19280:     
19281: Stderr:
19282: >
19283:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:372:in `run`
19284:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:2886:in `block in CompileOrStripBitcodeInBundle`
19285:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:2825:in `each`
19286:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:2825:in `CompileOrStripBitcodeInBundle`
19287:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:3112:in `block in ProcessIPA`
19288:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:3073:in `each`
19289:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:3073:in `ProcessIPA`
19290:     /APPLICATION_PATH/Xcode13_2_1.app/Contents/Developer/usr/bin/ipatool:4035:in `<main>`}
19291:    **EXPORT FAILED **
19292: Exit status: 70
19293: +---------------+-------------------------------+
19294: |               Build environment                                      |
19295: +---------------+-------------------------------+
19296: | xcode_path    | /APPLICATION_PATH/Xcode13_2_1.app |
19297: | gym_version   | 2.182.0                                             |
19298: | export_method | ad-hoc                                          |
19299: | sdk                    | iPhoneOS15.2.sdk                        |
19300: +---------------+-------------------------------+
19301: ▸ Touch /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-atnnlqdcznsyfuapefoclcbgvcix/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/iOSCloudBuid.app (in target 'Unity-iPhone' from project 'Unity-iPhone')
19302: ▸     cd /BUILD_PATH/gtmy.stand-alone-exercise-demo.ios-test/temp20220721-5823-1m6v378
19303: ▸     /usr/bin/touch -c /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-atnnlqdcznsyfuapefoclcbgvcix/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/iOSCloudBuid.app
19304: ▸ ** ARCHIVE SUCCEEDED **
19305: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
19306: 📋  For the complete and more detailed error log, check the full log at:
19307: 📋  /BUILD_PATH/Library/Logs/gym/iOSCloudBuid-Unity-iPhone.log
19308: Looks like fastlane ran into a build/archive error with your project
19309: It's hard to tell what's causing the error, so we wrote some guides on how
19310: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
19311: Before submitting an issue on GitHub, please follow the guide above and make
19312: sure your project is set up correctly.
19313: fastlane uses `xcodebuild` commands to generate your binary, you can see the
19314: the full commands printed out in yellow in the above log.
19315: Make sure to inspect the output above, as usually you'll find more error information there
19316: +------------------+-----------+
19317: |         Lane Context                       |
19318: +------------------+-----------+
19319: | DEFAULT_PLATFORM | ios        |
19320: | PLATFORM_NAME    | ios         |
19321: | LANE_NAME               | ios build |
19322: +------------------+-----------+
19323: Error packaging up the application
19324: +------+---------------------------------------------------------------+-------------+
19325: |                                  fastlane summary                                                                                    |
19326: +------+---------------------------------------------------------------+-------------+
19327: | Step | Action                                                                                                         | Time (in s) |
19329: | 1    | Verifying fastlane version                                                                                 | 0           |
19330: | 2    | default_platform                                                                                               | 0           |
19331: | 3    | set_info_plist_value                                                                                          | 0           |
19332: | 4    | update_project_provisioning                                                                          | 0           |
19333: | 5    | sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d;/DEVELOPMENT_TEA | 0           |
19334: | 💥   | gym                                                                                                                | 210         |
19335: +------+---------------------------------------------------------------+-------------+
19336: [!] Error packaging up the application
19337: fastlane finished with errors
19338: [2022-07-21T22:23:49.298Z] - 5.0.3.2.4.2 - ERROR: xcode build failed 
19339:   RuntimeError (Build Failure):

**Comment by homuler** [comment]
> 19308: Looks like fastlane ran into a build/archive error with your project
19309: It's hard to tell what's causing the error, so we wrote some guides on how
19310: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
19311: Before submitting an issue on GitHub, please follow the guide above and make
19312: sure your project is set up correctly.
19313: fastlane uses xcodebuild commands to generate your binary, you can see the
19314: the full commands printed out in yellow in the above log.
19315: Make sure to inspect the output above, as usually you'll find more error information there

**Comment by yuanzichun** [comment]
Found this updated error message. 
109: error: exportArchive: MediaPipeUnity.framework does not support provisioning profiles.
110: Error Domain=IDEProvisioningErrorDomain Code=10 "MediaPipeUnity.framework does not support provisioning profiles." UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=MediaPipeUnity.framework does not support provisioning profiles., NSLocalizedRecoverySuggestion=MediaPipeUnity.framework does not support provisioning profiles, but provisioning profile d4592eef-74db-4bb7-a1bf-5e6ee0e1a680 has been manually specified. Remove this item from the "provisioningProfiles" dictionary in your Export Options property list.}

**Comment by homuler** [comment]
It looks to me that this is a problem with your setup and not with this project.
If you can confirm that something needs to be fixed in this project, please reopen it.

**Comment by ZichunYuan** [comment]
Solution found: disable Bitcode!
