### ISSUE TITLE
TimeoutException: Failed to start WebCam

### ISSUE THREAD

**Issue by DonghwanKIM0101** [homuler/MediaPipeUnityPlugin#664]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

macOS Monterey 12.4

### Target Platform

UnityEditor

### Target Device

MacBook Pro (16-inch, 2019)

### [Linux Only] GCC/G++ and GLIBC Version

bazel: 5.0.0
gcc, g++: 13.1.6
python: 3.9.10

### Build Command

python3.9 build.py build --desktop cpu -vv

### Bug Description

The situation is quite simple to [#392](https://github.com/homuler/MediaPipeUnityPlugin/issues/392)

However, my MacBook is Intel Mac and I can't find `TextureFrame#ChangeNameFrom`.

Also, I put `Debug.Log` in `TexutreFrame#GetNativeTexturePtr`, but it isn't called.

Importantly, the error is occurred without scene change.

Sometimes, I can see the web cam screen in the first scene (face detection), and when I change to other scene the error is occurred, but almost all errors occur first scene that means I can't see the web cam screen at all.

+ When I build old version; 0.9.1 and run in unity 2020.3.~~, it works well.

### Steps to Reproduce the Bug

1. Run `python3.9 build.py build --desktop cpu -vv`
2. Start Play Mode and the below error occurs.
`TimeoutException: Failed to start WebCam`

### Log

[Editor.log](https://github.com/homuler/MediaPipeUnityPlugin/files/9166404/Editor.log)

**Comment by homuler** [comment]
> Sometimes, I can see the web cam screen in the first scene (face detection), and when I change to other scene the error is occurred, but almost all errors occur first scene that means I can't see the web cam screen at all.

This error has been occurring occasionally before, but I agree that it's happening more often than before.
If this error occurs, it is usually necessary to restart UnityEditor.

**Comment by DonghwanKIM0101** [comment]
I restart UnityEditor several times and even restart MacBook, but the error occurs almost all the time.

Is there any possible problem in my build progress, unity setting, or any else?

**Comment by homuler** [comment]
Thank you!
Hmm, that's interesting.

In my case (on Linux Desktop), when it happens, it happens often, and when it doesn't, it doesn't happen at all (and now I happen to be unable to reproduce it at all).
Can you tell me how much the `count` will eventually go up in your environment?
https://github.com/homuler/MediaPipeUnityPlugin/blob/6efa5e1b75b7c6aa487254ade15fe7cd49fc6842/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs#L264

**Comment by DonghwanKIM0101** [comment]
I'm not sure this result is helpful, but I test it several times.

1. start scene: 768
2. change scene: 726
3. change scene: 757
4. change scene: 704
5. change scene: 722
6. restart unity editor: 756
7. change scene: 700
8. change scene: 747
9. change scene: 710
10. change scene: 744
11. stop and re-play (without restarting editor): 615
12. change scene: 720
13. change scene: 712
14. change scene: 739
15. change scene: 785

**Comment by homuler** [comment]
Thanks!
It seems that `timeoutFarme` should be at least about `2000`.
If you send me a PR, I'll merge it.

**Comment by yalegria** [comment]
I encountering this issue too. I am on Mac OS M1. 

I got it to go away by setting timeoutFrame to 3000. It seems that 2000 is too low.
