### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#666]
### Plugin Version or Commit ID

last version

### Unity Version

2021.3

### Your Host OS

windows 10 try to export Android

### Target Platform

Android

### Command Sequences

python build.py build --android arm64 --android_ndk_api_level 21 -vv

### Log

k:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: C:/_bzl/ie7hvhua/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android (146 packages loaded, 18453 targets configured).
INFO: Found 1 target...
INFO: From Linking external/flatbuffers/flatc.exe [for host]:
LINK : warning LNK4001: no object files specified; libraries used
ERROR: C:/_bzl/ie7hvhua/external/fft2d/BUILD.bazel:27:11: Compiling fftsg.c failed: (Exit 1): clang failed: error executing command
  cd /d C:/_bzl/ie7hvhua/execroot/mediapipe_api
  SET ANDROID_NDK_API_LEVEL=21
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Git\cmd;C:\Program Files (x86)\PuTTY\;D:\xampp\php\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\ehsN\AppData\Local\Microsoft\WindowsApps;C:\Users\ehsN\.dotnet\tools;C:\Program Files\dotnet;C:\Users\ehsN\AppData\Roaming\Composer\vendor\bin;N:\Users\ehsan\AppData\Local\android-sdk;N:\Users\ehsan\AppData\Local\android-sdk\tools;N:\Users\ehsan\AppData\Local\android-sdk\platform-tools;C:\Users\ehsN\AppData\Local\GitHubDesktop\bin;C:\adb;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\FFMPEG;M:\Program Files (x86)\MATLAB\MATLAB Compiler Runtime\v714\runtime\win32;C:\Users\ehsN\AppData\Local\Programs\Python\Python39;C:\Users\ehsN\AppData\Local\Programs\Python\Python39\Scripts;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\ehsN\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_251\bin;C:\c_plus_plus;N:\Users\ehsan\AppData\Local\android-sdk\build-tools\30.0.3;C:\msys64\usr\bin;c:\bazel;c:\nuget;c:\unzip;C:\Users\ehsN\AppData\Local\Programs\Fiddler
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=2a07
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Users//ehsN//AppData//Local//Programs//Python//Python39//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
  external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target aarch64-none-linux-android -fpic -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -O2 -g -DNDEBUG -MD -MF bazel-out/android-arm64-v8a-opt/bin/external/fft2d/_objs/fft2d/fftsg.pic.d -frandom-seed=bazel-out/android-arm64-v8a-opt/bin/external/fft2d/_objs/fft2d/fftsg.pic.o -fPIC -iquote external/fft2d -iquote bazel-out/android-arm64-v8a-opt/bin/external/fft2d -w -std=c++17 --sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64 -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c external/fft2d/fftsg.c -o bazel-out/android-arm64-v8a-opt/bin/external/fft2d/_objs/fft2d/fftsg.pic.o
# Configuration: bf4c477145a00d54b4b191ea73d000868d4cbdf1c799b7e0394d10cb8333e28c
# Execution platform: @local_execution_config_platform//:platform
error: invalid argument '-std=c++17' not allowed with 'C'
Target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android failed to build
INFO: Elapsed time: 4797.918s, Critical Path: 1344.77s
INFO: 950 processes: 388 internal, 562 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "M:\MediaPipeUnityPlugin-last\build.py", line 469, in <module>
    Argument().command().run()
  File "M:\MediaPipeUnityPlugin-last\build.py", line 150, in run
    self._run_command(self._build_android_commands())
  File "M:\MediaPipeUnityPlugin-last\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\ehsN\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env ANDROID_NDK_API_LEVEL="21" --action_env PYTHON_BIN_PATH="C://Users//ehsN//AppData//Local//Programs//Python//Python39//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-zero exit status 1.

**Comment by homuler** [comment]
duplicates #597

**Comment by ehsanwwe** [comment]
this is not duplicated , because i made android in last years
my last built was for about 6 month ago
this error is show me  at today

**Comment by homuler** [comment]
In the first place, building `mediapipe_android.aar` on Windows is not supported (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10).

**Comment by ehsanwwe** [comment]
hello its me again
the docker steel error


python build.py build --android arm64 --linkopt=-s -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env Prog
ramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures
 //mediapipe_api:mediapipe_proto_srcs`
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class
 java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.ta
r.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --copt, --cpu, --crosstool_top, and 6 more have changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "73106859751c2bc314861adc136d5cbecee3f7ae
7d05539dc8235efbf4efdcbe"
DEBUG: Repository rules_cc instantiated at:
  C:/mediapipe/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 1252 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 8.405s, Critical Path: 0.33s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Feeds used:
  C:\Users\ContainerAdministrator\.nuget\packages\
  https://api.nuget.org/v3/index.json

All packages listed in C:\mediapipe\packages.config are already installed.
DEBUG (build.py): Copying '.nuget\Google.Protobuf.3.20.0\lib\netstandard2.0\Google.Protobuf.dll' to 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll' to 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll' to 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Copying '.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll' to 'build\Plugi
ns\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env Prog
ramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures
 //mediapipe_api:mediapipe_assets`
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class
 java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.ta
r.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "73106859751c2bc314861adc136d5cbecee3f7ae
7d05539dc8235efbf4efdcbe"
DEBUG: Repository rules_cc instantiated at:
  C:/mediapipe/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 54 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 6.638s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'build\Resources'...
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'Assets\StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Android...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env Prog
ramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures
 --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android`
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class
 java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.ta
r.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --copt, --cpu, --crosstool_top, and 6 more have changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "73106859751c2bc314861adc136d5cbecee3f7ae
7d05539dc8235efbf4efdcbe"
DEBUG: Repository rules_cc instantiated at:
  C:/mediapipe/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/a0ec971de0dc82e0bf8784393cb8c4a56c171045.zip fa
iled: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository android_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:474:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository remotejdk11_win instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:140:6: in <toplevel>
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/jdk/remote_java_repository.bzl:48:17: in remote_java_repository
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/bazel_android_tools/android_tools_pkg-0.23.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repos
itory.downloader.UnrecoverableHttpException Unknown host: mirror.bazel.build
ERROR: An error occurred during the fetch of repository 'android_tools':
   Traceback (most recent call last):
        File "C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_android_tools/android_tools_pkg-0.23.0.tar.gz] to C:/
_bzl/3vmcl3ou/external/android_tools/temp11319565029611690676/android_tools_pkg-0.23.0.tar.gz: Unknown host: mirror.bazel.build
ERROR: /DEFAULT.WORKSPACE.SUFFIX:474:13: fetching http_archive rule //external:android_tools: Traceback (most recent call last):
        File "C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_android_tools/android_tools_pkg-0.23.0.tar.gz] to C:/
_bzl/3vmcl3ou/external/android_tools/temp11319565029611690676/android_tools_pkg-0.23.0.tar.gz: Unknown host: mirror.bazel.build
INFO: Repository remote_java_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:392:6: in <toplevel>
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository android_opencv instantiated at:
  C:/mediapipe/WORKSPACE:295:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: C:/_bzl/3vmcl3ou/external/bazel_tools/tools/android/BUILD:197:8: @bazel_tools//tools/android:desugar_java8_legacy_libs depends on @android_tools//:des
ugar_jdk_libs.jar in repository @android_tools which failed to fetch. no such package '@android_tools//': java.io.IOException: Error downloading [https://mir
ror.bazel.build/bazel_android_tools/android_tools_pkg-0.23.0.tar.gz] to C:/_bzl/3vmcl3ou/external/android_tools/temp11319565029611690676/android_tools_pkg-0.
23.0.tar.gz: Unknown host: mirror.bazel.build
ERROR: Analysis of target '//mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' failed; build aborted:
INFO: Elapsed time: 18.392s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 3177 targets configured)
Traceback (most recent call last):
  File "C:\mediapipe\build.py", line 469, in <module>
    Argument().command().run()
  File "C:\mediapipe\build.py", line 150, in run
    self._run_command(self._build_android_commands())
  File "C:\mediapipe\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --ac
tion_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --ver
bose_failures --config=android_arm64 --java_runtime_version=remotejdk_11 //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android' returned non-ze
ro exit status 1.

**Comment by gb2111** [comment]
@homuler 
When I read the installation, it looks for me like Android build is supported via Docker Windows. Is that correct?
I am trying now Docker Windows and see same error.

I tried to apply patch to Bazel (step 5) and got following errors:

`C:\mediapipe>cd C:\bazel

C:\bazel>git checkout 5.2.0
M       src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt
M       src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java
HEAD is now at 2e8458b781 Release 5.2.0 (2022-06-07)

C:\bazel>git apply ..\mediapipe\third_party\bazel_android_fixes.diff
error: patch failed: src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt:14
error: src/main/java/com/google/devtools/build/lib/bazel/rules/android/android_ndk_cc_toolchain_template.txt: patch does not apply
error: patch failed: src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java:31
error: src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java: patch does not apply

C:\bazel>bazel --output_user_root=C:\_bzl build --java_runtime_version=remotejdk_11 //src:bazel.exe
ERROR: C:/_bzl/4yp365mj/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been re
moved. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://gi
thub.com/bazelbuild/bazel/issues/8622 for details.
ERROR: C:/_bzl/4yp365mj/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
ERROR: C:/bazel/src/main/cpp/BUILD:90:10: While resolving toolchains for target //src/main/cpp:client: invalid registered toolchain '@build_bazel_rules_nodejs//toolcha
ins/node:node_windows_amd64_toolchain':
ERROR: Analysis of target '//src:bazel.exe' failed; build aborted:
INFO: Elapsed time: 0.200s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

C:\bazel>cp bazel-bin\src\bazel.exe C:\bin
cp: cannot stat 'bazel-bin\src\bazel.exe': No such file or directory

C:\bazel>cd C:\mediapipe`

Can you clarify pls?

**Comment by homuler** [comment]
If you want to build libraries for Android on Windows, please use [Docker Linux Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container) (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/603#issuecomment-1149398186).

Note that you don't need to build the plugin by yourself (cf. https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation) and if you still want to do it, you can use [the package workflow](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml) after forking this repository.

**Comment by gb2111** [comment]
@homuler thanks for reply.
I will need only pose tracking files. all files take a lot of space so that will be huge saving.
but I got Linux compilation working well. Just curious if Docker Windows should work or not for Android.

**Comment by homuler** [comment]
> Just curious if Docker Windows should work or not for Android.

It works, but If you don't know how to avoid the error, please use [Docker Linux Container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container) (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/603#issuecomment-1149398186).
Note that `Docker Linux Container` runs on Windows.

**Comment by gb2111** [comment]
I was using Docker Linux Container and it works very well.
Thank you!
