### ISSUE TITLE
[IOS] Always needing to drag+drop MediaPipeUnity.framework to General>Frameworks, Libraries and Embedded Content List in Xcode?

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#669]
### Description

This is a very minor issue but I am wondering if there is a way to fix or automate this, every time I make a new app with Mediapipe and export an Xcode project for IOS, I get errors on build about MediapipeUnity.framework not being in the build until I drag+drop MediaPipeUnity.framework to General>Frameworks, Libraries and Embedded Content List in Xcode.
![Screenshot 2022-07-24 at 1 20 15 pm](https://user-images.githubusercontent.com/10745594/180646769-ef4b1761-d04b-4c07-a393-532311cf25c0.png)
![Screenshot 2022-07-24 at 1 22 28 pm](https://user-images.githubusercontent.com/10745594/180646777-c6931ecf-5c55-47b8-881d-029fa95067ae.png)

**Comment by homuler** [comment]
Is `AddToEmbeddedBinaries` set to `true`? 
https://github.com/homuler/MediaPipeUnityPlugin/blob/436edb06f9b62c4af146903db9a21869c7ce2a89/Packages/com.github.homuler.mediapipe/Runtime/Plugins/iOS/MediaPipeUnity.framework.meta#L77

**Comment by ROBYER1** [comment]
Could well be the meta file is being reset on package import, I'll close this as I haven't noticed it since I rechecked the values on the meta file.
