### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by chrisError** [homuler/MediaPipeUnityPlugin#67]
Hi,

everything is working great in iOS in Landscape mode, but the image / landmarks are rotated by 90deg CCW when viewing in Portrait, do you know where could try looking to see if we can fix this? thanks and thanks for such amazing work on this plug in!

**Comment by chrisError** [comment]
solved.

**Comment by emreboyraz0** [comment]
> solved.

how did you solved issue?

**Comment by nenenkosi** [comment]
@chrisError how did you solved issue? Please assist us on this issue

**Comment by 0x01001** [comment]
@chrisError I have encountered the same issue on ios please online.
