### ISSUE TITLE
May I compile a C++/C header file?

### ISSUE THREAD

**Issue by endink** [homuler/MediaPipeUnityPlugin#671]
### Plugin Version or Commit ID

0.10.1

### Unity Version

2021.3

### Your Host OS

Windows 10 home

### Target Platform

Windows Standalone

### Description

If I want to interact with your wrapped/extended C code use C++ language , are there any compilation parameters that allow me to compile to get a c/C++ header file ( mediapipe_c.h ) ?

**Comment by homuler** [comment]
Do you mean you want header files for `mediapipe_c.dll`?
Will you tell me what you want to do with them?

**Comment by endink** [comment]
Yes, that's what I mean. I think this is a great project, you provides a convenient compile script and a good C export library, which not only works for Unity, but I also want to try to use this C export code to UE.

**Comment by homuler** [comment]
I see.
I've never used UE, so I may be mistaken, but is it difficult to import C++ code as is? (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/487#issuecomment-1065800514)

If possible, it would be better to include the C++ MediaPipe code directly.
On the other hand, if you tell me what prevents you from doing so (e.g. UE specifications), I may be able to advise you.

**Comment by endink** [comment]
It's not too hard to include C++ source code into a UE project, but it would be better to include a DLL in the UE, which still requires wrapping a layer of API export code（C/C++ code）, and I think your C export code has done that, maybe it can be reused in UE, but it's missing a header file.

**Comment by homuler** [comment]
Would just copying all the relevant header files (e.g. [`mediapipe_api/framework/calculator_graph.h`](https://github.com/homuler/MediaPipeUnityPlugin/blob/adb2d908cb6e7b82950c8bfa51c493760a6293b8/mediapipe_api/framework/calculator_graph.h)) into your project work? (if directives (e.g. `MEDIAPIPE_DISABLE_GPU`) are properly set)

If so, maybe I can add a Bazel build target to build header files.

**Comment by homuler** [comment]
Sorry, there are so many dependent header files that it's not practical to do this manually.
And since MediaPipe doesn't export header files, I feel it is too far out of scope to do that with this project (we need to do more work but the result will be seldom used in Unity).

**Comment by homuler** [comment]
To export header files, I guess you need to copy all dependent header files (e.g. `absl/**/*.h`, `mediapipe/**/*.h`, `mediapipe_api/**/*.h`), which can be found under `bazel-MediaPipeUnityPlugin/{external,mediapipe_api}`.

**Comment by endink** [comment]
Okay, in fact, I don't need all the header files, only the (C#) p/invoke method and struct define are required , maybe I need to do some tests  to know what the best solution is at the moment.

**Comment by endink** [comment]
@homuler Thank you for your many replies, mediapipe dont have any feature of shared library at present, maybe the only way is write "extern C" code in mediapipe project and compile it to a dll/so, and write header file manually， it's a big work ! Now I admire even more what you have done in this project. Is there any experience you can tell me about making mediapipe to a shared C/C++ library,  I think we can close this issue.

**Comment by homuler** [comment]
> Is there any experience you can tell me about making mediapipe to a shared C/C++ library

Maybe there is, but it's hard to answer if it's an open question.

If there is a way to build a UE project with Bazel, I think you should use it.
If not, you may want to reuse source files under `mediapipe_api`.
I think it is possible to create a portable header file by changing each pointer type (e.g. `mediapipe::CalculatorGraph*`) to `void*`.

**Comment by endink** [comment]
Unfortunately, UE uses its own build pipline and toolset, it use cshape code as the build script , as I know, Bazel can't compile UE project, Thank you for your valuable advice, I got a lot of inspiration from talking with you .I close this issue now.

BTW, Your project is amazing to all unity developers (including me).

**Comment by homuler** [comment]
Thanks!
