### ISSUE TITLE
FaceDetections annotation Prefab missing

### ISSUE THREAD

**Issue by miraclestar** [homuler/MediaPipeUnityPlugin#674]
### Description

![A@P(}BT)W0GC2(YY `MREUC](https://user-images.githubusercontent.com/1502697/181151599-d54851fd-c230-4cb3-bf2a-4cfb55c02aec.png)

**Comment by homuler** [comment]
It exists here.
https://github.com/homuler/MediaPipeUnityPlugin/blob/adb2d908cb6e7b82950c8bfa51c493760a6293b8/Packages/com.github.homuler.mediapipe/Runtime/Objects/Detection%20List%20Annotation.prefab.meta#L2

If you think it's really a problem, reopen it using [the Bug Report form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abug&template=bug_report.yml).
