### ISSUE TITLE
Problem exporting android project

### ISSUE THREAD

**Issue by CorgiMyth** [homuler/MediaPipeUnityPlugin#675]
### Plugin Version or Commit ID

latest

### Unity Version

2021.3.6f1

### Your Host OS

Windows 10 Home

### Target Platform

Android

### Description

Is it possible to use this plugin to calculate the head pose estimation just like this website "https://towardsdatascience.com/head-pose-estimation-using-python-d165d3541600"? As shown from the website, it is required to use the OpenCV function to calculate the angle, does this plugin provide the function of open cv to calculate the angle?

Another problem is that whenever I'm trying to export the android project. I keep getting the error as shown in the image. I installed the library for android following the guide
![error](https://user-images.githubusercontent.com/108348576/181176190-d8f1a783-119e-45dd-b29e-3de6e6d78f7d.png)
.

**Comment by homuler** [comment]
> does this plugin provide the function of open cv to calculate the angle?

No. If you want to use OpenCV functions with C#, you need to use another plugin or export them by yourself.
However, I think you would rather write your own [Calculator](https://google.github.io/mediapipe/framework_concepts/calculators.html) in C++.
Also, note that OpenCV is not _required_ to solve a PnP problem (I'm not even sure we need to solve a PnP problem in the first place).

> Another problem is that whenever I'm trying to export the android project. I keep getting the error as shown in the image. I installed the library for android following the guide

Please ask in the Unity forum.
https://forum.unity.com/threads/unity-2021-3-6f-android-gradle-template-folder-missing-build-failed.1306626/

**Comment by homuler** [comment]
Can you describe how to reproduce the error?
We can usually restart each scene without problems.

**Comment by homuler** [comment]
> Will this affect anything in long term?

Yes.
As the error message says, `ResourceManager` must not be initialized more than once, so if this error occurs, there's a bug.

**Comment by homuler** [comment]
`LocalResourceManager` is only available on UnityEditor, so use another `ResourceManager` class.
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#load-model-files.

**Comment by ROBYER1** [comment]
Ensure the bytes files for your model are in StreamingAssets folder, change ResourceManager mode to Streaming Assets on the Solution gameobject in your scene or wherever it is

**Comment by ROBYER1** [comment]
> > Ensure the bytes files for your model are in StreamingAssets folder, change ResourceManager mode to Streaming Assets on the Solution gameobject in your scene or wherever it is
> 
> I changed the ResourceManager to Streaming Assets and its working, I able to export the project. The bytes files required are in StreamingAssets folder but after I built the apk, the face mesh is not working. (It worked on my pc)

Happy to help, this issue can be closed now I think!

**Comment by ROBYER1** [comment]
Is it working in editor?

**Comment by ROBYER1** [comment]
That's probably the root cause then, when you built Mediapipe did you build all the solutions? Refer to the build commands in the Wiki section to check. O would recommend to build Mediapipe again and try? Make sure you built it for android of course and also windows/mac depending on your editor

**Comment by ROBYER1** [comment]
I'd delete the Packages> com.homuler... folder at the very least before rebuilding. Also check on GitHub here I think the latest update Homuler did included a prebuilt package you can download from the Releases section.

**Comment by homuler** [comment]
Read the log (e.g. `adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`) first before attempting to fix your problem (don't forget to enable `Development Build`).
Without reading the log, nobody can identify the cause.

**Comment by homuler** [comment]
> May I know how to include the calculator to my project ?

Where does this error occur (e.g. on your Windows PC, Android phone, etc...) and how did you build the plugin (e.g. `python build.py ...`)?

> So whenever I run my project this error straight pop out, although I used the code provided in tutorial.

Please file another issue using [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).

**Comment by homuler** [comment]
GPU inference is not supported on Windows.

**Comment by homuler** [comment]
Yes.
