### ISSUE TITLE
Proper Way to Upgrade version from v0.8.1 to the latest one

### ISSUE THREAD

**Issue by am-badshah** [homuler/MediaPipeUnityPlugin#677]
### Description

I was working on version v0.8.1 for some months, what is the proper way to upgrade to the latest version v0.10.1 with very few errors/things to fix.  Please let me know if there is a guide that can be followed.

**Comment by homuler** [comment]
> what is the proper way to upgrade to the latest version v0.10.1 with very few errors/things to fix.

It depends on your code.
If you imported this plugin to another project, then please read the **:warning: BREAKING CHANGES** sections in [release pages](https://github.com/homuler/MediaPipeUnityPlugin/releases).
If you cloned this project and changed the sample code under the `Assets` folder, you may need to resolve many conflicts, too.
