### ISSUE TITLE
iOS build Error / Is the bundle id build correctly?

### ISSUE THREAD

**Issue by dayowoo** [homuler/MediaPipeUnityPlugin#678]
### Plugin Version or Commit ID

adb2d90

### Unity Version

2021.3.6f1 (Apple Silicon)

### Your Host OS

M1 Mac

### Target Platform

iOS

### [iOS Only] XCode Version

XCode 13.2 / simulator iPhone13(15.0)

### Command Sequences

1. I have completed the installation guide number 1 to 5.
2. and opened `mediapipe_api/objc/BUILD` and modified `bundle_id`
3. I opened Unity and set the **Build Setting > Player > Bundle Identifier** exactly the same.
4. I build the command. 
-  `python build.py build --desktop cpu --opencv cmake --macos_universal -vv`
- `python build.py build --desktop cpu  --ios arm64 -vv`
5. The build was successful in Unity, and this error occurs when opened with XCode.

I found this issue(#87). and after checking the `GPU usage`, I modified the build command, but it was not resolved.
After the modification, `python build.py build --desktop gpu --ios arm64 -vv`  was entered into the terminal but could not be installed. So I entered `python build.py build --desktop cpu  --ios arm64 -vv` again.

### Log

**- XCode build > build Success > This is Log after Splash Screen** 

Warning: Error creating LLDB target at path '/Users/yechanjeon/Library/Developer/Xcode/DerivedData/Unity-iPhone-dzcbadadhwqlvmfqrxkbvgythezz/Build/Products/ReleaseForRunning-iphonesimulator/MediaPipeUnityPlugin.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
2022-07-29 14:28:16.193296+0900 MediaPipeUnityPlugin[27792:232824] Built from '2021.3/staging' branch, Version '2021.3.6f1 (7da38d85baf6)', Build type 'Development', Scripting Backend 'il2cpp'
2022-07-29 14:28:16.199917+0900 MediaPipeUnityPlugin[27792:232824] MemoryManager: Using 'Dynamic Heap' Allocator.
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
-> applicationDidFinishLaunching()
Found 1 interfaces on host : 0) 172.16.202.96
Multi-casting "[IP] 172.16.202.96 [Port] 55000 [Flags] 2 [Guid] 2243251283 [EditorId] 0 [Version] 1048832 [Id] iPhonePlayer(8,YECHANs-MacBook-Pro.local):56000 [Debug] 0 [PackageName] iPhonePlayer [ProjectName] <no name>" to [225.0.0.222:54997]...
2022-07-29 14:28:16.429628+0900 MediaPipeUnityPlugin[27792:232824] Cannot find executable for CFBundle 0x7fea1b7d33e0 </System/Library/Frameworks/Metal.framework> (not loaded)

Setting UIViewControllerBasedStatusBarAppearance to NO is no longer supported.
Apple actively discourages that, and all application-wide methods of changing status bar appearance are deprecated

2022-07-29 14:28:17.261675+0900 MediaPipeUnityPlugin[27792:232824] Writing analzed variants.
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1; jobified=1
Initializing Metal device caps: Apple iOS simulator GPU
Initialize engine version: 2021.3.6f1 (7da38d85baf6)
2022-07-29 14:28:18.240820+0900 MediaPipeUnityPlugin[27792:232969] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600000f3e820> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2022-07-29 14:28:18.469867+0900 MediaPipeUnityPlugin[27792:233016] fopen failed for data file: errno = 2 (No such file or directory)
2022-07-29 14:28:18.470176+0900 MediaPipeUnityPlugin[27792:233016] Errors found! Invalidating cache...
2022-07-29 14:28:18.814693+0900 MediaPipeUnityPlugin[27792:233016] fopen failed for data file: errno = 2 (No such file or directory)
2022-07-29 14:28:18.814798+0900 MediaPipeUnityPlugin[27792:233016] Errors found! Invalidating cache...
2022-07-29 14:28:18.918043+0900 MediaPipeUnityPlugin[27792:232824] Unbalanced calls to begin/end appearance transitions for <SplashScreenController: 0x7fea1f33d820>.
UnloadTime: 2.016833 ms
dyld[27792]: missing symbol called
CoreSimulator 783.5 - Device: iPhone 13 (2D7FB6AB-205C-460C-9B4D-C8C7EF371763) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 13
(lldb)

### Additional Context

![Untitled](https://user-images.githubusercontent.com/44601601/181696342-8a7f0413-5084-477d-b05f-04527c9c29ba.png)

**Comment by homuler** [comment]
It looks like you have opened UnityEditor before building the plugin, so I guess some meta files were removed then (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/602#issuecomment-1148149391).
Will you see if `Add to Embedded Binaries` is checked?

**Comment by dayowoo** [comment]
Thank you for your answer.
but I didn't work out. I checked issue #602, #385, #87 
Please, help me.

1. I checked `Add to Embedded Binaries`.
![image](https://user-images.githubusercontent.com/44601601/182110346-1599a65c-634b-43b7-917b-1c74802fdbc9.png)

2. I checked `Used GPU` (I referred to #87)

3. `Build And Run` in Unity, and exit Unity.

4. open .xcodeproj, below is the log after a successful build. (I used iPhone13 simulator)

**Comment by homuler** [comment]
What happens if you run it on your device instead of a simulator?

> I checked Add to Embedded Binaries.

I think it's OK, but I recommend you run `git checkout .` or `git checkout Packages`.
All the meta files are configured to work by default.

**Comment by homuler** [comment]
And please make sure the error occurs when there's no cache.

**Comment by dayowoo** [comment]
Thank you. I'll try.
I have a question, Would it affect if I change the bundle identifier to [com.testcompany.testproj.foo] in xcode?
(in unity's bundle id is [com.testcompany.testproj])

**Comment by dayowoo** [comment]
I deleted the cache, but it was still difficult, so I connected the device directly and solved it. 
Thank you very much. 👍👍👍

**Comment by homuler** [comment]
I'm not sure, but there may be a problem with your emulator settings.
