### ISSUE TITLE
error : libmediapipe_c.dylib: mach-o, but wrong architecture

### ISSUE THREAD

**Issue by dayowoo** [homuler/MediaPipeUnityPlugin#679]
### Plugin Version or Commit ID

adb2d90

### Unity Version

2021.3.6f1 (Apple Silicon)

### Your Host OS

M1 Mac

### Target Platform

iOS

### [iOS Only] XCode Version

XCode 13.2

### Command Sequences

First, `DIINotFoundException: mediapipe_c assembly` error occurred.
so, I followed this issue(#640), but `libmediapipe_c.dylib: mach-o, but wrong architecture` occurs.

I entered the commands below in order
1. `python build.py build --desktop cpu --opencv cmake -vv`
2. `python3 build.py build --desktop cpu --ios arm64 -vv`

Pleas help me.

### Log

Plugins: Couldn't open /Users/yechanjeon/MediaPipeUnityPlugin-master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib, error: dlopen(/Users/yechanjeon/MediaPipeUnityPlugin-master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib, 2): no suitable image found.  Did find:
	/Users/yechanjeon/MediaPipeUnityPlugin-master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib: mach-o, but wrong architecture
	/Users/yechanjeon/MediaPipeUnityPlugin-master/Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib: mach-o, but wrong architecture

### Additional Context

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44601601/181724250-f1d64a37-4016-4767-85c4-5e650ded36d3.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/44601601/181724093-504f26fd-9587-4147-bd87-2a5ca6dd98d2.png">

**Comment by homuler** [comment]
Maybe the same as https://github.com/homuler/MediaPipeUnityPlugin/issues/388#issuecomment-1000059515.

See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#m1-mac.
> :warning: use UnityEditor (Apple silicon) (>= 2021.2.2f1) to open the project.

P.S. You can download a pre-built package from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1).

**Comment by dayowoo** [comment]
Thank you for your answer.
I already downloaded and used Unity editor 20201.3.6f1(Apple Silicon)

Below is the log after entering the build command`python3 build.py build --desktop cpu --ios arm64 -vv`. 
Is it properly installed?

2 warnings generated.
Target //mediapipe_api/objc:MediaPipeUnity up-to-date:
  bazel-out/applebin_ios-ios_arm64-opt-ST-2967bd56a867/bin/mediapipe_api/objc/MediaPipeUnity.zip
INFO: Elapsed time: 8.226s, Critical Path: 4.18s
INFO: 65 processes: 31 internal, 34 darwin-sandbox.
INFO: Build completed successfully, 65 total actions
DEBUG (build.py): Unarchiving 'bazel-out/applebin_ios-ios_arm64-opt-ST-2967bd56a867/bin/mediapipe_api/objc/MediaPipeUnity.zip' to 'build/Plugins/iOS'...
INFO (build.py): Built native libraries for iOS
INFO (build.py): Installing built resources...
DEBUG (build.py): Copying 'build' to 'Packages/com.github.homuler.mediapipe/Runtime' recursively...
DEBUG (build.py): Running `cp -r build/* Packages/com.github.homuler.mediapipe/Runtime`
INFO (build.py): Installed

**Comment by homuler** [comment]
There are several causes I can think of, but for now, could you try the following command?
```sh
python3 build.py build --desktop cpu --opencv cmake --macos_universal --ios arm64 -vv
```

And again, you can also download a pre-built package from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1).

**Comment by dayowoo** [comment]
The build was finally successful when i entered `python3 build.py build --desktop cpu --opencv cmake --macos_universal --ios arm64 -vv`! Thank you.
Thank you for the pre-built package introduction.
