### ISSUE TITLE
Unity crashes when running Tests called "Ctor_ ... _When_CalledWithNoArguments" 

### ISSUE THREAD

**Issue by mgarbade** [homuler/MediaPipeUnityPlugin#680]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Pro

### Target Platform

UnityEditor

### Command Sequences

- Open Unity -> Test Runner
- Run selected Tests

### Log

- Unity Editor crashes when running Tests with "Ctor_ShouldInstantiate..._When_CalledWithNoArguments" in name (see picture)
- I would expect the particulat test to fail but not the entire editor to crash
![2022-07-29 13_23_23-Window](https://user-images.githubusercontent.com/3956593/181752536-3f5f4287-16bb-4361-84a7-078d872c4c48.jpg)

### Additional Context

- There are a few commits from my local fork ontop of v0.10.0 which should however not affect any of those tests

**Comment by homuler** [comment]
To run tests on Windows, you need to skip tests labeled `SignalAbort` or `GpuOnly`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/adb2d908cb6e7b82950c8bfa51c493760a6293b8/.github/workflows/windows-test.yml#L145
