### ISSUE TITLE
LocalResourceManager is only supported on UnityEditor

### ISSUE THREAD

**Issue by inaPhy** [homuler/MediaPipeUnityPlugin#681]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

 2021.3.3f1

### Your Host OS

macOS Monterey 12.4

### Target Platform

iOS

### [iOS Only] XCode Version

13.4.1

### Command Sequences

Played correctly in Unity.
However, Mediapipe does not seem to work when integrated into an iOS /MacOS app.
In the application, the camera works fine, but no dots or lines appear.
At first, I made Hand Tracking into an app, but it didn't work, and I made other samples into apps, but the same thing happened.

### Log

Unable to find player assembly: /Users/username/MediaPipeUnityPlugin/Temp/StagingArea/Data/Managed/UnityEngine.TestRunner.dll
UnityEngine.Debug:LogWarning (object)
Unity.Burst.Editor.BurstAotCompiler:OnPostBuildPlayerScriptDLLsImpl (UnityEditor.Build.Reporting.BuildReport) (at Library/PackageCache/com.unity.burst@1.6.5/Editor/BurstAotCompiler.cs:350)
Unity.Burst.Editor.BurstAotCompiler:OnPostBuildPlayerScriptDLLs (UnityEditor.Build.Reporting.BuildReport) (at Library/PackageCache/com.unity.burst@1.6.5/Editor/BurstAotCompiler.cs:208)
UnityEditor.BuildPlayerWindow/DefaultBuildMethods:BuildPlayer (UnityEditor.BuildPlayerOptions)
UnityEditorStartup/<>c:<.cctor>b__0_0 (UnityEditor.BuildPlayerOptions) (at Assets/MediaPipeUnity/Editor/BuildProcessor.cs:9)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

Build completed with a result of 'Succeeded' in 12 seconds (11798 ms)
UnityEditor.BuildPlayerWindow/DefaultBuildMethods:BuildPlayer (UnityEditor.BuildPlayerOptions)
UnityEditorStartup/<>c:<.cctor>b__0_0 (UnityEditor.BuildPlayerOptions) (at Assets/MediaPipeUnity/Editor/BuildProcessor.cs:9)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

### Additional Context

Is there anything I need to set up before I build?
please remember me

**Comment by homuler** [comment]
Please use [the Bug Report form](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) and share the Player.log.

**Comment by homuler** [comment]
If you imported the plugin to your project, see https://github.com/homuler/MediaPipeUnityPlugin/issues/660#issuecomment-1186629090.

**Comment by inaPhy** [comment]
Create a folder "StreamingAssets" and import all files in Packages/com.github.homuler.mediapipe/Runtime/Resources.
But it did not work!

**Comment by inaPhy** [comment]
[player.log](https://github.com/homuler/MediaPipeUnityPlugin/files/9227955/player.log)

**Comment by inaPhy** [comment]
please remember me

**Comment by homuler** [comment]
> : LocalResourceManager is only supported on UnityEditor

Switch the `AssetLoaderType` to `StreamingAssets` (cf. #528).
![Screenshot_20220731_121746](https://user-images.githubusercontent.com/4690128/182008388-f53f7e0c-5f92-4e71-869c-c090638c4ecf.png)

P.S. If you can build the plugin on your PC and want to build the sample app, I recommend you clone this repository and build the project. You can run every scenes in a single app.

**Comment by ROBYER1** [comment]
I find that if I'm setting up lots of new projects I often miss this, or when setting streaming assets I would also have the copied local resource bytes files and the streaming assets files added to the app but with some checking of the Unity Editor build logs you can see which ones are being added to the app unnecessarily and which are being copied to be used and delete their original files in the Unity Project.

**Comment by Thaina** [comment]
This is totally a pitfall to build sample in android. Should we automatically handle this case in some way?
