### ISSUE TITLE
Unity crashes when trying to run hair segmentation and face mesh simultaneously

### ISSUE THREAD

**Issue by jcelsi** [homuler/MediaPipeUnityPlugin#683]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Home

### Target Platform

Windows Standalone

### Description

Unity crashes when trying to run hair segmentation and face mesh simultaneously.
Is there are a way to run those projects simultaneously or at least one after another in the sace scene?

**Comment by homuler** [comment]
Please share your code and the error log (Editor.log).

**Comment by jcelsi** [comment]
I was finally able to run more than one graph but i have another problem now so i will close this issue
