### ISSUE TITLE
Switch iOS FaceMesh to selfie camera

### ISSUE THREAD

**Issue by dayowoo** [homuler/MediaPipeUnityPlugin#685]
### Description

Hello,

I'm trying to switch the camera to selfie for FaceMesh for IOS,
appreciate it if you can help with that.

I'm not familiar with Unity and XCode so pardon me if questions sound naive.

**Comment by homuler** [comment]
If you mean you want to use the front camera as input in the Face Mesh sample scene, tap the camera icon and select it from the source field.
![Screenshot_20220803_195758](https://user-images.githubusercontent.com/4690128/182592595-0555b5bc-51d2-434f-8020-fa1167f00d78.png)

If you don't know how to do that using Unity, please refer to the API documentation or ask it elsewhere (e.g. in the Unity forum).

**Comment by dayowoo** [comment]
Thank you so much
