### ISSUE TITLE
XCode iOS not building

### ISSUE THREAD

**Issue by uacal** [homuler/MediaPipeUnityPlugin#687]
### Plugin Version or Commit ID

v0.8.10

### Unity Version

2021.3.7f1

### Your Host OS

macOS Monterey 12.5

### Target Platform

iOS

### [iOS Only] XCode Version

13.4.1

### Command Sequences

I compiled and exported project to Xcode from Unity as per the instructions. After that, opened XCode and tried to build the Xcode project and run in iPhone X. But the compilation error says
**ld: framework not found MediaPipeUnity**

I've Mediapipe.framework added in Frameworks/Libraries section. Still facing the issue.

Thanks for this wonderful plugin. It works in Android well. I'm facing issue in iOS.

### Log

Ld /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build_ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios12.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Products/ReleaseForRunning-iphoneos -L/Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build_ios/Libraries -F/Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Products/ReleaseForRunning-iphoneos -F/Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build_ios/Frameworks/com.github.homuler.mediapipe/Runtime/Plugins/iOS -filelist /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -map -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Metal -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build_ios/Libraries/baselib.a -framework MediaPipeUnity -framework OpenGLES -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-eobnqalfnovjirgnqzdvzvabjhwc/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework

ld: framework not found MediaPipeUnity
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by homuler** [comment]
Have you built the plugin for iOS?
If not yet,
1. Close UnityEditor.
2. Run `python build.py build --ios arm64 -vv` and make sure it finishes successfully.
3. Run `git checkout Packages`.
4. Build your project again.

**Comment by uacal** [comment]
I did it but it fails in CUDA in my project. I don't have Nvidia GPU. I'm having macbook pro 2015 model with intel iris graphics. But it compiled in your project samples in this repo. So, I copied mediapipe library from there.

Is there anyway to skip GPU and build for project? I'm stuck since 2-3 days. Please help soon if possible.

**Comment by uacal** [comment]
ERROR: error loading package '': at /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/tensorflow/workspace2.bzl:5:6: initialization of module 'third_party/gpus/cuda_configure.bzl' failed


this is the error I'm getting in the build.py

**Comment by homuler** [comment]
Please run `python build.py build --ios arm64 -vv` on your Mac and share the _complete_ log.

**Comment by uacal** [comment]
here's the log:

`macbook@192 sofiq % python build.py build --ios arm64 -vv                      
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1439, column 40, in <toplevel>
		remote_cuda_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
INFO: Repository tf_runtime instantiated at:
  /Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/WORKSPACE:429:14: in <toplevel>
  /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/tensorflow/workspace3.bzl:28:15: in workspace
  /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/third_party/tf_runtime/workspace.bzl:12:20: in repo
  /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/third_party/repo.bzl:128:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/third_party/repo.bzl:81:35: in <toplevel>
INFO: Repository tf_toolchains instantiated at:
  /Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/WORKSPACE:429:14: in <toplevel>
  /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/tensorflow/workspace3.bzl:18:17: in workspace
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: error loading package '': at /private/var/tmp/_bazel_macbook/ce22530bf89e8ab790efd50287992463/external/org_tensorflow/tensorflow/workspace2.bzl:5:6: initialization of module 'third_party/gpus/cuda_configure.bzl' failed
INFO: Elapsed time: 3.540s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build.py", line 469, in <module>
    Argument().command().run()
  File "/Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/Users/macbook/Documents/Unity/Projects/sofiqeumo/unity/sofiq/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.
macbook@192 sofiq % `

**Comment by uacal** [comment]
I also don't have third_party/gpus/cuda_configure.bzl file which fails.

**Comment by homuler** [comment]
What is the output of `bazel --version`?

**Comment by uacal** [comment]
macbook@192 sofiq % bazel --version
bazel 5.2.0
macbook@192 sofiq %

**Comment by homuler** [comment]
> Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec

How about running `python build.py build --bazel_build_opts="--experimental_repo_remote_exec" --ios arm64 -vv`?

**Comment by homuler** [comment]
Have you changed the code or cloned another repository (run `git remote get-url origin`)?
The version written [in the description](https://github.com/homuler/MediaPipeUnityPlugin/issues/687#issue-1327676560) (`v0.8.10`) does not exist, and some logs are impossible.

**Comment by uacal** [comment]
nope

**Comment by homuler** [comment]
Will you tell me the output of the following commands?
```sh
git remote get-url origin
git rev-parse HEAD
cat packages.config
```

**Comment by uacal** [comment]
git remote get-url origin:

macbook@192 sofiq % git remote get-url origin
2022-08-04 14:35:26.070 xcodebuild[5828:109443] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-08-04 14:35:26.070 xcodebuild[5828:109443] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
https://github.com/MimirRnD/sofiqeumo.git
macbook@192 sofiq % 

------------------------------
git rev-parse HEAD

macbook@192 sofiq % git rev-parse HEAD
7a40c5a82167e3b99bf65afa2957998cf387afbd
macbook@192 sofiq %


-------------------------------
cat packages.config

macbook@192 sofiq % cat packages.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Google.Protobuf" version="3.15.6" targetFramework="netstandard20" />
  <package id="System.Buffers" version="4.4.0" targetFramework="netstandard20" />
  <package id="System.Memory" version="4.5.3" targetFramework="netstandard20" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" targetFramework="netstandard20" />
</packages>
macbook@192 sofiq %

**Comment by uacal** [comment]
As I said earlier, I'm working on other project in which I'm using your plugin. So, the git URL is different than the one you maybe assume.

**Comment by uacal** [comment]
I'm doing anything wrong, can you please tell me the steps how to add your plugin in my project or should build plugin in your project and then move my code into it? 'cause I'm in a very bad position stuck here. Need a solution to get it working asap.

**Comment by homuler** [comment]
> As I said earlier, I'm working on other project in which I'm using your plugin.

Well, I don't know how you're using this plugin, but you may have cloned this repository or copied some source files to your project, and it's OK.
However, once you have cloned the code, if you want to continue to use it, you are responsible for maintaining it.

If you don't want to maintain the source code, [import the plugin to your project](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project).
You can also download the pre-built package from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1).

**Comment by uacal** [comment]
okay, I was doing all the wrong thing. Now, I've exported the the UnityPackage and imported the in the project but its giving errors in Unity.

Thanks for your help.
