### ISSUE TITLE
Undefined symbols for architecture arm64:   "_glReadPixels", ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by uacal** [homuler/MediaPipeUnityPlugin#688]
### Plugin Version or Commit ID

v0.8.10

### Unity Version

2021.3.7f1

### Your Host OS

macOS Monterey 12.5

### Target Platform

iOS

### [iOS Only] XCode Version

13.4.1

### Command Sequences

Run exported Xcode project to build in iPhone X (iOS 15) fails to build.

### Log

Getting this error:

Undefined symbols for architecture arm64:
  "_glReadPixels", referenced from:
      _Gl_ReadPixels_mE20D483BE5ADD7B85929FC4602F7EF734C31705D in Mediapipe.Runtime.o
      _UnsafeNativeMethods_glReadPixels_mBDD92D903AFA6B21E4187F39DCED58FB56E4BB4E in Mediapipe.Runtime.o
     (maybe you meant: _UnsafeNativeMethods_glReadPixels_mBDD92D903AFA6B21E4187F39DCED58FB56E4BB4E)
  "_glFlush", referenced from:
      _Gl_Flush_mA9D5ECA06470361D7940768395B3475EBE22FF6E in Mediapipe.Runtime.o
      _UnsafeNativeMethods_glFlush_m5E5824AC4B242F7F029A8D0B1CE4A08E910BDFD7 in Mediapipe.Runtime.o
     (maybe you meant: _UnsafeNativeMethods_glFlush_m5E5824AC4B242F7F029A8D0B1CE4A08E910BDFD7)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _glReadPixels
Undefined symbol: _glFlush

**Comment by ROBYER1** [comment]
If you search your error already in the Issues section you will see the fix for this [here,](https://github.com/homuler/MediaPipeUnityPlugin/issues/385) let me know if doing this doesn't work though
https://github.com/homuler/MediaPipeUnityPlugin/issues/385#issuecomment-997788547

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#undefined-symbols-for-architecture-arm64-_glreadpixels.

**Comment by uacal** [comment]
@homuler  @ROBYER1  I've checked what you said everything is alright as you said. Still the issue persists.

**Comment by ROBYER1** [comment]
Try a fresh build of your project and in player settings > engine stripping make sure it is set to minimal rather than high

**Comment by uacal** [comment]
@ROBYER1  engine stripping is by default set to minimal. Also I tried by creating fresh project and import plugin there. Still it is not working.

**Comment by ROBYER1** [comment]
The error is because OpenGLES dependency is missing - in Unity Editor Project View > Packages/com.github.homuler.mediapipe/Runtime/Plugins/iOS/MediaPipeUnity.framework, check that OpenGLES is ticked in dependencies and also tick Run on start if that is an option. Apply, build to a fresh folder and try again, also Clean Build in Xcode

**Comment by uacal** [comment]
@ROBYER1 @homuler I've done this also. Still not working. I've tried creating new project and done all of this process in that too. It's not working in that too. Please tell me what do I do to make it run my project.

**Comment by uacal** [comment]
@ROBYER1 thanks for your help. It ran by doing what you suggested. But, the settings were available on **Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib**. I'm leaving this here if anyone gets the settings there.

@homuler thanks for making this wonderful plugin.
