### ISSUE TITLE
How to get hand landmarks in hand tracking?

### ISSUE THREAD

**Issue by Chandra-Mauli-Sharma** [homuler/MediaPipeUnityPlugin#691]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.5f1

### Your Host OS

Windows 11

### Target Platform

Android

### Description

I am quite new to all this. I cannot find any possible way to get the landmark values. If anyone can help it would be very nice.

Thanks.

**Comment by homuler** [comment]
Have you read [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial) or searched related issues (e.g. #619)?

**Comment by Chandra-Mauli-Sharma** [comment]
Yes, I went through the tutorial and I also tried getting the `List<NormalizedLandmarkList> handLandmarks = null;` in `IEnumerator WaitForNextValue()` function using `Debug.Log()` in synchronous mode. But the screen turned black maybe because of the webcam not working.

**Comment by homuler** [comment]
Have you succeeded in running the Hand Tracking sample scene at least?
If not yet, check your `Editor.log` or `Player.log` and resolve that issue.

**Comment by Chandra-Mauli-Sharma** [comment]
Yes, I was able to run the hand tracking sample on my phone but it didn't run on my editor it showed DllNotFoundException:mediapipe_c. I thought this might be because I build the project just for Android through bazel.

**Comment by Chandra-Mauli-Sharma** [comment]
I got the solution thanks for helping.
