### ISSUE TITLE
How to make Mac project work on windows ?

### ISSUE THREAD

**Issue by jksfood** [homuler/MediaPipeUnityPlugin#692]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2020.3.37fc1

### Your Host OS

Windows 10 Professional

### Target Platform

Windows Standalone

### Description

I hava success run the project on mac os, But now, I also need to run this project on my windows 10 Professional , so I copy the project from mac to windows , but it does not work , even lead unity crash!

### Code to Reproduce the issue

Multiple scripted importers are targeting the extension 'gltf' and have all been rejected: UniGLTF.GltfScriptedImporter (assembly: D:\UnityProject\cloud\v2\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\Library\ScriptAssemblies\UniGLTF.Editor.dll), TriLibCore.Editor.TriLibGLTFScriptedImporter (assembly: D:\UnityProject\cloud\v2\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\Library\ScriptAssemblies\Assembly-CSharp-Editor.dll) 
UnityEditor.AssetImporters.ScriptedImporter:RegisterScriptedImporters ()

**Comment by homuler** [comment]
Please learn how to use Unity first.
For example, you must not copy the `Library/` folder.
