### ISSUE TITLE
Windows 10 gpu support

### ISSUE THREAD

**Issue by ijorquera** [homuler/MediaPipeUnityPlugin#693]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 home

### Target Platform

Windows Standalone

### Description

Hello, is there a way to enable gpu support for windows 10? I tried running hair segmentation in windows and ubuntu and the difference in performance is overwhelming so I would like to try enabling gpu on windows since cpu mode is a bit too slow (need a timeout of at least 1 second in order to get the segmentation somewhat working on cpu), but I'm not quite sure where should I start. 

### Code to Reproduce the issue

Compare hair segmentation in gpu and cpu mode

**Comment by homuler** [comment]
> is there a way to enable gpu support for windows 10?

I think it is technically possible, but GPU acceleration on Windows is not supported by MediaPipe (cf. https://google.github.io/mediapipe/getting_started/gpu_support.html).

> I'm not quite sure where should I start.

If you want to implement it, https://github.com/google/mediapipe/issues/617#issuecomment-675468331 may be helpful.

**Comment by ijorquera** [comment]
Thank you! I will look into that
