### ISSUE TITLE
Camera not showing any results in the samples app.

### ISSUE THREAD

**Issue by uacal** [homuler/MediaPipeUnityPlugin#694]
### Description

I've successfully build and ran the plugin and samples. But the camera doesn't show output like: Face Mesh in face and Hand Skeleton tracking in Hand Tracking. Sometimes the camera flickers also. I don't have any errors. Just not able to see the output. I'm running the samples in iPhone X - iOS 15.2.

Thanks for help in advance.

**Comment by homuler** [comment]
Use [the Bug Report form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abug&template=bug_report.yml).
