### ISSUE TITLE
Build Error in Window, could not find any instance of Visual Studio.

### ISSUE THREAD

**Issue by hyunjoebrother** [homuler/MediaPipeUnityPlugin#696]
### Plugin Version or Commit ID

dont know (maybe Recent ver.)

### Unity Version

2021.3.7f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Dont know (Maybe Recent ver.)

### Command Sequences

$ python build.py build --desktop cpu --opencv cmake -vv

### Log

ERROR: C:/_bzl/kzfpac4l/external/opencv/BUILD.bazel:243:6: Foreign Cc - CMake: Building opencv_cmake failed: (Exit 1): bash.exe failed: error executing command
  cd /d C:/_bzl/kzfpac4l/execroot/mediapipe_api
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C;C:\MediaPipeTest\MediaPipeUnityPlugin\venv\Scripts;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\????\AppData\Roaming\SPB_Data\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Java\jdk1.8.0_261\bin;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\????\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\????\AppData\Local\Programs\Python\Python310;C:\anaconda3;C:\anaconda3\Library\mingw-w64\bin;C:\anaconda3\Library\usr\bin;C:\anaconda3\Library\bin;C:\anaconda3\Scripts;C:\Users\????\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\????\AppData\Local\Programs\Python\Python38;C:\Users\????\AppData\Local\Microsoft\WindowsApps;C:\Modeltech_pe_edu_10.4a\win32pe_edu;C:\Users\????\AppData\Local\Programs\Microsoft VS Code\bin;C:\src\flutter\bin;C:\Android_SDK\emulator;C:\Android_SDK\platform-tools;C:\Android_SDK\tools;C:\Users\????\AppData\Roaming\nvm;C:\Program 
Files\nodejs;C:\Users\????\AppData\Roaming\npm
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=8e0a
    SET PYTHON_BIN_PATH=C://MediaPipeTest//MediaPipeUnityPlugin//venv//Scripts//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
  C:\msys64\usr\bin\bash.exe -c bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
# Configuration: b115b5f0572c4b1a8a12984ed67010b039ef18a2ce36ef8e3929559056f3575f
# Execution platform: @local_execution_config_platform//:platform
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library opencv_cmake

Environment:______________
PROCESSOR_LEVEL=6
BUILD_SCRIPT=bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/build_script.sh
EXT_BUILD_ROOT=C:\_bzl\kzfpac4l\execroot\mediapipe_api
BUILD_LOG=bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/CMake.log
PWD=/c/_bzl/kzfpac4l/execroot/mediapipe_api
MSYS_NO_PATHCONV=1
HOME=/home/HyunjoeBrother
BUILD_WRAPPER_SCRIPT=bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
PYTHON_BIN_PATH=C://MediaPipeTest//MediaPipeUnityPlugin//venv//Scripts//python.exe
EXT_BUILD_DEPS=C:\_bzl\kzfpac4l\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.ext_build_deps
SYSTEMROOT=C:\WINDOWS
TERM=xterm-256color
TEMP=C:\Temp
BUILD_TMPDIR=C:\_bzl\kzfpac4l\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir
INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files 
(x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
SHLVL=2
PROCESSOR_REVISION=8e0a
RUNFILES_MANIFEST_ONLY=1
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
MSYS2_ARG_CONV_EXCL=*
INSTALLDIR=C:\_bzl\kzfpac4l\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake
TMP=C:\Temp
PATH=C:\_bzl\kzfpac4l\execroot\mediapipe_api:/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/HostX64/x64:/usr/bin:/bin:/c/WINDOWS:/c/WINDOWS/System32:/c/WINDOWS/System32/WindowsPowerShell/v1.0:C:/c/MediaPipeTest/MediaPipeUnityPlugin/venv/Scripts:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin:/c/Users/?꾩“?뺣떂/AppData/Roaming/SPB_Data/bin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Windows Live/Shared:/c/Program Files/Java/jdk1.8.0_261/bin:/c/Program Files/MySQL/MySQL Server 
8.0/bin:/c/Program Files/Git/cmd:%NVM_HOME%:%NVM_SYMLINK%:/c/Program Files/nodejs:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Users/?꾩“?뺣떂/AppData/Local/Programs/Python/Python310/Scripts:/c/Users/?꾩“?뺣떂/AppData/Local/Programs/Python/Python310:/c/anaconda3:/c/anaconda3/Library/mingw-w64/bin:/c/anaconda3/Library/usr/bin:/c/anaconda3/Library/bin:/c/anaconda3/Scripts:/c/Users/?꾩“?뺣떂/AppData/Local/Programs/Python/Python38/Scripts:/c/Users/?꾩“?뺣떂/AppData/Local/Programs/Python/Python38:/c/Users/?꾩“?뺣떂/AppData/Local/Microsoft/WindowsApps:/c/Modeltech_pe_edu_10.4a/win32pe_edu:/c/Users/?꾩“?뺣떂/AppData/Local/Programs/Microsoft VS Code/bin:/c/src/flutter/bin:/c/Android_SDK/emulator:/c/Android_SDK/platform-tools:/c/Android_SDK/tools:/c/Users/?꾩“?뺣떂/AppData/Roaming/nvm:/c/Program Files/nodejs:/c/Users/?꾩“?뺣떂/AppData/Roaming/npm:/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/HostX64/x64:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/VC/VCPackages:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/bin/Roslyn:/c/Program Files/Microsoft Visual Studio/2022/Community/Team Tools/Performance Tools/x64:/c/Program Files/Microsoft Visual Studio/2022/Community/Team Tools/Performance Tools:/c/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0//x64:/c/Program Files (x86)/Windows Kits/10/bin//x64:/c/Program Files/Microsoft Visual Studio/2022/Community//MSBuild/Current/Bin/amd64:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/Tools/::/c/WINDOWS/system32:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/VC/Linux/bin/ConnectionManagerExe
WINDIR=C:\WINDOWS
PROCESSOR_ARCHITECTURE=AMD64
LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
SYSTEMDRIVE=C:
ProgramData=C:\ProgramData
_=/usr/bin/env
__________________________
+ 'C:\_bzl\kzfpac4l\execroot\mediapipe_api/external/cmake-3.22.2-windows-x86_64/bin/cmake.exe' -DBUILD_LIST=calib3d,core,features2d,highgui,imgcodecs,imgproc,video,videoio 
-DBUILD_opencv_apps=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_world=ON -DBUILD_EXAMPLES=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_JPEG=ON -DBUILD_OPENEXR=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON -DBUILD_ZLIB=ON -DWITH_1394=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_GTK=OFF -DWITH_IPP=OFF -DWITH_ITT=OFF -DWITH_JASPER=OFF -DWITH_V4L=OFF -DWITH_WEBP=OFF -DCV_ENABLE_INTRINSICS=ON -DWITH_EIGEN=ON -DENABLE_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DOPENCV_SKIP_PYTHON_LOADER=ON -DOPENCV_SKIP_VISIBILITY_HIDDEN=ON -DBUILD_WITH_STATIC_CRT=OFF -DWITH_LAPACK=ON '-DCMAKE_TOOLCHAIN_FILE=C:\_bzl\kzfpac4l\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir/crosstool_bazel.cmake' -DCMAKE_BUILD_TYPE=Release '-DCMAKE_INSTALL_PREFIX=C:\_bzl\kzfpac4l\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake' '-DCMAKE_PREFIX_PATH=C:\_bzl\kzfpac4l\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.ext_build_deps' -DCMAKE_RANLIB= -A x64 -G 'Visual Studio 16 2019' 'C:\_bzl\kzfpac4l\execroot\mediapipe_api/external/opencv'
CMake Error at CMakeLists.txt:111 (enable_language):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/_bzl/kzfpac4l/execroot/mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir/CMakeFiles/CMakeOutput.log".
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/CMake.log

Target //mediapipe_api:mediapipe_desktop failed to build
ERROR: C:/mediapipetest/mediapipeunityplugin/mediapipe_api/BUILD:254:10 Linking mediapipe_api/mediapipe_c.dll failed: (Exit 1): bash.exe failed: error executing command    
  cd /d C:/_bzl/kzfpac4l/execroot/mediapipe_api
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C;C:\MediaPipeTest\MediaPipeUnityPlugin\venv\Scripts;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\????\AppData\Roaming\SPB_Data\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Java\jdk1.8.0_261\bin;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\????\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\????\AppData\Local\Programs\Python\Python310;C:\anaconda3;C:\anaconda3\Library\mingw-w64\bin;C:\anaconda3\Library\usr\bin;C:\anaconda3\Library\bin;C:\anaconda3\Scripts;C:\Users\????\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\????\AppData\Local\Programs\Python\Python38;C:\Users\????\AppData\Local\Microsoft\WindowsApps;C:\Modeltech_pe_edu_10.4a\win32pe_edu;C:\Users\????\AppData\Local\Programs\Microsoft VS Code\bin;C:\src\flutter\bin;C:\Android_SDK\emulator;C:\Android_SDK\platform-tools;C:\Android_SDK\tools;C:\Users\????\AppData\Roaming\nvm;C:\Program 
Files\nodejs;C:\Users\????\AppData\Roaming\npm
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=8e0a
    SET PYTHON_BIN_PATH=C://MediaPipeTest//MediaPipeUnityPlugin//venv//Scripts//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
  C:\msys64\usr\bin\bash.exe -c bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
# Configuration: b115b5f0572c4b1a8a12984ed67010b039ef18a2ce36ef8e3929559056f3575f
# Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 990.541s, Critical Path: 767.85s
INFO: 2355 processes: 900 internal, 1455 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\MediaPipeTest\MediaPipeUnityPlugin\build.py", line 469, in <module>
    Argument().command().run()
  File "C:\MediaPipeTest\MediaPipeUnityPlugin\build.py", line 141, in run
    self._run_command(self._build_desktop_commands())
  File "C:\MediaPipeTest\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\현조형님\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://MediaPipeTest//MediaPipeUnityPlugin//venv//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake_static //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.
(venv) 

### Additional Context

Im trying to use MediaPipe (Selfi-Segmentation) on Unity.
Not using Docker, just install by resource (MSYS2, Python, bazel, NuGet, Numpy, openCV).
But Building did NOT complete successfully on VSC.
Also, When I open 'Start Scene' unity scene file, 
*error CS0246: The type or namespace name 'ImageFormat' could not be found (are you missing a using directive or an assembly reference?)*
have these Error Issues.

**Comment by homuler** [comment]
Please download a built package from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1) or fork this repository and run [the Package workflow](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/package.yml) (if you want to build the plugin with custom options).
