### ISSUE TITLE
Can I print out the same value of the eye position regardless of the face position?

### ISSUE THREAD

**Issue by dayowoo** [homuler/MediaPipeUnityPlugin#697]
### Description

Hello, I succeeded in printing landmarks using FaceMesh. 
I want all the coordinate values inside the face to be the same when I am with the same expression regardless of the face position. (This is because the eye position is the same wherever the face is.)

I want to open the coordinates on the cam and read the coordinate values in it.

 Do you have any reference materials for this? 
Thank you.

**Comment by homuler** [comment]
I'm not sure what you mean, but if you don't know how to use MediaPipe itself, please ask it elsewhere.

**Comment by dayowoo** [comment]
I looked it up and it was about face geometry. 
I found similar issues. (#593, #481)
Thank you for your answer.
