### ISSUE TITLE
Standalone build

### ISSUE THREAD

**Issue by Zumbalamambo** [homuler/MediaPipeUnityPlugin#698]
### Plugin Version or Commit ID

adb2d90

### Unity Version

2021.3.1f1

### Your Host OS

Ubuntu 18.0.4

### Target Platform

Linux Standalone

### Command Sequences

python build.py build --desktop gpu

### Log

-

### Additional Context

I have successfully compiled it on my Ubuntu Machine. When I try the same code on another machine, it throws the following error,

```
DllNotFoundException: mediapipe_c assembly:<unknown assembly> type:<unknown type> member:(null)
Mediapipe.UnsafeNativeMethods..cctor () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/UnsafeNativeMethods.cs:29)
```

What am I missing?

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception.
You may want to link OpenCV statically (`--opencv cmake`).

**Comment by Zumbalamambo** [comment]
@homuler thank you . I tried it but it's still throwing the same error! :( Am I missing something? I tried `python3.9 build.py build --desktop gpu --opencv cmake -v`

**Comment by homuler** [comment]
What is your host machine's OS (maybe `Ubuntu 18.04`?) and what is your target machine's OS?
In general, `libmediapipe_c.so` won't work on a machine if the GLIBC version is less than that of the machine used to build it.

**Comment by Zumbalamambo** [comment]
@homuler Yes, the other machine is `Ubuntu 18.0.4` while the mediapipe is built on `Ubuntu 20.0.4`. In Ubuntu 18.0.4, it has got glibc v2.27 while `Ubuntu 20.0.4` has got glibc v2.31. any possible fixes?

**Comment by homuler** [comment]
Please download the built package from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1) or use [Docker Ubuntu container](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker) to build it.

As mentioned in [the document](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#arch-linux), you should always prefer Docker.
> > :warning: If your GNU libc version in the target machine is compatible with it in the container, always prefer [Docker](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker).
