### ISSUE TITLE
Tutorial code question

### ISSUE THREAD

**Issue by CookieHCl** [homuler/MediaPipeUnityPlugin#699]
### Description

1. `yield return new WaitUntil(() => _webCamTexture.width > 16);` from
``` C#
var webCamDevice = WebCamTexture.devices[0];
_webCamTexture = new WebCamTexture(webCamDevice.name, _width, _height, _fps);
_webCamTexture.Play();

yield return new WaitUntil(() => _webCamTexture.width > 16);
```

Why do need this code? What happens if we don't have this line?

2. `yield return new WaitForEndOfFrame();` from
``` C#
while (true)
{
  _inputTexture.SetPixels32(_webCamTexture.GetPixels32(_inputPixelData));
  var imageFrame = new ImageFrame(ImageFormat.Types.Format.Srgba, _width, _height, _width * 4, _inputTexture.GetRawTextureData<byte>());
  var currentTimestamp = stopwatch.ElapsedTicks / (System.TimeSpan.TicksPerMillisecond / 1000);
  _graph.AddPacketToInputStream("input_video", new ImageFramePacket(imageFrame, new Timestamp(currentTimestamp))).AssertOk();

  yield return new WaitForEndOfFrame();

  if (multiFaceLandmarksStream.TryGetNext(out var multiFaceLandmarks))
  {
    _multiFaceLandmarksAnnotationController.DrawNow(multiFaceLandmarks);
  }
  else
  {
    _multiFaceLandmarksAnnotationController.DrawNow(null);
  }
}
```

What happens if we use `yield return null` instead?

**Comment by homuler** [comment]
> 1. `yield return new WaitUntil(() => _webCamTexture.width > 16);`
>
> Why do need this code? What happens if we don't have this line?

On macOS or iOS devices, the size of `WebCamTexture` can be 16x16 even when `WebCamTexture#isPlaying` returns `true`.

> 2. `yield return new WaitForEndOfFrame();`
>
> What happens if we use `yield return null` instead?

This makes a difference in when the coroutine resumes.
This is a pure Unity question, so please ask it elsewhere or google it for more details.

**Comment by CookieHCl** [comment]
@homuler 
Yes, I know `WaitForEndOfFrame` return after screen rendering, and `yield return null` return between Update and screen rendering.

I wanted to know why we need to draw landmarks after screen rendering.

**Comment by homuler** [comment]
I see.
In that sense, we don't need to draw annotations after screen rendering and `yield return null` might be better.

**Comment by CookieHCl** [comment]
OK. Thanks for answering!
