### ISSUE TITLE
Google.Protobuf.sln MacOS Issue

### ISSUE THREAD

**Issue by Almazikman** [homuler/MediaPipeUnityPlugin#70]
I installed mediapipe by instruction on Mac and I managed to start Hello World template, but, I have a problem with make cpu && make install

My terminal:
`MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make cpu && make install
mkdir -p .build
curl -L https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz -o .build/protobuf-3.13.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0    357      0 --:--:-- --:--:-- --:--:--   357
100 5154k    0 5154k    0     0   661k      0 --:--:--  0:00:07 --:--:--  589k
tar xf .build/protobuf-3.13.0.tar.gz -C .build
dotnet restore .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln && \
	dotnet build -c Release .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
/bin/sh: dotnet: command not found
make: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 127
MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make gpu
dotnet restore .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln && \
	dotnet build -c Release .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
/bin/sh: dotnet: command not found
make: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 127
MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make install
mkdir -p Assets/MediaPipe/SDK/Plugins/Protobuf
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/MediaPipe/SDK/Plugins/Protobuf
cp: .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/*: No such file or directory
make: *** [install-protobuf] Error 1
MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ `

Because of this issue in Unity I have a lot of errors like #62 
Any ideas how to fix it?

**Comment by homuler** [comment]
Please install .NET Core.
https://github.com/homuler/MediaPipeUnityPlugin#net-core

**Comment by Almazikman** [comment]
Yeah, it helped partly. I have an error in terminal:
`MacBook-Air-Aleksandr:MediaPipeUnityPlugin Sasha$ make cpu && make install
dotnet restore .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln && \
	dotnet build -c Release .build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.406

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/AddressBook.csproj (in 50.5 sec).
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/Google.Protobuf.Conformance.csproj (in 1.36 min).
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj (in 31.21 sec).
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/Google.Protobuf.JsonDump.csproj (in 19 ms).
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/Google.Protobuf.csproj (in 1.71 min).
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj (in 1.93 min).
  Restored /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj (in 53.2 sec).
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Google.Protobuf -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll
  Google.Protobuf -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard2.0/Google.Protobuf.dll
  Google.Protobuf -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard1.1/Google.Protobuf.dll
  Google.Protobuf.Test.TestProtos -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard1.1/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test.TestProtos -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard2.0/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Benchmarks -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/bin/Release/netcoreapp3.1/Google.Protobuf.Benchmarks.dll
  Google.Protobuf.JsonDump -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/bin/Release/netcoreapp2.1/Google.Protobuf.JsonDump.dll
  AddressBook -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/bin/Release/netcoreapp2.1/AddressBook.dll
  Google.Protobuf.Test -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll
  Google.Protobuf.Conformance -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/bin/Release/netcoreapp2.1/Google.Protobuf.Conformance.dll
  Google.Protobuf.Test.TestProtos -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/net45/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test -> /Users/Sasha/mediapipe/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/net451/Google.Protobuf.Test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:25.18
cd C && bazel  build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe_api:mediapipe_desktop mediapipe_api:mediapipe_assets mediapipe_api:mediapipe_proto_srcs
/bin/sh: bazel: command not found
make: *** [cpu] Error 127
`
And in Unity I still have a lot of issues. 
What did I miss?

> Please install .NET Core.
> https://github.com/homuler/MediaPipeUnityPlugin#net-core

**Comment by homuler** [comment]
You may not have installed `bazel` yet.
```txt
/bin/sh: bazel: command not found
```

Have you done this step?
```txt
1. Install MediaPipe and ensure that you can run Hello World! example.
```

**Comment by Almazikman** [comment]
Oh, somehow Mac removed bazel from PATH and that's why I couldn't install it. Now it's working and I don't have any Unity errors. Thanks for your help.
