### ISSUE TITLE
DLL Not Found Exception (Although I tried all that has been mentioned)

### ISSUE THREAD

**Issue by nader1414518** [homuler/MediaPipeUnityPlugin#701]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.4f1

### Your Host OS

macOS (M1 Chip)

### Target Platform

UnityEditor, Android

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.2
NDK: 21.3.6528147

### Command Sequences

Followed all of the steps in the installation section and I used the following command to build libs for Editor and Android

- python3 build.py build --desktop cpu --android arm64 -vv

And It gave me the same error 

DllNotFoundException: mediapipe_c assembly:<unknown assembly> type:<unknown type> member:(null)

and then I tried this

python3 build.py build --desktop cpu --android arm64 --opencv cmake  -vv

and still gave me the same error

### Log

- python3 build.py build --desktop cpu --android arm64 -vv

- python3 build.py build --desktop cpu --android arm64 --opencv cmake  -vv

**Comment by homuler** [comment]
Have you read https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception? (especially No.5)
Please also check https://github.com/homuler/MediaPipeUnityPlugin/issues/679#issuecomment-1200869407.

**Comment by nader1414518** [comment]
Thank you very much the issue is solved in the Unity Editor but the Android build (Hand Tracking Scene in the samples) is not starting the camera unless I switch to video and then to camera back and when I do that it doesn't detect anything 

I also tried to logcat to see any issues but nothing is showing as an error

Build Tools: 30.0.2
NDK: 21.3.6528147

Test Device: Android 11 (API 30)

If you can help me with this I would be grateful

**Comment by homuler** [comment]
If you built only the Hand Tracking Scene, then maybe #681 is the same issue.
If it doesn't solve your issue, please share the steps to reproduce it (describe in a way that anyone can reproduce it in their local environment) and the Player.log (`adb logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`). 

By the way, will you tell me what was the cause?
> Thank you very much the issue is solved in the Unity Editor

P.S.
In practice, when building the sample app, you should not modify `Scenes in Build` if unnecessary.
By default, each scene is configured to work on UnityEditor, but not on other platforms.
For example, if you import this plugin to your project, each sample scene will work on your UnityEditor, but it won't work on your Android devices unless you copy dependent resources to `Assets/StreamingAssets` and change the `AssetLoaderType` to `StreamingAssets`.

**Comment by nader1414518** [comment]
Thanks for your response, Regarding the previous problem this command fixed it for me

`python3 build.py build --desktop cpu --opencv cmake --macos_universal --ios arm64 -vv`

Regarding the Android Problem I switched the AssetLoaderType to StreamingAssets and copied all the files there (Assets/StreamingAssets) and that made the camera initialize successfully but It didn't detect the hands 

[Player.log](https://github.com/homuler/MediaPipeUnityPlugin/files/9332557/Player.log)

And this is the Player.log file

**Comment by nader1414518** [comment]
By the way I used this command instead so I can build the android libs 

`python3 build.py build --desktop cpu --opencv cmake --macos_universal --android arm64 -vv`

And the android is ARM64 I checked it

**Comment by nader1414518** [comment]
I switched to GPU inference mode and the Hand Tracking worked!! Thanks for your cooperation I appreciate it and sorry for spamming!!

**Comment by homuler** [comment]
> Thanks for your response, Regarding the previous problem this command fixed it for me
>
> `python3 build.py build --desktop cpu --opencv cmake --macos_universal --ios arm64 -vv`

I'm more interested in the cause, not how you fixed, but it's not important, so please let me know only if you find that.

P.S.
> this is the Player.log file

You should check `Development Build`. Otherwise, most log messages won't be output.
