### ISSUE TITLE
How to get the coordinates of each point of the finger

### ISSUE THREAD

**Issue by bbq82828** [homuler/MediaPipeUnityPlugin#702]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.7f1

### Your Host OS

macOS 12.5

### Target Platform

Mac Standalone

### Description

Hello, I want to ask how to get the coordinates of each point of the finger

**Comment by jsaon-L** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks

**Comment by homuler** [comment]
See #560, #610, #619.
duplicates #691.

**Comment by bbq82828** [comment]
Oh I see it thanks for your answer
