### ISSUE TITLE
shaking lips in the new version of your project

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#703]
### Description

in first line i should say thanks to you and Mediapipe team , because i was use old version of mediapipe ( about 9 month ago )
it was very weak but in the new version runtime speed was good and quality of detection face landmarks is awesome
but in the lips position the landmark shaking 
can you suggest me a way to reduce shaking of landmarks ?
( in the FaceMesh sample scene )

**Comment by homuler** [comment]
Have you confirmed that the issue doesn't occur when you run [the official sample app](https://google.github.io/mediapipe/solutions/face_mesh.html#example-apps)?

**Comment by ROBYER1** [comment]
Could be this again: https://github.com/homuler/MediaPipeUnityPlugin/issues/586
