### ISSUE TITLE
Depth perception

### ISSUE THREAD

**Issue by voiceofthedead** [homuler/MediaPipeUnityPlugin#707]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.5f1

### Your Host OS

Windows 11

### Target Platform

Windows Standalone

### Description

I've successfully got the SDK to work on my machine, but when I've decided to try to check out the Z values of landmarks (simply by enabling the checkmark), the skeleton rotated forwards like and old woman bent down by the weight of centuries on her shoulders. 
Is there an optimal range where the depth perception of the library is working properly, or is it just not an option?

**Comment by LGuilhermeRodrigues** [comment]
Did I reproduce your issue correctly?
![image](https://user-images.githubusercontent.com/68308462/184966487-37d35245-2fa3-46b6-92b4-639867d36f9f.png)

**Comment by homuler** [comment]
If you have a problem with the data returned by MediaPipe, then ask a question in the MediaPipe community.
As I recall, there's already a similar issue in https://github.com/google/mediapipe/issues.
