### ISSUE TITLE
Example Solutions on Android

### ISSUE THREAD

**Issue by bkaye3** [homuler/MediaPipeUnityPlugin#708]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

Windows 11 Home

### Target Platform

Android

### Description

I am trying to run the hand tracking example solution on an Android build. I am able to run this example in the UnityEditor and it works. The code will successfully build and run on an Android phone, but the hand tracking does not display when running on Android. I made sure to select GPU for Inference and Streaming Assets for Asset Loader Type for the Bootstrap script attached to the Solution object on the Hand Tracking scene. I am not sure what I am missing in order to get this to work. 
I used the all-in-one prebuilt package from the release page.

**Comment by homuler** [comment]
Please enable `Development Build` and share the Player.log (`adb logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`).

**Comment by ROBYER1** [comment]
Did you put the .bytes files you are using in the Streaming Assets folder too?

**Comment by bkaye3** [comment]
I had not moved the .bytes files into the Streaming Assets folder. I have done this now and some of the samples are working, such as face detection and face mesh, but the hand tracking still does not work.

The following is the output from the logcat:
[com.MediaPipeUnityPlugin.DefaultCompany-logcat.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9364730/com.MediaPipeUnityPlugin.DefaultCompany-logcat.txt)

**Comment by bkaye3** [comment]
After reading the logcat I found the error. I needed to move the handedness.txt file into the StreamingAssets folder. It is working now. Thank you for the help!

**Comment by ROBYER1** [comment]
> After reading the logcat I found the error. I needed to move the handedness.txt file into the StreamingAssets folder. It is working now. Thank you for the help!

I was about to suggest the same
