### ISSUE TITLE
help increasing FPS

### ISSUE THREAD

**Issue by jcelsi** [homuler/MediaPipeUnityPlugin#710]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### Description

I'm developing an scene using Holistic solution. When i run the async mode on the sample app the framerate 
I get almost 60 fps, but using the script i wrote following the api overview from the wiki the framerate decreases to almost 28 FPS.

Is there something wrong with my async implementation? 

```csharp
private IEnumerator Start()
    {
      if (WebCamTexture.devices.Length == 0)
      {
        throw new System.Exception("Web Camera devices are not found");
      }


      _screen.rectTransform.sizeDelta = new Vector2(_width, _height);

      _inputTexture = new Texture2D(_width, _height, TextureFormat.RGBA32, false);
      _outputTexture = new Texture2D(_width, _height, TextureFormat.RGBA32, false);
      _outputPixelData = new Color32[_width * _height];

      _screen.texture = _outputTexture;

      _resourceManager = new LocalResourceManager();
      yield return _resourceManager.PrepareAssetAsync("face_landmark_with_attention.bytes");

      var stopwatch = new Stopwatch();

      _faceMeshGraph = new CalculatorGraph(_meshConfigAsset.text);

      multiFaceLandmarksStream = new OutputStream<NormalizedLandmarkListPacket, NormalizedLandmarkList>(_faceMeshGraph, "face_landmarks", false);
      multiFaceLandmarksStream.AddListener(OnFaceLandmark);

      multiBodyLandmarksStream = new OutputStream<NormalizedLandmarkListPacket, NormalizedLandmarkList>(_faceMeshGraph, "pose_landmarks", false);
      multiBodyLandmarksStream.AddListener(OnBodyLandmark);

      multiFaceLandmarksStream.StartPolling().AssertOk();
      multiBodyLandmarksStream.StartPolling().AssertOk();
      _faceMeshGraph.StartRun().AssertOk();
      stopwatch.Start();

      while (liveTexture != null)
      {

        var texture = TextureToTexture2D(liveTexture);
        _inputTexture.SetPixels32(texture.GetPixels32());

        var imageFrame = new ImageFrame(ImageFormat.Types.Format.Srgba, _width, _height, _width * 4, _inputTexture.GetRawTextureData<byte>());

        //Set input
        var currentTimestamp = stopwatch.ElapsedTicks / (System.TimeSpan.TicksPerMillisecond / 1000);
        _faceMeshGraph.AddPacketToInputStream("input_video", new ImageFramePacket(imageFrame, new Timestamp(currentTimestamp))).AssertOk();

        _inputTexture.SetPixels32(texture.GetPixels32());
        _inputTexture.Apply();

        _outputTexture.SetPixels32(_inputTexture.GetPixels32());
        _outputTexture.Apply();

        yield return new WaitForEndOfFrame();
      }
    }
```

**Comment by homuler** [comment]
> ```cs
>       multiFaceLandmarksStream.StartPolling().AssertOk();
>       multiBodyLandmarksStream.StartPolling().AssertOk();
> ```

You don't need to call `StartPolling` since you won't implement polling.

> ``` cs
>         _inputTexture.SetPixels32(texture.GetPixels32());
>         _inputTexture.Apply();
> ```

I don't know why you're calling `SetPixels32` twice. Note that this is a very slow operation.

> ``` cs
>         _outputTexture.SetPixels32(_inputTexture.GetPixels32());
>         _outputTexture.Apply();
> ```

After all, you don't need to synchronize the input image and the output value, so I think you should render `liveTexture` directly.
Again, note that this is a very slow operation.

``` cs
_outputTexture = liveTexture;
```

> ```cs
> var texture = TextureToTexture2D(liveTexture);
> ```

I think you should initialize `liveTexture` as a `Texture2D` if possible.
