### ISSUE TITLE
Selfie Segmentation - how to change webCamTexture size vs background

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [homuler/MediaPipeUnityPlugin#712]
### Description

Hi,
I would like to request help with this:
I need to show with Selfie Segmentation sample for Android, video stream,  where user is in the center of image, and background is around on the Raw Image which is stretched two times  - it is hard to describe, so please take a look in pictures below.

This is what I get, when I have RawImage respecting aspect from Selfie segmentation (let's say this is Vertical Raw Image):
![image](https://user-images.githubusercontent.com/29869511/185384842-cdfda152-f102-414c-8e1f-f7d02f1bc2ca.png)

This is what I get, when RawImage is stretched -  (let's say this is Horizontal Raw Image):
![image](https://user-images.githubusercontent.com/29869511/185384152-f6c09617-ec00-4e05-b908-2326736c6026.png)

And this is what would be nice to have (background is wide, user is centered, not stretched):
![image](https://user-images.githubusercontent.com/29869511/185386079-345d2ef3-61f1-462f-b6ec-c7e789fbc7d7.png)

Thanks in advance for any help.

**Comment by ROBYER1** [comment]
Have you tried Aspect Ratio fitter component in your UI where you see this happening? https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-AspectRatioFitter.html

**Comment by TomaszWozniakMosina** [comment]
Thanks for the advice - I solved it by combining Raw Image and background and rendering it with another camera to Render Texture.
