### ISSUE TITLE
Selfie Segmentation - make background transparent

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [homuler/MediaPipeUnityPlugin#713]
### Description

Hi,
Please, somebody, tell me how to achieve in Selfie Segmentation to make background transparent (the default is green)?

Thanks in advance for info.

**Comment by homuler** [comment]
Enable alpha blending and change the alpha value of the Mask Annotation color.
```diff
diff --git a/Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader b/Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader
index 6c8dbe3..f123ab1 100644
--- a/Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader
+++ b/Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader
@@ -12,6 +12,7 @@ Shader "Unlit/MediaPipe/Unmask Shader"
     SubShader
     {
         Tags { "RenderType"="Transparent" }
+        Blend SrcAlpha OneMinusSrcAlpha
         LOD 100
 
         Pass
```

**Comment by LGuilhermeRodrigues** [comment]
with this change we can set the transparent color in the prefab Main Canvas>Container Panel>Body>Annotatable Screen>Annotation Layer>SegmentationMask Annotation

**Comment by LGuilhermeRodrigues** [comment]
> with this change we can set the transparent color in the prefab Main Canvas>Container Panel>Body>Annotatable Screen>Annotation Layer>SegmentationMask Annotation

then the background will still be gray because there is a gray background image in the object Main Canvas>Container Panel, just set its Color to be transparent too

**Comment by ROBYER1** [comment]
This can probably be closed now? @TomaszWozniakMosina

**Comment by TomaszWozniakMosina** [comment]
Yes, thank you very much for your help!
