### ISSUE TITLE
Android/data/com.study.MediaPipeUnityPlugin/files/pose_detection.bytes is not found

### ISSUE THREAD

**Issue by wizVR-zhangjun** [homuler/MediaPipeUnityPlugin#714]
### Description

I don't understand why the file pose_detection. bytes is missing, and this file is not required in my configuration file

![1661172967410](https://user-images.githubusercontent.com/60952586/185927017-67e5f0b7-30aa-44e6-8cac-b9f199ede37f.png)

![1661173121321](https://user-images.githubusercontent.com/60952586/185927304-d0a2dbdd-fb03-4be8-a56b-73dfd3375041.png)
![1661173144598](https://user-images.githubusercontent.com/60952586/185927318-68a37d61-7e6c-4bf9-aacb-653f85291fd6.png)
Pose_detection has been annotated Why report this error 

This is an error on the Android platform

**Comment by homuler** [comment]
Please choose [a more appropriate form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new/choose) and share the log and the code to reproduce your issue.
In addition to that, before submitting an issue, please make sure that others can understand it.
