### ISSUE TITLE
Supported Android API Level?

### ISSUE THREAD

**Issue by CookieHCl** [homuler/MediaPipeUnityPlugin#716]
### Description

What is the least supported Android API Level? Currently I'm using `mediapipe_android.aar` from releases.

Can I change least supported Android API Level by changing `--android_ndk_api_level` from `python build.py`?

**Comment by homuler** [comment]
> What is the least supported Android API Level? Currently I'm using mediapipe_android.aar from releases.

21 (NDK).
The release package was built by the Package workflow.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d2608ea69676db2a798402a42e00abb9684d1252/.github/workflows/package.yml#L52

> Can I change least supported Android API Level by changing --android_ndk_api_level from python build.py?

Yes.

**Comment by CookieHCl** [comment]
What is the lowest NDK level/target SDK level that I can build/run mediapipe?

**Comment by homuler** [comment]
I think it depends on your Unity version.
At least, this native plugin does not export any java classes nor use the MediaPipe Java API.
