### ISSUE TITLE
Windows - some scripts have compilation errors 

### ISSUE THREAD

**Issue by ch1474** [homuler/MediaPipeUnityPlugin#72]
Hello, 

The example scene won't run on Windows 10. I have attached the output from the make file, and a screenshot from Unity. 

[make_file_log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6055100/make_file_log.txt)
![unity_erros](https://user-images.githubusercontent.com/18485021/109396601-477e9f00-792a-11eb-9475-c69471fb0a5d.png)

**Comment by homuler** [comment]
Please run `make install` before starting Unity Editor.

**Comment by homuler** [comment]
closes because the build command has changed.
