### ISSUE TITLE
Undefined Symbols when building to iOS

### ISSUE THREAD

**Issue by Valtech-Stockwell** [homuler/MediaPipeUnityPlugin#721]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.8f1

### Your Host OS

Windows 11 (Xcode on Mac 12.5.1)

### Target Platform

iOS

### [iOS Only] XCode Version

13.4.11

### Command Sequences

Standard Build in Unity (target iOS)
Standard Build in Xcode (target iPad Air 5th Gen)

### Log

Showing Recent Issues
Ld /Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/valtechstockwell/Desktop/myapp
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Products/ReleaseForRunning-iphoneos -L/Users/valtechstockwell/Desktop/myapp/Libraries -L/Users/valtechstockwell/Desktop/myapp/Libraries/OpenCV+Unity/Plugins/iOS -F/Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Products/ReleaseForRunning-iphoneos -F/Users/valtechstockwell/Desktop/myapp/Frameworks/com.github.homuler.mediapipe/Runtime/Plugins/iOS -filelist /Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Metal -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /Users/valtechstockwell/Desktop/myapp/Libraries/baselib.a -lOpenCvSharpExtern -framework MediaPipeUnity -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/valtechstockwell/Library/Developer/Xcode/DerivedData/Unity-iPhone-aukplxrxkccmeseeexhpfjhmmmhc/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework

Undefined symbols for architecture arm64:
  "_glReadPixels", referenced from:
      _Gl_ReadPixels_mE20D483BE5ADD7B85929FC4602F7EF734C31705D in Mediapipe.Runtime.o
      _UnsafeNativeMethods_glReadPixels_mBDD92D903AFA6B21E4187F39DCED58FB56E4BB4E in Mediapipe.Runtime.o
     (maybe you meant: _UnsafeNativeMethods_glReadPixels_mBDD92D903AFA6B21E4187F39DCED58FB56E4BB4E)
  "_glFlush", referenced from:
      _Gl_Flush_mA9D5ECA06470361D7940768395B3475EBE22FF6E in Mediapipe.Runtime.o
      _UnsafeNativeMethods_glFlush_m5E5824AC4B242F7F029A8D0B1CE4A08E910BDFD7 in Mediapipe.Runtime.o
     (maybe you meant: _UnsafeNativeMethods_glFlush_m5E5824AC4B242F7F029A8D0B1CE4A08E910BDFD7)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Additional Context

Sorry... I don't know anything about building to iOS

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#undefined-symbols-for-architecture-arm64-_glreadpixels and https://github.com/homuler/MediaPipeUnityPlugin/issues/385#issuecomment-997788547.
