### ISSUE TITLE
Retrieve 2D Landmarks.

### ISSUE THREAD

**Issue by Zumbalamambo** [homuler/MediaPipeUnityPlugin#722]
### Feature Description

How do we retrieve the 2d Landmark positions (Vector2) and also the confidence possibly?

**Comment by homuler** [comment]
Have you tried [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks)?

**Comment by Zumbalamambo** [comment]
@homuler yes, I tried it. Always the Y values are negative. why is that so?

**Comment by homuler** [comment]
> Always the Y values are negative. why is that so?

It depends on the input and the output. From the information given, it is hard to say why.

> But `OnPoseWorldLandmarksOutput` has got `LandmarkList`. How do I retrieve the screen position in this case?

See [the official documentation](https://google.github.io/mediapipe/solutions/pose.html#pose_world_landmarks) for the output type.
`pose_world_landmarks` are scaled in meters and represented in the real-world coordinate system.
If you need to overlay the output result on the input image, you should probably use `pose_landmarks`, not `pose_world_landmarks`.

**Comment by Zumbalamambo** [comment]
@homuler the input is from the normal camera. Could it be because the frame is flipped which results in negative values?

**Comment by homuler** [comment]
I'd like you to use [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).
I understand that it is often difficult to decide which form to use, but at least this is not apparently a feature request.

> It depends on the input and the output.

- Explain which landmark has what value using a screenshot (e.g. the left wrist landmark (`left_hand_landmarks[0]`) is at `(0.5, -0.3)` in the image).
- Which solution are you using?
- From which output stream (e.g. `pose_landmarks`) are you getting the output?
- At which line of code are you getting the output?
   - If you're running your own code or have changed the sample code, share the code.

Note that if you're reading the value after calling `Rect#GetPoint` (that is, `Vector2`), then the value represents the position in that `Rect`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d2608ea69676db2a798402a42e00abb9684d1252/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/ImageCoordinate.cs#L479-L492
