### ISSUE TITLE
Build size for Android and iOS

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [homuler/MediaPipeUnityPlugin#724]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.7f1

### Your Host OS

Windows 11

### Target Platform

Windows Standalone, Android, iOS

### Description

Hi,
We use macOS Intel Mac guide from Wiki to build libraries. Everything is ok, but the size is very large.
Could you please tell me, how to reduce build size, maybe by excluding unnecessary solutions from libraries (android, iOS, Windows-Windows is needed only for development in Unity Editor) - we need only Selfie Segmentation.

Thank you in advance :)

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#build-command.

In your case, run `python build.py build --android arm64 --ios arm64 --linkopt=-s --solutions=selfie_segmentation -vv`.
If you want to disable the bitcode, you can also specify `--no-apple_bitcode` (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/524#issuecomment-1093834311).
