### ISSUE TITLE
Need to use AR Camera

### ISSUE THREAD

**Issue by Chandra-Mauli-Sharma** [homuler/MediaPipeUnityPlugin#725]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.5

### Your Host OS

Windows 11

### Target Platform

Android

### Description

I wanted to use the AR Camera with hand tracking. Can anyone please help?

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/343 and https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#imageframe.

**Comment by Chandra-Mauli-Sharma** [comment]
Sorry for the late reply. Actually, I am receiving these errors after implementing the solutions.
![image](https://user-images.githubusercontent.com/75089529/188456502-1417d9d5-cf15-4da7-a1b6-51cade5b2de9.png)

**Comment by Chandra-Mauli-Sharma** [comment]
Thanks for the help @homuler

**Comment by NeerajMehta** [comment]
@Chandra-Mauli-Sharma Were you able to achieve this? Can you help me on the same
