### ISSUE TITLE
Does MediaPipe Unity Plugin support detect two pose?

### ISSUE THREAD

**Issue by nhoknhutnhat95** [homuler/MediaPipeUnityPlugin#726]
### Feature Description

My project detected 1 pose. Now, how do I want to detect 2 poses?

**Comment by ROBYER1** [comment]
Surely this is a question for Google Mediapipe team, not Homuler

**Comment by homuler** [comment]
Related to https://github.com/homuler/MediaPipeUnityPlugin/issues/650#issuecomment-1184562632
