### ISSUE TITLE
Standalone Build (Sample Scene) fails to initialize

### ISSUE THREAD

**Issue by Valtech-Stockwell** [homuler/MediaPipeUnityPlugin#727]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.8f1

### Your Host OS

Windows 11 Pro

### Target Platform

Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

VC++ Redist: 2010 (10.0.40219), 2012 (11.0.61030), 2013 (12.0.30501), 2015-2022 (14.32.31332)
Windows SDK Addon: 10.1.0.0
.NET SDK: x86 (6.0.101), x64 (60.0.400)

### Command Sequences

Using Pre-packaged libraries

### Log

[Player.log - Changing Input](https://github.com/homuler/MediaPipeUnityPlugin/files/9445402/Player.log)
[Player.log - No Change](https://github.com/homuler/MediaPipeUnityPlugin/files/9445412/Player.log)
[Player.log - Load DLL via script](https://github.com/homuler/MediaPipeUnityPlugin/files/9445502/Player.log)

### Additional Context

Possibly Related: [Issue 401](https://github.com/homuler/MediaPipeUnityPlugin/issues/401)

I am running the Hand Tracking sample scene within unity with no issues. Tracking initializes as one would expect.
Building the system to either iOS or Windows Standalone produces the same 'silent error'.

Once the app starts, the webcam fails to initialize. On windows (Easier to test and debug) this can be `fixed*` by opening the camera settings (from the footer on the sample app), changing the dropdown from Webcam to anything else and swapping back. In doing so the webcam will initialize, but Mediapipe still seems to be down for the count.

Note:
- The player log seems to fail silently, but when you change from Webcam -> Image -> Webcam it does throw a null reference exception that you can see in the above logs
- Nothing is shown in the sample scene console in the stand alone, but in editor it Initializes the bootstrap.
- As far as I can tell this is not a [DLL Not Found Error](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception). I have ran through the troubleshooting and:
-- The library is under the correct folder (myApp_Data/Plugins/x86_64/mediapipe_c.dll)
-- The Managed plugin are in the correct folder (myApp_Data/Managed/{Google.Protobuf.dll, Mediapipe.Runtime.dll})
-- The libraries are compatible with my device (they work in editor)
-- The results of the `ldd` command shows all dependencies as found with valid paths
-- `mediapipe_c.dll`'s load on startup flag can be ticked on and no errors are displayed in the player logs
-- `Custom LoadLibrary()` script from the troubleshooting example does show that the DLL fails to load both in editor and in standalone, but proceeds to still function in editor. (Possible error on my part in implementation)

**Comment by homuler** [comment]
> Building the system to either iOS or Windows Standalone produces the same 'silent error'.

Check the `Development Build`. Otherwise, the logging code will be stripped.

The sample scenes are configured such that
- if the plugin was built in this repository, each scene works on every supported platforms by default.
- if the plugin was imported to another repository, each scene works on UnityEditor by default, but needs more work to run on other platforms.

I think you should have switched `Asset Loader Type` to `StreamingAssets` to fix compile errors, but you also need to copy dependent assets to the `StreamingAssets` folder (cf. #681, #708).

See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#load-model-files.
> :warning: To use `StreamingAssetResourceManager`, you need to place dependent assets under `Assets/StreamingAssets`. You can usually copy those assets from `Packages/com.github.homuler.mediapipe/Runtime/Resources`.

**Comment by Valtech-Stockwell** [comment]
> Check the `Development Build`. Otherwise, the logging code will be stripped.

Good catch, sorry to waste your time on that part. I should have gone there first.

> * if the plugin was imported to another repository, each scene works on UnityEditor by default, but needs more work to run on other platforms.

You are correct. I built your project as a bundle and imported it into mine stripping out un-needed scenes and objects.

> I think you should have switched `Asset Loader Type` to `StreamingAssets` to fix compile errors, but you also need to copy dependent assets to the `StreamingAssets` folder (cf. #681, #708).

Leaving it on local did not cause any compile errors, it was left on local. Changing it to Streaming and copying in `Assets/StreamingAssets` seems to have done the trick.

----

**Restatement of Problem;**
Standalone executable does not initialize webcam or bootstrap

**Environment Setup:**
Pre-built libraries and scene exported as an assetbundle and imported into a new project.

**Solution:**
- Rebuild in development to see actual errors
- Solution -> Bootstrap -> AssetLoaderType: Change to 'Streaming Assets'
- Copy `Assets/StreamingAssets` from master to my project
- Solution -> Bootstrap -> PreferableInferenceMode: Change to 'CPU' (This might just be bad testing on my part)

**Comment by ROBYER1** [comment]
> > Building the system to either iOS or Windows Standalone produces the same 'silent error'.
> 
> Check the `Development Build`. Otherwise, the logging code will be stripped.
> 
> The sample scenes are configured such that
> 
> * if the plugin was built in this repository, each scene works on every supported platforms by default.
> * if the plugin was imported to another repository, each scene works on UnityEditor by default, but needs more work to run on other platforms.
> 
> I think you should have switched `Asset Loader Type` to `StreamingAssets` to fix compile errors, but you also need to copy dependent assets to the `StreamingAssets` folder (cf. #681, #708).
> 
> See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#load-model-files.
> 
> > ⚠️ To use `StreamingAssetResourceManager`, you need to place dependent assets under `Assets/StreamingAssets`. You can usually copy those assets from `Packages/com.github.homuler.mediapipe/Runtime/Resources`.

It would be useful if this was somewhere in the introduction of the tutorials or getting started or a section about exporting a build of the sample app maybe? To the end user it is clear the plugin works fine when in the editor but when simply exporting a build of the sample app with the Asset Loader Type set to Local and it doesn't run, it isn't clear what the issue is with the sample project.
