### ISSUE TITLE
Updating ResourceManager

### ISSUE THREAD

**Issue by FarzanAlipour** [homuler/MediaPipeUnityPlugin#732]
### Description

Hi,
I'm trying to restart Mediapipe in the app but I get the ResourceManager can be initialised once exception
how can i unload or update ResourceManager?
thanks for your help ^^

**Comment by homuler** [comment]
> how can i unload or update ResourceManager?

`ResourceManager` cannot determine if it can be destroyed safely or not at any given time, so it can be initialized only once for simplicity.
You can unload `ResourceManager`, but you cannot initialize another instance after.
The sample app avoids this error by storing the only `ResourceManager` instance in a static class.
https://github.com/homuler/MediaPipeUnityPlugin/blob/d2608ea69676db2a798402a42e00abb9684d1252/Assets/MediaPipeUnity/Samples/Common/Scripts/AssetLoader.cs#L13

> I'm trying to restart Mediapipe in the app

What do you mean by "restart Mediapipe"?
Do you want to reload a scene?

**Comment by FarzanAlipour** [comment]
Thanks for your response.
yes I want to reload the Pose tracking sample scene and before that I stopped PoseTrackingSolution and disposed the gpu manager using GpuManager.ShutDown 
this exception is raised when Bootstrap class wants to provide a new StreamingAssetsResourceManager
`if (_IsInitialized)
        {
          throw new InvalidOperationException("ResourceManager can be initialized only once");
        }`

**Comment by homuler** [comment]
The `Bootstrap` class is implemented for _only_ the sample app and isn't intended to be loaded twice (the main purpose is to enable us to modify common behaviors (e.g. Asset Loader Type) easily from the UnityEditor).
In the sample app, `Bootstrap` class is attached to a global object in the Start Scene, but it's also attached (but disabled by default) to a `Solution` object in each scene.
https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/Assets/MediaPipeUnity/Samples/Scenes/Start%20Scene.unity#L141-L142
https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/Assets/MediaPipeUnity/Samples/Scenes/Face%20Detection/Face%20Detection.unity#L465

When each scene is started directly (`Start Scene` is not used), then the `Bootstrap` class that is attached to the `Solution` object is enabled.
https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/Assets/MediaPipeUnity/Samples/Common/Scripts/Solution.cs#L104

If you want to start a sample scene directly and reload it thereafter, you need to make sure the `Bootstrap` component is initialized only once.
But as I mentioned earlier, the `Bootstrap` class (and `PoseTrackingSolution` that depends on it) is not intended to be used out of the sample app, I recommend you only reuse the `PoseTrackingGraph` (see also [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial)).

**Comment by FarzanAlipour** [comment]
my project wasn't updated with latest changes in the repo.

https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/GpuManager.cs#L136

this line fixed the issue
