### ISSUE TITLE
Couldnot load library. 

### ISSUE THREAD

**Issue by sanamsta** [homuler/MediaPipeUnityPlugin#734]
### Description

Created xcode build but build is only working on same mac(intel) and when i tried to run the xcode build in another mac, couldnot load library error occured.

Build command i used : python build.py build --desktop cpu --opencv cmake --macos_universal -vv

<img width="1013" alt="Screen Shot 2022-09-02 at 11 37 37 AM" src="https://user-images.githubusercontent.com/14182332/188409049-87c8f841-4e8d-4fae-ac56-a6ebafec0003.png">

**Comment by homuler** [comment]
Please use [the Build/Install issue form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build-install-issue.yml).

See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#dllnotfoundexception.
> If the error occurs on UnityEditor, try loading `{lib}mediapipe_c.{so,dylib,dll}` on startup.

Usually, some helpful log will be output in your UnityEditor console.

P.S. If your target OS version is less than that of the machine used to build the library (e.g. target: macOS 11.x, built on macOS 12.x), then `libmediapipe_c.dylib` would be incompatible.
