### ISSUE TITLE
IOS Build rejected by apple: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [homuler/MediaPipeUnityPlugin#736]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.7f1

### Your Host OS

macOS 12.4 (Monterey)

### Target Platform

iOS

### [iOS Only] XCode Version

Xcode 13.4.x 

### Command Sequences

Build iOS application

### Log

ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

### Additional Context

Hi,
I had successfully built an application with the Mediapipe Unity plugin for iOS.
However, it is rejected from Apple validation, and mail is saying:
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

Mediapipe Unity plugin is the only plugin in the application.
Could you please help me recognize what is cause for this issue and how to solve this?

**Comment by philiprkk** [comment]
I'm not entirely sure if this is the issue but make sure you set the bundle_id here before you build the plugin:
D:\Repositories\MPUP093\MediaPipeUnityPlugin\bazel-mediapipeunityplugin\mediapipe_api\objc\BUILD

`# Copyright (c) 2021 homuler
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

load("@build_bazel_rules_apple//apple:ios.bzl", "ios_framework")

objc_library(
    name = "mediapipe_c_ios",
    sdk_frameworks = [
        "Accelerate",
        "AVFoundation",
        "CoreVideo",
        "CoreGraphics",
        "CoreMedia",
        "GLKit",
        "OpenGLES",
        "QuartzCore",
    ],
    deps = [
        "//mediapipe_api:mediapipe_c",
        "@ios_opencv//:OpencvFramework",
    ],
)

ios_framework(
    name = "MediaPipeUnity",
    bundle_id = "PLEASE_SET_YOUR_BUNDLE_ID_HERE.MediaPipeUnity",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Info.plist"],
    minimum_os_version = "11.0",
    visibility = ["//visibility:public"],
    deps = [
        ":mediapipe_c_ios",
    ],
)
`
