### ISSUE TITLE
Problem with running pose estimation solution on IOS

### ISSUE THREAD

**Issue by likwifi** [homuler/MediaPipeUnityPlugin#737]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

20221.3.8f1

### Your Host OS

mac OS m1

### Target Platform

iOS

### Description

Hello,
I'm trying to run the pose solution on IOS but receiving the following errors.
Code attached in next section, appreciate it if you can suggest what's the problem.
Ideally, I would like to see my webcam as an output stream and get Landmarks only with no segmentation etc. 
Not sure how to do that in GPU config text.

`MediaPipeUnityPlugin[676:28418] Errors found! Invalidating cache...
2022-09-06 16:15:11.852902+0400 MediaPipeUnityPlugin[676:28418] [Metal Compiler Warning] Warning: Compilation succeeded with: 

program_source:16:24: warning: writable resources in non-void vertex function
  vertex TextureVertex vertexShader(
                       ^
program_source:18:22: note: writable buffer defined here
      device float4* tex_coords [[buffer(1)]],`

### Code to Reproduce the issue

[pose_tracking_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9496810/pose_tracking_gpu.txt)
[PoseEstimation.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9496828/PoseEstimation.txt)

**Comment by homuler** [comment]
Please attach the complete log.

**Comment by likwifi** [comment]
![IMG_5021](https://user-images.githubusercontent.com/1791670/188668942-b742688e-59b9-44ca-ac0f-cca3134cb5b8.PNG)
[mediapipe.log](https://github.com/homuler/MediaPipeUnityPlugin/files/9498182/mediapipe.log)

Attached log and also screenshot.

**Comment by likwifi** [comment]
Found correct graph config from media pipe repository.
Attaching it and closing this.
Thanks.
[pose_tracking_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9498737/pose_tracking_gpu.txt)
