### ISSUE TITLE
How to use a custom camera

### ISSUE THREAD

**Issue by bbq82828** [homuler/MediaPipeUnityPlugin#738]
### Description

Hi 
I have a custom camera I want it to replace the webcam and be able to implement the mediapipe function through this camera

**Comment by homuler** [comment]
You may need to build [`ImageFrame`](https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#imageframe) instances using the input.
See also #343.

**Comment by bbq82828** [comment]
Sorry for replying so late 
I am currently rendering the camera image to RawImage and I want to pass the texture2d of the image to the mediapipe for use, but the image will only move when the camera is initialized 
I would like to ask how to make him execute continuously
The picture below shows me rewriting WebcamSource and replacing it with rawimage input
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/56858145/189788583-c53d6774-114c-4168-9846-41c2501f7d22.png">

**Comment by homuler** [comment]
Sorry, I don't understand your situation precisely.
What is your input class (e.g. `WebCamTexture`)? What you need to do is to build an `ImageFrame` instance using that.

**Comment by bbq82828** [comment]
Sorry, maybe I didn’t make it clear enough. I got a texture2D from my  custom camera  and I pass it into ReadFromImageSource but the result I get is that the mediapipe's image is only rendered when my camera is initialized, after that the mediapipe's image is still
<img width="846" alt="image" src="https://user-images.githubusercontent.com/56858145/190037145-26b66cb2-fa36-4384-8e0e-00bd6078ef25.png">
 As for ImageFrame I am trying using that.

**Comment by bbq82828** [comment]
I just solved the problem
I sent Textur2d to the past, but I didn't keep updating texure2d, so in order to solve it, I kept inputting the transmitted picture in my camera
Thanks for taking the time to reply
<img width="577" alt="image" src="https://user-images.githubusercontent.com/56858145/190044130-6c3f415d-4c51-4a74-8723-6b5cf7f761fd.png">

**Comment by zzanyoung** [comment]
@bbq82828 Hello,
I am currently working on a similar problem as you are and trying to find a solution. If it's not too much trouble, could you provide any hints or code snippets on how to use the data from a custom camera that renders on a RawImage for mediapipe? Thank you

**Comment by bbq82828** [comment]
@zzanyoung Hello, 
You must first find GetCurrentTexture() in WebCamSource and replace webCamTexture with the texture2D of your custom camera
<img width="350" alt="截圖 2023-04-18 下午2 15 43" src="https://user-images.githubusercontent.com/56858145/232688612-ade92c41-6fc2-409c-b032-50ff4e9a5934.png">

**Comment by zzanyoung** [comment]
@bbq82828 Thank you for your response. However, I tried to write a script based on the code in #738, but it doesn't work. I am using a Texture2D input from a UVC camera. So, I changed the code to use Texture2d instead. But when I build the modified project for Android, a white or gray screen occurs. Can you provide any tips here as well? Thank you again for your response :)
