### ISSUE TITLE
iOS Build Camera Not Working

### ISSUE THREAD

**Issue by glibshchur** [homuler/MediaPipeUnityPlugin#74]
Hello!
Trying to launch mediapipe in iOS device.
Unfortunately, I can't get any image from the camera at all. I can see all cameras of the device in the dropdown menu but none of them shows an image.
Getting next log from xCode: 
**GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A12Z GPU
Initialize engine version: 2019.4.12f1 (225e826a680e)
2021-03-02 14:49:39.825667+0200 tracker[8640:7064262] Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x106f3e200>.
UnloadTime: 1.579708 ms
Graph Changed: Face Detection
GraphSelectorController:OnValueChanged(Dropdown)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

WebCamDevice Changed: Back Camera
WebCamDeviceSelectorController:OnValueChanged(Dropdown)
<Start>d__2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

WebCamTexture Graphics Format: B8G8R8A8_UNorm
<ResetScreen>d__16:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
SceneDirector:ResetCamera(Nullable`1)
SceneDirector:ChangeWebCamDevice(Nullable`1)
WebCamDeviceSelectorController:OnValueChanged(Dropdown)
<Start>d__2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unable to open archive file: /private/var/containers/Bundle/Application/E9F69230-C529-425D-B34D-04FD68CF7390/tracker.app/Data/Raw/mediapipe
Mediapipe.AssetBundleManager:LoadAssetBundle()
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[ line 584] 
(Filename:  Line: 584)

Failed to read data for the AssetBundle 'mediapipe'.
Mediapipe.AssetBundleManager:LoadAssetBundle()
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean)
DemoGraph:Initialize()
<RunGraph>d__23:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[ line 449] 
(Filename:  Line: 449)

NullReferenceException: Object reference not set to an instance of an object.
  at Mediapipe.AssetBundleManager.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) [0x00000] in <00000000000000000000000000000000>:0 
  at DemoGraph.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at SceneDirector+<RunGraph>d__23.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)**

![telegram-cloud-photo-size-2-5328155090059637392-y](https://user-images.githubusercontent.com/36221261/109649978-44bbbe00-7b65-11eb-98f4-d216703c32ad.jpg)

**Comment by dayowoo** [comment]
How did you solve it?
