### ISSUE TITLE
Android app doesn't track hand landmarks

### ISSUE THREAD

**Issue by KornilovaK** [homuler/MediaPipeUnityPlugin#740]
### Description

I want to export android app. What I do: 
![image](https://user-images.githubusercontent.com/86467512/189123681-2f7a6087-5b47-4856-85d0-e0083cf54aca.png)
in the ```StreamingAssets``` folder I added hand tracking scene, .bytes files and handedness.txt, also in the selected ```Streaming Assets```
In the  ```BuildingSettings```  I ticked Start scene and HandTracking and app is built without problems. To android it's installed successfully too. It doesn't crash, but when I start it the landmarks aren't been drawn.
My first thought was that the problem is in the code, to which I made some changes. However in unity everything works fine. Moreover, when I tried to export it by the ```Development Build``` there weren't any errors in the console

**Comment by homuler** [comment]
> Moreover, when I tried to export it by the `Development Build` there weren't any errors in the console

Please use [the Build/Install issue form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build-install-issue.yml) and share the log.
