### ISSUE TITLE
Query on creating Managed Plugin for Mediapipe

### ISSUE THREAD

**Issue by aadityasp** [homuler/MediaPipeUnityPlugin#742]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.4f1

### Your Host OS

macOS Monterey 12.4

### Target Platform

Windows Standalone, Mac Standalone, Android, iOS

### Description

Hi @homuler, I'm pretty new to C# and I'm trying to understand the structure of this project. Please excuse my ignorance.
I see that you developed a Native plugin which is converting the c/c++ code from mediapipe to C#. There are a lot of C# functions with documentation(in API overview) on how to use them which is great! I'd like to create a managed plugin so that I just import all of these C# scripts in your project as a dll into my new project, is it possible to do that? If yes, could you please guide me on how to create a single dll of all of the C# scripts?

I just want to create a single dll and refer to your documentation on how to call various functions via a dll.

**Comment by homuler** [comment]
You may want to see https://github.com/vignetteapp/MediaPipe.NET.
