### ISSUE TITLE
Use Face_Geometry based on Face_Mesh

### ISSUE THREAD

**Issue by wizVR-zhangjun** [homuler/MediaPipeUnityPlugin#743]
### Plugin Version or Commit ID

v010.1

### Unity Version

2021.3.4f1

### Your Host OS

windows10

### Target Platform

Windows Standalone

### Description

I can get the face_mesh landmark on Windows, and they can work normally. I now want to get the pose matrix, scale, rotation, translation , Can I use the same method on Windows? To get it?

**Comment by homuler** [comment]
Maybe same as #753
