### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by HEKEPOIU** [homuler/MediaPipeUnityPlugin#744]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

windows 11 

### Target Platform

UnityEditor, Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

VS2022
WinSDK VER:10.0.22621.0

### Command Sequences

open project,and...
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/101374163/190863772-ad99a063-0297-4773-8444-7555e76550c0.png">

### Log

python build.py build --desktop cpu --opencv=cmake -v
<img width="741" alt="image" src="https://user-images.githubusercontent.com/101374163/190863613-b8626edd-35d5-4299-ae99-8b07c53f8c23.png">

### Additional Context

Python 3.10.6
bazel 5.3.0
nuget 6.2.1.2
Opencv 4.6.0

when I follow Installation Guide done every thing I have to do, and unity editor pop up error massage.
is it can run on win11?

**Comment by HEKEPOIU** [comment]
Update : I install the JAVE SDK, and I happen another problem.
bazel crashed due to an internal error.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/101374163/190887806-17b9c43a-8c90-4deb-b7d0-73572b52b323.png">

**Comment by homuler** [comment]
Intersting. At least, you should not use `python` installed by MSYS2, but I don't know the exact cause.

However, I can confirm it can be built on Windows 11 (see [GitHub Actions status](https://github.com/homuler/MediaPipeUnityPlugin/actions); it runs on Windows 10, but the configuration is the same essentially), and currently, you don't need to build the plugin on your local machine (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/696#issuecomment-1211893052), so I close the issue.
If you still want to build it on your local machine, see https://github.com/homuler/MediaPipeUnityPlugin/blob/30cd149d191b3ec2c672d420557a879fe528c459/.github/workflows/windows-test.yml
