### ISSUE TITLE
tflite file loading registration

### ISSUE THREAD

**Issue by fishhead012** [homuler/MediaPipeUnityPlugin#745]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.5f1

### Your Host OS

window10

### Target Platform

Windows Standalone

### Description

The resource manager has been changed to apply to existing games.

And I ran into a bug.

Can I know the timing of the tflite file loading registration?

//--------------------------------------------------------------------------------
Calculator::Open() for node "holisticlandmarkcpu__handlandmarksleftandrightcpu__handlandmarksfromposecpu_2__handlandmarkcpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: ; Can't find file: mediapipe/modules/hand_landmark/hand_landmark_full.tflite
Calculator::Open() for node "holisticlandmarkcpu__poselandmarkcpu__poselandmarkbyroicpu__poselandmarkmodelloader__LocalFileContentsCalculator" failed: ; Can't find file: mediapipe/modules/pose_landmark/pose_landmark_lite.tflite
Calculator::Open() for node "holisticlandmarkcpu__handlandmarksleftandrightcpu__handlandmarksfromposecpu_1__handlandmarkcpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: ; Can't find file: mediapipe/modules/hand_landmark/hand_landmark_full.tflite
Calculator::Open() for node "holisticlandmarkcpu__facelandmarksfromposecpu__facelandmarkcpu__facelandmarksmodelloader__LocalFileContentsCalculator" failed: ; Can't find file: mediapipe/modules/face_landmark/face_landmark.tflite
Calculator::Open() for node "holisticlandmarkcpu__poselandmarkcpu__posedetectioncpu__inferencecalculator__holisticlandmarkcpu__poselandmarkcpu__posedetectioncpu__InferenceCalculator" failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite

### Code to Reproduce the issue

// Text object read from existing resource manager
mp_api__ConvertFromCalculatorGraphConfigTextFormat(configText, &serializedProto)

// then
mp_CalculatorGraph__Initialize__PKc_i(mpPtr, serializedProto._str, serializedProto.length, &statusPtr);

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/632#issuecomment-1171025814 to know how the `ResourceManager` works.

> The resource manager has been changed to apply to existing games.

Then please describe that change in the `Code to Reproduce the issue` section.

> // Text object read from existing resource manager
> mp_api__ConvertFromCalculatorGraphConfigTextFormat(configText, &serializedProto)
> 
> // then
> mp_CalculatorGraph__Initialize__PKc_i(mpPtr, serializedProto._str, serializedProto.length, &statusPtr);

Describe the change in such a way that we can reproduce the issue on our local machine.
The above code is not relevant to the `ResourceManager` class.
