### ISSUE TITLE
cl error

### ISSUE THREAD

**Issue by mostafamdy** [homuler/MediaPipeUnityPlugin#746]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

.

### Your Host OS

Windows 11

### Target Platform

UnityEditor, Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

WINSDK=10.0.19041.0
VC_FULL_VERSION=14.29.30133

### Command Sequences

running 
`python build.py build --desktop cpu --opencv cmake  -vv`
in cmd get PYTHON_BIN_PATH error 

> Configuration Error: --define PYTHON_BIN_PATH='C://Users//mo//PycharmProjects//pythonProject//venv//Scripts//python.exe' is not executable. Is it the python binary?

I found  solution for this error by running on git bash 
but I get another error on 

> cl : Command line error D8022 : cannot open 'bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params'
> Target //mediapipe_api:mediapipe_desktop failed to build

note I tried to clone[ mediepipe repo](https://github.com/google/mediapipe)  and build hello world example it works well

### Log

mo@mostafa MINGW64 /d/unityMediapipe/MediaPipeUnityPlugin-master/MediaPipeUnityPlugin-master
$ python build.py build --desktop cpu --opencv cmake  -vv
Loading:
Loading: 0 packages loaded
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
Analyzing: target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured)
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 1.664s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Feeds used:
  C:\Users\mo\.nuget\packages\
  https://api.nuget.org/v3/index.json

All packages listed in D:\unityMediapipe\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\packages.config are already installed.
Loading:
Loading: 0 packages loaded
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
Analyzing: target //mediapipe_api:mediapipe_assets (0 packages loaded, 0 targets configured)
INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 54 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //mediapipe_api:mediapipe_assets up-to-date:
  bazel-bin/mediapipe_api/mediapipe_assets.zip
INFO: Elapsed time: 1.217s, Critical Path: 0.05s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/pdos7adc/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
Loading:
Loading: 0 packages loaded
INFO: Build options --@opencv//:switch and --define have changed, discarding analysis cache.
Analyzing: target //mediapipe_api:mediapipe_desktop (0 packages loaded, 0 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/a0ec971de0dc82e0bf8784393cb8c4a56c171045.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: C:/_bzl/pdos7adc/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: C:/_bzl/pdos7adc/external/com_google_mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule @com_google_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (0 packages loaded, 20475 targets configured).

INFO: Found 1 target...
[0 / 3] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[192 / 1,087] checking cached actions
[516 / 1,446] [Prepa] Linking external/com_github_glog_glog/glog.lib [for tool]
[1,303 / 2,267] Linking external/com_google_mediapipe/mediapipe/framework/tool/encode_as_c_string.exe [for tool]; 30s local ... (128 actions, 6 running)
INFO: From Linking external/flatbuffers/flatc.exe [for tool]:
LINK : warning LNK4001: no object files specified; libraries used
INFO: From Compiling absl/flags/commandlineflag.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
INFO: From Compiling absl/flags/usage_config.cc:
cl : Command line warning D9025 : overriding '/w' with '/W3'
ERROR: C:/_bzl/pdos7adc/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/BUILD:98:24: Compiling external/com_google_mediapipe/mediapipe/modules/objectron/calculators/lift_2d_frame_annotation_to_3d_calculator.pb.cc [for tool] failed: (Exit 2): cl.exe failed: error executing command (from target @com_google_mediapipe//mediapipe/modules/objectron/calculators:lift_2d_frame_annotation_to_3d_calculator_cc_proto)
  cd /d C:/_bzl/pdos7adc/execroot/mediapipe_api
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\mo\AppData\Local\Temp
    SET TMP=C:\Users\mo\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params
# Configuration: 2f594a253a1e095db2b41edd6cfc6804e274cf3518620b0ec7103049410f18a5
# Execution platform: @local_execution_config_platform//:platform
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30143 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8022 : cannot open 'bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_mediapipe/mediapipe/modules/objectron/calculators/_objs/lift_2d_frame_annotation_to_3d_calculator_cc_proto/lift_2d_frame_annotation_to_3d_calculator.pb.obj.params'
Target //mediapipe_api:mediapipe_desktop failed to build
INFO: Elapsed time: 243.711s, Critical Path: 47.10s
INFO: 202 processes: 185 internal, 17 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//mo//PycharmProjects//pythonProject//venv//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
DEBUG (build.py): Copying '.nuget\Google.Protobuf.3.20.0\lib\netstandard2.0\Google.Protobuf.dll' to 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll' to 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll' to 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Copying '.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll' to 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//mo//PycharmProjects//pythonProject//venv//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_assets`
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'build\Resources'...
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'Assets\StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//mo//PycharmProjects//pythonProject//venv//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake_static //mediapipe_api:mediapipe_desktop`
Traceback (most recent call last):
  File "D:\unityMediapipe\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 469, in <module>
    Argument().command().run()
  File "D:\unityMediapipe\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 141, in run
    self._run_command(self._build_desktop_commands())
  File "D:\unityMediapipe\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Users\mo\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://Users//mo//PycharmProjects//pythonProject//venv//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake_static //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

**Comment by mostafamdy** [comment]
ok I tried to build for facemesh only and it's working good 
I used this command 
`python build.py build --desktop cpu --opencv cmake --solutions face_mesh -vv`

**Comment by homuler** [comment]
> > Configuration Error: --define PYTHON_BIN_PATH='C://Users//mo//PycharmProjects//pythonProject//venv//Scripts//python.exe' is not executable. Is it the python binary?

It seems that this error can occur when `bash` is not resolved to `C:\msys64\usr\bin\bash` (e.g. `C:\Windows\System32\bash.exe`).
