### ISSUE TITLE
'MediaPipeException: MediaPipe Aborted' on Android

### ISSUE THREAD

**Issue by G93-7** [homuler/MediaPipeUnityPlugin#752]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.10f1

### Your Host OS

Windows 10

### Target Platform

Android

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.3
NDK. r21d

### Command Sequences

[HolisticGPU.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9636749/HolisticGPU.txt)
[holistic_graph_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9636739/holistic_graph_gpu.txt)

### Log

MediaPipeException: MediaPipe Aborted, refer glog files for more details
at Mediapipe.MpReturnCodeExtension.Assert (Mediapipe.MpReturnCode code) [0x0002f] in <d24e9f466dc24aec8932e0c7beddfafc>:0 
at Mediapipe.CalculatorGraph..ctor (System.Byte[] serializedConfig) [0x00012] in <d24e9f466dc24aec8932e0c7beddfafc>:0 
at Mediapipe.CalculatorGraph..ctor (Mediapipe.CalculatorGraphConfig config) [0x00007] in <d24e9f466dc24aec8932e0c7beddfafc>:0 
at Mediapipe.CalculatorGraph..ctor (System.String textFormatConfig) [0x0000c] in <d24e9f466dc24aec8932e0c7beddfafc>:0 
 at Mediapipe.Unity.Test.HolisticGPU+<Start>d__12.MoveNext () [0x001a9] in <404d0fb366b74c33b334f1a2136a623b>:0 
at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <a960d8def81c47b88e2442adc0b94113>:0 

[full log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9636776/full.log.txt)

### Additional Context

I want to run MediaPipe Holistic on Android. The goal of the project is to draw body, face and hand landmarks on frames and get landmark coordinates. So, I have built an android apk file in unity. But when I run the app on android smartphone it shows the blank screen. In the android logcat I see the following error: 
`MediaPipeException: MediaPipe Aborted, refer glog files for more details`

In unity I used MediaPipeUnityPlugin pre-built package released [here](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1).

At first I have created c# script and the graph to run MediaPipe Holistic on CPU. Hovewer, I later revealed [this issue ](https://github.com/homuler/MediaPipeUnityPlugin/issues/206) and thought it might be mandatory to use GPU on android. So, I changed the files, but got the same result.

The Unity scene contains a canvas screen and an empty gameobject. I attached c# script named 'HolisticGPU' and a graph named 'holistic_graph_gpu' to that gameobject. These files are attached to the issue.

I wonder what might be the cause of this error. Thank you in advance!

**Comment by homuler** [comment]
There may be a bug in your config.
Try validating the graph first (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/645#issuecomment-1179986503).

**Comment by G93-7** [comment]
I have validated the graph config as advised by @homuler. 

```
//_graph = new CalculatorGraph(_configAsset.text);

var config = CalculatorGraphConfig.Parser.ParseFromTextFormat(_configAsset.text);
Debug.Log("before validatedGraphConfig");
using (var validatedGraphConfig = new ValidatedGraphConfig())
{
    Debug.Log("before Initialize");
    validatedGraphConfig.Initialize(config).AssertOk();
    Debug.Log("before CalculatorGraph");
    _graph = new CalculatorGraph(validatedGraphConfig.Config());
}
```

After that, I got the following error in a bit more understandable form:

`MediaPipeException: UNKNOWN: Input stream "transformed_input_video_gpu" of calculator "[ImagePropertiesCalculator, input stream: IMAGE:transformed_input_video_gpu, and output stream: SIZE:image_size]" expects packets of type "OneOf<::mediapipe::Image, mediapipe::ImageFrame>" but the connected output stream will contain packets of type "mediapipe::GpuBuffer"`

I have found that a calculator named `ImagePropertiesCalculator `expects packets of type `Image `or `ImageFrame `but I have passed a packet of type `GpuBuffer`. So, I have made `transformed_input_video `the input of `ImagePropertiesCalculator` instead of `transformed_input_video_gpu`. After running the graph I found that the same problem was true for `AnnotationOverlayCalculator`. So, I have changed the sequence of nodes. I put `GpuBufferToImageFrameCalculator `after `HolisticLandmarkGpu `calculator. It returned `transformed_input_video_imageframe `which is of type `Imageframe`. I have attached it to `AnnotationOverlayCalculator`. 

After that I got the following errors:
```
MediaPipeException: FAILED_PRECONDITION: Graph has errors: 
Calculator::Open() for node "holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__inferencecalculator__holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__InferenceCalculator" failed: Failed to read /storage/emulated/0/Android/data/com.DefaultCompany.TestHolisticPCGPU/files/pose_detection.bytes
Calculator::Open() for node "holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read /storage/emulated/0/Android/data/com.DefaultCompany.TestHolisticPCGPU/files/hand_landmark_full.bytes
Calculator::Open() for node "holisticlandmarkgpu__poselandmarkgpu__poselandmarkbyroigpu__poselandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read /storage/emulated/0/Android/data/com.DefaultCompany.TestHolisticPCGPU/files/pose_landmark_lite.bytes
Calculator::Open() for node "holisticlandmarkgpu__facelandmarksfromposegpu__facelandmarkgp
```

I guessed that it could not load model files. So, I have loaded them manually in the script. 

```
_resourceManager = new StreamingAssetsResourceManager();
            yield return _resourceManager.PrepareAssetAsync("pose_detection.bytes", "pose_detection.bytes", false);
            yield return _resourceManager.PrepareAssetAsync("pose_landmark_lite.bytes", "pose_landmark_lite.bytes", false);
            yield return _resourceManager.PrepareAssetAsync("hand_landmark_full.bytes", "hand_landmark_full.bytes", false);
            yield return _resourceManager.PrepareAssetAsync("hand_recrop.bytes", "hand_recrop.bytes", false);
            yield return _resourceManager.PrepareAssetAsync("handedness.txt", "handedness.txt", false);
            yield return _resourceManager.PrepareAssetAsync("face_landmark.bytes", "face_landmark.bytes", false);
            yield return _resourceManager.PrepareAssetAsync("face_detection_short_range.bytes", "face_detection_short_range.bytes", false);
            yield return _resourceManager.PrepareAssetAsync("face_landmark_with_attention.bytes", "face_landmark_with_attention.bytes", false);
```

And finally it worked!

The edited script and graph config files are attached to the comment. 
[HolisticGPU.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9675765/HolisticGPU.txt)
[holistic_graph_gpu_edited.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9675766/holistic_graph_gpu_edited.txt)

Thanks @homuler for the comment. It helped me find the reason of the error.

**Comment by G93-7** [comment]
Now there is another problem. Tracking starts after a few seconds of opening the app. Also, the image is shown rotated on the screen. As I rotate the phone and change the orientation it also changes but incorrectly. I attach the screenshots taken in all four cases of orientation.  

Portrait
![Portrait](https://user-images.githubusercontent.com/80401198/193071080-4f501f37-e10d-428d-9df4-d01261d093ca.png)

PortraitUpsideDown
![PortraitUpsideDown](https://user-images.githubusercontent.com/80401198/193071104-06f8d038-4d73-45e3-b0c8-471731d1efe7.png)

LandscapeLeft
![LandscapeLeft](https://user-images.githubusercontent.com/80401198/193071122-03902e30-d725-4953-b95c-9a2e7948d526.png)

LandscapeRight
![LandscapeRight](https://user-images.githubusercontent.com/80401198/193071141-0168f166-2f5c-4d36-bb0e-2965851fce12.png)

I think the latter problem is due to the change of the coordinate system when the orientation changes. I decided to rotate the image frame in the opposite direction in the graph config file. I used `rotation_mode `property given [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/image_transformation_calculator.proto). I added `rotation_mode `in the last node like this:

```
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:output_video_1"
  output_stream: "IMAGE:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      flip_horizontally: true,
      rotation_mode: ROTATION_270
      
    }
  }
}
```

But it did not work. Then I performed rotation in script. I have rotated `_outputPixelData `of type `Color32[]` returned from `outputPacket `. Then I passed rotated `_outputPixelData ` to `_outputTexture`. This approach worked. So, I have to manually rotate `_outputPixelData `in each case of screen orientation. 

Is there any other method to correctly render the image in every case of phone screen orientation?

**Comment by homuler** [comment]
Did you try the sample app and read the code?
At least, `ImageTransformationCalculator` will transform the output image correctly if it's given proper options, but in the first place, do you want to display the output image (annotated by MediaPipe) as it is?
In actual applications, I think you don't usually want to use annotated images.

**Comment by G93-7** [comment]
In my project there was used the rendered image returned by the graph. Now I have changed the project according to the [tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#annotation).  
But the image is still rotated. I want it to be correctly oriented in every case of screen orientation. 

I have set 640 and 480 to _width and _height accordingly in the inspector. So, the resolution of the image on the screen is 640x480. How can I display the image to fill the whole screen?

![result](https://user-images.githubusercontent.com/80401198/193826715-048f84ab-2383-4b69-8f4b-64cfb6a92dd1.png)

**Comment by homuler** [comment]
_Did you try the sample app and read the code?_
I think [the sample app](https://github.com/homuler/MediaPipeUnityPlugin#plate_with_cutlery-try-the-sample-app) already implemented exactly what you're trying to do.

> How can I display the image to fill the whole screen?

Please ask questions about Unity elsewhere (e.g. Unity Form).

**Comment by G93-7** [comment]
Sorry for the late reply,

> Did you try the sample app and read the code?
> I think [the sample app](https://github.com/homuler/MediaPipeUnityPlugin#plate_with_cutlery-try-the-sample-app) already implemented exactly what you're trying to do.

Yes, of course, I have tried the sample app. It works fine in the editor. I have written the code according to the [tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#official-solution) and [advanced topics](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Advanced-Topics). Holistic tracking works very well in the editor and in Windows executable. But on Android, the image is rotated as described above. 


> How can I display the image to fill the whole screen?
> 
> Please ask questions about Unity elsewhere (e.g. Unity Form).

The question was not general. It was about this certain project. Let me explain it in a bit more detail. 

The `_screen` gameobject displays an image with resolution `_width x _height` (640X480 in this case). As I guessed, `AutoFit.cs` script enlarges the image to fit the width or height of the screen. However, the quality of the image deteriorates. Is it possible to display the original image returned from the camera (with an unchanged resolution) and then draw landmarks on it?

**Comment by homuler** [comment]
> Yes, of course, I have tried the sample app. It works fine in the editor.

I mean, did you try the sample app _on Android_? Is the screen image rotated there, too?

> The `_screen` gameobject displays an image with resolution `_width x _height` (640X480 in this case). As I guessed, `AutoFit.cs` script enlarges the image to fit the width or height of the screen. However, the quality of the image deteriorates. Is it possible to display the original image returned from the camera (with an unchanged resolution) and then draw landmarks on it?

If you think there is a problem with `AutoFit.cs`, please file another issue.
However, it seems to me that there's a contradiction between what you are saying and what you are trying to do.

If you want to display the original image, then you must not resize the image. In this case, when the image size is small, it is expected that it will not fill the screen.
On the other hand, if you want a small image to fill the screen, you need to resize it. However, if the input image (e.g. 640x480) is smaller than the screen size (e.g. 2400x1080), the resized image should be rough, of course.
If you are still unhappy with the coarseness of the resized image, you need to increase the resolution of the camera.

And I think those things are not related to MediaPipe at all.
