### ISSUE TITLE
Face data mapping

### ISSUE THREAD

**Issue by wizVR-zhangjun** [homuler/MediaPipeUnityPlugin#753]
### Description

First of all, thank the staff for their hard work
I want to map the face data from Mediapipe to a 3D character model, but I don't have a viable solution. What should I do
@homuler Give me some advice if you don't mind

**Comment by homuler** [comment]
> What should I do

Retrieve the face landmark positions, and change your 3D model's parameters.
See also https://github.com/google/mediapipe/issues/1615.
