### ISSUE TITLE
Cannot push android application to playstore

### ISSUE THREAD

**Issue by aadityasp** [homuler/MediaPipeUnityPlugin#757]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.4f1

### Your Host OS

macOS Monterey 12.4

### Target Platform

Android

### Description

Hi, I'm trying to push an android application (which uses this plugin) to the play store, and it limits the .aab file to 150MB, the only huge file is the libmediapipe_jni.so file under arm64-v8a in the .aab file. I came across the fix from #65  , but as I'm having build issues on my m1 Mac, I used the pre built package provided in the latest v0.10.1 release. Is there a prebuilt package with symbol information stripped down from libmediapipe_jni.so ? Would really appreciate if anyone can help me by building a package with a smaller libmediapipe_jni.so 

Thanks!!

**Comment by homuler** [comment]
Maybe the simplest way is to fork this repository, modify the package workflow, and [run it](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/package.yml).
https://github.com/homuler/MediaPipeUnityPlugin/blob/30cd149d191b3ec2c672d420557a879fe528c459/.github/workflows/package.yml#L52

However, it looks like a problem that we should address, so I will distribute a version with symbols stripped later.

**Comment by aadityasp** [comment]
Thanks! I will try to run it, but looking forward to a version with smaller size.

**Comment by aadityasp** [comment]
> https://github.com/homuler/MediaPipeUnityPlugin/blob/30cd149d191b3ec2c672d420557a879fe528c459/.github/workflows/package.yml#L52
> 
Based on #65, I tried replacing the above line to             
`python build.py build --bazel_build_opts "--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0" --android arm64 --android_ndk_api_level 21 --strip_all -vv`

But looks like the build.py doesn't have --strip_all parameter. Is there another way to do it ?

**Comment by aadityasp** [comment]
`            python build.py build --bazel_build_opts "--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0" --android arm64 --android_ndk_api_level 21 --linkopt=-s -vv
`
This fixed it!! The mediapipe_android.aar is smaller now and I was able to push to play store! Thanks :)
