### ISSUE TITLE
Plugin does not work on Samsung Galaxy S22 Ultra

### ISSUE THREAD

**Issue by Paxios** [homuler/MediaPipeUnityPlugin#760]
### Plugin Version or Commit ID

v0.10.1 (downloaded from master)

### Unity Version

2021.3.8

### Your Host OS

macOS Monterey 12.6

### Target Platform

Android

### Target Device

Samsung Galaxy S22 Ultra

### [Android Only] Android Build Tools and NDK Version

Build tools: 30.0.3
NDK: 21.4.7075529

### Build Command

**python build.py build -c opt --linkopt=-s --desktop cpu --android armv7 --android_ndk_api_level 21 --solutions=pose**
I also tried:
**python build.py build -c opt --linkopt=-s --desktop cpu --android arm64 --android_ndk_api_level 21 --solutions=pose**

### Bug Description

Same build (apk) works fine on Samsung Galaxy Note 8 (GPU).

**What happens on S22 Ultra (GPU):** 
No pose estimation results are provided for ~ 45 seconds (feels like the graph would be loading). After that time the device restarts itself. Device performs a hard reset (turns off and on). I have a feeling that the device becomes a bit laggy (device's native animation aren't as smooth as they should be and a bit unresponsive) before it restarts. 

**What happens on Note 8:** 
It takes about 5 seconds for a graph to load and then runs normally as long as the app is open (tested it for 10 minutes).

It works fine on macOS (CPU) too.

### Steps to Reproduce the Bug

1. Build the plugin
2. Import it into the project
3. Install the device on S22 Ultra
4. Wait for a minute

### Log

There are no logs, only warning I get is:
**E/SOCL: /data/local/tmp/OCL19148T14.cl:63:27: warning: double precision constant requires cl_khr_fp64, casting to single precision
      FLT4 result = INIT_FLT4(0.0);**

But this is written a lot before the crash happens.

### Additional Context

I've been using this plugin for few months now and it worked perfectly on Samsung Galaxy Note 8. But recently, when I installed the app on Samsung Galaxy S22 Ultra the app stopped working.

I found one relateable bug on interneted. But that was linked to ARFoundation: https://forum.unity.com/threads/arfoundation-5-0-doesnt-work-on-samsung-s22-ultra.1247563/

I tried downloading and running https://google.github.io/mediapipe/solutions/hands.html#main-example and it works fine on S22 Ultra (it doesn't crash the device).

**Comment by homuler** [comment]
> Steps to Reproduce the Bug
> 1. Build the plugin
> 2. Import it into the project

Which project?
Will you try running the sample app? (not importing it into another project)

> There are no logs,

Please build the sample app with the `Development Build` enabled and run it again.
There should be logs, so share _the complete log_.

> Build Command
> python build.py build -c opt --linkopt=-s --desktop cpu --android arm64 --android_ndk_api_level 21 --solutions=pose

In general, when debugging, you should not strip the symbols.

**Comment by Paxios** [comment]
Hello.

Sorry for a late reply. As a project I was referencing to my own project (not public anywhere). I tried it with the sample app now, without stripping the symbols and same thing happened again. on S22 Ultra the face detection did not work and the app froze if I switched to another calculator in app (pose, hand, etc.). Same APK worked fine on Samsung galaxy Note 8.

logs: https://filebin.net/j6e707vjyma226gl

This time I did not use the master version, but I used https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.1

To build the plugin I used "python build.py build --android armv7 --desktop cpu --ios arm64 --android_ndk_api_level 21 -vv"

**Comment by Paxios** [comment]
It works if I:
1. Build with
> python build.py build -c opt --linkopt=-s --android arm64 
2. Open the sample project with Unity 2022.2.x. 
3. Build it as arm64 with IL2CPP
 
It works in my own project now too.
**The problem wasn't with the plugin, but the unity version**. It works after switching to 2022.2.x.

Looks like it is a Unity v2021 bug and not from UnityMediaPipePlugin 😄. I guess there's some misconfiguration with Unity v2021 and newer devices.

I'll let you close the ticket. Thanks for the help. I really appreciate it ❤️!
