### ISSUE TITLE
Build Failed For Android Platform in macOS

### ISSUE THREAD

**Issue by NeerajMehta** [homuler/MediaPipeUnityPlugin#761]
### Plugin Version or Commit ID

v0.8.10

### Unity Version

2022.1.19

### Your Host OS

macOS

### Target Platform

Android

### Description

While building for Android I am getting the below error. I have tried every possible issue like setting up Android SDK and NDK path. Please help me with this.
<img width="1440" alt="Screenshot 2022-10-09 at 10 37 49 PM" src="https://user-images.githubusercontent.com/7052504/194770107-b6f52b2a-f9e1-42a0-8bd1-ae17b945443a.png">

### Code to Reproduce the issue

/Users/neeraj/Projects/MediaPipeUnityPlugin-master/mediapipe_api/java/com/github/homuler/mediapipe/BUILD:10:14: While resolving toolchains for target //mediapipe_api/java/com/github/homuler/mediapipe:mediapipe_android_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type

**Comment by homuler** [comment]
> I have tried every possible issue like setting up Android SDK and NDK path.

In general, as far as the issue can be solved, the fact the issue has not been solved yet means that you've not tried everything, so please describe what you have done in detail.

The error message usually means that Android SDK is not properly installed or `ANDROID_HOME` is not set corretly. 
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#android-configuration.

Notice that
- you can download the built plugin from the release page and
- you can also [build a package with custom options using GitHub Actions](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml) (you need to fork this repository).

**Comment by NeerajMehta** [comment]
![Untitled](https://user-images.githubusercontent.com/7052504/194800437-55ec0895-94ad-4b25-9f1a-fad02576ab81.png)
Hi This is my Profile path where I have added Android SDK.

**Comment by homuler** [comment]
It looks to me that you're using `zsh`, not `bash`.
Does your current session really read `~/.bash_profile` file?

```sh
echo $ANDROID_HOME
```

**Comment by NeerajMehta** [comment]
Oh Yeah, I am using zsh not bash

**Comment by homuler** [comment]
So may I close the issue?

**Comment by homuler** [comment]
> Now I am working to detect a smile and another facial expression

Please ask questions about how to use MediaPipe in the official MediaPipe community.
I think you need to write your own calculator or learn a custom model.
