### ISSUE TITLE
Problems learning to use

### ISSUE THREAD

**Issue by ma6667** [homuler/MediaPipeUnityPlugin#762]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.11f1

### Your Host OS

Win11Pro

### Target Platform

UnityEditor, Windows Standalone

### Description

Hello, I would like to ask about facemask how I should go about it. And how do I use the file Maskannotation.cs,MaskAnnotationController.cs,MaskShader.shader in mediapipe correctly?Thank you very much

**Comment by homuler** [comment]
Please read [the Getting Started page](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started) first.
And if there's something unclear to you after reading it, ask a question.

**Comment by ma6667** [comment]
I read the Getting Started article carefully, but like MultiFaceLandmarkListAnnotationController.cs it has its own stream. If I want to create a mask based on MaskAnnotationController.cs should I use the same method or do I need to create a new stream?
Or is there another way to build a facemask?and how to use MaskShader.shader?
I'm really sorry to bother you, I'm a rookie in this area.
 @homuler

**Comment by homuler** [comment]
`MaskAnnotationController` is used to annotate the segmentation mask (cf. https://google.github.io/mediapipe/solutions/selfie_segmentation.html) and is not related to Face Mesh / Face Effect, so I'm afraid that it's not what you're looking for.

What do you mean by "build a facemask"?
If it's similar to [the effect renderer](https://google.github.io/mediapipe/solutions/face_mesh.html#effect-renderer), you need to do some more work to run it currently (see #79, #593).

**Comment by ma6667** [comment]
Hello, for the effect renderer, can you describe it in more detail? @homuler

**Comment by homuler** [comment]
Please continue in #79.
There may not be much more I can say, though.
