### ISSUE TITLE
How to import v0.10.1

### ISSUE THREAD

**Issue by tcboy88** [homuler/MediaPipeUnityPlugin#764]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Description

[v0.10.1] In this version, pre-built packages are distributed for the first time.
Does it mean I don't need to built it myself, and I can just import this UnityPackage and run it?
But I couldn't find a way to import the com.github.homuler.mediapipe-0.10.1.tgz file, can you please elaborate? Thank you.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#build-and-install-a-local-tarball-file

**Comment by tcboy88** [comment]
great, thanks!
