### ISSUE TITLE
Windows build error with  --linkopt=-s

### ISSUE THREAD

**Issue by CookieHCl** [homuler/MediaPipeUnityPlugin#765]
### Plugin Version or Commit ID

e0a68a8c169f8d0bf09df824171b050fe39a5551 (master)

### Unity Version

used github action

### Your Host OS

Windows

### Target Platform

Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

used github action

### Command Sequences

A build error `Compiler doesn't support baseline optimization flags` occured when I built MediaPipeUnityPlugin on windows machine with docker, so I tried building with github action.

However building with github action also failed with same error.

I've used ` --desktop cpu --opencv cmake --linkopt=-s` to use github action. This is the `print-inputs` job's output.

```
 inputs.ref=refs/heads/master
inputs.bazelBuildArgs=--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0
inputs.linuxBuildArgs=--desktop gpu --opencv cmake --linkopt=-s --solutions pose
inputs.androidBuildArgs=--android fat --linkopt=-s --solutions pose
inputs.macosBuildArgs=--desktop cpu --opencv cmake --macos_universal --linkopt=-s --solutions pose
inputs.iosBuildArgs=--ios arm64 --linkopt=-s --solutions pose
inputs.windowsBuildArgs=--desktop cpu --opencv cmake --linkopt=-s
```

### Log

See full log here: [https://github.com/CookieHCl/MediaPipeUnityPlugin/actions/runs/3243974165/jobs/5319477398](https://github.com/CookieHCl/MediaPipeUnityPlugin/actions/runs/3243974165/jobs/5319477398)

ERROR: C:/_bzl/3vmcl3ou/external/opencv/BUILD.bazel:243:6: Foreign Cc - CMake: Building opencv_cmake failed: (Exit 1): bash.exe failed: error executing command 
rules_foreign_cc: Build failed!
  cd /d C:/_bzl/3vmcl3ou/execroot/mediapipe_api
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Users\ContainerAdministrator\AppData\Local\bazelisk\downloads\bazelbuild\bazel-5.2.0-windows-x86_64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\bin;C:\Python;C:\Python\Scripts;C:\msys64\usr\bin;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\Users\ContainerAdministrator\AppData\Roaming\npm
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 106 Stepping 6, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=6a06
    SET PYTHON_BIN_PATH=C://Python//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
  C:\msys64\usr\bin\bash.exe -c bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
# Configuration: 36b8e6aaa736723a342714bfcc88fcdd55beb1bc42235614db2226f0904a28fd
# Execution platform: @local_execution_config_platform//:platform
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library opencv_cmake

Environment:______________
PROCESSOR_LEVEL=6
BUILD_SCRIPT=bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/build_script.sh
EXT_BUILD_ROOT=C:\_bzl\3vmcl3ou\execroot\mediapipe_api
BUILD_LOG=bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/CMake.log
***
MSYS_NO_PATHCONV=1
HOME=/
BUILD_WRAPPER_SCRIPT=bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
PYTHON_BIN_PATH=C://Python//python.exe
EXT_BUILD_DEPS=C:\_bzl\3vmcl3ou\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.ext_build_deps
SYSTEMROOT=C:\Windows
TERM=xterm-256color
TEMP=C:\Users\CONTAI~1\AppData\Local\Temp
BUILD_TMPDIR=C:\_bzl\3vmcl3ou\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
SHLVL=2
PROCESSOR_REVISION=6a06
RUNFILES_MANIFEST_ONLY=1
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 106 Stepping 6, GenuineIntel
MSYS2_ARG_CONV_EXCL=*
INSTALLDIR=C:\_bzl\3vmcl3ou\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake
TMP=C:\Users\CONTAI~1\AppData\Local\Temp
PATH=C:\_bzl\3vmcl3ou\execroot\mediapipe_api:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64:/usr/bin:/bin:/c/Windows:/c/Windows/System32:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Users/ContainerAdministrator/AppData/Local/bazelisk/downloads/bazelbuild/bazel-5.2.0-windows-x86_64/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/nodejs:/c/bin:/c/Python:/c/Python/Scripts:/usr/bin:/c/Users/ContainerAdministrator/AppData/Local/Microsoft/WindowsApps:/c/Users/ContainerAdministrator/AppData/Roaming/npm:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/VC/VCPackages:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/bin/Roslyn:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools/devinit:/c/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools//MSBuild/Current/Bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools/::/c/Windows/system32:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja
WINDIR=C:\Windows
PROCESSOR_ARCHITECTURE=AMD64
LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
SYSTEMDRIVE=C:
ProgramData=C:\ProgramData
_=/usr/bin/env
__________________________
+ 'C:\_bzl\3vmcl3ou\execroot\mediapipe_api/external/cmake-3.22.2-windows-x86_64/bin/cmake.exe' -DBUILD_LIST=calib3d,core,features2d,highgui,imgcodecs,imgproc,video,videoio -DBUILD_opencv_apps=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_world=ON -DBUILD_EXAMPLES=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_JPEG=ON -DBUILD_OPENEXR=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON -DBUILD_ZLIB=ON -DWITH_1394=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_GTK=OFF -DWITH_IPP=OFF -DWITH_ITT=OFF -DWITH_JASPER=OFF -DWITH_V4L=OFF -DWITH_WEBP=OFF -DCV_ENABLE_INTRINSICS=ON -DWITH_EIGEN=ON -DENABLE_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DOPENCV_SKIP_PYTHON_LOADER=ON -DOPENCV_SKIP_VISIBILITY_HIDDEN=ON -DBUILD_WITH_STATIC_CRT=OFF -DWITH_LAPACK=ON '-DCMAKE_TOOLCHAIN_FILE=C:\_bzl\3vmcl3ou\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir/crosstool_bazel.cmake' -DCMAKE_BUILD_TYPE=Release '-DCMAKE_INSTALL_PREFIX=C:\_bzl\3vmcl3ou\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake' '-DCMAKE_PREFIX_PATH=C:\_bzl\3vmcl3ou\execroot\mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.ext_build_deps' -DCMAKE_RANLIB= -A x64 -G 'Visual Studio 16 2019' 'C:\_bzl\3vmcl3ou\execroot\mediapipe_api/external/opencv'
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- The CXX compiler identification is MSVC 19.29.30146.0
-- The C compiler identification is MSVC 19.29.30146.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detected processor: AMD64
-- Performing Test HAVE_CXX11 (check file: cmake/checks/cxx11.cpp)
-- Performing Test HAVE_CXX11 - Failed
-- Found PythonInterp: C:/Python/python.exe (found suitable version "3.9.9", minimum required is "2.7") 
CMake Warning at cmake/OpenCVDetectPython.cmake:81 (message):
  CMake's 'find_host_package(PythonInterp 2.7)' found wrong Python version:

  PYTHON_EXECUTABLE=C:/Python/python.exe

  PYTHON_VERSION_STRING=3.9.9

  Consider providing the 'PYTHON2_EXECUTABLE' variable via CMake command line
  or environment variables

Call Stack (most recent call first):
  cmake/OpenCVDetectPython.cmake:271 (find_python)
  CMakeLists.txt:611 (include)

-- Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter) 
    Reason given by package: 
        Interpreter: Wrong major version for the interpreter "C:/Python/python.exe"

-- Found PythonInterp: C:/Python/python.exe (found suitable version "3.9.9", minimum required is "3.2") 
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "3.9.9")
<string>:1: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 

-- Performing Test HAVE_CXX_FP:PRECISE
-- Performing Test HAVE_CXX_FP:PRECISE - Failed
-- Performing Test HAVE_C_FP:PRECISE
-- Performing Test HAVE_C_FP:PRECISE - Failed
-- Performing Test HAVE_CPU_SSE3_SUPPORT (check file: cmake/checks/cpu_sse3.cpp)
-- Performing Test HAVE_CPU_SSE3_SUPPORT - Failed
-- SSE3 is not supported by C++ compiler
-- Performing Test HAVE_CPU_SSSE3_SUPPORT (check file: cmake/checks/cpu_ssse3.cpp)
-- Performing Test HAVE_CPU_SSSE3_SUPPORT - Failed
-- SSSE3 is not supported by C++ compiler
-- Performing Test HAVE_CPU_SSE4_1_SUPPORT (check file: cmake/checks/cpu_sse41.cpp)
-- Performing Test HAVE_CPU_SSE4_1_SUPPORT - Failed
-- SSE4_1 is not supported by C++ compiler
-- Performing Test HAVE_CPU_POPCNT_SUPPORT (check file: cmake/checks/cpu_popcnt.cpp)
-- Performing Test HAVE_CPU_POPCNT_SUPPORT - Failed
-- POPCNT is not supported by C++ compiler
-- Performing Test HAVE_CPU_SSE4_2_SUPPORT (check file: cmake/checks/cpu_sse42.cpp)
-- Performing Test HAVE_CPU_SSE4_2_SUPPORT - Failed
-- SSE4_2 is not supported by C++ compiler
-- Performing Test HAVE_CXX_ARCH:AVX (check file: cmake/checks/cpu_fp16.cpp)
-- Performing Test HAVE_CXX_ARCH:AVX - Failed
-- FP16 is not supported by C++ compiler
-- AVX is not supported by C++ compiler
-- Performing Test HAVE_CXX_ARCH:AVX2 (check file: cmake/checks/cpu_avx2.cpp)
-- Performing Test HAVE_CXX_ARCH:AVX2 - Failed
-- AVX2 is not supported by C++ compiler
-- Performing Test HAVE_CXX_ARCH:AVX512 (check file: cmake/checks/cpu_avx512.cpp)
-- Performing Test HAVE_CXX_ARCH:AVX512 - Failed
-- AVX_512F is not supported by C++ compiler
-- AVX512_COMMON is not supported by C++ compiler
-- AVX512_SKX is not supported by C++ compiler
-- Optimization SSE3 is not available, skipped
-- Dispatch optimization SSE4_1 is not available, skipped
-- Dispatch optimization SSE4_2 is not available, skipped
-- Dispatch optimization AVX is not available, skipped
-- Dispatch optimization FP16 is not available, skipped
-- Dispatch optimization AVX2 is not available, skipped
-- Dispatch optimization AVX512_SKX is not available, skipped
-- Performing Test HAVE_CPU_BASELINE_FLAGS
-- Performing Test HAVE_CPU_BASELINE_FLAGS - Failed
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:582 (message):
  Compiler doesn't support baseline optimization flags:
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:316 (ocv_compiler_optimization_options)
  CMakeLists.txt:614 (include)

-- Configuring incomplete, errors occurred!
See also "C:/_bzl/3vmcl3ou/execroot/mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir/CMakeFiles/CMakeOutput.log".
See also "C:/_bzl/3vmcl3ou/execroot/mediapipe_api/bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake.build_tmpdir/CMakeFiles/CMakeError.log".
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/CMake.log

Target //mediapipe_api:mediapipe_desktop failed to build
INFO (build.py): Building protobuf sources...
ERROR: C:/mediapipe/mediapipe_api/BUILD:254:10 Linking mediapipe_api/mediapipe_c.dll failed: (Exit 1): bash.exe failed: error executing command 
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0 //mediapipe_api:mediapipe_proto_srcs`
  cd /d C:/_bzl/3vmcl3ou/execroot/mediapipe_api
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Users\ContainerAdministrator\AppData\Local\bazelisk\downloads\bazelbuild\bazel-5.2.0-windows-x86_64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\bin;C:\Python;C:\Python\Scripts;C:\msys64\usr\bin;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\Users\ContainerAdministrator\AppData\Roaming\npm
    SET PROCESSOR_ARCHITECTURE=AMD64
    SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 106 Stepping 6, GenuineIntel
    SET PROCESSOR_LEVEL=6
    SET PROCESSOR_REVISION=6a06
    SET PYTHON_BIN_PATH=C://Python//python.exe
    SET ProgramData=C:\ProgramData
    SET RUNFILES_MANIFEST_ONLY=1
  C:\msys64\usr\bin\bash.exe -c bazel-out/x64_windows-opt/bin/external/opencv/opencv_cmake_foreign_cc/wrapper_build_script.sh
# Configuration: 36b8e6aaa736723a342714bfcc88fcdd55beb1bc42235614db2226f0904a28fd
# Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 1460.215s, Critical Path: 832.04s
INFO: 3285 processes: 1197 internal, 2088 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "C:\mediapipe\build.py", line 469, in <module>
    Argument().command().run()
  File "C:\mediapipe\build.py", line 141, in run
    self._run_command(self._build_desktop_commands())
  File "C:\mediapipe\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0 --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake_static //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_proto_srcs.zip' to 'build\Scripts\Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source [https://api.nuget.org/v3/index.json`](https://api.nuget.org/v3/index.json%60)
DEBUG (build.py): Copying '.nuget\Google.Protobuf.3.20.0\lib\netstandard2.0\Google.Protobuf.dll' to 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Creating 'build\Plugins\Protobuf'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\Google.Protobuf.dll'...
DEBUG (build.py): Copying '.nuget\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll' to 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Buffers.dll'...
DEBUG (build.py): Copying '.nuget\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll' to 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Memory.dll'...
DEBUG (build.py): Copying '.nuget\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll' to 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
DEBUG (build.py): Changing the mode of 'build\Plugins\Protobuf\System.Runtime.CompilerServices.Unsafe.dll'...
INFO (build.py): Downloaded protobuf dlls
INFO (build.py): Building resource files
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0 //mediapipe_api:mediapipe_assets`
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'build\Resources'...
DEBUG (build.py): Unarchiving 'bazel-bin\mediapipe_api\mediapipe_assets.zip' to 'Assets\StreamingAssets'...
INFO (build.py): Built resource files
INFO (build.py): Building native libraries for Desktop...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --linkopt=-s --action_env PYTHON_BIN_PATH="C://Python//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures --experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0 --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=cmake_static //mediapipe_api:mediapipe_desktop`
Error: Process completed with exit code 1.

**Comment by homuler** [comment]
Windows linker is completely different from the Linux one.
See https://learn.microsoft.com/en-us/cpp/build/reference/linker-options?view=msvc-170 for more details.

**Comment by CookieHCl** [comment]
Then how do I build windows version and android version with link option enabled? Just run python build.py twice?

**Comment by homuler** [comment]
On Windows, yes (but note that building for android on Windows is not recommended in the first place).
On GitHub Actions, we can build them in parallel, so this is not relevant.
