### ISSUE TITLE
in use FaceMesh, I found it to be a not good predictor Z frame of reference compared with Mediapipe 

### ISSUE THREAD

**Issue by Tongbook** [homuler/MediaPipeUnityPlugin#766]
### Description

in use FaceMesh, I found it to be a good predictor Z frame of reference compared with Mediapipe

**Comment by Tongbook** [comment]
Constant Z coordinate

**Comment by homuler** [comment]
Sorry, I'm not quite sure what you mean.
Can you share a translated text using DeepL or similar?

**Comment by Tongbook** [comment]
I see that FaceMesh's coordinate Z has not changed. I found the same problem with Holistic FaceMesh



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Junrou ***@***.***> |
| Date | 10/14/2022 20:14 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [homuler/MediaPipeUnityPlugin] in use FaceMesh, I found it to be a not good predictor Z frame of reference compared with Mediapipe (Issue #766) |

Sorry, I'm not quite sure what you mean.
Can you share a translated text using DeepL or similar?

**Comment by homuler** [comment]
> I see that FaceMesh's coordinate Z has not changed.

Are you talking about the Z coordinates of the spheres used for the annotation?
If so, set `visualizeZ` to `true` (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/599#issuecomment-1145534773).
