### ISSUE TITLE
only crash in android HUAWEI (xiaomi mix4 not crash)

### ISSUE THREAD

**Issue by jsaon-L** [homuler/MediaPipeUnityPlugin#769]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2020.3.29f1

### Your Host OS

win11 22H2

### Target Platform

Android

### Target Device

HUAWEI P30,HUAWEI Mate30 Pro

### Build Command

python build.py build  --android arm64 --android_ndk_api_level 21 --linkopt=-s --solutions hands pose -vv

### Bug Description

switch unity scene crash
but other android phone not crash
crash only in HUAWEI

### Steps to Reproduce the Bug

Multiple switching scene

### Log

[smartfixtx.log](https://github.com/homuler/MediaPipeUnityPlugin/files/9818862/smartfixtx.log)

**Comment by homuler** [comment]
duplicates #730
