### ISSUE TITLE
Hand Tracking issue on Samsung devices

### ISSUE THREAD

**Issue by spaskhalov** [homuler/MediaPipeUnityPlugin#771]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

macOS Monterey 12.6 & Ubuntu 20.04

### Target Platform

Android

### Target Device

Samsung Galaxy A32 android 12, Samsung Galaxy A33 Android 12

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.2
NDK: 21.4.7075529

### Build Command

Use prebuild libraries from release

### Bug Description

Hand Tracking works very unstable (actually does not work). The hand is either not recognized at all, or it is recognized for several frames and disappears again. The tracking hand is "blinking" on the screen all the time. At the same time, Hand Tracking work correctly on some others Android devices (Poco F3, One Plus 9)

### Steps to Reproduce the Bug

1) Clone MediaPipeUnityPlugin repository from tag v0.10.1
2) Download zip archive with release v0.10.1 and copy files to Packages. I wanna mention, that If i build library with build.py i have the same result (same bug).
3) Build Project for Android platform and run Hand Tracking sample.

### Log

[logs02.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/9850027/logs02.txt)

### Screenshot/Video

https://user-images.githubusercontent.com/13979910/197467417-a05b380f-02c1-45f6-83a6-837215f221d2.mp4

**Comment by homuler** [comment]
> The tracking hand is "blinking" on the screen all the time.

When the inference takes a long time, an empty packet is emitted and the annotation flickers.
Try setting a larger value to `Timeout Millisec` or running the graph in Sync mode (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/661#issuecomment-1189705966).

P.S.
When sharing the log, please build the app with `Development Build` enabled. Otherwise, the logger won't output.

**Comment by spaskhalov** [comment]
Increasing `Timeout Microsec` in ten times, fixed issue for us on our Samsung devices. Thx, @homuler!
