### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':

### ISSUE THREAD

**Issue by kikikiec** [homuler/MediaPipeUnityPlugin#772]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021

### Your Host OS

WINDOWS11

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio Community : 17.3.6
winSdk version : 10.0.19041.0

### Command Sequences

C:\MediaPipeUnityPlugin>set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

C:\MediaPipeUnityPlugin>set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC

C:\MediaPipeUnityPlugin>set BEZEL_VC_FULL_VERSION=17.3.6

C:\MediaPipeUnityPlugin>set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

C:\MediaPipeUnityPlugin>python3 -m venv env

C:\MediaPipeUnityPlugin>env\Scripts\activate

(env) C:\MediaPipeUnityPlugin>python -m pip install numpy

(env) C:\MediaPipeUnityPlugin>set PYTHON_BIN_PATH=C:\MediaPipeUnityPlugin\env\Scripts\python.exe

(env) C:\MediaPipeUnityPlugin>python build.py build --desktop cpu --opencv=cmake -v

### Log

(env) C:\MediaPipeUnityPlugin>python build.py build --desktop cpu --opencv=cmake -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs`
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:433:14: in <toplevel>
  C:/_bzl/kwr2wusf/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/_bzl/kwr2wusf/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/_bzl/kwr2wusf/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/_bzl/kwr2wusf/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: C:/mediapipeunityplugin/WORKSPACE:433:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/_bzl/kwr2wusf/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Repository rules_proto instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:380:25: in <toplevel>
  C:/_bzl/kwr2wusf/external/build_bazel_rules_swift/swift/repositories.bzl:134:11: in swift_rules_dependencies
  C:/_bzl/kwr2wusf/external/build_bazel_rules_swift/swift/repositories.bzl:32:18: in _maybe
Repository rule http_archive defined at:
  C:/_bzl/kwr2wusf/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository rules_cc instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:90:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/kwr2wusf/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository com_google_protobuf instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:193:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/kwr2wusf/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository bazel_rules_dict instantiated at:
  C:/mediapipeunityplugin/WORKSPACE:96:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/kwr2wusf/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Elapsed time: 1.075s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/framework ... (21 packages)
    Fetching https://github.com/bazelbuild/rules_proto/archive/11bf7c25e666dd7ddacbcd4d4c4a9de7a25175f8.tar.gz
    Fetching https://github.com/protocolbuffers/protobuf/archive/v3.19.1.tar.gz
Traceback (most recent call last):
  File "C:\MediaPipeUnityPlugin\build.py", line 469, in <module>
    Argument().command().run()
  File "C:\MediaPipeUnityPlugin\build.py", line 112, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\MediaPipeUnityPlugin\build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\path\to\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="C://MediaPipeUnityPlugin//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

Hello Homuler . Thanks for the tutorial and plugin. 

I've been trying to install your plugin. i got an error. i've try to solve this issue . but my knowledge wasnt' enough. 

can you help me this? 

i've installed OpenCV 4.6.0

**Comment by woookaka** [comment]
same error :(
