### ISSUE TITLE
Can't save an immutable Prefab errors on Objects prefabs

### ISSUE THREAD

**Issue by amokto** [homuler/MediaPipeUnityPlugin#774]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.11f1

### Your Host OS

Windows 10 Pro

### Target Platform

UnityEditor

### Build Command

native libraries from prebuilt package release.

### Bug Description

Thanks for providing a prebuilt package, I have added the latest release as a package and everything works fine.
However the prefabs in the Objects folder that has Arrow and any Annotations scripts throws `ArgumentException: Can't save an immutable Prefab` errors. 

### Steps to Reproduce the Bug

1. Add latest package to a new Unity project
2. Select Arrow or any Annotation prefab in the Runtime/Objects folder.

### Log

ArgumentException: Can't save an immutable Prefab
UnityEditor.PrefabUtility.SavePrefabAsset (UnityEngine.GameObject asset, System.Boolean& savedSuccessfully) (at <4e64905d831f4883a53259ef37fb023b>:0)
UnityEditor.PrefabImporterEditor.SaveDirtyPrefabAssets (System.Boolean reloadInspectors) (at <4e64905d831f4883a53259ef37fb023b>:0)
UnityEditor.PrefabImporterEditor.OnDestroy () (at <4e64905d831f4883a53259ef37fb023b>:0)

### Screenshot/Video

![image](https://user-images.githubusercontent.com/103036086/197980557-04234d56-3e66-490b-a3cc-668488ddabc0.png)

### Additional Context

I assume this is caused by the OnValidate() functions on the scripts, which triggers an asset update. Consider removing this to avoid the immutable prefab errors. 

I would also suggest to move everything except Scripts out of the Runtime folder. The shaders, materials, objects prefabs etc. could be added to a root folder outside Runtime. For example TMPro uses a "Package resources" folder.

**Comment by monsteradurm** [comment]
Also having this exact issue as described. Is there any fix that can be applied in the interim so I can build.
