### ISSUE TITLE
Hand Tracking Tutorial

### ISSUE THREAD

**Issue by karahanoguzhan** [homuler/MediapipeUnityPlugin#775]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

macOS Monterey 12.2

### Target Platform

UnityEditor

### Description

Hello, I am new to mediapipeunity plugin, I am having issues about understanding the hand tracking scene under samples/scenes. In the getting started page, there is an implemented official face mesh solution. I am trying to implement hand tracking solution like that. Here, I am trying to understand the hand tracking scene, the inputs, outputs of the hand tracking graph but I can't get anywhere. Could you help me implement the hand tracking solution like the one in official face mesh solution in getting started page please?

**Comment by homuler** [comment]
> Here, I am trying to understand the hand tracking scene, the inputs, outputs of the hand tracking graph but I can't get anywhere.

Please be more specific about what you don't understand.

**Comment by karahanoguzhan** [comment]
Thanks. I solved the issue
