### ISSUE TITLE
Avoid the prediction of pose when person not in frame. 

### ISSUE THREAD

**Issue by omdivyatej** [homuler/MediaPipeUnityPlugin#777]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2020.3.29f

### Your Host OS

Windows 10

### Target Platform

Windows Standalone

### Description

The holistic part on Mediapipe works well. But, when I am sitting on a chair, it predicts the rest of my pose even if my legs are not in frame. Is there any any way to avoid it? Is there a confidence score parameter I can manipulate? If yes, where can I find the confidence score?

**Comment by homuler** [comment]
Please ask this kind of question to the MediaPipe official team.

> Is there any any way to avoid it?

It depends on what you want to avoid.
- If you want MediaPipe to stop calculating whole landmarks, you may want to change confidence parameters (cf. https://google.github.io/mediapipe/solutions/pose.html#min_tracking_confidence).
- If you want MediaPipe to calculate just only upper pose landmarks, it may be impossible (I don't know).
- If you want to filter non-visible landmarks, see the `presence` or `visibility`(cf. https://github.com/google/mediapipe/blob/1b5da09a9243b603023ce298c441e12b565211f3/mediapipe/framework/formats/landmark.proto#L61-L62)
