### ISSUE TITLE
Google.Protobuf.dll Multiple precompiled assemblies with the same name

### ISSUE THREAD

**Issue by j4nberner** [homuler/MediaPipeUnityPlugin#778]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.9f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor

### Description

I would like to combine the MediaPipe plugin for landmark-extraction with a custom deep-learning model which is able to predict things like lean-angle and and body position. For this I need Barracuda which also uses Google.Protobuf.dll. As soon as I import Barracuda to the Unity project, I get the error "Multiple precompiled assemblies with the same name Google.Protobuf.dll included on the current platform. Only one assembly with the same name is allowed per platform."

I already tried renaming the file oder deleting it and linking mediapipe to the Google.Protobuf.dll from Barracuda. But nothing seems to work.

Does anybody have any idea how to resolve this issue?

Thank you!
Jan

**Comment by j4nberner** [comment]
used different mediapipe implementation from https://github.com/creativeIKEP/BlazePoseBarracuda

**Comment by fengkan** [comment]
moving the barracuda library from \Library\PackageCache to \Packages, and deleting the Google.Protobuf.dll in it fixes this problem for me.
