### ISSUE TITLE
How to create a Github Action and download large binaries

### ISSUE THREAD

**Issue by Kariaro** [homuler/MediaPipeUnityPlugin#779]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.0f1

### Your Host OS

All

### Target Platform

iOS

### Description

The iOS binary for MediaPipe is over 100 MB and can thus not be uploaded to GitHub.

I'm trying to create a GitHub action that will either **Generate the binaries with the release** or **Download the binaries from another location**

Without access to the whole repo (Build scripts and source files) when using only the `.unitypackage` and `.gitignore`'s to prevent the large binary files from being submitted to GitHub, How could I configure my project to generate these binary files?

Is there a guide for how to accomplish this or is it currently not possible yet?

**Comment by homuler** [comment]
Sorry, I'm afraid I don't get what you mean precisely.
Can you describe your issue, distinguishing between what it is and what you would like it to be?

At least, once you fork the repository, I think you can run workflows and build a package with your favorite options.
![Screenshot 2022-11-03 at 10-13-19 Actions · homuler_MediaPipeUnityPlugin](https://user-images.githubusercontent.com/4690128/199630547-acaa8aee-93d1-4bc0-ae32-409cf34bd55d.png)

**Comment by Kariaro** [comment]
If I want to use this plugin in a unity project. How do I create a GitHub action that contains the mediapipe libraries.

The iOS library is over 100 mb so it can’t be uploaded to GitHub.

One solution I’ve thought about is downloading your release and unpacking it in the `Packages` during a git action.

My question is. Do you have any official solution to this?

**Comment by homuler** [comment]
At least, I think you can build libraries by copying published GitHub workflows.

> The iOS library is over 100 mb so it can’t be uploaded to GitHub.

You can reduce the size by specifying `--no-apple_bitcode` and `--linkopt="-s"` (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/724#issuecomment-1228353665).
If you want to keep the embedded bitcode, you may also want to look into Git LFS (cf. https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits).

> One solution I’ve thought about is downloading your release and unpacking it in the Packages during a git action.

Sorry, I don't know what is the problem. Why don't you do so?

**Comment by Kariaro** [comment]
I solved it! Thank you.

The commands to make it smaller also helped!

By creating a fork of the project and then making a custom release I'm now downloading that release in my github actions :+1:

:D
