### ISSUE TITLE
MediaPipe updates

### ISSUE THREAD

**Issue by philiprkk** [homuler/MediaPipeUnityPlugin#78]
Hi, quick question.

Does installing this plugin automatically use the latest updates from MediaPipe? More specifically, is this update included:
https://github.com/google/mediapipe/releases/tag/0.8.3.1

I'd like to be able to use the z-coordinate for body tracking in Unity and would just like to know if it can be done through this plugin now or at a later time.

Thanks

**Comment by homuler** [comment]
Currently this plugin depends on version `0.8.2`.
I plan to upgrade the dependencies this weekend.

**Comment by philiprkk** [comment]
Good to know, thanks!
