### ISSUE TITLE
face mesh & landmark detection: lips pressed together

### ISSUE THREAD

**Issue by monsteradurm** [homuler/MediaPipeUnityPlugin#781]
### Description

Hi, I am wondering if anyone else has tried or come up with a solution for the following problem.
The generally wonderful landmark detection, is estimating the lip position incorrectly when lips are "pursed together" see example below with my ugly mug:

![image](https://user-images.githubusercontent.com/7044684/200451871-d6f22c58-6b3b-4a1b-8776-e37fa992e681.png)

In this picture the lips are held together tightly so they are not so visible but is estimated as though they are, therefore when i try to measure the distance between top of lip(pt 0) and bottom of lip(pt 17), the difference is largely the same as if they were not pursed together at all.

Does anyone have a workaround for doing this sort of thing or a recommendation?

**Comment by homuler** [comment]
Please ask it in the official community (it seems that you've already done so).
Duplicates https://github.com/google/mediapipe/issues/3824
