### ISSUE TITLE
Github actions: How to customize "windows-test.yml"

### ISSUE THREAD

**Issue by mgarbade** [homuler/MediaPipeUnityPlugin#784]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2020.3.26f1

### Your Host OS

Windows 10 Pro

### Target Platform

UnityEditor

### Description

I'm trying understand and adapt the `[windows-test.yml](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/workflows/windows-test.yml)` file. However, I don't understand 

 - where to get the `secret.UNITY_TOTP_KEY`
 - how to avoid generating a Unity license and instead use a secret.UNITY_LICENSE which I already generated beforehand

Any hints are welcome

**Comment by mgarbade** [comment]
ok, I meanwhile found out that TOTP is "two factor authentication one time password". 

Apparantly the Unity license server sees a login from a foreign IP and requires some extra security measure.

Unclear to me:
- is there one TOTP that I can enter into github actions and use it for multiple github actions runs or do I need to generate a new TOTP before every run?

**Comment by mgarbade** [comment]
hmm, yeah licensing seems to be an issue on Windows VMs, I just got 
```
LICENSE SYSTEM [20221116 16:41:2] Machine binding 2 mismatch: (value of current machine)  != 576562626572264761624c65526f7578 (value in license file). Reason might be there is a hardware change on this machine after the license was activated.
```
trying to run a "clean" game-ci unity-test-runner:

```
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2.0.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

I also tried rerunning "windows-test.yml" yesterday, but so far no success. Also I'm a little bit scared of what I saw after digging into
```
      - name: Request a Unity license file
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_TOTP_KEY: ${{ secrets.UNITY_TOTP_KEY }}
        run: |
          npm install -g unity-verify-code
          git clone -b ci https://github.com/homuler/unity-license-activate.git
          cd unity-license-activate
          npm install
          cd ..
          npm install -g ./unity-license-activate
          unity-license-activate "$env:UNITY_EMAIL" "$env:UNITY_PASSWORD" Unity_v${{ matrix.unity.version }}.alf --authenticator-key "$env:UNITY_TOTP_KEY"
```


The [unit-license-activate](https://github.com/homuler/unity-license-activate.git) repository asks for 3~4 secrets among which should be an `ACCESS_TOKEN` and / or my email login credentials.
Sounds to me like I have to trust the author not to breach my email account and download / modify any of my private github repositories 🤔

**Comment by mgarbade** [comment]
> If you've not enabled 2FA, you can ignore it

As I said: 
> Apparently the Unity license server sees a login from a foreign IP (the github Actions Windows VM) and requires some extra security measure.

So even though I never enabled two factor authentication, Unity sends a verification code to my email, as can be seen from the error.png screenshot below
![error](https://user-images.githubusercontent.com/3956593/202432052-b9997e54-6d6c-43ca-b0ef-1f4f6f40933a.png)

**Comment by homuler** [comment]
Then you might rather look into [the original repository](https://github.com/game-ci/unity-license-activate#%EF%B8%8F-secrets).

> Sounds to me like I have to trust the author not to breach my email account and download / modify any of my private github repositories thinking

I think your reaction is plausible and actually, I forked the repository and removed some log output (but I just found there still seemed to be [some problematic log output](https://github.com/homuler/unity-license-activate/blob/052f4e04d86d5d86a064cda877649b9b0409c6c9/lib/cli.js#L40)).
But after all, if you don't trust the author, you don't need to use the OSS.
You can just solve the problem on your own.

**Comment by aisportscoach** [comment]
hmm I couldn't solve the "verification problem", so in the meantime I created 
- dummy Unity account 
- dummy Github account

I activated 2 factor authentication for that account
- I copied the initial secret
- and added it as UNITY_TOTP_KEY secret in the respective github repository
- then re-ran your "windows-test.yml"

now the error.png looks like this:
![error](https://user-images.githubusercontent.com/97443240/203133828-bef8eb4b-a6af-4916-a29b-187cdf2974cc.png)


The total secrets I set up for that repository are
- UNITY_EMAIL
- UNITY_PASSWORD
- UNITY_TOTP_KEY

I guess I could add more Github secrets (EMAIL_PASSWORD, ACCESS_TOKEN) but the error doesn't look like that is the problem here...

**Comment by aisportscoach** [comment]
I would also love to debug the code myself, but I'm not sure, how to get started. 
Maybe run the homuler/unity-license-activate locally (without Github actions) and see if I can get it running on a dummy Unity project?  

In that case what do I need? Docker-Desktop  + WSL2 + ???

By the way: I don't understand how "npm" gets installed which is used in 

```
npm install -g unity-verify-code
```

is it part of the `crazy-max/ghaction-chocolatey` image?

**Comment by homuler** [comment]
> now the error.png looks like this:

I think you can skip this page once you log in locally once.

> Maybe run the `homuler/unity-license-activate` locally (without Github actions) and see if I can get it running on a dummy Unity project?

At least, that's how I debugged the program (but you don't need to create a dummy Unity project to activate the license).

> In that case what do I need? Docker-Desktop + WSL2 + ???

As you have probably noticed, it works on Windows, Linux and macOS, so choose your preferred environments.

> is it part of the `crazy-max/ghaction-chocolatey` image?

See https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md

**Comment by homuler** [comment]
By the way, I feel like we're getting off the topic.
I'd like you to think a little bit about whether it is really related to this project before asking.

**Comment by mgarbade** [comment]
Just for completeness: I got some intermediary progress! Yes the "Unity has made update" message shown in the screenshot only happens when using Github Actions and must be "clicked away" manually.
I therefore 
- launched a workflow .yml file checking the external ip of the VM 
```
      - name: Display ip address
        run: |
          echo "check external ip - start"
          curl https://ipinfo.io/ip
          echo "check external ip - done"`
```
- checked the external ip -> came from USA / Virginia
- [setup a VPN](https://www.youtube.com/watch?v=m-i2JBtG4FE&ab_channel=NetworkChuck) on my local PC which uses an EC2 instance in the US as a proxy
- manually login to [unity](https://id.unity.com/)
- click away the warning

-> now the license activation step is working
