### ISSUE TITLE
Multiplayer Support/ Area Recognition / Linux + ARM

### ISSUE THREAD

**Issue by TKTSWalker** [homuler/MediaPipeUnityPlugin#785]
### Feature Description

Hello, I was wondering if anything like the following was in the works for Instant Motion Tracking or if there any ideas on how to implement 

- A robust way to compare a dataset to others on a server and spawn objects there based on how others placed said objects 
- Multiplayer support, meaning to allow everyone to seethe same items through different positions (Different people using a UI can see the UIs of other people)
- The ability to run this on Linux with an ARM CPU

Thank you, if it helps I would be willing to pay in January for help!

**Comment by homuler** [comment]
> A robust way to compare a dataset to others on a server and spawn objects there based on how others placed said objects

Sorry, I'm not sure what you mean by
- compare a dataset to others on a server
- there
- said objects

> Multiplayer support

It seems to me that it is not related to this project at all.
If you think it is, will you elaborate a bit more?

- The ability to run this on Linux with an ARM CPU

Can you report the error you see when you try to build it on your ARM machine?
In fact, I don't know if we can build this project on ARM machines or not.
