### ISSUE TITLE
How to build geometry_pipeline_metadata_landmarks.binarypb

### ISSUE THREAD

**Issue by endink** [homuler/MediaPipeUnityPlugin#787]
### Feature Description

As I know , we can use the following command to build geometry_pipeline_metadata_landmarks.binarypb.

```
bazel build --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH=[pythone path] mediapipe/modules/face_geometry/data:geometry_pipeline_metadata_landmarks
```
Your compilation script is so convenient, especially for somebody like me who are not very familiar with bazel, but to compile "geometry" I can only use mediapipe native build  commands?

**Comment by endink** [comment]
BTW, Whether considering that you let compile the module into a separate project, so that it can be used by non-Unity projects, now I use your compilation module to compile the DLL library that I wrote for UnrealEngine, because you provide good static static support and many useful compilation options, which is not provided by the official compilation script.

**Comment by homuler** [comment]
Maybe related to #79 .

>  but to compile "geometry" I can only use mediapipe native build commands?

For now, yes, because this project doesn't include Face Geometry-related calculators by default.
Can you tell me the use case you want to build the Face Geometry solution?
I have not supported it yet because I think it would be more effective to build the Mesh on Unity (in your case, it may be UE).

**Comment by endink** [comment]
I use it to solve for face blendshape, because face mesh does not better reflect the position of mesh and image due to orthogonal projection. In my process, it is more accurate to use geometric data than face mesh. I use FaceGeometryFromLandmarks to get Face Geometry
