### ISSUE TITLE
Error with older version

### ISSUE THREAD

**Issue by Loe123** [homuler/MediaPipeUnityPlugin#789]
### Plugin Version or Commit ID

v.0.6.0

### Unity Version

2021.3.8f1

### Your Host OS

Windows 10 Home

### Target Platform

Windows Standalone

### Target Device

MSI GL65

### Build Command

copy file:
D:\Downloads\MediaPipeUnityPlugin-0.6.0\Packages\com.github.homuler.mediapipe   ->D:\ My project\Package D:\Downloads\MediaPipeUnityPlugin-0.6.0\Assets\Mediapipe    -> D:\My project/Assets

### Bug Description

error CS0400: The type or namespace name 'XXXXXX' could not be found in the global namespace (are you missing an assembly reference?)

### Steps to Reproduce the Bug

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(3,32): error CS0234: The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\DetectionAnnotationController.cs(5,32): error CS0234: The type or namespace name 'LocationData' does not exist in the namespace 'Mediapipe' (are you missing an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\DetectionAnnotationController.cs(4,21): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\External\Protobuf.cs(6,20): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraph.cs(4,7): error CS0246: The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraphConfig.cs(1,20): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(31,62): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(61,65): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(73,60): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\AnnotationController.cs(73,82): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\NodeAnnotationController.cs(19,49): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\ClassificationAnnotationController.cs(13,49): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\NodeAnnotationController.cs(34,49): error CS0246: The type or namespace name 'LocationData' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\CircleAnnotationController.cs(28,49): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\TimedModelMatrixProtoListPacket.cs(4,57): error CS0246: The type or namespace name 'TimedModelMatrixProtoList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\TimedModelMatrixProtoListPacket.cs(8,21): error CS0246: The type or namespace name 'TimedModelMatrixProtoList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\TimedModelMatrixProtoListPacket.cs(18,30): error CS0246: The type or namespace name 'TimedModelMatrixProtoList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListPacket.cs(4,54): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListPacket.cs(8,21): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListPacket.cs(18,30): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListVectorPacket.cs(5,65): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\RectListAnnotationController.cs(7,54): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\DetectionAnnotationController.cs(44,49): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\DetectionAnnotationController.cs(54,62): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListVectorPacket.cs(9,26): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedLandmarkListVectorPacket.cs(19,35): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\RectAnnotationController.cs(21,49): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedRectPacket.cs(4,46): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedRectPacket.cs(8,21): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedRectPacket.cs(18,30): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedRectVectorPacket.cs(5,57): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedRectVectorPacket.cs(9,26): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\NormalizedRectVectorPacket.cs(19,35): error CS0246: The type or namespace name 'NormalizedRect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectPacket.cs(4,36): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectPacket.cs(8,21): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectPacket.cs(18,30): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectVectorPacket.cs(5,47): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectVectorPacket.cs(9,26): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\RectVectorPacket.cs(19,35): error CS0246: The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\DetectionListAnnotationController.cs(16,54): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\EdgeAnnotationController.cs(21,49): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\EdgeAnnotationController.cs(21,71): error CS0246: The type or namespace name 'NormalizedLandmark' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\LandmarkListAnnotationController.cs(58,49): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListPacket.cs(4,50): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Annotation\LandmarkListAnnotationController.cs(90,26): error CS0246: The type or namespace name 'NormalizedLandmarkList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListPacket.cs(8,21): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListPacket.cs(18,30): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryPacket.cs(4,44): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListVectorPacket.cs(5,61): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryPacket.cs(8,21): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryPacket.cs(18,30): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListVectorPacket.cs(9,26): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryVectorPacket.cs(5,55): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\ClassificationListVectorPacket.cs(19,35): error CS0246: The type or namespace name 'ClassificationList' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionPacket.cs(4,41): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryVectorPacket.cs(9,26): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\FaceGeometryVectorPacket.cs(19,35): error CS0246: The type or namespace name 'FaceGeometry' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionPacket.cs(8,21): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraph.cs(32,30): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionPacket.cs(18,30): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraph.cs(40,30): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraph.cs(49,12): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionVectorPacket.cs(5,52): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionVectorPacket.cs(9,26): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Tool\NameUtil.cs(23,44): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Packet\DetectionVectorPacket.cs(19,35): error CS0246: The type or namespace name 'Detection' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraph.cs(26,28): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Tool\NameUtil.cs(36,50): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\Tool\NameUtil.cs(57,44): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraphConfig.cs(6,84): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.github.homuler.mediapipe\Runtime\Scripts\Framework\CalculatorGraphConfig.cs(6,19): error CS0246: The type or namespace name 'CalculatorGraphConfig' could not be found (are you missing a using directive or an assembly reference?)

![no](https://user-images.githubusercontent.com/72906753/203259513-7c4285a0-e8dc-4dc9-b1d0-08e4daeb5ee3.PNG)

### Log

 I want to use an older version (0.6.0).
So I download the zip archive, build new Unity3d, copy the zip archive to the new project.

MediaPipeUnityPlugin-0.6.0\Packages\com.github.homuler.mediapipe   -> My project\Packages
                                     MediaPipeUnityPlugin-0.6.0\Assets\Mediapipe    -> My project/Assets

When copied it will have error.
error CS0400: The type or namespace name 'XXXXXX' could not be found in the global namespace (are you missing an assembly reference?)
Or is it possible to publish a .tgz file?

### Screenshot/Video

https://youtu.be/aSS6oZ_xS6g

**Comment by Loe123** [comment]
![Uploading no.PNG…]()

**Comment by homuler** [comment]
duplicates #177
