### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by Loe123** [homuler/MediaPipeUnityPlugin#791]
### Plugin Version or Commit ID

v.0.6.2

### Unity Version

2021.3.8f1

### Your Host OS

Windows 10 Home

### Target Platform

Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++:14.29.30133
Windows SDK Version:10.0.19041.0

### Command Sequences

set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

virtualenv env
env\Scripts\activate
set PYTHON_BIN_PATH=C:\test\MediaPipeUnityPlugin-0.6.2\env\Scripts\python.exe
python build.py build --desktop cpu --include_opencv_libs -v

### Log

DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "98525a5a98b72d17ae37c01f6f70b2c5d31a8d6582e65c44410da4c92b17a669"
DEBUG: Repository rules_cc instantiated at:
  C:/test/mediapipeunityplugin-0.6.2/WORKSPACE:78:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/v7eeodun/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
ERROR: Traceback (most recent call last):
        File "C:/_bzl/v7eeodun/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 529, column 58, in <toplevel>
                ios_application = rule_factory.create_apple_bundling_rule(
        File "C:/_bzl/v7eeodun/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "C:/_bzl/v7eeodun/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//mediapipe_api:mediapipe_desktop' failed; build aborted: error loading package '@com_google_mediapipe//mediapipe/gpu': at C:/_bzl/v7eeodun/external/build_bazel_rules_apple/apple/ios.bzl:37:5: initialization of module 'apple/internal/ios_rules.bzl' failed
INFO: Elapsed time: 17.348s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 418 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/gpu
Traceback (most recent call last):
  File "C:\test\MediaPipeUnityPlugin-0.6.2\build.py", line 392, in <module>
    Argument().command().run()
  File "C:\test\MediaPipeUnityPlugin-0.6.2\build.py", line 135, in run
    self._run_command(self._build_desktop_commands())
  File "C:\test\MediaPipeUnityPlugin-0.6.2\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\40943\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://test//MediaPipeUnityPlugin-0.6.2//env//Scripts//python.exe', '--define', 'MEDIAPIPE_DISABLE_GPU=1', '--@opencv//:switch=local', '//mediapipe_api:mediapipe_desktop']' returned non-zero exit status 1.

![image](https://user-images.githubusercontent.com/72906753/203268869-eae48690-3c82-49ad-bb42-7f9c86de5431.png)

**Comment by homuler** [comment]
v.0.6.2 is not supported anymore.
Please download the latest version.

**Comment by homuler** [comment]
> Error: 'apple_common' value has no field or method 'objc_proto_aspect'

FYI: you need to upgrade some libraries (but I'm not sure that's enough).
If you want to keep using an older version, check the commit logs and apply the necessary changes.
