### ISSUE TITLE
How to get face rotation matrix from face landmarks

### ISSUE THREAD

**Issue by Boulaouaney** [homuler/MediaPipeUnityPlugin#795]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

Windows 11 Pro

### Target Platform

UnityEditor

### Description

I was successful in adding an effect on the face using the face landmarks positions.

However, I am struggling to add a 3D object such as a hat on top of the head.

My approach is to have the object follow the position of the face landmark number 10 (top of the head). This hasn't worked properly yet, and one of the main issues is the rotation.

I saw on the official mediapipe repo issues that a solution would be to get the rotation matrix. Can you please guide me on how to do that in this plugin? or if you have a better approach to suggest please do

Thank you!

**Comment by homuler** [comment]
Maybe related to (or the same as) #787, #410 and #79.

**Comment by rish6ix** [comment]
Hi @Boulaouaney  were you able to solve this ?

**Comment by Boulaouaney** [comment]
@rish6ix not yet unfortunately... I put this task aside for a while now to work on other tasks in the project. I will update if I manage to solve it. Please do so as well if you find a solution

**Comment by azmath37** [comment]
Hi @Boulaouaney,
Im also facing the same problem ,
Please update if solution is found 
Thanks.

**Comment by droncaglio** [comment]
Hi, I was able to make a AR app that display glasses on face. You can see it working on the link below. If it is good enough for you I can make a video and share my code. To hard for me to explain here.

https://youtu.be/a0LaPd4fg1I

**Comment by Boulaouaney** [comment]
@azmath37 sorry for the super late update, I've stopped working on this project a while ago. I think we ended up using animation rigging to add the hat, but it wasn't very realistic. I hope you managed to find a better solution.

@droncaglio sharing your code would be very nice. I personally am not working on this anymore, but I am sure many people will find it helpful.
