### ISSUE TITLE
how to get 3D position for unity scene about Face and Hand in holistic

### ISSUE THREAD

**Issue by fishhead012** [homuler/MediaPipeUnityPlugin#797]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.5f1

### Your Host OS

window 10

### Target Platform

UnityEditor

### Description

In the holistic scene sample, only Pose can get 3d position.

how to get 3d position about face and hand
please tell me how to get 3d position

**Comment by homuler** [comment]
Please read [the official document](https://google.github.io/mediapipe/solutions/holistic.html#face_landmarks).

> A list of `468` face landmarks. Each landmark consists of `x`, `y` and `z`. `x` and `y` are normalized to `[0.0, 1.0]` by the image width and height respectively. `z` represents the landmark depth with the depth at center of the head being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of `z` uses roughly the same scale as `x`.

See also https://github.com/homuler/MediaPipeUnityPlugin/issues/599#issuecomment-1145534773.
