### ISSUE TITLE
237 errors when compiled the code. Many namespaces are missing from Runtime/Scripts 

### ISSUE THREAD

**Issue by bhavya0598** [homuler/MediaPipeUnityPlugin#798]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.10f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Lastest

### Command Sequences

None

### Log

None

**Comment by homuler** [comment]
Please read [the README](https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation) first.
