### ISSUE TITLE
How to get the handness of  hand landmarks

### ISSUE THREAD

**Issue by Sassantky** [homuler/MediaPipeUnityPlugin#799]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

MacOS BigSur 11.4

### Target Platform

UnityEditor

### Description

With the help of Wiki, I have successfully used this plugin to get the hand landmarks. Thank you very much for the great plugin.

Now, I would like to know if the acquired landmark is a right or left hand. 

However, I don’t t know how to get the handness information of the acquired landmark from the outputstream. How can I do this?

Config Asset uses the following
mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt

Thank you !!

**Comment by homuler** [comment]
You can get the handedness by reading a value from [the `handedness` stream](https://github.com/google/mediapipe/blob/e457039fc6350fbd2e75aa2d034f9b68af6d3410/mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt#L29) with the same timestamp as the landmark.

I think you're initializing `multiFaceLandmarksStream` like this:
```cs
var multiFaceLandmarksStream = new OutputStream<NormalizedLandmarkListVectorPacket, List<NormalizedLandmarkList>>(_graph, "multi_face_landmarks");
multiFaceLandmarksStream.StartPolling().AssertOk();
```

In addition to that, you need to initialize `handednessStream` like this:
```cs
var handednessStream = new OutputStream<ClassificationListVectorPacket,
List<ClassificationList>>(_graph, "handedness");
handednessStream.StartPolling().AssertOk();
```

Note that the type of the value in the `handedness` stream is `std::vector<ClassificationList>` in C++ and the corresponding class in C# is `List<ClassificationList>`.
See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#initialization-2.
