### ISSUE TITLE
Error during make step

### ISSUE THREAD

**Issue by ashrvstv** [homuler/MediapipeUnityPlugin#8]
getting the  following error 

```
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/Mediapipe/SDK/Plugins/Protobuf
cp: cannot stat '.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/*': No such file or directory
Makefile:55: recipe for target 'install-protobuf' failed
make: *** [install-protobuf] Error 1

```
Steps to reproduce : 
step 1 - git clone https://github.com/homuler/MediapipeUnityPlugin.git
step 2 - cd MediapipeUnityPlugin
step 3 - make install

Prerequisites - already satisfied
1- mediapipe is installed 
2- opencv  version 3.4.10-pre installed
3- protocol compiler version libprotoc 3.0.0 installed

**Comment by homuler** [comment]
Please run `make` before `make install`.

**Comment by ashrvstv** [comment]
@homuler running `make` gives the following error

```
mkdir -p .build
curl -L https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz -o .build/protobuf-3.13.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0    203      0 --:--:-- --:--:-- --:--:--   203
100 5154k    0 5154k    0     0  1333k      0 --:--:--  0:00:03 --:--:-- 1757k
tar xf .build/protobuf-3.13.0.tar.gz -C .build
./.build/protobuf-3.13.0/csharp/buildall.sh
+ echo Building relevant projects.
Building relevant projects.
+ dotnet restore ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
./.build/protobuf-3.13.0/csharp/buildall.sh: line 9: dotnet: command not found
Makefile:43: recipe for target '.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll' failed
make: *** [.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll] Error 127

```

**Comment by homuler** [comment]
To build `Google.Protobuf.dll`, `dotnet` command is required (cf. https://github.com/homuler/MediapipeUnityPlugin#protocol-buffer).
Please install .NET Core SDK(3.x) and .NET Core runtime 2.1.

**Comment by ashishkrshrivastava** [comment]
@homuler I have already installed using 
```
sudo snap install dotnet-sdk --classic
sudo snap install dotnet-runtime-31
```

**Comment by homuler** [comment]
Please make sure that you can run `dotnet --version`.
Below issue may be related.
https://askubuntu.com/questions/1131867/dotnet-command-not-found-after-installing-using-snap

**Comment by ashrvstv** [comment]
Thanks @homuler that worked
but now i am facing this error

```
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/Mediapipe/SDK/Plugins/Protobuf
cp -f C/bazel-bin/mediapipe_api/libmediapipe_c.so Assets/Mediapipe/SDK/Plugins
cp: cannot stat 'C/bazel-bin/mediapipe_api/libmediapipe_c.so': No such file or directory
Makefile:58: recipe for target 'install-mediapipe_c' failed
make: *** [install-mediapipe_c] Error 1

```
Mediapipe examples are already working on my system

**Comment by homuler** [comment]
Please copy and paste the log when you run `make`.

**Comment by ashrvstv** [comment]
Thankyou so much @homuler . it worked 
on `make install`
```
~/MediapipeUnityPlugin$ make install
```
```
cp .build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/* Assets/Mediapipe/SDK/Plugins/Protobuf
cp -f C/bazel-bin/mediapipe_api/libmediapipe_c.so Assets/Mediapipe/SDK/Plugins
unzip C/bazel-bin/mediapipe_api/mediapipe_models.zip -d Assets/Mediapipe/SDK/Models
Archive:  C/bazel-bin/mediapipe_api/mediapipe_models.zip
  inflating: Assets/Mediapipe/SDK/Models/face_detection_front.tflite  
  inflating: Assets/Mediapipe/SDK/Models/face_detection_front_labelmap.txt  
  inflating: Assets/Mediapipe/SDK/Models/face_landmark.tflite  
  inflating: Assets/Mediapipe/SDK/Models/hair_segmentation.tflite  
  inflating: Assets/Mediapipe/SDK/Models/hand_landmark.tflite  
  inflating: Assets/Mediapipe/SDK/Models/handedness.txt  
  inflating: Assets/Mediapipe/SDK/Models/iris_landmark.tflite  
  inflating: Assets/Mediapipe/SDK/Models/palm_detection.tflite  
  inflating: Assets/Mediapipe/SDK/Models/palm_detection_labelmap.txt  
  inflating: Assets/Mediapipe/SDK/Models/ssdlite_object_detection.tflite  
  inflating: Assets/Mediapipe/SDK/Models/ssdlite_object_detection_labelmap.txt  
  inflating: Assets/Mediapipe/SDK/Models/pose_detection.tflite  
  inflating: Assets/Mediapipe/SDK/Models/pose_landmark_upper_body.tflite  
```

**Comment by ashrvstv** [comment]
@homuler Readme doesnot contain instructions to use this plugin inside unity. My objective is to use pose landmarks and render a 3D model over a landmark. Can you please guide me how can i get pose landmarks using this plugin?

**Comment by homuler** [comment]
As to pose tracking, I'm developing now, but the HandTracking example may be used as a reference.

1. Define `output_stream` you use in [the graph config file](https://github.com/homuler/MediapipeUnityPlugin/blob/de4d054f4795ed47997da205b0a152c64d309760/Assets/Mediapipe/Examples/HandTracking/hand_tracking_mobile.txt#L21)
2. [Initialize the graph](https://github.com/homuler/MediapipeUnityPlugin/blob/de4d054f4795ed47997da205b0a152c64d309760/Assets/Mediapipe/Examples/Scripts/DemoGraph.cs#L22)
3. Prepare an [OutputStreamPoller](https://github.com/homuler/MediapipeUnityPlugin/blob/de4d054f4795ed47997da205b0a152c64d309760/Assets/Mediapipe/Examples/HandTracking/Scripts/HandTrackingGraph.cs#L41) and the corresponding `Packet`.
4. [Push the image](https://github.com/homuler/MediapipeUnityPlugin/blob/de4d054f4795ed47997da205b0a152c64d309760/Assets/Mediapipe/Examples/Scripts/DemoGraph.cs#L43) to the graph.
5. [Wait and fetch the result](https://github.com/homuler/MediapipeUnityPlugin/blob/de4d054f4795ed47997da205b0a152c64d309760/Assets/Mediapipe/Examples/HandTracking/Scripts/HandTrackingGraph.cs#L96).

Overall, I think that the sample code is very similar to [the official one](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc).

**Comment by homuler** [comment]
In https://github.com/homuler/MediapipeUnityPlugin/commit/269a081018f179f6ed01469043e2bb2c412fd5d9, I added [sample code](https://github.com/homuler/MediapipeUnityPlugin/blob/269a081018f179f6ed01469043e2bb2c412fd5d9/Assets/Mediapipe/Examples/PoseTracking/Scripts/PoseTrackingGraph.cs) to use pose landmarks.
