### ISSUE TITLE
Build on android is inoperative

### ISSUE THREAD

**Issue by tianqi1994** [homuler/MediaPipeUnityPlugin#800]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.15f1c1

### Your Host OS

WIN11

### Target Platform

Android

### [Android Only] Android Build Tools and NDK Version

Unity auto install

### Command Sequences

Nothing

### Log

I have download the release sourceCode. and use the Unity build android platform immediately,No error is reported,But the recognition failed,Am I missing something?

**Comment by homuler** [comment]
> **Command Sequences**
>
> Nothing

Please describe what you did step by step.

> I have download the release sourceCode

If you downloaded `Source code (zip)` or `Source code (tar.gz)`, they don't contain the required libraries so they won't work (and I think they won't even be compiled).

> But the recognition failed

It is not apparent what you mean, so please share the screenshot.
