### ISSUE TITLE
Media Pipe Unity with AR Foundation Camera 

### ISSUE THREAD

**Issue by AbdullahNarsun** [homuler/MediaPipeUnityPlugin#801]
### Feature Description

We are trying to integrate Media Pipe Unity with AR Foundation, 
We almost got the tracking and AR work done, But the problem is we are unable to make both features functional. Like using object detection with AR camera, because object detection uses Web cam Texture.

How can we convert web cam texture and use as an AR Camera Input ? 
Or
How can we  convert AR Camera out render texture and send it to Media Pipe Unity plugin for detection instead of Web cam texture?

### Current Behaviour/State

If we use both in same scene.
Only one work at a time. When we pause web cam texture.....

### Additional Context

Help Us!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by homuler** [comment]
See #343 and https://github.com/homuler/MediaPipeUnityPlugin/wiki/API-Overview#initialization-4.
