### ISSUE TITLE
trying to use GeometryPipelineCalculator

### ISSUE THREAD

**Issue by cdiddy77** [homuler/MediaPipeUnityPlugin#802]
## Goal

use FaceGeometryPipelineCalculator to get 3D face geometry on desktop

## Where I am

Modified the Face Mesh sample scene to add a node that uses FaceGeometryPipelineCalculator, as so:
```
# Computes face geometry from face landmarks for a single face.
node {
  calculator: "FaceGeometryPipelineCalculator"
  input_side_packet: "ENVIRONMENT:environment"
  input_stream: "IMAGE_SIZE:input_image_size"
  input_stream: "MULTI_FACE_LANDMARKS:multi_face_landmarks"
  output_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
  options: {
    [mediapipe.FaceGeometryPipelineCalculatorOptions.ext] {
      metadata_path: "MYPATHTO/geometry_pipeline_metadata_landmarks.binarypb"
    }
  }
}
```

result, when I load project in Unity and press play:

```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mediapipe.CalculatorGraphConfig: 148:59: Extension "mediapipe.FaceGeometryPipelineCalculatorOptions.ext" is not defined or is not an extension of "mediapipe.CalculatorOptions".
UnityEngine.Debug:LogError (object)
[lots of stack trace]
```

I am led to believe that I would need to generate the CS files for this type from the corresponding .proto file in mediapipe, and so I modify `mediapipe_api/modules/face_geometry/protos/BUILD` adding a target for geometry_pipeline_calculator.proto: 

```
csharp_proto_src(
    name = "geometry_pipeline_calculator_cs",
    proto_src = "mediapipe/modules/face_geometry/geometry_pipeline_calculator.proto",
    deps = [
        "@com_google_mediapipe//mediapipe/modules/face_geometry:protos_src",
    ],
)
```

I am defeated because there is no :protos_src in the `face_geometry` build file. If I dive deeper, I think that the reason that `protos_src` target exists for other @com_google_mediapipe BUILD files, is because of the mysterious and magical `third_party/mediapipe_visibility.diff` file. Am I right? If so, is the solution for me to generate the cryptic diff goo for `mediapipe/modules/face_geometry/BUILD` ? 

or am I completely in the weeds? What is the path to victory here?

**Comment by homuler** [comment]
You need to build native libraries with `FaceGeometryPipelineCalculator`.

e.g.
```diff
diff --git a/mediapipe_api/BUILD b/mediapipe_api/BUILD
index 7f0f674..2b998c3 100644
--- a/mediapipe_api/BUILD
+++ b/mediapipe_api/BUILD
@@ -305,6 +305,7 @@ cc_library(
     ] + select({
         "@com_google_mediapipe//mediapipe/gpu:disable_gpu": [],
         "//conditions:default": [
+            "@com_google_mediapipe//mediapipe/modules/face_geometry:face_geometry_from_landmarks",
             "@com_google_mediapipe//mediapipe/gpu:gl_scaler_calculator",
             "@com_google_mediapipe//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",
             "@com_google_mediapipe//mediapipe/gpu:gpu_buffer_to_image_frame_calculator",
```

**Comment by cdiddy77** [comment]
@homuler Thanks! That seems like a necessary but not sufficient condition, that I had not considered (I guess I would have discovered it at runtime?) but I am still left with the problem that FaceGeometryPipelineCalculatorOptions is not defined. What am I missing?

**Comment by homuler** [comment]
Note that the above patch is for GPU.
To build libraries for CPU, add `face_geometry:face_geometry_from_landmarks` to the `disable_gpu` condition.

**Comment by homuler** [comment]
If you have more questions, please update the description using [the support form format](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/support.yml).

**Comment by cdiddy77** [comment]
For posterity: I was able to move past this by getting the geometry_pipeline_calculator proto to be "visible". There are various changes in `mediapipe_visibility.diff` which apply changes to mediapipe before building, specifically to change the visibility of different proto files. I created, with some difficulty, a further diff to make the various protos in `mediapipe/modules/face_geometry/BUILD` also be visible.

**Comment by azmath37** [comment]
Hi @homuler 
I had followed the tutorials to achieve AR virtual try on experience like sunglasses 
after having basic research on how to achieve it, I got to know that we require face geometry for getting expected results.
but got stuck at same issue mentioned by @cdiddy77 so could you please elaborate how to move Forword.
thanks in advance...!
Hoping for best suggestions  
below is the error faced 
![image](https://user-images.githubusercontent.com/24653085/212271032-5e10443a-f1e0-41aa-9360-f1fdcebfdc01.png)
Calculator what I have used is below.  
[Face_Geometry.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10409506/Face_Geometry.txt)
