### ISSUE TITLE
Basic Objectron Detection With AR Camera

### ISSUE THREAD

**Issue by AbdullahNarsun** [homuler/MediaPipeUnityPlugin#803]
### Feature Description

Thanks for replying my previous request. I am facing difficulty to integrate objectron example with AR camera. Can you please provide very basic format for it like you provided [here](https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1096698719) for face detection. Much much appriciated!

### Current Behaviour/State

This is very good plugin but i can hardly find any documentation regarding AR came

### Additional Context

Please help me!

**Comment by AbdullahNarsun** [comment]
Here is my script if u want to have a look into it.
`using Mediapipe;
using Mediapipe.Unity;
using Mediapipe.Unity.Objectron;

using System;
using System.Collections;
using System.Collections.Generic;

using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using UnityEngine;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;

using Stopwatch = System.Diagnostics.Stopwatch;

public class ARCameraManagerTest : MonoBehaviour
{

  [SerializeField] private ARCameraManager _cameraManager;
  [SerializeField] private TextAsset _configText; // attach `face_detection_gpu.txt`

  //public ObjectronGraph objectronGraph;
  //private NativeArray<byte> _buffer;

  private CalculatorGraph _calculatorGraph;
  private NativeArray<byte> _buffer;
  private Stopwatch _stopwatch;
  private ResourceManager _resourceManager;
  private GpuResources _gpuResources;



  private IEnumerator Start()
  {
    //   var graphInitRequest = objectronGraph.WaitForInit(RunningMode.Async);
    //  yield return graphInitRequest;
    //  if (graphInitRequest.isError)
    //  {
    //    Debug.Log(graphInitRequest.error);
    //    yield break;
    //  }

    //  _cameraManager.frameReceived += OnCameraFrameReceived;

    //  var sidePacket = new SidePacket();

    //  sidePacket.Emplace("input_rotation", new IntPacket(0));
    //  sidePacket.Emplace("input_horizontally_flipped", new BoolPacket(false));
    //  sidePacket.Emplace("input_vertically_flipped", new BoolPacket(true));
    //  sidePacket.Emplace("model_type", new IntPacket(0));

    //  sidePacket.Emplace("allowed_labels", new StringPacket(objectronGraph.GetAllowedLabels(objectronGraph.category)));
    //  sidePacket.Emplace("max_num_objects", new IntPacket(objectronGraph.maxNumObjects));

    //  Debug.Log($"Category = {objectronGraph.GetAllowedLabels(objectronGraph.category)}");
    //  Debug.Log($"Max Num Objects = {objectronGraph.maxNumObjects}");

    //  objectronGraph.StartRun(sidePacket);
    //-------------------

    _cameraManager.frameReceived += OnCameraFrameReceived;
    _gpuResources = GpuResources.Create().Value();
  _calculatorGraph = new CalculatorGraph(_configText.text);
  _calculatorGraph.SetGpuResources(_gpuResources).AssertOk();

    _stopwatch = new Stopwatch();

  _resourceManager = new StreamingAssetsResourceManager();
    yield return _resourceManager.PrepareAssetAsync("object_detection_ssd_mobilenetv2_oidv4_fp16.bytes");
    yield return _resourceManager.PrepareAssetAsync("object_detection_oidv4_labelmap.txt");
    yield return _resourceManager.PrepareAssetAsync("object_detection_3d_sneakers.bytes", "object_detection_3d.bytes",true);



  _calculatorGraph.ObserveOutputStream("lifted_objects", 0, OutputCallback, true).AssertOk();

  var sidePacket = new SidePacket();
  sidePacket.Emplace("input_rotation", new IntPacket(0));
    sidePacket.Emplace("input_horizontally_flipped", new BoolPacket(false));
    sidePacket.Emplace("input_vertically_flipped", new BoolPacket(true));
    sidePacket.Emplace("model_type", new IntPacket(0));

    sidePacket.Emplace("allowed_labels", new StringPacket("Footwear"));
    sidePacket.Emplace("max_num_objects", new IntPacket(1));

    _calculatorGraph.StartRun(sidePacket).AssertOk();
    _stopwatch.Start();


  }


  private void OnDestroy()
  {
    //_cameraManager.frameReceived -= OnCameraFrameReceived;

    //var status = objectronGraph.calculatorGraph.CloseAllPacketSources();
    //if (!status.Ok())
    //{
    //  Debug.Log($"Failed to close packet sources: {status}");
    //}

    //status = objectronGraph.calculatorGraph.WaitUntilDone();
    //if (!status.Ok())
    //{
    //  Debug.Log(status);
    //}

    //objectronGraph.calculatorGraph.Dispose();
    //_buffer.Dispose();
    //---------------
    _cameraManager.frameReceived -= OnCameraFrameReceived;

    var status = _calculatorGraph.CloseAllPacketSources();
    if (!status.Ok())
    {
      Debug.Log($"Failed to close packet sources: {status}");
    }

    status = _calculatorGraph.WaitUntilDone();
    if (!status.Ok())
    {
      Debug.Log(status);
    }

    _calculatorGraph.Dispose();
    _gpuResources.Dispose();
    _buffer.Dispose();

  }

  private unsafe void OnCameraFrameReceived(ARCameraFrameEventArgs eventArgs)
  {
    //if (_cameraManager.TryAcquireLatestCpuImage(out var image))
    //{
    //  InitBuffer(image);

    //  var conversionParams = new XRCpuImage.ConversionParams(image, TextureFormat.RGBA32);
    //  var ptr = (IntPtr)NativeArrayUnsafeUtility.GetUnsafePtr(_buffer);
    //  image.Convert(conversionParams, ptr, _buffer.Length);
    //  image.Dispose();

    //  var imageFrame = new ImageFrame(ImageFormat.Types.Format.Srgba, image.width, image.height, 4 * image.width, _buffer);
    //  var currentTimestamp = objectronGraph._stopwatch.ElapsedTicks / (TimeSpan.TicksPerMillisecond / 1000);
    //  var imageFramePacket = new ImageFramePacket(imageFrame, new Timestamp(currentTimestamp));

    //  objectronGraph.calculatorGraph.StartRun().AssertOk();

    //  objectronGraph.calculatorGraph.AddPacketToInputStream("input_video", imageFramePacket).AssertOk();
    //}
    //----------------
    if (_cameraManager.TryAcquireLatestCpuImage(out var image))
    {
      InitBuffer(image);

      var conversionParams = new XRCpuImage.ConversionParams(image, TextureFormat.RGBA32);
      var ptr = (IntPtr)NativeArrayUnsafeUtility.GetUnsafePtr(_buffer);
      image.Convert(conversionParams, ptr, _buffer.Length);
      image.Dispose();

      var imageFrame = new ImageFrame(ImageFormat.Types.Format.Srgba, image.width, image.height, 4 * image.width, _buffer);
      var currentTimestamp = _stopwatch.ElapsedTicks / (TimeSpan.TicksPerMillisecond / 1000);
      var imageFramePacket = new ImageFramePacket(imageFrame, new Timestamp(currentTimestamp));

      _calculatorGraph.AddPacketToInputStream("input_video", imageFramePacket).AssertOk();
    }

  }

  private void InitBuffer(XRCpuImage image)
  {
    var length = image.width * image.height * 4;
    if (_buffer == null || _buffer.Length != length)
    {
      _buffer = new NativeArray<byte>(length, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
    }
  }

  [AOT.MonoPInvokeCallback(typeof(CalculatorGraph.NativePacketCallback))]
  private static Status.StatusArgs OutputCallback(IntPtr graphPtr, int steramId, IntPtr packetPtr)
  {
    try
    {
      using (var packet = new DetectionVectorPacket(packetPtr, false))
      {
        var value = packet.IsEmpty() ? null : packet.Get();

        if (value != null && value.Count > 0)
        {
          foreach (var detection in value)
          {
            Debug.Log(detection);
          }
        }
      }
      return Status.StatusArgs.Ok();
    }
    catch (Exception e)
    {
      return Status.StatusArgs.FailedPrecondition(e.ToString());
    }
  }
}
`

**Comment by homuler** [comment]
The output type of the `lifted_objects` stream is `FrameAnnotation`, not `DetectionVector`, so you cannot use `DetectionVectorPacket` to get the output value.
https://github.com/homuler/MediaPipeUnityPlugin/blob/391d7d98b127ce41ceac85ec47f6126664f1bc4e/Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronGraph.cs#L82

P.S.
I recommend you use `OutputStream` instead of calling `CalculatorGraph#ObserveOutputStream` directly.

```cs
  private IEnumerator Start()
  {
    // ...
    _liftedObjectsStream = new OutputStream<FrameAnnotationPacket, FrameAnnotation>(_calculatorGraph, "lifted_objects");
    _liftedObjectsStream.AddListener(OutputCallback);
    _calculatorGraph.StartRun(sidePacket).AssertOk();
    // ...
  }

  private void OutputCallback(object stream, OutputEventArgs<FrameAnnotation> eventArgs)
  {
    Debug.Log(eventArgs.value);
  }
```
