### ISSUE TITLE
OutOfMemory crash  iPhone 6, iOS 12.5.5

### ISSUE THREAD

**Issue by TMW81** [homuler/MediaPipeUnityPlugin#804]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.12f1

### Your Host OS

Windows 11

### Target Platform

iOS

### Description

When using SelfieSegmentation on iOS, I have crash and exception:
OutOfMemory: The OS most likely terminated your app because it overused RAM.

It is probably connected with MediaPipe plugin, because it happens always when the plugin starts to crop the background.
On other iOS devices (higher versions than iPhone 6) it works fine.

Please tell me, is it possible that MediaPipe is too 'heavy' to run on iPhone6? Or what are the minimal device requirements for Selfie Segmentation? 

Thanks in advance for the response.

**Comment by homuler** [comment]
> is it possible that MediaPipe is too 'heavy' to run on iPhone6?

Please make sure that you can run [the official sample app](https://google.github.io/mediapipe/solutions/selfie_segmentation.html#mobile) on your iPhone 6.
If it runs, then you may be able to reduce the memory usage of this project's sample app.

**Comment by TMW81** [comment]
Thank you.
