### ISSUE TITLE
World Position for physics based collision with AR Objects

### ISSUE THREAD

**Issue by AbdullahNarsun** [homuler/MediaPipeUnityPlugin#813]
### Feature Description

I am using sneaker model of objectron scene, Feeding AR Camera´s visual as an input to the model and its working great (All thanks to you). But the problem is am looking for a more physical collision for kick placement. So I want to get the world position of the detected object to place a collider over there and to collide with ball in scene. 

I tried all annonation controllers from scene but I guess I am not getting actual position of object. Is there anything you can help with me?

Here is the reference video link (https://drive.google.com/file/d/1BGAgiYjj1xTARfEJ_pTKdr5414J7rlaR/view?usp=drivesdk)

### Current Behaviour/State

Distance base kick placement. In the current behaviour I am getting world origin from Transform Annonation script and after converting them to screen points just figuring out the distance when foot come near to ball´s screen point placing the kick.

**Comment by homuler** [comment]
Please use [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).

> I guess I am not getting actual position of object.

If you think so, then please explain in more detail and convince me of that (maybe the same as #780 ?).

**Comment by BilalatNarsun** [comment]
The problem I figure out is my when I rotate my Camera it is actually expanding the image by some mean @homuler.
When I rotate up it squeeze down and when I rotate down it's squeeze up. But I keep the AR in exact portrait the texture matches with with AR. How can I stop image to do this behavior. What I want to achieve is to get the exact world points to interact with physics objects in scene. 

I tried your solution of  1080/1800 but could not understand it at all.

**Comment by homuler** [comment]
> > I tried your solution of 1080/1800 but could not understand it at all.

See https://github.com/homuler/MediaPipeUnityPlugin/issues/780#issuecomment-1312334889.
So did it work?

If you just don't know how to use ARFoundation, please google it.
If you have any further questions, please create [another support issue](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).
