### ISSUE TITLE
iOS crash when changing scenes with Selfie Segmentation 

### ISSUE THREAD

**Issue by LoopIssuer** [homuler/MediaPipeUnityPlugin#814]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.12f1

### Your Host OS

Windows 11

### Target Platform

iOS

### Description

Hi,
Only on iOS build (iPhone XR) when navigating between scenes several times (5-10 times), and one scene is initializing MediaPipe Selfie Segmentation sample, I get crash.
It is hard to get a log when the app crashes, but sometimes I get this errors (they are watched with Sentry, but almost always only one of them at once:

`System.InvalidOperationException: The table is full
  File "GlobalInstanceTable.cs", line 36, in Add
  File "Assembly-CSharp3.cpp", line 15896, in Start
  File "GraphRunner.cs", line 99, in Start`
  
  `System.NullReferenceException: Object reference not set to an instance of an object.
  File "SolutionCustom.cs", line 101, in ReadFromImageSource
  File "ImageSourceSolutionCustom.cs", line 110, in Run`

`System.NullReferenceException: Object reference not set to an instance of an object.
  File "Assembly-CSharp1.cpp", in WaitForWebCamTexture { <lambda> }
...
(1 additional frame(s) were not displayed)`

Please, give some advice what can be a reason of that crash.

**Comment by TMW81** [comment]
I have also take a snapshot of the scene after enter/exit this scene and there is possibly memory leak pointing to TextureFreame.
Please take a look at the screen. I think this issue is similar: https://github.com/homuler/MediaPipeUnityPlugin/issues/450
![image](https://user-images.githubusercontent.com/29869511/208772795-b3e7893e-581d-4951-8f79-e4d2093b29c4.png)

**Comment by TMW81** [comment]
I don't know, but maybe it is somehow connected with TextureFramePool - maybe pooled frames are not disposed correctly on destroy?

**Comment by homuler** [comment]
Is the error reproducible with the sample app (this unity project)? 

It seems that you have changed some code and the change can be causing this issue.
In that case, please fill the `Code to Reproduce the issue` field.

> **Code to Reproduce the issue**
>
> _No response_

**Comment by TMW81** [comment]
Could you please give me a hint which class could be responsible for that? I would like to paste the code, but don't know which one...
I made some changes in SelfieSegmentationSolution.cs, Bootstrap.cs, WebCamSource.cs, MaskAnnotation.cs and Screen.cs.

**Comment by TMW81** [comment]
Ok, I tested sample app - I think issue is present. I am switching between Face detection scene and Selfie segmentation scene - the memory leak is present I think.
However I attached modified scripts. Please take a look and give me a hint - maybe I messed up with something also.
![imaege](https://user-images.githubusercontent.com/29869511/209198686-d2f40442-7236-46ba-a712-7747a0dae75e.png)
[SelfieSegmentationCustom.zip]
(https://github.com/homuler/MediaPipeUnityPlugin/files/10289483/SelfieSegmentationCustom.zip)
[MaskAnnotation.zip](https://github.com/homuler/MediaPipeUnityPlugin/files/10289525/MaskAnnotation.zip)

**Comment by homuler** [comment]
> the memory leak is present I think.

Which part did you look at to determine that there is a memory leak?
I can see that the `Untracked Memory` has surely increased, but after all, it is _untracked_ and the memory profiler should not know when it was/will be freed.

> Could you please give me a hint which class could be responsible for that

Please [provide source code to reproduce the issue ((share the link to your repository if possible))](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/.github/ISSUE_TEMPLATE/support.yml).
If I cannot confirm the issue on my local machine, then there's nothing I can do (so the URL to the project repository is usually preferable).

**Comment by TMW81** [comment]
Yeah, you are right.
However, it is difficult to provide source code to reproduce. Instead, could you please answer one question:
How to, properly, change **in the sample app** scene from any of your scenes, to a scene without working/active Bootstrap and other components (like Solution, ImageSource etc.)? I mean: how to disable properly your plugin?

**Comment by homuler** [comment]
> it is difficult to provide source code to reproduce. 

It's OK, but note that I won't support you unless the necessary information is provided.

> How to, properly, change **in the sample app** scene from any of your scenes, to a scene without working/active Bootstrap and other components (like Solution, ImageSource etc.)?

The sample app uses the `Bootstrap` and `Solution` classes to switch and run scenes, so you can't do that.
Of course, if you rewrite or add some classes, you may be able to do that.

> I mean: how to disable properly your plugin?

I don't get what you mean. If you don't need to use the plugin, then you can just remove it from your project.
If you are referring to components under `Assets` by the word `plugin`, then you don't need to use them in the first place (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial).

**Comment by LoopIssuer** [comment]
_

> I mean: how to disable properly your plugin?

_

Sorry for the wrong explanation. 
Let's say I add a new, empty Unity Scene to the sample app. When I switch to this empty scene, I would like to have memory cleared from all things connected to MediaPipe Unity plugin (in particular I want to clear memory from Textures used by Plugin). Should it happen with Solution.Stop()? Or should I use some other method?

**Comment by homuler** [comment]
`Solution.Stop()` will stop MediaPipe, but to clear all the `Texture`s, at least you need to destroy `TextureFramePool`.
However, the sample app does not assume `TextureFramePool` will be destroyed while the app is running, it may not work as you expect (maybe `TextureFrame` should be `IDisposable`?).

**Comment by LoopIssuer** [comment]
Thanks. So how to destroy (release from memory) the pooled TextureFrames?

**Comment by homuler** [comment]
If it is a problem, probably you need to destroy them explicitly here.
https://github.com/homuler/MediaPipeUnityPlugin/blob/42f9117fb2000a87c2dad5e024255f3c0a51600d/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/TextureFramePool.cs#L51-L68

**Comment by LoopIssuer** [comment]
I already tried:
`        private void OnDestroy()
        {
            lock (((ICollection)_availableTextureFrames).SyncRoot)
            {
                for (int i = _availableTextureFrames.Count - 1; i >= 0; i--)
                {
                    var textureFrame = _availableTextureFrames.ToList()[i];
                    textureFrame.Release();
                    textureFrame.OnRelease.RemoveListener(OnTextureFrameRelease);
                    textureFrame = null;
                }

                _availableTextureFrames.Clear();
                _availableTextureFrames = null;
            }

            lock (((ICollection)_textureFramesInUse).SyncRoot)
            {
                for (int i = _textureFramesInUse.Values.Count - 1; i >= 0; i--)
                {
                    var textureFrame = _textureFramesInUse.Values.ToList()[i];
                    textureFrame.Release();
                    textureFrame.OnRelease.RemoveListener(OnTextureFrameRelease);
                    textureFrame = null;
                }
            
                _textureFramesInUse.Clear();
                _textureFramesInUse = null;
            }
            Resources.UnloadUnusedAssets();
        }`


It helped there were much more textures in the memory, but still there are some in memory on other scene:
It looks like for each scene change, one texture (from TextureFramePool probably) remains in memory:

![image](https://user-images.githubusercontent.com/29869511/209776284-1b2501e5-143f-4c3d-a893-82e0729f4c0f.png)

**Comment by homuler** [comment]
Again, can you reproduce it with the sample app (without any change)?

**Comment by homuler** [comment]
> one texture (from TextureFramePool probably) remains in memory

I'm not sure, but maybe the texture of the `Screen`?
https://github.com/homuler/MediaPipeUnityPlugin/blob/2c8a31ae5b4232fbffd97fdc6b4f2b8f1a6370b4/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs#L14

**Comment by LoopIssuer** [comment]
Yes! Thank you. 
One last thing - why there still exists these small textures marked in red? I was hoping they will be released with those 0,6 textures.
![image](https://user-images.githubusercontent.com/29869511/209781330-75482e73-91d7-4f60-b6e9-23c86961d835.png)

**Comment by LoopIssuer** [comment]
Oh, they are probably created outside MediaPipe Unity Plugin.

Thank you for your great support!
Have a nice day and a Happy New Year 2023!
