### ISSUE TITLE
do you have a plan to update mediapipe version from 0.8.10 to 0.8.11?

### ISSUE THREAD

**Issue by choigawoon** [homuler/MediaPipeUnityPlugin#815]
### Feature Description

if you dont mind, i want your plugin having mediapipe plugin 0.8.11 as you did for 0.8.10, https://github.com/homuler/MediaPipeUnityPlugin/issues/585  
here's the mediapipe release, https://github.com/google/mediapipe/releases/tag/v0.8.11  

### Current Behaviour/State

multiple landmark values for handtracking on the client side are different with my server using mediapipe 0.8.11  

### Additional Context

i'm in development on my AR Game using the HandTracking Solution.
there is a server to predict where my gesture of player is correct or not.

i'm in trouble with poor performance on my unity game because my game send a image made from webcam at 10fps.
i tried to fix this by getting the values for hand tracking on the client side and send them instead of the image, but the values are slightly different from on my server side when detecting the same video source.

i guess it`s from the version difference of mediapipe between my server and my client.

or if you give me an any advice how to upgrade the version of mediapipe on my self, it would be good for me.

thank you

**Comment by homuler** [comment]
I'm planning to upgrade the MediaPipe version if the next version is released.

> i guess it`s from the version difference of mediapipe between my server and my client.

Is the difference important?
If so, I'll seriously consider it, but if only the fact there're differences in the result is important, I think you can downgrade the MediaPipe version you're running on your server.

>  if you give me an any advice how to upgrade the version of mediapipe on my self, it would be good for me.

Please see https://github.com/homuler/MediaPipeUnityPlugin/pull/585.
At least, you need to update the [`WORKSPACE`](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/WORKSPACE) file, and in most cases, you also need to update patch files under the [`third_party`](https://github.com/homuler/MediaPipeUnityPlugin/tree/4cd3a549a432718b9140223d867c2e2ad9cdffc5/third_party) directory.

**Comment by homuler** [comment]
resolved by #837
