### ISSUE TITLE
I want to combine Face Detection and Hand tracking sample in one scene, or fix Holistic demo.

### ISSUE THREAD

**Issue by HiddenStar0412** [homuler/MediaPipeUnityPlugin#816]
### Description

I am currently developing an app that tracks faces and hands at the same time.
Initially, I started with a sample from Holistic, but the performance we wanted from our mobile devices is not coming out.
In fact, my app doesn't need entire feature like Holistic's FaceMesh, it only needs to track the location of the eyes, nose, and mouth.
So I tried to combine only Face Detection and Hand Tracking of the sample, but it was impossible to combine because the two samples use different tracking graphs.
I tried to simplify and optimize the tracking of Holistic, but eventually found that we had to rebuild the library by rewriting the Calculator of HolisticLandmarkCpu from the config information file(holistic_cpu.txt , etc).
But I don't know what to do with it.
There is no way in Unity, and I think we need to change from the original library.
I don't know the specific method, so please let me know if there is any helpful information.

**Comment by homuler** [comment]
> So I tried to combine only Face Detection and Hand Tracking of the sample, but it was impossible to combine because the two samples use different tracking graphs.

You can write a new `CalculatorGraphConfig` combining calculators by yourself (for example, you can overwrite [face_detection_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/Assets/MediaPipeUnity/Samples/Scenes/Face%20Detection/face_detection_cpu.txt)).
If you don't know how to do it, please ask a question in the official MediaPipe community.

> I tried to simplify and optimize the tracking of Holistic, but eventually found that we had to rebuild the library by rewriting the Calculator of HolisticLandmarkCpu from the config information file(holistic_cpu.txt , etc).

I think it is easier to add a new one than to rewrite it.
Please see [iris_landmarks_from_face_landmarks_cpu.pbtxt](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/mediapipe_api/modules/iris_landmark/iris_landmarks_from_face_landmarks_cpu.pbtxt) and how the `IrisLandmarkLeftAndRightFromFaceLandmarksCpu` calculator [is](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/mediapipe_api/modules/iris_landmark/BUILD) [built](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/mediapipe_api/BUILD#L385).
