### ISSUE TITLE
Working on Unity and Windows Build but when i install it on my phone. Installing and showing camera but no graph.

### ISSUE THREAD

**Issue by ubaid10cs97** [homuler/MediaPipeUnityPlugin#818]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

windows 10

### Target Platform

Android

### Command Sequences

set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

### Log

its installing but not showing graph on android. ndk and sdk checked.

**Comment by homuler** [comment]
Will you describe your issue more precisely?
I don't know what is your issue, but maybe it's the same as https://github.com/homuler/MediaPipeUnityPlugin/issues/727#issuecomment-1231614357?

> **Log**

Check on the `Development Build` and share the player log (e.g. `adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`).
