### ISSUE TITLE
Reprojecting values from mediapipe to Kinect depth map

### ISSUE THREAD

**Issue by MoritzSkowronski** [homuler/MediaPipeUnityPlugin#819]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.16f1

### Your Host OS

macOS Monterey 12.6.2

### Target Platform

UnityEditor, Windows Standalone

### Description

Hello,

I'm currently building an installation where a Kinect is mounted at the ceiling, looking down on the table. I want to detect the touch of users on the table. For this, I came up with the somewhat weird solution of feeding the Kinect IR image into media pipe to get the x and y values for the hands. Then, using these 2D values, I could sample the depth map of the Kinect to get the correct world position (as seen from the Kinect) for the hands. 

My current plan is, I need to be able to either:

1. Add the depth map to a TextureFrame while its being processed by media pipe to retrieve it later (so the results would either hold the depth map or contain a pointer to it)
2. Use the timestamp of the texture to manage a second dictionary containing the depth map for each timestamp. After inspecting the code, this could in theory be done in the TextureFramePool, am I correct?

So my question is now whether there is a more easy solution to this and if not, whether my two assumptions up there are feasible! ;) Of course, it would be best, if there would be a solution that allows using async mode.

**Comment by homuler** [comment]
Note that you don't need to use `TextureFrame` or `TextureFramePool` to run this plugin (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#send-imageframe).
These classes are placed under `Assets/`, which only belongs to the sample project, not the plugin package (if I can come up with a generic enough I/F, I may include it in the package).

> Of course, it would be best, if there would be a solution that allows using async mode.

I think what you need to do to use the async mode is to make sure that you can access the depth map corresponding to [the output value](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/Assets/MediaPipeUnity/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs#L103) from the callback method (maybe we should pass the timestamp [here](https://github.com/homuler/MediaPipeUnityPlugin/blob/4cd3a549a432718b9140223d867c2e2ad9cdffc5/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs#L402)?).
