### ISSUE TITLE
How to get current WebCam texture using only "(HandTrackingSolution)solution" attribute inside external class/module in Unity?

### ISSUE THREAD

**Issue by Drunkensteinn** [homuler/MediaPipeUnityPlugin#820]
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.3f1

### Your Host OS

Ubuntu20.04 - Windows 10;

### Target Platform

UnityEditor, Linux Standalone

### Description

Greetings. I'm struggling with the custom/educational implementation of some game. I figured out that I need a current input WebCamera frame or WebCameraTexture, so as HandTrackingSolution was Inherited from the Solution class, I thought that I can use the GetCurrentTextureFrame() method, which returns a Texture's object. Please, I looking forward for some valuable advice. 

### Code to Reproduce the issue

public Mediapipe.Unity.Solution solution;
.
.
.
var texture = ((HandTrackingSolution)solution).imageSource.GetCurrentTexture();

It gives an error: NullReferenceException: Object reference not set to an instance of an object
Instantiation and allocation gave the same results. I used Coroutines to be sure that the camera thread would take up with the main thread.

**Comment by Drunkensteinn** [comment]
I need to process those textures continuously and output on a different window.

**Comment by homuler** [comment]
> **Code to Reproduce the issue**

Please write the code as completely as possible so that you think I can reproduce the error in my local environment.

Have you already tried [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#official-solution)?
