### ISSUE TITLE
Presence and Visible of NormalizedLandmark  always zero

### ISSUE THREAD

**Issue by fishhead012** [homuler/MediaPipeUnityPlugin#827]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.5f1

### Your Host OS

window 10

### Target Platform

Android

### Description

Presence and Visible of mediapipe::NormalizedLandmarkList  always zero.

but mediapipe::LandmarkList has Presence and Visible correct value.

how can i get Presence and Visible of mediapipe::NormalizedLandmarkList ?

**Comment by homuler** [comment]
duplicates #601 

Please check if [the official sample app](https://google.github.io/mediapipe/solutions/hands.html#example-apps) returns `presence` first.
