### ISSUE TITLE
Issue happens when I make the project for Windows10

### ISSUE THREAD

**Issue by tinatinaZ** [homuler/MediaPipeUnityPlugin#83]
Hi there, I was able to run Hello World of MediaPipe on my Windows 10. But I couldn't build this project since it keeps showing this error that I don't know how to fix.

> ERROR: C:/_bzl/v4hcamu3/external/org_tensorflow/tensorflow/lite/kernels/BUILD:663:11: Compiling tensorflow/lite/kernels/elementwise.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 66 argument(s) skipped)
cl : Command line warning D9002 : ignoring unknown option '-O3'
external/org_tensorflow/tensorflow/lite/kernels/elementwise.cc(299): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1518)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
INFO: Elapsed time: 220.193s, Critical Path: 181.51s
INFO: 2478 processes: 352 internal, 2126 local.
FAILED: Build did NOT complete successfully
make: *** [Makefile:46: cpu] Error 1

By the way I linked Visual Studio 2019 to the bazel variables when I installed MediaPipe, so I am not sure why the error is related to Visual Studio 2017.
Really appreciate your help!

**Comment by BarnabasTakacs** [comment]
Hello,

I am also trying to build this for Windows without success. Which 'make' are you using?
I tried MingW and Basel builds , but all failed. 
Thanks in advance

**Comment by tinatinaZ** [comment]
> Hello,
> 
> I am also trying to build this for Windows without success. Which 'make' are you using?
> I tried MingW and Basel builds , but all failed.
> Thanks in advance

I tried MinGW in MSYS2, failed too.

**Comment by homuler** [comment]
I think this is same as https://github.com/homuler/MediaPipeUnityPlugin/issues/46
