### ISSUE TITLE
LocalResourceManager 

### ISSUE THREAD

**Issue by Wayne-nulitics** [homuler/MediaPipeUnityPlugin#830]
### Plugin Version or Commit ID

v0.8

### Unity Version

2021.3.16f1

### Your Host OS

Windows 10 

### Target Platform

Android

### Description

Can you use LocalResourceManager and manually copy the model files to the Persistant Path for runtime?
I would like to be able to update the models over time without needing to redeploy a .apk, so each time I update the model file it gets downloaded to the Persistance data path and the user quicks and reloads the app to reload the new models.
I don't want to use StreamingAssets that are hardcoded during the build.

**Comment by homuler** [comment]
> Can you use LocalResourceManager 

No. `LocalResourceManager` can run only on UnityEditor.
You need to implement `ResourceManager` for your purposes.

**Comment by Wayne-nulitics** [comment]
@homuler would it be possible to schedule a session with you to discuss my project and see if its possible with this plugin, I did a lot of testing with OpenCV and DNN in Unity, NatML, Unity Baracuda but none of them could give me what I want, I'm comfortable using MediaPipe but would like a technical session, like a deep dive, covering 3 very specific topics, they are: Dynamic/Runtime model files, howto, even if a reload is required, just not an new app install, then the support for segementation and finally the config files, comfortable to make it worth your while. Since I'm still prototyping it's all still up in the air, some pointers would be welcome.

**Comment by homuler** [comment]
> would it be possible to schedule a session with you to discuss my project

Do you mean that you want to sign a support contract with me?

**Comment by Wayne-nulitics** [comment]
@homuler Yup

**Comment by Wayne-nulitics** [comment]
@homuler How do I contact you outside of a github post?

**Comment by Wayne-nulitics** [comment]
> > would it be possible to schedule a session with you to discuss my project
> 
> Do you mean that you want to sign a support contract with me?

Hi, can you email me your details? I'd like to discuss this option with you.

**Comment by homuler** [comment]
I would be most grateful if you could use [ko-fi](https://ko-fi.com/homuler) DMs.
