### ISSUE TITLE
Handtracking to a SMPL-X avatar with mediapipe Holistic

### ISSUE THREAD

**Issue by Hakoware** [homuler/MediaPipeUnityPlugin#831]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.2.17.f1

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### Description

I am trying to apply handtracking to a smpl-x avatar with mediapipe holistic, I am implementing the right hand detection and I manage to extract the landmarks from ``` OutputEventArgs<NormalizedLandmarkList> eventArgs ```
 located in ```HolisticTrackingSolution.``` And I get this ```[ { { "x": 0.394239277, "y": 0.5861167, "z": 4.6727007E-07 }, { "x": 0.447378844, "y": 0.59169513, "z": -0.0270992424 },..... ```

So I process them and be able to assign each coordinate to the SMPL-X avatar but I don't get the result I need which is to be able to replicate my hand and as you can see the avatar deforms. I don't know if the mediapipe "z" coordinate can be used directly in Unity.

I think the problem occurs with the depth of the points, which is not directly provided by the landmark of the hands.

![image](https://user-images.githubusercontent.com/112647766/212679713-5a7a118a-5716-4424-b94f-1a5890540953.png)

### Additional Context

Currently mediapipe has 21 points and SMPL-X has 15 so I don't consider points 4,8,12,16 and 20.

**Comment by homuler** [comment]
Sorry, what do you want me to do?

**Comment by Hakoware** [comment]
Hi! the idea is that the SMPL-X avatar can replicate mi hand exactly where the hand landmarks are.

**Comment by homuler** [comment]
> as you can see the avatar deforms.

Actually, I don't know if it deforms or not since I don't know the original avatar.

> I think the problem occurs with the depth of the points

If you set z to 0, does it display as expected?

**Comment by homuler** [comment]
The Z value is not precise, so to get good results, I think you need to tweak the value.
However, if the result is extremely distorted, I think it's more likely that your code has bugs.
cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/94#issuecomment-973545978

**Comment by Hakoware** [comment]
Thank you so much I will check it out. 
This is an example of the main idea I need to address.

https://twitter.com/tesseraktzero/status/1305079376539561985

https://www.youtube.com/watch?v=8Va3_jwYOJU
