### ISSUE TITLE
Open / Close Example-Scene from Menu

### ISSUE THREAD

**Issue by mgarbade** [homuler/MediaPipeUnityPlugin#833]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Pro

### Target Platform

Windows Standalone, Android

### Description

I'm trying to build a simple app that 
- boots into a (very simple, self-written) menu scene
- from there opens a solution (e.g. Pose Tracking Scene) 
- go back to the menu scene
- open again Pose Tracking Scene

sounds very simple. But I'm running into some issues as described below. 

My question in short: 
- How can I completely clean up a "Solution Scene", i.e. stop / dispose of mediapipe entirely such that I can close the scene and later restart it?

### Code to Reproduce the issue

- pressing "Play" triggers 

      SceneManager.LoadScene(1);

which simply opens the "Pose Tracking Scene" (from the cleanly imported MediaPipeUnityPlugin version 0.10.3) 
![2023-01-20 15_35_33-Window](https://user-images.githubusercontent.com/3956593/213744319-2ce88561-b8f2-4906-8283-1c1d8efc7c28.jpg)
- inside the Pose Tracking Scene is a new "Back Button" (see footer) that triggers

    SceneManager.LoadScene(0);

which brings back the menu scene
![2023-01-20 15_35_51-Window](https://user-images.githubusercontent.com/3956593/213744339-500dfe97-b1bc-41bc-8775-b629bb35e263.jpg)

- now when I press "Play" again I get various errors:
  - in Unity Editor-Play-Mode 
    - the whole Editor crashes
    -> turns out this is due to [Glog being called twice](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs#L49-L61) inside mediapipe, which causes the crash
  - on Android the Scene loads but no recognition is working (probably due to a similar error)

# What did I try so far?

1. when I disable Glog, I'm getting the next error: "ResourceManager can be initialized only once"

2. trying to calls [_solution.Stop()](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs#L50) on the PoseTrackingSolution before exiting the scene 
  -> weirdly this doesn't seem to make a difference
3. creating a Bootstrap GameObject in the Menu Scene similar to the "Start Scene" Scene in the `MediaPipeUnity/Samples/UI/Scripts`
  -> problem of double initializations persists
  -> also this solution feels a little unclean, as mediapipe apparently runs in background throughout the entire app (also when its not needed like in the menu) 
4. commenting  [throw new InvalidOperationException("ResourceManager can be initialized only once");](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/ResourceManager.cs#L35)
  -> leads to the next problem of the Webcam not starting properly ("TimeoutException: Failed to start WebCam")

**Comment by mgarbade** [comment]
Update: Today things seem to run fine, applying the above mentioned 4 tricks....
(not sure what was wrong before)

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/732#issuecomment-1236893275.
