### ISSUE TITLE
3D object not attaching properly in my Landmarks

### ISSUE THREAD

**Issue by iamkim17** [homuler/MediaPipeUnityPlugin#835]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.3f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor, Android

### Description

I successfully got the position of the landmarks and translate its position to a cube, I'm trying to attach the cube to the shoulder but the cube didn't totally attach where the shoulder landmark is, it's kinda floating while getting the position.

![image](https://user-images.githubusercontent.com/11855668/215007846-0e32958b-f3ea-447d-a979-8052e7ac0911.png)

### Code to Reproduce the issue

if (poseLandmarksStream.TryGetNext(out var poseLandmarks))
      {
        if (poseLandmarks != null && poseLandmarks.Landmark.Count > 0)
        {
          var shoulder = new Vector3(poseLandmarks.Landmark[11].X, poseLandmarks.Landmark[11].Y, poseLandmarks.Landmark[11].Z);
          //Move cube object to shoulder landmark
          newObject.transform.position = shoulder * 2;
          foreach (var landmarks in poseLandmarks.Landmark)
          {
            // top of the head
            var topOfHead = landmarks;
            Debug.Log($"Unity Local Coordinates: {screenRect.GetPoint(topOfHead)}, Image Coordinates: {topOfHead}");
          }
        }
      }

### Additional Context

I tried this 

A list of 468 face landmarks. Each landmark consists of x, y and z. x and y are normalized to [0.0, 1.0] by the image width and height respectively. z represents the landmark depth with the depth at center of the head being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of z uses roughly the same scale as x.

**Comment by homuler** [comment]
> it's kinda floating while getting the position

> I tried this

Sorry, I didn't get what you'd like to say in these sentences.
You may want to read https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#coordinate-system and https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks first.

> Note that the output values are in the Image Coordinate System.
> To convert them to the Unity local coordinates, you can use methods defined in `ImageCoordinateSystem`.
>
> >   :bell: Which coordinate system the output is based on depends on the solution. For example, The Objectron Graph uses the Camera Coordinate System instead of the Image Coordinate System.

**Comment by iamkim17** [comment]
I'll look into those articles. Thank you!
