### ISSUE TITLE
Issue when Combining Hand Tracking with Instant Motion Tracking

### ISSUE THREAD

**Issue by DeveloperAugustus** [homuler/MediaPipeUnityPlugin#836]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2020.3.42f1

### Your Host OS

Windows 10 Home

### Target Platform

Android

### Description

Hello,
I am actually trying to combine Hand Tracking scene with Instant Motion Tracking scene.

So, far, this is what I have done -- 

1. Made a copy of instant motion tracking scene
2. added Hand Tracking components(copied from Hand tracking scene -- Main Canvas and Solution) and added in the hierarchy in the Instant Motion Tracking copied scene
3.  added all components promptly , and added the same main camera to the hand tracking main canvas in render camera slot, -- screen space -- camera
4. so, i have two solutions gameobject in hierarchy now -- one is for the instant motion tracking and one is for hand tracking 
5. two main canvas also, one is for the instant motion tracking and one is for hand tracking
6. so, when the build this scene and run it on my phone(oneplus 7 pro)

in initial startup, it runs the hand tracking and the instant motion tracking is stuck at the center of the screen.

and then from camera toggle menu, when i enable the screen would go black and, then you can get the blue sphere, moving according to your touch position and then at the same time, you can see the hands also, but not camera rendering, just black screen(screenshot attached)

![RefeerenceImage_mediapipeUnityissue](https://user-images.githubusercontent.com/33311565/215020438-4d1b6e9b-34c3-46bb-87cd-6a36fc549e8a.jpeg)

![RefereImage01 (1)](https://user-images.githubusercontent.com/33311565/215021841-9639a23d-bec0-4a1b-82a5-a7db849e24c3.jpeg)

my question and the area where i need help is, how can i combine both hand tracking and instant motion tracking in a single scene, with one camera?

i hope my explanation is clear to you, thanks and regards

### Code to Reproduce the issue

Here is the link to the project -- [https://drive.google.com/file/d/1fFkje1xvYg6iuZURxk3Sg_i2NEZKk09x/view?usp=share_link](url)

**Comment by homuler** [comment]
> how can i combine both hand tracking and instant motion tracking in a single scene, with one camera?

You can run `HandTrackingGraph` and `RegionTrackingGraph` at the same time, but I think you should write a single `CalculatorGraphConfig` where hand tracking and instant motion tracking are combined.

**Comment by DeveloperAugustus** [comment]
Many thanks for your time and help, i figured it out, both works good now.
Regards
