### ISSUE TITLE
Holistic Landmark | Visualize Z

### ISSUE THREAD

**Issue by MajorThom13** [homuler/MediaPipeUnityPlugin#839]
### Feature Description

Would be highly appreciated if you could make Holistic Landmark Visualize Z. The Pose Landmark has this, but it is missing all the cool features that Holistic is tracking.

Side note, would be nice if you had an example of a 3D character rigged up using Holistic Landmark and Pose Landmark.

**Comment by homuler** [comment]
> Would be highly appreciated if you could make Holistic Landmark Visualize Z

Will you explain it using a screenshot or video?
I'm not sure what is the missing feature, which the pose landmark has.

**Comment by MajorThom13** [comment]
Example photo shown below illustrating the flat 2d face and eye tracking.

I have looked in your code, and enabled Visualize Z where I could find it, but it doesn’t turn the face and eye tracking into a 3d object.

Having a vector3 output for face / head rotation would be nice too.

Preferably, it would be nice if you had a Unity example scene showing your tracking work with a rigged 3d avatar. That would really be excellent.

***@***.***


Tom

**Comment by homuler** [comment]
> Example photo shown below

Which photo? Maybe you attached to the email and not attached to this issue?

**Comment by MajorThom13** [comment]
Example picture attached.

You guys must realize you don’t have an example for showing the face elements or finger elements in 3D, only 2D.

If you can share an example of the body, the face, and the fingers all translated to a 3D avatar, that would be great.


***@***.***

**Comment by homuler** [comment]
> Example picture attached.

Well, please open this issue page using your browser.
You'll see what I mean...

I'm not sure what the issue is, but did you check `Visualize Z` of `HandLandmarkListAnnotationController`? 
![Screenshot_20230327_000535](https://user-images.githubusercontent.com/4690128/227784906-e3b5e6ed-71f6-49e6-847c-a785e68289d5.png)
