### ISSUE TITLE
Emotions & Scores

### ISSUE THREAD

**Issue by MajorThom13** [homuler/MediaPipeUnityPlugin#842]
### Feature Description

It would be nice if you could add emotion detection and score values to the project.

Would also be nice if you could add Gender, Age, Race, Blond Hair estimation (blond or not blond), etc.

Thanks!

**Comment by homuler** [comment]
> The goal of this project is to port the MediaPipe API (C++) one by one to C# so that it can be called from Unity.

To add features to MediaPipe is out of the project scope.
If you need those features, please ask MediaPipe developers.

Once they are supported by MediaPipe, then they would be in the scope.
