### ISSUE TITLE
Minimal requirements Android

### ISSUE THREAD

**Issue by LoopIssuer** [homuler/MediaPipeUnityPlugin#843]
### Description

Hi,
Is there any 'minimal requirements' list for running selfie segmentation on Android devices?
We are currently facing issue: client has Android 12 (Nokia C100), and image from selfie segmentation is not generated.
We have no access to the client's device, only small trace in remote logs:

```
UnityEngine.GraphicsBuffer..ctor (UnityEngine.GraphicsBuffer+Target target, System.Int32 count, System.Int32 stride) (at <00000000000000000000000000000000>:0)
Mediapipe.Unity.MaskAnnotation.InitMaskBuffer (System.Int32 width, System.Int32 height) (at <00000000000000000000000000000000>:0)
```
We are assuming that device is not very good, but maybe there is other reason?
Or maybe you could give a hint - what are minimal requirements for Android device to run selfie segmentation?

Thanks in advance for any help

**Comment by onuralpszr** [comment]
Hello;

Mediapipe sys requirements for android 

https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel

Maybe cause something you missing while MP compile or you change a code 

One question did you compile this solution (parameters are here : https://github.com/homuler/MediaPipeUnityPlugin/blob/master/build.py#L437) for example If you need face mesh we need to compile that too for run it.)

**Comment by homuler** [comment]
Not enough memory or something?

It seems that it fails on the following code.
https://github.com/homuler/MediaPipeUnityPlugin/blob/1a8563095f0d5e6b9816a4f639728c2cbafab208/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotation.cs#L113

I think It would be good to try to find out why this fails.

**Comment by gb2111** [comment]
> Hello;
> 
> Mediapipe sys requirements for android
> 
> https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel
> 
> Maybe cause something you missing while MP compile or you change a code
> 
> One question did you compile this solution (parameters are here : https://github.com/homuler/MediaPipeUnityPlugin/blob/master/build.py#L437) for example If you need face mesh we need to compile that too for run it.)

This looks like build requirements. Do u know any about Android's spec?

**Comment by homuler** [comment]
@LoopIssuer 
> Unfortunately, we have no access to the device on which it happens. So, if you had to guess - what could be the cause of this error?

I think you should think how you can identify the cause.
My guess is as I stated above.
> Not enough memory
