### ISSUE TITLE
How to get the value of all coordinates from handtracking?

### ISSUE THREAD

**Issue by afeloth69** [homuler/MediaPipeUnityPlugin#846]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.3f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### Description

I wanted to use the coordinates from the handtracking to move objects, but I'm unable to find where these are stored.

**Comment by onuralpszr** [comment]
Hello, 

If you look at the examples you can see there is "Draw" in [HandLandmarkListAnnotation Line 149](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HandLandmarkListAnnotation.cs#L149) is getting NormalizedLandmarkList target. They are basically "Normalized value between 0-1" and you can do convert to Unity Coordinates by using [GetPoint](https://github.com/homuler/MediaPipeUnityPlugin/blob/527d3b10ae593d43c74f466c5e23b2c2440c7b30/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/CameraCoordinate.cs#L169) in CameraCoordinate.cs


Also check the wiki : https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#coordinate-system

**Comment by homuler** [comment]
In the sample app, where you can access the output vary depending on[the running mode](https://github.com/homuler/MediaPipeUnityPlugin/issues/661#issuecomment-1189705966).

- In sync mode
https://github.com/homuler/MediaPipeUnityPlugin/blob/1a8563095f0d5e6b9816a4f639728c2cbafab208/Assets/MediaPipeUnity/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs#L79

- In non-blocking sync mode
https://github.com/homuler/MediaPipeUnityPlugin/blob/1a8563095f0d5e6b9816a4f639728c2cbafab208/Assets/MediaPipeUnity/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs#L83

- In async mode
read `eventArgs.value` of each callback
https://github.com/homuler/MediaPipeUnityPlugin/blob/1a8563095f0d5e6b9816a4f639728c2cbafab208/Assets/MediaPipeUnity/Samples/Scenes/Hand%20Tracking/HandTrackingSolution.cs#L103
