### ISSUE TITLE
Support for rotation on Android and iPhone in samples

### ISSUE THREAD

**Issue by gb2111** [homuler/MediaPipeUnityPlugin#847]
### Feature Description

Camera and pose detection will rotate accordingly to screen orientation.

### Current Behaviour/State

Currently pose detection and camera are aligned only with the initial screen orientation. When you rotate further, the camera preview is not as one would expect in the phone app. Below photo shows app initialized in portrait mode and then rotated to horizontal.
![obraz](https://user-images.githubusercontent.com/22025896/218061263-bde9ebe8-28b9-4b2a-805a-453f326bea82.png)

**Comment by homuler** [comment]
I am not planning to change this behavior as I am using the sample app to test the behavior when the device is rotated. 

At least, I think this is not essential for the sample app, so the priority is low.
