### ISSUE TITLE
Linking mediapipe_api/mediapipe_c.dll failed

### ISSUE THREAD

**Issue by Jvvv00** [homuler/MediaPipeUnityPlugin#849]
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2021.3.11f1

### Your Host OS

Window 11 Home

### Target Platform

UnityEditor, Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 14.34.31933
Windows SDK: 10.0.22000.0

### Command Sequences

For the installation guideline, i have follow the steps in https://www.youtube.com/watch?v=kMJOmzmMxZw and the installation guide given https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide. Everything was fine until i run the command
> python build.py build --desktop cpu -v

### Log

WARNING: C:/_bzl/4q5buzh5/external/com_google_mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule @com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_google_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: C:/_bzl/4q5buzh5/external/com_google_mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule @com_google_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_google_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe_api:mediapipe_desktop (43 packages loaded, 7843 targets configured).
INFO: Found 1 target...
ERROR: D:/mediapipeunityplugin-master/mediapipe_api/BUILD:255:10: Linking mediapipe_api/mediapipe_c.dll failed: (Exit 1120): link.exe failed: error executing command D:\Visual Studio\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt/bin/mediapipe_api/mediapipe_c.dll-2.params
   Creating library bazel-out/x64_windows-opt/bin/mediapipe_api/mediapipe_c.dll.if.lib and object bazel-out/x64_windows-opt/bin/mediapipe_api/mediapipe_c.dll.if.exp
LINK : warning LNK4217: symbol 'TfLiteXNNPackDelegateOptionsDefault' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'tflite_inference_calculator.lo.lib(tflite_inference_calculator.obj)' in function '"private: class absl::lts_20220623::Status __cdecl mediapipe::TfLiteInferenceCalculator::LoadDelegate(class mediapipe::CalculatorContext *)" (?LoadDelegate@TfLiteInferenceCalculator@mediapipe@@AEAA?AVStatus@lts_20220623@absl@@PEAVCalculatorContext@2@@Z)'
LINK : warning LNK4286: symbol 'TfLiteXNNPackDelegateDelete' defined in 'xnnpack_delegate.lib(xnnpack_delegate.obj)' is imported by 'inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)'
face_detection_options_registry.lo.lib(face_detection_options_lib.obj) : error LNK2019: unresolved external symbol "private: static class RegistrationToken::RegistrationToken const mediapipe::tool::OptionsRegistry::registration_token<class mediapipe::FaceDetectionOptions>" (??$registration_token@VFaceDetectionOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@0VRegistrationToken@3@B) referenced in function "??__E?$registration_token@VFaceDetectionOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ" (??__E?$registration_token@VFaceDetectionOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ)
inference_calculator_options_registry.lo.lib(inference_calculator_options_lib.obj) : error LNK2019: unresolved external symbol "private: static class RegistrationToken::RegistrationToken const mediapipe::tool::OptionsRegistry::registration_token<class mediapipe::InferenceCalculatorOptions>" (??$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@0VRegistrationToken@3@B) referenced in function "??__E?$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ" (??__E?$registration_token@VInferenceCalculatorOptions@mediapipe@@@OptionsRegistry@tool@mediapipe@@YAXXZ)
bazel-out\x64_windows-opt\bin\mediapipe_api\mediapipe_c.dll : fatal error LNK1120: 2 unresolved externals
Target //mediapipe_api:mediapipe_desktop failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.211s, Critical Path: 5.61s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "D:\MediaPipeUnityPlugin-master\build.py", line 471, in <module>
    Argument().command().run()
  File "D:\MediaPipeUnityPlugin-master\build.py", line 143, in run
    self._run_command(self._build_desktop_commands())
  File "D:\MediaPipeUnityPlugin-master\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "D:\python\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH="D://MediaPipeUnityPlugin-master//env//Scripts//python.exe" --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --define MEDIAPIPE_DISABLE_GPU=1 --@opencv//:switch=local //mediapipe_api:mediapipe_desktop' returned non-zero exit status 1.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation.
For now, you can download the source code with the built libraries from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.3), so you don't need to build them.

If you still want to build them for yourself (with your favorite options), please use the Package Workflow.
> You can also make use of [the Package Workflow](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/workflows/package.yml) on Github Actions after forking this repository.

**Comment by homuler** [comment]
mabye https://github.com/google/mediapipe/issues/4060#issuecomment-1416893825 is related.

**Comment by lsqnet79** [comment]
I'm using this links to install Mediapipe  https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10
Error 
after I paste python build.py build --desktop cpu -v
![error](https://user-images.githubusercontent.com/95261128/219942923-ba44c9d3-8f95-472a-97f7-5727a178134a.JPG)

**Comment by homuler** [comment]
> bazel does not currently work properly from paths **containing spaces**

@lsqnet79 Please read the error message.
Again, note that you don't need to build the plugin _on your local machine_ (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/849#issuecomment-1435435649).
