### ISSUE TITLE
MacOS_Standalone: Failed to read data for the AssetBundle 'mediapipe'.

### ISSUE THREAD

**Issue by tinatinaZ** [homuler/MediaPipeUnityPlugin#85]
Hi there, I went through the installation steps for MacOS.
The project runs nicely in the Unity Editor on my Mac, but on MacOS standalone, it cannot show camera texture and all the functions. The WebCamScreen is blank.
These errors are from the log file:

>WebCamTexture Graphics Format: B8G8R8A8_UNorm
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
<ResetScreen>d__16:MoveNext() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs:54)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/MonoBehaviour.bindings.cs:91)
SceneDirector:ResetCamera(Nullable`1) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:86)
SceneDirector:ChangeWebCamDevice(Nullable`1) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:75)
WebCamDeviceSelectorController:OnValueChanged(Dropdown) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/WebCamDeviceSelectorController.cs:62)
WebCamDeviceSelectorController:ResetOptions(WebCamDevice[]) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/WebCamDeviceSelectorController.cs:56)
<Start>d__2:MoveNext() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/WebCamDeviceSelectorController.cs:45)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
 
>(Filename: /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs Line: 54)

>Unable to open archive file: /Users/christina/Desktop/MediaPipeUnityPlugin/MediaPipeMac.app/Contents/Resources/Data/StreamingAssets/mediapipe
UnityEngine.AssetBundle:LoadFromFile_Internal(String, UInt32, UInt64)
UnityEngine.AssetBundle:LoadFromFile(String) (at /Users/bokken/buildslave/unity/build/Modules/AssetBundle/Managed/AssetBundle.bindings.cs:87)
Mediapipe.AssetBundleManager:LoadAssetBundle() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/SDK/Scripts/Util/AssetBundleManager.cs:68)
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/SDK/Scripts/Util/AssetBundleManager.cs:89)
AssetBundleLoader:PrepareAsset(String, String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/ResourceManager/AssetBundleLoader.cs:13)
DemoGraph:PrepareDependentAsset(String, String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:192)
DemoGraph:PrepareDependentAsset(String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:196)
FaceDetectionGraph:PrepareDependentAssets() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Graphs/FaceDetection/Scripts/FaceDetectionGraph.cs:44)
DemoGraph:Initialize() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:46)
<RunGraph>d__23:MoveNext() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:171)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

>[./Runtime/VirtualFileSystem/ArchiveFileSystem/ArchiveStorageReader.cpp line 584] 
(Filename: /Users/bokken/buildslave/unity/build/Modules/AssetBundle/Managed/AssetBundle.bindings.cs Line: 87)

>Failed to read data for the AssetBundle 'mediapipe'.
UnityEngine.AssetBundle:LoadFromFile_Internal(String, UInt32, UInt64)
UnityEngine.AssetBundle:LoadFromFile(String) (at /Users/bokken/buildslave/unity/build/Modules/AssetBundle/Managed/AssetBundle.bindings.cs:87)
Mediapipe.AssetBundleManager:LoadAssetBundle() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/SDK/Scripts/Util/AssetBundleManager.cs:68)
Mediapipe.AssetBundleManager:PrepareAsset(String, String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/SDK/Scripts/Util/AssetBundleManager.cs:89)
AssetBundleLoader:PrepareAsset(String, String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/ResourceManager/AssetBundleLoader.cs:13)
DemoGraph:PrepareDependentAsset(String, String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:192)
DemoGraph:PrepareDependentAsset(String, Boolean) (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:196)
FaceDetectionGraph:PrepareDependentAssets() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Graphs/FaceDetection/Scripts/FaceDetectionGraph.cs:44)
DemoGraph:Initialize() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:46)
<RunGraph>d__23:MoveNext() (at /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:171)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

>[./Modules/AssetBundle/Public/AssetBundleLoadFromAsyncOperation.cpp line 450] 
(Filename: /Users/bokken/buildslave/unity/build/Modules/AssetBundle/Managed/AssetBundle.bindings.cs Line: 87)

>NullReferenceException: Object reference not set to an instance of an object
  at Mediapipe.AssetBundleManager.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) [0x0001a] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/SDK/Scripts/Util/AssetBundleManager.cs:92 
  at AssetBundleLoader.PrepareAsset (System.String name, System.String uniqueKey, System.Boolean overwrite) [0x00001] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/ResourceManager/AssetBundleLoader.cs:13 
  at DemoGraph.PrepareDependentAsset (System.String assetName, System.String uniqueKey, System.Boolean overwrite) [0x00001] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:192 
  at DemoGraph.PrepareDependentAsset (System.String assetName, System.Boolean overwrite) [0x00001] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:196 
  at FaceDetectionGraph.PrepareDependentAssets () [0x00001] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Graphs/FaceDetection/Scripts/FaceDetectionGraph.cs:44 
  at DemoGraph.Initialize () [0x00001] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs:46 
  at SceneDirector+<RunGraph>d__23.MoveNext () [0x00148] in /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:171 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00020] in /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17 
 
>(Filename: /Users/christina/Desktop/MediaPipeUnityPlugin/Assets/MediaPipe/SDK/Scripts/Util/AssetBundleManager.cs Line: 92)

I take a look at the StreamingAssets\ , there is no mediapipe. 
Thanks for help in advance!

**Comment by homuler** [comment]
I wonder if your repository's HEAD is behind.
Will you pull the latest commit and try again, please?

**Comment by tinatinaZ** [comment]
> I wonder if your repository's HEAD is behind.
> Will you pull the latest commit and try again, please?
Yes it is up to date. But the problem still exist.
Do I suppose to see anything in the StreamingAssets folder after using "Build AssetBundles"? It is nothing there now.
Also, I checked the Asset Labels panel on my Unity Editor, there is no "mediapipe" or any other bundle label. Could it be the problem?

**Comment by homuler** [comment]
I see.
I guess there would be many diffs under `Assets/MediaPipe/SDK/Resources` if you run `git diff`.

If so, please checkout those files.

**Comment by tinatinaZ** [comment]
> I see.
> I guess there would be many diffs under `Assets/MediaPipe/SDK/Resources` if you run `git diff`.
> 
> If so, please checkout those files.

Yes, this works!!! Cheers and many thanks!!!!!
