### ISSUE TITLE
Cam problem by changing unity scenes

### ISSUE THREAD

**Issue by PaulDieterich** [homuler/MediaPipeUnityPlugin#850]
### Description

Hello,

I'm not sure where to report this. 
I'm using the Holistic solution in an university project and I'm quite new to Unity. 
So here is my go:

I have two scenes: A gameScene and a menuScene. 
I start the menuScene and press play, so that the gameScene gets loaded. The calibration starts (in the now loaded gameScene), I map the Mediapipe model on a player model and "play". After the game ends, I switch back to the menuScene. If i come back to the game scene (by clicking "play" again), I want to calibrate new. 
By doing this, I get the following error: 
![error1](https://cdn.discordapp.com/attachments/1067719860487983144/1074950725563588618/image.png)
After I removed the exception throws, I got this error:
![error2](https://cdn.discordapp.com/attachments/1067719860487983144/1074954742914101278/image.png)
I think the access for the webcam is still in use and after creating the new scene the reference is still there.
![code](https://cdn.discordapp.com/attachments/1067719860487983144/1074954629873414184/image.png)
Is there a way to be sure the camera is not occupied before the new  initialization?

**Comment by PaulDieterich** [comment]
I tests a bit, 
if i connect two cameras to the PC and change the Cams,back and forth, after the scene change.

**Comment by homuler** [comment]
> Is there a way to be sure the camera is not occupied before the new initialization?

Just stop the `WebCamTexture` before starting a new one (cf. [`OnDestroy`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnDestroy.html)).
