### ISSUE TITLE
cannot work on android phone

### ISSUE THREAD

**Issue by polaris7765** [homuler/MediaPipeUnityPlugin#853]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.10f1

### Your Host OS

Windows 11

### Target Platform

Android

### Target Device

HUAWEI PCT-AL10 5ENDU19410007232 [DISCONNECTED] 

### [Android Only] Android Build Tools and NDK Version

published from unity 2021.3.10f1

### Build Command

published from unity 2021.3.10f1， is this allowed?

### Bug Description

cannot works. but no crash.

### Steps to Reproduce the Bug

1. installed the apk in this android phone[published from unity directly].
2. run apk 
3. the app can run, no crash, but cannot do any motion capture.
4. logcat just have this problem.

### Log

![1](https://user-images.githubusercontent.com/86842244/219652484-b0aa70f3-e54f-413b-96c3-0ea7b1f64d33.jpg)

**Comment by homuler** [comment]
> installed the apk in this android phone[published from unity directly].

Where did you download the source code?

> logcat just have this problem.

Run `adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"` and share the result, please.

**Comment by lsqnet79** [comment]
I got the same issue as well no pose estimation tracking on a samsung galaxy S21
- I installed directly from the Mediapipe unity package v0.10.3.

**Comment by homuler** [comment]
@lsqnet79 See https://github.com/homuler/MediaPipeUnityPlugin/issues/681.

To use the plugin, it's OK to download the unitypackage, but if you want to build *the sample app*, I recommend you download `MediaPipeUnityPlugin-all.zip`.
