### ISSUE TITLE
Wear shoes with objectron/Sneaker

### ISSUE THREAD

**Issue by burungiu** [homuler/MediaPipeUnityPlugin#854]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.18f1

### Your Host OS

MacOS Latest

### Target Platform

Android, iOS

### Description

Hello, there is a way to wear a shoe over the bounding box with objectron?
I tried to place it into bounding box, but I don't know how to positionate, scale and rotate it right.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/10330202/219687741-b2082381-c40f-4ef0-82fb-11af1e38cba0.png">

**Comment by homuler** [comment]
closes since the objectron support has ended.
cf. https://github.com/google/mediapipe/blob/master/docs/solutions/objectron.md
