### ISSUE TITLE
connecting pose_world_landmarks to right/left_hand_landmarks

### ISSUE THREAD

**Issue by Dillxn** [homuler/MediaPipeUnityPlugin#857]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.18f1

### Your Host OS

Windows 10

### Target Platform

Windows Standalone, Android, iOS

### Description

I am parenting a 3d human model rig's constraints to MediaPipe landmark points. This works for the purpose of puppeteering the model, but I'm finding that the hand landmarks are in an entirely different coordinate system from the pose landmarks. 

Is there any way I can get all of the landmarks (both hands and pose) in the same coordinate system?

**Comment by homuler** [comment]
At least, `pose_landmarks` (not `pose_world_landmarks`) uses the same coordinate system.
cf. https://google.github.io/mediapipe/solutions/holistic.html#pose_landmarks

If you want to map `hand_landmarks` in the world coordinate system, please ask the MediaPipe developers.

**Comment by Dillxn** [comment]
Thank you for your quick response. Am I correct in thinking that I cannot therefore puppet a full 3D rig of a human using the currently available landmark data (since pose_landmarks is 2D, essentially)?

**Comment by homuler** [comment]
> since pose_landmarks is 2D, essentially

Honestly, I'm not sure the `pose_world_landmarks` can predict the depth correctly in the first place.
If the only difference between `pose_landmarks` and `pose_world_landmarks` is the coordinate system, then there should be no difference in accuracy between `pose_landmarks` and `pose_world_landmarks`.
To get the correct information, please ask the MediaPipe developers.

By the way, if you prefer, maybe there's a way to get hand landmarks in the world coordinates (cf. https://github.com/google/mediapipe/issues/3491#issuecomment-1364434438).

**Comment by Dillxn** [comment]
I really appreciate your responses. I see in you closed [issue 360](https://github.com/homuler/MediaPipeUnityPlugin/issues/360). Would you please tell me how can I access `multi_hand_world_landmarks` via your plugin? I suspect this might solve my issue.
