### ISSUE TITLE
Connect handtracking with Arfoundation.

### ISSUE THREAD

**Issue by alessandro1441** [homuler/MediaPipeUnityPlugin#858]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2020.x

### Your Host OS

Windows 10

### Target Platform

Android, iOS

### Description

hi, how can i connect mediapipe with arfoundation to move objects with handtracking?.  Thank you.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/343

**Comment by alessandro1441** [comment]
Thanks You.

**Comment by pinak1999** [comment]
> Thanks You.

@alessandro1441  were you able to use AR Foundation with mediapipe?
