### ISSUE TITLE
Support the latest 52 blendshapes

### ISSUE THREAD

**Issue by GeorgeS2019** [homuler/MediaPipeUnityPlugin#862]
### Feature Description

The following commit provides the latest mediapipe 52 blendshapes
https://github.com/google/mediapipe/commit/ba10ae8410ce431f593c95986a230add675e5ccd

The geometry and coefficients are listed [here](https://github.com/google/mediapipe/issues/3421#issuecomment-1442150437)

With this new addition, this provides facial mocap for avatars that use the ARKit 52 blendshapes.

### Current Behaviour/State

Currently, Users who are using industry standards e.g. [Character Creator 3 ](https://character-creator.reallusion.com/)limit themselves only facial mocap apps from Apple App Store

**Comment by baronha** [comment]
Does @mediapipe js support ?

**Comment by GeorgeS2019** [comment]
@baronha  try this [repos](https://github.com/LingDong-/handpose-facemesh-demos)

**Comment by GeorgeS2019** [comment]
[[Feature Request] face_blendshapes.tflite](https://github.com/keijiro/FaceMeshBarracuda/issues/24)

**Comment by newnon** [comment]
#935 this PR add blendshape support
