### ISSUE TITLE
Unstable recognition Objectron Sneakers

### ISSUE THREAD

**Issue by burungiu** [homuler/MediaPipeUnityPlugin#865]
### Plugin Version or Commit ID

0.10.3

### Unity Version

2021.3.18f1

### Your Host OS

MacOS 12.6

### Target Platform

iOS

### Description

I try to implement a try-on application for shoes using Objectron with sneakers model. But I meet some errors of prediction for the sneaker position. I tried min confidence to 0.1-03 and min trackign 0.3-0.5 but it still returns wrong positions. I tried with multiple min confidence (0.4, 0.5, 0.8 ...) but it didn't solved the problem

Any suggestions?

https://user-images.githubusercontent.com/10330202/221908690-a480275f-ad1e-4f6e-807d-df2c563f9066.MP4

**Comment by nenenkosi** [comment]
.
