### ISSUE TITLE
HandLandmarks are not correctly mapped with AR Camera

### ISSUE THREAD

**Issue by pinak1999** [homuler/MediaPipeUnityPlugin#866]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.0f1

### Your Host OS

Windows 10

### Target Platform

Android, iOS

### Description

I have an AR camera and feeding the live feed ( IMAGE WIDTH: 640 IMAGE HEIGHT: 480) to mediapipe graph the output landmarks have some different position. I tried your annotations prefab and script but that doesn't even render anything on screen so i created 21 small Sphere. and used the 21 vectors x,y,z axis to just update the position for these Sphere. The output is the hand is being formed and tracked but at the top right corner somewhere and since it's AR camera i can find it but as soon as the hand coords update it's gone somewhere else again.

### Code to Reproduce the issue

```
for (int i = 0; i < handLandmarks[0].Landmark.Count; i++)
				{
				 
							hand[i].transform.position = new Vector3(handLandmarks[0].Landmark[i].X, handLandmarks[0].Landmark[i].Y, handLandmarks[0].Landmark[i].Z);
							Debug.Log("Mediapipe returned: " + handLandmarks[0].Landmark[i].X + " " + handLandmarks[0].Landmark[i].Y + " " + handLandmarks[0].Landmark[i].Z);
							Debug.Log("handpoint location " + hand[i].transform.position);
							hand[i].SetActive(true);
						
				}for (int i = 0; i < handLandmarks[0].Landmark.Count; i++)
				{
				 
							hand[i].transform.position = new Vector3(handLandmarks[0].Landmark[i].X, handLandmarks[0].Landmark[i].Y, handLandmarks[0].Landmark[i].Z);
							Debug.Log("Mediapipe returned: " + handLandmarks[0].Landmark[i].X + " " + handLandmarks[0].Landmark[i].Y + " " + handLandmarks[0].Landmark[i].Z);
							Debug.Log("handpoint location " + hand[i].transform.position);
							hand[i].SetActive(true);
						
				}```

### Additional Context

landmarks are : ``` { "landmark": [ { "x": 0.477978557, "y": 0.668863952, "z": 4.94096E-10 }, { "x": 0.450127423, "y": 0.634920359, "z": 0.01859781 }, { "x": 0.4011144, "y": 0.6147708, "z": 0.0244471822 }, { "x": 0.357254267, "y": 0.6122347, "z": 0.02788824 }, { "x": 0.332624078, "y": 0.6230995, "z": 0.03289756 }, { "x": 0.3757499, "y": 0.60431236, "z": -0.002649412 }, { "x": 0.323199272, "y": 0.6053482, "z": 0.009252947 }, { "x": 0.331897885, "y": 0.615685, "z": 0.0254958551 }, { "x": 0.3491085, "y": 0.6206934, "z": 0.0349519663 }, { "x": 0.3690185, "y": 0.6243121, "z": -0.0130901635 }, { "x": 0.323068351, "y": 0.6286866, "z": -0.00103493524 }, { "x": 0.334134847, "y": 0.6372638, "z": 0.01176348 }, { "x": 0.351346552, "y": 0.6400868, "z": 0.0184446387 }, { "x": 0.367140442, "y": 0.647397757, "z": -0.0189866424 }, { "x": 0.330169857, "y": 0.6525503, "z": -0.00360553362 }, { "x": 0.3426565, "y": 0.6581394, "z": 0.009416257 }, { "x": 0.361393452, "y": 0.6595913, "z": 0.0143546639 }```

**Comment by homuler** [comment]
Have you checked https://github.com/homuler/MediaPipeUnityPlugin/issues/780?

>  I tried your annotations prefab and script but that doesn't even render anything on screen

Maybe you're just using it wrong?

**Comment by pinak1999** [comment]
> Have you checked #780?

Yes, I did but in my case even the annotation prefab isn't drawing anything

**Comment by pinak1999** [comment]
As you can see even the code provided in #780 doesn't work for me.
![image](https://user-images.githubusercontent.com/117369879/223207097-7b10dcc6-bd09-4562-9171-687fc8fb3e6f.png)

```
_controller.DrawNow(handLandmarks); // to draw hands
```

**Comment by homuler** [comment]
Well, I'm not the author of the code, so I'm not sure if it works as it is.

I recommend
- you should make sure that ARFoundation works without running the `CalculatorGraph`.
- you should make sure that you're getting the landmark values (e.g. using `Debug.Log`).
- you should _not_ use the Sample app's `Main Canvas` prefab.
   - see https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#annotation

**Comment by pinnakkkk** [comment]
> Well, I'm not the author of the code, so I'm not sure if it works as it is.
> 
> I recommend
> 
> * you should make sure that ARFoundation works without running the `CalculatorGraph`.
> * you should make sure that you're getting the landmark values (e.g. using `Debug.Log`).
> * you should _not_ use the Sample app's `Main Canvas` prefab.
>   
>   * see https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#annotation

Here's what i understood so far, when using raw handlandmarks coords to create a hand in 3d space it's always top right and it's flipped (it can be fixed by rotating or flip the image) and since the output is normalized, when the AR camera moves in 3d space the coords are changed  hence they need to me mapped out considering AR camera as origin is my hypothesis correct?

**Comment by homuler** [comment]
I would appreciate it if you could put periods (`.`) in the correct position.

> it's always top right and it's flipped (it can be fixed by rotating or flip the image) 

Sorry, I don't get what you mean. Do you mean that the origin is top-right?

> when the AR camera moves in 3d space the coords are changed hence they need to me mapped out considering AR camera as origin

MediaPipe just receives the input image and it doesn't know if it's from AR camera or not.
All what you need to know is that the returned value is normalized in Image Coordinate System.
cf. https://google.github.io/mediapipe/solutions/hands.html#multi_hand_landmarks

See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks.
