### ISSUE TITLE
Question: New Release for Updated MediaPipe

### ISSUE THREAD

**Issue by M-Colley** [homuler/MediaPipeUnityPlugin#867]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.18f

### Your Host OS

Windows 11

### Target Platform

Windows Standalone

### Description

Hey, and thank you so much for this package!

I was wondering when the **next release** is planned? I understand that one can use their own workflow but for less tech-savvy people a new release with the update MediaPipe v 0.9.1 might be helpful. 

Again, thank you very much for your time!

Kind regards

**Comment by homuler** [comment]
I'd not decided yet, but there's nothing preventing it, so I'll release a new version this weekend.

P.S.
You can usually download the latest package from [the GitHub Actions page](https://github.com/homuler/MediaPipeUnityPlugin/actions/workflows/build-package.yml).
However, as you noted, you need to fork this repository to run the workflow with your favorite options.

**Comment by lsqnet79** [comment]
I got this errors  on the @bazel_tools//platforms.
![error](https://user-images.githubusercontent.com/95261128/222894790-05d00e59-7cf5-4d1f-a6b4-ca4de1a029d1.PNG)

**Comment by homuler** [comment]
I released [v0.11.0](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.11.0).
