### ISSUE TITLE
Constructing own graph using existing calculators

### ISSUE THREAD

**Issue by chris-the-wiz** [homuler/MediaPipeUnityPlugin#870]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.9f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor, Android

### Description

I try to create a trimmed down blend of pose and hands detection graphs. Came out with the code attached below and it works under windows in the editor perfectly. When I run it on android, the graph loaded from the text file throws the following errors:

```
"NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: PoseLandmarkCpu; Unable to find Calculator \"PoseLandmarkCpu\"
No registered object with name: HandLandmarkTrackingCpu; Unable to find Calculator \"HandLandmarkTrackingCpu\""
```
I kept the calculator names same as in examples which work on android. 
What is the reason for this?

### Code to Reproduce the issue

the graph code:

```
input_stream: "input_video"
input_side_packet: "num_hands" #hands


output_stream: "pose_landmarks"
output_stream: "pose_world_landmarks"

#hands

output_stream: "hand_world_landmarks"
output_stream: "handedness"
output_stream: "palm_detections"
output_stream: "hand_rects_from_palm_detections"



node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:pose_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "ROTATION_DEGREES:input_rotation"
  input_side_packet: "FLIP_HORIZONTALLY:input_horizontally_flipped"
  input_side_packet: "FLIP_VERTICALLY:input_vertically_flipped"
  output_stream: "IMAGE:transformed_input_video"
}

# Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkCpu"
  input_stream: "IMAGE:transformed_input_video"
  input_side_packet: "MODEL_COMPLEXITY:model_complexity"
  input_side_packet: "SMOOTH_LANDMARKS:smooth_landmarks"
  input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
  input_side_packet: "SMOOTH_SEGMENTATION:smooth_segmentation"
  output_stream: "LANDMARKS:pose_landmarks"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks"
 
}


node {
  calculator: "HandLandmarkTrackingCpu"
  input_stream: "IMAGE:transformed_input_video"
  input_side_packet: "MODEL_COMPLEXITY:model_complexity"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks" 
  output_stream: "HANDEDNESS:handedness" 
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
 
} #hands

```

**Comment by homuler** [comment]
For now, only CPU calculators are supported on Windows, and only GPU calculators are supported on Android.
https://github.com/homuler/MediaPipeUnityPlugin#android-ios

So you need to replace the `PoseLandmarkCpu` and `HandLandmarkTrackingCpu` calculators with the `PoseLandmarkGpu` and `HandLandmarkTrackingGpu` calculators.

The sample app switches the config at runtime as follows:
https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs#L45-L78

See also [pose_tracking_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/pose_tracking_cpu.txt) and [pose_tracking_opengles.txt](https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/pose_tracking_opengles.txt).

P.S.
I think we can run CPU calculators on Android in theory, but at least [the distributed libraries](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.11.0) are built with GPU enabled.
https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/mediapipe_api/BUILD#L407-L417

**Comment by chris-the-wiz** [comment]
Thanks. works now.
