### ISSUE TITLE
Set Android front camera as default at start

### ISSUE THREAD

**Issue by lsqnet79** [homuler/MediaPipeUnityPlugin#871]
### Feature Description

Hi sorry I also new to unity. 
Is there a way to pre start android phone front camera to start at the begining rather than the rear camera?

**Comment by onuralpszr** [comment]
For examples scenes  you can change [here](https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs#L139) "0" to "1" to make it front camera.

You can also do something like this so you can separate your desktop and mobile devices. 

#if (UNITY_ANDROID || UNITY_IOS)
        webCamDevice = availableSources[1];
#endif

#if UNITY_EDITOR
        webCamDevice = availableSources[0];
#endif

**Comment by lsqnet79** [comment]
Thank you it works well !
