### ISSUE TITLE
Official Solution example with Holistic instead of FaceMesh

### ISSUE THREAD

**Issue by JelleDeGeest** [homuler/MediaPipeUnityPlugin#872]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.18f1

### Your Host OS

Windows 10 Home

### Target Platform

UnityEditor

### Description

I am trying to edit the Official Solution example to show the landmarks ( pose_landmarks, left_hand_landmarks and right_hand_landmarks) of the Holistic Graph inside the console instead of the landmarks of the FaceMesh Graph.

I used the Holistic graph file from:
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipeUnity/Samples/Scenes/Holistic/holistic_cpu.tx
Where i only removed the inputs sidepacket lines (I found online that if you remove these, the standard values is used).

For the code i used the code from:
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks
Where i only changed the resources and the name of the landmark output stream

I verified my graph in the mediapipe tool and the code is very similar to the tutorial.
The unity error freezes and crashes without any information when i try to run the code so i have no clue where the error might be.

By doing some testing it seems to crash on the function on line 82:
posestream.TryGetNext(out var poseLandmarks)

Any suggestions or insights would be greatly appreciated!

### Code to Reproduce the issue

Graph:
[holistic_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10948565/holistic_cpu.txt)
Code:
[FaceMesh.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10948574/FaceMesh.txt)

**Comment by rajandeepsingh13** [comment]
Did you get this working? Trying to do the same?

**Comment by JelleDeGeest** [comment]
@rajandeepsingh13 yes i got it working. it something to do with a vector that was an array instead of just 1 vector or something like that.

**Comment by rajandeepsingh13** [comment]
> @rajandeepsingh13 yes i got it working. it had something to do with a vector that was an array instead of just 1 vector or something like that.

Would it be possible for you to share your script that you used to run holistic_cpu.txt? It would really help in understanding how the tutorial can be modified.
