### ISSUE TITLE
how to Render a 3D hand in world Space 

### ISSUE THREAD

**Issue by pinnakkkk** [homuler/MediaPipeUnityPlugin#873]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.18f

### Your Host OS

windows 10

### Target Platform

Android, iOS

### Description

I want to create a 3d hand in unity world space and track it considering the camera position. I do have some rough idea on how to do this but need some pointers. 

1. how can i convert these normalized values into real world coords? 
2. there is world hand landmarks as output can they be used? if so then how bcs i tired attach a proller but didnt work

**Comment by homuler** [comment]
maybe duplicates #857

**Comment by dclxviclangames** [comment]
> возможно дубликаты #857

could you help me with the example of Samples/Scenes/HandTracking to explain how I can get the position of hands in 3D space, I tried your tutorial from the wiki, I develop for Android, and nothing was displayed for me, although everything works on your demo scenes
