### ISSUE TITLE
Room Feature with transform position of world landmarks for Pose Tracking.

### ISSUE THREAD

**Issue by JaneshOhilo** [homuler/MediaPipeUnityPlugin#874]
### Feature Description

First of all, I really appreciate the effort you put into making this repository work.
I would like the Pose Model created in the Room to transform its position as I move across the room just like it does in the main canvas area.

### Current Behaviour/State

Currently the model is either anchored or hinged at a particular position in the room.
I implemented the room feature for MultiHandTracking, but am not able to figure out how to transform their postion.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/115792829/225218976-c4b53a72-efe8-4175-ab50-2d5943127ce1.gif)

### Additional Context

I feel the rotations are mapped but not the translation. Correct me if I am wrong.
Thanks.

**Comment by homuler** [comment]
> Currently the model is either anchored or hinged at a particular position in the room.

That's because the origin is at the center between hips.
If you want to translate the origin, you may want to refer to the `pose_landmarks`, too.

cf. https://google.github.io/mediapipe/solutions/pose.html#pose_world_landmarks
> `x`, `y` and `z`: Real-world 3D coordinates in meters with the origin at the center between hips.
