### ISSUE TITLE
Occlusion Based Solution

### ISSUE THREAD

**Issue by TKTSWalker** [homuler/MediaPipeUnityPlugin#877]
### Feature Description

Just saying that i'm working on an occlusion and monocular depth system i'll post for free, someone here has been trying to sell it through their email which doesn't quite sit right with me, especially if homuler who worked hard to get this in Unity isn't getting reimbursed! Expect an update in two to three weeks!

**Comment by 1101728133** [comment]
expectation

**Comment by TKTSWalker** [comment]
Sorry, I finished it but have been so busy with a project I decided to release it at once with my open source VR headset!

**Comment by 1101728133** [comment]
亲，您的来信可能不能及时看到，看到后必定第一时间回复！

**Comment by 1101728133** [comment]
亲，您的来信可能不能及时看到，看到后必定第一时间回复！
