### ISSUE TITLE
mediapipe sample scenes don't work on linux build with cpu 

### ISSUE THREAD

**Issue by Y0u-553f** [homuler/MediaPipeUnityPlugin#881]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.20f1

### Your Host OS

Windows 10 Home

### Target Platform

Linux Standalone

### Target Device

regular laptop with i5 7th gen and nvidia 940mx

### [Windows Only] Visual Studio C++ and Windows SDK Version

I didn't build any library , I am building from the com.github.homuler.mediapipe-0.11.0.tgz project.

### [Linux Only] GCC/G++ and GLIBC Version

ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### Build Command

I didn't build any library I am using 
com.github.homuler.mediapipe-0.11.0.tgz 

### Bug Description

when I use hand tracking solution sample scene on cpu it works on the unity editor and the windows build but it dosen't work on linux build . 

hand tracking solution sample scene on gpu work just fine btw.

### Steps to Reproduce the Bug

1/ Download the com.github.homuler.mediapipe-0.11.0.tgz 
2/open the unity project
3/open the handTracking solution sample scene 
4/set prefarable inference mode : cpu and Asset Load Type : Streaming Assets
5/Build For linux only the HandTracking solution.

### Log

here is the exception message on the developer console during runTime : 

HandTrackingSolution: MediaPipeException: Not_FOUND: ValidatedGraphConfig Initialization failed.
No regisrted object with name: HandLandmark TrackingCpu:Unable to find Calculator "HandLandmarkTrackingCpu" at MediaPipe.Status.AssertOk () [0x0000f] in
C:/Users/youss/OneDrive/Desktop/MediaPipeUnityPlugin-all/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Por/\Status.cs:147at mediapipe.Unity.GraphRunner<Initialize>d_39.MoveNext() [0x00091] in

**Comment by homuler** [comment]
This is because `libmediapipe_c.so` in the release package is built for GPU.
If you want to run it with GPU disabled, please build it by yourself.

cf. https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation

**Comment by homuler** [comment]
> if I use python build.py build --desktop gpu -vv will I build for both gpu and cpu ? or I have to make 2 seperate builds one for gpu and one for cpu ?

If you mean that you want to include both `HandLandmarkTrackingCpu` and `HandLandmarkTrackingGpu` in `libmediapipe_c.so`, you cannot do that just running `build.py`, and such a use case is not supported (so the answer to the latter question is yes).
I think you can do that in theory, but it's not easy since MediaPipe doesn't support that, too.

**Comment by Y0u-553f** [comment]
> > if I use python build.py build --desktop gpu -vv will I build for both gpu and cpu ? or I have to make 2 seperate builds one for gpu and one for cpu ?
> 
> If you mean that you want to include both `HandLandmarkTrackingCpu` and `HandLandmarkTrackingGpu` in `libmediapipe_c.so`, you cannot do that just running `build.py`, and such a use case is not supported (so the answer to the latter question is yes). I think you can do that in theory, but it's not easy since MediaPipe doesn't support that, too.

thanks a lot
