### ISSUE TITLE
Window's build does not work.

### ISSUE THREAD

**Issue by Afamuefuna** [homuler/MediaPipeUnityPlugin#886]
### Description

After downloading the MediaPipe Tarball package for Unity, I tried to build one of the samples, while it worked in the Unity editor, it didn't work on the build file for windows when I played the game, what am I missing, please?

I use windows 11

MediaPipe version is 0.10.3

Thanks.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/681#issuecomment-1200339913

**Comment by Afamuefuna** [comment]
Phew, thanks a lot, it works now, best asset I've seen in awhile btw
