### ISSUE TITLE
CPU build failed in Linux - Mediapipe docker 

### ISSUE THREAD

**Issue by Emad-Eldeen** [homuler/MediaPipeUnityPlugin#89]
I am trying to build the project again now with the exact same steps as in #62  (using Mediapipe Docker image), but I am getting the following error in make cpu
```
ERROR: /root/.cache/bazel/_bazel_root/de3c76406078cb2218dae867db59221a/external/com_google_mediapipe/mediapipe/calculators/tensor/BUILD:599:11: C++ compilation of rule '@com_google_mediapipe//mediapipe/calculators/tensor:image_to_tensor_converter_opencv' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:106:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
INFO: Elapsed time: 50.849s, Critical Path: 50.01s
INFO: 499 processes: 499 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Makefile:46: recipe for target 'cpu' failed
make: *** [cpu] Error 1
root@c09a74d83417:/MediaPipeUnityPlugin#
```
I also tried to install a standalone ubuntu and went throw all the steps and got the same error.
What do you think the problem is? could it be that something has changed since then?

**Comment by Emad-Eldeen** [comment]
It seems that the issue is from Mediapipe side with the latest update. [issue](https://github.com/google/mediapipe/issues/1733)
Is there a way to select an older version of Mediapipe ?

**Comment by homuler** [comment]
The versions of gcc and g++ in the container are too old (need to be >= 8).
You need to upgrade gcc/g++ or change base image to `ubuntu:20.04` (in the latter case, default OpenCV version is 4, so you may need to install OpenCV 3 manually).

> Is there a way to select an older version of Mediapipe ?

Simply `git checkout` an older commit that works.

**Comment by Emad-Eldeen** [comment]
Checking out Mediapipe to [v0.8.2](https://github.com/google/mediapipe/tree/0.8.2)
was not enough. I also had to checkout [v0.4.3](https://github.com/homuler/MediaPipeUnityPlugin/tree/v0.4.3) in your repo.
