### ISSUE TITLE
Unity Android apk Export Build Failure On FaceMesh Tutorial but works on Sample FaceMesh

### ISSUE THREAD

**Issue by sabrol12** [homuler/MediaPipeUnityPlugin#890]
### Plugin Version or Commit ID

v.0.10.3 and v.0.11.0

### Unity Version

2021.3.19f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

Hi, sorry if they may sound trivial but I'm a bit new to using Unity and Mediapipe. My end goal here is to simply export your tutorial unity scene as an android apk build. 

1.) I started by downloading your plugins ( I tried both the v.0.10.3, and v.0.11.0 ) .unitypackage. Imported into my Unity project by simply right clicking in my project, "Import Package" -> "Custom Package", selecting the package and successfully imports.

a.) First I tried the v.0.11.0, I was having issues exporting the regular sample FaceMesh scene provided under (Assets/MediaPipeUnity/Samples/Scenes/FaceMesh) as an android apk. I did this by simply going to 
"File" -> "Build Settings" ->"Build" ( after switching to android platform, confirming I have all SDK,NDK,JDK,GRADE's installed that were recommended by unity editor).

b.) Therefore I created a completely new project, downloaded the v.0.10.3 of the plugin, did the same exact thing in a.) and the build was successful ( using default player settings, just changed the Company Name and Version),  I was able to build an android apk file no problem for the (Assets/MediaPipeUnity/Samples/Scenes/FaceMesh).

c.) After sucessfully doing this, I wanted to do this for your tutorial. Following it step by step I got the tutorial working using cpu graph. **Now here lies the issue:** when I try to export this Tutorial scene as an android apk build, it fails to build with the following error:

"Assets\MediaPipeUnity\Tutorial\Official Solution\FaceMesh.cs(46,30): error CS0246: The type or namespace name 'LocalResourceManager' could not be found (are you missing a using directive or an assembly reference?) " in the console.
( I will attach picture of the all errors.)

I cannot understand what could be causing this issue as I know the LocalResourceManager is located in the Packages: (Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/LocalResourceManager.cs). 

**Errors in Console** 
![Errors_In_Console](https://user-images.githubusercontent.com/115596758/230528404-7242122b-39fb-4043-a7a1-4353ad7bbcca.jpg)

**All the installed external Tools with Unity**
![Installed_External_Tools_W_Unity](https://user-images.githubusercontent.com/115596758/230528380-bc6aa07e-aedd-4d64-9fb8-af8361315f48.jpg)

I would highly appreciate any help, comment or feedback you or anyone could please give regarding this issue, as I've been trying to solve this problem for days now with no luck, thus the reasoning I'm reaching out to here hopefully for some clarification.   
 

### Code to Reproduce the issue

The Code to reproduce this issue is simply the same exact code you provided in your tutorial for the cpu implementation, and just simply doing the "File" -> "Build Settings" ->"Build" for android in Unity Editor. 

### Additional Context

I would like to now just take the time and thank you (and all others who contributed) for building this plugin for unity, I really hope to hear back from you (or someone else) soon, if possible. Again, I do apologize if this is something trivial or if it is something that may already have been discussed before.

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#load-model-files.

> For testing purposes, the `LocalResourceManager` class is sufficient.
>
> ```cs
> var resourceManager = new LocalResourceManager();
> yield return resourceManager.PrepareAssetAsync("dependent_asset_name");
> ```
> 
> In development / production, you can choose either `StreamingAssetResourceManager` or `AssetBundleResourceManager`.
For example, `StreamingAssetResourceManager` will load model files from [`Application.streamingAssetsPath`](https://docs.unity3d.com/Manual/StreamingAssets.html).

`LocalResourceManager` is available only on UnityEditor, so use `StreamingAssetResourceManager` instead.
https://github.com/homuler/MediaPipeUnityPlugin/blob/7c43b75f693d5f3a63056848f0a66e861d908809/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/LocalResourceManager.cs#L7

**Comment by sabrol12** [comment]
Hey, thank you very much for responding, that actually worked and sorry for that simple mistake. But now I am facing another issue with actually getting the face mesh to work using that apk file. As per the instructions, when I place all the dependent assets for the face mesh under Assets/StreamingAssets it works fine in unity. 

But when I actually export the apk file, there is no face tracking happening on the android device. I think this may be due to me only exporting the Official Solution scene, and since the StreamingAssets folder is outside of that it does not do face tracking, I could be 100% wrong here. I tried to simply add the StreamingAssets folder containing the assets into the scene itself but that does not work either, giving the following error: 

**Error**
![E1](https://user-images.githubusercontent.com/115596758/230658441-a63cea8d-8ef3-4b8c-b7a3-862602ad4bc9.jpg)

With the StreamingAssets under /Tutorial/Offical Solution/StreamingAssets
**What Causes Error**
![Causes_Error](https://user-images.githubusercontent.com/115596758/230658421-6ab21650-32d4-4636-aef1-0cbd2fcf774a.jpg)

With the SteamingAssets under Assets/StreamingAssets, working fine in unity, not in android.
**Works Fine In Unity But Not in the Android Device after exporting the apk build.**
![Works_Fine_In_Unity_Not_Android](https://user-images.githubusercontent.com/115596758/230658575-f47b4e2a-9afe-4015-b13c-3be7a2536edf.jpg)



Do you have any suggestions as to how I could go about resolving this issue? Again I cannot express my appreciation for your help in words. I would highly appreciate any help, thank you.

**Comment by homuler** [comment]
Please read the log (run `adb -s [device_id] logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`) first.
I'm not sure, but it may be the same issue as https://github.com/homuler/MediaPipeUnityPlugin/issues/870#issuecomment-1458076895.

If you want, pass your custom path to `StreamingAssetResourceManager`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/7c43b75f693d5f3a63056848f0a66e861d908809/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/StreamingAssetsResourceManager.cs#L22

**Comment by sabrol12** [comment]
Hey, again thank you very much for your response and again I cannot express my gratitude enough. I ran the command you recommended, and just as you said, I do believe it is related to the other issue, where android does not supposed the cpu graph? This was the result of the log:

```
04-07 23:24:38.932 15509 15550 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
04-07 23:24:38.952 15509 15550 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 7461mb
04-07 23:24:38.952 15509 15550 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
04-07 23:24:38.952 15509 15550 I Unity   : ApplicationInfo com.testOffical.FaceMeshTest2 version 1.0.4
04-07 23:24:38.952 15509 15550 I Unity   : Built from '2021.3/staging' branch, Version '2021.3.19f1 (c9714fde33b6)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
04-07 23:24:39.041 15509 15550 I Unity   : Company Name: testOffical
04-07 23:24:39.041 15509 15550 I Unity   : Product Name: FaceMeshTest
04-07 23:24:46.059 15509 15509 W Unity   : Timeout while trying to pause the Unity Engine.
04-07 23:24:47.180 15509 15550 E native  : E20230407 23:24:47.180203 15550 calculator_graph.cc:25] Aborted
04-07 23:24:47.215 15509 15550 E Unity   : MediaPipeException: MediaPipe Aborted, refer glog files for more details
04-07 23:24:47.215 15509 15550 E Unity   :   at Mediapipe.MpReturnCodeExtension.Assert (Mediapipe.MpReturnCode code) [0x0002f] in <86527154d3604c868e7ecbff761774a9>:0
04-07 23:24:47.215 15509 15550 E Unity   :   at Mediapipe.CalculatorGraph..ctor (System.Byte[] serializedConfig) [0x00012] in <86527154d3604c868e7ecbff761774a9>:0
04-07 23:24:47.215 15509 15550 E Unity   :   at Mediapipe.CalculatorGraph..ctor (Mediapipe.CalculatorGraphConfig config) [0x00007] in <86527154d3604c868e7ecbff761774a9>:0
04-07 23:24:47.215 15509 15550 E Unity   :   at Mediapipe.CalculatorGraph..ctor (System.String textFormatConfig) [0x0000c] in <86527154d3604c868e7ecbff761774a9>:0
04-07 23:24:47.215 15509 15550 E Unity   :   at Mediapipe.Unity.Tutorial.FaceMesh+<Start>d__10.MoveNext () [0x0017b] in <445dab2da46f48f1883bc155a8758a71>:0
04-07 23:24:47.215 15509 15550 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <097b93cc61694b088c43861955e64b81>:0 
```

Currently I am trying to get the gpu graph working on the unity editor as per your tutorial. Although I am a bit confused, as in your issue #870 comment you pointed me to, you mention "For now, only CPU calculators are supported on Windows, and only GPU calculators are supported on Android.", so I'm a bit confused as to whether the gpu graphs will work on the Windows Unity Editor (I think it should right? Due to your tutorial and other issues using Windows 10 w/ Unity Editor to build the gpu graphs?).

On mac I know it is simple to build the libraries with gpu enabled/disabled ( I tried it, but my mac is too old for this work ). But I do not know how I would go about doing this on Windows, I would highly appreciate any kind of guidance you could provide regarding this matter, even though it may be trivial. I simply cannot thank you enough for all your help thus far. 


PS: If the gpu graphs are able to work properly for android, I should not need to worry about passing my custom path to StreamingAssetResourceManager correct? Or would that "Failed to load ____.bytes: HTTP/1.1 404 Not Found" error in the previous comment still occur? (I ask this because even with passing my own custom path into the public StreamingAssetsResourceManager(string path), it still gave me the same error when the StreamingAssets folder is inside or outside the Tutorial/Offical Solution scene).

**Comment by homuler** [comment]
> MediaPipeException: MediaPipe Aborted, refer glog files for more details

See https://github.com/homuler/MediaPipeUnityPlugin/issues/645#issuecomment-1179986503.

> so I'm a bit confused as to whether the gpu graphs will work on the Windows Unity Editor

`*Gpu` calculators do not work on Windows. On the other hand, `*Cpu` graphs won't work on Android.
If you want to run your graph on both, you need to switch your config depending on the platform.

> On mac I know it is simple to build the libraries with gpu enabled/disabled

Certainly, you can build it with GPU enabled, but unfortunately, it's not so simple.

> I should not need to worry about passing my custom path to StreamingAssetResourceManager correct?

Always read the log and check which path it is trying to read (and failed). I strongly recommend you place `StreamingAssets` forlder directly under `Assets` first.
Note that you need to build the app with Development build checked to read the log.

**Comment by sabrol12** [comment]
Hey got it working, thank you very much for your help again I cannot express my gratitude in words. Thank you for the plugin, people like you make this world great! Thank you so much.

**Comment by homuler** [comment]
The method for displaying the input image in the correct orientation is more related to how to use Unity than this project itself, so please ask on the Unity forum for this topic.
