### ISSUE TITLE
Pose Tracking Works With Very Low FPS

### ISSUE THREAD

**Issue by karahanoguzhan** [homuler/MediaPipeUnityPlugin#891]
### Plugin Version or Commit ID

7c43b75f693d5f3a63056848f0a66e861d908809

### Unity Version

2021.3.18f1

### Your Host OS

macOS Monterey 12.6

### Target Platform

Android

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.3
NDK: 21.4.7075529

### Build Command

python build.py build --android fat --android_ndk_api_level 21 --solutions pose --linkopt=-s -vv

### Bug Description

I was building the plugin with 0.8.11 mediapipe for arm64 only, and was not specifying `--android_ndk_api_level 21`. Pose tracking was normally working with this build command, around 30 fps. 
But some time later, it turns out i need build for arm7 also, so I have built the plugin with 0.9.1 mediapipe with `--android fat` option. After that, `Unable to load DLL 'mediapipe_jni'` error arised and I rebuilt it with `--android_ndk_api_level 21` option. With this build, the error is gone. But another bug came out, Pose tracking is not working properly. Now it is running around 5-10 fps, and it is not accurate very well. On logcat, no errors was showing, what can I do to fix this?

### Steps to Reproduce the Bug

Run `python build.py build --android fat --android_ndk_api_level 21 --solutions pose --linkopt=-s -vv`
Build for Android
Try Pose Tracking and bug occurs.

### Log

No error logs.

**Comment by homuler** [comment]
> But another bug came out

Can you tell me why you thought this issue was a bug? For example, have you confirmed that there is no difference in performance when building the official MediaPipe sample app for armv7 in a similar way?

**Comment by karahanoguzhan** [comment]
@homuler could you help me please? Do you have any idea about what could be wrong?

**Comment by homuler** [comment]
It's similar to https://github.com/homuler/MediaPipeUnityPlugin/issues/879.

You said there was no issue with the sample app, and since I don't know anything about your app, I can't answer what the cause might be.
