### ISSUE TITLE
Different output of OnPoseWorldLandmarksOutput for Pose tracking scene and Holistic scene.

### ISSUE THREAD

**Issue by 3Bridge123** [homuler/MediaPipeUnityPlugin#892]
### Plugin Version or Commit ID

v0.10.3

### Unity Version

2021.3.18f1

### Your Host OS

Windows 10

### Target Platform

UnityEditor

### Description

I ran the game on the same image with Bootstrap's Default image source set to Image in both the Pose tracking and Holistic Scenes.
When I checked the value of eventArgs.value in OnPoseWorldLandmarksOutput of HolisticTrackingSolution.cs and PoseTrackingSolution.cs in debug mode, I found that the value of landmarks was significantly different.
Even if the scene is different, if the image is the same, the result of Pose tracking should be almost the same, right?

**Comment by homuler** [comment]
Please ask the MediaPipe developers. If you're sure that Pose and Holistic should return similar output, please add a note about it.
