### ISSUE TITLE
Get Point Data

### ISSUE THREAD

**Issue by TKTSWalker** [homuler/MediaPipeUnityPlugin#893]
### Plugin Version or Commit ID

0.11.0

### Unity Version

2021.3.8f1

### Your Host OS

Windows OS

### Target Platform

Windows Standalone

### Description

I am trying to get a list of points from the Instant Motion Tracking solution to make SLAM work better, how would I get the list? Also how would you connect an IMU into the code for the IMT solution?

**Comment by homuler** [comment]
Have you read [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial)?

> Also how would you connect an IMU into the code for the IMT solution?

Mediapipe's Instant Motion Tracking essentially only performs region tracking. Therefore, it may be better to consider incorporating the results of region tracking into your application.
