### ISSUE TITLE
Question: Upgrade to MediaPipe 0.10.0

### ISSUE THREAD

**Issue by M-Colley** [homuler/MediaPipeUnityPlugin#896]
### Feature Description

Hello, thank you so much for your hard work - I really appreciate it and know how much work this is. 

I was wondering whether there are plans to upgrade to MediaPipe 0.10.0 (https://github.com/google/mediapipe/releases/tag/v0.10.0) soon? This does seem like a major upgrade (as indicated by the developers themselves).

Thank you!

Kind regards

**Comment by homuler** [comment]
I will do when I feel inclined to do so (maybe in May). However, implementing a sample of the new feature may take some time.

**Comment by GeorgeS2019** [comment]
@homuler 
The Mediapipe.NET need your upgrade :-)

**Comment by M-Colley** [comment]
It nos is actually 0.10.0 :) 

https://github.com/google/mediapipe/releases/tag/v0.10.0

**Comment by GeorgeS2019** [comment]
@homuler  Hopefully U are on schedule for a late May/early June release.  We all depend on you

**Comment by cdiddy77** [comment]
@homuler I would love to help with moving to 0.10.0 if there is anything I can do. We are really wanting to get the new landmarks tracking into our app.

**Comment by GeorgeS2019** [comment]
@homuler  => great job!

**Comment by cdiddy77** [comment]
so much yay!
