### ISSUE TITLE
Visualize X,Y,Z -- utilizing and/or modifiying the values 

### ISSUE THREAD

**Issue by sbahrami-vz** [homuler/MediaPipeUnityPlugin#899]
### Plugin Version or Commit ID

0.10.0

### Unity Version

2021.3.21

### Your Host OS

Windows 11

### Target Platform

Android, iOS

### Description

Hi @homuler 
I'm trying to get the values of X,Y,Z of the landmarks when I enable the Z visualization on hands, the weird thing is the head is always attached to the center of the render canvas (segmented person), and when for example the hands are toward the camera they got extended too much in 3D space, is there a way I can utilize and balance the visualization parameters (values) to e.g. limit the extension. and is there a way to have a not flickery landmarks?

Thanks

**Comment by homuler** [comment]
Since I'm not sure what you mean, could you please explain using a screenshot?
Anyway, please check the definition of the value in [the MediaPipe official documentation](https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md#pose_landmarks) first.
