### ISSUE TITLE
Running examples in unity gives error

### ISSUE THREAD

**Issue by ashrvstv** [homuler/MediapipeUnityPlugin#9]
Getting error while running example

```
DllNotFoundException: mediapipe_c
Director.OnDisable () (at Assets/Mediapipe/Examples/Scripts/Director.cs:35)
```
![Screenshot from 2020-09-21 23-37-15](https://user-images.githubusercontent.com/70220871/93804401-dee91300-fc63-11ea-87b1-7cd866165d31.png)

**Steps to reproduce**

step 1- git clone MediapipeUnityPlugin
step 2 - open in unity
step 3 - run HandTrackingGPU scene

**Comment by homuler** [comment]
You need to identify what causes the DllNotFoundException.
Will you try checking (or unchecking) **Load on startup** in **Plugin load settings** section?

![Screenshot_20200922_084819](https://user-images.githubusercontent.com/4690128/93832381-84c26f00-fcb0-11ea-8fdb-dfe5d33ccdf6.png)

**Comment by ashrvstv** [comment]
@homuler i think it is not even present at the path Assets/Mediapipe/SDK/Plugins/
![Screenshot from 2020-09-22 15-03-20](https://user-images.githubusercontent.com/70220871/93866153-ec92ad00-fce4-11ea-9f9e-18dc261e6c7c.png)

**Comment by homuler** [comment]
Well, it surely exists in the above screenshot. `libmediapipe_c.so` is that.

**Comment by ashrvstv** [comment]
Yeah, my bad. 

> Will you try checking (or unchecking) Load on startup in Plugin load settings section?

I tried this. its not working in either case. 

**On enabling**
![Screenshot from 2020-09-22 18-19-56](https://user-images.githubusercontent.com/70220871/93884844-0d68fb80-fd01-11ea-8086-46c7e689d553.png)

**On disabling**
![Screenshot from 2020-09-22 18-20-59](https://user-images.githubusercontent.com/70220871/93884941-2a053380-fd01-11ea-9e2f-3670a054960c.png)

![Screenshot from 2020-09-22 18-21-07](https://user-images.githubusercontent.com/70220871/93884958-2ffb1480-fd01-11ea-9982-d696a296720f.png)

![Screenshot from 2020-09-22 18-21-17](https://user-images.githubusercontent.com/70220871/93884987-37bab900-fd01-11ea-89f6-2b29feeb9890.png)

**Comment by homuler** [comment]
OK. Please check `Load on startup` and click `Apply` button, and restart Unity Editor.
I expect some warning logs will show up in the console when Unity Editor starts.
![Screenshot_20200922_221449](https://user-images.githubusercontent.com/4690128/93887123-3f8a5580-fd21-11ea-8c53-5e47456f0087.png)

By the way, if you use Debian or Ubuntu, and your OpenCV's shared object files are installed under `/usr/lib/x86_64-linux-gnu/`, then you may need to edit [opencv_linux.BUILD](https://github.com/homuler/MediapipeUnityPlugin/blob/master/C/third_party/opencv_linux.BUILD). (cf. https://github.com/homuler/MediapipeUnityPlugin#opencv)

**Comment by ashrvstv** [comment]
> if you use Debian or Ubuntu, and your OpenCV's shared object files are installed under /usr/lib/x86_64-linux-gnu/

I have modified opencv_linux.BUILD

![Screenshot from 2020-09-22 22-42-02](https://user-images.githubusercontent.com/70220871/93917315-76179e80-fd28-11ea-96bb-9aa3bc941b22.png)

**Comment by ashrvstv** [comment]
But same problem is here, 


> I expect some warning logs will show up in the console when Unity Editor starts.

Yeah right


![Screenshot from 2020-09-22 23-04-43](https://user-images.githubusercontent.com/70220871/93917551-c3940b80-fd28-11ea-965a-b153ca8a01e3.png)

on disabling the setting there is no warning at start
![Screenshot from 2020-09-22 23-05-29](https://user-images.githubusercontent.com/70220871/93917717-f6d69a80-fd28-11ea-85c1-1dc2282fa453.png)

but showing same error at runtime
![Screenshot from 2020-09-22 23-05-57](https://user-images.githubusercontent.com/70220871/93917760-048c2000-fd29-11ea-8f61-d21298267759.png)

**Comment by homuler** [comment]
https://github.com/homuler/MediapipeUnityPlugin/issues/2#issuecomment-689501672 may be relevant.

> But same problem is here,
> > I expect some warning logs will show up in the console when Unity Editor starts.

Please copy and paste that warning log in **text**.
I know it continues to fail, I'd like to know why it fails.

> I have modified opencv_linux.BUILD

After editing, did you run `make`, `make install` and restart Unity Editor?
This file is not read at runtime. If it is not correct at build time, OpenCV will not be linked statically.

**Comment by ashrvstv** [comment]
> After editing, did you run make, make install and restart Unity Editor?

@homuler it worked after i run` make` and `make install `command and restart unity.

**Comment by ashrvstv** [comment]
@homuler it is running on Unity but when i am trying to build android apk file. it is giving errors

`Assets/Mediapipe/Examples/Scripts/Director.cs(7,31): error CS0234: The type or namespace name 'Windows' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)`

`Error building Player because scripts had compiler errors`

```
Build completed with a result of 'Failed' in 6 seconds (6063 ms)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)
```

```
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002af] in /home/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:194 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /home/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:95 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

```
![Screenshot from 2020-09-23 12-31-54](https://user-images.githubusercontent.com/70220871/93978413-992e6680-fd99-11ea-8aa7-4d648cec484e.png)

**Comment by homuler** [comment]
I'm planning to support Android, but currently Linux Desktop is the only supported platform (this error may be not relevant though).
https://github.com/homuler/MediapipeUnityPlugin/issues/3

**Comment by ashrvstv** [comment]
okay @homuler ,  waiting for android support, btw, thanks for your help.
