### ISSUE TITLE
Unity Project - Android   doesnt work

### ISSUE THREAD

**Issue by AlanWuJinliang** [homuler/MediaPipeUnityPlugin#90]
@homuler   TThank you very much for your help，
now i already build Android and ios Succeed in mac os .
and the ios is can run in the iphone.
but when i change to Android ,it show a error:

`Assets/MediaPipe/Examples/Scripts/SceneDirector.cs(53,39): error CS0103: The name 'GetCurrentContext' does not exist in the current context
`
 
`here is the code`

#if UNITY_ANDROID
    if (IsGpuEnabled()) {
      PluginCallback callback = GetCurrentContext;
      var fp = Marshal.GetFunctionPointerForDelegate(callback);
      GL.IssuePluginEvent(fp, 1);
    }
#endif

**Comment by AlanWuJinliang** [comment]
when i Commented code  and run in Android phone,
show log:
`MediapipeException:MediaPipe Aborted,refer glog files for more details`

**Comment by SachinGanesh** [comment]
@AlanWuJinliang Were you able to solve the issue?

**Comment by SachinGanesh** [comment]
Okay. Android app works only if GPU option is selected

**Comment by AlanWuJinliang** [comment]
Yeah,now it  run succeed.
