### ISSUE TITLE
Camera not open in Android app 

### ISSUE THREAD

**Issue by tarekmostafa12** [homuler/MediaPipeUnityPlugin#907]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.22f1

### Your Host OS

Windows 11 

### Target Platform

Android

### Target Device

Redmi Note 8 pro

### Build Command

i only make build android from Build Settings

### Bug Description

this apk shows only black screen

### Steps to Reproduce the Bug

I imported MediaPipeUnity.0.11.0.unitypackage , change Asset Loader Type to Streaming Assets and make an apk .

### Log

no logs appear in apk

### Screenshot/Video

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/134814899/f4922811-ff21-4454-b8d6-5b7b64b032a2)

**Comment by AlexiaAnn** [comment]
I have encountered the same issue,Did you manage to solve the problem?

**Comment by tarekmostafa12** [comment]
i made this but no landmarks appears 
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/134814899/3bf1e959-fd20-4a02-8f8d-1ca9a6bbe81b)

**Comment by LGuilhermeRodrigues** [comment]
Before the build, I copied some resources from packages/homuler/packageresources/mediapipe to the streaming assets folder

**Comment by tarekmostafa12** [comment]
i made it but no landmarks

**Comment by LGuilhermeRodrigues** [comment]
For me, the problem of showing the camera frame but without the drawings resolved when I changed to GPU. But maybe there are other problems like arm architecture in the unity build settings

**Comment by tarekmostafa12** [comment]
can you help me please? i tried a lot but no landmarks in android

**Comment by homuler** [comment]
Please try building an apk using `MediaPipeUnityPlugin-all.zip` first.

> no logs appear in apk

Please build it with `Development Build` enabled.
