### ISSUE TITLE
Build error concerning python

### ISSUE THREAD

**Issue by stzogas** [homuler/MediaPipeUnityPlugin#908]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.25f1

### Your Host OS

Windows 11

### Target Platform

UnityEditor

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++ : 14.29.30133 
Windows SDK : 10.0.19041.0

### Command Sequences

set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
set BAZEL_VC_FULL_VERSION=14.29.30133 
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0
set PYTHON_BIN_PATH=C:\Python\python.exe
python build.py build --desktop cpu --include_opencv_libs -v

### Log

[Log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/11593549/Log.txt)

### Additional Context

ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/_bzl/vh7gku2x/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/vh7gku2x/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/vh7gku2x/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Python//python.exe' is not executable. Is it the python binary?
ERROR: C:/users/stzog/desktop/unity/unity_3d/mediapipeunityplugin-all/WORKSPACE:476:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/_bzl/vh7gku2x/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/_bzl/vh7gku2x/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/_bzl/vh7gku2x/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Python//python.exe' is not executable. Is it the python binary?
INFO: Repository yarn instantiated at:
  C:/users/stzog/desktop/unity/unity_3d/mediapipeunityplugin-all/WORKSPACE:510:18: in <toplevel>
  C:/_bzl/vh7gku2x/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:44:22: in node_repositories
Repository rule yarn_repositories defined at:
  C:/_bzl/vh7gku2x/external/rules_nodejs/nodejs/yarn_repositories.bzl:177:36: in <toplevel>
INFO: Repository bazel_rules_dict instantiated at:
  C:/users/stzog/desktop/unity/unity_3d/mediapipeunityplugin-all/WORKSPACE:75:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/vh7gku2x/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_google_protobuf instantiated at:
  C:/users/stzog/desktop/unity/unity_3d/mediapipeunityplugin-all/WORKSPACE:172:13: in <toplevel>
Repository rule http_archive defined at:
  C:/_bzl/vh7gku2x/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Python//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 1.493s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_mediapipe//mediapipe/calculators/audio ... (23 packages)
    Fetching @npm; Restarting.
    Fetching https://github.com/yarnpkg/yarn/releases/download/v1.22.11/yarn-v1.22.11.tar.gz
    Fetching https://github.com/protocolbuffers/protobuf/archive/v3.19.1.tar.gz
Traceback (most recent call last):
  File "C:\Users\stzog\Desktop\Unity\Unity_3D\MediaPipeUnityPlugin-all\build.py", line 478, in <module>
    Argument().command().run()
  File "C:\Users\stzog\Desktop\Unity\Unity_3D\MediaPipeUnityPlugin-all\build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "C:\Users\stzog\Desktop\Unity\Unity_3D\MediaPipeUnityPlugin-all\build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "C:\Python\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Python//python.exe --action_env ProgramData --action_env PROCESSOR_ARCHITECTURE --action_env PROCESSOR_IDENTIFIER --action_env PROCESSOR_LEVEL --action_env PROCESSOR_REVISION --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

**Comment by stzogas** [comment]
Any help please...???

**Comment by homuler** [comment]
Please read [the README](https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation).

> You can download them from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases) instead.

So you don't need to build the plugin by yourself.
