### ISSUE TITLE
Unable to support TensorFlow Lite Task Library model?

### ISSUE THREAD

**Issue by psiydown** [homuler/MediaPipeUnityPlugin#909]
@homuler Hope to enhance support for Mediapipe latest "pose_ landmarker.task", ["face_ landmarker.task"](https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task), "hand_ Landmarker.task" model.

After decompressing 'face_ landmarker.task' there are three model files. How do use 'face_blendshapes.tflite' to get blendshapes in Unity?

**Comment by onuralpszr** [comment]
This is related to this https://github.com/homuler/MediaPipeUnityPlugin/issues/896

Project needs a lot of changes before even talk about these changes, it is not just ".task" files it is also about proto to flatbuffers and change major cpp parts make compatible with unity then needs to make changes about patches has been included in bazel part (https://github.com/homuler/MediaPipeUnityPlugin/tree/master/third_party) as well.

**Comment by newnon** [comment]
Face blendshape support #935
