### ISSUE TITLE
Pass YUV (YCbCr) texture buffers data or a RenderTexture to create an ImageFrame

### ISSUE THREAD

**Issue by ABazL** [homuler/MediaPipeUnityPlugin#910]
### Plugin Version or Commit ID

0.10.3

### Unity Version

2021.3.9f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

Hello,

I'm actually trying to find a solution to pass a buffer data from a YCbCr texture out of an Android native library (AIMAGE_FORMAT_YUV_420_888 format exactly) to one of the constructor of ImageFrame class.

For now we are using those buffers data (one per plane Y/U/V) only for rendering through a Unity RenderTexture and YUV to RGB conversion is done through a shader.

According what we can deliever either Y/U/V buffers data separately or a RenderTexture, is it possible to create an ImageFrame ?
Idea is to avoid GetPixels/SetPixels operations because they are too costly in terms of performance.

Thanks!

### Additional Context

I saw that there was two ImageFrame definitions that could be interesting for us:

**1. First interesting ImageFrame definition**

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/3b64b909-2bc5-454b-8e21-f244c1232a82)

Example:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/5c5c55bd-3b09-4f51-af57-81744878dee3)

By trying to use this ImageFrame definition, I have a question:
How the buffer data is supposed to be architectured for a Ycbcr420p format before being passed to the ImageFrame ? (YYYYUVUV / YYYYUUVV / etc)
As you can see, I've only passed here the Y buffer but it will be not enough.

**2. Second interesting ImageFrame definition**

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/dced0f26-2f5b-4d14-a597-6907304041c1)

Example:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/1ff08921-08ea-421a-bb6f-f4fa41ed7c1d)

Does something like the above example should work ? 
Could the "pixelData" property required as IntPtr in the definition be filled by a RenderTexture.GetNativeTexturePtr() ?
I didn't found much informations about the Deleter delegate, is this a callback trigger once the ImageFrame object is destroyed/released ?

Do you see another solution to create an ImageFrame with either Y/U/V buffers data or a Unity RenderTexture ?

Thanks!

**Comment by homuler** [comment]
Sorry for the late reply.

> is it possible to create an ImageFrame ?

I think it's possible, but the support for YCbCr is limited and not useful in most cases (see https://github.com/homuler/MediaPipeUnityPlugin/issues/832).
