### ISSUE TITLE
FaceMeshSolution: Mediapipe.MediaPipeException: FAILED_PRECONDITION

### ISSUE THREAD

**Issue by KiranJodhani** [homuler/MediaPipeUnityPlugin#911]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.6

### Your Host OS

Mac OS - Intel

### Target Platform

UnityEditor

### Command Sequences

Imported plugin as per the steps. Some scene works well but some(Especially Face Detection and Face Mesh)  are not 
It gives error on start

### Log

From Face mesh sample scene

FaceMeshSolution: Mediapipe.MediaPipeException: FAILED_PRECONDITION: System.NullReferenceException: Object reference not set to an instance of an object
  at Mediapipe.Unity.FaceMesh.FaceMeshGraph.ConfigureCalculatorGraph (Mediapipe.CalculatorGraphConfig config) [0x001d2] in /MediaPipeUnityPlugin/Assets/MediaPipeUnity/Samples/Scenes/Face Mesh/FaceMeshGraph.cs:147

**Comment by homuler** [comment]
Please attach the complete log.
I think the logs you provided are related to the events resulting from the issue, rather than indicating the cause.
