### ISSUE TITLE
Mac build error

### ISSUE THREAD

**Issue by MoneyWonders** [homuler/MediaPipeUnityPlugin#914]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.13f1

### Your Host OS

macOS Monterey 12.6.3

### Target Platform

Android

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.2
NDK: r21d which built into Unity

### [iOS Only] XCode Version

XCode 14.2

### Command Sequences

export JAVA_HOME=/Applications/Unity/Hub/Editor/2021.3.13f1/PlaybackEngines/AndroidPlayer/OpenJDK/
export ANDROID_HOME=/Applications/Unity/Hub/Editor/2021.3.13f1/PlaybackEngines/AndroidPlayer/SDK/
export ANDROID_NDK_HOME=/Applications/Unity/Hub/Editor/2021.3.13f1/PlaybackEngines/AndroidPlayer/NDK/
python build.py build --android arm64 --linkopt=-s -vv

### Log

WARNING: Download from https://nodejs.org/dist/v16.15.0/node-v16.15.0-darwin-x64.tar.gz failed: class java.io.IOException GET returned 500 Internal Server Error
ERROR: An error occurred during the fetch of repository 'nodejs_darwin_amd64'
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_michaellin/c4f1ea20e1fbbc6991019826232801ba/external/rules_nodejs/nodejs/repositories.bzl", line 358, column 19, in _nodejs_repo_impl
		_download_node(repository_ctx)
	File "/private/var/tmp/_bazel_michaellin/c4f1ea20e1fbbc6991019826232801ba/external/rules_nodejs/nodejs/repositories.bzl", line 174, column 40, in _download_node
		repository_ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://nodejs.org/dist/v16.15.0/node-v16.15.0-darwin-x64.tar.gz] to /private/var/tmp/_bazel_michaellin/c4f1ea20e1fbbc6991019826232801ba/external/nodejs_darwin_amd64/bin/nodejs/temp10326247846823580760/node-v16.15.0-darwin-x64.tar.gz: GET returned 500 Internal Server Error

### Additional Context

It seems because node.js no longer support v16.15.0 and update to 18.16.0 now.

By the way, due to the size limit of Android aab, we really need the optimized library.
Could you please include the optimized library of Android in the new release ?
Thanks a lot.

**Comment by homuler** [comment]
closes since at least CI is working.

> Could you please include the optimized library of Android in the new release ?

The symbols of the libraries in the tarball and the unitypackage are stripped now (see https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.12.0).
