### ISSUE TITLE
Face Mesh execution error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#915]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2022.3.1f1

### Your Host OS

Ubuntu20.04

### Target Platform

Linux Standalone

### Build Command

Face Mesh.unity

### Bug Description

Web camera is OK, but facemesh is not shown.

### Steps to Reproduce the Bug

1. Start Unity
2. Import MediaPipeUnity.0.11.0.unitypackage
3. Execute Assets/MediaPipeUnity/Samples/Scenes/Face Mesh/Face Mesh.unity

### Log

No registered object with name: FaceLandmarkFrontCpu; Unable to find Calculator "FaceLandmarkFrontCpu"
  at Mediapipe.Status.AssertOk () [0x00014] in ./Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:149 
  at Mediapipe.Unity.GraphRunner+<Initialize>d__39.MoveNext () [0x00078] in /home/dl/Unity/Hub/MediaPipe1/Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:119 
  at Mediapipe.Unity.WaitForResult+<Run>d__20.MoveNext () [0x0007c] in /home/dl/Unity/Hub/MediaPipe1/Assets/MediaPipeUnity/Samples/Common/Scripts/WaitForResult.cs:51 
UnityEngine.Logger:LogError (string,object)
Mediapipe.Unity.MemoizedLogger:LogError (string,object) (at Assets/MediaPipeUnity/Samples/Common/Scripts/MemoizedLogger.cs:199)
Mediapipe.Unity.Logger:LogError (string,object) (at ./Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Logger.cs:90)
Mediapipe.Unity.ImageSourceSolution`1/<Run>d__12<Mediapipe.Unity.FaceMesh.FaceMeshGraph>:MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs:79)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

**Comment by homuler** [comment]
Did you switch the Preferable Inference Mode from GPU to CPU?
If so, see https://github.com/homuler/MediaPipeUnityPlugin/issues/881.

P.S.
If you just want to run the sample scene, I recommend you download MediaPipeUnityPlugin-all.zip.

**Comment by Ishihara-Masabumi** [comment]
Thanks.
Then, please let me know how to  set the Preferable Inference Mode to GPU.
Next, please let me know how to  import  MediaPipeUnityPlugin-all.zip.

**Comment by homuler** [comment]
Are there any other error logs? Specifically, could it be that the GPU is not being utilized?
cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/FAQ#internalexception-internal--eglmakecurrent-returned-error-0x3000

See also https://github.com/homuler/MediaPipeUnityPlugin/issues/196.

**Comment by Ishihara-Masabumi** [comment]
This status is a little bit before, so it can't be replayed.

**Comment by Ishihara-Masabumi** [comment]
The initial error log at run is below.

![Screenshot from 2023-06-16 11-23-09](https://github.com/homuler/MediaPipeUnityPlugin/assets/23301778/7b4c6f5d-70ba-48a3-9cfa-1a786d5106b8)

**Comment by homuler** [comment]
> If you encounter an error like below and you use OpenGL Core as the Unity's graphics APIs, please try Vulkan.
