### ISSUE TITLE
perfect package for Linux

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#916]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2022.3.1f1

### Your Host OS

Ubuntu20.04

### Target Platform

Linux Standalone

### Description

I need perfect package for Linux.
Please tell me which package is perfect for Linux.

**Comment by homuler** [comment]
What do you mean by "perfect"?

**Comment by Ishihara-Masabumi** [comment]
We can run all the scenes.

**Comment by homuler** [comment]
All three files attached to the release page (i.e. `com.github.homuler.mediapipe-*.tgz`, `MediaPipeUnity.*.unitypackage`, `MediaPipeUnityPlugin-all.zip`) will do.
