### ISSUE TITLE
Face mesh execution error 2

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#917]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2022.3.1f1

### Your Host OS

Windows10

### Target Platform

Winodws Standalone

### Build Command

Face Mesh.unity

### Bug Description

I ran Face Mesh.unity, but the facemesh didin't show.

### Steps to Reproduce the Bug

1. Download MediaPipeUnityPlugin-all.zip
2. Unzip MediaPipeUnityPlugin-all.zip
3. Set the package in Assets
4. Execute Face Mesh.unity

### Log

FaceMeshSolution: Mediapipe.InternalException: Failed to prepare dependent assets
  at Mediapipe.Unity.GraphRunner+<Initialize>d__39.MoveNext () [0x00180] in C:\Users\user\Basis\Assets\MediaPipeUnityPlugin-all\Assets\MediaPipeUnity\Samples\Common\Scripts\GraphRunner.cs:134 
  at Mediapipe.Unity.WaitForResult+<Run>d__20.MoveNext () [0x0007c] in C:\Users\user\Basis\Assets\MediaPipeUnityPlugin-all\Assets\MediaPipeUnity\Samples\Common\Scripts\WaitForResult.cs:51 
UnityEngine.Logger:LogError (string,object)
Mediapipe.Unity.MemoizedLogger:LogError (string,object) (at Assets/MediaPipeUnityPlugin-all/Assets/MediaPipeUnity/Samples/Common/Scripts/MemoizedLogger.cs:199)
Mediapipe.Unity.Logger:LogError (string,object) (at Assets/MediaPipeUnityPlugin-all/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Logger.cs:90)
Mediapipe.Unity.ImageSourceSolution`1/<Run>d__12<Mediapipe.Unity.FaceMesh.FaceMeshGraph>:MoveNext () (at Assets/MediaPipeUnityPlugin-all/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs:79)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by homuler** [comment]
Please share the complete log.

> 3. Set the package in Assets

What did you do here?

**Comment by Ishihara-Masabumi** [comment]
unzipped folder MediaPipeUnityPlugin-all is copied in Assets.

**Comment by Ishihara-Masabumi** [comment]
Perfect log at run is below.

![Screenshot from 2023-06-16 11-28-59](https://github.com/homuler/MediaPipeUnityPlugin/assets/23301778/2bc502d1-e75d-48d0-9e77-3cad2be8647f)

**Comment by homuler** [comment]
> unzipped folder MediaPipeUnityPlugin-all is copied in Assets.

`MediaPipeUnityPlugin-all.zip` contains a stand alone unity project.
After unzipping it, please just open the project.

**Comment by Ishihara-Masabumi** [comment]
Thank you.
I have just opened Face Mesh.unity file.
