### ISSUE TITLE
usage of com.github.homuler.mediapipe-0.11.0

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#918]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2022.3.1f1

### Your Host OS

Windows10

### Target Platform

Windows Standalone

### Description

In com.github.homuler.mediapipe-0.11.0, there is no Face Mesh.unity file.
How should I do to use Fasemesh?

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/821#issuecomment-1365958366.

See also https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started
