### ISSUE TITLE
face mesh execution error 3

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#919]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2022.3.1f1

### Your Host OS

Ubuntu20.04

### Target Platform

Linux Standalone

### Build Command

MediaPipeUnity.0.11.0.unitypackage

### Bug Description

web camera image wasn't shown.

### Steps to Reproduce the Bug

1. start unity
2. import MediaPipeUnity.0.11.0.unitypackage
3. select Face Mesh.unity
4. run

### Log

: If your native library is built for CPU, change 'Preferable Inference Mode' to CPU from the Inspector Window for Bootstrap
UnityEngine.Logger:LogWarning (string,object)
Mediapipe.Unity.MemoizedLogger:LogWarning (string,object) (at Assets/MediaPipeUnity/Samples/Common/Scripts/MemoizedLogger.cs:187)
Mediapipe.Unity.Logger:LogWarning (string,object) (at ./Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Logger.cs:114)
Mediapipe.Unity.Logger:LogWarning (object) (at ./Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Logger.cs:121)
Mediapipe.Unity.Bootstrap/<Init>d__16:MoveNext () (at Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs:101)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

### Screenshot/Video

![Screenshot from 2023-06-16 09-49-43](https://github.com/homuler/MediaPipeUnityPlugin/assets/23301778/eff0d352-50ff-4bc4-a9f4-f28bee01d064)

**Comment by homuler** [comment]
duplicates #915 
See https://github.com/homuler/MediaPipeUnityPlugin/issues/915#issuecomment-1593902902.

First, please check if there're already similar issues before creating a new issue (in most cases, there is).
Second, please don't create the same issue repeatedly.

**Comment by Ishihara-Masabumi** [comment]
But, the status is not completely the same.
