### ISSUE TITLE
Remove models which are not needed before building native libraries

### ISSUE THREAD

**Issue by jignesh-comxr** [homuler/MediaPipeUnityPlugin#92]
I want to make use of just the hand tracking graph from this SDK.  I am building an app for iOS as well as Android.
What changes should I make in the `C/mediapipe_api/BUILD` file to achieve this? 

I tried an iOS build by removing the unnecessary graphs from the BUILD file, but it gave an error "`mediapipe not found`" on iPhone (the project worked fine on the editor).

Following is the edited BUILD file which I used:
[BUILD.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/6154011/BUILD.txt)

Can you help me in figuring out which all graphs to remove from the BUILD file so that I can just run the Hand tracking graph. This will help me in reducing the app size as well.

**Comment by homuler** [comment]
As to model files, you can also remove them by selecting `None` as their AssetBundle label.
![asset-bundle](https://user-images.githubusercontent.com/4690128/111461655-d2e89480-8760-11eb-905c-b9433f991c09.png)
And to reduce the library size, please see #65, too.

> I tried an iOS build by removing the unnecessary graphs from the BUILD file, but it gave an error "mediapipe not found" on iPhone (the project worked fine on the editor).

Will you attach the error log, please?

**Comment by jignesh-comxr** [comment]
@homuler 

Thanks for the suggestion.


> I tried an iOS build by removing the unnecessary graphs from the BUILD file, but it gave an error "`mediapipe not found`" on iPhone (the project worked fine on the editor).

Ignore this part, I was able to solve it myself (The "StreamingAssets" folder wasn't there in the project for some reason).

I was able to reduce the size for both iOS and Android by making change to the `C/mediapipe_api/BUILD` file.
Further, using the changes mention in #65, the apk size for the Android build reduced substantially. 

Is there any similar changes like the one in #65 for reducing the library size for iOS?

**Comment by homuler** [comment]
I updated the repository and you can now pass `--linkopt=-s` to `bazel` like this.

```sh
python build.py build --ios arm64 -s -v
```

> Is there any similar changes like the one in #65 for reducing the library size for iOS?

If you disable bitcode, probably the size would be much smaller (you cannot switch this option currently, though).
See https://github.com/homuler/MediaPipeUnityPlugin/blob/master/build.py#L207.
