### ISSUE TITLE
Linux version doesn't work

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#920]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.18f1

### Your Host OS

Ubuntu20.04

### Target Platform

Linux Standalone

### Build Command

Face Mesh.unity

### Bug Description

Face mesh wasn't shown.

### Steps to Reproduce the Bug

1. Open MediaPipeUnityPlugin-all
2. Run Face Mesh.unity

### Log

no message

### Screenshot/Video

![Screenshot from 2023-06-17 06-06-45](https://github.com/homuler/MediaPipeUnityPlugin/assets/23301778/0d6dc3aa-cc15-437a-8bc4-2b54dc7fcbbd)

**Comment by homuler** [comment]
Please don't open a new issue and continue in #915.

> Face mesh wasn't shown.

That's because you're running an empty scene (Face Mesh.unity is not opened).
