### ISSUE TITLE
How to get screen width and height

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#930]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.18f1

### Your Host OS

Windows10

### Target Platform

Windows Standalone

### Description

I need to get  screen width and height.
But, the following error message was shown.

Assets\MediaPipeUnity\Samples\Scenes\Face Mesh\FaceMeshSolution.cs(34,30): error CS0117: 'Screen' does not contain a definition for 'width'

Assets\MediaPipeUnity\Samples\Scenes\Face Mesh\FaceMeshSolution.cs(35,31): error CS0117: 'Screen' does not contain a definition for 'height'

**Comment by homuler** [comment]
Feel free to use the code from the sample app (files under `Assets`), but please note that I do not provide specific support for it.
If needed, you can modify the [Screen.cs](https://github.com/homuler/MediaPipeUnityPlugin/blob/f811ad3ab87166e56c9d67d764a16f86bbfe653f/Assets/MediaPipeUnity/Samples/Common/Scripts/Screen.cs) file accordingly.
For more information on how to use the plugin, please read [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial) first.
