### ISSUE TITLE
failed to build the docker image on windows with a linux container.

### ISSUE THREAD

**Issue by choigawoon** [homuler/MediaPipeUnityPlugin#936]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.8f1

### Your Host OS

Windows11Pro 22000.2057

### Target Platform

Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

i used docker desktop, so i think no need this.

### Command Sequences

docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile

### Log

 => ERROR [builder  4/10] RUN gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official  2.0s
------
 > [builder  4/10] RUN gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&     echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list &&     apt update:
#0 0.538 gpg: keybox '/usr/share/keyrings/mono-official-archive-keyring.gpg' created
#0 1.950 gpg: CRC error; EF0B94 - E39330
#0 1.950 gpg: read_block: read error: Invalid keyring
#0 1.950 gpg: Total number processed: 0
------
Dockerfile:72
--------------------
  71 |     # Install NuGet
  72 | >>> RUN gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
  73 | >>>     echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list && \
  74 | >>>     apt update
  75 |
--------------------
ERROR: failed to solve: process "/bin/sh -c gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&     echo \"deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main\" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list &&     apt update" did not complete successfully: exit code: 2

### Additional Context

i have no idea about gpg, and it says CRC error there.  
could you give me any tip for me?  
i use the lastest code tagged v0.12.0.  

windows 11  
linux container, docker desktop  
my command for building image  
```
docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile
```

**Comment by homuler** [comment]
How about running it with the `--no-cache` option?

**Comment by choigawoon** [comment]
it occured when i build an image.
i tried but failed again.  
```cmd
docker build --no-cache -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile
```

**Comment by homuler** [comment]
> it works on the other machine.

Do you mean it works on the other machines on the same network?
