### ISSUE TITLE
Typo in Wiki code example

### ISSUE THREAD

**Issue by Ale1** [homuler/MediaPipeUnityPlugin#939]
### Description

![Screenshot 2023-06-29 at 16 57 02](https://github.com/homuler/MediaPipeUnityPlugin/assets/4612160/3a6d0e02-1e0a-4e83-8d19-5ed2429ea980)

In the "Getting Started --> More Tips --> Glog" page, the code example has: 

`Glog.minLogLevel = 0; // output INFO logs
Glog.v = 3; // output more verbose logs`

but its missing capitalisation on minLogLevel and V, it should instead be:

`Glog.MinLogLevel = 0; // output INFO logs
Glog.V = 3; // output more verbose logs`

**Comment by homuler** [comment]
Thx! I fixed it.
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#glog

I feel it would be best to include the documents in the repository.
