### ISSUE TITLE
Compatibility of mediapipe version 0.9.3 with this MediaPipeUnityPlugin

### ISSUE THREAD

**Issue by emphaticaditya** [homuler/MediaPipeUnityPlugin#940]
### Feature Description

Hey guys
Can anyone link this unity plugin bridge to 0.9.3 or later version of mediapipe. It'll be really helpful. Thanks in advance!!

**Comment by homuler** [comment]
Sorry, I forgot to update the README.
The latest version (v0.12.0) uses MediaPipe 0.10.1.
https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.12.0
