### ISSUE TITLE
the face, pose, and hand of the avatar can be driven through the detection ability of Holistic, and even 52 blendshapes of ARKit can be supported

### ISSUE THREAD

**Issue by boostcat** [homuler/MediaPipeUnityPlugin#943]
### Feature Description

I hope that the function of driving avatar can be added in the demo, and the face, pose, and hand of the avatar can be driven through the detection ability of Holistic, and even 52 blendshapes of ARKit can be supported.
Thank you very much.
for example: [https://3d.kalidoface.com/](https://3d.kalidoface.com/)

**Comment by homuler** [comment]
This project aims to enable the creation of applications similar to Kalidoface, but providing an application like Kalidoface is not its purpose.
