### ISSUE TITLE
Standalone build don't work on different pc

### ISSUE THREAD

**Issue by TulgaTDev** [homuler/MediaPipeUnityPlugin#946]
### Description

I recently encountered a strange issue. Initially, I developed a Unity project that utilizes the Mediapipe plugin. After completing the project, I built a version that worked fine on my PC. However, when I attempted to run it on a different PC, things didn't go as expected. The annotation points didn't appear on my face (which is recorded through the webcam). As a result, I decided to build the project on the new PC, where the previous build didn't work. When I opened the project, I encountered errors related to the asset loader type from the bootstrap component. To resolve these errors, I changed the asset loader type from "streaming assets" to "local." Then, I switched it back to "streaming assets" for the build. After fixing these errors, I successfully built and ran the project, it worked fine. Interestingly, I also rechecked the first build version from my old computer, and it somehow worked as well. For now, everything seems to be functioning correctly, but I would like to understand the cause of this issue and learn how to prevent it from occurring in the future.

**Comment by homuler** [comment]
I suspect that the necessary model files were not included in the initial build, but the information above is not enough to provide a conclusive answer.

If you'd like to specify the cause, please share the reproduction steps and the corresponding logs after confirming that the issue can be reproduced in your environment.

**Comment by TulgaTDev** [comment]
how can i add necessary models to build?
