### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Almazikman** [homuler/MediaPipeUnityPlugin#95]
I managed to build properly, now it's more or less works but, from start, it didn't render camera image on background, I checked adb logs and noticed that problem was assetBundles, I built them and tried again - nothing changed. After several tries I revert my changes in settings - no result but app started to crash after 1-2 seconds. I built assetBundles, btw.

Here are my logs
`03-20 00:02:05.095 26467 26482 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 2826mb
03-20 00:02:05.095 26467 26482 I Unity   : 
03-20 00:02:05.095 26467 26482 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf), 4 little (mask: 0xf0)
03-20 00:02:05.095 26467 26482 I Unity   : 
03-20 00:02:05.097 26467 26482 I Unity   : ApplicationInfo com.Template.TestAR version 0.1 build e0141dd9-be66-453e-be18-30b3a429cfa3
03-20 00:02:05.097 26467 26482 I Unity   : 
03-20 00:02:05.097 26467 26482 I Unity   : Built from '2020.2/release' branch, Version '2020.2.1f1 (270dd8c3da1c)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
03-20 00:02:05.097 26467 26482 I Unity   : 
03-20 00:02:05.338 26467 26482 I Unity   : Company Name: Template
03-20 00:02:05.338 26467 26482 I Unity   : Product Name: TestAR
03-20 00:02:05.410 26467 26482 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_i
03-20 00:02:05.410 26467 26482 D Unity   : mage_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT
03-20 00:02:05.410 26467 26482 D Unity   : _external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control
03-20 00:02:09.283 26467 26482 I Unity   : Starting to load assets
03-20 00:02:09.283 26467 26482 I Unity   : 
03-20 00:02:09.285 26467 26491 E Unity   : Unable to open archive file: jar:file:///data/app/com.Template.TestAR-4cr08o1qHzZ94PbgHoOUOA==/base.apk!/assets/AssetBundles/mediapipe/models
03-20 00:02:09.285 26467 26491 E Unity   : 
03-20 00:02:09.313 26467 26482 E Unity   : Failed to load the AssetBundle
03-20 00:02:09.313 26467 26482 E Unity   : 
03-20 00:02:09.399 26467 26482 I Unity   : Graph Changed: Face Detection
03-20 00:02:09.399 26467 26482 I Unity   : 
03-20 00:02:09.857 26467 26482 I Unity   : WebCamDevice Changed: Camera 0
03-20 00:02:09.857 26467 26482 I Unity   : 
03-20 00:02:10.076 26467 26482 I Unity   : WebCamTexture Graphics Format: 88
03-20 00:02:10.076 26467 26482 I Unity   : 
03-20 00:02:10.084 26467 26482 I Unity   : EGL Context Found (-966330944)
03-20 00:02:10.084 26467 26482 I Unity   : 
03-20 00:02:10.088 26467 26482 I native  : I20210320 00:02:10.088512 26482 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
03-20 00:02:10.092 26467 26573 I native  : I20210320 00:02:10.092283 26573 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 V@331.0 (GIT@a7f70d7, I06947f1a28) (Date:11/19/18))
03-20 00:02:10.124 26467 26482 E Unity   : Failed to read data for the AssetBundle 'models'.
03-20 00:02:10.124 26467 26482 E Unity   : 
03-20 00:02:10.687 26467 26482 E Unity   : MediaPipeException: INTERNAL: Graph has errors: 
03-20 00:02:10.687 26467 26482 E Unity   : Calculator::Open() for node "facedetectionfrontgpu__InferenceCalculator" failed: ; (asset_path)!=(nullptr)apipe_api/util/resource_manager.cc:33) 
03-20 00:02:10.687 26467 26482 E Unity   :   at Mediapipe.Status.AssertOk () [0x00013] in <2b69336195ea426bbf7bd604110e13bf>:0 
03-20 00:02:10.687 26467 26482 E Unity   :   at SceneDirector+<RunGraph>d__26.MoveNext () [0x001b0] in <ee631ed102754ad89e173b8301214009>:0 
03-20 00:02:10.687 26467 26482 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <e12aeddac25b4395aeaca946c70b344e>:0 
03-20 00:02:10.687 26467 26482 E Unity   : 
`

Could you help me?

**Comment by AlanWuJinliang** [comment]
try compile again.
delete the project.
restart

**Comment by AlanWuJinliang** [comment]
must make sure your compile environment is true.

**Comment by homuler** [comment]
> After several tries I revert my changes in settings

I don't know what those changes are, but from the below logs, I can say that your app assumes that AssetBundle file called `mediapipe/models` exists but it didn't actually.

> 03-20 00:02:10.124 26467 26482 E Unity : Failed to read data for the AssetBundle 'models'.
03-20 00:02:10.124 26467 26482 E Unity :
03-20 00:02:10.687 26467 26482 E Unity : MediaPipeException: INTERNAL: Graph has errors: 
03-20 00:02:10.687 26467 26482 E Unity : Calculator::Open() for node "facedetectionfrontgpu__InferenceCalculator" failed: ; (asset_path)!=(nullptr)apipe_api/util/resource_manager.cc:33) 

Please check below things.

1. Is there `Assets/StreamingAssets/mediapipe/models`?
2. AssetBundle Label for your model files are correct? (must be `mediapipe/models` in your case)
   ![asset-bundle](https://user-images.githubusercontent.com/4690128/111461655-d2e89480-8760-11eb-905c-b9433f991c09.png)
