### ISSUE TITLE
MediaPipeUnityPlugin concurrency guide

### ISSUE THREAD

**Issue by jsaon-L** [homuler/MediaPipeUnityPlugin#951]
### Description

I want to make a server program that can be used to identify Pose, but I don't know how to deal with concurrency,

**Comment by homuler** [comment]
Since this plugin runs on the client side, I wasn't sure if this question was related to this project, but how specifically is it?

**Comment by jsaon-L** [comment]
I want this program to run on the server side
I want to create a server program where http request can do image recognition,get image pose or facemesh
When there are a lot of http requests, how should I use "MediaPipeUnityPlugin" to process the pictures sent by http and make full use of GPU resources


I don't know if I express clearly, I drew a diagram to explain what I want to do
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/17309378/04225f65-1803-42f0-9ef9-ff69f332e8be)

any help is greatly appreciated
