### ISSUE TITLE
What kind of runtime backend this Plugin use?

### ISSUE THREAD

**Issue by dayowoo** [homuler/MediaPipeUnityPlugin#952]
### Description

Hi, first Thank you for creating Mediapipe Plugin.

I want to know which runtime backend this Plugin use..

https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=blazepose
There is 3type of runtime backend model (mediapipe-gpu, tfjs-webgl, tfjs-webgpu)

Thank you.

**Comment by homuler** [comment]
> There is 3type of runtime backend model (mediapipe-gpu, tfjs-webgl, tfjs-webgpu)

1. This project doesn't run on the web. Therefore, the 3 options for the `runtime-backend` are not relevant to this project.
2. I believe the choice of runtime is determined by `CalculatorGraphConfig` rather than this plugin.

Could you please let me know the intention behind this question?

**Comment by dayowoo** [comment]
I want to increase fps speed, mediapipe latency.
so I got the fastest fps speed when I use mediapipe-gpu runtime backend model in that site.

I'm just curious, thanks for answering

**Comment by homuler** [comment]
> I still dont know how.....

Sorry, what would you like to know?

**Comment by dayowoo** [comment]
Sorry for the late reply.
The purpose of my question is to increase the mediapipe latency.

I am conducting a test by device.

The mediapipe latency is over 50 on the desktop and 30 on the iOS, but about 10 on the Galaxy series. (The application fps are all equal to 30.)

The difference is that graphic api is different from opengles and metal.
So, I modified my Holistic_opengles (OpenGlesConfig file in Holistic Tracking graph), but it doesnt make to improve latency.

> I believe the choice of runtime is determined by CalculatorGraphConfig rather than this plugin.

and.. Is this the correct code for the `CalculatorGraphConfig` you mentioned?
[Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraph.cs](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraph.cs)

Thank you.

**Comment by homuler** [comment]
Generally, the unit of latency is understood to be milliseconds (ms), but are you referring to FPS here? (would you like to improve the performance on the Android devices?)

If so, can you check if it is the same issue as https://github.com/homuler/MediaPipeUnityPlugin/issues/768#issuecomment-1285330371 ?

> Is this the correct code for the `CalculatorGraphConfig` you mentioned?

See https://developers.google.com/mediapipe/framework/framework_concepts/graphs
