### ISSUE TITLE
After building, the applications don't start.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#955]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.7f1

### Your Host OS

Windows10

### Target Platform

Windows Standalone

### Description

After building, MediaPipeUnityPlugin.exe file was generated.
After double clicking the exe file, a menu window appears.
Then, click a specific application, but the application doesn't start.
Please tell me how to build for the applications to start.

**Comment by homuler** [comment]
Please build the app with Development Build checked and share the Player.log.
