### ISSUE TITLE
builded exe can't run on some windows10 PC

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [homuler/MediaPipeUnityPlugin#962]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

Windows10

### Target Platform

Windows Standalone

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio 2019

### Command Sequences

Building on the Windows 10 PC is successful.
But, the created exe can't run on some Windows 10 PC.
So it is strange.
Please tell me the reason and the countermeasure.

### Log

Nothing

**Comment by homuler** [comment]
Please share the log.
