### ISSUE TITLE
How can I install these native libraries ?

### ISSUE THREAD

**Issue by koko-cg** [homuler/MediaPipeUnityPlugin#964]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.18f1

### Your Host OS

macOC Ventura13.4.1 (M1)

### Target Platform

UnityEditor, Mac Standalone, iOS

### Description

This is the first text at Install Guide.

"This repository does not contain required libraries (e.g. libmediapipe_c.so, Google.Protobuf.dll, etc), so you need to build them first."

I want to know which native libraries I should install, and how can I install them.

I'm not sure if the absence of this library is the cause, but when I try to install and open the sample scene, I get a 'PackageWindowsManager Error' and can't open it. It's a very basic question, but if anyone knows, I would be grateful for your help.

**Comment by homuler** [comment]
Please just download `MediaPipeUnityPlugin-all.zip` from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.12.0) and open the project.

See also https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation
