### ISSUE TITLE
Compilation error for MacOs/iOs build

### ISSUE THREAD

**Issue by shalom-aviv** [homuler/MediaPipeUnityPlugin#967]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2022

### Your Host OS

MacOs Venture 13.4.1

### Target Platform

Mac Standalone, iOS

### Command Sequences

python build.py build --desktop cpu --opencv cmake --macos_universal --ios arm64 -vv

### Log

<img width="1471" alt="Screenshot 2023-07-23 at 8 55 55 PM" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/78256107/b355da0d-c6f6-439a-8e64-d0f2e2832715">
<img width="1470" alt="Screenshot 2023-07-23 at 8 56 18 PM" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/78256107/2773ed96-581f-4ed9-9f56-a619c2f8c99c">
<img width="1479" alt="Screenshot 2023-07-23 at 8 56 50 PM" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/78256107/507b8e22-5356-46d8-9247-bbde32031217">

**Comment by homuler** [comment]
won't fix since it compiles successfully on GitHub Actions.
