### ISSUE TITLE
what is the correct pose index

### ISSUE THREAD

**Issue by andeyeluguo** [homuler/MediaPipeUnityPlugin#968]
### Description

I read the code in the tutorial
```
var topOfHead = landmarks.Landmark[10];
  Debug.Log($"Unity Local Coordinates: {screenRect.GetPoint(topOfHead)}, Image Coordinates: {topOfHead}");
}
```

but in the 
https://ai.googleblog.com/2020/08/on-device-real-time-body-pose-tracking.html
the index 10 seems not to be the top of head. can you please give a  offical picture of the MediaPipeUnityPlugin pose?

**Comment by homuler** [comment]
Please note that the tutorial deals with Face Mesh, not Pose.
https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png
