### ISSUE TITLE
androidにおける動画再生と同時にポーズ推定を行った時の動作の問題について

### ISSUE THREAD

**Issue by hakule6** [homuler/MediaPipeUnityPlugin#969]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2022.3.5

### Your Host OS

macOS Ventura13.4.1

### Target Platform

Android

### Description

日本語で失礼します
現在、動画を再生させながらポーズ推定を行うアプリを作成しているのですが、ポーズを推定する動作は

    if (_outputVideoStream.TryGetNext(out var outputVideo))
    {
      if (outputVideo.TryReadPixelData(_outputPixelData))
      {
        _outputTexture.SetPixels32(_outputPixelData);
        _outputTexture.Apply();
      }
    }

のコードで人の目で正常に動作していることが確認できるのですが、動画を再生する部分に関しては動画がカクカクして、正常に動作しない状況です
動画に関しては、videoplayerを用いて実装しています

### Additional Context

私が調べたところ、疑わしい部分はandroidにおけるcpuのスレッドが不自然に生成されているところです、以下のようにスレッドが生成されています
![スクリーンショット 2023-07-24 18 01 23](https://github.com/homuler/MediaPipeUnityPlugin/assets/136915287/7611c14b-baa0-49bd-bcbb-107f7bc8ea37)

    if (_outputVideoStream.TryGetNext(out var outputVideo))
    {
      if (outputVideo.TryReadPixelData(_outputPixelData))
      {
        _outputTexture.SetPixels32(_outputPixelData);
        _outputTexture.Apply();
      }
    }

このコードを削除すると、以下のようにスレッドが再利用され、動画は滑らかに正常に再生されます
![スクリーンショット 2023-07-24 18 02 12](https://github.com/homuler/MediaPipeUnityPlugin/assets/136915287/e3d067d2-c7d9-45f8-bb73-4943960d4c4d)

何か解決法はありませんでしょうか？よろしくお願いします

**Comment by homuler** [comment]
できれば（chatGPTを使うなどして）英語でissueを作って欲しいですが、今回はそのまま回答します。

全体でどういうコードになっているのか分かりませんが、↓のコードはめちゃくちゃ遅いと思います。
> ```cs
> if (_outputVideoStream.TryGetNext(out var outputVideo))
> {
>   if (outputVideo.TryReadPixelData(_outputPixelData))
>   {
>     _outputTexture.SetPixels32(_outputPixelData);
>     _outputTexture.Apply();
>   }
> }
> ```

少なくとも、もう少し速い方法があります。
https://github.com/homuler/MediaPipeUnityPlugin/blob/c827fb1e1bd70cc9a2ca1772d5a5b7e353452799/Assets/MediaPipeUnity/Samples/Scenes/MediaPipe%20Video/MediaPipeVideoSolution.cs#L84

ただ、そもそも画像データをMediaPipeから取ってそうなのはなんででしょう？
画像自体は、おそらく入力としてMediaPipeに送ったものがあると思うので、ポーズ推定の結果（e.g. `NormalizedLandmarkList`）だけMediaPipeから受け取って、画像は入力画像をそのまま画面に表示するのが良いと思います。

**Comment by hakule6** [comment]
ご返信ありがとうございます、ご迷惑をおかけしました、今後は英語でissueを作成いたします

ご返信からですと、`TryGetNext()`を呼び出さずに`NormalizedLandmarkList`からLandmarkの座標のみを受け取るとパフォーマンスは改善するということでしょうか？試してみますので、お待ちいただけないでしょうか

**Comment by homuler** [comment]
どんな `CalculatorGraphConfig` を使っているか書かれていないので、なんとも言えないですが、 `pose_landmarks` の値を `TryGetNext` で取るのは良いとして、`output_video` を取る必要はないのでは？という趣旨です（画面に表示する画像は、入力画像を使えば良い）。MediaPipeがannotationをつけた画像を表示するのが目的であれば、この限りではないですが。
https://github.com/homuler/MediaPipeUnityPlugin/blob/c827fb1e1bd70cc9a2ca1772d5a5b7e353452799/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/PoseTrackingGraph.cs#L124

それより速くしたければ、非同期で受け取るという方法もありますが、実装がやや難しくなります。

**Comment by hakule6** [comment]
少し伝え間違えた点がありました、申し訳ございません
動画からポーズの推定を行っているわけではなく、ポーズの推定はカメラから取った映像で行っています、その隣に映像を流す、ということです
```C#
if (_outputVideoStream.TryGetNext(out var outputVideo))
{
  if (outputVideo.TryReadPixelData(_outputPixelData))
  {
    _outputTexture.SetPixels32(_outputPixelData);
    _outputTexture.Apply();
  }
}
```
このコードは、ちゃんとカメラから撮れた映像が正しい画面上の座標に投影されているか確認する目的があります

`Landmark`を取得するために、以下のコードを使っています
```C#
if (_poseLandmarksStream.TryGetNext(out var poseLandmarks))
{
  if (poseLandmarks != null)
  {
    for (int i = 1; i <= 32; i++)
    {
      var index = nameAndNumberPairs.Value;
      _bodyLandmarks = _screenRect.GetPoint(poseLandmarks.Landmark[index]);
    }
  }
}
```
最初は、カメラからの映像と流す映像を同時に再生することがパフォーマンスの低下に繋がっていると思い、`_outputVideoStream.TryGetNext(out var outputVideo)`を削除したのですが、`_poseLandmarksStream.TryGetNext(out var poseLandmarks)`をとるだけでも、流したい映像はカクカクになってしまいます

**Comment by homuler** [comment]
> カメラからの映像と流す映像を同時に再生することがパフォーマンスの低下に繋がっていると思い、

プロファイラで遅い部分を特定してください。
`TryGetNext` でスレッドをブロックしているなら、 `_poseLandmarksStream` の初期化の仕方が悪いかもしれません。

> 流したい映像はカクカクになってしまいます

サンプルアプリを試しましたか？
サンプルアプリでも同様であれば、対象のデバイスでは限界がある可能性があります。
また、サンプルアプリに  Async モードと Sync モードがありますが（アプリUIのフッターのボタンから変更できる）、それぞれ試してみて、挙動が変わるかも見てほしいです。

> ### Code to Reproduce the issue

が `No response` になっていますが、これではこれ以上回答できません。
CalculatorGraphの開始から終了までと、CalculatorGraphConfigの中身は最低でも載せてほしいです（理想的には、再現可能な最小構成のコードを共有してほしい）。

**Comment by hakule6** [comment]
プロファイラを確認したところ、`Webcam.Update`に419msかかり、主にこの部分が遅いと思われます、`TryGetNext`でスレッドをブロックしているかどうかは確認できませんでしたが、どのように確認するか、教えていただけると幸いです

>サンプルアプリを試しましたか？ 

この部分に関しては現在試しておりますので、お待ちください

>CalculatorGraphの開始から終了までと、CalculatorGraphConfigの中身は最低でも載せてほしいです（理想的には、再現可能な最小構成のコードを共有してほしい）。

すみません、CalculatorGraphの開始から終了までと、CalculatorGraphConfigの中身とはなんでしょうか？CalculatorGraphのスクリプトということでしょうか（違うのであれば教えていただけると嬉しいです）

**Comment by hakule6** [comment]
>サンプルアプリを試しましたか？

こちらに関して試してみたのですが、私が作成したアプリと同じannotationをつけたカメラの映像は気になる程度の各月はなく、映像の方は音声も途切れ途切れになりカクつくという問題がsync, Async関係なく発生しています

**Comment by homuler** [comment]
> Code to Reproduce the issue

私が手元で再現するのに必要十分なコードを書いてほしいです（今の情報では、私があなたの見ている画面を再現するのは不可能ですよね？）。
[Tutorialのコード](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#official-solution-gpu)のようなものです（リポジトリのリンクでもOK）。

CalculatorGraphConfigというのは、[ここ](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#send-input) のようなprotoで書かれたCalculatorGraphの設定です。

> こちらに関して試してみたのですが、私が作成したアプリと同じannotationをつけたカメラの映像は気になる程度のカクつきはなく、映像の方は音声も途切れ途切れになりカクつくという問題がsync, Async関係なく発生しています

何を試しましたか？（サンプルアプリは音声を出力しないので……）
こちらの意図としては、このリポジトリのunity projectを（何も変えずに）そのままbuildして実行ほしいです。
また、こういう時は、何が起きているのかを示すために、画面キャプチャした動画を載せてもらうのが一番ありがたいです。

**Comment by homuler** [comment]
> `Webcam.Update` に419msかかり

このコードはこのプラグインと関係ありますか？

**Comment by hakule6** [comment]
[https://github.com/hakule6/Mediapipe_withVideo.git](url)
以上がリポジトリのリンクです、github初心者のため、100MBを超えるフィアルのアップロードの仕方がわからず、以上のリポジトリでは`Packages/com.github.homuler.mediapipe/Runtime/Plugins`にある`mediapipe_android.aar`と`Packages/com.github.homuler.mediapipe/Runtime/Plugins/iOS`にある`MediaPipeUnity`が欠けてます、申し訳ございません

TutorialとSampleのPose Trackingで私がここまで述べたものを作成しているので、Android上で動かしていただければ幸いです、ご迷惑をおかけします

>該当するコードが分からないのですが、このコードはこのプラグインと関係ありますか？

これに関しては、official solutionの`WebcamTexture`に関連があると思いますが、なぜここで時間がかかってしまうのは見当がついていないです（想定した箇所と異なったため）

**Comment by hakule6** [comment]
ちなみに

>カメラと映像を同時に流すのは好ましくないと考えたこともあるのですが、mediapipeを用いない実装ではこのような問題が発生しませんでした

で述べた通り、今のところmediapipeを用いて実装した場合のみこの問題が発生しています

**Comment by homuler** [comment]
> 何を試しましたか？（サンプルアプリは音声を出力しないので……）
こちらの意図としては、このリポジトリのunity projectを（何も変えずに）そのままbuildして実行ほしいです。
また、こういう時は、何が起きているのかを示すために、画面キャプチャした動画を載せてもらうのが一番ありがたいです。

こちらはどうですか？

**Comment by homuler** [comment]
> 100MBを超えるフィアルのアップロードの仕方がわからず

実際に手元で動かすわけではないので、問題ないです :+1:  （ただし、手元で動かせるレベルのコードがないと、回答できないことが多いです）

全部1 commitで入っていて、diffがわからないのですが、問題のコードは↓ですか？
https://github.com/hakule6/Mediapipe_withVideo/blob/a67179c7ea7b48d3bcd98854102f936783ceb34b/Assets/MediaPipeUnity/Tutorial/Pose%20Tracking/PoseTracking.cs

1. 具体的にどの行で時間がかかっていますか？（Deep Profilingを有効にすれば分かるはず）
2. `_width` と `_height` の値はどうなっていますか？
   - これが大きいと、 [`SetPixels32`](https://github.com/hakule6/Mediapipe_withVideo/blob/a67179c7ea7b48d3bcd98854102f936783ceb34b/Assets/MediaPipeUnity/Tutorial/Pose%20Tracking/PoseTracking.cs#L113) は致命的に遅くなると思います
   - 同じ理由で、[`_outputTexture` の更新](https://github.com/hakule6/Mediapipe_withVideo/blob/a67179c7ea7b48d3bcd98854102f936783ceb34b/Assets/MediaPipeUnity/Tutorial/Pose%20Tracking/PoseTracking.cs#L119-L126)は相当遅いと思います
     - 本質的ではないと思いますが（そもそも `outputVideoStream` からデータを読むべきではない）、もう少し速い方法もあります
       https://github.com/homuler/MediaPipeUnityPlugin/blob/c7771138cf2361f6184220424fa751ab90f60672/Assets/MediaPipeUnity/Samples/Scenes/MediaPipe%20Video/MediaPipeVideoSolution.cs#L84
3. Androidでは、 `ImageFramePacket` ではなく `GpuBufferPacket` を入力に使って、コピー回数を減らす方法があります
   https://github.com/homuler/MediaPipeUnityPlugin/blob/c7771138cf2361f6184220424fa751ab90f60672/Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs#L194
  https://github.com/homuler/MediaPipeUnityPlugin/blob/c7771138cf2361f6184220424fa751ab90f60672/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/TextureFrame.cs#L245-L246

**Comment by hakule6** [comment]
>こちらはどうですか？
要するに、↓が実装の問題なのかの原因を切り分けたいです（このリポジトリのサンプルや、MediaPipe公式のサンプルが端末上で遅ければ、それより速くできない可能性が高いため）。

リポジトリを何も手を加えずに動かした時、ということでしょうか？
その場合は、特に問題なく正常に動いています

**Comment by hakule6** [comment]
確認してくださり、ありがとうございます！

>問題のコードは↓ですか？

はい、その通りです

>具体的にどの行で時間がかかっていますか？

これについては、やってみるので後ほど詳しくお伝えします

>`_width` と `_height` の値はどうなっていますか？

`_width`については640、`_height`については320が入っています、ここがパフォーマンスを低下させていると疑って値を小さくしたこともあるのですが、特に変化はありませんでした
`outputVideoStream`から読む代替案としての`_outputTexture.LoadRawTextureData`の実装、`GpuBufferPacket`での実装も試してみますので、お待ちいただけないでしょうか

**Comment by hakule6** [comment]
すみません、現在検証中で一点お聞きしたいことがあるのですが

>そもそも outputVideoStream からデータを読むべきではない

↑について、現在`Landmarks`を取得するために結局`OutputStream`から座標を取得しなければならないのですが、この部分に関しては他のアプローチが存在するのでしょうか？（不勉強で申し訳ございません）

**Comment by homuler** [comment]
> この部分に関しては他のアプローチが存在するのでしょうか？

[CalculatorGraphConfig](https://developers.google.com/mediapipe/framework/framework_concepts/graphs) の用語での `output_stream` 以外から読むことはできないと思います。
この値をC#から読む方法はいくつかありますが、必要な値（ここではposeのlandmarkなど）を読む分にはどの方法を使っても良いと思います。 

`outputVideoStream` からデータを読むべきではないというのは、画像データが大きいからで（NativeのデータをManagedな領域にコピーするのに時間がかかる）、 `OutputStream` を使うのが非推奨ということではありません。
ちなみに、もっというと `PoseRendererGpu` は、最終的には消したほうが良いです。debug用途に使うのは良いと思いますし、今回の問題と直接関係はないと思っていますが。

P.S. ノイズにもなるので、特に悪いことをしていないのに謝ったり、不勉強とか書く必要はないです

**Comment by hakule6** [comment]
>ノイズにもなるので、特に悪いことをしていないのに謝ったり、不勉強とか書く必要はないです

ご迷惑をおかけしました

以下の動画はカメラから撮った映像をnativeでRenderTextureに流しているのですが（diffが確認できます）、unityのプロファイラでは30fpsのパフォーマンスが確認され、遅い部分は特にありませんでした

https://github.com/homuler/MediaPipeUnityPlugin/assets/136915287/0bd26a02-ca6e-43f1-953c-b5095bbf6b27

AndroidStudioのプロファイラを確認した時、以下の状態が確認できます

![スクリーンショット 2023-08-03 15 36 07](https://github.com/homuler/MediaPipeUnityPlugin/assets/136915287/fb69ff2a-6977-45c7-8d06-311ab82904af)

映った時に映像の再生が遅くなるのを見るとやはりパフォーマンスが下がってしまうので、`output_video` を取ることが原因ではないとは思うのですが...いかがでしょうか

**Comment by homuler** [comment]
> `output_video` を取ることが原因ではないとは思うのですが...いかがでしょうか

なるほど、 `output_video` の取得そのものが問題になるというより、取得結果を使った処理が遅い可能性はあるかなと思っていました。

> 具体的にどの行で時間がかかっていますか？（Deep Profilingを有効にすれば分かるはず）

結局これに尽きていて、こちらのスタンスは

1. 無償サポートの範囲では、原因調査をするつもりはない
2. あるコード（メソッド呼び出し等）が遅く、それがプラグインの使い方 or 実装に起因するものであれば、アドバイス or 修正する
3. プラグインと関係のないコードが遅いのであれば、issueはクローズ

というものなので、とにかく原因の行を特定して、それについての質問を投げてほしいです（サンプルアプリが問題なかったとのことなので、アプリの実装上の問題の可能性が高いと思っています）。

**Comment by hakule6** [comment]
> （Deep Profilingを有効にすれば分かるはず）

こちらに関してですが、以下のような状況です
![スクリーンショット 2023-08-04 9 40 19](https://github.com/homuler/MediaPipeUnityPlugin/assets/136915287/26ad0cbf-7a93-4305-ba4d-11b45b660a70)
![スクリーンショット 2023-08-04 9 42 52](https://github.com/homuler/MediaPipeUnityPlugin/assets/136915287/38e1c7ae-8ab0-44a0-89d4-daceec7806d1)

`OutputStream`の`TryGetNext()`で時間がかかっているのは読み取れるのですが、特段長い時間を要していないので、不明な状況です

もう少し私の方で調べてみますので、お待ちください
