### ISSUE TITLE
run build.py get error AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by jsaon-L** [homuler/MediaPipeUnityPlugin#97]
hi i want update to 0.51 from 0.50 
i run ` python build.py build --desktop cpu -v` and `python build.py build --help` get same error 👇
```
Traceback (most recent call last):
  File "build.py", line 341, in <module>
    Argument().command().run()
  File "build.py", line 310, in __init__
    build_command_parser.add_argument('--resources', action=argparse.BooleanOptionalAction, default=True)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```
this my console 
![image](https://user-images.githubusercontent.com/17309378/111961327-e3678900-8b2b-11eb-95b4-e2314476fecf.png)

---
I think this project is amazing
I want to contribute code but i will only unity 
so i can help what (●'◡'●)

**Comment by jsaon-L** [comment]
i can play 0.5.0 in UnityEditor
i git clone 0.5.1 buil fail

**Comment by chrisError** [comment]
we ae getting some python build error (on Mac OS), the previous build script was working for us.

**Comment by jsaon-L** [comment]
> we ae getting some python build error (on Mac OS), the previous build script was working for us.

so i Should be use `make cpu` and `make install` to build 0.5.1 right ?

**Comment by chrisError** [comment]
ah no sorry we are not able to build 0.5.1 at all, 0.5 was building for us.

**Comment by jsaon-L** [comment]
> ah no sorry we are not able to build 0.5.1 at all, 0.5 was building for us.

ok i back 0.5.0
wait next perfect version
thank you

**Comment by homuler** [comment]
I overlooked that Python 3.9 is required to use `argparse.BooleanOptionalAction`.
As a workaround, will you upgrade python and try again?

**Comment by chrisError** [comment]
thanks @homuler using python 3.9 fixed that build issue, but we did now hit the compilation error
"In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_errors.cc:23:
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/portable_egl.h:19:10: fatal error: 'EGL/egl.h' file not found
#include <EGL/egl.h>"

but I can start a new issue for that now.

**Comment by pjbaron** [comment]
That egl.h issue is triggered by building 'gpu' for desktop - when I built for cpu it worked

**Comment by jsaon-L** [comment]
use python3.9 all ok 
and `set` not work in powershell ,use cmd in windows

**Comment by GreyPoupwn** [comment]
Using pyenv / Python 3.9.0 worked for me, as well.

I highly suggest using pyenv to manage python versions, rather than installing multiple versions and crossing one's fingers :)

**Comment by homuler** [comment]
I updated README and also introduced Docker environments.

**Comment by Leuconoe** [comment]
I put the library with BooleanOptionalAction in the same path as build.py. The build went without a problem.

wget --no-clobber https://raw.githubusercontent.com/python/cpython/master/Lib/argparse.py

**Comment by Thaina** [comment]
> That egl.h issue is triggered by building 'gpu' for desktop - when I built for cpu it worked

So we can't build desktop gpu even in windows? Which platform we need for then then
