### ISSUE TITLE
Mediapipe consume more cpu in URP Project

### ISSUE THREAD

**Issue by sxyxlhq** [homuler/MediaPipeUnityPlugin#979]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.19f1

### Your Host OS

Window 10 Home

### Target Platform

Android

### Description

Hello Homuler, I found that mediapipe consume more cpu in urp project.  I create two projects. one is buildin, the other is URP.
 I run Holistic Sample Scene, source is Video. 
this is run in buildin project
![buildin](https://github.com/homuler/MediaPipeUnityPlugin/assets/11514032/eb14b792-dd98-4b88-afd4-b8f909f19637)
this is run in urp project
![urp](https://github.com/homuler/MediaPipeUnityPlugin/assets/11514032/58d42987-47f8-4c6d-a4b8-9c229bb3774f)
please help me.

**Comment by mgarbade** [comment]
What do you mean by "one is buildin". Do you use a different rendering engine than URP? (URP is probably the faster option)

**Comment by sxyxlhq** [comment]
I mean is " Built-in Render Pipeline"

**Comment by sxyxlhq** [comment]
Hello,mgarbade. please help me. How to make URP Project achieve the same performance

**Comment by sxyxlhq** [comment]
Hello Homuler, please help me. How to make URP Project achieve the same performance

**Comment by sxyxlhq** [comment]
Hello Homuler, maybe I found the reason. 

> SetPixels32(textureBuffer.GetPixels32());

GetPixels32() create a array in the method "ReadTextureFromOnCPU" in "TextureFame.cs"

_textureBuffer is Texture2D, _texture is Texture2D too.

May I replace _textureBuffer by _texture ?
There will not need to get Color32 Array for _texture

**Comment by homuler** [comment]
I'm replacing the `TextureFrame` implementation for new Task APIs (and it is placed under `Packages/`), and I hope it will perform better than the old one.
https://github.com/homuler/MediaPipeUnityPlugin/blob/7252d53c1c0b23b5ae39cb4b44f97b2f5039f327/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Face%20Detection/FaceDetectorRunner.cs#L80
https://github.com/homuler/MediaPipeUnityPlugin/blob/7252d53c1c0b23b5ae39cb4b44f97b2f5039f327/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs#L138-L172

P.S. Feel free to use the scripts placed under `Assets/`, but please note that they were originally implemented without the intention of being used outside of this project (e.g. some I/Fs are distorted for the purpose of the sample).

**Comment by sxyxlhq** [comment]
Thank You for your reply.
