### ISSUE TITLE
Runtime Plugin folder for Android and iOS doesn't update automatically

### ISSUE THREAD

**Issue by HeiniHeo** [homuler/MediaPipeUnityPlugin#986]
### Plugin Version or Commit ID

v0.11.0

### Unity Version

2021.3.6f1

### Your Host OS

macOS Ventura 13.2.1

### Target Platform

Android, iOS

### Command Sequences

I'm building an application on Android or iOS through unity, but the plugin folders for Android and iOS doesn't build automatically.
The folders location is on "Packages > com.github.homuler.mediapipe > Runtime > Plugins > Android & iOS".
These folders are always existing, but the size of these folders are very small about 4~20bytes...

### Log

<img width="245" alt="Screenshot 2023-08-08 at 6 08 16 PM" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/80299773/c95502b2-c960-4dbc-ac93-91f07b83399e">

**Comment by homuler** [comment]
Specifically, what kind of problem do you want to solve?

**Comment by HeiniHeo** [comment]
Sorry for not being specific
When I build an app, I always face this 'mediapipe_jni' error
<img width="616" alt="Screenshot 2023-08-09 at 1 21 28 PM" src="https://github.com/homuler/MediaPipeUnityPlugin/assets/80299773/3e011ea6-55c1-4f85-a42b-e455d730e224">

How can I fix it?

**Comment by homuler** [comment]
This repository does not contain required libraries (in this case, `mediapipe_android.aar`).
Please see https://github.com/homuler/MediaPipeUnityPlugin#hammer_and_wrench-installation for more details.

If it's OK, I recommend you download `MediaPipeUnityPlugin-all.zip` from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.12.0) and build the app.
