### ISSUE TITLE
Android build streaming assets

### ISSUE THREAD

**Issue by TulgaTDev** [homuler/MediaPipeUnityPlugin#987]
### Description

Hello again, I've done everything on the standalone build, and everything works great. But now I want to convert my project to Android. built my android apk and looks like models are not included. How can I add streaming asset model files into apk?

**Comment by homuler** [comment]
See https://docs.unity3d.com/Manual/SpecialFolders.html .
Please ask questions about how to use Unity in a different location, such as Unity forum.
