### ISSUE TITLE
Selfie Segmentation, Android and iOS overheat

### ISSUE THREAD

**Issue by LoopIssuer** [homuler/MediaPipeUnityPlugin#993]
### Description

I'm using Selfie Segmentation (together with Agora SDK), everything works fine. Unfortunately, our client believes that the application overheats the phone (Android and iOS) too quickly (does not provide data) and users therefore resign from using it.
Is there anything that can be done to make the phones less hot and drain less battery?

Thanks in advance

**Comment by homuler** [comment]
With the given information, I can only provide a general response, so I will close the issue.
