### ISSUE TITLE
Unable to find version '1.11.1' of package 'Microsoft.Unity.Analyzers'. in DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json too many things

### ISSUE THREAD

**Issue by semi8583** [homuler/MediaPipeUnityPlugin#999]
### Plugin Version or Commit ID

v0.12.0

### Unity Version

2021.3.16f1

### Your Host OS

Window 11 WSL2 ubuntu 22.04.3 LTS

### Target Platform

Linux Standalone

### [Linux Only] GCC/G++ and GLIBC Version

ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.

### Command Sequences

set PYTHON_BIN_PATH=/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/env/bin/python

### Log

(env) semi@MotionB01:/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin$ python build.py build --desktop cpu -vv
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 0.282s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Runtime/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
### Unable to find version '1.11.1' of package 'Microsoft.Unity.Analyzers'.
Traceback (most recent call last):
  File "/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/build.py", line 470, in <module>
    Argument().command().run()
  File "/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/build.py", line 121, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nuget install -o .nuget -Source https://api.nuget.org/v3/index.json' returned non-zero exit status 1.

### Additional Context

(env) semi@MotionB01:/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin$ python build.py build --desktop cpu --opencv=cmake -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
INFO: Analyzed target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe_api:mediapipe_proto_srcs up-to-date:
  bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip
INFO: Elapsed time: 0.284s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG (build.py): Unarchiving 'bazel-bin/mediapipe_api/mediapipe_proto_srcs.zip' to 'build/Runtime/Scripts/Protobuf'...
INFO (build.py): Built protobuf sources
INFO (build.py): Downloading dlls...
DEBUG (build.py): Running `nuget install -o .nuget -Source https://api.nuget.org/v3/index.json`
Unable to find version '1.11.1' of package 'Microsoft.Unity.Analyzers'.
Traceback (most recent call last):
  File "/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/build.py", line 470, in <module>
    Argument().command().run()
  File "/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/build.py", line 121, in run
    self._run_command(self._build_proto_dlls_commands())
  File "/mnt/c/Users/JKKim/Downloads/MediaPipeUnityPlugin/build.py", line 56, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nuget install -o .nuget -Source https://api.nuget.org/v3/index.json' returned non-zero exit status 1.

**Comment by homuler** [comment]
Please download `MediaPipeUnityPlugin-all.zip` from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.12.0).
It includes all the required resources, so you don't need to build libraries.

P.S. you should not set `PYTHON_BIN_PATH` manually.

**Comment by semi8583** [comment]
Ohh my god.. then 
May i import into my project using MediaPipeUnityPlugin-all as commentd [import-into-your-project](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#import-into-your-project)

**Comment by semi8583** [comment]
i want to import mediapipeunity to my own project that fbx character move by webcam, is it perfect use for MediaPipeUnityPlugin-all.zip?

**Comment by homuler** [comment]
Then `com.github.homuler.mediapipe-0.12.0.tgz` or `MediaPipeUnity.0.12.0.unitypackage` would be better.

You can build them using `MediaPipeUnityPlugin-all.zip`, but if you don't need to test the sample app, you may just download those built packages.
